This notebook for finding best parmter on LSTM

This is to find best parm based on LSTM

#**Pre-request**

##Mount google drive

In [1]:
### **Mount** Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##Install pakages

In [2]:
#Install pakages
project_path = "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/"
!cat "{project_path}requirement/Install/NASEnhancedPretraindMLModleAdvance.txt"
!pip install  -r "{project_path}requirement/Install/NASEnhancedPretraindMLModleAdvance.txt" --no-cache-dir
%cd $project_path

torch
transformers
huggingface_hub
datasets
timm
patool
sktime
reformer_pytorch
optuna
ptflopsRequirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2.11.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (5.12.1)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.20.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (4.0.0)
Requirement already satisfied: timm in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 5)) (1.0.27)
Collecting patool (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 6))
  Downloading patool-4.0.5-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting sktime (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7))
  Downloading sktime-1.0.1-py3-none-any.whl.metadata (28 kB)
Collecting reformer_pytorch (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading reformer_pytorch-1.4.4-py3-none-any.whl.metadata (764 bytes)
Collecting optuna (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting ptflops (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 10))
  Downloading ptflops-0.7.5-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.29.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (0.28.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (0.70.16)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from timm->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 5)) (0.26.0+cu128)
Requirement already satisfied: joblib<1.6,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.5.3)
Collecting scikit-base<1.1.0,>=1.0.0 (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7))
  Downloading scikit_base-1.0.2-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: scikit-learn<1.8.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.6.1)
Requirement already satisfied: scipy<2.0.0,>=1.2 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.16.3)
Collecting axial-positional-embedding>=0.1.0 (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading axial_positional_embedding-0.3.12-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8)) (0.8.2)
Collecting local-attention (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading local_attention-1.11.2-py3-none-any.whl.metadata (929 bytes)
Collecting product-key-memory (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading product_key_memory-0.3.0-py3-none-any.whl.metadata (4.9 kB)
Collecting alembic>=1.5.0 (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9)) (2.0.51)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9)) (1.1.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.5.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.9.0.post0)

##Import  libs

In [3]:
# =====================================================
# 📦 Standard Library
# =====================================================
import os
import sys
import time
import logging
import hashlib
import shutil
import subprocess
import warnings
from datetime import datetime

# Start timer
start_time = time.time()

# =====================================================
# 🧮 Data & Visualization
# =====================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yaml

# Pandas display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# =====================================================
# ⚙️ Machine Learning - Scikit-learn
# =====================================================
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler
from sklearn.utils import class_weight
from sklearn.covariance import EmpiricalCovariance
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)

# =====================================================
# 🌲 XGBoost
# =====================================================
from xgboost import XGBClassifier
import joblib

# =====================================================
# 🔥 Deep Learning - PyTorch
# =====================================================
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from torch.cuda.amp import autocast

# =====================================================
# 🤖 Deep Learning - TensorFlow / Keras
# =====================================================
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Dense, Masking, Dropout, Layer
from tensorflow.keras.optimizers import Adam

# =====================================================
# 🤗 Transformers & Time Series
# =====================================================
from transformers import AutoModel
from sktime.datasets import load_from_tsfile_to_dataframe
# from mamba_ssm import Mamba  # Uncomment if needed

# =====================================================
# 🧠 Explainability
# =====================================================
import shap

# =====================================================
# 📊 Google Colab Specific
# =====================================================
from google.colab import data_table
data_table.enable_dataframe_formatter()
try:
    from google.colab import data_table
    data_table.enable_dataframe_formatter()
    data_table.DataTable.max_columns = 50
    data_table.DataTable.max_rows = 150
except ImportError:
    pass
from tqdm import tqdm

print("✅ All imports loaded successfully!")

✅ All imports loaded successfully!

##Confirmation setup

In [4]:
# =====================================================
# 🎲 Random Seeds (Reproducibility)
# =====================================================
!nvidia-smi                # confirm GPU
!pip show torch  # confirm versions
torch.manual_seed(42)
np.random.seed(42)

Thu Jul  9 10:28:13 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:00:05.0 Off |                    0 |
| N/A   34C    P0             56W /  400W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Name: torch
Version: 2.11.0+cu128
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org
Author:
Author-email: PyTorch Team <packages@pytorch.org>
License: BSD-3-Clause
Location: /usr/local/lib/python3.12/dist-packages
Requires: cuda-bindings, cuda-toolkit, filelock, fsspec, jinja2, networkx, nvidia-cudnn-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvshmem-cu12, setuptools, sympy, triton, typing-extensions
Required-by: accelerate, axial_positional_embedding, CoLT5-attention, fastai, hyper-connections, local-attention, peft, product_key_memory, ptflops, reformer-pytorch, sentence-transformers, timm, torch-einops-utils, torchdata, torchvision

## Enable Config

In [5]:

logger = logging.getLogger(__name__)

def load_config(config_path="configs/baseline.yaml"):
    """Load YAML config file and expand ${root_path} placeholders."""
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    logger.info(f"✅ Loaded config from {config_path}")

    # --- Expand ${root_path} placeholders ---
    root = config.get("root_path", "")

    def expand_paths(obj):
        if isinstance(obj, dict):
            return {k: expand_paths(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [expand_paths(i) for i in obj]
        elif isinstance(obj, str) and "${root_path}" in obj:
            return obj.replace("${root_path}", root)
        else:
            return obj

    config = expand_paths(config)
    return config
config = load_config(os.path.join(project_path, "configs", "baseline.yaml"))

## Set Variables

In [6]:


#limit = config['ML']['limit']

# ==========================================================
# UNIFIED HYPERPARAMETERS (Match TimesNet NAS Best)
# ==========================================================
# ==========================================================
# 🔧 UNIFIED HYPERPARAMETERS (Match TimesNet NAS Best)
# ==========================================================

# ----------------------------------------------------------
# 📏 Sequence Settings
# ----------------------------------------------------------
max_seq_len = 4                  # Maximum sequence length
recent_mode = False               # False → oldest mode, True → recent-window mode
nas_epochs = 20
n_trials_rf_xgb = 100




# ----------------------------------------------------------
# 📊 Evaluation Settings
# ----------------------------------------------------------
threshold = 0.5                   # Default classification threshold
opt_metric = "f1"                 # Optimization metric for model selection
early_stop_metric = 'val_accuracy'# Metric for early stopping
correlation_threshold = 0.85      # Feature correlation threshold


# ----------------------------------------------------------
# 💾 Paths
# ----------------------------------------------------------
model_path = config['ML']['models']

# ----------------------------------------------------------
# 🔄 Training State (Reset before each model)
# ----------------------------------------------------------
best_threshold = 0.5              # Best threshold (general)

# ==========================================================
# ✅ Configuration Summary
# ==========================================================
print("="*60)
print("📋 CONFIGURATION SUMMARY")
print("="*60)
print(f"  Sequence length:  {max_seq_len}")
print(f"  Mode:             {'Recent' if recent_mode else 'Oldest'}")
print(f"  Threshold:        {threshold}")
print(f"  Model path:       {model_path}")
print("="*60)

# Global unified results table for all models
results_table = pd.DataFrame(columns=["Round", "AUC", "Recall", "F1", "Model"])
summary = pd.DataFrame(
    columns=[
        "Model",
        "AUC",
        "Recall",
        "Precision",
        "F1",
        "threshold"
    ]
)

============================================================
📋 CONFIGURATION SUMMARY
============================================================
  Sequence length:  4
  Mode:             Oldest
  Threshold:        0.5
  Model path:       /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/models/
============================================================

##Split users level

In [7]:

# user_path = config['ML']['Events']['base_path'] + config['ML']['Events']['files']['user']
# df_user = pd.read_csv(user_path)
# print(f"✅ Loaded transactional user dataset: {df_user.shape}")



# # Aggregate to one row per user (max label = 1 if any fraud)
# user_labels = df_user.groupby("phone_no_m")["label"].max()
# print(f"👥 Unique users for splitting: {len(user_labels)}")

# # ==============================================================
# # 2️⃣ Create user-level split (stratified, no leakage)
# # ==============================================================

# fraud_users = user_labels[user_labels == 1].index
# normal_users = user_labels[user_labels == 0].index

# fraud_train, fraud_test = train_test_split(fraud_users, test_size=0.2, random_state=42)
# normal_train, normal_test = train_test_split(normal_users, test_size=0.2, random_state=42)

# train_users = set(fraud_train) | set(normal_train)
# test_users  = set(fraud_test)  | set(normal_test)

# # ==============================================================
# # 3️⃣ Save unified split (shared across LSTM / RF / XGB)
# # ==============================================================

# split_dir = "splits/shared_user_split_v1"
# os.makedirs(split_dir, exist_ok=True)

# pd.DataFrame({"phone_no_m": sorted(train_users)}).to_csv(f"{split_dir}/train_users.csv", index=False)
# pd.DataFrame({"phone_no_m": sorted(test_users)}).to_csv(f"{split_dir}/test_users.csv", index=False)

# # ==============================================================
# # 4️⃣ Summary
# # ==============================================================

# print("\n👥 Users Summary:")
# print(f"   Total : {len(user_labels):,}")
# print(f"   Fraud : {len(fraud_users):,} ({len(fraud_users)/len(user_labels)*100:.2f}%)")
# print(f"   Normal: {len(normal_users):,} ({len(normal_users)/len(user_labels)*100:.2f}%)")

# print("\n📂 Split saved to /splits/:")
# print(f"   Train users: {len(train_users)}")
# print(f"   Test  users: {len(test_users)}")
# print(f"   Fraud ratio train: {len(fraud_train)/len(train_users)*100:.2f}%")
# print(f"   Fraud ratio test : {len(fraud_test)/len(test_users)*100:.2f}%")

## Helpers

### evaluate_global

In [8]:
def evaluate_global(model, X_test, y_test, model_name="Model", threshold=0.5):
    """
    Generic evaluator for both classic ML models and neural networks.
    """
    print(f"\n📊 Evaluation threshold is: {threshold}")

    # ---- Predict probabilities ----
    if hasattr(model, "predict_proba"):
        # For sklearn-style models
        y_pred_prob = model.predict_proba(X_test)[:, 1]
    else:
        # For neural nets (e.g., Keras)
        preds = model.predict(X_test)
        if preds.shape[-1] == 2:
            # 2-class softmax output
            y_pred_prob = preds[:, 1]
        else:
            # Single sigmoid output
            y_pred_prob = preds.ravel()

    # ... rest of function unchanged
    # ---- Predict classes ----
    y_pred = (y_pred_prob > threshold).astype(int)

    # ---- Metrics ----
    auc = roc_auc_score(y_test, y_pred_prob)
    #recall = recall_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred, zero_division=0)

    precision = precision_score(y_test, y_pred, zero_division=0)
    #f1 = f1_score(y_test, y_pred)
    f1     = f1_score(y_test, y_pred, zero_division=0)

    report = classification_report(y_test, y_pred, digits=4)
    cm = confusion_matrix(y_test, y_pred)

    # ---- Display ----
    print(f"\n📊 Classification Report — {model_name}")
    print(report)
    print(f"AUC: {auc:.4f} | Recall: {recall:.4f} | Precision: {precision:.4f} | F1: {f1:.4f}")

    # ---- Confusion Matrix ----
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Normal (0)", "Fraud (1)"])
    disp.plot(cmap="Blues")
    plt.title(f"Confusion Matrix — {model_name}")
    plt.grid(False)
    plt.show()

    # ---- Summary Dictionary ----
    return {
        "Model": model_name,
        "AUC": auc,
        "Recall": recall,
        "Precision": precision,
        "F1": f1,
        "threshold": threshold
    }

### append_to_summary

In [9]:

def append_to_summary(summary, model_name, results):
    """
    Appends or updates the summary table with model results.
    Works with both capitalized and lowercase keys automatically.
    """
    # ✅ Create summary DataFrame if missing
    if summary is None or not isinstance(summary, pd.DataFrame):
          summary = pd.DataFrame(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])
    # Ensure "Model" column exists (prevents KeyError)
    if "Model" not in summary.columns:
        summary = pd.DataFrame(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])

    # ✅ Normalize key names to lowercase
    results = {k.lower(): v for k, v in results.items()}

    # ✅ Remove any existing row for the same model
    summary = summary[summary["Model"] != model_name]

    # ✅ Add new row (robust to missing values)
    row = {
        "Model": model_name,
        "AUC": round(results.get("auc", np.nan), 4) if not pd.isna(results.get("auc", np.nan)) else np.nan,
        "Recall": round(results.get("recall", np.nan), 4) if not pd.isna(results.get("recall", np.nan)) else np.nan,
        "Precision": round(results.get("precision", np.nan), 4) if not pd.isna(results.get("precision", np.nan)) else np.nan,
        "F1": round(results.get("f1", np.nan), 4) if not pd.isna(results.get("f1", np.nan)) else np.nan,
        "Threshold": round(results.get("threshold", np.nan), 4) if not pd.isna(results.get("threshold", np.nan)) else np.nan
    }


    # ✅ Append and reindex
    summary = pd.concat([summary, pd.DataFrame([row])], ignore_index=True)
    summary = summary.reindex(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])
    return summary

### find_best_threshold

In [10]:
def find_best_threshold(y_true, probs, low=0.2, high=0.8, n=61):
    best_f1 = -1.0
    best_thr = 0.5
    for thr in np.linspace(low, high, n):
        preds = (probs >= thr).astype(int)
        f1 = f1_score(y_true, preds, zero_division=0)
        if f1 > best_f1:
            best_f1 = f1
            best_thr = thr
    return best_thr, best_f1


def get_timesnet_val_threshold(results_dir):
    val_prob_path = os.path.join(results_dir, "val_prob.npy")
    val_true_path = os.path.join(results_dir, "val_true.npy")

    if not os.path.exists(val_prob_path) or not os.path.exists(val_true_path):
        raise FileNotFoundError(
            f"Missing validation probability files in {results_dir}. "
            f"Expected val_prob.npy and val_true.npy"
        )

    val_probs = np.load(val_prob_path)
    val_true = np.load(val_true_path)

    best_thr, best_f1 = find_best_threshold(val_true, val_probs)
    return best_thr, best_f1

###Drop and select features

In [11]:
def prepare_features(df):
    """
    Selects only the explicitly defined features for model training.
    You control which features are used by editing 'selected_features' below.
    """

    # --- Define selected features manually ---
    selected_features = [
        "window_size", "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
       "voc_avg_duration", "voc_max_duration", "voc_std_duration", "voc_active_days",
       "voc_active_hours", "sms_total_msgs", "sms_unique_contacts", "sms_active_hours",
       "sms_calltype_ratio", "app_months_active", "app_total_flow", "app_avg_flow",
       "app_std_flow", "app_unique_apps_mean", "app_unique_apps_max", "user_months_active",
        "arpu_mean", "arpu_std", "arpu_max", "idcard_cnt", "snapshot_round"
   ]
  #  selected_features = [
   #     "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
    #   "voc_avg_duration", "voc_max_duration", "voc_std_duration", "voc_active_days",
     # "voc_active_hours", "sms_total_msgs", "sms_unique_contacts", "sms_active_hours",
     #"sms_calltype_ratio", "idcard_cnt"
    #]
   # selected_features = [
    #    "voc_active_days",
    #"voc_active_hours",
    #"voc_unique_contacts",
    #"sms_calltype_ratio",
    #"sms_active_hours" ]


    # ✅ You can manually remove or comment out features here
    # For example:
    # selected_features = [f for f in selected_features if not (f.startswith("app_") or f.startswith("arpu_"))]

    # --- Keep only existing columns ---
    available = [f for f in selected_features if f in df.columns]
    missing = [f for f in selected_features if f not in df.columns]

    X = df[available].copy()

    #print(f"\n📊 Final features used ({len(available)}): {available}")
    if missing:
        print(f"⚠️ Missing columns not found in data: {missing}")

    return X

### Compare

In [12]:

def plot_progressive_results(
    results_table,
    metrics=("AUC", "Recall", "F1"),
    round_col=None,
    figsize=(14, 6)
):
    """
    Plot progressive evaluation metrics per round for multiple models.

    Parameters
    ----------
    results_table : pd.DataFrame
        Must contain columns: Model, metrics, and either Round or input_size
    metrics : tuple
        Metrics to plot (default: AUC, Recall, F1)
    round_col : str or None
        Column name for x-axis. If None, auto-detects.
    figsize : tuple
        Figure size for plots
    """

    # --------------------------------------------------
    # Auto-detect round column
    # --------------------------------------------------
    if round_col is None:
        if "Round" in results_table.columns:
            round_col = "Round"
        elif "input_size" in results_table.columns:
            round_col = "input_size"
        else:
            raise ValueError("No Round or input_size column found.")

    # --------------------------------------------------
    # Sort results (important for correct curves)
    # --------------------------------------------------
    results_table = results_table.sort_values(
        by=[round_col, "Model"],
        ascending=True
    ).reset_index(drop=True)


    # --------------------------------------------------
    # Plot each metric
    # --------------------------------------------------
    for metric in metrics:

        plt.figure(figsize=figsize)

        for model in results_table["Model"].unique():
            subset = (
                results_table[results_table["Model"] == model]
                .sort_values(by=round_col)
            )

            plt.plot(
                subset[round_col],
                subset[metric],
                marker="o",
                markersize=6,
                linewidth=2,
                label=model,
                alpha=0.85
            )

        plt.title(f"{metric} per {round_col}", fontsize=18)
        plt.xlabel(round_col, fontsize=14)
        plt.ylabel(metric, fontsize=14)
        plt.grid(True, linestyle="--", alpha=0.4)

        # Legend outside
        plt.legend(
            loc="upper center",
            bbox_to_anchor=(0.5, -0.12),
            ncol=4,
            fontsize=10
        )

        plt.tight_layout(rect=[0, 0.1, 1, 1])
        plt.show()
    display(results_table)

    return results_table

###get_key_rounds

In [13]:
# ============================================================
# 🔬 SCIENTIFIC KEY ROUNDS SELECTION
# ============================================================

def get_key_rounds(max_seq_len, method="linear", n_points=5):
    """
    Generate scientifically meaningful evaluation checkpoints.

    Args:
        max_seq_len: Maximum sequence length (16, 100, 300, etc.)
        method: Selection strategy
            - "linear": Equal spacing (1, 25%, 50%, 75%, 100%)
            - "logarithmic": More points early (where changes happen fast)
            - "sqrt": Square root spacing (balanced)
            - "percentile": Fixed percentages
        n_points: Number of evaluation points (default 5)

    Returns:
        List of round numbers to evaluate
    """

    if max_seq_len <= n_points:
        # If sequence is short, evaluate all rounds
        return list(range(1, max_seq_len + 1))

    if method == "linear":
        # Equal spacing: 1, 25%, 50%, 75%, 100%
        rounds = np.linspace(1, max_seq_len, n_points)

    elif method == "logarithmic":
        # More points early (fraud detection often shows early signal)
        # Log scale: 1, 2, 4, 8, 16 style
        rounds = np.logspace(0, np.log10(max_seq_len), n_points)

    elif method == "sqrt":
        # Square root spacing (balanced between linear and log)
        rounds = np.square(np.linspace(1, np.sqrt(max_seq_len), n_points))

    elif method == "percentile":
        # Fixed percentages: 1st event, 10%, 25%, 50%, 75%, 100%
        percentages = [0, 0.1, 0.25, 0.5, 0.75, 1.0]
        rounds = [max(1, int(p * max_seq_len)) for p in percentages]
        return sorted(set(rounds))  # Remove duplicates

    elif method == "early_focus":
        # Focus on early detection (more points in first half)
        # Useful for fraud detection where early signal matters
        early = np.linspace(1, max_seq_len * 0.5, n_points - 2)
        late = [max_seq_len * 0.75, max_seq_len]
        rounds = np.concatenate([early, late])

    else:
        raise ValueError(f"Unknown method: {method}")

    # Convert to integers, ensure valid range, remove duplicates
    rounds = [int(round(r)) for r in rounds]
    rounds = [max(1, min(r, max_seq_len)) for r in rounds]
    rounds = sorted(set(rounds))

    # Always include 1 and max_seq_len
    if 1 not in rounds:
        rounds = [1] + rounds
    if max_seq_len not in rounds:
        rounds = rounds + [max_seq_len]

    return rounds

##key_rounds = get_key_rounds(max_seq_len, method=method, n_points=n_points)
##print(f"📊 Evaluating rounds: {key_rounds}")
#print(f"   Total: {len(key_rounds)} rounds instead of {max_seq_len}")

#ML Modules

### Feature Importance

In [14]:
# def plot_feature_importance(model, X_train, model_name="Model", top_n=20):
#     """
#     Plot feature importance for tree-based models (XGBoost, RandomForest).
#     """


#     # Handle model type
#     if hasattr(model, "get_booster"):  # XGBoost
#         importance = model.get_booster().get_score(importance_type='gain')
#         fi = pd.DataFrame({
#             'Feature': list(importance.keys()),
#             'Importance': list(importance.values())
#         })
#     elif hasattr(model, "feature_importances_"):  # RandomForest
#         fi = pd.DataFrame({
#             'Feature': X_train.columns,
#             'Importance': model.feature_importances_
#         })
#     else:
#         raise ValueError(f"{model_name} does not support feature importance extraction.")

#     # Sort and plot
#     fi = fi.sort_values(by='Importance', ascending=False)
#     display(fi.head(10))

#     plt.figure(figsize=(10,6))
#     plt.barh(fi['Feature'][:top_n][::-1], fi['Importance'][:top_n][::-1])
#     plt.title(f'📊 {model_name} Feature Importance (Top {top_n})')
#     plt.xlabel('Importance')
#     plt.ylabel('Feature')
#     plt.grid(alpha=0.4)
#     plt.tight_layout()
#     plt.show()

#     return fi

# fi_xgb = plot_feature_importance(xgb_model, snap_X_train, "XGBoost")
# fi_rf = plot_feature_importance(rf_model, snap_X_train, "Random Forest")

### Load

In [15]:
def load_raw_datasets(config):


    if "ML" in config and "Events" in config["ML"]:
        events_cfg = config["ML"]["Events"]
    else:
        events_cfg = config["Events"]

    base = events_cfg["base_path"]
    files = events_cfg["files"]

    # --- Load all datasets ---
    df_voc = pd.read_csv(os.path.join(base, files["voc"]))
    df_sms = pd.read_csv(os.path.join(base, files["sms"]))
    df_app = pd.read_csv(os.path.join(base, files["app"]))
    df_user = pd.read_csv(os.path.join(base, files["user"]))

    # --- Normalize timestamps and add source column ---
    for df, src in [(df_voc, "VOC"), (df_sms, "SMS"), (df_app, "APP"), (df_user, "USER")]:
        df["source"] = src
        ts_col = [c for c in df.columns if "time" in c.lower()][0]
        df.rename(columns={ts_col: "event_time"}, inplace=True)
        df["event_time"] = pd.to_datetime(df["event_time"], errors="coerce")

    print("✅ Raw datasets loaded and timestamp-normalized.")
    return df_voc, df_sms, df_app, df_user

df_voc, df_sms, df_app, df_user = load_raw_datasets(config)

✅ Raw datasets loaded and timestamp-normalized.

### Build timeline (events)

In [16]:
def merge_and_prepare_events(df_voc, df_sms, df_app, df_user):

    # --- 1️⃣ Normalize USER dataset ---
    if 'label' not in df_user.columns:
        raise KeyError("❌ 'label' column not found in user dataset")

    # Ensure numeric consistency
    df_user['label'] = df_user['label'].fillna(0).astype(int)
    df_user['idcard_cnt'] = df_user['idcard_cnt'].fillna(0).astype(float)
    df_user['arpu_value'] = df_user['arpu_value'].fillna(0).astype(float)

    # --- 2️⃣ Extract static info for merging (label + sim count only) ---
    #static_user_info = df_user.groupby("phone_no_m", as_index=False)[["label", "idcard_cnt"]].max()
    # --- 2️⃣ Extract static info from the RAW user table (covers all 6,106 users) ---
    lbl_cfg = config["ML"]["labels"]
    raw_user = pd.read_csv(os.path.join(lbl_cfg["base_path"], lbl_cfg["file"]))
    static_user_info = raw_user[["phone_no_m", "label", "idcard_cnt"]].drop_duplicates("phone_no_m")
    static_user_info["label"] = static_user_info["label"].astype(int)
    static_user_info["idcard_cnt"] = static_user_info["idcard_cnt"].fillna(0).astype(float)

    # --- 3️⃣ Merge static info into other event tables ---
    df_voc = df_voc.merge(static_user_info, on="phone_no_m", how="left")
    df_sms = df_sms.merge(static_user_info, on="phone_no_m", how="left")
    df_app = df_app.merge(static_user_info, on="phone_no_m", how="left")


    # --- 4️⃣ Combine all transactional event sources ---
    # include df_user itself since arpu_value is event-like
    events = pd.concat([df_voc, df_sms, df_app, df_user], ignore_index=True)

    # --- 5️⃣ Fill and order ---
    #events["label"] = events["label"].fillna(0).astype(int)
    missing = int(events["label"].isna().sum())
    assert missing == 0, f"{missing} events have no label — label merge is broken"
    events["label"] = events["label"].astype(int)

    events["event_time"] = pd.to_datetime(events["event_time"], errors="coerce")
    events = events.sort_values(["phone_no_m", "event_time"]).reset_index(drop=True)

    # --- 6️⃣ Summary ---
    print("\n🔎 Feature Summary per Source:")
    for src, df in [("VOC", df_voc), ("SMS", df_sms), ("APP", df_app), ("USER", df_user)]:
        print(f"\n📂 Source: {src}")
        print(f"   Events: {len(df):,}")
        print(f"   Users : {df['phone_no_m'].nunique():,}")
        print(f"   Columns ({len(df.columns)}): {', '.join(df.columns)}")

    print("\n📊 Combined Dataset Summary:")
    print(f"   Total events: {len(events):,}")
    print(f"   Unique users: {events['phone_no_m'].nunique():,}")
    print(f"   Fraud ratio: {events['label'].mean()*100:.2f}%")
    user_labels = events.groupby("phone_no_m")["label"].max()
    print(f"   Fraud users: {int(user_labels.sum()):,} / {user_labels.size:,} ({user_labels.mean()*100:.2f}%)")

    return events

events = merge_and_prepare_events(df_voc, df_sms, df_app, df_user)

display(events.head())

🔎 Feature Summary per Source:

📂 Source: VOC
   Events: 5,015,430
   Users : 6,025
   Columns (11): phone_no_m, opposite_no_m, calltype_id, event_time, call_dur, city_name, county_name, imei_m, source, label, idcard_cnt

📂 Source: SMS
   Events: 6,848,509
   Users : 6,103
   Columns (7): phone_no_m, opposite_no_m, calltype_id, event_time, source, label, idcard_cnt

📂 Source: APP
   Events: 3,283,602
   Users : 6,106
   Columns (10): phone_no_m, event_time, source, busi_name, flow, month_id, flow_norm, month_str, label, idcard_cnt

📂 Source: USER
   Events: 39,454
   Users : 5,929
   Columns (10): phone_no_m, event_time, source, month_id, arpu_value, city_name, county_name, idcard_cnt, label, month_col

📊 Combined Dataset Summary:
   Total events: 15,186,995
   Unique users: 6,106
   Fraud ratio: 24.63%
   Fraud users: 1,962 / 6,106 (32.13%)

,phone_no_m,opposite_no_m,calltype_id,event_time,call_dur,city_name,county_name,imei_m,source,label,idcard_cnt,busi_name,flow,month_id,flow_norm,month_str,arpu_value,month_col
0,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-13 16:21:53,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-13 16:21:53,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Split data based on users (fraud, not fraud)

In [17]:


# ======================================
# Clean Numeric Columns
# ======================================
events = events.copy()
numeric_cols = events.select_dtypes(include=["number"]).columns.difference(["label"])

# Replace NaN with 0 for numeric fields (avoids scaling issues)
events[numeric_cols] = events[numeric_cols].fillna(0)

print(f"\n📊 Numeric columns to scale ({len(numeric_cols)}): {numeric_cols.tolist()}")


# ======================================
# 2 Create / Load Shared Train-Val-Test User Split
# ======================================
split_dir = os.path.join(config["root_path"], "splits", "shared_user_split_v1")
train_split_file = f"{split_dir}/train_users.csv"
test_split_file  = f"{split_dir}/test_users.csv"
val_split_file   = f"{split_dir}/val_users.csv"

os.makedirs(split_dir, exist_ok=True)

all_split_files_exist = (
    os.path.exists(train_split_file)
    and os.path.exists(test_split_file)
    and os.path.exists(val_split_file)
)

if all_split_files_exist:
    print("📂 Using shared user split files...")
    train_users = set(pd.read_csv(train_split_file)["phone_no_m"])
    test_users  = set(pd.read_csv(test_split_file)["phone_no_m"])
    val_users   = set(pd.read_csv(val_split_file)["phone_no_m"])
else:
    print("🆕 Creating shared train/test/val user split...")

    # One label per user
    user_labels = events.groupby("phone_no_m")["label"].max()
    fraud_users = user_labels[user_labels == 1].index
    normal_users = user_labels[user_labels == 0].index

    # 1) Train/Test split (split fraud user %)
    fraud_train, fraud_test = train_test_split(
        fraud_users, test_size=0.2, random_state=42
    )
    normal_train, normal_test = train_test_split(
        normal_users, test_size=0.2, random_state=42
    )

    train_users_full = set(fraud_train) | set(normal_train)
    test_users = set(fraud_test) | set(normal_test)

    # 2) Validation split from training users only
    train_user_labels = user_labels.loc[list(train_users_full)]

    fraud_train_users = train_user_labels[train_user_labels == 1].index
    normal_train_users = train_user_labels[train_user_labels == 0].index

    fraud_tr, fraud_val = train_test_split(
        fraud_train_users, test_size=0.2, random_state=42
    )
    normal_tr, normal_val = train_test_split(
        normal_train_users, test_size=0.2, random_state=42
    )

    train_users = set(fraud_tr) | set(normal_tr)
    val_users   = set(fraud_val) | set(normal_val)

    pd.DataFrame({"phone_no_m": sorted(train_users)}).to_csv(train_split_file, index=False)
    pd.DataFrame({"phone_no_m": sorted(test_users)}).to_csv(test_split_file, index=False)
    pd.DataFrame({"phone_no_m": sorted(val_users)}).to_csv(val_split_file, index=False)

    print(f"✅ Saved shared split files to '{split_dir}/'")
# ======================================
# Split overlap checks
# ======================================
assert len(train_users & test_users) == 0, "❌ User leakage: train and test overlap"
assert len(train_users & val_users) == 0, "❌ User leakage: train and val overlap"
assert len(test_users & val_users) == 0, "❌ User leakage: test and val overlap"

print("🔒 Split overlap checks passed:")
print(f"   train ∩ test = {len(train_users & test_users)}")
print(f"   train ∩ val  = {len(train_users & val_users)}")
print(f"   test  ∩ val  = {len(test_users & val_users)}")
user_labels = events.groupby("phone_no_m")["label"].max()
print(f"   sizes  train/val/test = {len(train_users)} / {len(val_users)} / {len(test_users)}")
print(f"   fraud  train/val/test = {int(user_labels.loc[list(train_users)].sum())} / "
      f"{int(user_labels.loc[list(val_users)].sum())} / {int(user_labels.loc[list(test_users)].sum())}")
# ======================================
# Apply Split to Events
# ======================================
train_events = events[events["phone_no_m"].isin(train_users)]
test_events  = events[events["phone_no_m"].isin(test_users)]
val_events = events[events["phone_no_m"].isin(val_users)]

# Sanity checks
assert len(set(train_events["phone_no_m"]) & set(test_events["phone_no_m"])) == 0, "❌ User leakage detected!"
assert train_events["label"].nunique() == 2, "❌ Training set must contain both classes"
assert test_events["label"].nunique() == 2, "❌ Test set must contain both classes"

# --- add time gap, scaled featur ---
# for name, df in [('train_events', train_events), ('test_events', test_events)]:
#     df = df.copy()  # avoid SettingWithCopyWarning
#     df['event_time'] = pd.to_datetime(df['event_time'])
#     #df.sort_values(['phone_no_m', 'event_time'], inplace=True)
#     df = df.sort_values(['phone_no_m', 'event_time'], kind='mergesort').reset_index(drop=True)
#     df['dt_hours'] = df.groupby('phone_no_m')['event_time'].diff().dt.total_seconds() / 3600
#     df['dt_hours'] = df['dt_hours'].fillna(0)
#     df['dt_hours'] = np.log1p(df['dt_hours'])  # normalize gaps
#     if name == 'train_events':
#         train_events = df
#     else:
#         test_events = df
for name, df in [
    ('train_events', train_events),
    ('val_events', val_events),
    ('test_events', test_events)
]:
    df = df.copy()
    df['event_time'] = pd.to_datetime(df['event_time'])
    df = df.sort_values(['phone_no_m', 'event_time'], kind='mergesort').reset_index(drop=True)
    df['dt_hours'] = df.groupby('phone_no_m')['event_time'].diff().dt.total_seconds() / 3600
    df['dt_hours'] = df['dt_hours'].fillna(0)
    df['dt_hours'] = np.log1p(df['dt_hours'])

    if name == 'train_events':
        train_events = df
    elif name == 'val_events':
        val_events = df
    else:
        test_events = df


# Store unscaled events BEFORE line 895
train_events_unscaled = train_events.copy()
test_events_unscaled = test_events.copy()
val_events_unscaled = val_events.copy()


# Sanity checks
assert len(set(train_events["phone_no_m"]) & set(test_events["phone_no_m"])) == 0, "❌ User leakage detected!"
assert train_events["label"].nunique() == 2, "❌ Training set must contain both classes"
assert test_events["label"].nunique() == 2, "❌ Test set must contain both classes"
scale_cols_seq = sorted(set(train_events.select_dtypes(include=["number"]).columns) - {"label"})
scaler_seq = StandardScaler().fit(train_events[scale_cols_seq])
train_events[scale_cols_seq] = scaler_seq.transform(train_events[scale_cols_seq])
test_events[scale_cols_seq]  = scaler_seq.transform(test_events[scale_cols_seq])
val_events[scale_cols_seq]   = scaler_seq.transform(val_events[scale_cols_seq])

# ======================================
# 4️⃣ snapshot
# ======================================

# ======================================
# 4️⃣ Create Sequences (using multiple features)
# ======================================
numeric_features = [c for c in numeric_cols if c not in ["label"]]  # exclude label
if 'dt_hours' in train_events.columns:
    numeric_features.append('dt_hours')
print(f"\n📦 Features used for sequences: {numeric_features}")
feature_cols_tf = numeric_features.copy()
# 👉 Transformer feature columns: same numeric features as LSTM + source_id

if "source_id" not in feature_cols_tf:
    feature_cols_tf.append("source_id")

print("[Transformer] feature_cols_tf:", feature_cols_tf)

📊 Numeric columns to scale (6): ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt']
📂 Using shared user split files...
🔒 Split overlap checks passed:
   train ∩ test = 0
   train ∩ val  = 0
   test  ∩ val  = 0
   sizes  train/val/test = 3907 / 977 / 1222
   fraud  train/val/test = 1255 / 314 / 393

📦 Features used for sequences: ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt', 'dt_hours']
[Transformer] feature_cols_tf: ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt', 'dt_hours', 'source_id']

### Generate_snapshots_from_events

In [18]:
# ============================================================
# 🔧 OPTIMIZED SNAPSHOT GENERATION FROM EVENTS (FIXED)
# ============================================================

def generate_snapshots_from_events(
    events_df,
    users,
    r,
    max_seq_len,
    recent_mode=True
):
    """
    Generate snapshot features from events DataFrame.
    OPTIMIZED: Uses groupby instead of per-user filtering.
    """

    # 1️⃣ Filter to relevant users FIRST (huge speedup)
    events_filtered = events_df[events_df["phone_no_m"].isin(users)].copy()

    if events_filtered.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    # 2️⃣ Sort once
    events_filtered = events_filtered.sort_values(["phone_no_m", "event_time"])

    # 3️⃣ Apply selection logic per user using groupby
    def select_events(df_u):
        if recent_mode:
            df_u = df_u.tail(max_seq_len).head(r)
        else:
            df_u = df_u.head(r)
        return df_u

    selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)

    if selected.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    # 4️⃣ Aggregate features using groupby
    snapshot_rows = []

    for user, df_u in tqdm(selected.groupby("phone_no_m"), desc="Generating snapshots"):
    #for user, df_u in selected.groupby("phone_no_m"):
        row = {"phone_no_m": user}

        # Get label
        label = int(df_u["label"].max()) if "label" in df_u.columns else 0

        # --- Voice Features ---
        voc = df_u[df_u["source"] == "VOC"]
        if len(voc) > 0:
            if "call_dur" in voc.columns:
                call_dur = pd.to_numeric(voc["call_dur"], errors="coerce").fillna(0)
            else:
                call_dur = pd.Series([0])

            row["voc_total_calls"] = len(voc)
            row["voc_unique_contacts"] = voc["opposite_no_m"].nunique() if "opposite_no_m" in voc.columns else 0
            row["voc_total_duration"] = call_dur.sum()
            row["voc_avg_duration"] = call_dur.mean()
            row["voc_max_duration"] = call_dur.max()
            row["voc_std_duration"] = call_dur.std() if len(call_dur) > 1 else 0
            row["voc_active_days"] = voc["event_time"].dt.weekday.nunique()
            row["voc_active_hours"] = voc["event_time"].dt.hour.nunique()
        else:
            row.update({
                "voc_total_calls": 0, "voc_unique_contacts": 0, "voc_total_duration": 0,
                "voc_avg_duration": 0, "voc_max_duration": 0, "voc_std_duration": 0,
                "voc_active_days": 0, "voc_active_hours": 0
            })

        # --- SMS Features ---
        sms = df_u[df_u["source"] == "SMS"]
        if len(sms) > 0:
            row["sms_total_msgs"] = len(sms)
            row["sms_unique_contacts"] = sms["opposite_no_m"].nunique() if "opposite_no_m" in sms.columns else 0
            row["sms_active_hours"] = sms["event_time"].dt.hour.nunique()
            if "calltype_id" in sms.columns:
                calltype = pd.to_numeric(sms["calltype_id"], errors="coerce")
                row["sms_calltype_ratio"] = (calltype == 1).mean()
            else:
                row["sms_calltype_ratio"] = 0
        else:
            row.update({
                "sms_total_msgs": 0, "sms_unique_contacts": 0,
                "sms_active_hours": 0, "sms_calltype_ratio": 0
            })

        # --- App Features ---
        app = df_u[df_u["source"] == "APP"]
        if len(app) > 0:
            if "flow" in app.columns:
                flow = pd.to_numeric(app["flow"], errors="coerce").fillna(0)
            else:
                flow = pd.Series([0])

            row["app_months_active"] = app["month_id"].nunique() if "month_id" in app.columns else 0
            row["app_total_flow"] = flow.sum()
            row["app_avg_flow"] = flow.mean()
            row["app_std_flow"] = flow.std() if len(flow) > 1 else 0
            row["app_unique_apps_mean"] = app["busi_name"].nunique() if "busi_name" in app.columns else 0
            row["app_unique_apps_max"] = app["busi_name"].nunique() if "busi_name" in app.columns else 0
        else:
            row.update({
                "app_months_active": 0, "app_total_flow": 0, "app_avg_flow": 0,
                "app_std_flow": 0, "app_unique_apps_mean": 0, "app_unique_apps_max": 0
            })

        # --- User/ARPU Features ---
        arpu = df_u[df_u["source"] == "USER"]
        if len(arpu) > 0:
            if "arpu_value" in arpu.columns:
                arpu_val = pd.to_numeric(arpu["arpu_value"], errors="coerce")
            else:
                arpu_val = pd.Series([0])

            row["user_months_active"] = arpu["month_id"].nunique() if "month_id" in arpu.columns else 0
            row["arpu_mean"] = arpu_val.mean()
            row["arpu_std"] = arpu_val.std() if len(arpu_val) > 1 else 0
            row["arpu_max"] = arpu_val.max()
            row["idcard_cnt"] = arpu["idcard_cnt"].max() if "idcard_cnt" in arpu.columns else 0
        else:
            row.update({
                "user_months_active": 0, "arpu_mean": 0, "arpu_std": 0,
                "arpu_max": 0, "idcard_cnt": 0
            })

        # Meta features
        row["window_size"] = r
        row["snapshot_round"] = r
        row["label"] = label

        snapshot_rows.append(row)

    # Build DataFrame
    df_snapshot = pd.DataFrame(snapshot_rows).fillna(0)

    if df_snapshot.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    y = df_snapshot["label"].values
    user_ids = df_snapshot["phone_no_m"].values
    X = df_snapshot.drop(columns=["phone_no_m", "label"])

    return X, y, user_ids

#  ▶ Classic Ml Snapshot based

###### Genrate input data

In [19]:

# ============================================================
# 📋 Define snapshot feature columns (same as sequencestreaming.py)
# ============================================================

SNAPSHOT_FEATURE_COLS = [
    # Voice
    "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
    "voc_avg_duration", "voc_max_duration", "voc_std_duration",
    "voc_active_days", "voc_active_hours",
    # SMS
    "sms_total_msgs", "sms_unique_contacts", "sms_active_hours", "sms_calltype_ratio",
    # App
    "app_months_active", "app_total_flow", "app_avg_flow",
    "app_std_flow", "app_unique_apps_mean", "app_unique_apps_max",
    # User / ARPU
    "user_months_active", "arpu_mean", "arpu_std", "arpu_max", "idcard_cnt",
    # Meta
    "window_size", "snapshot_round"
]

print(f"📊 Snapshot features: {len(SNAPSHOT_FEATURE_COLS)} columns")

# ============================================================
# 🚀 RF/XGBoost - UNIFIED PIPELINE (Uses same events as LSTM)
# ============================================================


print("\n" + "="*60)
print(f"[{datetime.now()}] 🌲 RF/XGBoost Training (from events, same as LSTM)")
print("="*60)

# ============================================================
# 1️⃣ Generate training snapshots (r = max_seq_len)
# ============================================================
print(f"\n[{datetime.now()}] 📊 Generating training snapshots (r={max_seq_len})...")

X_train_snap, y_train_snap, users_train_snap = generate_snapshots_from_events(
    events_df=train_events_unscaled,
    users=train_users,
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)
neg = (y_train_snap == 0).sum()
pos = (y_train_snap == 1).sum()
XGB_scale_pos_weight = neg / pos

print(f"[{datetime.now()}] ✅ Training snapshots: {len(X_train_snap)} users, {X_train_snap.shape[1]} features")

# ============================================================
# 2️⃣ Align columns and scale
# ============================================================
print(f"[{datetime.now()}] 🔄 Scaling...")
X_train_snap = X_train_snap.reindex(columns=SNAPSHOT_FEATURE_COLS, fill_value=0)
scaler_snap = StandardScaler().fit(X_train_snap)
X_train_scaled = scaler_snap.transform(X_train_snap)
print(f"[{datetime.now()}] ✅ Scaling done")

📊 Snapshot features: 25 columns

============================================================
[2026-07-09 10:31:32.552807] 🌲 RF/XGBoost Training (from events, same as LSTM)
============================================================

[2026-07-09 10:31:32.552895] 📊 Generating training snapshots (r=4)...

/tmp/ipykernel_1088/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 3907/3907 [00:11<00:00, 350.98it/s]

[2026-07-09 10:31:59.525778] ✅ Training snapshots: 3907 users, 25 features
[2026-07-09 10:31:59.526397] 🔄 Scaling...
[2026-07-09 10:31:59.531342] ✅ Scaling done

#### Show sample

In [20]:
# ============================================================
# 🔍 DEBUG: Print Sample Snapshots
# ============================================================

print("="*60)
print("🔍 SAMPLE SNAPSHOTS DEBUG")
print("="*60)

# Generate a small sample
X_sample, y_sample, users_sample = generate_snapshots_from_events(
    events_df=train_events_unscaled,
    users=list(train_users)[:10],  # Only 10 users for sample
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)

print(f"\n📊 Sample shape: {X_sample.shape}")
print(f"📊 Labels: {y_sample}")
print(f"📊 Users: {users_sample}")

# Show features
print(f"\n📋 Feature columns ({len(X_sample.columns)}):")
print(X_sample.columns.tolist())

# Show sample data
print(f"\n📊 Sample snapshots (first 5 users):")
sample_df = X_sample.copy()
sample_df['label'] = y_sample
sample_df['user'] = users_sample
sample_df = sample_df[['user', 'label'] + [c for c in sample_df.columns if c not in ['user', 'label']]]
display(sample_df.head())

# Show statistics
print(f"\n📈 Feature statistics:")
display(X_sample.describe().T)

# Show class distribution
print(f"\n📊 Class distribution:")
print(f"   Fraud (1): {sum(y_sample == 1)} ({sum(y_sample == 1)/len(y_sample)*100:.1f}%)")
print(f"   Normal (0): {sum(y_sample == 0)} ({sum(y_sample == 0)/len(y_sample)*100:.1f}%)")

============================================================
🔍 SAMPLE SNAPSHOTS DEBUG
============================================================

/tmp/ipykernel_1088/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 10/10 [00:00<00:00, 335.44it/s]

📊 Sample shape: (10, 25)
📊 Labels: [0 1 1 1 1 0 0 0 0 0]
📊 Users: ['34357bec7cb34c45041090307418572525dd36966fe2c509d62a40d4fcf396fe734dbcd8a8c426b941295835e311f5cb2dfcf2fc264616e176d9881bd0c23fef'
 '6bb165091808f8ff8c4ef98ad41df804e63e7cbe7670c2edcace5f9da30db0339e9d5a58c2532a29808d0adc78bf574dd62c9ee10eaf53adb958c03f3dc66d0f'
 '6c84db3037ddfb7b98646d026d8cf6ab42b696b92e19d6d02695b411da0348d886029415ba4aa102589b7051581867ed2104e7a9aab29eacca76b6b592db4dd4'
 '81023faf5cde8acd83b59766b88f659107e9057636475412f1ddf0aca4f75a35d20d0c8861f43e6e8a01522810a4b1416b3130ff96882ee30380aa6c65d8b1c9'
 '956ac7b1a212462e429be191b1589af42949dc4bcbd8129dcdab3705fe19146a07e1082de64a45ca47c976bc0c864cd54074b97a3b43e4c072e944d4eaa9f2c8'
 'b5e616747cd5f63e31b385a3dddcf41ed8c53406310e6553215dda8e11d64c9dad60b92f2cf3eaebf5d08f60eed26896c2e2c7f31a2438fe4dcf3cc0939bcd19'
 'db97a545f5e29bdc6c656f2c8ca698cdeb874e0aa2e5890e6aec000a0c7cc65c28533b6c368933a510e8ad5d2d4b77f3e65d5bac487a7dc65ad2e9e3bd9a1cfd'
 'f2699c378c246201f07fce780e57a60fff30a9d2d1d30f5550f85ee3d8d830f4772e3b0a16255fd433ddad830a1821d383f92b9bf030b67d3f757461ad1fc92e'
 'f80d6ed449d9325b97dbc44a52a2ed33267cca4212a5114639adc9141dfd0ada392da215c0bb5a7c016ac0adb8d4c49334519d57f7aa78897918881e5a8262ca'
 'feb3efbfb9fb727ac3dfd8f056e9d1f08767a9625ee0a43e954e5cd4ebd487971a036fc8d1fc9fcc1552a615d62a4cdf7ebaac2d5e3625390859465ea0bf0d08']

📋 Feature columns (25):
['voc_total_calls', 'voc_unique_contacts', 'voc_total_duration', 'voc_avg_duration', 'voc_max_duration', 'voc_std_duration', 'voc_active_days', 'voc_active_hours', 'sms_total_msgs', 'sms_unique_contacts', 'sms_active_hours', 'sms_calltype_ratio', 'app_months_active', 'app_total_flow', 'app_avg_flow', 'app_std_flow', 'app_unique_apps_mean', 'app_unique_apps_max', 'user_months_active', 'arpu_mean', 'arpu_std', 'arpu_max', 'idcard_cnt', 'window_size', 'snapshot_round']

📊 Sample snapshots (first 5 users):

,user,label,voc_total_calls,voc_unique_contacts,voc_total_duration,voc_avg_duration,voc_max_duration,voc_std_duration,voc_active_days,voc_active_hours,sms_total_msgs,sms_unique_contacts,sms_active_hours,sms_calltype_ratio,app_months_active,app_total_flow,app_avg_flow,app_std_flow,app_unique_apps_mean,app_unique_apps_max,user_months_active,arpu_mean,arpu_std,arpu_max,idcard_cnt,window_size,snapshot_round
0,34357bec7cb34c45041090307418572525dd36966fe2c5...,0,0,0,0.0,0.0,0.0,0.0,0,0,4,1,2,0.00,0,0,0,0,0,0,0,0,0,0,0,4,4
1,6bb165091808f8ff8c4ef98ad41df804e63e7cbe7670c2...,1,0,0,0.0,0.0,0.0,0.0,0,0,4,3,3,0.00,0,0,0,0,0,0,0,0,0,0,0,4,4
2,6c84db3037ddfb7b98646d026d8cf6ab42b696b92e19d6...,1,0,0,0.0,0.0,0.0,0.0,0,0,4,1,2,0.00,0,0,0,0,0,0,0,0,0,0,0,4,4
3,81023faf5cde8acd83b59766b88f659107e90576364754...,1,0,0,0.0,0.0,0.0,0.0,0,0,4,1,1,0.00,0,0,0,0,0,0,0,0,0,0,0,4,4
4,956ac7b1a212462e429be191b1589af42949dc4bcbd812...,1,0,0,0.0,0.0,0.0,0.0,0,0,4,3,3,0.25,0,0,0,0,0,0,0,0,0,0,0,4,4

📈 Feature statistics:

,count,mean,std,min,25%,50%,75%,max
voc_total_calls,10.0,0.800000,1.316561,0.0,0.0,0.0,1.500000,3.000000
voc_unique_contacts,10.0,0.500000,0.849837,0.0,0.0,0.0,0.750000,2.000000
voc_total_duration,10.0,34.100000,76.501924,0.0,0.0,0.0,32.250000,244.000000
voc_avg_duration,10.0,12.083333,25.693258,0.0,0.0,0.0,13.500000,81.333333
voc_max_duration,10.0,17.600000,38.361439,0.0,0.0,0.0,20.250000,122.000000
voc_std_duration,10.0,5.431926,11.812306,0.0,0.0,0.0,5.833631,37.541089
voc_active_days,10.0,0.300000,0.483046,0.0,0.0,0.0,0.750000,1.000000
voc_active_hours,10.0,0.600000,0.966092,0.0,0.0,0.0,1.500000,2.000000
sms_total_msgs,10.0,3.200000,1.316561,1.0,2.5,4.0,4.000000,4.000000
sms_unique_contacts,10.0,1.700000,0.948683,1.0,1.0,1.0,2.750000,3.000000
sms_active_hours,10.0,1.700000,0.823273,1.0,1.0,1.5,2.000000,3.000000
sms_calltype_ratio,10.0,0.025000,0.079057,0.0,0.0,0.0,0.000000,0.250000
app_months_active,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
app_total_flow,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
app_avg_flow,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
app_std_flow,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
app_unique_apps_mean,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
app_unique_apps_max,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
user_months_active,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
arpu_mean,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
arpu_std,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
arpu_max,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
idcard_cnt,10.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
window_size,10.0,4.000000,0.000000,4.0,4.0,4.0,4.000000,4.000000
snapshot_round,10.0,4.000000,0.000000,4.0,4.0,4.0,4.000000,4.000000

📊 Class distribution:
   Fraud (1): 4 (40.0%)
   Normal (0): 6 (60.0%)

### RF and XGB NAS

In [21]:
# ============================================================
# 🔧 PREPARE DATA FOR RF/XGB NAS
# ============================================================
import optuna
from optuna.samplers import TPESampler
# Number of trials (same as TimesNet/LSTM NAS)
# ============================================================
# 📊 Trial Logging (matches NAS TimesNet structure)
# ============================================================
rf_trial_log = []
best_rf_f1_so_far = -1.0
best_rf_trial_so_far = -1
ENQUEUED_RF_IDS = {0, 1, 2, 3}

xgb_trial_log = []
best_xgb_f1_so_far = -1.0
best_xgb_trial_so_far = -1
ENQUEUED_XGB_IDS = {0, 1, 2, 3}
print(f"\\n[{datetime.now()}] 📊 Generating test snapshots...")

X_test_snap, y_test_snap, users_test_snap = generate_snapshots_from_events(
    events_df=test_events_unscaled,
    users=test_users,
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)

X_test_snap = X_test_snap.reindex(columns=SNAPSHOT_FEATURE_COLS, fill_value=0)
X_test_scaled = scaler_snap.transform(X_test_snap)

print(f"[{datetime.now()}] ✅ Test snapshots: {len(X_test_snap)} users")

# Generate validation snapshots
print(f"\\n[{datetime.now()}] 📊 Generating validation snapshots...")

X_val_snap, y_val_snap, users_val_snap = generate_snapshots_from_events(
    events_df=val_events_unscaled,
    users=val_users,
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)

X_val_snap = X_val_snap.reindex(columns=SNAPSHOT_FEATURE_COLS, fill_value=0)
X_val_scaled = scaler_snap.transform(X_val_snap)

print(f"[{datetime.now()}] ✅ Validation snapshots: {len(X_val_snap)} users")

neg = (y_train_snap == 0).sum()
pos = (y_train_snap == 1).sum()
XGB_scale_pos_weight = neg / pos
print(f"   Class ratio → Normal: {neg}, Fraud: {pos}, scale_pos_weight: {XGB_scale_pos_weight:.2f}")

# Already computed above for XGB, reuse the same neg/pos
RF_class_weight = {
    0: 1.0,           # normal users — keep as 1
    1: neg / pos      # fraud users — same ratio as XGB
}
print(f"   RF class_weight: {RF_class_weight}")


# ============================================================
# 🌲 RANDOM FOREST NAS
# ============================================================

def rf_objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 500),
        "max_depth": trial.suggest_int("max_depth", 2, 20),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
    }

    model = RandomForestClassifier(**params, random_state=42, n_jobs=-1)
    model.fit(X_train_scaled, y_train_snap)

    val_probs  = model.predict_proba(X_val_scaled)[:, 1]
    test_probs = model.predict_proba(X_test_scaled)[:, 1]

    # --- Validation threshold + metrics ---
    best_val_thr, best_val_f1 = find_best_threshold(y_val_snap, val_probs)
    val_preds = (val_probs >= best_val_thr).astype(int)
    val_auc = roc_auc_score(y_val_snap, val_probs)
    val_recall = recall_score(y_val_snap, val_preds, zero_division=0)
    val_precision = precision_score(y_val_snap, val_preds, zero_division=0)

    # --- Test metrics using VALIDATION threshold ---
    test_preds = (test_probs >= best_val_thr).astype(int)
    test_f1 = f1_score(y_test_snap, test_preds, zero_division=0)
    test_auc = roc_auc_score(y_test_snap, test_probs)
    test_recall = recall_score(y_test_snap, test_preds, zero_division=0)
    test_precision = precision_score(y_test_snap, test_preds, zero_division=0)

    # --- Oracle test threshold (monitoring only) ---
    best_test_thr, best_test_f1_oracle = find_best_threshold(y_test_snap, test_probs)

    # --- Log trial ---
    global best_rf_f1_so_far, best_rf_trial_so_far
    if best_val_f1 > best_rf_f1_so_far:
        best_rf_f1_so_far = best_val_f1
        best_rf_trial_so_far = trial.number

    trial_row = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "time": datetime.now().strftime("%H:%M:%S"),
        "seq_length": max_seq_len,
        "trial_id": trial.number,
        "model": "RandomForest",

        # Validation
        "val_f1": round(best_val_f1, 4),
        "val_auc": round(val_auc, 4),
        "val_recall": round(val_recall, 4),
        "val_precision": round(val_precision, 4),

        # Parameters
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "min_samples_split": params["min_samples_split"],
        "min_samples_leaf": params["min_samples_leaf"],

        # Thresholds
        "val_threshold": round(best_val_thr, 3),
        "best_test_threshold": round(best_test_thr, 3),

        # Best tracking
        "best_val_so_far": round(best_rf_f1_so_far, 4),
        "best_trial_id": best_rf_trial_so_far,

        # Test (monitoring only)
        "test_f1": round(test_f1, 4),
        "test_auc": round(test_auc, 4),
        "test_recall": round(test_recall, 4),
        "test_precision": round(test_precision, 4),

        # Diagnostics
        "gap_val_test": round(best_val_f1 - test_f1, 4),
        "is_enqueued": trial.number in ENQUEUED_RF_IDS,
        "status": "OK",
    }
    rf_trial_log.append(trial_row)

    display(pd.DataFrame([trial_row]))

    return best_val_f1

    # Evaluate on TEST set (same as TimesNet NAS)
    #probs = model.predict_proba(X_test_scaled)[:, 1]

    # # Same threshold search as TimesNet/LSTM NAS
    # best_f1 = -1.0
    # for thr in np.linspace(0.2, 0.8, 61):
    #     pred = (probs >= thr).astype(int)
    #     f1 = f1_score(y_test_snap, pred, zero_division=0)
    #     if f1 > best_f1:
    #         best_f1 = f1

    # return best_f1


# ============================================================
# 🚀 XGBOOST NAS
# ============================================================

def xgb_objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 500),
        "max_depth": trial.suggest_int("max_depth", 2, 20),
        "learning_rate": trial.suggest_float("learning_rate", 0.001, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "gamma": trial.suggest_float("gamma", 0.0, 1.0),
        "patience": trial.suggest_int("patience", 2, 5),
    }

    patience = params.pop("patience")
    model = XGBClassifier(**params,early_stopping_rounds=patience, random_state=42, n_jobs=-1, eval_metric='logloss')

    model.fit(X_train_scaled, y_train_snap,eval_set=[(X_val_scaled, y_val_snap)], verbose=False)
    actual_trees = model.best_iteration if hasattr(model, "best_iteration") else params["n_estimators"]

    val_probs  = model.predict_proba(X_val_scaled)[:, 1]
    test_probs = model.predict_proba(X_test_scaled)[:, 1]

    # --- Validation threshold + metrics ---
    best_val_thr, best_val_f1 = find_best_threshold(y_val_snap, val_probs)
    val_preds = (val_probs >= best_val_thr).astype(int)
    val_auc = roc_auc_score(y_val_snap, val_probs)
    val_recall = recall_score(y_val_snap, val_preds, zero_division=0)
    val_precision = precision_score(y_val_snap, val_preds, zero_division=0)

    # --- Test metrics using VALIDATION threshold ---
    test_preds = (test_probs >= best_val_thr).astype(int)
    test_f1 = f1_score(y_test_snap, test_preds, zero_division=0)
    test_auc = roc_auc_score(y_test_snap, test_probs)
    test_recall = recall_score(y_test_snap, test_preds, zero_division=0)
    test_precision = precision_score(y_test_snap, test_preds, zero_division=0)

    # --- Oracle test threshold (monitoring only) ---
    best_test_thr, best_test_f1_oracle = find_best_threshold(y_test_snap, test_probs)

    # --- Log trial ---
    global best_xgb_f1_so_far, best_xgb_trial_so_far
    if best_val_f1 > best_xgb_f1_so_far:
        best_xgb_f1_so_far = best_val_f1
        best_xgb_trial_so_far = trial.number

    trial_row = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "time": datetime.now().strftime("%H:%M:%S"),
        "seq_length": max_seq_len,
        "trial_id": trial.number,
        "model": "XGBoost",

        # Validation
        "val_f1": round(best_val_f1, 4),
        "val_auc": round(val_auc, 4),
        "val_recall": round(val_recall, 4),
        "val_precision": round(val_precision, 4),

        # Parameters
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "learning_rate": params["learning_rate"],
        "subsample": params["subsample"],
        "colsample_bytree": params["colsample_bytree"],
        "min_child_weight": params["min_child_weight"],
        "gamma": params["gamma"],

        "actual_trees": actual_trees,
        "patience": patience,

        # Thresholds
        "val_threshold": round(best_val_thr, 3),
        "best_test_threshold": round(best_test_thr, 3),

        # Best tracking
        "best_val_so_far": round(best_xgb_f1_so_far, 4),
        "best_trial_id": best_xgb_trial_so_far,

        # Test (monitoring only)
        "test_f1": round(test_f1, 4),
        "test_auc": round(test_auc, 4),
        "test_recall": round(test_recall, 4),
        "test_precision": round(test_precision, 4),

        # Diagnostics
        "gap_val_test": round(best_val_f1 - test_f1, 4),
        "is_enqueued": trial.number in ENQUEUED_XGB_IDS,
        "status": "OK",
    }
    xgb_trial_log.append(trial_row)

    display(pd.DataFrame([trial_row]))

    return best_val_f1


# ============================================================
# 🔬 RUN NAS - RANDOM FOREST
# ============================================================

print("\\n" + "="*60)
print("🌲 RANDOM FOREST NAS")
print("="*60)

sampler_rf = TPESampler(
    n_startup_trials=10,
    n_ei_candidates=24,
    multivariate=True,
    seed=42
)

study_rf = optuna.create_study(
    direction="maximize",
    sampler=sampler_rf
    #pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=3)
)

study_rf.enqueue_trial({"n_estimators": 100, "max_depth": 10, "min_samples_split": 2, "min_samples_leaf": 1})
study_rf.enqueue_trial({"n_estimators": 500, "max_depth": 20, "min_samples_split": 2, "min_samples_leaf": 1})
study_rf.enqueue_trial({"n_estimators": 200, "max_depth":  5, "min_samples_split":10, "min_samples_leaf": 5})
study_rf.enqueue_trial({"n_estimators": 300, "max_depth": 12, "min_samples_split": 5, "min_samples_leaf": 2})


print(f"[{datetime.now()}] 🚀 Starting RF NAS ({n_trials_rf_xgb} trials)...")
study_rf.optimize(rf_objective, n_trials=n_trials_rf_xgb)

print("\\n" + "="*60)
print("🎉 RF NAS COMPLETE")
print("="*60)
print(f"Best Trial: {study_rf.best_trial.number}")
print(f"Best F1: {study_rf.best_value:.4f}")
print(f"Best Params: {study_rf.best_params}")


# ============================================================
# 🔬 RUN NAS - XGBOOST
# ============================================================

print("\\n" + "="*60)
print("🚀 XGBOOST NAS")
print("="*60)

sampler_xgb = TPESampler(
    n_startup_trials=10,
    n_ei_candidates=24,
    multivariate=True,
    seed=42
)

study_xgb = optuna.create_study(
    direction="maximize",
    sampler=sampler_xgb
    #pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=3)
)

study_xgb.enqueue_trial({"n_estimators": 100, "max_depth": 6, "learning_rate": 0.1,  "subsample": 1.0, "colsample_bytree": 1.0, "min_child_weight": 1, "gamma": 0.0, "patience": 3 })
study_xgb.enqueue_trial({"n_estimators": 500, "max_depth": 4, "learning_rate": 0.01, "subsample": 0.8, "colsample_bytree": 0.8, "min_child_weight": 3, "gamma": 0.1, "patience": 3 })
study_xgb.enqueue_trial({"n_estimators":  50, "max_depth": 8, "learning_rate": 0.3,  "subsample": 0.7, "colsample_bytree": 0.7, "min_child_weight": 1, "gamma": 0.0, "patience": 3 })
study_xgb.enqueue_trial({"n_estimators": 300, "max_depth": 3, "learning_rate": 0.05, "subsample": 0.6, "colsample_bytree": 0.6, "min_child_weight": 5, "gamma": 0.5, "patience": 3 })



print(f"[{datetime.now()}] 🚀 Starting XGB NAS ({n_trials_rf_xgb} trials)...")
study_xgb.optimize(xgb_objective, n_trials=n_trials_rf_xgb)

print("\\n" + "="*60)
print("🎉 XGB NAS COMPLETE")
print("="*60)
print(f"Best Trial: {study_xgb.best_trial.number}")
print(f"Best F1: {study_xgb.best_value:.4f}")
print(f"Best Params: {study_xgb.best_params}")


# ============================================================
# 📊 SAVE RESULTS
# ============================================================

# Save Optuna study results
OUT_DIR = os.path.join(config["output"]["results_dir"], "NAS_v2/")
os.makedirs(OUT_DIR, exist_ok=True)
study_rf.trials_dataframe().to_csv(f"{OUT_DIR}nas_rf_results_WL{max_seq_len}.csv", index=False)
study_xgb.trials_dataframe().to_csv(f"{OUT_DIR}nas_xgb_results_WL{max_seq_len}.csv", index=False)
pd.DataFrame(rf_trial_log).to_csv(f"{OUT_DIR}nas_rf_trial_log_WL{max_seq_len}.csv", index=False)
pd.DataFrame(xgb_trial_log).to_csv(f"{OUT_DIR}nas_xgb_trial_log_WL{max_seq_len}.csv", index=False)

print("💾 Saved: nas_rf_results.csv, nas_xgb_results.csv")
print("💾 Saved: nas_rf_trial_log.csv, nas_xgb_trial_log.csv")

# ============================================================
# 📋 COMPARISON SUMMARY
# ============================================================

print("\n" + "="*60)
print("📋 NAS RESULTS COMPARISON")
print("="*60)

print(f"\n{'Model':<15} {'Best Val F1':<12} {'Best Trial':<12}")
print("-" * 40)
print(f"{'RandomForest':<15} {study_rf.best_value:<12.4f} {study_rf.best_trial.number:<12}")
print(f"{'XGBoost':<15} {study_xgb.best_value:<12.4f} {study_xgb.best_trial.number:<12}")

print("\n📊 Best RF Params:")
for k, v in study_rf.best_params.items():
    print(f"   {k}: {v}")

print("\n📊 Best XGB Params:")
for k, v in study_xgb.best_params.items():
    print(f"   {k}: {v}")

# Display full trial logs
print("\n📊 RF Trial Log (sorted by val_f1):")
display(
    pd.DataFrame(rf_trial_log)
    .sort_values("val_f1", ascending=False)
    .reset_index(drop=True)
)

print("\n📊 XGB Trial Log (sorted by val_f1):")
display(
    pd.DataFrame(xgb_trial_log)
    .sort_values("val_f1", ascending=False)
    .reset_index(drop=True)
)

\n[2026-07-09 10:32:00.634780] 📊 Generating test snapshots...

/tmp/ipykernel_1088/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 1222/1222 [00:03<00:00, 348.54it/s]

[2026-07-09 10:32:09.295865] ✅ Test snapshots: 1222 users
\n[2026-07-09 10:32:09.296007] 📊 Generating validation snapshots...

/tmp/ipykernel_1088/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 977/977 [00:02<00:00, 349.76it/s]
/tmp/ipykernel_1088/3487339742.py:269: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  sampler_rf = TPESampler(
[I 2026-07-09 10:32:15,776] A new study created in memory with name: no-name-72dcebf3-4491-40b2-9b1d-e2ce1b30c0b3

[2026-07-09 10:32:15.773441] ✅ Validation snapshots: 977 users
   Class ratio → Normal: 2652, Fraud: 1255, scale_pos_weight: 2.11
   RF class_weight: {0: 1.0, 1: np.float64(2.113147410358566)}
\n============================================================
🌲 RANDOM FOREST NAS
============================================================
[2026-07-09 10:32:15.777659] 🚀 Starting RF NAS (100 trials)...

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:16,4,0,RandomForest,0.6248,0.7707,0.6975,0.5659,100,10,2,1,0.24,0.24,0.6248,0,0.6,0.7551,0.6565,0.5525,0.0248,True,OK

[I 2026-07-09 10:32:16,313] Trial 0 finished with value: 0.6248216833095578 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.6248216833095578.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:17,4,1,RandomForest,0.618,0.752,0.6465,0.5918,500,20,2,1,0.41,0.4,0.6248,0,0.5802,0.7287,0.5802,0.5802,0.0378,True,OK

[I 2026-07-09 10:32:17,905] Trial 1 finished with value: 0.6179604261796042 and parameters: {'n_estimators': 500, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.6248216833095578.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:18,4,2,RandomForest,0.6241,0.773,0.6688,0.585,200,5,10,5,0.31,0.39,0.6248,0,0.5882,0.761,0.6107,0.5674,0.0358,True,OK

[I 2026-07-09 10:32:18,668] Trial 2 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.6248216833095578.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:19,4,3,RandomForest,0.6276,0.7668,0.6815,0.5815,300,12,5,2,0.31,0.28,0.6276,3,0.587,0.749,0.6183,0.5586,0.0406,True,OK

[I 2026-07-09 10:32:19,674] Trial 3 finished with value: 0.6275659824046921 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.6275659824046921.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:20,4,4,RandomForest,0.6263,0.7667,0.6752,0.584,218,20,15,6,0.33,0.27,0.6276,3,0.5898,0.7455,0.6183,0.5638,0.0365,False,OK

[I 2026-07-09 10:32:20,457] Trial 4 finished with value: 0.6262924667651403 and parameters: {'n_estimators': 218, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 6}. Best is trial 3 with value: 0.6275659824046921.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:20,4,5,RandomForest,0.6241,0.7717,0.6688,0.585,120,4,3,9,0.32,0.2,0.6276,3,0.5882,0.7565,0.6107,0.5674,0.0358,False,OK

[I 2026-07-09 10:32:21,004] Trial 5 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 120, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 3 with value: 0.6275659824046921.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:22,4,6,RandomForest,0.6259,0.7671,0.6688,0.5882,321,15,2,10,0.36,0.27,0.6276,3,0.5882,0.7464,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:32:22,057] Trial 6 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 321, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 3 with value: 0.6275659824046921.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:23,4,7,RandomForest,0.6259,0.774,0.6688,0.5882,425,6,5,2,0.32,0.26,0.6276,3,0.5882,0.763,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:32:23,347] Trial 7 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 425, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.6275659824046921.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:24,4,8,RandomForest,0.6298,0.7692,0.707,0.5678,187,11,10,3,0.26,0.26,0.6298,8,0.5986,0.7546,0.6565,0.5501,0.0312,False,OK

[I 2026-07-09 10:32:24,067] Trial 8 finished with value: 0.6297872340425532 and parameters: {'n_estimators': 187, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 8 with value: 0.6297872340425532.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:25,4,9,RandomForest,0.6241,0.7724,0.6688,0.585,325,4,7,4,0.32,0.2,0.6298,8,0.5882,0.759,0.6107,0.5674,0.0358,False,OK

[I 2026-07-09 10:32:25,117] Trial 9 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 325, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 8 with value: 0.6297872340425532.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:25,4,10,RandomForest,0.6246,0.7611,0.6783,0.5788,190,19,8,1,0.37,0.31,0.6298,8,0.5797,0.7346,0.6107,0.5517,0.0449,False,OK

[I 2026-07-09 10:32:25,861] Trial 10 finished with value: 0.624633431085044 and parameters: {'n_estimators': 190, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 8 with value: 0.6297872340425532.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:26,4,11,RandomForest,0.6246,0.774,0.6943,0.5677,241,9,13,1,0.24,0.27,0.6298,8,0.5995,0.7583,0.6514,0.5553,0.0251,False,OK

[I 2026-07-09 10:32:26,721] Trial 11 finished with value: 0.6246418338108882 and parameters: {'n_estimators': 241, 'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 1}. Best is trial 8 with value: 0.6297872340425532.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:27,4,12,RandomForest,0.6286,0.7666,0.7006,0.5699,331,14,9,3,0.3,0.3,0.6298,8,0.6012,0.7474,0.6539,0.5563,0.0274,False,OK

[I 2026-07-09 10:32:27,799] Trial 12 finished with value: 0.6285714285714286 and parameters: {'n_estimators': 331, 'max_depth': 14, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 8 with value: 0.6297872340425532.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:29,4,13,RandomForest,0.628,0.7673,0.707,0.5649,400,14,13,3,0.29,0.3,0.6298,8,0.5933,0.7476,0.6514,0.5447,0.0347,False,OK

[I 2026-07-09 10:32:29,083] Trial 13 finished with value: 0.628005657708628 and parameters: {'n_estimators': 400, 'max_depth': 14, 'min_samples_split': 13, 'min_samples_leaf': 3}. Best is trial 8 with value: 0.6297872340425532.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:29,4,14,RandomForest,0.6307,0.7673,0.707,0.5692,222,13,11,5,0.28,0.29,0.6307,14,0.5944,0.7485,0.6489,0.5484,0.0363,False,OK

[I 2026-07-09 10:32:29,902] Trial 14 finished with value: 0.6306818181818182 and parameters: {'n_estimators': 222, 'max_depth': 13, 'min_samples_split': 11, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:30,4,15,RandomForest,0.6271,0.7657,0.707,0.5635,91,13,15,4,0.27,0.28,0.6307,14,0.594,0.7491,0.6514,0.5458,0.0332,False,OK

[I 2026-07-09 10:32:30,412] Trial 15 finished with value: 0.6271186440677966 and parameters: {'n_estimators': 91, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:31,4,16,RandomForest,0.6241,0.7681,0.6688,0.585,230,10,19,6,0.35,0.26,0.6307,14,0.5868,0.7532,0.6107,0.5647,0.0373,False,OK

[I 2026-07-09 10:32:31,288] Trial 16 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 230, 'max_depth': 10, 'min_samples_split': 19, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:31,4,17,RandomForest,0.6261,0.7686,0.7038,0.5638,134,14,7,6,0.27,0.27,0.6307,14,0.5991,0.7473,0.6539,0.5527,0.027,False,OK

[I 2026-07-09 10:32:31,886] Trial 17 finished with value: 0.6260623229461756 and parameters: {'n_estimators': 134, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:32,4,18,RandomForest,0.6241,0.7672,0.6688,0.585,264,12,13,10,0.36,0.3,0.6307,14,0.5868,0.7487,0.6107,0.5647,0.0373,False,OK

[I 2026-07-09 10:32:32,790] Trial 18 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 264, 'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 10}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:33,4,19,RandomForest,0.623,0.7703,0.6656,0.5854,384,3,13,8,0.36,0.2,0.6307,14,0.5894,0.7584,0.6081,0.5718,0.0336,False,OK

[I 2026-07-09 10:32:33,981] Trial 19 finished with value: 0.6229508196721312 and parameters: {'n_estimators': 384, 'max_depth': 3, 'min_samples_split': 13, 'min_samples_leaf': 8}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:35,4,20,RandomForest,0.6231,0.7704,0.6688,0.5833,470,9,20,2,0.33,0.29,0.6307,14,0.59,0.7548,0.6132,0.5684,0.0332,False,OK

[I 2026-07-09 10:32:35,412] Trial 20 finished with value: 0.6231454005934718 and parameters: {'n_estimators': 470, 'max_depth': 9, 'min_samples_split': 20, 'min_samples_leaf': 2}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:36,4,21,RandomForest,0.6278,0.7695,0.7038,0.5667,420,12,7,5,0.27,0.29,0.6307,14,0.5928,0.749,0.6463,0.5474,0.0351,False,OK

[I 2026-07-09 10:32:36,725] Trial 21 finished with value: 0.6278409090909091 and parameters: {'n_estimators': 420, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:37,4,22,RandomForest,0.6263,0.7664,0.6752,0.584,255,15,9,5,0.33,0.37,0.6307,14,0.5881,0.7443,0.6158,0.5628,0.0382,False,OK

[I 2026-07-09 10:32:37,618] Trial 22 finished with value: 0.6262924667651403 and parameters: {'n_estimators': 255, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:38,4,23,RandomForest,0.6278,0.7708,0.7038,0.5667,301,11,13,6,0.26,0.28,0.6307,14,0.5958,0.7515,0.6489,0.5508,0.032,False,OK

[I 2026-07-09 10:32:38,618] Trial 23 finished with value: 0.6278409090909091 and parameters: {'n_estimators': 301, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:39,4,24,RandomForest,0.6269,0.7737,0.6688,0.5899,70,7,10,1,0.35,0.26,0.6307,14,0.5904,0.7598,0.6107,0.5714,0.0365,False,OK

[I 2026-07-09 10:32:39,048] Trial 24 finished with value: 0.6268656716417911 and parameters: {'n_estimators': 70, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:40,4,25,RandomForest,0.6294,0.7661,0.6815,0.5847,395,20,10,5,0.34,0.4,0.6307,14,0.5908,0.7434,0.6209,0.5635,0.0386,False,OK

[I 2026-07-09 10:32:40,301] Trial 25 finished with value: 0.6294117647058823 and parameters: {'n_estimators': 395, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:41,4,26,RandomForest,0.625,0.7659,0.7006,0.5641,493,20,8,7,0.29,0.29,0.6307,14,0.5972,0.7431,0.6489,0.5531,0.0278,False,OK

[I 2026-07-09 10:32:41,804] Trial 26 finished with value: 0.625 and parameters: {'n_estimators': 493, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:43,4,27,RandomForest,0.6265,0.7676,0.6783,0.582,428,19,15,4,0.33,0.4,0.6307,14,0.5908,0.7462,0.6209,0.5635,0.0357,False,OK

[I 2026-07-09 10:32:43,186] Trial 27 finished with value: 0.6264705882352941 and parameters: {'n_estimators': 428, 'max_depth': 19, 'min_samples_split': 15, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:44,4,28,RandomForest,0.6241,0.7662,0.6688,0.585,367,20,14,8,0.34,0.29,0.6307,14,0.5868,0.7454,0.6107,0.5647,0.0373,False,OK

[I 2026-07-09 10:32:44,394] Trial 28 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 367, 'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 8}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:45,4,29,RandomForest,0.6265,0.7629,0.6783,0.582,354,20,8,3,0.36,0.38,0.6307,14,0.5908,0.7415,0.6209,0.5635,0.0357,False,OK

[I 2026-07-09 10:32:45,550] Trial 29 finished with value: 0.6264705882352941 and parameters: {'n_estimators': 354, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:46,4,30,RandomForest,0.6259,0.769,0.7006,0.5656,181,10,6,3,0.25,0.29,0.6307,14,0.5923,0.7529,0.6489,0.5449,0.0336,False,OK

[I 2026-07-09 10:32:46,265] Trial 30 finished with value: 0.6258890469416786 and parameters: {'n_estimators': 181, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:47,4,31,RandomForest,0.625,0.7659,0.7006,0.5641,356,20,8,7,0.3,0.3,0.6307,14,0.5972,0.7441,0.6489,0.5531,0.0278,False,OK

[I 2026-07-09 10:32:47,420] Trial 31 finished with value: 0.625 and parameters: {'n_estimators': 356, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:48,4,32,RandomForest,0.6278,0.7693,0.7038,0.5667,251,12,9,4,0.28,0.28,0.6307,14,0.5967,0.7491,0.6514,0.5505,0.0311,False,OK

[I 2026-07-09 10:32:48,306] Trial 32 finished with value: 0.6278409090909091 and parameters: {'n_estimators': 251, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:48,4,33,RandomForest,0.6212,0.7623,0.6815,0.5707,145,20,19,1,0.34,0.41,0.6307,14,0.5846,0.7407,0.6285,0.5465,0.0366,False,OK

[I 2026-07-09 10:32:48,937] Trial 33 finished with value: 0.6211901306240929 and parameters: {'n_estimators': 145, 'max_depth': 20, 'min_samples_split': 19, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:49,4,34,RandomForest,0.6272,0.7629,0.6752,0.5856,310,16,9,1,0.36,0.28,0.6307,14,0.5867,0.7427,0.6158,0.5602,0.0406,False,OK

[I 2026-07-09 10:32:49,984] Trial 34 finished with value: 0.6272189349112426 and parameters: {'n_estimators': 310, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:51,4,35,RandomForest,0.6271,0.7671,0.707,0.5635,341,19,12,5,0.3,0.4,0.6307,14,0.5947,0.7428,0.6514,0.547,0.0325,False,OK

[I 2026-07-09 10:32:51,084] Trial 35 finished with value: 0.6271186440677966 and parameters: {'n_estimators': 341, 'max_depth': 19, 'min_samples_split': 12, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:51,4,36,RandomForest,0.6278,0.7683,0.7038,0.5667,138,11,11,3,0.26,0.27,0.6307,14,0.5956,0.754,0.6539,0.5468,0.0322,False,OK

[I 2026-07-09 10:32:51,698] Trial 36 finished with value: 0.6278409090909091 and parameters: {'n_estimators': 138, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:53,4,37,RandomForest,0.6285,0.7651,0.6815,0.5831,468,18,7,4,0.35,0.38,0.6307,14,0.5908,0.7421,0.6209,0.5635,0.0377,False,OK

[I 2026-07-09 10:32:53,122] Trial 37 finished with value: 0.6284875183553598 and parameters: {'n_estimators': 468, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:53,4,38,RandomForest,0.6259,0.771,0.6688,0.5882,59,6,17,8,0.38,0.39,0.6307,14,0.5882,0.7597,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:32:53,546] Trial 38 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 59, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 8}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:54,4,39,RandomForest,0.6265,0.7672,0.6783,0.582,190,16,14,4,0.33,0.39,0.6307,14,0.5915,0.746,0.6209,0.5648,0.035,False,OK

[I 2026-07-09 10:32:54,292] Trial 39 finished with value: 0.6264705882352941 and parameters: {'n_estimators': 190, 'max_depth': 16, 'min_samples_split': 14, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:55,4,40,RandomForest,0.6248,0.7692,0.6975,0.5659,406,11,8,2,0.25,0.23,0.6307,14,0.597,0.7529,0.6539,0.5491,0.0278,False,OK

[I 2026-07-09 10:32:55,602] Trial 40 finished with value: 0.6248216833095578 and parameters: {'n_estimators': 406, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:57,4,41,RandomForest,0.6302,0.7625,0.6783,0.5884,492,18,5,3,0.36,0.38,0.6307,14,0.5915,0.7403,0.6209,0.5648,0.0387,False,OK

[I 2026-07-09 10:32:57,138] Trial 41 finished with value: 0.6301775147928994 and parameters: {'n_estimators': 492, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:58,4,42,RandomForest,0.6276,0.7614,0.6815,0.5815,493,20,6,3,0.36,0.37,0.6307,14,0.5884,0.7381,0.6183,0.5612,0.0392,False,OK

[I 2026-07-09 10:32:58,635] Trial 42 finished with value: 0.6275659824046921 and parameters: {'n_estimators': 493, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:00,4,43,RandomForest,0.6266,0.7609,0.6815,0.5799,485,16,5,2,0.35,0.42,0.6307,14,0.5884,0.7415,0.6183,0.5612,0.0383,False,OK

[I 2026-07-09 10:33:00,112] Trial 43 finished with value: 0.6266471449487555 and parameters: {'n_estimators': 485, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:00,4,44,RandomForest,0.6271,0.7692,0.707,0.5635,222,12,13,4,0.25,0.29,0.6307,14,0.5945,0.7492,0.6565,0.5432,0.0326,False,OK

[I 2026-07-09 10:33:00,944] Trial 44 finished with value: 0.6271186440677966 and parameters: {'n_estimators': 222, 'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:01,4,45,RandomForest,0.6241,0.7667,0.6688,0.585,258,10,7,8,0.34,0.27,0.6307,14,0.5868,0.7507,0.6107,0.5647,0.0373,False,OK

[I 2026-07-09 10:33:01,856] Trial 45 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 258, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:03,4,46,RandomForest,0.6298,0.7687,0.707,0.5678,480,13,3,5,0.27,0.29,0.6307,14,0.594,0.7483,0.6514,0.5458,0.0358,False,OK

[I 2026-07-09 10:33:03,318] Trial 46 finished with value: 0.6297872340425532 and parameters: {'n_estimators': 480, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:04,4,47,RandomForest,0.6287,0.7695,0.7038,0.5681,478,12,4,5,0.28,0.29,0.6307,14,0.5942,0.7497,0.6463,0.5498,0.0346,False,OK

[I 2026-07-09 10:33:04,773] Trial 47 finished with value: 0.6287339971550497 and parameters: {'n_estimators': 478, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:06,4,48,RandomForest,0.6289,0.7667,0.707,0.5663,482,14,2,7,0.27,0.28,0.6307,14,0.5951,0.7463,0.6489,0.5496,0.0338,False,OK

[I 2026-07-09 10:33:06,233] Trial 48 finished with value: 0.6288951841359773 and parameters: {'n_estimators': 482, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:07,4,49,RandomForest,0.6254,0.7679,0.707,0.5606,352,16,2,6,0.28,0.3,0.6307,14,0.5933,0.7452,0.6514,0.5447,0.0321,False,OK

[I 2026-07-09 10:33:07,382] Trial 49 finished with value: 0.6253521126760564 and parameters: {'n_estimators': 352, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:07,4,50,RandomForest,0.6259,0.7687,0.7006,0.5656,93,15,7,10,0.27,0.4,0.6307,14,0.5939,0.7491,0.6438,0.5512,0.032,False,OK

[I 2026-07-09 10:33:07,876] Trial 50 finished with value: 0.6258890469416786 and parameters: {'n_estimators': 93, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:09,4,51,RandomForest,0.6259,0.7679,0.6688,0.5882,471,19,2,10,0.36,0.29,0.6307,14,0.5882,0.7462,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:33:09,331] Trial 51 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 471, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:10,4,52,RandomForest,0.627,0.7663,0.7038,0.5652,457,16,4,7,0.28,0.29,0.6307,14,0.5944,0.7443,0.6489,0.5484,0.0325,False,OK

[I 2026-07-09 10:33:10,747] Trial 52 finished with value: 0.6269503546099291 and parameters: {'n_estimators': 457, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:12,4,53,RandomForest,0.628,0.7672,0.707,0.5649,421,13,2,7,0.27,0.27,0.6307,14,0.5958,0.7479,0.6489,0.5508,0.0322,False,OK

[I 2026-07-09 10:33:12,052] Trial 53 finished with value: 0.628005657708628 and parameters: {'n_estimators': 421, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:13,4,54,RandomForest,0.6287,0.7703,0.7038,0.5681,454,11,2,5,0.26,0.29,0.6307,14,0.5944,0.7509,0.6489,0.5484,0.0343,False,OK

[I 2026-07-09 10:33:13,459] Trial 54 finished with value: 0.6287339971550497 and parameters: {'n_estimators': 454, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:13,4,55,RandomForest,0.6259,0.7674,0.6688,0.5882,104,8,11,7,0.38,0.28,0.6307,14,0.5882,0.755,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:33:13,982] Trial 55 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 104, 'max_depth': 8, 'min_samples_split': 11, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:15,4,56,RandomForest,0.6294,0.7644,0.6815,0.5847,400,16,2,3,0.33,0.41,0.6307,14,0.5901,0.7433,0.6209,0.5622,0.0393,False,OK

[I 2026-07-09 10:33:15,268] Trial 56 finished with value: 0.6294117647058823 and parameters: {'n_estimators': 400, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:16,4,57,RandomForest,0.6257,0.7608,0.6815,0.5784,382,16,5,2,0.34,0.43,0.6307,14,0.5877,0.7422,0.6183,0.5599,0.0381,False,OK

[I 2026-07-09 10:33:16,505] Trial 57 finished with value: 0.6257309941520468 and parameters: {'n_estimators': 382, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:17,4,58,RandomForest,0.6285,0.763,0.6815,0.5831,343,18,2,3,0.35,0.37,0.6307,14,0.5894,0.7402,0.6209,0.5609,0.0391,False,OK

[I 2026-07-09 10:33:17,622] Trial 58 finished with value: 0.6284875183553598 and parameters: {'n_estimators': 343, 'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:18,4,59,RandomForest,0.6241,0.7717,0.6688,0.585,257,4,19,10,0.32,0.31,0.6307,14,0.5882,0.7576,0.6107,0.5674,0.0358,False,OK

[I 2026-07-09 10:33:18,515] Trial 59 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 257, 'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 10}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:19,4,60,RandomForest,0.6307,0.7674,0.707,0.5692,454,14,2,4,0.29,0.29,0.6307,14,0.5977,0.7455,0.6539,0.5503,0.033,False,OK

[I 2026-07-09 10:33:19,950] Trial 60 finished with value: 0.6306818181818182 and parameters: {'n_estimators': 454, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:21,4,61,RandomForest,0.6272,0.7662,0.6752,0.5856,477,13,2,3,0.33,0.3,0.6307,14,0.592,0.7457,0.6183,0.5678,0.0353,False,OK

[I 2026-07-09 10:33:21,483] Trial 61 finished with value: 0.6272189349112426 and parameters: {'n_estimators': 477, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:23,4,62,RandomForest,0.627,0.7663,0.6879,0.576,488,16,2,4,0.32,0.37,0.6307,14,0.5854,0.7427,0.6234,0.5518,0.0416,False,OK

[I 2026-07-09 10:33:23,039] Trial 62 finished with value: 0.6269956458635704 and parameters: {'n_estimators': 488, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:24,4,63,RandomForest,0.6259,0.7672,0.6688,0.5882,469,11,13,10,0.36,0.28,0.6307,14,0.5882,0.7487,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:33:24,492] Trial 63 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 469, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 10}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:25,4,64,RandomForest,0.623,0.7705,0.6656,0.5854,380,3,16,1,0.36,0.2,0.6307,14,0.5872,0.7589,0.6081,0.5677,0.0357,False,OK

[I 2026-07-09 10:33:25,700] Trial 64 finished with value: 0.6229508196721312 and parameters: {'n_estimators': 380, 'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:26,4,65,RandomForest,0.6279,0.7664,0.6879,0.5775,344,15,3,4,0.32,0.37,0.6307,14,0.5875,0.7453,0.6234,0.5556,0.0404,False,OK

[I 2026-07-09 10:33:26,855] Trial 65 finished with value: 0.627906976744186 and parameters: {'n_estimators': 344, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:28,4,66,RandomForest,0.6277,0.7684,0.7006,0.5685,367,11,4,4,0.28,0.28,0.6307,14,0.5995,0.7507,0.6514,0.5553,0.0281,False,OK

[I 2026-07-09 10:33:28,048] Trial 66 finished with value: 0.6276747503566333 and parameters: {'n_estimators': 367, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:28,4,67,RandomForest,0.6263,0.7654,0.6752,0.584,146,16,9,4,0.35,0.38,0.6307,14,0.5901,0.7441,0.6209,0.5622,0.0362,False,OK

[I 2026-07-09 10:33:28,687] Trial 67 finished with value: 0.6262924667651403 and parameters: {'n_estimators': 146, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:29,4,68,RandomForest,0.6259,0.7711,0.6688,0.5882,226,7,11,4,0.36,0.27,0.6307,14,0.5882,0.7581,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:33:29,525] Trial 68 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 226, 'max_depth': 7, 'min_samples_split': 11, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:30,4,69,RandomForest,0.622,0.7705,0.6656,0.5838,468,3,3,8,0.35,0.36,0.6307,14,0.589,0.7585,0.6107,0.5687,0.0331,False,OK

[I 2026-07-09 10:33:30,943] Trial 69 finished with value: 0.6220238095238095 and parameters: {'n_estimators': 468, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:31,4,70,RandomForest,0.6259,0.7709,0.6688,0.5882,69,7,4,5,0.34,0.38,0.6307,14,0.5882,0.7576,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:33:31,387] Trial 70 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 69, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:32,4,71,RandomForest,0.6274,0.7657,0.6783,0.5836,429,16,2,4,0.35,0.37,0.6307,14,0.5891,0.7429,0.6183,0.5625,0.0383,False,OK

[I 2026-07-09 10:33:32,784] Trial 71 finished with value: 0.6273932253313697 and parameters: {'n_estimators': 429, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:34,4,72,RandomForest,0.628,0.7672,0.707,0.5649,478,13,2,7,0.27,0.26,0.6307,14,0.5958,0.7477,0.6489,0.5508,0.0322,False,OK

[I 2026-07-09 10:33:34,346] Trial 72 finished with value: 0.628005657708628 and parameters: {'n_estimators': 478, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:35,4,73,RandomForest,0.6287,0.7674,0.7038,0.5681,465,15,9,6,0.29,0.28,0.6307,14,0.5965,0.7464,0.6489,0.5519,0.0322,False,OK

[I 2026-07-09 10:33:35,884] Trial 73 finished with value: 0.6287339971550497 and parameters: {'n_estimators': 465, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:36,4,74,RandomForest,0.6255,0.768,0.6943,0.5692,182,11,8,1,0.29,0.23,0.6307,14,0.5976,0.7522,0.6463,0.5558,0.0279,False,OK

[I 2026-07-09 10:33:36,630] Trial 74 finished with value: 0.6255380200860832 and parameters: {'n_estimators': 182, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:37,4,75,RandomForest,0.628,0.7695,0.707,0.5649,236,13,12,6,0.26,0.27,0.6307,14,0.5953,0.7478,0.6514,0.5482,0.0327,False,OK

[I 2026-07-09 10:33:37,520] Trial 75 finished with value: 0.628005657708628 and parameters: {'n_estimators': 236, 'max_depth': 13, 'min_samples_split': 12, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:39,4,76,RandomForest,0.6287,0.7672,0.7038,0.5681,481,14,8,4,0.29,0.38,0.6307,14,0.596,0.7456,0.6514,0.5494,0.0327,False,OK

[I 2026-07-09 10:33:39,060] Trial 76 finished with value: 0.6287339971550497 and parameters: {'n_estimators': 481, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:40,4,77,RandomForest,0.6283,0.7622,0.6783,0.5852,484,17,10,1,0.36,0.3,0.6307,14,0.5908,0.741,0.6209,0.5635,0.0375,False,OK

[I 2026-07-09 10:33:40,612] Trial 77 finished with value: 0.6283185840707964 and parameters: {'n_estimators': 484, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:42,4,78,RandomForest,0.6259,0.7671,0.7006,0.5656,478,17,4,6,0.29,0.29,0.6307,14,0.5944,0.7453,0.6489,0.5484,0.0315,False,OK

[I 2026-07-09 10:33:42,107] Trial 78 finished with value: 0.6258890469416786 and parameters: {'n_estimators': 478, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:43,4,79,RandomForest,0.6259,0.7672,0.6688,0.5882,496,11,4,10,0.36,0.28,0.6307,14,0.5882,0.7488,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:33:43,641] Trial 79 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 496, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:44,4,80,RandomForest,0.6276,0.7653,0.6815,0.5815,382,19,7,4,0.34,0.38,0.6307,14,0.588,0.7425,0.6209,0.5584,0.0396,False,OK

[I 2026-07-09 10:33:44,909] Trial 80 finished with value: 0.6275659824046921 and parameters: {'n_estimators': 382, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:46,4,81,RandomForest,0.6278,0.7691,0.7038,0.5667,500,11,5,4,0.26,0.28,0.6307,14,0.5953,0.751,0.6514,0.5482,0.0325,False,OK

[I 2026-07-09 10:33:46,487] Trial 81 finished with value: 0.6278409090909091 and parameters: {'n_estimators': 500, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:48,4,82,RandomForest,0.6294,0.7658,0.6815,0.5847,479,15,5,4,0.33,0.41,0.6307,14,0.5915,0.7451,0.6209,0.5648,0.0379,False,OK

[I 2026-07-09 10:33:48,027] Trial 82 finished with value: 0.6294117647058823 and parameters: {'n_estimators': 479, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:49,4,83,RandomForest,0.6294,0.7649,0.6815,0.5847,481,16,6,3,0.33,0.41,0.6307,14,0.5901,0.7427,0.6209,0.5622,0.0393,False,OK

[I 2026-07-09 10:33:49,557] Trial 83 finished with value: 0.6294117647058823 and parameters: {'n_estimators': 481, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:50,4,84,RandomForest,0.6266,0.7602,0.6815,0.5799,430,18,4,2,0.35,0.38,0.6307,14,0.588,0.7417,0.6209,0.5584,0.0387,False,OK

[I 2026-07-09 10:33:50,944] Trial 84 finished with value: 0.6266471449487555 and parameters: {'n_estimators': 430, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:52,4,85,RandomForest,0.6287,0.7667,0.7038,0.5681,441,14,7,3,0.3,0.3,0.6307,14,0.5984,0.7468,0.6539,0.5515,0.0304,False,OK

[I 2026-07-09 10:33:52,346] Trial 85 finished with value: 0.6287339971550497 and parameters: {'n_estimators': 441, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:53,4,86,RandomForest,0.627,0.7688,0.7038,0.5652,314,12,20,1,0.26,0.26,0.6307,14,0.6028,0.7501,0.6641,0.5518,0.0242,False,OK

[I 2026-07-09 10:33:53,409] Trial 86 finished with value: 0.6269503546099291 and parameters: {'n_estimators': 314, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:54,4,87,RandomForest,0.6274,0.7654,0.6783,0.5836,483,16,4,4,0.35,0.37,0.6307,14,0.5891,0.7427,0.6183,0.5625,0.0383,False,OK

[I 2026-07-09 10:33:54,908] Trial 87 finished with value: 0.6273932253313697 and parameters: {'n_estimators': 483, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:56,4,88,RandomForest,0.6289,0.7678,0.707,0.5663,420,18,12,6,0.29,0.3,0.6307,14,0.5944,0.7445,0.6489,0.5484,0.0345,False,OK

[I 2026-07-09 10:33:56,232] Trial 88 finished with value: 0.6288951841359773 and parameters: {'n_estimators': 420, 'max_depth': 18, 'min_samples_split': 12, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:57,4,89,RandomForest,0.623,0.7692,0.6656,0.5854,231,3,8,10,0.36,0.35,0.6307,14,0.5894,0.7569,0.6081,0.5718,0.0336,False,OK

[I 2026-07-09 10:33:57,079] Trial 89 finished with value: 0.6229508196721312 and parameters: {'n_estimators': 231, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:58,4,90,RandomForest,0.6281,0.764,0.6752,0.5873,403,14,2,3,0.34,0.37,0.6307,14,0.592,0.7452,0.6183,0.5678,0.0362,False,OK

[I 2026-07-09 10:33:58,364] Trial 90 finished with value: 0.6281481481481481 and parameters: {'n_estimators': 403, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:33:59,4,91,RandomForest,0.6278,0.7703,0.7038,0.5667,218,11,8,5,0.27,0.28,0.6307,14,0.5967,0.7508,0.6514,0.5505,0.0311,False,OK

[I 2026-07-09 10:33:59,196] Trial 91 finished with value: 0.6278409090909091 and parameters: {'n_estimators': 218, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:00,4,92,RandomForest,0.6276,0.7656,0.6815,0.5815,489,17,5,4,0.34,0.37,0.6307,14,0.5887,0.7435,0.6209,0.5596,0.0389,False,OK

[I 2026-07-09 10:34:00,754] Trial 92 finished with value: 0.6275659824046921 and parameters: {'n_estimators': 489, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:02,4,93,RandomForest,0.6215,0.7561,0.672,0.5781,443,17,2,1,0.36,0.4,0.6307,14,0.5794,0.737,0.6081,0.5532,0.0421,False,OK

[I 2026-07-09 10:34:02,215] Trial 93 finished with value: 0.6215022091310751 and parameters: {'n_estimators': 443, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:03,4,94,RandomForest,0.628,0.7667,0.707,0.5649,341,20,10,6,0.3,0.29,0.6307,14,0.5944,0.7447,0.6489,0.5484,0.0336,False,OK

[I 2026-07-09 10:34:03,361] Trial 94 finished with value: 0.628005657708628 and parameters: {'n_estimators': 341, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:04,4,95,RandomForest,0.6259,0.7678,0.7006,0.5656,456,17,19,9,0.27,0.27,0.6307,14,0.5955,0.7448,0.6463,0.5522,0.0303,False,OK

[I 2026-07-09 10:34:04,805] Trial 95 finished with value: 0.6258890469416786 and parameters: {'n_estimators': 456, 'max_depth': 17, 'min_samples_split': 19, 'min_samples_leaf': 9}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:06,4,96,RandomForest,0.6289,0.7686,0.707,0.5663,477,13,2,5,0.27,0.26,0.6307,14,0.594,0.7484,0.6514,0.5458,0.0349,False,OK

[I 2026-07-09 10:34:06,272] Trial 96 finished with value: 0.6288951841359773 and parameters: {'n_estimators': 477, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:07,4,97,RandomForest,0.6156,0.7688,0.6401,0.5929,192,2,13,2,0.41,0.38,0.6307,14,0.5783,0.756,0.5776,0.5791,0.0373,False,OK

[I 2026-07-09 10:34:07,014] Trial 97 finished with value: 0.6156202143950995 and parameters: {'n_estimators': 192, 'max_depth': 2, 'min_samples_split': 13, 'min_samples_leaf': 2}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:08,4,98,RandomForest,0.6283,0.7646,0.6783,0.5852,488,18,8,3,0.36,0.38,0.6307,14,0.5898,0.7429,0.6183,0.5638,0.0385,False,OK

[I 2026-07-09 10:34:08,524] Trial 98 finished with value: 0.6283185840707964 and parameters: {'n_estimators': 488, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 14 with value: 0.6306818181818182.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:09,4,99,RandomForest,0.6287,0.7675,0.7038,0.5681,402,15,6,6,0.29,0.29,0.6307,14,0.5972,0.7463,0.6489,0.5531,0.0315,False,OK

[I 2026-07-09 10:34:09,820] Trial 99 finished with value: 0.6287339971550497 and parameters: {'n_estimators': 402, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 14 with value: 0.6306818181818182.
/tmp/ipykernel_1088/3487339742.py:307: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  sampler_xgb = TPESampler(
[I 2026-07-09 10:34:09,823] A new study created in memory with name: no-name-661fcffc-6290-48ca-9fd3-bbbae9549c26

\n============================================================
🎉 RF NAS COMPLETE
============================================================
Best Trial: 14
Best F1: 0.6307
Best Params: {'n_estimators': 222, 'max_depth': 13, 'min_samples_split': 11, 'min_samples_leaf': 5}
\n============================================================
🚀 XGBOOST NAS
============================================================
[2026-07-09 10:34:09.826051] 🚀 Starting XGB NAS (100 trials)...

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:10,4,0,XGBoost,0.6265,0.771,0.6783,0.582,100,6,0.1,1.0,1.0,1,0.0,29,3,0.29,0.39,0.6265,0,0.587,0.757,0.6183,0.5586,0.0395,True,OK

[I 2026-07-09 10:34:10,572] Trial 0 finished with value: 0.6264705882352941 and parameters: {'n_estimators': 100, 'max_depth': 6, 'learning_rate': 0.1, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 0.0, 'patience': 3}. Best is trial 0 with value: 0.6264705882352941.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:11,4,1,XGBoost,0.6259,0.7711,0.6688,0.5882,500,4,0.01,0.8,0.8,3,0.1,282,3,0.32,0.26,0.6265,0,0.5882,0.7599,0.6107,0.5674,0.0377,True,OK

[I 2026-07-09 10:34:11,044] Trial 1 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.01, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1, 'patience': 3}. Best is trial 0 with value: 0.6264705882352941.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:11,4,2,XGBoost,0.6232,0.7666,0.6847,0.5718,50,8,0.3,0.7,0.7,1,0.0,9,3,0.3,0.35,0.6265,0,0.5857,0.7486,0.626,0.5503,0.0375,True,OK

[I 2026-07-09 10:34:11,342] Trial 2 finished with value: 0.6231884057971014 and parameters: {'n_estimators': 50, 'max_depth': 8, 'learning_rate': 0.3, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1, 'gamma': 0.0, 'patience': 3}. Best is trial 0 with value: 0.6264705882352941.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:11,4,3,XGBoost,0.625,0.7753,0.6688,0.5866,300,3,0.05,0.6,0.6,5,0.5,78,3,0.31,0.27,0.6265,0,0.5882,0.7635,0.6107,0.5674,0.0368,True,OK

[I 2026-07-09 10:34:11,680] Trial 3 finished with value: 0.625 and parameters: {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.05, 'subsample': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5, 'gamma': 0.5, 'patience': 3}. Best is trial 0 with value: 0.6264705882352941.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:12,4,4,XGBoost,0.6285,0.7687,0.6465,0.6114,218,20,0.065049,0.799329,0.578009,2,0.058084,43,5,0.43,0.41,0.6285,4,0.5923,0.7495,0.5878,0.5969,0.0362,False,OK

[I 2026-07-09 10:34:12,097] Trial 4 finished with value: 0.628482972136223 and parameters: {'n_estimators': 218, 'max_depth': 20, 'learning_rate': 0.06504856968981275, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'min_child_weight': 2, 'gamma': 0.05808361216819946, 'patience': 5}. Best is trial 4 with value: 0.628482972136223.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:15,4,5,XGBoost,0.6277,0.7677,0.6847,0.5795,321,15,0.001125,0.984955,0.916221,3,0.181825,320,2,0.33,0.34,0.6285,4,0.5906,0.7415,0.626,0.5591,0.0371,False,OK

[I 2026-07-09 10:34:15,887] Trial 5 finished with value: 0.6277372262773723 and parameters: {'n_estimators': 321, 'max_depth': 15, 'learning_rate': 0.001124579825911934, 'subsample': 0.9849549260809971, 'colsample_bytree': 0.9162213204002109, 'min_child_weight': 3, 'gamma': 0.18182496720710062, 'patience': 2}. Best is trial 4 with value: 0.628482972136223.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:16,4,6,XGBoost,0.6263,0.7657,0.6752,0.584,187,11,0.011748,0.645615,0.805926,2,0.292145,186,3,0.35,0.29,0.6285,4,0.5867,0.7471,0.6158,0.5602,0.0396,False,OK

[I 2026-07-09 10:34:16,413] Trial 6 finished with value: 0.6262924667651403 and parameters: {'n_estimators': 187, 'max_depth': 11, 'learning_rate': 0.01174843954800703, 'subsample': 0.645614570099021, 'colsample_bytree': 0.8059264473611898, 'min_child_weight': 2, 'gamma': 0.29214464853521815, 'patience': 3}. Best is trial 4 with value: 0.628482972136223.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:17,4,7,XGBoost,0.6314,0.771,0.6847,0.5858,255,16,0.003123,0.757117,0.796207,1,0.607545,254,2,0.33,0.38,0.6314,7,0.5897,0.7505,0.6234,0.5594,0.0418,False,OK

[I 2026-07-09 10:34:17,083] Trial 7 finished with value: 0.631424375917768 and parameters: {'n_estimators': 255, 'max_depth': 16, 'learning_rate': 0.003123317753376431, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'min_child_weight': 1, 'gamma': 0.6075448519014384, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:17,4,8,XGBoost,0.6212,0.7619,0.6815,0.5707,79,20,0.246597,0.904199,0.652307,1,0.684233,9,3,0.34,0.45,0.6314,7,0.585,0.7495,0.626,0.5491,0.0362,False,OK

[I 2026-07-09 10:34:17,383] Trial 8 finished with value: 0.6211901306240929 and parameters: {'n_estimators': 79, 'max_depth': 20, 'learning_rate': 0.24659691172104828, 'subsample': 0.9041986740582306, 'colsample_bytree': 0.6523068845866853, 'min_child_weight': 1, 'gamma': 0.6842330265121569, 'patience': 3}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:17,4,9,XGBoost,0.6211,0.7691,0.6943,0.5619,105,11,0.001217,0.95466,0.62939,7,0.311711,104,4,0.32,0.32,0.6314,7,0.5976,0.7523,0.6463,0.5558,0.0234,False,OK

[I 2026-07-09 10:34:17,777] Trial 9 finished with value: 0.6210826210826211 and parameters: {'n_estimators': 105, 'max_depth': 11, 'learning_rate': 0.0012167028814593455, 'subsample': 0.954660201039391, 'colsample_bytree': 0.6293899908000085, 'min_child_weight': 7, 'gamma': 0.31171107608941095, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:18,4,10,XGBoost,0.6272,0.7691,0.6752,0.5856,385,9,0.007486,0.647661,0.83926,2,0.98203,276,2,0.34,0.27,0.6314,7,0.5864,0.7524,0.6132,0.5618,0.0408,False,OK

[I 2026-07-09 10:34:18,367] Trial 10 finished with value: 0.6272189349112426 and parameters: {'n_estimators': 385, 'max_depth': 9, 'learning_rate': 0.007485762113667508, 'subsample': 0.6476613760768839, 'colsample_bytree': 0.8392599136842959, 'min_child_weight': 2, 'gamma': 0.9820295107782193, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:18,4,11,XGBoost,0.6206,0.7625,0.6433,0.5994,322,16,0.053192,0.774809,0.637993,1,0.141313,45,5,0.41,0.42,0.6314,7,0.5934,0.7433,0.5903,0.5964,0.0272,False,OK

[I 2026-07-09 10:34:18,720] Trial 11 finished with value: 0.620583717357911 and parameters: {'n_estimators': 322, 'max_depth': 16, 'learning_rate': 0.05319151004361627, 'subsample': 0.7748091687724276, 'colsample_bytree': 0.6379928981524459, 'min_child_weight': 1, 'gamma': 0.1413125351723752, 'patience': 5}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:19,4,12,XGBoost,0.6291,0.7725,0.6752,0.5889,225,19,0.197397,0.781071,0.515169,5,0.173003,14,4,0.34,0.26,0.6314,7,0.5885,0.7495,0.6132,0.5657,0.0406,False,OK

[I 2026-07-09 10:34:19,031] Trial 12 finished with value: 0.629080118694362 and parameters: {'n_estimators': 225, 'max_depth': 19, 'learning_rate': 0.19739737649446037, 'subsample': 0.7810705229236253, 'colsample_bytree': 0.5151687304541452, 'min_child_weight': 5, 'gamma': 0.17300341242800232, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:19,4,13,XGBoost,0.6283,0.7643,0.6783,0.5852,261,19,0.198348,0.855072,0.628774,6,0.438603,15,4,0.33,0.46,0.6314,7,0.5877,0.7476,0.6183,0.5599,0.0407,False,OK

[I 2026-07-09 10:34:19,336] Trial 13 finished with value: 0.6283185840707964 and parameters: {'n_estimators': 261, 'max_depth': 19, 'learning_rate': 0.19834780141551392, 'subsample': 0.8550719350504232, 'colsample_bytree': 0.6287744717844188, 'min_child_weight': 6, 'gamma': 0.43860332555484843, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:20,4,14,XGBoost,0.6229,0.7715,0.6943,0.5648,359,18,0.001189,0.811531,0.753284,3,0.606705,358,3,0.31,0.3,0.6314,7,0.5942,0.7502,0.6463,0.5498,0.0287,False,OK

[I 2026-07-09 10:34:20,107] Trial 14 finished with value: 0.6228571428571429 and parameters: {'n_estimators': 359, 'max_depth': 18, 'learning_rate': 0.0011894795519703045, 'subsample': 0.8115309643539689, 'colsample_bytree': 0.7532842956845496, 'min_child_weight': 3, 'gamma': 0.6067045391479273, 'patience': 3}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:20,4,15,XGBoost,0.6292,0.7714,0.6783,0.5868,164,16,0.00468,0.710433,0.655758,1,0.630177,163,2,0.33,0.36,0.6314,7,0.5905,0.7538,0.6183,0.5651,0.0387,False,OK

[I 2026-07-09 10:34:20,615] Trial 15 finished with value: 0.6292466765140325 and parameters: {'n_estimators': 164, 'max_depth': 16, 'learning_rate': 0.004680171898822395, 'subsample': 0.7104325652584219, 'colsample_bytree': 0.6557578250516903, 'min_child_weight': 1, 'gamma': 0.6301774490776256, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:21,4,16,XGBoost,0.6241,0.7729,0.6688,0.585,124,15,0.00217,0.740767,0.671286,1,0.547472,123,2,0.33,0.31,0.6314,7,0.5895,0.7547,0.6158,0.5654,0.0345,False,OK

[I 2026-07-09 10:34:21,061] Trial 16 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 124, 'max_depth': 15, 'learning_rate': 0.0021699026018386783, 'subsample': 0.7407672743072937, 'colsample_bytree': 0.6712860374543324, 'min_child_weight': 1, 'gamma': 0.5474722512276197, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:21,4,17,XGBoost,0.6241,0.7693,0.7006,0.5627,274,17,0.003474,0.586475,0.811714,3,0.693146,273,2,0.29,0.27,0.6314,7,0.5937,0.7506,0.6489,0.5472,0.0304,False,OK

[I 2026-07-09 10:34:21,721] Trial 17 finished with value: 0.624113475177305 and parameters: {'n_estimators': 274, 'max_depth': 17, 'learning_rate': 0.0034740661303076102, 'subsample': 0.5864746620903274, 'colsample_bytree': 0.8117140038053614, 'min_child_weight': 3, 'gamma': 0.6931460445066386, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:22,4,18,XGBoost,0.625,0.7719,0.6688,0.5866,220,18,0.010156,0.739974,0.547729,4,0.68998,219,4,0.36,0.28,0.6314,7,0.5882,0.7557,0.6107,0.5674,0.0368,False,OK

[I 2026-07-09 10:34:22,243] Trial 18 finished with value: 0.625 and parameters: {'n_estimators': 220, 'max_depth': 18, 'learning_rate': 0.010156127380476882, 'subsample': 0.7399737187335127, 'colsample_bytree': 0.5477293603184072, 'min_child_weight': 4, 'gamma': 0.6899800555192335, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:22,4,19,XGBoost,0.6241,0.7712,0.6688,0.585,132,8,0.00169,0.596063,0.654338,3,0.882894,131,3,0.33,0.3,0.6314,7,0.5882,0.7554,0.6107,0.5674,0.0358,False,OK

[I 2026-07-09 10:34:22,651] Trial 19 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 132, 'max_depth': 8, 'learning_rate': 0.0016901333678765215, 'subsample': 0.5960627516686373, 'colsample_bytree': 0.6543375191172167, 'min_child_weight': 3, 'gamma': 0.8828937204231811, 'patience': 3}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:23,4,20,XGBoost,0.6288,0.7676,0.6879,0.5791,161,14,0.023543,0.851562,0.852344,2,0.887114,98,2,0.32,0.46,0.6314,7,0.5895,0.7472,0.6285,0.5551,0.0393,False,OK

[I 2026-07-09 10:34:23,073] Trial 20 finished with value: 0.62882096069869 and parameters: {'n_estimators': 161, 'max_depth': 14, 'learning_rate': 0.02354309355033805, 'subsample': 0.851561967973421, 'colsample_bytree': 0.8523442641568046, 'min_child_weight': 2, 'gamma': 0.8871141992879107, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:23,4,21,XGBoost,0.6257,0.7699,0.7134,0.5572,182,18,0.067614,0.755939,0.558946,9,0.060673,59,3,0.27,0.27,0.6314,7,0.5991,0.7549,0.6616,0.5474,0.0266,False,OK

[I 2026-07-09 10:34:23,418] Trial 21 finished with value: 0.6256983240223464 and parameters: {'n_estimators': 182, 'max_depth': 18, 'learning_rate': 0.06761427267722876, 'subsample': 0.755938969697116, 'colsample_bytree': 0.5589460710152867, 'min_child_weight': 9, 'gamma': 0.06067327154306103, 'patience': 3}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:24,4,22,XGBoost,0.6286,0.7666,0.7006,0.5699,249,8,0.00265,0.762116,0.956956,1,0.588046,248,2,0.3,0.38,0.6314,7,0.5939,0.7527,0.6438,0.5512,0.0347,False,OK

[I 2026-07-09 10:34:24,028] Trial 22 finished with value: 0.6285714285714286 and parameters: {'n_estimators': 249, 'max_depth': 8, 'learning_rate': 0.0026500255156006623, 'subsample': 0.7621163383659832, 'colsample_bytree': 0.9569560266426074, 'min_child_weight': 1, 'gamma': 0.5880462240181034, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:24,4,23,XGBoost,0.6254,0.7718,0.6752,0.5824,353,14,0.020434,0.851499,0.627127,2,0.488777,122,2,0.36,0.45,0.6314,7,0.587,0.7505,0.6183,0.5586,0.0384,False,OK

[I 2026-07-09 10:34:24,478] Trial 23 finished with value: 0.6253687315634219 and parameters: {'n_estimators': 353, 'max_depth': 14, 'learning_rate': 0.02043381804272009, 'subsample': 0.8514994644120948, 'colsample_bytree': 0.6271271373614467, 'min_child_weight': 2, 'gamma': 0.48877713498440245, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:24,4,24,XGBoost,0.622,0.7702,0.6656,0.5838,307,19,0.178725,0.710428,0.510672,5,0.099669,15,3,0.34,0.27,0.6314,7,0.5858,0.75,0.6081,0.565,0.0362,False,OK

[I 2026-07-09 10:34:24,826] Trial 24 finished with value: 0.6220238095238095 and parameters: {'n_estimators': 307, 'max_depth': 19, 'learning_rate': 0.17872536673986394, 'subsample': 0.7104275568689482, 'colsample_bytree': 0.5106715693267924, 'min_child_weight': 5, 'gamma': 0.0996687477720313, 'patience': 3}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:25,4,25,XGBoost,0.625,0.7694,0.6688,0.5866,340,14,0.195734,0.918962,0.501416,4,0.036336,14,4,0.35,0.27,0.6314,7,0.5881,0.7528,0.6158,0.5628,0.0369,False,OK

[I 2026-07-09 10:34:25,127] Trial 25 finished with value: 0.625 and parameters: {'n_estimators': 340, 'max_depth': 14, 'learning_rate': 0.19573388458952845, 'subsample': 0.9189619365681432, 'colsample_bytree': 0.5014161807523778, 'min_child_weight': 4, 'gamma': 0.03633604073377858, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:27,4,26,XGBoost,0.6288,0.7663,0.6879,0.5791,330,17,0.009683,0.757119,0.906398,1,0.544735,191,2,0.35,0.43,0.6314,7,0.5892,0.7461,0.626,0.5566,0.0396,False,OK

[I 2026-07-09 10:34:27,082] Trial 26 finished with value: 0.62882096069869 and parameters: {'n_estimators': 330, 'max_depth': 17, 'learning_rate': 0.009683218649758291, 'subsample': 0.757118838546558, 'colsample_bytree': 0.9063975331529877, 'min_child_weight': 1, 'gamma': 0.5447350535075665, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:28,4,27,XGBoost,0.6223,0.7676,0.6401,0.6054,197,19,0.240643,0.63453,0.606655,3,0.488096,16,4,0.43,0.43,0.6314,7,0.5943,0.7421,0.5852,0.6037,0.028,False,OK

[I 2026-07-09 10:34:28,240] Trial 27 finished with value: 0.6222910216718266 and parameters: {'n_estimators': 197, 'max_depth': 19, 'learning_rate': 0.24064301871640809, 'subsample': 0.6345297275857276, 'colsample_bytree': 0.6066551388092939, 'min_child_weight': 3, 'gamma': 0.48809587758346396, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:28,4,28,XGBoost,0.6231,0.768,0.6369,0.6098,69,17,0.059157,0.687298,0.581329,4,0.022109,51,3,0.43,0.37,0.6314,7,0.5917,0.7452,0.5827,0.601,0.0313,False,OK

[I 2026-07-09 10:34:28,786] Trial 28 finished with value: 0.6230529595015576 and parameters: {'n_estimators': 69, 'max_depth': 17, 'learning_rate': 0.05915680484598284, 'subsample': 0.6872976285614808, 'colsample_bytree': 0.5813292912127471, 'min_child_weight': 4, 'gamma': 0.022109026469386173, 'patience': 3}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:29,4,29,XGBoost,0.6241,0.7742,0.6688,0.585,207,19,0.004574,0.689005,0.560656,1,0.833703,206,2,0.33,0.37,0.6314,7,0.5895,0.755,0.6158,0.5654,0.0345,False,OK

[I 2026-07-09 10:34:29,353] Trial 29 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 207, 'max_depth': 19, 'learning_rate': 0.004574474779106767, 'subsample': 0.6890047413823858, 'colsample_bytree': 0.5606559647435765, 'min_child_weight': 1, 'gamma': 0.8337031473838338, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:30,4,30,XGBoost,0.6241,0.7694,0.6688,0.585,272,13,0.001017,0.673383,0.79953,2,0.275864,271,2,0.33,0.31,0.6314,7,0.5878,0.7499,0.6132,0.5644,0.0363,False,OK

[I 2026-07-09 10:34:30,025] Trial 30 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 272, 'max_depth': 13, 'learning_rate': 0.001016591565839177, 'subsample': 0.673383359879189, 'colsample_bytree': 0.7995301816171514, 'min_child_weight': 2, 'gamma': 0.27586383176698887, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:30,4,31,XGBoost,0.6288,0.7668,0.6879,0.5791,122,14,0.034084,0.822725,0.96115,1,0.911104,56,2,0.34,0.36,0.6314,7,0.5902,0.7477,0.6285,0.5563,0.0386,False,OK

[I 2026-07-09 10:34:30,409] Trial 31 finished with value: 0.62882096069869 and parameters: {'n_estimators': 122, 'max_depth': 14, 'learning_rate': 0.03408411451870527, 'subsample': 0.8227254461822037, 'colsample_bytree': 0.9611498885998158, 'min_child_weight': 1, 'gamma': 0.9111044303874646, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:30,4,32,XGBoost,0.6274,0.7689,0.6783,0.5836,166,13,0.023587,0.928022,0.770126,3,0.842568,91,2,0.33,0.39,0.6314,7,0.5894,0.7459,0.6209,0.5609,0.038,False,OK

[I 2026-07-09 10:34:30,814] Trial 32 finished with value: 0.6273932253313697 and parameters: {'n_estimators': 166, 'max_depth': 13, 'learning_rate': 0.02358651398495611, 'subsample': 0.9280219673755096, 'colsample_bytree': 0.770126220920937, 'min_child_weight': 3, 'gamma': 0.8425680903284909, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:31,4,33,XGBoost,0.6279,0.7676,0.6879,0.5775,131,20,0.001848,0.740329,0.886706,2,0.490469,130,2,0.32,0.34,0.6314,7,0.5861,0.7503,0.6234,0.553,0.0418,False,OK

[I 2026-07-09 10:34:31,323] Trial 33 finished with value: 0.627906976744186 and parameters: {'n_estimators': 131, 'max_depth': 20, 'learning_rate': 0.001848311245179901, 'subsample': 0.7403285780886979, 'colsample_bytree': 0.8867057961484025, 'min_child_weight': 2, 'gamma': 0.4904689778355817, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:31,4,34,XGBoost,0.6242,0.7728,0.6401,0.6091,149,14,0.048993,0.79578,0.545628,5,0.388592,63,4,0.41,0.36,0.6314,7,0.5928,0.7536,0.5852,0.6005,0.0314,False,OK

[I 2026-07-09 10:34:31,693] Trial 34 finished with value: 0.6242236024844721 and parameters: {'n_estimators': 149, 'max_depth': 14, 'learning_rate': 0.04899324389356191, 'subsample': 0.7957797106049203, 'colsample_bytree': 0.5456278503743982, 'min_child_weight': 5, 'gamma': 0.38859208988357485, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:32,4,35,XGBoost,0.6263,0.7683,0.6752,0.584,252,18,0.033387,0.647115,0.558041,7,0.227558,115,5,0.34,0.28,0.6314,7,0.5864,0.7543,0.6132,0.5618,0.0399,False,OK

[I 2026-07-09 10:34:32,116] Trial 35 finished with value: 0.6262924667651403 and parameters: {'n_estimators': 252, 'max_depth': 18, 'learning_rate': 0.03338698863039417, 'subsample': 0.6471154165855, 'colsample_bytree': 0.5580405334592006, 'min_child_weight': 7, 'gamma': 0.22755846330300913, 'patience': 5}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:32,4,36,XGBoost,0.6277,0.7685,0.6847,0.5795,157,17,0.021949,0.751316,0.812494,1,0.835102,108,4,0.34,0.44,0.6314,7,0.5889,0.7474,0.6234,0.5581,0.0388,False,OK

[I 2026-07-09 10:34:32,592] Trial 36 finished with value: 0.6277372262773723 and parameters: {'n_estimators': 157, 'max_depth': 17, 'learning_rate': 0.021949005453285653, 'subsample': 0.7513155725149254, 'colsample_bytree': 0.8124942042405605, 'min_child_weight': 1, 'gamma': 0.8351017619336336, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:33,4,37,XGBoost,0.6241,0.7708,0.6688,0.585,140,14,0.001743,0.740789,0.776228,3,0.883275,139,2,0.33,0.31,0.6314,7,0.5882,0.7536,0.6107,0.5674,0.0358,False,OK

[I 2026-07-09 10:34:33,040] Trial 37 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 140, 'max_depth': 14, 'learning_rate': 0.0017433392213666952, 'subsample': 0.7407888302556621, 'colsample_bytree': 0.7762284964701629, 'min_child_weight': 3, 'gamma': 0.8832751282090479, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:33,4,38,XGBoost,0.6231,0.7707,0.6688,0.5833,122,17,0.01164,0.772985,0.621511,1,0.55958,121,3,0.36,0.38,0.6314,7,0.5867,0.7499,0.6158,0.5602,0.0365,False,OK

[I 2026-07-09 10:34:33,551] Trial 38 finished with value: 0.6231454005934718 and parameters: {'n_estimators': 122, 'max_depth': 17, 'learning_rate': 0.011639535277602774, 'subsample': 0.7729848190626225, 'colsample_bytree': 0.6215113253965897, 'min_child_weight': 1, 'gamma': 0.5595802565228004, 'patience': 3}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:33,4,39,XGBoost,0.6215,0.7688,0.672,0.5781,220,20,0.182052,0.844333,0.557748,4,0.093177,14,4,0.35,0.41,0.6314,7,0.5852,0.7455,0.6158,0.5576,0.0363,False,OK

[I 2026-07-09 10:34:33,851] Trial 39 finished with value: 0.6215022091310751 and parameters: {'n_estimators': 220, 'max_depth': 20, 'learning_rate': 0.182052471998495, 'subsample': 0.844332518976549, 'colsample_bytree': 0.5577478942267987, 'min_child_weight': 4, 'gamma': 0.09317694865731689, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:34,4,40,XGBoost,0.6283,0.7663,0.6783,0.5852,267,19,0.002745,0.787265,0.886694,2,0.850252,266,2,0.33,0.39,0.6314,7,0.5891,0.7481,0.6183,0.5625,0.0392,False,OK

[I 2026-07-09 10:34:34,555] Trial 40 finished with value: 0.6283185840707964 and parameters: {'n_estimators': 267, 'max_depth': 19, 'learning_rate': 0.00274492806507511, 'subsample': 0.7872649143200356, 'colsample_bytree': 0.8866939795452284, 'min_child_weight': 2, 'gamma': 0.8502518414056954, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:35,4,41,XGBoost,0.6252,0.7645,0.6401,0.6109,354,15,0.01796,0.701666,0.983022,2,0.442705,117,3,0.45,0.35,0.6314,7,0.5946,0.7448,0.5878,0.6016,0.0306,False,OK

[I 2026-07-09 10:34:35,026] Trial 41 finished with value: 0.6251944012441679 and parameters: {'n_estimators': 354, 'max_depth': 15, 'learning_rate': 0.017959859931520255, 'subsample': 0.7016657692292105, 'colsample_bytree': 0.9830217772438141, 'min_child_weight': 2, 'gamma': 0.4427053139711453, 'patience': 3}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:35,4,42,XGBoost,0.6274,0.7709,0.6783,0.5836,292,14,0.002084,0.814077,0.735464,1,0.534983,291,2,0.33,0.38,0.6314,7,0.5894,0.7529,0.6209,0.5609,0.038,False,OK

[I 2026-07-09 10:34:35,762] Trial 42 finished with value: 0.6273932253313697 and parameters: {'n_estimators': 292, 'max_depth': 14, 'learning_rate': 0.002084172824049147, 'subsample': 0.8140767721348523, 'colsample_bytree': 0.7354641828998842, 'min_child_weight': 1, 'gamma': 0.5349831972717682, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:36,4,43,XGBoost,0.623,0.7651,0.6815,0.5737,405,19,0.017205,0.703255,0.835079,1,0.382195,121,2,0.35,0.42,0.6314,7,0.5837,0.744,0.6209,0.5508,0.0393,False,OK

[I 2026-07-09 10:34:36,318] Trial 43 finished with value: 0.6229985443959243 and parameters: {'n_estimators': 405, 'max_depth': 19, 'learning_rate': 0.017204715956775363, 'subsample': 0.703254989371153, 'colsample_bytree': 0.8350794447527311, 'min_child_weight': 1, 'gamma': 0.38219549952169996, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:37,4,44,XGBoost,0.627,0.7654,0.6879,0.576,340,17,0.004221,0.793358,0.926221,1,0.381727,339,2,0.34,0.43,0.6314,7,0.5857,0.7454,0.626,0.5503,0.0413,False,OK

[I 2026-07-09 10:34:37,278] Trial 44 finished with value: 0.6269956458635704 and parameters: {'n_estimators': 340, 'max_depth': 17, 'learning_rate': 0.004220975873133127, 'subsample': 0.7933577943409924, 'colsample_bytree': 0.9262208910985188, 'min_child_weight': 1, 'gamma': 0.38172715037899835, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:37,4,45,XGBoost,0.6283,0.7667,0.6783,0.5852,297,16,0.012463,0.892796,0.992112,4,0.807482,173,2,0.34,0.42,0.6314,7,0.5901,0.7435,0.6209,0.5622,0.0382,False,OK

[I 2026-07-09 10:34:37,809] Trial 45 finished with value: 0.6283185840707964 and parameters: {'n_estimators': 297, 'max_depth': 16, 'learning_rate': 0.01246259833907622, 'subsample': 0.8927963576611048, 'colsample_bytree': 0.9921120630562149, 'min_child_weight': 4, 'gamma': 0.8074815806320836, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:38,4,46,XGBoost,0.6283,0.765,0.6783,0.5852,134,12,0.00586,0.99061,0.992604,3,0.940065,133,4,0.34,0.36,0.6314,7,0.5935,0.743,0.626,0.5642,0.0348,False,OK

[I 2026-07-09 10:34:38,277] Trial 46 finished with value: 0.6283185840707964 and parameters: {'n_estimators': 134, 'max_depth': 12, 'learning_rate': 0.0058595625837310475, 'subsample': 0.9906095936174711, 'colsample_bytree': 0.9926038737851366, 'min_child_weight': 3, 'gamma': 0.9400649357575187, 'patience': 4}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:38,4,47,XGBoost,0.6244,0.7684,0.6752,0.5808,309,16,0.0504,0.657835,0.859832,3,0.823188,40,2,0.33,0.25,0.6314,7,0.5874,0.7494,0.6158,0.5615,0.0371,False,OK

[I 2026-07-09 10:34:38,650] Trial 47 finished with value: 0.6244477172312224 and parameters: {'n_estimators': 309, 'max_depth': 16, 'learning_rate': 0.05039983711857925, 'subsample': 0.6578352916548366, 'colsample_bytree': 0.8598321024227695, 'min_child_weight': 3, 'gamma': 0.8231882126921823, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:38,4,48,XGBoost,0.6227,0.7733,0.6465,0.6006,170,17,0.284034,0.769217,0.503083,5,0.271028,14,5,0.36,0.38,0.6314,7,0.587,0.7493,0.5878,0.5863,0.0357,False,OK

[I 2026-07-09 10:34:38,962] Trial 48 finished with value: 0.6226993865030674 and parameters: {'n_estimators': 170, 'max_depth': 17, 'learning_rate': 0.2840340578640623, 'subsample': 0.7692169095127082, 'colsample_bytree': 0.503083235733467, 'min_child_weight': 5, 'gamma': 0.2710282752563392, 'patience': 5}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:42,4,49,XGBoost,0.6277,0.7664,0.6847,0.5795,128,16,0.019146,0.66181,0.812606,1,0.72605,107,2,0.35,0.4,0.6314,7,0.5872,0.7474,0.6209,0.5571,0.0405,False,OK

[I 2026-07-09 10:34:42,450] Trial 49 finished with value: 0.6277372262773723 and parameters: {'n_estimators': 128, 'max_depth': 16, 'learning_rate': 0.019145721179340887, 'subsample': 0.6618103364530122, 'colsample_bytree': 0.8126061637716275, 'min_child_weight': 1, 'gamma': 0.7260498375413428, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:42,4,50,XGBoost,0.625,0.7708,0.6688,0.5866,226,16,0.038936,0.612484,0.553497,2,0.530631,51,2,0.35,0.27,0.6314,7,0.5861,0.7531,0.6107,0.5634,0.0389,False,OK

[I 2026-07-09 10:34:42,811] Trial 50 finished with value: 0.625 and parameters: {'n_estimators': 226, 'max_depth': 16, 'learning_rate': 0.03893644479925171, 'subsample': 0.6124841215534026, 'colsample_bytree': 0.5534973753067721, 'min_child_weight': 2, 'gamma': 0.530631030479515, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:43,4,51,XGBoost,0.6244,0.7648,0.6752,0.5808,113,17,0.050937,0.779734,0.953557,2,0.99536,44,2,0.34,0.44,0.6314,7,0.5911,0.7456,0.6234,0.5619,0.0334,False,OK

[I 2026-07-09 10:34:43,159] Trial 51 finished with value: 0.6244477172312224 and parameters: {'n_estimators': 113, 'max_depth': 17, 'learning_rate': 0.05093678193959161, 'subsample': 0.7797338110276268, 'colsample_bytree': 0.9535574578392406, 'min_child_weight': 2, 'gamma': 0.9953600322717304, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:43,4,52,XGBoost,0.6246,0.7678,0.6783,0.5788,70,8,0.026831,0.730908,0.936758,3,0.807578,69,2,0.32,0.28,0.6314,7,0.5852,0.7531,0.6158,0.5576,0.0394,False,OK

[I 2026-07-09 10:34:43,603] Trial 52 finished with value: 0.624633431085044 and parameters: {'n_estimators': 70, 'max_depth': 8, 'learning_rate': 0.026831050202074994, 'subsample': 0.7309081493265112, 'colsample_bytree': 0.9367583233971025, 'min_child_weight': 3, 'gamma': 0.8075777573915279, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:44,4,53,XGBoost,0.6271,0.7676,0.6561,0.6006,131,18,0.019192,0.87075,0.859102,1,0.760434,95,2,0.37,0.39,0.6314,7,0.5957,0.7487,0.598,0.5934,0.0314,False,OK

[I 2026-07-09 10:34:44,047] Trial 53 finished with value: 0.6270928462709284 and parameters: {'n_estimators': 131, 'max_depth': 18, 'learning_rate': 0.019191601269998766, 'subsample': 0.8707500926712879, 'colsample_bytree': 0.859101591445543, 'min_child_weight': 1, 'gamma': 0.7604336734043735, 'patience': 2}. Best is trial 7 with value: 0.631424375917768.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:44,4,54,XGBoost,0.6324,0.7713,0.6847,0.5874,99,10,0.072888,0.832238,0.898412,1,0.787882,27,2,0.34,0.42,0.6324,54,0.5872,0.7512,0.6209,0.5571,0.0451,False,OK

[I 2026-07-09 10:34:44,373] Trial 54 finished with value: 0.6323529411764706 and parameters: {'n_estimators': 99, 'max_depth': 10, 'learning_rate': 0.07288781887943684, 'subsample': 0.8322379244403183, 'colsample_bytree': 0.8984115609948832, 'min_child_weight': 1, 'gamma': 0.7878820397938634, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:44,4,55,XGBoost,0.6265,0.7705,0.6465,0.6078,208,12,0.237529,0.786014,0.911095,4,0.657911,11,2,0.46,0.3,0.6324,54,0.592,0.7419,0.5852,0.599,0.0345,False,OK

[I 2026-07-09 10:34:44,673] Trial 55 finished with value: 0.6265432098765432 and parameters: {'n_estimators': 208, 'max_depth': 12, 'learning_rate': 0.23752868313817646, 'subsample': 0.7860135188770044, 'colsample_bytree': 0.9110952307609161, 'min_child_weight': 4, 'gamma': 0.6579110496852258, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:44,4,56,XGBoost,0.6294,0.7702,0.6815,0.5847,125,9,0.113652,0.767576,0.895059,1,0.677794,17,2,0.34,0.44,0.6324,54,0.588,0.7493,0.6209,0.5584,0.0415,False,OK

[I 2026-07-09 10:34:44,980] Trial 56 finished with value: 0.6294117647058823 and parameters: {'n_estimators': 125, 'max_depth': 9, 'learning_rate': 0.11365203576710406, 'subsample': 0.7675764960854584, 'colsample_bytree': 0.8950589925113599, 'min_child_weight': 1, 'gamma': 0.6777942853344818, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:45,4,57,XGBoost,0.6296,0.7653,0.6847,0.5827,163,10,0.062569,0.904727,0.884505,2,0.814194,38,3,0.32,0.46,0.6324,54,0.5882,0.7486,0.6234,0.5568,0.0413,False,OK

[I 2026-07-09 10:34:45,333] Trial 57 finished with value: 0.6295754026354319 and parameters: {'n_estimators': 163, 'max_depth': 10, 'learning_rate': 0.06256856477054927, 'subsample': 0.904727080390425, 'colsample_bytree': 0.8845045604176773, 'min_child_weight': 2, 'gamma': 0.8141935958442706, 'patience': 3}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:45,4,58,XGBoost,0.6212,0.7688,0.6529,0.5925,158,9,0.220159,0.957992,0.805027,1,0.915071,15,4,0.37,0.44,0.6324,54,0.5942,0.7523,0.598,0.5905,0.027,False,OK

[I 2026-07-09 10:34:45,682] Trial 58 finished with value: 0.6212121212121212 and parameters: {'n_estimators': 158, 'max_depth': 9, 'learning_rate': 0.22015870760426406, 'subsample': 0.9579924552111101, 'colsample_bytree': 0.8050271243002033, 'min_child_weight': 1, 'gamma': 0.9150709090709366, 'patience': 4}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:45,4,59,XGBoost,0.6281,0.775,0.6752,0.5873,93,4,0.082582,0.813882,0.885164,1,0.565598,38,3,0.29,0.26,0.6324,54,0.591,0.7607,0.6158,0.5681,0.0372,False,OK

[I 2026-07-09 10:34:46,002] Trial 59 finished with value: 0.6281481481481481 and parameters: {'n_estimators': 93, 'max_depth': 4, 'learning_rate': 0.08258182669315535, 'subsample': 0.8138819569507058, 'colsample_bytree': 0.885164211135916, 'min_child_weight': 1, 'gamma': 0.5655980040780484, 'patience': 3}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:46,4,60,XGBoost,0.6283,0.7666,0.6783,0.5852,209,8,0.092867,0.98397,0.960075,4,0.719807,28,3,0.34,0.3,0.6324,54,0.5908,0.748,0.6209,0.5635,0.0375,False,OK

[I 2026-07-09 10:34:46,321] Trial 60 finished with value: 0.6283185840707964 and parameters: {'n_estimators': 209, 'max_depth': 8, 'learning_rate': 0.09286650674191768, 'subsample': 0.9839697712999083, 'colsample_bytree': 0.9600748837571152, 'min_child_weight': 4, 'gamma': 0.719806572273352, 'patience': 3}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:46,4,61,XGBoost,0.6261,0.7718,0.7038,0.5638,287,4,0.033332,0.77035,0.905508,4,0.749665,88,4,0.26,0.26,0.6324,54,0.5974,0.7575,0.6514,0.5517,0.0286,False,OK

[I 2026-07-09 10:34:46,718] Trial 61 finished with value: 0.6260623229461756 and parameters: {'n_estimators': 287, 'max_depth': 4, 'learning_rate': 0.0333321669292246, 'subsample': 0.7703498890197303, 'colsample_bytree': 0.9055075588683422, 'min_child_weight': 4, 'gamma': 0.7496645976451839, 'patience': 4}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:47,4,62,XGBoost,0.6283,0.7705,0.6783,0.5852,153,7,0.052838,0.978843,0.824839,3,0.870805,56,2,0.33,0.28,0.6324,54,0.5901,0.7536,0.6209,0.5622,0.0382,False,OK

[I 2026-07-09 10:34:47,063] Trial 62 finished with value: 0.6283185840707964 and parameters: {'n_estimators': 153, 'max_depth': 7, 'learning_rate': 0.052838279052744415, 'subsample': 0.9788426890361972, 'colsample_bytree': 0.8248390315888288, 'min_child_weight': 3, 'gamma': 0.8708046186691595, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:47,4,63,XGBoost,0.6228,0.7685,0.6783,0.5757,98,8,0.14383,0.722606,0.840824,1,0.725059,16,2,0.33,0.26,0.6324,54,0.5875,0.7501,0.6234,0.5556,0.0353,False,OK

[I 2026-07-09 10:34:47,369] Trial 63 finished with value: 0.6228070175438597 and parameters: {'n_estimators': 98, 'max_depth': 8, 'learning_rate': 0.14383012753102578, 'subsample': 0.7226057432193904, 'colsample_bytree': 0.8408240093541506, 'min_child_weight': 1, 'gamma': 0.7250589228562521, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:47,4,64,XGBoost,0.6277,0.7703,0.6847,0.5795,199,11,0.095434,0.857078,0.788332,1,0.761152,24,2,0.34,0.43,0.6324,54,0.5855,0.7504,0.6183,0.5561,0.0422,False,OK

[I 2026-07-09 10:34:47,723] Trial 64 finished with value: 0.6277372262773723 and parameters: {'n_estimators': 199, 'max_depth': 11, 'learning_rate': 0.09543421964812689, 'subsample': 0.8570783401866691, 'colsample_bytree': 0.7883320449208218, 'min_child_weight': 1, 'gamma': 0.7611520072644924, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:48,4,65,XGBoost,0.6236,0.7673,0.6911,0.5681,222,7,0.061013,0.629609,0.971477,4,0.450563,40,2,0.3,0.28,0.6324,54,0.5976,0.7533,0.6463,0.5558,0.0259,False,OK

[I 2026-07-09 10:34:48,046] Trial 65 finished with value: 0.6235632183908046 and parameters: {'n_estimators': 222, 'max_depth': 7, 'learning_rate': 0.06101298437795013, 'subsample': 0.6296089661173783, 'colsample_bytree': 0.9714765992841641, 'min_child_weight': 4, 'gamma': 0.45056312179819435, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:48,4,66,XGBoost,0.6279,0.7618,0.6879,0.5775,89,12,0.089746,0.968747,0.994866,2,0.780086,20,2,0.31,0.36,0.6324,54,0.5853,0.744,0.6285,0.5477,0.0426,False,OK

[I 2026-07-09 10:34:48,391] Trial 66 finished with value: 0.627906976744186 and parameters: {'n_estimators': 89, 'max_depth': 12, 'learning_rate': 0.0897461352934314, 'subsample': 0.9687471046233579, 'colsample_bytree': 0.9948660878945655, 'min_child_weight': 2, 'gamma': 0.7800860947950552, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:48,4,67,XGBoost,0.6235,0.7677,0.6752,0.5792,129,10,0.159226,0.803485,0.941397,1,0.727389,15,2,0.35,0.44,0.6324,54,0.5837,0.7474,0.6209,0.5508,0.0398,False,OK

[I 2026-07-09 10:34:48,777] Trial 67 finished with value: 0.6235294117647059 and parameters: {'n_estimators': 129, 'max_depth': 10, 'learning_rate': 0.15922597513523618, 'subsample': 0.8034845627096221, 'colsample_bytree': 0.9413966918907499, 'min_child_weight': 1, 'gamma': 0.7273891083548512, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:49,4,68,XGBoost,0.6306,0.7725,0.6688,0.5966,155,19,0.167599,0.773808,0.507311,6,0.259515,17,3,0.35,0.27,0.6324,54,0.5827,0.7535,0.6005,0.5659,0.0479,False,OK

[I 2026-07-09 10:34:49,107] Trial 68 finished with value: 0.6306306306306306 and parameters: {'n_estimators': 155, 'max_depth': 19, 'learning_rate': 0.16759914275569382, 'subsample': 0.7738075084845317, 'colsample_bytree': 0.5073107799036203, 'min_child_weight': 6, 'gamma': 0.25951489819121165, 'patience': 3}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:49,4,69,XGBoost,0.6233,0.7643,0.6401,0.6073,122,18,0.042998,0.657467,0.6433,7,0.4259,67,3,0.4,0.29,0.6324,54,0.5881,0.7471,0.5776,0.5989,0.0352,False,OK

[I 2026-07-09 10:34:49,486] Trial 69 finished with value: 0.6232558139534884 and parameters: {'n_estimators': 122, 'max_depth': 18, 'learning_rate': 0.04299848163568159, 'subsample': 0.6574668414784107, 'colsample_bytree': 0.6432997400057936, 'min_child_weight': 7, 'gamma': 0.42590014478468174, 'patience': 3}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:49,4,70,XGBoost,0.6222,0.774,0.6688,0.5817,214,18,0.165372,0.80049,0.513496,5,0.221005,17,2,0.33,0.35,0.6324,54,0.5895,0.7497,0.6158,0.5654,0.0327,False,OK

[I 2026-07-09 10:34:49,833] Trial 70 finished with value: 0.6222222222222222 and parameters: {'n_estimators': 214, 'max_depth': 18, 'learning_rate': 0.1653719753610885, 'subsample': 0.8004896186441721, 'colsample_bytree': 0.5134960857162006, 'min_child_weight': 5, 'gamma': 0.2210047345189801, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:50,4,71,XGBoost,0.6272,0.7726,0.6752,0.5856,148,20,0.16225,0.825526,0.503638,5,0.593951,20,4,0.34,0.26,0.6324,54,0.5888,0.7515,0.6158,0.5641,0.0384,False,OK

[I 2026-07-09 10:34:50,149] Trial 71 finished with value: 0.6272189349112426 and parameters: {'n_estimators': 148, 'max_depth': 20, 'learning_rate': 0.16224976868198224, 'subsample': 0.8255258385111048, 'colsample_bytree': 0.5036384560842405, 'min_child_weight': 5, 'gamma': 0.593950893686042, 'patience': 4}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:50,4,72,XGBoost,0.6269,0.7722,0.6688,0.5899,148,14,0.007256,0.666248,0.551343,3,0.575682,147,2,0.36,0.31,0.6324,54,0.589,0.7546,0.6107,0.5687,0.0379,False,OK

[I 2026-07-09 10:34:50,616] Trial 72 finished with value: 0.6268656716417911 and parameters: {'n_estimators': 148, 'max_depth': 14, 'learning_rate': 0.007255719762404002, 'subsample': 0.6662481377539226, 'colsample_bytree': 0.5513430038536501, 'min_child_weight': 3, 'gamma': 0.5756815008190241, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:50,4,73,XGBoost,0.6233,0.7662,0.6401,0.6073,80,16,0.152112,0.792329,0.594418,7,0.127003,17,3,0.39,0.28,0.6324,54,0.5925,0.7469,0.5827,0.6026,0.0308,False,OK

[I 2026-07-09 10:34:50,943] Trial 73 finished with value: 0.6232558139534884 and parameters: {'n_estimators': 80, 'max_depth': 16, 'learning_rate': 0.15211243890065193, 'subsample': 0.7923291563103317, 'colsample_bytree': 0.5944176173256877, 'min_child_weight': 7, 'gamma': 0.12700280734049468, 'patience': 3}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:51,4,74,XGBoost,0.6281,0.7719,0.6752,0.5873,104,3,0.126625,0.534437,0.658147,1,0.261151,35,5,0.28,0.31,0.6324,54,0.5902,0.7593,0.6158,0.5667,0.0379,False,OK

[I 2026-07-09 10:34:51,251] Trial 74 finished with value: 0.6281481481481481 and parameters: {'n_estimators': 104, 'max_depth': 3, 'learning_rate': 0.12662523584923827, 'subsample': 0.5344368730696502, 'colsample_bytree': 0.6581468648802479, 'min_child_weight': 1, 'gamma': 0.26115110298680566, 'patience': 5}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:51,4,75,XGBoost,0.6287,0.7692,0.6847,0.5811,72,10,0.126779,0.854358,0.80058,3,0.751685,20,2,0.32,0.26,0.6324,54,0.5861,0.7485,0.6234,0.553,0.0425,False,OK

[I 2026-07-09 10:34:51,600] Trial 75 finished with value: 0.6286549707602339 and parameters: {'n_estimators': 72, 'max_depth': 10, 'learning_rate': 0.12677948207641537, 'subsample': 0.854358186890428, 'colsample_bytree': 0.8005804870631662, 'min_child_weight': 3, 'gamma': 0.7516851652118598, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:51,4,76,XGBoost,0.6241,0.7713,0.6688,0.585,195,20,0.0474,0.875172,0.509488,7,0.237114,69,4,0.35,0.36,0.6324,54,0.5892,0.7504,0.6132,0.5671,0.0348,False,OK

[I 2026-07-09 10:34:51,991] Trial 76 finished with value: 0.6240713224368499 and parameters: {'n_estimators': 195, 'max_depth': 20, 'learning_rate': 0.04740042211908493, 'subsample': 0.8751717625032648, 'colsample_bytree': 0.5094880046334794, 'min_child_weight': 7, 'gamma': 0.23711367774498815, 'patience': 4}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:52,4,77,XGBoost,0.6279,0.7677,0.6879,0.5775,223,11,0.024884,0.760811,0.815892,2,0.95503,91,3,0.32,0.3,0.6324,54,0.5871,0.7502,0.626,0.5528,0.0408,False,OK

[I 2026-07-09 10:34:52,535] Trial 77 finished with value: 0.627906976744186 and parameters: {'n_estimators': 223, 'max_depth': 11, 'learning_rate': 0.024883701953006453, 'subsample': 0.7608114421540741, 'colsample_bytree': 0.8158917203608129, 'min_child_weight': 2, 'gamma': 0.9550296245662631, 'patience': 3}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:53,4,78,XGBoost,0.625,0.7701,0.6688,0.5866,157,17,0.121599,0.767432,0.522983,5,0.337081,20,3,0.36,0.27,0.6324,54,0.5851,0.7518,0.6081,0.5637,0.0399,False,OK

[I 2026-07-09 10:34:53,700] Trial 78 finished with value: 0.625 and parameters: {'n_estimators': 157, 'max_depth': 17, 'learning_rate': 0.12159857480581629, 'subsample': 0.7674318016059104, 'colsample_bytree': 0.5229834221718968, 'min_child_weight': 5, 'gamma': 0.3370810846252206, 'patience': 3}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:54,4,79,XGBoost,0.6259,0.7755,0.6688,0.5882,64,5,0.072303,0.612309,0.526411,2,0.999788,41,2,0.34,0.36,0.6324,54,0.5875,0.7584,0.6107,0.566,0.0384,False,OK

[I 2026-07-09 10:34:54,945] Trial 79 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 64, 'max_depth': 5, 'learning_rate': 0.07230306253074964, 'subsample': 0.6123089352692415, 'colsample_bytree': 0.5264109400254153, 'min_child_weight': 2, 'gamma': 0.9997880756517732, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:55,4,80,XGBoost,0.6248,0.7714,0.6975,0.5659,148,12,0.004297,0.577119,0.659931,1,0.63711,147,2,0.31,0.31,0.6324,54,0.5962,0.7533,0.6463,0.5534,0.0286,False,OK

[I 2026-07-09 10:34:55,747] Trial 80 finished with value: 0.6248216833095578 and parameters: {'n_estimators': 148, 'max_depth': 12, 'learning_rate': 0.004297092681569483, 'subsample': 0.5771193967316207, 'colsample_bytree': 0.6599306722136912, 'min_child_weight': 1, 'gamma': 0.6371102341118524, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:56,4,81,XGBoost,0.6248,0.7671,0.6815,0.5768,246,17,0.007874,0.658819,0.74795,1,0.455915,245,2,0.35,0.38,0.6324,54,0.5872,0.7485,0.6209,0.5571,0.0376,False,OK

[I 2026-07-09 10:34:56,481] Trial 81 finished with value: 0.6248175182481752 and parameters: {'n_estimators': 246, 'max_depth': 17, 'learning_rate': 0.007873893321647162, 'subsample': 0.6588189205624531, 'colsample_bytree': 0.7479498674648014, 'min_child_weight': 1, 'gamma': 0.45591522500673665, 'patience': 2}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:56,4,82,XGBoost,0.6259,0.7712,0.6688,0.5882,63,6,0.014278,0.909026,0.774444,4,0.679367,62,4,0.34,0.29,0.6324,54,0.5882,0.7532,0.6107,0.5674,0.0377,False,OK

[I 2026-07-09 10:34:56,837] Trial 82 finished with value: 0.6259314456035767 and parameters: {'n_estimators': 63, 'max_depth': 6, 'learning_rate': 0.014277928043233185, 'subsample': 0.9090261945308207, 'colsample_bytree': 0.7744439933860179, 'min_child_weight': 4, 'gamma': 0.6793669138782146, 'patience': 4}. Best is trial 54 with value: 0.6323529411764706.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:57,4,83,XGBoost,0.6325,0.7652,0.6879,0.5854,246,12,0.013943,0.928962,0.919437,1,0.761104,120,2,0.35,0.45,0.6325,83,0.5928,0.7493,0.626,0.5629,0.0397,False,OK

[I 2026-07-09 10:34:57,356] Trial 83 finished with value: 0.6325036603221084 and parameters: {'n_estimators': 246, 'max_depth': 12, 'learning_rate': 0.01394265775616684, 'subsample': 0.9289623807763887, 'colsample_bytree': 0.9194366836902442, 'min_child_weight': 1, 'gamma': 0.7611035875898916, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:57,4,84,XGBoost,0.6281,0.767,0.6911,0.5756,114,11,0.02005,0.882093,0.811616,2,0.817183,113,3,0.32,0.44,0.6325,83,0.5874,0.7491,0.6285,0.5513,0.0407,False,OK

[I 2026-07-09 10:34:57,800] Trial 84 finished with value: 0.6280752532561505 and parameters: {'n_estimators': 114, 'max_depth': 11, 'learning_rate': 0.0200498464837498, 'subsample': 0.8820930483108277, 'colsample_bytree': 0.8116156467840467, 'min_child_weight': 2, 'gamma': 0.8171828022983881, 'patience': 3}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:58,4,85,XGBoost,0.6325,0.7643,0.6879,0.5854,223,12,0.006223,0.933912,0.838983,2,0.776278,222,2,0.33,0.4,0.6325,83,0.5904,0.7474,0.6234,0.5606,0.0421,False,OK

[I 2026-07-09 10:34:58,443] Trial 85 finished with value: 0.6325036603221084 and parameters: {'n_estimators': 223, 'max_depth': 12, 'learning_rate': 0.0062234456637886345, 'subsample': 0.9339120236199924, 'colsample_bytree': 0.8389827390102579, 'min_child_weight': 2, 'gamma': 0.7762778322389531, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:59,4,86,XGBoost,0.6272,0.7697,0.6752,0.5856,270,8,0.003374,0.908483,0.872618,1,0.707162,269,2,0.33,0.39,0.6325,83,0.5892,0.7562,0.6132,0.5671,0.038,False,OK

[I 2026-07-09 10:34:59,026] Trial 86 finished with value: 0.6272189349112426 and parameters: {'n_estimators': 270, 'max_depth': 8, 'learning_rate': 0.0033744563103592835, 'subsample': 0.9084832140452042, 'colsample_bytree': 0.8726182327739755, 'min_child_weight': 1, 'gamma': 0.7071624612228042, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:34:59,4,87,XGBoost,0.6305,0.765,0.6847,0.5842,263,11,0.012549,0.921291,0.855192,2,0.814401,159,2,0.33,0.42,0.6325,83,0.5887,0.7474,0.6209,0.5596,0.0418,False,OK

[I 2026-07-09 10:34:59,532] Trial 87 finished with value: 0.6304985337243402 and parameters: {'n_estimators': 263, 'max_depth': 11, 'learning_rate': 0.012548689868779085, 'subsample': 0.921291446156965, 'colsample_bytree': 0.8551919242456507, 'min_child_weight': 2, 'gamma': 0.8144006476200799, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:00,4,88,XGBoost,0.627,0.7649,0.6879,0.576,289,14,0.007587,0.984954,0.846871,1,0.611523,229,3,0.35,0.42,0.6325,83,0.593,0.7466,0.6285,0.5614,0.034,False,OK

[I 2026-07-09 10:35:00,252] Trial 88 finished with value: 0.6269956458635704 and parameters: {'n_estimators': 289, 'max_depth': 14, 'learning_rate': 0.007586755771926678, 'subsample': 0.9849542502293092, 'colsample_bytree': 0.846870558795527, 'min_child_weight': 1, 'gamma': 0.611523447683211, 'patience': 3}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:00,4,89,XGBoost,0.6325,0.7656,0.6879,0.5854,127,13,0.008434,0.952148,0.911069,2,0.648605,126,2,0.34,0.39,0.6325,83,0.588,0.7455,0.6209,0.5584,0.0446,False,OK

[I 2026-07-09 10:35:00,783] Trial 89 finished with value: 0.6325036603221084 and parameters: {'n_estimators': 127, 'max_depth': 13, 'learning_rate': 0.008434090234361731, 'subsample': 0.9521479708879038, 'colsample_bytree': 0.9110694968257698, 'min_child_weight': 2, 'gamma': 0.6486054851584341, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:01,4,90,XGBoost,0.6307,0.7659,0.6879,0.5822,112,14,0.006867,0.976666,0.90297,2,0.645365,111,2,0.33,0.37,0.6325,83,0.5885,0.7431,0.626,0.5553,0.0421,False,OK

[I 2026-07-09 10:35:01,294] Trial 90 finished with value: 0.6306569343065693 and parameters: {'n_estimators': 112, 'max_depth': 14, 'learning_rate': 0.006866964294591304, 'subsample': 0.9766664397939623, 'colsample_bytree': 0.9029696840740885, 'min_child_weight': 2, 'gamma': 0.6453647913620648, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:01,4,91,XGBoost,0.6268,0.7659,0.6847,0.578,139,15,0.006169,0.980124,0.8998,1,0.743537,138,2,0.34,0.39,0.6325,83,0.5892,0.7478,0.626,0.5566,0.0376,False,OK

[I 2026-07-09 10:35:01,846] Trial 91 finished with value: 0.6268221574344023 and parameters: {'n_estimators': 139, 'max_depth': 15, 'learning_rate': 0.006168983430998534, 'subsample': 0.9801237305402659, 'colsample_bytree': 0.8998001101710245, 'min_child_weight': 1, 'gamma': 0.7435367349781805, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:02,4,92,XGBoost,0.6254,0.7695,0.6752,0.5824,239,9,0.003264,0.937915,0.800808,6,0.852422,238,2,0.33,0.28,0.6325,83,0.5861,0.7545,0.6107,0.5634,0.0393,False,OK

[I 2026-07-09 10:35:02,440] Trial 92 finished with value: 0.6253687315634219 and parameters: {'n_estimators': 239, 'max_depth': 9, 'learning_rate': 0.0032637142143137647, 'subsample': 0.9379151495329854, 'colsample_bytree': 0.8008084299218082, 'min_child_weight': 6, 'gamma': 0.8524223234242224, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:02,4,93,XGBoost,0.6324,0.7659,0.6847,0.5874,333,11,0.03012,0.887357,0.858855,1,0.863172,67,2,0.34,0.44,0.6325,83,0.587,0.7502,0.6183,0.5586,0.0454,False,OK

[I 2026-07-09 10:35:02,853] Trial 93 finished with value: 0.6323529411764706 and parameters: {'n_estimators': 333, 'max_depth': 11, 'learning_rate': 0.03011955226438948, 'subsample': 0.887357491251666, 'colsample_bytree': 0.8588553953952555, 'min_child_weight': 1, 'gamma': 0.8631718281705475, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:03,4,94,XGBoost,0.6277,0.7667,0.6847,0.5795,362,11,0.07878,0.930988,0.953943,2,0.802977,29,2,0.32,0.44,0.6325,83,0.5868,0.7441,0.6234,0.5543,0.0409,False,OK

[I 2026-07-09 10:35:03,189] Trial 94 finished with value: 0.6277372262773723 and parameters: {'n_estimators': 362, 'max_depth': 11, 'learning_rate': 0.07877985716820106, 'subsample': 0.9309883069360579, 'colsample_bytree': 0.9539432968547076, 'min_child_weight': 2, 'gamma': 0.8029770466223474, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:03,4,95,XGBoost,0.6296,0.7656,0.6847,0.5827,427,14,0.011482,0.905792,0.84593,2,0.932082,194,3,0.34,0.46,0.6325,83,0.5887,0.7457,0.6209,0.5596,0.0409,False,OK

[I 2026-07-09 10:35:03,760] Trial 95 finished with value: 0.6295754026354319 and parameters: {'n_estimators': 427, 'max_depth': 14, 'learning_rate': 0.011481927420609413, 'subsample': 0.9057920593224401, 'colsample_bytree': 0.8459296389120404, 'min_child_weight': 2, 'gamma': 0.932082216749427, 'patience': 3}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:04,4,96,XGBoost,0.627,0.7688,0.6879,0.576,97,13,0.00772,0.955296,0.973484,4,0.778891,96,2,0.31,0.34,0.6325,83,0.5867,0.741,0.6285,0.5501,0.0403,False,OK

[I 2026-07-09 10:35:04,184] Trial 96 finished with value: 0.6269956458635704 and parameters: {'n_estimators': 97, 'max_depth': 13, 'learning_rate': 0.007719516812279004, 'subsample': 0.9552961286644824, 'colsample_bytree': 0.9734837437645529, 'min_child_weight': 4, 'gamma': 0.7788913587301398, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:04,4,97,XGBoost,0.6288,0.7665,0.6879,0.5791,212,13,0.010388,0.979142,0.873034,2,0.984259,211,2,0.31,0.4,0.6325,83,0.5861,0.7468,0.6234,0.553,0.0427,False,OK

[I 2026-07-09 10:35:04,764] Trial 97 finished with value: 0.62882096069869 and parameters: {'n_estimators': 212, 'max_depth': 13, 'learning_rate': 0.010388053094225682, 'subsample': 0.9791418643788098, 'colsample_bytree': 0.8730338621186291, 'min_child_weight': 2, 'gamma': 0.9842586433094276, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:05,4,98,XGBoost,0.625,0.7694,0.7006,0.5641,389,8,0.014598,0.825833,0.766287,3,0.645971,160,2,0.29,0.26,0.6325,83,0.5944,0.7518,0.6489,0.5484,0.0306,False,OK

[I 2026-07-09 10:35:05,231] Trial 98 finished with value: 0.625 and parameters: {'n_estimators': 389, 'max_depth': 8, 'learning_rate': 0.014597745661409412, 'subsample': 0.8258333626712179, 'colsample_bytree': 0.7662868214223287, 'min_child_weight': 3, 'gamma': 0.6459705039605581, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:05,4,99,XGBoost,0.6263,0.77,0.6752,0.584,278,9,0.01422,0.895917,0.707162,2,0.97826,142,2,0.33,0.39,0.6325,83,0.5888,0.7531,0.6158,0.5641,0.0375,False,OK

[I 2026-07-09 10:35:05,685] Trial 99 finished with value: 0.6262924667651403 and parameters: {'n_estimators': 278, 'max_depth': 9, 'learning_rate': 0.014219900206480616, 'subsample': 0.8959170964001025, 'colsample_bytree': 0.70716201880626, 'min_child_weight': 2, 'gamma': 0.9782603649659336, 'patience': 2}. Best is trial 83 with value: 0.6325036603221084.

\n============================================================
🎉 XGB NAS COMPLETE
============================================================
Best Trial: 83
Best F1: 0.6325
Best Params: {'n_estimators': 246, 'max_depth': 12, 'learning_rate': 0.01394265775616684, 'subsample': 0.9289623807763887, 'colsample_bytree': 0.9194366836902442, 'min_child_weight': 1, 'gamma': 0.7611035875898916, 'patience': 2}
💾 Saved: nas_rf_results.csv, nas_xgb_results.csv
💾 Saved: nas_rf_trial_log.csv, nas_xgb_trial_log.csv

============================================================
📋 NAS RESULTS COMPARISON
============================================================

Model           Best Val F1  Best Trial
----------------------------------------
RandomForest    0.6307       14
XGBoost         0.6325       83

📊 Best RF Params:
   n_estimators: 222
   max_depth: 13
   min_samples_split: 11
   min_samples_leaf: 5

📊 Best XGB Params:
   n_estimators: 246
   max_depth: 12
   learning_rate: 0.01394265775616684
   subsample: 0.9289623807763887
   colsample_bytree: 0.9194366836902442
   min_child_weight: 1
   gamma: 0.7611035875898916
   patience: 2

📊 RF Trial Log (sorted by val_f1):

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:32:29,4,14,RandomForest,0.6307,0.7673,0.7070,0.5692,222,13,11,5,0.28,0.29,0.6307,14,0.5944,0.7485,0.6489,0.5484,0.0363,False,OK
1,2026-07-09,10:33:19,4,60,RandomForest,0.6307,0.7674,0.7070,0.5692,454,14,2,4,0.29,0.29,0.6307,14,0.5977,0.7455,0.6539,0.5503,0.0330,False,OK
2,2026-07-09,10:32:57,4,41,RandomForest,0.6302,0.7625,0.6783,0.5884,492,18,5,3,0.36,0.38,0.6307,14,0.5915,0.7403,0.6209,0.5648,0.0387,False,OK
3,2026-07-09,10:32:24,4,8,RandomForest,0.6298,0.7692,0.7070,0.5678,187,11,10,3,0.26,0.26,0.6298,8,0.5986,0.7546,0.6565,0.5501,0.0312,False,OK
4,2026-07-09,10:33:03,4,46,RandomForest,0.6298,0.7687,0.7070,0.5678,480,13,3,5,0.27,0.29,0.6307,14,0.5940,0.7483,0.6514,0.5458,0.0358,False,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026-07-09,10:33:30,4,69,RandomForest,0.6220,0.7705,0.6656,0.5838,468,3,3,8,0.35,0.36,0.6307,14,0.5890,0.7585,0.6107,0.5687,0.0331,False,OK
96,2026-07-09,10:34:02,4,93,RandomForest,0.6215,0.7561,0.6720,0.5781,443,17,2,1,0.36,0.40,0.6307,14,0.5794,0.7370,0.6081,0.5532,0.0421,False,OK
97,2026-07-09,10:32:48,4,33,RandomForest,0.6212,0.7623,0.6815,0.5707,145,20,19,1,0.34,0.41,0.6307,14,0.5846,0.7407,0.6285,0.5465,0.0366,False,OK
98,2026-07-09,10:32:17,4,1,RandomForest,0.6180,0.7520,0.6465,0.5918,500,20,2,1,0.41,0.40,0.6248,0,0.5802,0.7287,0.5802,0.5802,0.0378,True,OK
99,2026-07-09,10:34:07,4,97,RandomForest,0.6156,0.7688,0.6401,0.5929,192,2,13,2,0.41,0.38,0.6307,14,0.5783,0.7560,0.5776,0.5791,0.0373,False,OK

📊 XGB Trial Log (sorted by val_f1):

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,10:35:00,4,89,XGBoost,0.6325,0.7656,0.6879,0.5854,127,13,0.008434,0.952148,0.911069,2,0.648605,126,2,0.34,0.39,0.6325,83,0.5880,0.7455,0.6209,0.5584,0.0446,False,OK
1,2026-07-09,10:34:57,4,83,XGBoost,0.6325,0.7652,0.6879,0.5854,246,12,0.013943,0.928962,0.919437,1,0.761104,120,2,0.35,0.45,0.6325,83,0.5928,0.7493,0.6260,0.5629,0.0397,False,OK
2,2026-07-09,10:34:58,4,85,XGBoost,0.6325,0.7643,0.6879,0.5854,223,12,0.006223,0.933912,0.838983,2,0.776278,222,2,0.33,0.40,0.6325,83,0.5904,0.7474,0.6234,0.5606,0.0421,False,OK
3,2026-07-09,10:34:44,4,54,XGBoost,0.6324,0.7713,0.6847,0.5874,99,10,0.072888,0.832238,0.898412,1,0.787882,27,2,0.34,0.42,0.6324,54,0.5872,0.7512,0.6209,0.5571,0.0451,False,OK
4,2026-07-09,10:35:02,4,93,XGBoost,0.6324,0.7659,0.6847,0.5874,333,11,0.030120,0.887357,0.858855,1,0.863172,67,2,0.34,0.44,0.6325,83,0.5870,0.7502,0.6183,0.5586,0.0454,False,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026-07-09,10:34:33,4,39,XGBoost,0.6215,0.7688,0.6720,0.5781,220,20,0.182052,0.844333,0.557748,4,0.093177,14,4,0.35,0.41,0.6314,7,0.5852,0.7455,0.6158,0.5576,0.0363,False,OK
96,2026-07-09,10:34:17,4,8,XGBoost,0.6212,0.7619,0.6815,0.5707,79,20,0.246597,0.904199,0.652307,1,0.684233,9,3,0.34,0.45,0.6314,7,0.5850,0.7495,0.6260,0.5491,0.0362,False,OK
97,2026-07-09,10:34:45,4,58,XGBoost,0.6212,0.7688,0.6529,0.5925,158,9,0.220159,0.957992,0.805027,1,0.915071,15,4,0.37,0.44,0.6324,54,0.5942,0.7523,0.5980,0.5905,0.0270,False,OK
98,2026-07-09,10:34:17,4,9,XGBoost,0.6211,0.7691,0.6943,0.5619,105,11,0.001217,0.954660,0.629390,7,0.311711,104,4,0.32,0.32,0.6314,7,0.5976,0.7523,0.6463,0.5558,0.0234,False,OK
99,2026-07-09,10:34:18,4,11,XGBoost,0.6206,0.7625,0.6433,0.5994,322,16,0.053192,0.774809,0.637993,1,0.141313,45,5,0.41,0.42,0.6314,7,0.5934,0.7433,0.5903,0.5964,0.0272,False,OK

#freeze

In [22]:
%pip freeze > "{project_path}requirement/freez/NASEnhancedPretraindMLModleAdvance-lock.txt"

In [23]:
end = time.time()
elapsed = end - start_time

hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)

print(f"Total Time = {hours}h {minutes}m {seconds}s")

Total Time = 0h 7m 18s