This is to find best parm based on TimeNet

#**Pre-request**

##Mount google drive

In [1]:
### **Mount** Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##Install pakages

In [2]:
#Install pakages
project_path = "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/"
!cat "{project_path}requirement/Install/NASEnhancedPretraindMLModleAdvance.txt"
!pip install  -r "{project_path}requirement/Install/NASEnhancedPretraindMLModleAdvance.txt" --no-cache-dir
%cd $project_path

torch
transformers
huggingface_hub
datasets
timm
patool
sktime
reformer_pytorch
optuna
ptflopsRequirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2.11.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (5.12.1)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.20.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (4.0.0)
Requirement already satisfied: timm in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 5)) (1.0.27)
Collecting patool (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 6))
  Downloading patool-4.0.5-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting sktime (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7))
  Downloading sktime-1.0.1-py3-none-any.whl.metadata (28 kB)
Collecting reformer_pytorch (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading reformer_pytorch-1.4.4-py3-none-any.whl.metadata (764 bytes)
Collecting optuna (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting ptflops (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 10))
  Downloading ptflops-0.7.5-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.29.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (0.28.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (0.70.16)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from timm->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 5)) (0.26.0+cu128)
Requirement already satisfied: joblib<1.6,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.5.3)
Collecting scikit-base<1.1.0,>=1.0.0 (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7))
  Downloading scikit_base-1.0.2-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: scikit-learn<1.8.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.6.1)
Requirement already satisfied: scipy<2.0.0,>=1.2 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.16.3)
Collecting axial-positional-embedding>=0.1.0 (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading axial_positional_embedding-0.3.12-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8)) (0.8.2)
Collecting local-attention (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading local_attention-1.11.2-py3-none-any.whl.metadata (929 bytes)
Collecting product-key-memory (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading product_key_memory-0.3.0-py3-none-any.whl.metadata (4.9 kB)
Collecting alembic>=1.5.0 (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9)) (2.0.51)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9)) (1.1.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.5.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.9.0.post0)

##Import  libs

In [3]:
# =====================================================
# 📦 Standard Library
# =====================================================
import os
import sys
import time
import logging
import hashlib
import shutil
import subprocess
import warnings
from datetime import datetime

# Start timer
start_time = time.time()

# =====================================================
# 🧮 Data & Visualization
# =====================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yaml

# Pandas display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# =====================================================
# ⚙️ Machine Learning - Scikit-learn
# =====================================================
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler
from sklearn.utils import class_weight
from sklearn.covariance import EmpiricalCovariance
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)

# =====================================================
# 🌲 XGBoost
# =====================================================
from xgboost import XGBClassifier
import joblib

# =====================================================
# 🔥 Deep Learning - PyTorch
# =====================================================
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from torch.cuda.amp import autocast

# =====================================================
# 🤖 Deep Learning - TensorFlow / Keras
# =====================================================
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Dense, Masking, Dropout, Layer
from tensorflow.keras.optimizers import Adam

# =====================================================
# 🤗 Transformers & Time Series
# =====================================================
from transformers import AutoModel
from sktime.datasets import load_from_tsfile_to_dataframe
# from mamba_ssm import Mamba  # Uncomment if needed

# =====================================================
# 🧠 Explainability
# =====================================================
import shap

# =====================================================
# 📊 Google Colab Specific
# =====================================================
from google.colab import data_table
data_table.enable_dataframe_formatter()
try:
    from google.colab import data_table
    data_table.enable_dataframe_formatter()
    data_table.DataTable.max_columns = 50
    data_table.DataTable.max_rows = 150
except ImportError:
    pass

from tqdm import tqdm

print("✅ All imports loaded successfully!")

✅ All imports loaded successfully!

##Confirmation setup

In [4]:
# =====================================================
# 🎲 Random Seeds (Reproducibility)
# =====================================================
!nvidia-smi                # confirm GPU
!pip show torch  # confirm versions
torch.manual_seed(42)
np.random.seed(42)

Wed Jul  8 17:46:37 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:00:05.0 Off |                    0 |
| N/A   33C    P0             54W /  400W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Name: torch
Version: 2.11.0+cu128
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org
Author:
Author-email: PyTorch Team <packages@pytorch.org>
License: BSD-3-Clause
Location: /usr/local/lib/python3.12/dist-packages
Requires: cuda-bindings, cuda-toolkit, filelock, fsspec, jinja2, networkx, nvidia-cudnn-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvshmem-cu12, setuptools, sympy, triton, typing-extensions
Required-by: accelerate, axial_positional_embedding, CoLT5-attention, fastai, hyper-connections, local-attention, peft, product_key_memory, ptflops, reformer-pytorch, sentence-transformers, timm, torch-einops-utils, torchdata, torchvision

## Enable Config

In [5]:

logger = logging.getLogger(__name__)

def load_config(config_path="configs/baseline.yaml"):
    """Load YAML config file and expand ${root_path} placeholders."""
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    logger.info(f"✅ Loaded config from {config_path}")

    # --- Expand ${root_path} placeholders ---
    root = config.get("root_path", "")

    def expand_paths(obj):
        if isinstance(obj, dict):
            return {k: expand_paths(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [expand_paths(i) for i in obj]
        elif isinstance(obj, str) and "${root_path}" in obj:
            return obj.replace("${root_path}", root)
        else:
            return obj

    config = expand_paths(config)
    return config
config = load_config(os.path.join(project_path, "configs", "baseline.yaml"))

## Set Variables

In [6]:


#limit = config['ML']['limit']
n_trials=100
#
# ==========================================================
# UNIFIED HYPERPARAMETERS (Match TimesNet NAS Best)
# ==========================================================
# ==========================================================
# 🔧 UNIFIED HYPERPARAMETERS (Match TimesNet NAS Best)
# ==========================================================

# ----------------------------------------------------------
# 📏 Sequence Settings
# ----------------------------------------------------------
max_seq_len = 4                  # Maximum sequence length
recent_mode = False               # False → oldest mode, True → recent-window mode
epochs=20
# ----------------------------------------------------------
# 🏗️ Model Architecture (Shared across LSTM/Transformer/TimesNet)
# ----------------------------------------------------------

# ----------------------------------------------------------
# 📊 Evaluation Settings
# ----------------------------------------------------------
threshold = 0.5                   # Default classification threshold
opt_metric = "f1"                 # Optimization metric for model selection
early_stop_metric = 'val_accuracy'# Metric for early stopping
correlation_threshold = 0.85      # Feature correlation threshold
best_threshold = 0.5              # Best threshold (general)


# ----------------------------------------------------------
# 💾 Paths
# ----------------------------------------------------------
model_path = config['ML']['models']

# ==========================================================
# ✅ Configuration Summary
# ==========================================================
print("="*60)
print("📋 CONFIGURATION SUMMARY")
print("="*60)
print(f"  Sequence length:  {max_seq_len}")
print(f"  Mode:             {'Recent' if recent_mode else 'Oldest'}")
print(f"  Threshold:        {threshold}")
print(f"  Model path:       {model_path}")
print("="*60)

# Global unified results table for all models
results_table = pd.DataFrame(columns=["Round", "AUC", "Recall", "F1", "Model"])
summary = pd.DataFrame(
    columns=[
        "Model",
        "AUC",
        "Recall",
        "Precision",
        "F1",
        "threshold"
    ]
)

============================================================
📋 CONFIGURATION SUMMARY
============================================================
  Sequence length:  4
  Mode:             Oldest
  Threshold:        0.5
  Model path:       /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/models/
============================================================

##Split users level

In [7]:

# user_path = config['ML']['Events']['base_path'] + config['ML']['Events']['files']['user']
# df_user = pd.read_csv(user_path)
# print(f"✅ Loaded transactional user dataset: {df_user.shape}")



# # Aggregate to one row per user (max label = 1 if any fraud)
# user_labels = df_user.groupby("phone_no_m")["label"].max()
# print(f"👥 Unique users for splitting: {len(user_labels)}")

# # ==============================================================
# # 2️⃣ Create user-level split (stratified, no leakage)
# # ==============================================================

# fraud_users = user_labels[user_labels == 1].index
# normal_users = user_labels[user_labels == 0].index

# fraud_train, fraud_test = train_test_split(fraud_users, test_size=0.2, random_state=42)
# normal_train, normal_test = train_test_split(normal_users, test_size=0.2, random_state=42)

# train_users = set(fraud_train) | set(normal_train)
# test_users  = set(fraud_test)  | set(normal_test)

# # ==============================================================
# # 3️⃣ Save unified split (shared across LSTM / RF / XGB)
# # ==============================================================

# split_dir = "splits/shared_user_split_v1"
# os.makedirs(split_dir, exist_ok=True)

# train_split_file = f"{split_dir}/train_users.csv"
# test_split_file  = f"{split_dir}/test_users.csv"
# val_split_file   = f"{split_dir}/val_users.csv"

# pd.DataFrame({"phone_no_m": sorted(train_users)}).to_csv(train_split_file, index=False)
# pd.DataFrame({"phone_no_m": sorted(test_users)}).to_csv(test_split_file, index=False)
# ==============================================================
# 4️⃣ Summary
# ==============================================================

# print("\n👥 Users Summary:")
# print(f"   Total : {len(user_labels):,}")
# print(f"   Fraud : {len(fraud_users):,} ({len(fraud_users)/len(user_labels)*100:.2f}%)")
# print(f"   Normal: {len(normal_users):,} ({len(normal_users)/len(user_labels)*100:.2f}%)")

# print("\n📂 Split saved to /splits/:")
# print(f"   Train users: {len(train_users)}")
# print(f"   Test  users: {len(test_users)}")
# print(f"   Fraud ratio train: {len(fraud_train)/len(train_users)*100:.2f}%")
# print(f"   Fraud ratio test : {len(fraud_test)/len(test_users)*100:.2f}%")

## Helpers

### evaluate_global

In [8]:
def evaluate_global(model, X_test, y_test, model_name="Model", threshold=0.5):
    """
    Generic evaluator for both classic ML models and neural networks.
    """
    print(f"\n📊 Evaluation threshold is: {threshold}")

    # ---- Predict probabilities ----
    if hasattr(model, "predict_proba"):
        # For sklearn-style models
        y_pred_prob = model.predict_proba(X_test)[:, 1]
    else:
        # For neural nets (e.g., Keras)
        preds = model.predict(X_test)
        if preds.shape[-1] == 2:
            # 2-class softmax output
            y_pred_prob = preds[:, 1]
        else:
            # Single sigmoid output
            y_pred_prob = preds.ravel()

    # ... rest of function unchanged
    # ---- Predict classes ----
    y_pred = (y_pred_prob > threshold).astype(int)

    # ---- Metrics ----
    auc = roc_auc_score(y_test, y_pred_prob)
    #recall = recall_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred, zero_division=0)

    precision = precision_score(y_test, y_pred, zero_division=0)
    #f1 = f1_score(y_test, y_pred)
    f1     = f1_score(y_test, y_pred, zero_division=0)

    report = classification_report(y_test, y_pred, digits=4)
    cm = confusion_matrix(y_test, y_pred)

    # ---- Display ----
    print(f"\n📊 Classification Report — {model_name}")
    print(report)
    print(f"AUC: {auc:.4f} | Recall: {recall:.4f} | Precision: {precision:.4f} | F1: {f1:.4f}")

    # ---- Confusion Matrix ----
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Normal (0)", "Fraud (1)"])
    disp.plot(cmap="Blues")
    plt.title(f"Confusion Matrix — {model_name}")
    plt.grid(False)
    plt.show()

    # ---- Summary Dictionary ----
    return {
        "Model": model_name,
        "AUC": auc,
        "Recall": recall,
        "Precision": precision,
        "F1": f1,
        "threshold": threshold
    }

### append_to_summary

In [9]:

def append_to_summary(summary, model_name, results):
    """
    Appends or updates the summary table with model results.
    Works with both capitalized and lowercase keys automatically.
    """
    # ✅ Create summary DataFrame if missing
    if summary is None or not isinstance(summary, pd.DataFrame):
          summary = pd.DataFrame(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])
    # Ensure "Model" column exists (prevents KeyError)
    if "Model" not in summary.columns:
        summary = pd.DataFrame(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])

    # ✅ Normalize key names to lowercase
    results = {k.lower(): v for k, v in results.items()}

    # ✅ Remove any existing row for the same model
    summary = summary[summary["Model"] != model_name]

    # ✅ Add new row (robust to missing values)
    row = {
        "Model": model_name,
        "AUC": round(results.get("auc", np.nan), 4) if not pd.isna(results.get("auc", np.nan)) else np.nan,
        "Recall": round(results.get("recall", np.nan), 4) if not pd.isna(results.get("recall", np.nan)) else np.nan,
        "Precision": round(results.get("precision", np.nan), 4) if not pd.isna(results.get("precision", np.nan)) else np.nan,
        "F1": round(results.get("f1", np.nan), 4) if not pd.isna(results.get("f1", np.nan)) else np.nan,
        "Threshold": round(results.get("threshold", np.nan), 4) if not pd.isna(results.get("threshold", np.nan)) else np.nan
    }


    # ✅ Append and reindex
    summary = pd.concat([summary, pd.DataFrame([row])], ignore_index=True)
    summary = summary.reindex(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])
    return summary

### find_best_threshold

In [10]:
def find_best_threshold(y_true, probs, low=0.2, high=0.8, n=61):
    best_f1 = -1.0
    best_thr = 0.5
    for thr in np.linspace(low, high, n):
        preds = (probs >= thr).astype(int)
        f1 = f1_score(y_true, preds, zero_division=0)
        if f1 > best_f1:
            best_f1 = f1
            best_thr = thr
    return best_thr, best_f1


def get_timesnet_val_threshold(results_dir):
    val_prob_path = os.path.join(results_dir, "val_prob.npy")
    val_true_path = os.path.join(results_dir, "val_true.npy")

    if not os.path.exists(val_prob_path) or not os.path.exists(val_true_path):
        raise FileNotFoundError(
            f"Missing validation probability files in {results_dir}. "
            f"Expected val_prob.npy and val_true.npy"
        )

    val_probs = np.load(val_prob_path)
    val_true = np.load(val_true_path)

    best_thr, best_f1 = find_best_threshold(val_true, val_probs)
    return best_thr, best_f1

###Drop and select features

In [11]:
def prepare_features(df):
    """
    Selects only the explicitly defined features for model training.
    You control which features are used by editing 'selected_features' below.
    """

    # --- Define selected features manually ---
    selected_features = [
        "window_size", "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
       "voc_avg_duration", "voc_max_duration", "voc_std_duration", "voc_active_days",
       "voc_active_hours", "sms_total_msgs", "sms_unique_contacts", "sms_active_hours",
       "sms_calltype_ratio", "app_months_active", "app_total_flow", "app_avg_flow",
       "app_std_flow", "app_unique_apps_mean", "app_unique_apps_max", "user_months_active",
        "arpu_mean", "arpu_std", "arpu_max", "idcard_cnt", "snapshot_round"
   ]
  #  selected_features = [
   #     "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
    #   "voc_avg_duration", "voc_max_duration", "voc_std_duration", "voc_active_days",
     # "voc_active_hours", "sms_total_msgs", "sms_unique_contacts", "sms_active_hours",
     #"sms_calltype_ratio", "idcard_cnt"
    #]
   # selected_features = [
    #    "voc_active_days",
    #"voc_active_hours",
    #"voc_unique_contacts",
    #"sms_calltype_ratio",
    #"sms_active_hours" ]


    # ✅ You can manually remove or comment out features here
    # For example:
    # selected_features = [f for f in selected_features if not (f.startswith("app_") or f.startswith("arpu_"))]

    # --- Keep only existing columns ---
    available = [f for f in selected_features if f in df.columns]
    missing = [f for f in selected_features if f not in df.columns]

    X = df[available].copy()

    #print(f"\n📊 Final features used ({len(available)}): {available}")
    if missing:
        print(f"⚠️ Missing columns not found in data: {missing}")

    return X

### Compare

In [12]:

def plot_progressive_results(
    results_table,
    metrics=("AUC", "Recall", "F1"),
    round_col=None,
    figsize=(14, 6)
):
    """
    Plot progressive evaluation metrics per round for multiple models.

    Parameters
    ----------
    results_table : pd.DataFrame
        Must contain columns: Model, metrics, and either Round or input_size
    metrics : tuple
        Metrics to plot (default: AUC, Recall, F1)
    round_col : str or None
        Column name for x-axis. If None, auto-detects.
    figsize : tuple
        Figure size for plots
    """

    # --------------------------------------------------
    # Auto-detect round column
    # --------------------------------------------------
    if round_col is None:
        if "Round" in results_table.columns:
            round_col = "Round"
        elif "input_size" in results_table.columns:
            round_col = "input_size"
        else:
            raise ValueError("No Round or input_size column found.")

    # --------------------------------------------------
    # Sort results (important for correct curves)
    # --------------------------------------------------
    results_table = results_table.sort_values(
        by=[round_col, "Model"],
        ascending=True
    ).reset_index(drop=True)


    # --------------------------------------------------
    # Plot each metric
    # --------------------------------------------------
    for metric in metrics:

        plt.figure(figsize=figsize)

        for model in results_table["Model"].unique():
            subset = (
                results_table[results_table["Model"] == model]
                .sort_values(by=round_col)
            )

            plt.plot(
                subset[round_col],
                subset[metric],
                marker="o",
                markersize=6,
                linewidth=2,
                label=model,
                alpha=0.85
            )

        plt.title(f"{metric} per {round_col}", fontsize=18)
        plt.xlabel(round_col, fontsize=14)
        plt.ylabel(metric, fontsize=14)
        plt.grid(True, linestyle="--", alpha=0.4)

        # Legend outside
        plt.legend(
            loc="upper center",
            bbox_to_anchor=(0.5, -0.12),
            ncol=4,
            fontsize=10
        )

        plt.tight_layout(rect=[0, 0.1, 1, 1])
        plt.show()
    display(results_table)

    return results_table

###get_key_rounds

In [13]:
# ============================================================
# 🔬 SCIENTIFIC KEY ROUNDS SELECTION
# ============================================================

def get_key_rounds(max_seq_len, method="linear", n_points=5):
    """
    Generate scientifically meaningful evaluation checkpoints.

    Args:
        max_seq_len: Maximum sequence length (16, 100, 300, etc.)
        method: Selection strategy
            - "linear": Equal spacing (1, 25%, 50%, 75%, 100%)
            - "logarithmic": More points early (where changes happen fast)
            - "sqrt": Square root spacing (balanced)
            - "percentile": Fixed percentages
        n_points: Number of evaluation points (default 5)

    Returns:
        List of round numbers to evaluate
    """

    if max_seq_len <= n_points:
        # If sequence is short, evaluate all rounds
        return list(range(1, max_seq_len + 1))

    if method == "linear":
        # Equal spacing: 1, 25%, 50%, 75%, 100%
        rounds = np.linspace(1, max_seq_len, n_points)

    elif method == "logarithmic":
        # More points early (fraud detection often shows early signal)
        # Log scale: 1, 2, 4, 8, 16 style
        rounds = np.logspace(0, np.log10(max_seq_len), n_points)

    elif method == "sqrt":
        # Square root spacing (balanced between linear and log)
        rounds = np.square(np.linspace(1, np.sqrt(max_seq_len), n_points))

    elif method == "percentile":
        # Fixed percentages: 1st event, 10%, 25%, 50%, 75%, 100%
        percentages = [0, 0.1, 0.25, 0.5, 0.75, 1.0]
        rounds = [max(1, int(p * max_seq_len)) for p in percentages]
        return sorted(set(rounds))  # Remove duplicates

    elif method == "early_focus":
        # Focus on early detection (more points in first half)
        # Useful for fraud detection where early signal matters
        early = np.linspace(1, max_seq_len * 0.5, n_points - 2)
        late = [max_seq_len * 0.75, max_seq_len]
        rounds = np.concatenate([early, late])

    else:
        raise ValueError(f"Unknown method: {method}")

    # Convert to integers, ensure valid range, remove duplicates
    rounds = [int(round(r)) for r in rounds]
    rounds = [max(1, min(r, max_seq_len)) for r in rounds]
    rounds = sorted(set(rounds))

    # Always include 1 and max_seq_len
    if 1 not in rounds:
        rounds = [1] + rounds
    if max_seq_len not in rounds:
        rounds = rounds + [max_seq_len]

    return rounds

#key_rounds = get_key_rounds(max_seq_len, method=method, n_points=n_points)
#print(f"📊 Evaluating rounds: {key_rounds}")
#print(f"   Total: {len(key_rounds)} rounds instead of {max_seq_len}")

#ML Modules

### Load

In [14]:
def load_raw_datasets(config):


    if "ML" in config and "Events" in config["ML"]:
        events_cfg = config["ML"]["Events"]
    else:
        events_cfg = config["Events"]

    base = events_cfg["base_path"]
    files = events_cfg["files"]

    # --- Load all datasets ---
    df_voc = pd.read_csv(os.path.join(base, files["voc"]))
    df_sms = pd.read_csv(os.path.join(base, files["sms"]))
    df_app = pd.read_csv(os.path.join(base, files["app"]))
    df_user = pd.read_csv(os.path.join(base, files["user"]))

    # --- Normalize timestamps and add source column ---
    for df, src in [(df_voc, "VOC"), (df_sms, "SMS"), (df_app, "APP"), (df_user, "USER")]:
        df["source"] = src
        ts_col = [c for c in df.columns if "time" in c.lower()][0]
        df.rename(columns={ts_col: "event_time"}, inplace=True)
        df["event_time"] = pd.to_datetime(df["event_time"], errors="coerce")

    print("✅ Raw datasets loaded and timestamp-normalized.")
    return df_voc, df_sms, df_app, df_user

df_voc, df_sms, df_app, df_user = load_raw_datasets(config)

✅ Raw datasets loaded and timestamp-normalized.

### Build timeline (events)

In [15]:
def merge_and_prepare_events(df_voc, df_sms, df_app, df_user):

    # --- 1️⃣ Normalize USER dataset ---
    if 'label' not in df_user.columns:
        raise KeyError("❌ 'label' column not found in user dataset")

    # Ensure numeric consistency
    df_user['label'] = df_user['label'].fillna(0).astype(int)
    df_user['idcard_cnt'] = df_user['idcard_cnt'].fillna(0).astype(float)
    df_user['arpu_value'] = df_user['arpu_value'].fillna(0).astype(float)

    # --- 2️⃣ Extract static info for merging (label + sim count only) ---
    #static_user_info = df_user.groupby("phone_no_m", as_index=False)[["label", "idcard_cnt"]].max()
    # --- 2️⃣ Extract static info from the RAW user table (covers all 6,106 users) ---
    lbl_cfg = config["ML"]["labels"]
    raw_user = pd.read_csv(os.path.join(lbl_cfg["base_path"], lbl_cfg["file"]))
    static_user_info = raw_user[["phone_no_m", "label", "idcard_cnt"]].drop_duplicates("phone_no_m")
    static_user_info["label"] = static_user_info["label"].astype(int)
    static_user_info["idcard_cnt"] = static_user_info["idcard_cnt"].fillna(0).astype(float)

    # --- 3️⃣ Merge static info into other event tables ---
    df_voc = df_voc.merge(static_user_info, on="phone_no_m", how="left")
    df_sms = df_sms.merge(static_user_info, on="phone_no_m", how="left")
    df_app = df_app.merge(static_user_info, on="phone_no_m", how="left")


    # --- 4️⃣ Combine all transactional event sources ---
    # include df_user itself since arpu_value is event-like
    events = pd.concat([df_voc, df_sms, df_app, df_user], ignore_index=True)

    # --- 5️⃣ Fill and order ---
    #events["label"] = events["label"].fillna(0).astype(int)
    missing = int(events["label"].isna().sum())
    assert missing == 0, f"{missing} events have no label — label merge is broken"
    events["label"] = events["label"].astype(int)

    events["event_time"] = pd.to_datetime(events["event_time"], errors="coerce")
    events = events.sort_values(["phone_no_m", "event_time"]).reset_index(drop=True)

    # --- 6️⃣ Summary ---
    print("\n🔎 Feature Summary per Source:")
    for src, df in [("VOC", df_voc), ("SMS", df_sms), ("APP", df_app), ("USER", df_user)]:
        print(f"\n📂 Source: {src}")
        print(f"   Events: {len(df):,}")
        print(f"   Users : {df['phone_no_m'].nunique():,}")
        print(f"   Columns ({len(df.columns)}): {', '.join(df.columns)}")

    print("\n📊 Combined Dataset Summary:")
    print(f"   Total events: {len(events):,}")
    print(f"   Unique users: {events['phone_no_m'].nunique():,}")
    print(f"   Fraud ratio: {events['label'].mean()*100:.2f}%")
    user_labels = events.groupby("phone_no_m")["label"].max()
    print(f"   Fraud users: {int(user_labels.sum()):,} / {user_labels.size:,} ({user_labels.mean()*100:.2f}%)")

    return events

events = merge_and_prepare_events(df_voc, df_sms, df_app, df_user)

display(events.head())

🔎 Feature Summary per Source:

📂 Source: VOC
   Events: 5,015,430
   Users : 6,025
   Columns (11): phone_no_m, opposite_no_m, calltype_id, event_time, call_dur, city_name, county_name, imei_m, source, label, idcard_cnt

📂 Source: SMS
   Events: 6,848,509
   Users : 6,103
   Columns (7): phone_no_m, opposite_no_m, calltype_id, event_time, source, label, idcard_cnt

📂 Source: APP
   Events: 3,283,602
   Users : 6,106
   Columns (10): phone_no_m, event_time, source, busi_name, flow, month_id, flow_norm, month_str, label, idcard_cnt

📂 Source: USER
   Events: 39,454
   Users : 5,929
   Columns (10): phone_no_m, event_time, source, month_id, arpu_value, city_name, county_name, idcard_cnt, label, month_col

📊 Combined Dataset Summary:
   Total events: 15,186,995
   Unique users: 6,106
   Fraud ratio: 24.63%
   Fraud users: 1,962 / 6,106 (32.13%)

,phone_no_m,opposite_no_m,calltype_id,event_time,call_dur,city_name,county_name,imei_m,source,label,idcard_cnt,busi_name,flow,month_id,flow_norm,month_str,arpu_value,month_col
0,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-13 16:21:53,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-13 16:21:53,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Split data based on users (fraud, not fraud)

In [16]:


# ======================================
# Clean Numeric Columns
# ======================================
events = events.copy()
numeric_cols = events.select_dtypes(include=["number"]).columns.difference(["label"])

# Replace NaN with 0 for numeric fields (avoids scaling issues)
events[numeric_cols] = events[numeric_cols].fillna(0)

print(f"\n📊 Numeric columns to scale ({len(numeric_cols)}): {numeric_cols.tolist()}")


# ======================================
# 2 Create / Load Shared Train-Val-Test User Split
# ======================================
split_dir = os.path.join(config["root_path"], "splits", "shared_user_split_v1")
train_split_file = f"{split_dir}/train_users.csv"
test_split_file  = f"{split_dir}/test_users.csv"
val_split_file   = f"{split_dir}/val_users.csv"

os.makedirs(split_dir, exist_ok=True)

all_split_files_exist = (
    os.path.exists(train_split_file)
    and os.path.exists(test_split_file)
    and os.path.exists(val_split_file)
)

if all_split_files_exist:
    print("📂 Using shared user split files...")
    train_users = set(pd.read_csv(train_split_file)["phone_no_m"])
    test_users  = set(pd.read_csv(test_split_file)["phone_no_m"])
    val_users   = set(pd.read_csv(val_split_file)["phone_no_m"])
else:
    print("🆕 Creating shared train/test/val user split...")

    # One label per user
    user_labels = events.groupby("phone_no_m")["label"].max()
    fraud_users = user_labels[user_labels == 1].index
    normal_users = user_labels[user_labels == 0].index

    # 1) Train/Test split (split fraud user %)
    fraud_train, fraud_test = train_test_split(
        fraud_users, test_size=0.2, random_state=42
    )
    normal_train, normal_test = train_test_split(
        normal_users, test_size=0.2, random_state=42
    )

    train_users_full = set(fraud_train) | set(normal_train)
    test_users = set(fraud_test) | set(normal_test)

    # 2) Validation split from training users only
    train_user_labels = user_labels.loc[list(train_users_full)]

    fraud_train_users = train_user_labels[train_user_labels == 1].index
    normal_train_users = train_user_labels[train_user_labels == 0].index

    fraud_tr, fraud_val = train_test_split(
        fraud_train_users, test_size=0.2, random_state=42
    )
    normal_tr, normal_val = train_test_split(
        normal_train_users, test_size=0.2, random_state=42
    )

    train_users = set(fraud_tr) | set(normal_tr)
    val_users   = set(fraud_val) | set(normal_val)

    pd.DataFrame({"phone_no_m": sorted(train_users)}).to_csv(train_split_file, index=False)
    pd.DataFrame({"phone_no_m": sorted(test_users)}).to_csv(test_split_file, index=False)
    pd.DataFrame({"phone_no_m": sorted(val_users)}).to_csv(val_split_file, index=False)

    print(f"✅ Saved shared split files to '{split_dir}/'")
# ======================================
# Split overlap checks
# ======================================
assert len(train_users & test_users) == 0, "❌ User leakage: train and test overlap"
assert len(train_users & val_users) == 0, "❌ User leakage: train and val overlap"
assert len(test_users & val_users) == 0, "❌ User leakage: test and val overlap"

print("🔒 Split overlap checks passed:")
print(f"   train ∩ test = {len(train_users & test_users)}")
print(f"   train ∩ val  = {len(train_users & val_users)}")
print(f"   test  ∩ val  = {len(test_users & val_users)}")
user_labels = events.groupby("phone_no_m")["label"].max()
print(f"   sizes  train/val/test = {len(train_users)} / {len(val_users)} / {len(test_users)}")
print(f"   fraud  train/val/test = {int(user_labels.loc[list(train_users)].sum())} / "
      f"{int(user_labels.loc[list(val_users)].sum())} / {int(user_labels.loc[list(test_users)].sum())}")
# ======================================
# Apply Split to Events
# ======================================
train_events = events[events["phone_no_m"].isin(train_users)]
test_events  = events[events["phone_no_m"].isin(test_users)]
val_events = events[events["phone_no_m"].isin(val_users)]

# Sanity checks
assert len(set(train_events["phone_no_m"]) & set(test_events["phone_no_m"])) == 0, "❌ User leakage detected!"
assert train_events["label"].nunique() == 2, "❌ Training set must contain both classes"
assert test_events["label"].nunique() == 2, "❌ Test set must contain both classes"

# --- add time gap, scaled featur ---
# for name, df in [('train_events', train_events), ('test_events', test_events)]:
#     df = df.copy()  # avoid SettingWithCopyWarning
#     df['event_time'] = pd.to_datetime(df['event_time'])
#     #df.sort_values(['phone_no_m', 'event_time'], inplace=True)
#     df = df.sort_values(['phone_no_m', 'event_time'], kind='mergesort').reset_index(drop=True)
#     df['dt_hours'] = df.groupby('phone_no_m')['event_time'].diff().dt.total_seconds() / 3600
#     df['dt_hours'] = df['dt_hours'].fillna(0)
#     df['dt_hours'] = np.log1p(df['dt_hours'])  # normalize gaps
#     if name == 'train_events':
#         train_events = df
#     else:
#         test_events = df
for name, df in [
    ('train_events', train_events),
    ('val_events', val_events),
    ('test_events', test_events)
]:
    df = df.copy()
    df['event_time'] = pd.to_datetime(df['event_time'])
    df = df.sort_values(['phone_no_m', 'event_time'], kind='mergesort').reset_index(drop=True)
    df['dt_hours'] = df.groupby('phone_no_m')['event_time'].diff().dt.total_seconds() / 3600
    df['dt_hours'] = df['dt_hours'].fillna(0)
    df['dt_hours'] = np.log1p(df['dt_hours'])

    if name == 'train_events':
        train_events = df
    elif name == 'val_events':
        val_events = df
    else:
        test_events = df


# Store unscaled events BEFORE line 895
train_events_unscaled = train_events.copy()
test_events_unscaled = test_events.copy()
val_events_unscaled = val_events.copy()


# Sanity checks
assert len(set(train_events["phone_no_m"]) & set(test_events["phone_no_m"])) == 0, "❌ User leakage detected!"
assert train_events["label"].nunique() == 2, "❌ Training set must contain both classes"
assert test_events["label"].nunique() == 2, "❌ Test set must contain both classes"
scale_cols_seq = sorted(set(train_events.select_dtypes(include=["number"]).columns) - {"label"})
scaler_seq = StandardScaler().fit(train_events[scale_cols_seq])
train_events[scale_cols_seq] = scaler_seq.transform(train_events[scale_cols_seq])
test_events[scale_cols_seq]  = scaler_seq.transform(test_events[scale_cols_seq])
val_events[scale_cols_seq]   = scaler_seq.transform(val_events[scale_cols_seq])

# ======================================
# 4️⃣ snapshot
# ======================================

# ======================================
# 4️⃣ Create Sequences (using multiple features)
# ======================================
numeric_features = [c for c in numeric_cols if c not in ["label"]]  # exclude label
if 'dt_hours' in train_events.columns:
    numeric_features.append('dt_hours')
print(f"\n📦 Features used for sequences: {numeric_features}")
feature_cols_tf = numeric_features.copy()
# 👉 Transformer feature columns: same numeric features as LSTM + source_id

if "source_id" not in feature_cols_tf:
    feature_cols_tf.append("source_id")

print("[Transformer] feature_cols_tf:", feature_cols_tf)

📊 Numeric columns to scale (6): ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt']
📂 Using shared user split files...
🔒 Split overlap checks passed:
   train ∩ test = 0
   train ∩ val  = 0
   test  ∩ val  = 0
   sizes  train/val/test = 3907 / 977 / 1222
   fraud  train/val/test = 1255 / 314 / 393

📦 Features used for sequences: ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt', 'dt_hours']
[Transformer] feature_cols_tf: ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt', 'dt_hours', 'source_id']

### Generate_snapshots_from_events

In [17]:
# ============================================================
# 🔧 OPTIMIZED SNAPSHOT GENERATION FROM EVENTS (FIXED)
# ============================================================

def generate_snapshots_from_events(
    events_df,
    users,
    r,
    max_seq_len,
    recent_mode=True
):
    """
    Generate snapshot features from events DataFrame.
    OPTIMIZED: Uses groupby instead of per-user filtering.
    """

    # 1️⃣ Filter to relevant users FIRST (huge speedup)
    events_filtered = events_df[events_df["phone_no_m"].isin(users)].copy()

    if events_filtered.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    # 2️⃣ Sort once
    events_filtered = events_filtered.sort_values(["phone_no_m", "event_time"])

    # 3️⃣ Apply selection logic per user using groupby
    def select_events(df_u):
        if recent_mode:
            df_u = df_u.tail(max_seq_len).head(r)
        else:
            df_u = df_u.head(r)
        return df_u

    selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)

    if selected.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    # 4️⃣ Aggregate features using groupby
    snapshot_rows = []

    for user, df_u in tqdm(selected.groupby("phone_no_m"), desc="Generating snapshots"):
    #for user, df_u in selected.groupby("phone_no_m"):
        row = {"phone_no_m": user}

        # Get label
        label = int(df_u["label"].max()) if "label" in df_u.columns else 0

        # --- Voice Features ---
        voc = df_u[df_u["source"] == "VOC"]
        if len(voc) > 0:
            if "call_dur" in voc.columns:
                call_dur = pd.to_numeric(voc["call_dur"], errors="coerce").fillna(0)
            else:
                call_dur = pd.Series([0])

            row["voc_total_calls"] = len(voc)
            row["voc_unique_contacts"] = voc["opposite_no_m"].nunique() if "opposite_no_m" in voc.columns else 0
            row["voc_total_duration"] = call_dur.sum()
            row["voc_avg_duration"] = call_dur.mean()
            row["voc_max_duration"] = call_dur.max()
            row["voc_std_duration"] = call_dur.std() if len(call_dur) > 1 else 0
            row["voc_active_days"] = voc["event_time"].dt.weekday.nunique()
            row["voc_active_hours"] = voc["event_time"].dt.hour.nunique()
        else:
            row.update({
                "voc_total_calls": 0, "voc_unique_contacts": 0, "voc_total_duration": 0,
                "voc_avg_duration": 0, "voc_max_duration": 0, "voc_std_duration": 0,
                "voc_active_days": 0, "voc_active_hours": 0
            })

        # --- SMS Features ---
        sms = df_u[df_u["source"] == "SMS"]
        if len(sms) > 0:
            row["sms_total_msgs"] = len(sms)
            row["sms_unique_contacts"] = sms["opposite_no_m"].nunique() if "opposite_no_m" in sms.columns else 0
            row["sms_active_hours"] = sms["event_time"].dt.hour.nunique()
            if "calltype_id" in sms.columns:
                calltype = pd.to_numeric(sms["calltype_id"], errors="coerce")
                row["sms_calltype_ratio"] = (calltype == 1).mean()
            else:
                row["sms_calltype_ratio"] = 0
        else:
            row.update({
                "sms_total_msgs": 0, "sms_unique_contacts": 0,
                "sms_active_hours": 0, "sms_calltype_ratio": 0
            })

        # --- App Features ---
        app = df_u[df_u["source"] == "APP"]
        if len(app) > 0:
            if "flow" in app.columns:
                flow = pd.to_numeric(app["flow"], errors="coerce").fillna(0)
            else:
                flow = pd.Series([0])

            row["app_months_active"] = app["month_id"].nunique() if "month_id" in app.columns else 0
            row["app_total_flow"] = flow.sum()
            row["app_avg_flow"] = flow.mean()
            row["app_std_flow"] = flow.std() if len(flow) > 1 else 0
            row["app_unique_apps_mean"] = app["busi_name"].nunique() if "busi_name" in app.columns else 0
            row["app_unique_apps_max"] = app["busi_name"].nunique() if "busi_name" in app.columns else 0
        else:
            row.update({
                "app_months_active": 0, "app_total_flow": 0, "app_avg_flow": 0,
                "app_std_flow": 0, "app_unique_apps_mean": 0, "app_unique_apps_max": 0
            })

        # --- User/ARPU Features ---
        arpu = df_u[df_u["source"] == "USER"]
        if len(arpu) > 0:
            if "arpu_value" in arpu.columns:
                arpu_val = pd.to_numeric(arpu["arpu_value"], errors="coerce")
            else:
                arpu_val = pd.Series([0])

            row["user_months_active"] = arpu["month_id"].nunique() if "month_id" in arpu.columns else 0
            row["arpu_mean"] = arpu_val.mean()
            row["arpu_std"] = arpu_val.std() if len(arpu_val) > 1 else 0
            row["arpu_max"] = arpu_val.max()
            row["idcard_cnt"] = arpu["idcard_cnt"].max() if "idcard_cnt" in arpu.columns else 0
        else:
            row.update({
                "user_months_active": 0, "arpu_mean": 0, "arpu_std": 0,
                "arpu_max": 0, "idcard_cnt": 0
            })

        # Meta features
        row["window_size"] = r
        row["snapshot_round"] = r
        row["label"] = label

        snapshot_rows.append(row)

    # Build DataFrame
    df_snapshot = pd.DataFrame(snapshot_rows).fillna(0)

    if df_snapshot.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    y = df_snapshot["label"].values
    user_ids = df_snapshot["phone_no_m"].values
    X = df_snapshot.drop(columns=["phone_no_m", "label"])

    return X, y, user_ids

#  ▶ Classic Ml Snapshot based

# ▶  Advance ML

### make_user_sequences

In [18]:

# ============================================================
# 2️⃣ Selector functions (FIXED, SIMPLE)
# ============================================================

def selector_oldest(r):
    """Select oldest r events"""
    return lambda df_u: df_u.head(r)

def selector_last_r(r):
    """Select LAST r events (to match full evaluation behavior)"""
    return lambda df_u: df_u.tail(r)

def selector_most_recent(r):
    """Select most recent r events (used AFTER window freeze)"""
    return lambda df_u: df_u.tail(r)

def make_user_sequences(
    events,
    feature_cols=None,
    max_seq_len=100,
    event_selector=None,
):
    events = events.copy()
    users, X_seq, y = [], [], []

    SOURCE_MAP = {
        "APP": 0,
        "SMS": 1,
        "USER": 2,
        "VOC": 3,
    }

    unknown_sources = set(events["source"].astype(str).unique()) - set(SOURCE_MAP.keys())
    assert len(unknown_sources) == 0, f"❌ Unknown source values found: {unknown_sources}"

    events["source_id"] = events["source"].map(SOURCE_MAP).astype(int)

    if feature_cols is None:
        feature_cols = events.select_dtypes(include=["number"]) \
                             .columns.difference(["label"]) \
                             .tolist()
    if "source_id" not in feature_cols:
        feature_cols.append("source_id")

    for user, df_u in events.groupby("phone_no_m"):

        # 1️⃣ Sort
        df_u = df_u.sort_values("event_time")

        # 2️⃣ Freeze to last max_seq_len
        if recent_mode:
            df_u = df_u.tail(max_seq_len)   # E51..E100

        # 3️⃣ 🔁 APPLY PROGRESSIVE SELECTION HERE
        if event_selector is not None:
            df_u = event_selector(df_u)

        # 4️⃣ Features
        feats = df_u[feature_cols].to_numpy(dtype=float)

        # 5️⃣ Pad / truncate
        if len(feats) < max_seq_len:
            feats = np.pad(feats, ((max_seq_len - len(feats), 0), (0, 0)))
        else:
            feats = feats[-max_seq_len:]

        label = int(df_u["label"].max())

        X_seq.append(feats)
        y.append(label)
        users.append(user)

    return np.array(X_seq), np.array(y), np.array(users)

### Create sequences

In [19]:

trans_X_train, trans_y_train, users_train = make_user_sequences(train_events, feature_cols=numeric_features, max_seq_len=max_seq_len,event_selector=selector_oldest(max_seq_len))
trans_X_test, trans_y_test, users_test = make_user_sequences(test_events, feature_cols=numeric_features, max_seq_len=max_seq_len,event_selector=selector_oldest(max_seq_len))
trans_X_val, trans_y_val, _ =            make_user_sequences(val_events,    feature_cols=numeric_features,max_seq_len=max_seq_len, event_selector=selector_oldest(max_seq_len))
assert len(set(val_events["phone_no_m"])) > 0, "❌ Validation set is empty!"
assert val_events["label"].nunique() == 2, "❌ Validation set must contain both classes"

print("\n✅ Sequence Summary (per-user sequences):")
print(f"   X_train: {trans_X_train.shape} | Fraud ratio: {np.mean(trans_y_train)*100:.2f}%")
print(f"   X_test : {trans_X_test.shape} | Fraud ratio: {np.mean(trans_y_test)*100:.2f}%")

# ======================================
# 5️⃣ Consistency Check
# ======================================
trans_rf_train = set(pd.read_csv(train_split_file)["phone_no_m"])
trans_rf_test  = set(pd.read_csv(test_split_file)["phone_no_m"])
assert trans_rf_train == train_users, "❌ Train user mismatch between LSTM and RF/XGB!"
assert trans_rf_test  == test_users,  "❌ Test user mismatch between LSTM and RF/XGB!"
print("\n🔒 Consistency Check: ✅ Same users used for all models (LSTM, RF, XGBoost).")

✅ Sequence Summary (per-user sequences):
   X_train: (3907, 4, 8) | Fraud ratio: 32.12%
   X_test : (1222, 4, 8) | Fraud ratio: 32.16%

🔒 Consistency Check: ✅ Same users used for all models (LSTM, RF, XGBoost).

#Pretrained

#TimesNet

## Preparation

###Install

In [20]:

# ============================
# 1️⃣ Clean up any old copies
# ============================
#!rm -rf /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library

# ============================
# 2️⃣ Clone directly from gethub
# ============================
#!git clone https://github.com/thuml/Time-Series-Library.git /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library

# ============================
# 3️⃣ Add repo to Python path
# ============================
import sys
sys.path.append('/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library')

print("✅ Basic environment ready for TSLib!")

# ============================
# 4️⃣ Verify repo structure
# ============================
%cd /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library
!ls -lh run.py

✅ Basic environment ready for TSLib!
/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library
-rw------- 1 root root 16K Apr 29 16:31 run.py

### Evaluate experiment

In [21]:

def evaluate_experiment(
    results_dir: str,
    threshold,
    num_classes: int = None,
    class_labels=None,
    title: str = None,
    show_plot: bool = True,
):
    pred_path = os.path.join(results_dir, "pred.npy")
    true_path = os.path.join(results_dir, "true.npy")
    prob_path = os.path.join(results_dir, "prob.npy")

    if not os.path.exists(pred_path) or not os.path.exists(true_path):
        raise FileNotFoundError(f"❌ Could not find pred.npy or true.npy in {results_dir}")

    true = np.load(true_path).flatten()

    # ── Probabilities available → use passed validation threshold ──
    if os.path.exists(prob_path):
        probs = np.load(prob_path).flatten()

        try:
            auc_val = roc_auc_score(true, probs) if len(np.unique(true)) == 2 else np.nan
        except:
            auc_val = np.nan

        pred = (probs >= threshold).astype(int)
        best_thr = threshold

    # ── Fallback → hard labels only ──
    else:
        pred = np.load(pred_path).flatten()
        best_thr = 0.5
        try:
            auc_val = roc_auc_score(true, pred) if len(np.unique(true)) == 2 else np.nan
        except:
            auc_val = np.nan

    # ── Metrics from final pred ──
    acc  = accuracy_score(true, pred)
    prec = precision_score(true, pred, average="binary", zero_division=0)
    rec  = recall_score(true, pred, average="binary", zero_division=0)
    f1   = f1_score(true, pred, average="binary", zero_division=0)

    # ── Confusion matrix ──
    cm = confusion_matrix(true, pred)
    if class_labels is None:
        class_labels = [str(c) for c in np.unique(true)]

    # ── Plot ──
    if show_plot:
        disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_labels)
        plt.figure(figsize=(8, 8))
        disp.plot(cmap="Blues", values_format="d", colorbar=False)
        plt.title(title or f"Confusion Matrix ({os.path.basename(results_dir)})")
        plt.show()

    # ── Print ──
    print(f"\n📊 Accuracy: {acc:.4f}")
    print(f"📈 Precision: {prec:.4f} | Recall: {rec:.4f} | F1: {f1:.4f} | AUC: {auc_val:.4f}")
    print(f"🎯 Threshold: {best_thr:.3f}")
    print("\nDetailed Report:")
    print(classification_report(true, pred, target_names=class_labels, digits=4))

    return {
        "NAS SL": max_seq_len,
        "Testing SL": max_seq_len,
        "f1": f1,
        "accuracy": acc,
        "recall": rec,
        "precision": prec,
        "auc": auc_val,
        "confusion_matrix": cm,
        "threshold": round(best_thr, 3),
    }

### Data handling

#### Covert  data to ts format

In [22]:


def write_ts_file(
    X, y, split_name,
    problem_name="FraudDataset",
    out_dir=None,
    pad_to_dim=None,
    round_id=None
):


    if out_dir is None:
        out_dir = f"/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/ExternalDataset/TimesNet/classification/FraudDataset_NAS_{max_seq_len}"
    os.makedirs(out_dir, exist_ok=True)
    suffix = f"_R{round_id}" if round_id is not None else ""
    ts_path = os.path.join(
        out_dir,
        f"{problem_name}_{split_name.upper()}{suffix}.ts"
    )


    with open(ts_path, "w") as f:
        f.write(f"@problemName {problem_name}\n")
        f.write("@timeStamps false\n")
        f.write("@univariate false\n")
        f.write("@classLabel true 0 1\n")
        f.write("@data\n")

        for i in range(len(X)):
            arr = np.array(X[i])

            # --- Pad or trim to target feature dimension ---
            if pad_to_dim is not None:
                if arr.ndim == 1:
                    arr = arr.reshape(-1, 1)
                n_dim = arr.shape[1]
                if n_dim < pad_to_dim:
                    pad = np.zeros((arr.shape[0], pad_to_dim - n_dim))
                    arr = np.hstack((arr, pad))
                elif n_dim > pad_to_dim:
                    arr = arr[:, :pad_to_dim]

            # --- Convert to string format ---
            if arr.ndim == 1:
                arr_str = ",".join(map(str, arr))
            else:
                parts = [",".join(map(str, arr[:, d])) for d in range(arr.shape[1])]
                arr_str = " : ".join(parts)  # colon separates dimensions

            f.write(f"{arr_str}:{int(y[i])}\n")

    print(f"✅ Wrote {ts_path} with {len(X)} samples (strict sktime format)")
    if pad_to_dim:
        print(f"📏 Feature dimensions padded/trimmed to {pad_to_dim}")

#### Convert

In [23]:

write_ts_file(trans_X_train, trans_y_train, split_name="TRAIN", pad_to_dim=13)
write_ts_file(trans_X_test, trans_y_test, split_name="TEST", pad_to_dim=13)
write_ts_file(trans_X_val, trans_y_val, split_name="VAL", pad_to_dim=13)


# write_ts_file(Xtr_raw, ytr, split_name="TRAIN")
# write_ts_file(Xte_raw, yte, split_name="TEST")

!ls -lh /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/ExternalDataset/TimesNet/classification/FraudDataset_NAS_{max_seq_len}/

file_path = f"/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/ExternalDataset/TimesNet/classification/FraudDataset_NAS_{max_seq_len}/FraudDataset_TRAIN.ts"
X, y = load_from_tsfile_to_dataframe(file_path)

print("✅ Loaded OK!")
print(X.shape)
print(set(y))

✅ Wrote /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/ExternalDataset/TimesNet/classification/FraudDataset_NAS_4/FraudDataset_TRAIN.ts with 3907 samples (strict sktime format)
📏 Feature dimensions padded/trimmed to 13
✅ Wrote /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/ExternalDataset/TimesNet/classification/FraudDataset_NAS_4/FraudDataset_TEST.ts with 1222 samples (strict sktime format)
📏 Feature dimensions padded/trimmed to 13
✅ Wrote /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/ExternalDataset/TimesNet/classification/FraudDataset_NAS_4/FraudDataset_VAL.ts with 977 samples (strict sktime format)
📏 Feature dimensions padded/trimmed to 13
total 4.1M
-rw------- 1 root root 831K Jul  8 17:50 FraudDataset_TEST.ts
-rw------- 1 root root 2.6M Jul  8 17:50 FraudDataset_TRAIN.ts
-rw------- 1 root root 665K Jul  8 17:50 FraudDataset_VAL.ts
✅ Loaded OK!
(3907, 13)
{np.str_('1'), np.str_('0')}

#### Show sample

In [24]:
ts_dir = f"/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/ExternalDataset/TimesNet/classification/FraudDataset_NAS_{max_seq_len}"

for fname in ["FraudDataset_TRAIN.ts", "FraudDataset_TEST.ts"]:
    fpath = os.path.join(ts_dir, fname)
    print(f" {fname}: exists = {os.path.exists(fpath)} | size = {os.path.getsize(fpath)/1024:.1f} KB")
    if os.path.exists(fpath):
        with open(fpath) as f:
            for i, line in enumerate(f):
                if i < 10:
                    print(line.strip())
                else:
                    break
        print("------\n")

 FraudDataset_TRAIN.ts: exists = True | size = 2656.6 KB
@problemName FraudDataset
@timeStamps false
@univariate false
@classLabel true 0 1
@data
-0.029840919093863435,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : -0.23359317309003816,-0.23359317309003816,-0.23359317309003816,-0.23359317309003816 : 0.8381382030441827,0.8381382030441827,0.8381382030441827,0.8381382030441827 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : -0.8170257391209248,-0.8170257391209248,-0.8170257391209248,-0.8170257391209248 : -0.5335819405272189,-0.5335819405272189,-0.5335819405272189,3.8769679998396516 : 1.0,1.0,1.0,1.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:0
-0.029840919093863435,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : -0.23359317309003816,-0.23359317309003816,-0.23359317309003816,-0.23359317309003816 : 0.8381382030441827,0.8381382030441827,0.8381382030441827,0.8381382030441827 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : 1.7923163352486038,1.7923163352486038,1.7923163352486038,1.7923163352486038 : -0.5335819405272189,-0.5335819405272189,-0.5335819405272189,-0.5335819405272189 : 1.0,1.0,1.0,1.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:1
-0.029840919093863435,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : -0.23359317309003816,-0.06041045082242551,-0.23359317309003816,-0.23359317309003816 : -1.6306892826027064,-0.3962755397792619,0.8381382030441827,0.8381382030441827 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : -0.8170257391209248,-0.8170257391209248,-0.8170257391209248,-0.8170257391209248 : -0.5335819405272189,6.925580281323344,5.002378903712142,-0.5335819405272189 : 0.0,3.0,1.0,1.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:1
0.36254728286496063,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : -0.23359317309003816,-0.23359317309003816,-0.23359317309003816,-0.23359317309003816 : -1.6306892826027064,0.8381382030441827,0.8381382030441827,0.8381382030441827 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : -0.8170257391209248,-0.8170257391209248,-0.8170257391209248,-0.8170257391209248 : -0.5335819405272189,2.7531519559309134,-0.5335819405272189,-0.5297405153765863 : 2.0,1.0,1.0,1.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:1
-0.029840919093863435,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : -0.18163835640975437,0.3725463548466062,-0.23359317309003816,-0.23359317309003816 : -0.3962755397792619,-0.3962755397792619,0.8381382030441827,0.8381382030441827 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : -0.8170257391209248,-0.8170257391209248,-0.8170257391209248,-0.8170257391209248 : -0.5335819405272189,0.20670243091678048,0.19381437083879238,-0.5335819405272189 : 3.0,3.0,1.0,1.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:0
------

 FraudDataset_TEST.ts: exists = True | size = 830.9 KB
@problemName FraudDataset
@timeStamps false
@univariate false
@classLabel true 0 1
@data
-0.029840919093863435,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : 0.2599775853726579,1.1605277411642436,-0.025773906368902973,-0.04309217859566424 : -0.3962755397792619,-0.3962755397792619,-0.3962755397792619,-0.3962755397792619 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : -0.8170257391209248,-0.8170257391209248,-0.8170257391209248,-0.8170257391209248 : -0.5335819405272189,-0.020493129064966746,3.2282184701404497,3.4960925971455823 : 3.0,3.0,3.0,3.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:0
-0.029840919093863435,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : -0.23359317309003816,-0.23359317309003816,-0.07772872304918677,-0.23359317309003816 : 0.8381382030441827,0.8381382030441827,-0.3962755397792619,0.8381382030441827 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : 0.9225356437920942,0.9225356437920942,0.9225356437920942,0.9225356437920942 : -0.5335819405272189,-0.5335819405272189,2.63054625477638,-0.08029766630000028 : 1.0,1.0,3.0,1.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:0
-0.029840919093863435,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : -0.1643200841829931,-0.23359317309003816,-0.23359317309003816,-0.23359317309003816 : 0.8381382030441827,0.8381382030441827,0.8381382030441827,0.8381382030441827 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : 0.052754952335584714,0.052754952335584714,0.052754952335584714,0.052754952335584714 : -0.5335819405272189,-0.5300892519586765,-0.5332322353669128,0.8408037868631448 : 3.0,1.0,1.0,1.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:0
-0.029840919093863435,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : -0.17297922029637375,-0.23359317309003816,-0.23359317309003816,-0.23359317309003816 : 0.8381382030441827,0.8381382030441827,0.8381382030441827,0.8381382030441827 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : 0.9225356437920942,0.9225356437920942,0.9225356437920942,0.9225356437920942 : -0.5335819405272189,0.47387421570732363,-0.5335819405272189,-0.5335819405272189 : 3.0,1.0,1.0,1.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:0
-0.029840919093863435,-0.029840919093863435,-0.029840919093863435,-0.029840919093863435 : -0.23359317309003816,-0.23359317309003816,-0.23359317309003816,-0.23359317309003816 : 0.8381382030441827,0.8381382030441827,0.8381382030441827,0.8381382030441827 : -0.041480529072158906,-0.041480529072158906,-0.041480529072158906,-0.041480529072158906 : -0.2519196987865733,-0.2519196987865733,-0.2519196987865733,-0.2519196987865733 : 0.052754952335584714,0.052754952335584714,0.052754952335584714,0.052754952335584714 : -0.5335819405272189,-0.5335819405272189,3.522798646675703,-0.5335819405272189 : 1.0,1.0,1.0,1.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0 : 0.0,0.0,0.0,0.0:0
------

#### Summrize

In [25]:

file_path = f"/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/ExternalDataset/TimesNet/classification/FraudDataset_NAS_{max_seq_len}/FraudDataset_TRAIN.ts"

X, y = load_from_tsfile_to_dataframe(file_path)

print("✅ File loaded successfully!")
print(f"Shape of X: {X.shape}")
print(f"Number of labels: {len(set(y))}")
print(f"Labels: {set(y)}")
#print(f"Example (first row):\n", X.iloc[0])

print("Feature ranges per column:")
for col in range(X.shape[1]):
    values = np.concatenate(X.iloc[:, col].values)
    print(f"Column {col}: mean={np.mean(values):.3f}, std={np.std(values):.3f}")

✅ File loaded successfully!
Shape of X: (3907, 13)
Number of labels: 2
Labels: {np.str_('1'), np.str_('0')}
Feature ranges per column:
Column 0: mean=-0.008, std=0.413
Column 1: mean=-0.027, std=0.937
Column 2: mean=0.578, std=0.587
Column 3: mean=-0.041, std=0.001
Column 4: mean=-0.250, std=0.061
Column 5: mean=0.114, std=1.174
Column 6: mean=0.203, std=1.563
Column 7: mean=1.513, std=0.891
Column 8: mean=0.000, std=0.000
Column 9: mean=0.000, std=0.000
Column 10: mean=0.000, std=0.000
Column 11: mean=0.000, std=0.000
Column 12: mean=0.000, std=0.000

### NAS TimeNet full Training

In [26]:

# ============================================================
# NAS TIMESNET – FULL UNFROZEN TRAINING (ARCH SEARCH)
# ============================================================

import os
import shutil
import subprocess
import optuna
from optuna.samplers import TPESampler
import numpy as np
import pandas as pd



# ============================================================
# CONFIG (MATCHES YOUR PIPELINE)
# ============================================================
RUN_PY = "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py"
DATA_ROOT = f"/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/ExternalDataset/TimesNet/classification/FraudDataset_NAS_{max_seq_len}/"
TEST_RESULTS_ROOT = f"./test_results/"

# ============================================================
# SAFETY UTIL
# ============================================================
def find_latest_results_dir(base=f"./test_results/"):
    if not os.path.exists(base):
        raise RuntimeError("❌ test_results directory does not exist")

    candidates = [
        os.path.join(base, d)
        for d in os.listdir(base)
        if os.path.isdir(os.path.join(base, d))
    ]
    if not candidates:
        raise RuntimeError("❌ No TimesNet results directory found")

    return max(candidates, key=os.path.getmtime)

# ============================================================
# RUN ONE NAS TRIAL (TRAIN + FULL EVAL)
# ============================================================

nas_trial_log = []
best_f1_so_far = -1.0
best_trial_so_far = -1
ENQUEUED_TRIAL_IDS = {0, 1, 2, 3}

def run_timesnet_nas(trial_id, params):

    model_id = f"NAS_TimesNet_{trial_id}"

    # ✅ FIXED: Use ALL parameters from search space
    cmd = f"""CUDA_VISIBLE_DEVICES=0 python -u {RUN_PY} \
    --task_name classification \
    --is_training 1 \
    --mode UnfrozenOptWL \
    --root_path {DATA_ROOT} \
    --model_id {model_id} \
    --model TimesNet \
    --data UEA \
    --data_path FraudDataset \
    --features M \
    --seq_len {max_seq_len} \
    --target OT \
    --gpu 0 \
    --use_gpu 1 \
    --patience {params["patience"]} \
    --batch_size {params["batch_size"]} \
    --train_epochs {epochs} \
    --learning_rate {params["lr"]} \
    --e_layers {params["e_layers"]} \
    --d_model {params["d_model"]} \
    --d_ff {params["d_ff"]} \
    --top_k {params["top_k"]} \
    --num_kernels {params["num_kernels"]} \
    --dropout {params["dropout"]} \
    --des NAS_UnfrozenOptWL_Search \
    --itr 1
    """
    # Note: weight_decay removed since run.py may not support it

    print(cmd)
    get_ipython().system(cmd)

    print("==========================xxxxxxxxxxxxxxxxxx===============")

    # --------------------------------------------------------
    # Locate results safely (NO guessing)
    # --------------------------------------------------------
    #results_dir = find_latest_results_dir()
    # ✅ FIX — read from exact folder matching current trial
    setting = (
        f"classification_{model_id}_TimesNet_UEA_ftM_"
        f"sl{max_seq_len}_ll48_pl0_"
        f"dm{params['d_model']}_nh8_"
        f"el{params['e_layers']}_dl1_"
        f"df{params['d_ff']}_expand2_dc4_fc1_"
        f"ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0"
    )
    results_dir = os.path.join(f"./test_results/", setting)

    val_true_path = os.path.join(results_dir, "val_true.npy")
    val_prob_path  = os.path.join(results_dir, "val_prob.npy")
    if not os.path.exists(val_prob_path) or not os.path.exists(val_true_path):
        raise RuntimeError("❌ val_prob.npy / val_true.npy not found")
    val_probs = np.load(val_prob_path).flatten()
    val_true  = np.load(val_true_path).flatten()

    best_val_f1 = -1.0
    best_val_thr = 0.5

    for thr in np.linspace(0.2, 0.8, 61):
        f1 = f1_score(val_true, (val_probs >= thr).astype(int), zero_division=0)
        if f1 > best_val_f1:
            best_val_f1 = f1
            best_val_thr = thr
# --- VALIDATION metrics using best validation threshold ---
    val_preds = (val_probs >= best_val_thr).astype(int)

    val_auc = roc_auc_score(val_true, val_probs)
    val_recall = recall_score(val_true, val_preds, zero_division=0)
    val_precision = precision_score(val_true, val_preds, zero_division=0)

    # --- TEST F1 ---
    test_true_path = os.path.join(results_dir, "true.npy")
    test_prob_path  = os.path.join(results_dir, "prob.npy")
    if not os.path.exists(test_prob_path) or not os.path.exists(test_true_path):
        raise RuntimeError("❌ prob.npy / true.npy not found")
    test_probs = np.load(test_prob_path).flatten()
    test_true  = np.load(test_true_path).flatten()

    best_test_f1 = -1.0
    best_thr = 0.5
    for thr in np.linspace(0.2, 0.8, 61):
        f1 = f1_score(test_true, (test_probs >= thr).astype(int), zero_division=0)
        if f1 > best_test_f1:
            best_test_f1 = f1
            best_thr = thr
# --- TEST metrics using validation threshold (scientifically correct) ---
    test_preds = (test_probs >= best_val_thr).astype(int)

    test_auc = roc_auc_score(test_true, test_probs)
    test_recall = recall_score(test_true, test_preds, zero_division=0)
    test_precision = precision_score(test_true, test_preds, zero_division=0)
    test_f1 = f1_score(test_true, test_preds, zero_division=0)

    # ========================================================
    # Trial summary row
    # ========================================================
    now = datetime.now()
    global best_f1_so_far, best_trial_so_far

    if best_val_f1 > best_f1_so_far:
        best_f1_so_far = best_val_f1
        best_trial_so_far = trial_id

    is_enqueued_trial = trial_id in ENQUEUED_TRIAL_IDS

    trial_row = {
      "date": now.strftime("%Y-%m-%d"),
      "time": now.strftime("%H:%M:%S"),
      "seq_length": max_seq_len,
      "trial_id": trial_id,

      # 🔹 Validation (optimization target)
      "val_f1": round(best_val_f1, 4),
      "val_auc": round(val_auc, 4),
      "val_recall": round(val_recall, 4),
      "val_precision": round(val_precision, 4),

      # 🔹 Model parameters
      "d_model": params["d_model"],
      "lr": params["lr"],
      "d_ff": params["d_ff"],
      "e_layers": params["e_layers"],
      "top_k": params["top_k"],
      "num_kernels": params["num_kernels"],
      "dropout": params["dropout"],
      "batch_size": params["batch_size"],
      "patience": params["patience"],

      # 🔹 Thresholds
      "val_threshold": round(best_val_thr, 3),
      "best_test_threshold": round(best_thr, 3),

      # 🔹 Best tracking
      "best_val_so_far": round(best_f1_so_far, 4),
      "best_trial_id": best_trial_so_far,

      # 🔹 Test (monitoring only)
      "test_f1": round(test_f1, 4),
      "test_auc": round(test_auc, 4),
      "test_recall": round(test_recall, 4),
      "test_precision": round(test_precision, 4),

      # 🔹 Diagnostics
      "gap_val_test": round(best_val_f1 - test_f1, 4),
      "is_enqueued": is_enqueued_trial,
      "status": "OK",
  }

    nas_trial_log.append(trial_row)
    display(
    pd.DataFrame([trial_row])
    .sort_values("val_f1", ascending=False)
    .reset_index(drop=True)
)

#     display(
#     pd.DataFrame(nas_trial_log)
#     .sort_values("val_f1", ascending=False)
#     .reset_index(drop=True)
# )
    return best_val_f1


# ============================================================
# OPTUNA OBJECTIVE
# ============================================================
def objective(trial):
    params = {
        "lr": trial.suggest_float("lr", 5e-5, 3e-3, log=True),
        "d_model": trial.suggest_categorical("d_model", [2, 4, 8, 16, 32, 48, 64, 128, 256]),
        "d_ff": trial.suggest_categorical("d_ff", [2, 4, 8, 16, 32, 64, 128, 256, 512]),
        "e_layers": trial.suggest_int("e_layers", 2, 6),
        "top_k": trial.suggest_categorical("top_k", [2]),
        "dropout": trial.suggest_float("dropout", 0.0, 0.4),
        "batch_size": trial.suggest_categorical("batch_size", [8, 16]),
        "patience": trial.suggest_int("patience", 2, 5),
        "num_kernels": trial.suggest_categorical("num_kernels", [3, 4, 6]),
    }

    try:
        return run_timesnet_nas(trial.number, params)
    except Exception as e:
        print(f"❌ Trial {trial.number} failed: {e}")
        raise optuna.exceptions.TrialPruned(str(e))


# ============================================================
# RUN NAS SEARCH
# ============================================================

# ✅ Better sampler for smarter search
sampler = TPESampler(
    n_startup_trials=10,      # Random trials before TPE kicks in
    n_ei_candidates=24,       # More candidates for acquisition function
    multivariate=True,        # Consider parameter correlations
    seed=42
)

study = optuna.create_study(
    direction="maximize",
    sampler=sampler
   # pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=3)
)

# ✅ FIXED: Enqueued trials now include ALL required parameters
# Trial 1: xs config (best AUC)
study.enqueue_trial({
    "lr": 1e-3,
    "d_model": 4,
    "d_ff": 2,
    "e_layers": 2,
    "top_k": 2,
    "dropout": 0.0,
    "batch_size": 8,
    "patience": 3,
    "num_kernels": 6

})

# Trial 2: dxs config (best F1)
study.enqueue_trial({
    "lr": 1e-3,
    "d_model": 4,
    "d_ff": 2,
    "e_layers": 2,
    "top_k": 2,
    "dropout": 0.3,
    "batch_size": 8,
    "patience": 3,
    "num_kernels": 6
})

# Trial 3: s config variant
study.enqueue_trial({
    "lr": 1e-4,
    "d_model": 32,
    "d_ff": 32,
    "e_layers": 2,
    "top_k": 2,
    "dropout": 0.1,
    "batch_size": 8,
    "patience": 3,
    "num_kernels": 6
})



# ✅ ADD: Very small model (to show minimum threshold)
study.enqueue_trial({
    "lr": 1e-3,
    "d_model": 2,
    "d_ff": 2,
    "e_layers": 2,
    "top_k": 2,
    "dropout": 0.0,
    "batch_size": 16,
    "patience": 3,
    "num_kernels": 6
})



max_attempts = n_trials + 20  # allow up to 20 failures
attempts = 0
while len([t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE]) < n_trials:
    if attempts >= max_attempts:
        print(f"⚠️ Reached {max_attempts} attempts, stopping with {len(nas_trial_log)} valid trials")
        break
    study.optimize(objective, n_trials=1)
    attempts += 1

BEST_TRIAL = study.best_trial.number
BEST_PARAMS = study.best_trial.params
BEST_MODEL_ID = f"NAS_TimesNet_{BEST_TRIAL}"

print("\n" + "="*60)
print("🎉 BEST NAS MODEL FOUND")
print("="*60)
print("Model ID:", BEST_MODEL_ID)
print("Best F1:", study.best_value)
print("Best Params:", BEST_PARAMS)

# ============================================================
# ANALYSIS: SHOW ALL RESULTS FOR YOUR PROOF
# ============================================================
print("\n" + "="*60)
print("📊 ALL TRIALS RANKED BY F1")
print("="*60)

trials_df = study.trials_dataframe()
trials_df = trials_df.sort_values("value", ascending=False)

# Show relevant columns

display(
    pd.DataFrame(nas_trial_log)
    .sort_values("val_f1", ascending=False)
    .reset_index(drop=True)
)

# ============================================================
# ANALYSIS: MODEL SIZE vs PERFORMANCE
# ============================================================
print("\n" + "="*60)
print("📈 MODEL SIZE vs PERFORMANCE ANALYSIS")
print("="*60)

# Group by d_model and show average F1
if "params_d_model" in trials_df.columns:
    size_analysis = trials_df.groupby("params_d_model")["value"].agg(["mean", "max", "count"])
    size_analysis.columns = ["Avg_F1", "Max_F1", "Trials"]
    size_analysis = size_analysis.sort_index()
    print("\nPerformance by d_model:")
    print(size_analysis.to_string())

# ============================================================
# SAVE RESULTS TO CSV
# ============================================================
OUT_DIR = os.path.join(config["output"]["results_dir"], "NAS_v2/")
os.makedirs(OUT_DIR, exist_ok=True)
results_path = f"{OUT_DIR}nas_timesnet_results_WL{max_seq_len}.csv"
trials_df.to_csv(results_path, index=False)
pd.DataFrame(nas_trial_log).sort_values("val_f1", ascending=False).to_csv(f"{OUT_DIR}nas_timesnet_trial_log_WL{max_seq_len}.csv", index=False)
print(f"\n💾 Results saved to: {results_path}")

/tmp/ipykernel_12994/4137100912.py:260: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  sampler = TPESampler(
[I 2026-07-08 17:50:25,699] A new study created in memory with name: no-name-a6f65343-f33f-40ba-bdcd-2084525b71fa

DATA_ROOT → /content/FraudDataset_NAS_4/
cwd → /content/tsl_work
CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_0     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 3     --batch_size 8     --train_epochs 20     --learning_rate 0.001     --e_layers 2     --d_model 4     --d_ff 2     --top_k 2     --num_kernels 6     --dropout 0.0     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 2
d_layers                 : 1
d_model                  : 4
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.0
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.001
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_0
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 3
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_0_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=14.75s, Train Loss=0.6419, Val Loss=0.5709, Val F1=0.5410, Test Loss=0.5731, Test F1=0.5455
Validation loss decreased (inf --> -0.540962).  Saving model ...
[Epoch 02/20], Time=11.25s, Train Loss=0.5224, Val Loss=0.4839, Val F1=0.6614, Test Loss=0.4946, Test F1=0.6567
Validation loss decreased (-0.540962 --> -0.661442).  Saving model ...
[Epoch 03/20], Time=11.12s, Train Loss=0.4769, Val Loss=0.4604, Val F1=0.6731, Test Loss=0.4768, Test F1=0.6683
Validation loss decreased (-0.661442 --> -0.673139).  Saving model ...
[Epoch 04/20], Time=11.10s, Train Loss=0.4633, Val Loss=0.4513, Val F1=0.6791, Test Loss=0.4732, Test F1=0.6716
Validation loss decreased (-0.673139 --> -0.679128).  Saving model ...
[Epoch 05/20], Time=11.26s, Train Loss=0.4593, Val Loss=0.4542, Val F1=0.6732, Test Loss=0.4749, Test F1=0.6692
EarlyStopping counter: 1 out of 3
[Epoch 06/20], Time=11.14s, Train Loss=0.4539, Val Loss=0.4496, Val F1=0.6750, Test Loss=0.4747, Test F1=0.6623
EarlyStopping counter: 2 out of 3
[Epoch 07/20], Time=11.06s, Train Loss=0.4534, Val Loss=0.4500, Val F1=0.6729, Test Loss=0.4703, Test F1=0.6700
EarlyStopping counter: 3 out of 3
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_0_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_0_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7888707037643208
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_0_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,17:53:41,4,0,0.6791,0.8283,0.6943,0.6646,4,0.001,2,2,2,6,0.0,8,3,0.29,0.27,0.6791,0,0.6684,0.8152,0.6718,0.665,0.0108,True,OK

[I 2026-07-08 17:53:42,251] Trial 0 finished with value: 0.6791277258566978 and parameters: {'lr': 0.001, 'd_model': 4, 'd_ff': 2, 'e_layers': 2, 'top_k': 2, 'dropout': 0.0, 'batch_size': 8, 'patience': 3, 'num_kernels': 6}. Best is trial 0 with value: 0.6791277258566978.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_1     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 3     --batch_size 8     --train_epochs 20     --learning_rate 0.001     --e_layers 2     --d_model 4     --d_ff 2     --top_k 2     --num_kernels 6     --dropout 0.3     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 2
d_layers                 : 1
d_model                  : 4
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.3
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.001
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_1
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 3
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_1_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=12.28s, Train Loss=0.6700, Val Loss=0.6190, Val F1=0.4964, Test Loss=0.6192, Test F1=0.4976
Validation loss decreased (inf --> -0.496425).  Saving model ...
[Epoch 02/20], Time=11.23s, Train Loss=0.6045, Val Loss=0.5485, Val F1=0.5800, Test Loss=0.5503, Test F1=0.5799
Validation loss decreased (-0.496425 --> -0.579974).  Saving model ...
[Epoch 03/20], Time=11.02s, Train Loss=0.5481, Val Loss=0.4963, Val F1=0.6439, Test Loss=0.4981, Test F1=0.6464
Validation loss decreased (-0.579974 --> -0.643902).  Saving model ...
[Epoch 04/20], Time=11.17s, Train Loss=0.5234, Val Loss=0.4730, Val F1=0.6677, Test Loss=0.4826, Test F1=0.6651
Validation loss decreased (-0.643902 --> -0.667717).  Saving model ...
[Epoch 05/20], Time=11.09s, Train Loss=0.5089, Val Loss=0.4678, Val F1=0.6667, Test Loss=0.4795, Test F1=0.6701
EarlyStopping counter: 1 out of 3
[Epoch 06/20], Time=11.14s, Train Loss=0.5011, Val Loss=0.4644, Val F1=0.6632, Test Loss=0.4789, Test F1=0.6667
EarlyStopping counter: 2 out of 3
[Epoch 07/20], Time=11.00s, Train Loss=0.4936, Val Loss=0.4648, Val F1=0.6656, Test Loss=0.4804, Test F1=0.6708
EarlyStopping counter: 3 out of 3
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_1_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_1_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7831423895253683
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_1_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,17:55:53,4,1,0.6677,0.8168,0.6752,0.6604,4,0.001,2,2,2,6,0.3,8,3,0.32,0.27,0.6791,0,0.6582,0.8124,0.659,0.6574,0.0095,True,OK

[I 2026-07-08 17:55:53,298] Trial 1 finished with value: 0.6677165354330709 and parameters: {'lr': 0.001, 'd_model': 4, 'd_ff': 2, 'e_layers': 2, 'top_k': 2, 'dropout': 0.3, 'batch_size': 8, 'patience': 3, 'num_kernels': 6}. Best is trial 0 with value: 0.6791277258566978.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_2     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 3     --batch_size 8     --train_epochs 20     --learning_rate 0.0001     --e_layers 2     --d_model 32     --d_ff 32     --top_k 2     --num_kernels 6     --dropout 0.1     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.1
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0001
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_2
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 3
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_2_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.24s, Train Loss=0.7026, Val Loss=0.5260, Val F1=0.6187, Test Loss=0.5300, Test F1=0.6220
Validation loss decreased (inf --> -0.618658).  Saving model ...
[Epoch 02/20], Time=12.39s, Train Loss=0.5059, Val Loss=0.4717, Val F1=0.6646, Test Loss=0.4787, Test F1=0.6642
Validation loss decreased (-0.618658 --> -0.664577).  Saving model ...
[Epoch 03/20], Time=12.29s, Train Loss=0.4819, Val Loss=0.4589, Val F1=0.6770, Test Loss=0.4709, Test F1=0.6797
Validation loss decreased (-0.664577 --> -0.677019).  Saving model ...
[Epoch 04/20], Time=12.45s, Train Loss=0.4700, Val Loss=0.4521, Val F1=0.6767, Test Loss=0.4661, Test F1=0.6798
EarlyStopping counter: 1 out of 3
[Epoch 05/20], Time=12.29s, Train Loss=0.4584, Val Loss=0.4535, Val F1=0.6799, Test Loss=0.4685, Test F1=0.6859
Validation loss decreased (-0.677019 --> -0.679939).  Saving model ...
[Epoch 06/20], Time=12.28s, Train Loss=0.4555, Val Loss=0.4532, Val F1=0.6821, Test Loss=0.4676, Test F1=0.6845
Validation loss decreased (-0.679939 --> -0.682119).  Saving model ...
[Epoch 07/20], Time=12.53s, Train Loss=0.4507, Val Loss=0.4667, Val F1=0.6834, Test Loss=0.4814, Test F1=0.6810
Validation loss decreased (-0.682119 --> -0.683386).  Saving model ...
[Epoch 08/20], Time=12.34s, Train Loss=0.4501, Val Loss=0.4530, Val F1=0.6826, Test Loss=0.4669, Test F1=0.6841
EarlyStopping counter: 1 out of 3
[Epoch 09/20], Time=12.41s, Train Loss=0.4489, Val Loss=0.4523, Val F1=0.6811, Test Loss=0.4657, Test F1=0.6878
EarlyStopping counter: 2 out of 3
[Epoch 10/20], Time=12.37s, Train Loss=0.4486, Val Loss=0.4519, Val F1=0.6806, Test Loss=0.4648, Test F1=0.6864
EarlyStopping counter: 3 out of 3
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_2_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_2_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.79050736497545
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_2_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,17:58:51,4,2,0.6834,0.8287,0.6943,0.6728,32,0.0001,32,2,2,6,0.1,8,3,0.2,0.27,0.6834,2,0.6793,0.8261,0.6845,0.6742,0.0041,True,OK

[I 2026-07-08 17:58:51,123] Trial 2 finished with value: 0.6833855799373041 and parameters: {'lr': 0.0001, 'd_model': 32, 'd_ff': 32, 'e_layers': 2, 'top_k': 2, 'dropout': 0.1, 'batch_size': 8, 'patience': 3, 'num_kernels': 6}. Best is trial 2 with value: 0.6833855799373041.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_3     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 3     --batch_size 16     --train_epochs 20     --learning_rate 0.001     --e_layers 2     --d_model 2     --d_ff 2     --top_k 2     --num_kernels 6     --dropout 0.0     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 2
d_layers                 : 1
d_model                  : 2
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.0
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.001
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_3
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 3
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_3_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.04s, Train Loss=0.7380, Val Loss=0.6527, Val F1=0.5674, Test Loss=0.6606, Test F1=0.5563
Validation loss decreased (inf --> -0.567442).  Saving model ...
[Epoch 02/20], Time=5.91s, Train Loss=0.6031, Val Loss=0.5477, Val F1=0.5705, Test Loss=0.5563, Test F1=0.5603
Validation loss decreased (-0.567442 --> -0.570543).  Saving model ...
[Epoch 03/20], Time=5.97s, Train Loss=0.5490, Val Loss=0.5285, Val F1=0.5683, Test Loss=0.5396, Test F1=0.5629
EarlyStopping counter: 1 out of 3
[Epoch 04/20], Time=5.93s, Train Loss=0.5417, Val Loss=0.5265, Val F1=0.5700, Test Loss=0.5379, Test F1=0.5627
EarlyStopping counter: 2 out of 3
[Epoch 05/20], Time=5.91s, Train Loss=0.5367, Val Loss=0.5252, Val F1=0.5691, Test Loss=0.5358, Test F1=0.5689
EarlyStopping counter: 3 out of 3
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_3_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_3_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7545008183306056
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_3_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:00:11,4,3,0.5705,0.7322,0.586,0.5559,2,0.001,2,2,2,6,0.0,16,3,0.42,0.34,0.6834,2,0.5592,0.7283,0.6005,0.5233,0.0113,True,OK

[I 2026-07-08 18:00:11,482] Trial 3 finished with value: 0.5705426356589147 and parameters: {'lr': 0.001, 'd_model': 2, 'd_ff': 2, 'e_layers': 2, 'top_k': 2, 'dropout': 0.0, 'batch_size': 16, 'patience': 3, 'num_kernels': 6}. Best is trial 2 with value: 0.6833855799373041.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_4     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 3     --batch_size 16     --train_epochs 20     --learning_rate 0.0002317175804240088     --e_layers 3     --d_model 2     --d_ff 4     --top_k 2     --num_kernels 4     --dropout 0.2447411578889518     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 4
d_layers                 : 1
d_model                  : 2
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2447411578889518
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0002317175804240088
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_4
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 3
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_4_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.94s, Train Loss=0.7786, Val Loss=0.7684, Val F1=0.4996, Test Loss=0.7698, Test F1=0.4993
Validation loss decreased (inf --> -0.499593).  Saving model ...
[Epoch 02/20], Time=7.05s, Train Loss=0.7444, Val Loss=0.7316, Val F1=0.4996, Test Loss=0.7330, Test F1=0.4993
Validation loss decreased (-0.499593 --> -0.499593).  Saving model ...
[Epoch 03/20], Time=6.92s, Train Loss=0.7140, Val Loss=0.6969, Val F1=0.5107, Test Loss=0.6979, Test F1=0.5156
Validation loss decreased (-0.499593 --> -0.510675).  Saving model ...
[Epoch 04/20], Time=7.08s, Train Loss=0.6841, Val Loss=0.6703, Val F1=0.5133, Test Loss=0.6712, Test F1=0.5184
Validation loss decreased (-0.510675 --> -0.513305).  Saving model ...
[Epoch 05/20], Time=6.92s, Train Loss=0.6624, Val Loss=0.6510, Val F1=0.5107, Test Loss=0.6514, Test F1=0.5178
EarlyStopping counter: 1 out of 3
[Epoch 06/20], Time=7.05s, Train Loss=0.6450, Val Loss=0.6358, Val F1=0.5112, Test Loss=0.6373, Test F1=0.5178
EarlyStopping counter: 2 out of 3
[Epoch 07/20], Time=7.00s, Train Loss=0.6310, Val Loss=0.6227, Val F1=0.5124, Test Loss=0.6252, Test F1=0.5174
EarlyStopping counter: 3 out of 3
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_4_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_4_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.648936170212766
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_4_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:01:52,4,4,0.5133,0.4349,0.9522,0.3514,2,0.000232,4,3,2,4,0.244741,16,3,0.43,0.43,0.6834,2,0.5184,0.4352,0.9669,0.3541,-0.0051,False,OK

[I 2026-07-08 18:01:52,046] Trial 4 finished with value: 0.5133047210300429 and parameters: {'lr': 0.0002317175804240088, 'd_model': 2, 'd_ff': 4, 'e_layers': 3, 'top_k': 2, 'dropout': 0.2447411578889518, 'batch_size': 16, 'patience': 3, 'num_kernels': 4}. Best is trial 2 with value: 0.6833855799373041.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_5     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0004105410738776579     --e_layers 3     --d_model 64     --d_ff 128     --top_k 2     --num_kernels 4     --dropout 0.20802720847112433     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.20802720847112433
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0004105410738776579
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_5
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_5_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=15.13s, Train Loss=0.5035, Val Loss=0.4595, Val F1=0.6781, Test Loss=0.4683, Test F1=0.6791
Validation loss decreased (inf --> -0.678072).  Saving model ...
[Epoch 02/20], Time=13.99s, Train Loss=0.4738, Val Loss=0.4550, Val F1=0.6805, Test Loss=0.4718, Test F1=0.6874
Validation loss decreased (-0.678072 --> -0.680484).  Saving model ...
[Epoch 03/20], Time=14.05s, Train Loss=0.4606, Val Loss=0.4601, Val F1=0.6816, Test Loss=0.4733, Test F1=0.6775
Validation loss decreased (-0.680484 --> -0.681600).  Saving model ...
[Epoch 04/20], Time=13.86s, Train Loss=0.4568, Val Loss=0.4517, Val F1=0.6765, Test Loss=0.4647, Test F1=0.6861
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=13.94s, Train Loss=0.4503, Val Loss=0.4472, Val F1=0.6817, Test Loss=0.4606, Test F1=0.6957
Validation loss decreased (-0.681600 --> -0.681750).  Saving model ...
[Epoch 06/20], Time=13.85s, Train Loss=0.4421, Val Loss=0.4523, Val F1=0.6893, Test Loss=0.4776, Test F1=0.6658
Validation loss decreased (-0.681750 --> -0.689320).  Saving model ...
[Epoch 07/20], Time=13.97s, Train Loss=0.4416, Val Loss=0.4376, Val F1=0.7061, Test Loss=0.4618, Test F1=0.7008
Validation loss decreased (-0.689320 --> -0.706076).  Saving model ...
[Epoch 08/20], Time=14.04s, Train Loss=0.4404, Val Loss=0.4425, Val F1=0.6906, Test Loss=0.4605, Test F1=0.7019
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=13.92s, Train Loss=0.4361, Val Loss=0.4530, Val F1=0.6926, Test Loss=0.4690, Test F1=0.6746
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=13.99s, Train Loss=0.4333, Val Loss=0.4477, Val F1=0.6952, Test Loss=0.4652, Test F1=0.6876
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=13.87s, Train Loss=0.4310, Val Loss=0.4662, Val F1=0.6807, Test Loss=0.4685, Test F1=0.7030
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=13.83s, Train Loss=0.4279, Val Loss=0.4447, Val F1=0.6988, Test Loss=0.4594, Test F1=0.7004
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_5_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_5_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.806873977086743
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_5_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:05:35,4,5,0.7061,0.8427,0.6847,0.7288,64,0.000411,128,3,2,4,0.208027,8,5,0.36,0.33,0.7061,5,0.6961,0.8342,0.6616,0.7345,0.01,False,OK

[I 2026-07-08 18:05:35,915] Trial 5 finished with value: 0.7060755336617406 and parameters: {'lr': 0.0004105410738776579, 'd_model': 64, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.20802720847112433, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_6     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 2     --batch_size 16     --train_epochs 20     --learning_rate 0.0005782645901916579     --e_layers 6     --d_model 2     --d_ff 64     --top_k 2     --num_kernels 6     --dropout 0.28274293753904683     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 2
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.28274293753904683
dtwwarp                  : False
e_layers                 : 6
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0005782645901916579
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_6
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 2
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_6_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el6_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.0.kernels.4.weight
 - model.3.conv.0.kernels.4.bias
 - model.3.conv.0.kernels.5.weight
 - model.3.conv.0.kernels.5.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.3.conv.2.kernels.4.weight
 - model.3.conv.2.kernels.4.bias
 - model.3.conv.2.kernels.5.weight
 - model.3.conv.2.kernels.5.bias
 - model.4.conv.0.kernels.0.weight
 - model.4.conv.0.kernels.0.bias
 - model.4.conv.0.kernels.1.weight
 - model.4.conv.0.kernels.1.bias
 - model.4.conv.0.kernels.2.weight
 - model.4.conv.0.kernels.2.bias
 - model.4.conv.0.kernels.3.weight
 - model.4.conv.0.kernels.3.bias
 - model.4.conv.0.kernels.4.weight
 - model.4.conv.0.kernels.4.bias
 - model.4.conv.0.kernels.5.weight
 - model.4.conv.0.kernels.5.bias
 - model.4.conv.2.kernels.0.weight
 - model.4.conv.2.kernels.0.bias
 - model.4.conv.2.kernels.1.weight
 - model.4.conv.2.kernels.1.bias
 - model.4.conv.2.kernels.2.weight
 - model.4.conv.2.kernels.2.bias
 - model.4.conv.2.kernels.3.weight
 - model.4.conv.2.kernels.3.bias
 - model.4.conv.2.kernels.4.weight
 - model.4.conv.2.kernels.4.bias
 - model.4.conv.2.kernels.5.weight
 - model.4.conv.2.kernels.5.bias
 - model.5.conv.0.kernels.0.weight
 - model.5.conv.0.kernels.0.bias
 - model.5.conv.0.kernels.1.weight
 - model.5.conv.0.kernels.1.bias
 - model.5.conv.0.kernels.2.weight
 - model.5.conv.0.kernels.2.bias
 - model.5.conv.0.kernels.3.weight
 - model.5.conv.0.kernels.3.bias
 - model.5.conv.0.kernels.4.weight
 - model.5.conv.0.kernels.4.bias
 - model.5.conv.0.kernels.5.weight
 - model.5.conv.0.kernels.5.bias
 - model.5.conv.2.kernels.0.weight
 - model.5.conv.2.kernels.0.bias
 - model.5.conv.2.kernels.1.weight
 - model.5.conv.2.kernels.1.bias
 - model.5.conv.2.kernels.2.weight
 - model.5.conv.2.kernels.2.bias
 - model.5.conv.2.kernels.3.weight
 - model.5.conv.2.kernels.3.bias
 - model.5.conv.2.kernels.4.weight
 - model.5.conv.2.kernels.4.bias
 - model.5.conv.2.kernels.5.weight
 - model.5.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=17.21s, Train Loss=0.7001, Val Loss=0.6661, Val F1=0.4864, Test Loss=0.6700, Test F1=0.4867
Validation loss decreased (inf --> -0.486445).  Saving model ...
[Epoch 02/20], Time=16.11s, Train Loss=0.6645, Val Loss=0.6421, Val F1=0.4864, Test Loss=0.6462, Test F1=0.4867
Validation loss decreased (-0.486445 --> -0.486445).  Saving model ...
[Epoch 03/20], Time=16.16s, Train Loss=0.6474, Val Loss=0.6307, Val F1=0.4864, Test Loss=0.6354, Test F1=0.4867
Validation loss decreased (-0.486445 --> -0.486445).  Saving model ...
[Epoch 04/20], Time=16.05s, Train Loss=0.6388, Val Loss=0.6256, Val F1=0.4864, Test Loss=0.6313, Test F1=0.4867
Validation loss decreased (-0.486445 --> -0.486445).  Saving model ...
Traceback (most recent call last):
  File "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py", line 236, in <module>
    exp.train(setting)
  File "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/exp/exp_classification_save_full_train_opt_WL.py", line 211, in train
    vali_loss, val_f1 = self.vali(vali_data, vali_loader, criterion)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/exp/exp_classification_save_full_train_opt_WL.py", line 75, in vali
    outputs = self.model(batch_x, padding_mask, None, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/models/TimesNet.py", line 213, in forward
    dec_out = self.classification(x_enc, x_mark_enc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/models/TimesNet.py", line 188, in classification
    enc_out = self.layer_norm(self.model[i](enc_out))
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1779, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1790, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/models/TimesNet.py", line 53, in forward
    out = out.reshape(B, length // period, period,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[1, 0, 0, 2]' is invalid for input of size 8

[I 2026-07-08 18:07:39,354] Trial 6 pruned. ❌ val_prob.npy / val_true.npy not found

==========================xxxxxxxxxxxxxxxxxx===============
❌ Trial 6 failed: ❌ val_prob.npy / val_true.npy not found
CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_7     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0006416354462323625     --e_layers 2     --d_model 64     --d_ff 16     --top_k 2     --num_kernels 6     --dropout 0.25456416450551217     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.25456416450551217
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0006416354462323625
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_7
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_7_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.93s, Train Loss=0.5772, Val Loss=0.4673, Val F1=0.6625, Test Loss=0.4807, Test F1=0.6684
Validation loss decreased (inf --> -0.662519).  Saving model ...
[Epoch 02/20], Time=6.95s, Train Loss=0.4818, Val Loss=0.4551, Val F1=0.6800, Test Loss=0.4727, Test F1=0.6757
Validation loss decreased (-0.662519 --> -0.680000).  Saving model ...
[Epoch 03/20], Time=6.74s, Train Loss=0.4708, Val Loss=0.4593, Val F1=0.6677, Test Loss=0.4770, Test F1=0.6717
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=6.82s, Train Loss=0.4634, Val Loss=0.4645, Val F1=0.6863, Test Loss=0.4852, Test F1=0.6781
Validation loss decreased (-0.680000 --> -0.686335).  Saving model ...
[Epoch 05/20], Time=6.81s, Train Loss=0.4608, Val Loss=0.4578, Val F1=0.6884, Test Loss=0.4812, Test F1=0.6793
Validation loss decreased (-0.686335 --> -0.688418).  Saving model ...
[Epoch 06/20], Time=6.93s, Train Loss=0.4573, Val Loss=0.4703, Val F1=0.6837, Test Loss=0.4815, Test F1=0.6891
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=6.74s, Train Loss=0.4511, Val Loss=0.4535, Val F1=0.6701, Test Loss=0.4689, Test F1=0.6753
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=6.89s, Train Loss=0.4513, Val Loss=0.4386, Val F1=0.6889, Test Loss=0.4544, Test F1=0.6928
Validation loss decreased (-0.688418 --> -0.688889).  Saving model ...
[Epoch 09/20], Time=6.81s, Train Loss=0.4452, Val Loss=0.4401, Val F1=0.6869, Test Loss=0.4569, Test F1=0.6884
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=6.83s, Train Loss=0.4445, Val Loss=0.4417, Val F1=0.6994, Test Loss=0.4620, Test F1=0.7028
Validation loss decreased (-0.688889 --> -0.699367).  Saving model ...
[Epoch 11/20], Time=6.91s, Train Loss=0.4436, Val Loss=0.4373, Val F1=0.6980, Test Loss=0.4525, Test F1=0.7044
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=6.86s, Train Loss=0.4386, Val Loss=0.4407, Val F1=0.6954, Test Loss=0.4569, Test F1=0.7037
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=6.89s, Train Loss=0.4379, Val Loss=0.4442, Val F1=0.6973, Test Loss=0.4629, Test F1=0.7039
EarlyStopping counter: 3 out of 5
[Epoch 14/20], Time=6.88s, Train Loss=0.4302, Val Loss=0.4407, Val F1=0.6980, Test Loss=0.4618, Test F1=0.6982
EarlyStopping counter: 4 out of 5
[Epoch 15/20], Time=6.85s, Train Loss=0.4310, Val Loss=0.4327, Val F1=0.6913, Test Loss=0.4567, Test F1=0.6961
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_7_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_7_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8117839607201309
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_7_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:10:13,4,7,0.6994,0.8387,0.7038,0.695,64,0.000642,16,2,2,6,0.254564,16,5,0.38,0.38,0.7061,5,0.7028,0.8343,0.6921,0.7139,-0.0035,False,OK

[I 2026-07-08 18:10:13,667] Trial 7 finished with value: 0.6993670886075949 and parameters: {'lr': 0.0006416354462323625, 'd_model': 64, 'd_ff': 16, 'e_layers': 2, 'top_k': 2, 'dropout': 0.25456416450551217, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_8     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 2     --batch_size 8     --train_epochs 20     --learning_rate 0.00012758738854286804     --e_layers 6     --d_model 16     --d_ff 16     --top_k 2     --num_kernels 6     --dropout 0.0027808522124762817     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 16
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.0027808522124762817
dtwwarp                  : False
e_layers                 : 6
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00012758738854286804
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_8
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 2
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_8_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el6_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.0.kernels.4.weight
 - model.3.conv.0.kernels.4.bias
 - model.3.conv.0.kernels.5.weight
 - model.3.conv.0.kernels.5.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.3.conv.2.kernels.4.weight
 - model.3.conv.2.kernels.4.bias
 - model.3.conv.2.kernels.5.weight
 - model.3.conv.2.kernels.5.bias
 - model.4.conv.0.kernels.0.weight
 - model.4.conv.0.kernels.0.bias
 - model.4.conv.0.kernels.1.weight
 - model.4.conv.0.kernels.1.bias
 - model.4.conv.0.kernels.2.weight
 - model.4.conv.0.kernels.2.bias
 - model.4.conv.0.kernels.3.weight
 - model.4.conv.0.kernels.3.bias
 - model.4.conv.0.kernels.4.weight
 - model.4.conv.0.kernels.4.bias
 - model.4.conv.0.kernels.5.weight
 - model.4.conv.0.kernels.5.bias
 - model.4.conv.2.kernels.0.weight
 - model.4.conv.2.kernels.0.bias
 - model.4.conv.2.kernels.1.weight
 - model.4.conv.2.kernels.1.bias
 - model.4.conv.2.kernels.2.weight
 - model.4.conv.2.kernels.2.bias
 - model.4.conv.2.kernels.3.weight
 - model.4.conv.2.kernels.3.bias
 - model.4.conv.2.kernels.4.weight
 - model.4.conv.2.kernels.4.bias
 - model.4.conv.2.kernels.5.weight
 - model.4.conv.2.kernels.5.bias
 - model.5.conv.0.kernels.0.weight
 - model.5.conv.0.kernels.0.bias
 - model.5.conv.0.kernels.1.weight
 - model.5.conv.0.kernels.1.bias
 - model.5.conv.0.kernels.2.weight
 - model.5.conv.0.kernels.2.bias
 - model.5.conv.0.kernels.3.weight
 - model.5.conv.0.kernels.3.bias
 - model.5.conv.0.kernels.4.weight
 - model.5.conv.0.kernels.4.bias
 - model.5.conv.0.kernels.5.weight
 - model.5.conv.0.kernels.5.bias
 - model.5.conv.2.kernels.0.weight
 - model.5.conv.2.kernels.0.bias
 - model.5.conv.2.kernels.1.weight
 - model.5.conv.2.kernels.1.bias
 - model.5.conv.2.kernels.2.weight
 - model.5.conv.2.kernels.2.bias
 - model.5.conv.2.kernels.3.weight
 - model.5.conv.2.kernels.3.bias
 - model.5.conv.2.kernels.4.weight
 - model.5.conv.2.kernels.4.bias
 - model.5.conv.2.kernels.5.weight
 - model.5.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=31.87s, Train Loss=0.5944, Val Loss=0.5095, Val F1=0.6230, Test Loss=0.5164, Test F1=0.6241
Validation loss decreased (inf --> -0.623044).  Saving model ...
[Epoch 02/20], Time=31.07s, Train Loss=0.4983, Val Loss=0.4721, Val F1=0.6634, Test Loss=0.4875, Test F1=0.6591
Validation loss decreased (-0.623044 --> -0.663430).  Saving model ...
[Epoch 03/20], Time=31.16s, Train Loss=0.4773, Val Loss=0.4559, Val F1=0.6795, Test Loss=0.4750, Test F1=0.6726
Validation loss decreased (-0.663430 --> -0.679487).  Saving model ...
[Epoch 04/20], Time=31.47s, Train Loss=0.4618, Val Loss=0.4523, Val F1=0.6909, Test Loss=0.4699, Test F1=0.6760
Validation loss decreased (-0.679487 --> -0.690852).  Saving model ...
[Epoch 05/20], Time=30.73s, Train Loss=0.4559, Val Loss=0.4483, Val F1=0.6924, Test Loss=0.4652, Test F1=0.6795
Validation loss decreased (-0.690852 --> -0.692427).  Saving model ...
[Epoch 06/20], Time=30.68s, Train Loss=0.4498, Val Loss=0.4483, Val F1=0.6874, Test Loss=0.4643, Test F1=0.6805
EarlyStopping counter: 1 out of 2
[Epoch 07/20], Time=30.61s, Train Loss=0.4466, Val Loss=0.4456, Val F1=0.6854, Test Loss=0.4626, Test F1=0.6863
EarlyStopping counter: 2 out of 2
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_8_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el6_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_8_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el6_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7962356792144026
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_8_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el6_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:14:53,4,8,0.6924,0.8299,0.7134,0.6727,16,0.000128,16,6,2,6,0.002781,8,2,0.32,0.27,0.7061,5,0.6784,0.8243,0.687,0.67,0.014,False,OK

[I 2026-07-08 18:14:53,344] Trial 8 finished with value: 0.6924265842349304 and parameters: {'lr': 0.00012758738854286804, 'd_model': 16, 'd_ff': 16, 'e_layers': 6, 'top_k': 2, 'dropout': 0.0027808522124762817, 'batch_size': 8, 'patience': 2, 'num_kernels': 6}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_9     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 2     --batch_size 16     --train_epochs 20     --learning_rate 0.00018779053622035974     --e_layers 6     --d_model 16     --d_ff 64     --top_k 2     --num_kernels 3     --dropout 0.09682210860460017     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 16
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.09682210860460017
dtwwarp                  : False
e_layers                 : 6
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00018779053622035974
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_9
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 2
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_9_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el6_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.4.conv.0.kernels.0.weight
 - model.4.conv.0.kernels.0.bias
 - model.4.conv.0.kernels.1.weight
 - model.4.conv.0.kernels.1.bias
 - model.4.conv.0.kernels.2.weight
 - model.4.conv.0.kernels.2.bias
 - model.4.conv.2.kernels.0.weight
 - model.4.conv.2.kernels.0.bias
 - model.4.conv.2.kernels.1.weight
 - model.4.conv.2.kernels.1.bias
 - model.4.conv.2.kernels.2.weight
 - model.4.conv.2.kernels.2.bias
 - model.5.conv.0.kernels.0.weight
 - model.5.conv.0.kernels.0.bias
 - model.5.conv.0.kernels.1.weight
 - model.5.conv.0.kernels.1.bias
 - model.5.conv.0.kernels.2.weight
 - model.5.conv.0.kernels.2.bias
 - model.5.conv.2.kernels.0.weight
 - model.5.conv.2.kernels.0.bias
 - model.5.conv.2.kernels.1.weight
 - model.5.conv.2.kernels.1.bias
 - model.5.conv.2.kernels.2.weight
 - model.5.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=12.86s, Train Loss=0.5953, Val Loss=0.5074, Val F1=0.6011, Test Loss=0.5129, Test F1=0.6249
Validation loss decreased (inf --> -0.601093).  Saving model ...
[Epoch 02/20], Time=11.63s, Train Loss=0.5109, Val Loss=0.4770, Val F1=0.6453, Test Loss=0.4873, Test F1=0.6571
Validation loss decreased (-0.601093 --> -0.645265).  Saving model ...
[Epoch 03/20], Time=11.58s, Train Loss=0.4916, Val Loss=0.4628, Val F1=0.6615, Test Loss=0.4754, Test F1=0.6756
Validation loss decreased (-0.645265 --> -0.661538).  Saving model ...
[Epoch 04/20], Time=11.67s, Train Loss=0.4800, Val Loss=0.4542, Val F1=0.6771, Test Loss=0.4707, Test F1=0.6764
Validation loss decreased (-0.661538 --> -0.677067).  Saving model ...
[Epoch 05/20], Time=11.69s, Train Loss=0.4633, Val Loss=0.4499, Val F1=0.6741, Test Loss=0.4672, Test F1=0.6782
EarlyStopping counter: 1 out of 2
[Epoch 06/20], Time=11.69s, Train Loss=0.4628, Val Loss=0.4469, Val F1=0.6810, Test Loss=0.4658, Test F1=0.6751
Validation loss decreased (-0.677067 --> -0.680982).  Saving model ...
[Epoch 07/20], Time=11.64s, Train Loss=0.4570, Val Loss=0.4508, Val F1=0.6752, Test Loss=0.4682, Test F1=0.6649
EarlyStopping counter: 1 out of 2
[Epoch 08/20], Time=11.55s, Train Loss=0.4484, Val Loss=0.4539, Val F1=0.6807, Test Loss=0.4697, Test F1=0.6824
EarlyStopping counter: 2 out of 2
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_9_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el6_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_9_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el6_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7970540098199672
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_9_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el6_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:17:20,4,9,0.681,0.8312,0.707,0.6568,16,0.000188,64,6,2,3,0.096822,16,2,0.35,0.26,0.7061,5,0.6725,0.8228,0.6845,0.6609,0.0085,False,OK

[I 2026-07-08 18:17:20,683] Trial 9 finished with value: 0.6809815950920245 and parameters: {'lr': 0.00018779053622035974, 'd_model': 16, 'd_ff': 64, 'e_layers': 6, 'top_k': 2, 'dropout': 0.09682210860460017, 'batch_size': 16, 'patience': 2, 'num_kernels': 3}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_10     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.000623330026117765     --e_layers 5     --d_model 16     --d_ff 128     --top_k 2     --num_kernels 4     --dropout 0.30544399741971057     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 16
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.30544399741971057
dtwwarp                  : False
e_layers                 : 5
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.000623330026117765
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_10
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_10_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el5_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.4.conv.0.kernels.0.weight
 - model.4.conv.0.kernels.0.bias
 - model.4.conv.0.kernels.1.weight
 - model.4.conv.0.kernels.1.bias
 - model.4.conv.0.kernels.2.weight
 - model.4.conv.0.kernels.2.bias
 - model.4.conv.0.kernels.3.weight
 - model.4.conv.0.kernels.3.bias
 - model.4.conv.2.kernels.0.weight
 - model.4.conv.2.kernels.0.bias
 - model.4.conv.2.kernels.1.weight
 - model.4.conv.2.kernels.1.bias
 - model.4.conv.2.kernels.2.weight
 - model.4.conv.2.kernels.2.bias
 - model.4.conv.2.kernels.3.weight
 - model.4.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=21.80s, Train Loss=0.5620, Val Loss=0.4696, Val F1=0.6655, Test Loss=0.4849, Test F1=0.6597
Validation loss decreased (inf --> -0.665511).  Saving model ...
[Epoch 02/20], Time=21.05s, Train Loss=0.4919, Val Loss=0.4597, Val F1=0.6761, Test Loss=0.4761, Test F1=0.6830
Validation loss decreased (-0.665511 --> -0.676145).  Saving model ...
[Epoch 03/20], Time=20.79s, Train Loss=0.4886, Val Loss=0.4783, Val F1=0.6667, Test Loss=0.4837, Test F1=0.6758
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=20.58s, Train Loss=0.4785, Val Loss=0.4670, Val F1=0.6719, Test Loss=0.4805, Test F1=0.6684
EarlyStopping counter: 2 out of 5
[Epoch 05/20], Time=20.87s, Train Loss=0.4718, Val Loss=0.4586, Val F1=0.6732, Test Loss=0.4753, Test F1=0.6667
EarlyStopping counter: 3 out of 5
[Epoch 06/20], Time=20.85s, Train Loss=0.4747, Val Loss=0.4593, Val F1=0.6841, Test Loss=0.4685, Test F1=0.6910
Validation loss decreased (-0.676145 --> -0.684124).  Saving model ...
[Epoch 07/20], Time=20.71s, Train Loss=0.4676, Val Loss=0.4588, Val F1=0.6764, Test Loss=0.4689, Test F1=0.6772
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=20.71s, Train Loss=0.4623, Val Loss=0.4506, Val F1=0.6843, Test Loss=0.4667, Test F1=0.6929
Validation loss decreased (-0.684124 --> -0.684292).  Saving model ...
[Epoch 09/20], Time=20.83s, Train Loss=0.4639, Val Loss=0.4493, Val F1=0.6825, Test Loss=0.4652, Test F1=0.6853
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=20.76s, Train Loss=0.4597, Val Loss=0.4531, Val F1=0.6852, Test Loss=0.4669, Test F1=0.6858
Validation loss decreased (-0.684292 --> -0.685246).  Saving model ...
[Epoch 11/20], Time=20.92s, Train Loss=0.4580, Val Loss=0.4533, Val F1=0.6803, Test Loss=0.4690, Test F1=0.6839
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=20.75s, Train Loss=0.4579, Val Loss=0.4588, Val F1=0.6793, Test Loss=0.4716, Test F1=0.6858
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=20.88s, Train Loss=0.4599, Val Loss=0.4513, Val F1=0.6795, Test Loss=0.4657, Test F1=0.6754
EarlyStopping counter: 3 out of 5
[Epoch 14/20], Time=20.77s, Train Loss=0.4554, Val Loss=0.4599, Val F1=0.6743, Test Loss=0.4735, Test F1=0.6704
EarlyStopping counter: 4 out of 5
[Epoch 15/20], Time=20.79s, Train Loss=0.4570, Val Loss=0.4524, Val F1=0.6740, Test Loss=0.4613, Test F1=0.6886
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_10_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el5_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_10_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el5_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8011456628477905
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_10_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el5_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:23:31,4,10,0.6852,0.8271,0.6656,0.7061,16,0.000623,128,5,2,4,0.305444,8,5,0.4,0.33,0.7061,5,0.672,0.8248,0.6361,0.7123,0.0132,False,OK

[I 2026-07-08 18:23:31,263] Trial 10 finished with value: 0.6852459016393443 and parameters: {'lr': 0.000623330026117765, 'd_model': 16, 'd_ff': 128, 'e_layers': 5, 'top_k': 2, 'dropout': 0.30544399741971057, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_11     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0005007666891209306     --e_layers 3     --d_model 64     --d_ff 32     --top_k 2     --num_kernels 6     --dropout 0.2753321516433814     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2753321516433814
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0005007666891209306
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_11
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_11_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=10.41s, Train Loss=0.5576, Val Loss=0.4588, Val F1=0.6728, Test Loss=0.4717, Test F1=0.6697
Validation loss decreased (inf --> -0.672755).  Saving model ...
[Epoch 02/20], Time=9.39s, Train Loss=0.4853, Val Loss=0.4579, Val F1=0.6832, Test Loss=0.4739, Test F1=0.6782
Validation loss decreased (-0.672755 --> -0.683153).  Saving model ...
[Epoch 03/20], Time=9.21s, Train Loss=0.4719, Val Loss=0.4625, Val F1=0.6815, Test Loss=0.4713, Test F1=0.6806
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=9.11s, Train Loss=0.4646, Val Loss=0.4550, Val F1=0.6783, Test Loss=0.4640, Test F1=0.6811
EarlyStopping counter: 2 out of 5
[Epoch 05/20], Time=9.17s, Train Loss=0.4590, Val Loss=0.4656, Val F1=0.6855, Test Loss=0.4785, Test F1=0.7006
Validation loss decreased (-0.683153 --> -0.685535).  Saving model ...
[Epoch 06/20], Time=9.28s, Train Loss=0.4504, Val Loss=0.4507, Val F1=0.6817, Test Loss=0.4637, Test F1=0.7040
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=9.22s, Train Loss=0.4452, Val Loss=0.4761, Val F1=0.6937, Test Loss=0.4881, Test F1=0.6924
Validation loss decreased (-0.685535 --> -0.693679).  Saving model ...
[Epoch 08/20], Time=9.12s, Train Loss=0.4484, Val Loss=0.4578, Val F1=0.6947, Test Loss=0.4713, Test F1=0.6995
Validation loss decreased (-0.693679 --> -0.694704).  Saving model ...
[Epoch 09/20], Time=9.11s, Train Loss=0.4430, Val Loss=0.4486, Val F1=0.6887, Test Loss=0.4603, Test F1=0.6992
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=9.19s, Train Loss=0.4362, Val Loss=0.4393, Val F1=0.6883, Test Loss=0.4591, Test F1=0.6831
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=9.14s, Train Loss=0.4410, Val Loss=0.4529, Val F1=0.6941, Test Loss=0.4646, Test F1=0.6988
EarlyStopping counter: 3 out of 5
[Epoch 12/20], Time=9.21s, Train Loss=0.4420, Val Loss=0.4379, Val F1=0.6959, Test Loss=0.4562, Test F1=0.6998
Validation loss decreased (-0.694704 --> -0.695925).  Saving model ...
[Epoch 13/20], Time=9.27s, Train Loss=0.4351, Val Loss=0.4361, Val F1=0.6928, Test Loss=0.4525, Test F1=0.6996
EarlyStopping counter: 1 out of 5
[Epoch 14/20], Time=9.14s, Train Loss=0.4357, Val Loss=0.4364, Val F1=0.6944, Test Loss=0.4571, Test F1=0.7003
EarlyStopping counter: 2 out of 5
[Epoch 15/20], Time=9.16s, Train Loss=0.4333, Val Loss=0.4537, Val F1=0.6867, Test Loss=0.4704, Test F1=0.6972
EarlyStopping counter: 3 out of 5
[Epoch 16/20], Time=9.14s, Train Loss=0.4334, Val Loss=0.4409, Val F1=0.6937, Test Loss=0.4698, Test F1=0.6922
EarlyStopping counter: 4 out of 5
[Epoch 17/20], Time=9.28s, Train Loss=0.4295, Val Loss=0.4442, Val F1=0.6937, Test Loss=0.4616, Test F1=0.7050
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_11_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_11_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8003273322422259
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_11_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:27:00,4,11,0.6959,0.8377,0.707,0.6852,64,0.000501,32,3,2,6,0.275332,16,5,0.33,0.26,0.7061,5,0.6935,0.8345,0.6794,0.7082,0.0024,False,OK

[I 2026-07-08 18:27:00,675] Trial 11 finished with value: 0.6959247648902821 and parameters: {'lr': 0.0005007666891209306, 'd_model': 64, 'd_ff': 32, 'e_layers': 3, 'top_k': 2, 'dropout': 0.2753321516433814, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_12     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0002949527513029715     --e_layers 2     --d_model 32     --d_ff 16     --top_k 2     --num_kernels 4     --dropout 0.3079987503352446     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.3079987503352446
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0002949527513029715
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_12
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_12_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=6.66s, Train Loss=0.6876, Val Loss=0.5408, Val F1=0.5790, Test Loss=0.5417, Test F1=0.5843
Validation loss decreased (inf --> -0.579035).  Saving model ...
[Epoch 02/20], Time=5.56s, Train Loss=0.5525, Val Loss=0.4986, Val F1=0.6207, Test Loss=0.5031, Test F1=0.6343
Validation loss decreased (-0.579035 --> -0.620690).  Saving model ...
[Epoch 03/20], Time=5.52s, Train Loss=0.5107, Val Loss=0.4789, Val F1=0.6565, Test Loss=0.4909, Test F1=0.6582
Validation loss decreased (-0.620690 --> -0.656514).  Saving model ...
[Epoch 04/20], Time=5.65s, Train Loss=0.5007, Val Loss=0.4711, Val F1=0.6690, Test Loss=0.4867, Test F1=0.6675
Validation loss decreased (-0.656514 --> -0.668954).  Saving model ...
[Epoch 05/20], Time=5.64s, Train Loss=0.4892, Val Loss=0.4654, Val F1=0.6773, Test Loss=0.4822, Test F1=0.6717
Validation loss decreased (-0.668954 --> -0.677266).  Saving model ...
[Epoch 06/20], Time=5.58s, Train Loss=0.4813, Val Loss=0.4597, Val F1=0.6731, Test Loss=0.4757, Test F1=0.6708
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=5.51s, Train Loss=0.4764, Val Loss=0.4560, Val F1=0.6801, Test Loss=0.4741, Test F1=0.6792
Validation loss decreased (-0.677266 --> -0.680062).  Saving model ...
[Epoch 08/20], Time=5.55s, Train Loss=0.4706, Val Loss=0.4547, Val F1=0.6775, Test Loss=0.4715, Test F1=0.6734
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=5.56s, Train Loss=0.4647, Val Loss=0.4564, Val F1=0.6852, Test Loss=0.4755, Test F1=0.6803
Validation loss decreased (-0.680062 --> -0.685155).  Saving model ...
[Epoch 10/20], Time=5.55s, Train Loss=0.4622, Val Loss=0.4537, Val F1=0.6837, Test Loss=0.4726, Test F1=0.6779
EarlyStopping counter: 1 out of 5
[Epoch 11/20], Time=5.76s, Train Loss=0.4645, Val Loss=0.4526, Val F1=0.6835, Test Loss=0.4688, Test F1=0.6814
EarlyStopping counter: 2 out of 5
[Epoch 12/20], Time=5.59s, Train Loss=0.4608, Val Loss=0.4526, Val F1=0.6836, Test Loss=0.4695, Test F1=0.6806
EarlyStopping counter: 3 out of 5
[Epoch 13/20], Time=5.77s, Train Loss=0.4589, Val Loss=0.4489, Val F1=0.6826, Test Loss=0.4681, Test F1=0.6838
EarlyStopping counter: 4 out of 5
[Epoch 14/20], Time=5.61s, Train Loss=0.4535, Val Loss=0.4534, Val F1=0.6880, Test Loss=0.4751, Test F1=0.6831
Validation loss decreased (-0.685155 --> -0.688000).  Saving model ...
[Epoch 15/20], Time=5.63s, Train Loss=0.4573, Val Loss=0.4531, Val F1=0.6867, Test Loss=0.4724, Test F1=0.6802
EarlyStopping counter: 1 out of 5
[Epoch 16/20], Time=5.58s, Train Loss=0.4559, Val Loss=0.4471, Val F1=0.6878, Test Loss=0.4659, Test F1=0.6883
EarlyStopping counter: 2 out of 5
[Epoch 17/20], Time=5.56s, Train Loss=0.4546, Val Loss=0.4458, Val F1=0.6854, Test Loss=0.4656, Test F1=0.6853
EarlyStopping counter: 3 out of 5
[Epoch 18/20], Time=5.62s, Train Loss=0.4497, Val Loss=0.4454, Val F1=0.6840, Test Loss=0.4624, Test F1=0.6913
EarlyStopping counter: 4 out of 5
[Epoch 19/20], Time=5.59s, Train Loss=0.4531, Val Loss=0.4420, Val F1=0.6872, Test Loss=0.4615, Test F1=0.6948
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_12_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_12_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7986906710310966
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_12_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:29:38,4,12,0.688,0.8296,0.6847,0.6913,32,0.000295,16,2,2,4,0.307999,16,5,0.3,0.28,0.7061,5,0.6745,0.8278,0.6565,0.6935,0.0135,False,OK

[I 2026-07-08 18:29:38,015] Trial 12 finished with value: 0.688 and parameters: {'lr': 0.0002949527513029715, 'd_model': 32, 'd_ff': 16, 'e_layers': 2, 'top_k': 2, 'dropout': 0.3079987503352446, 'batch_size': 16, 'patience': 5, 'num_kernels': 4}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_13     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0004966862745708952     --e_layers 4     --d_model 64     --d_ff 4     --top_k 2     --num_kernels 4     --dropout 0.11062283314083585     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 4
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.11062283314083585
dtwwarp                  : False
e_layers                 : 4
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0004966862745708952
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_13
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_13_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=17.94s, Train Loss=0.5399, Val Loss=0.4595, Val F1=0.6811, Test Loss=0.4699, Test F1=0.6764
Validation loss decreased (inf --> -0.681115).  Saving model ...
[Epoch 02/20], Time=16.72s, Train Loss=0.4705, Val Loss=0.4571, Val F1=0.6848, Test Loss=0.4732, Test F1=0.6760
Validation loss decreased (-0.681115 --> -0.684800).  Saving model ...
[Epoch 03/20], Time=16.79s, Train Loss=0.4613, Val Loss=0.4575, Val F1=0.6893, Test Loss=0.4732, Test F1=0.6760
Validation loss decreased (-0.684800 --> -0.689320).  Saving model ...
[Epoch 04/20], Time=17.70s, Train Loss=0.4561, Val Loss=0.4566, Val F1=0.6822, Test Loss=0.4691, Test F1=0.6743
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=18.80s, Train Loss=0.4509, Val Loss=0.4516, Val F1=0.6852, Test Loss=0.4646, Test F1=0.6937
EarlyStopping counter: 2 out of 5
[Epoch 06/20], Time=18.59s, Train Loss=0.4444, Val Loss=0.4552, Val F1=0.6857, Test Loss=0.4706, Test F1=0.6964
EarlyStopping counter: 3 out of 5
[Epoch 07/20], Time=18.73s, Train Loss=0.4463, Val Loss=0.4609, Val F1=0.6782, Test Loss=0.4734, Test F1=0.6756
EarlyStopping counter: 4 out of 5
[Epoch 08/20], Time=18.69s, Train Loss=0.4387, Val Loss=0.4450, Val F1=0.6868, Test Loss=0.4598, Test F1=0.6974
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_13_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_13_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7986906710310966
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_13_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:32:58,4,13,0.6893,0.8289,0.6783,0.7007,64,0.000497,4,4,2,4,0.110623,8,5,0.42,0.35,0.7061,5,0.672,0.8245,0.6387,0.709,0.0173,False,OK

[I 2026-07-08 18:32:58,427] Trial 13 finished with value: 0.6893203883495146 and parameters: {'lr': 0.0004966862745708952, 'd_model': 64, 'd_ff': 4, 'e_layers': 4, 'top_k': 2, 'dropout': 0.11062283314083585, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_14     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00010621265358942143     --e_layers 2     --d_model 4     --d_ff 128     --top_k 2     --num_kernels 4     --dropout 0.2535009597738638     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 4
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2535009597738638
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00010621265358942143
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_14
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_14_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=12.33s, Train Loss=0.6832, Val Loss=0.6044, Val F1=0.5479, Test Loss=0.5995, Test F1=0.5667
Validation loss decreased (inf --> -0.547879).  Saving model ...
[Epoch 02/20], Time=11.38s, Train Loss=0.5987, Val Loss=0.5391, Val F1=0.6136, Test Loss=0.5334, Test F1=0.6329
Validation loss decreased (-0.547879 --> -0.613636).  Saving model ...
[Epoch 03/20], Time=11.17s, Train Loss=0.5609, Val Loss=0.5176, Val F1=0.6188, Test Loss=0.5144, Test F1=0.6462
Validation loss decreased (-0.613636 --> -0.618803).  Saving model ...
[Epoch 04/20], Time=11.07s, Train Loss=0.5439, Val Loss=0.5062, Val F1=0.6329, Test Loss=0.5057, Test F1=0.6430
Validation loss decreased (-0.618803 --> -0.632867).  Saving model ...
[Epoch 05/20], Time=11.13s, Train Loss=0.5363, Val Loss=0.5007, Val F1=0.6433, Test Loss=0.5042, Test F1=0.6430
Validation loss decreased (-0.632867 --> -0.643333).  Saving model ...
[Epoch 06/20], Time=11.36s, Train Loss=0.5245, Val Loss=0.4933, Val F1=0.6460, Test Loss=0.4983, Test F1=0.6527
Validation loss decreased (-0.643333 --> -0.646048).  Saving model ...
[Epoch 07/20], Time=11.62s, Train Loss=0.5148, Val Loss=0.4883, Val F1=0.6476, Test Loss=0.4932, Test F1=0.6574
Validation loss decreased (-0.646048 --> -0.647564).  Saving model ...
[Epoch 08/20], Time=11.57s, Train Loss=0.5177, Val Loss=0.4882, Val F1=0.6600, Test Loss=0.4942, Test F1=0.6629
Validation loss decreased (-0.647564 --> -0.660000).  Saving model ...
[Epoch 09/20], Time=11.30s, Train Loss=0.5134, Val Loss=0.4846, Val F1=0.6622, Test Loss=0.4920, Test F1=0.6643
Validation loss decreased (-0.660000 --> -0.662162).  Saving model ...
[Epoch 10/20], Time=11.13s, Train Loss=0.5026, Val Loss=0.4796, Val F1=0.6633, Test Loss=0.4899, Test F1=0.6597
Validation loss decreased (-0.662162 --> -0.663333).  Saving model ...
[Epoch 11/20], Time=10.93s, Train Loss=0.5034, Val Loss=0.4763, Val F1=0.6746, Test Loss=0.4860, Test F1=0.6621
Validation loss decreased (-0.663333 --> -0.674617).  Saving model ...
[Epoch 12/20], Time=10.71s, Train Loss=0.5010, Val Loss=0.4767, Val F1=0.6724, Test Loss=0.4855, Test F1=0.6620
EarlyStopping counter: 1 out of 5
[Epoch 13/20], Time=10.75s, Train Loss=0.4999, Val Loss=0.4722, Val F1=0.6746, Test Loss=0.4824, Test F1=0.6635
Validation loss decreased (-0.674617 --> -0.674617).  Saving model ...
[Epoch 14/20], Time=11.02s, Train Loss=0.4937, Val Loss=0.4731, Val F1=0.6747, Test Loss=0.4828, Test F1=0.6659
Validation loss decreased (-0.674617 --> -0.674658).  Saving model ...
[Epoch 15/20], Time=10.81s, Train Loss=0.4950, Val Loss=0.4722, Val F1=0.6746, Test Loss=0.4810, Test F1=0.6659
EarlyStopping counter: 1 out of 5
[Epoch 16/20], Time=10.87s, Train Loss=0.4992, Val Loss=0.4728, Val F1=0.6711, Test Loss=0.4813, Test F1=0.6675
EarlyStopping counter: 2 out of 5
[Epoch 17/20], Time=10.82s, Train Loss=0.4939, Val Loss=0.4722, Val F1=0.6689, Test Loss=0.4805, Test F1=0.6675
EarlyStopping counter: 3 out of 5
[Epoch 18/20], Time=10.64s, Train Loss=0.4905, Val Loss=0.4740, Val F1=0.6790, Test Loss=0.4873, Test F1=0.6683
Validation loss decreased (-0.674658 --> -0.679012).  Saving model ...
[Epoch 19/20], Time=10.58s, Train Loss=0.4900, Val Loss=0.4729, Val F1=0.6701, Test Loss=0.4814, Test F1=0.6675
EarlyStopping counter: 1 out of 5
[Epoch 20/20], Time=10.66s, Train Loss=0.4845, Val Loss=0.4702, Val F1=0.6740, Test Loss=0.4794, Test F1=0.6659
EarlyStopping counter: 2 out of 5
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_14_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_14_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7815057283142389
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_14_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:37:34,4,14,0.679,0.8167,0.7006,0.6587,4,0.000106,128,2,2,4,0.253501,8,5,0.27,0.26,0.7061,5,0.6617,0.8161,0.6768,0.6472,0.0173,False,OK

[I 2026-07-08 18:37:34,157] Trial 14 finished with value: 0.6790123456790124 and parameters: {'lr': 0.00010621265358942143, 'd_model': 4, 'd_ff': 128, 'e_layers': 2, 'top_k': 2, 'dropout': 0.2535009597738638, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_15     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0008371430472490793     --e_layers 2     --d_model 48     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.1740023198182718     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.1740023198182718
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0008371430472490793
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_15
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_15_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=15.62s, Train Loss=0.5247, Val Loss=0.4637, Val F1=0.6828, Test Loss=0.4767, Test F1=0.6885
Validation loss decreased (inf --> -0.682842).  Saving model ...
[Epoch 02/20], Time=14.36s, Train Loss=0.4715, Val Loss=0.4543, Val F1=0.6766, Test Loss=0.4632, Test F1=0.6836
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=14.40s, Train Loss=0.4630, Val Loss=0.4603, Val F1=0.6817, Test Loss=0.4686, Test F1=0.6907
EarlyStopping counter: 2 out of 5
[Epoch 04/20], Time=14.42s, Train Loss=0.4580, Val Loss=0.4461, Val F1=0.6957, Test Loss=0.4665, Test F1=0.6939
Validation loss decreased (-0.682842 --> -0.695652).  Saving model ...
[Epoch 05/20], Time=14.64s, Train Loss=0.4557, Val Loss=0.4461, Val F1=0.6870, Test Loss=0.4637, Test F1=0.6777
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=14.58s, Train Loss=0.4475, Val Loss=0.4520, Val F1=0.6892, Test Loss=0.4589, Test F1=0.6999
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=14.67s, Train Loss=0.4421, Val Loss=0.4491, Val F1=0.7057, Test Loss=0.4828, Test F1=0.6824
Validation loss decreased (-0.695652 --> -0.705691).  Saving model ...
[Epoch 08/20], Time=14.71s, Train Loss=0.4424, Val Loss=0.4429, Val F1=0.6923, Test Loss=0.4557, Test F1=0.7060
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=14.60s, Train Loss=0.4368, Val Loss=0.4462, Val F1=0.6961, Test Loss=0.4574, Test F1=0.7000
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=14.53s, Train Loss=0.4331, Val Loss=0.4583, Val F1=0.6771, Test Loss=0.4717, Test F1=0.6924
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=14.44s, Train Loss=0.4322, Val Loss=0.4591, Val F1=0.6855, Test Loss=0.4744, Test F1=0.6892
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=14.73s, Train Loss=0.4266, Val Loss=0.4421, Val F1=0.6978, Test Loss=0.4597, Test F1=0.6915
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_15_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_15_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7945990180032734
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_15_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:41:26,4,15,0.7057,0.8396,0.6911,0.7209,48,0.000837,128,2,2,6,0.174002,8,5,0.49,0.39,0.7061,5,0.6736,0.8241,0.659,0.6888,0.0321,False,OK

[I 2026-07-08 18:41:26,285] Trial 15 finished with value: 0.7056910569105691 and parameters: {'lr': 0.0008371430472490793, 'd_model': 48, 'd_ff': 128, 'e_layers': 2, 'top_k': 2, 'dropout': 0.1740023198182718, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_16     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 8     --train_epochs 20     --learning_rate 0.0015749096016459503     --e_layers 3     --d_model 48     --d_ff 256     --top_k 2     --num_kernels 6     --dropout 0.1749909444145939     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 256
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.1749909444145939
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0015749096016459503
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_16
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_16_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=26.39s, Train Loss=0.5076, Val Loss=0.4526, Val F1=0.6874, Test Loss=0.4779, Test F1=0.6747
Validation loss decreased (inf --> -0.687403).  Saving model ...
[Epoch 02/20], Time=25.33s, Train Loss=0.4825, Val Loss=0.4505, Val F1=0.6815, Test Loss=0.4809, Test F1=0.6728
EarlyStopping counter: 1 out of 4
[Epoch 03/20], Time=25.59s, Train Loss=0.4834, Val Loss=0.4601, Val F1=0.6743, Test Loss=0.4778, Test F1=0.6684
EarlyStopping counter: 2 out of 4
[Epoch 04/20], Time=25.62s, Train Loss=0.4774, Val Loss=0.4564, Val F1=0.6854, Test Loss=0.4849, Test F1=0.6769
EarlyStopping counter: 3 out of 4
[Epoch 05/20], Time=25.10s, Train Loss=0.4779, Val Loss=0.5167, Val F1=0.6613, Test Loss=0.5161, Test F1=0.6717
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_16_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_16_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7937806873977087
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_16_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:44:38,4,16,0.6874,0.8303,0.7038,0.6717,48,0.001575,256,3,2,6,0.174991,8,4,0.39,0.35,0.7061,5,0.6675,0.819,0.6692,0.6658,0.0199,False,OK

[I 2026-07-08 18:44:38,445] Trial 16 finished with value: 0.687402799377916 and parameters: {'lr': 0.0015749096016459503, 'd_model': 48, 'd_ff': 256, 'e_layers': 3, 'top_k': 2, 'dropout': 0.1749909444145939, 'batch_size': 8, 'patience': 4, 'num_kernels': 6}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_17     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00025276282263456796     --e_layers 3     --d_model 48     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.15359393993152862     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.15359393993152862
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00025276282263456796
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_17
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_17_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=21.44s, Train Loss=0.5299, Val Loss=0.4588, Val F1=0.6751, Test Loss=0.4720, Test F1=0.6760
Validation loss decreased (inf --> -0.675079).  Saving model ...
[Epoch 02/20], Time=20.39s, Train Loss=0.4812, Val Loss=0.4625, Val F1=0.6879, Test Loss=0.4787, Test F1=0.6846
Validation loss decreased (-0.675079 --> -0.687898).  Saving model ...
[Epoch 03/20], Time=20.51s, Train Loss=0.4663, Val Loss=0.4545, Val F1=0.6815, Test Loss=0.4724, Test F1=0.6700
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=20.49s, Train Loss=0.4592, Val Loss=0.4602, Val F1=0.6884, Test Loss=0.4791, Test F1=0.6888
Validation loss decreased (-0.687898 --> -0.688372).  Saving model ...
[Epoch 05/20], Time=20.49s, Train Loss=0.4539, Val Loss=0.4589, Val F1=0.6806, Test Loss=0.4725, Test F1=0.6841
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=20.42s, Train Loss=0.4549, Val Loss=0.4584, Val F1=0.6878, Test Loss=0.4803, Test F1=0.6906
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=20.26s, Train Loss=0.4443, Val Loss=0.4435, Val F1=0.6989, Test Loss=0.4571, Test F1=0.6940
Validation loss decreased (-0.688372 --> -0.698873).  Saving model ...
[Epoch 08/20], Time=20.44s, Train Loss=0.4412, Val Loss=0.4554, Val F1=0.6741, Test Loss=0.4663, Test F1=0.6858
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=20.60s, Train Loss=0.4392, Val Loss=0.4478, Val F1=0.6860, Test Loss=0.4574, Test F1=0.7007
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=20.69s, Train Loss=0.4361, Val Loss=0.4394, Val F1=0.6910, Test Loss=0.4521, Test F1=0.7040
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=20.62s, Train Loss=0.4344, Val Loss=0.4433, Val F1=0.7016, Test Loss=0.4593, Test F1=0.6979
Validation loss decreased (-0.698873 --> -0.701571).  Saving model ...
[Epoch 12/20], Time=20.14s, Train Loss=0.4307, Val Loss=0.4427, Val F1=0.6997, Test Loss=0.4589, Test F1=0.6987
EarlyStopping counter: 1 out of 5
[Epoch 13/20], Time=19.83s, Train Loss=0.4264, Val Loss=0.4444, Val F1=0.6969, Test Loss=0.4711, Test F1=0.6850
EarlyStopping counter: 2 out of 5
[Epoch 14/20], Time=20.10s, Train Loss=0.4244, Val Loss=0.4535, Val F1=0.6944, Test Loss=0.4750, Test F1=0.6969
EarlyStopping counter: 3 out of 5
[Epoch 15/20], Time=20.15s, Train Loss=0.4223, Val Loss=0.4421, Val F1=0.6898, Test Loss=0.4606, Test F1=0.6915
EarlyStopping counter: 4 out of 5
[Epoch 16/20], Time=20.05s, Train Loss=0.4209, Val Loss=0.4470, Val F1=0.7045, Test Loss=0.4698, Test F1=0.6967
Validation loss decreased (-0.701571 --> -0.704545).  Saving model ...
[Epoch 17/20], Time=20.12s, Train Loss=0.4131, Val Loss=0.4443, Val F1=0.6894, Test Loss=0.4734, Test F1=0.6913
EarlyStopping counter: 1 out of 5
[Epoch 18/20], Time=20.15s, Train Loss=0.4129, Val Loss=0.4408, Val F1=0.6953, Test Loss=0.4744, Test F1=0.6803
EarlyStopping counter: 2 out of 5
[Epoch 19/20], Time=20.13s, Train Loss=0.4104, Val Loss=0.4443, Val F1=0.6939, Test Loss=0.4729, Test F1=0.6807
EarlyStopping counter: 3 out of 5
[Epoch 20/20], Time=20.48s, Train Loss=0.4054, Val Loss=0.4443, Val F1=0.6963, Test Loss=0.4872, Test F1=0.6812
EarlyStopping counter: 4 out of 5
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_17_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_17_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.806873977086743
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_17_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:52:25,4,17,0.7045,0.8365,0.6911,0.7185,48,0.000253,128,3,2,6,0.153594,8,5,0.43,0.36,0.7061,5,0.6897,0.8279,0.6616,0.7202,0.0149,False,OK

[I 2026-07-08 18:52:25,519] Trial 17 finished with value: 0.7045454545454546 and parameters: {'lr': 0.00025276282263456796, 'd_model': 48, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.15359393993152862, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_18     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.001219772741603871     --e_layers 2     --d_model 256     --d_ff 128     --top_k 2     --num_kernels 4     --dropout 0.21771766613545987     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.21771766613545987
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.001219772741603871
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_18
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_18_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=12.51s, Train Loss=0.5129, Val Loss=0.5316, Val F1=0.6265, Test Loss=0.5358, Test F1=0.6724
Validation loss decreased (inf --> -0.626474).  Saving model ...
[Epoch 02/20], Time=11.60s, Train Loss=0.4891, Val Loss=0.4885, Val F1=0.6585, Test Loss=0.4918, Test F1=0.6783
Validation loss decreased (-0.626474 --> -0.658537).  Saving model ...
[Epoch 03/20], Time=11.76s, Train Loss=0.4923, Val Loss=0.4777, Val F1=0.6607, Test Loss=0.4805, Test F1=0.6723
Validation loss decreased (-0.658537 --> -0.660688).  Saving model ...
[Epoch 04/20], Time=11.91s, Train Loss=0.4903, Val Loss=0.4748, Val F1=0.6782, Test Loss=0.4920, Test F1=0.6777
Validation loss decreased (-0.660688 --> -0.678179).  Saving model ...
[Epoch 05/20], Time=11.76s, Train Loss=0.4930, Val Loss=0.4645, Val F1=0.6882, Test Loss=0.4774, Test F1=0.6853
Validation loss decreased (-0.678179 --> -0.688172).  Saving model ...
[Epoch 06/20], Time=11.58s, Train Loss=0.4828, Val Loss=0.4764, Val F1=0.6817, Test Loss=0.4944, Test F1=0.6806
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=11.43s, Train Loss=0.4705, Val Loss=0.4974, Val F1=0.6792, Test Loss=0.4913, Test F1=0.6871
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=11.43s, Train Loss=0.4622, Val Loss=0.4707, Val F1=0.6838, Test Loss=0.4910, Test F1=0.6923
EarlyStopping counter: 3 out of 5
[Epoch 09/20], Time=11.25s, Train Loss=0.4718, Val Loss=0.5250, Val F1=0.6836, Test Loss=0.5434, Test F1=0.6842
EarlyStopping counter: 4 out of 5
[Epoch 10/20], Time=11.63s, Train Loss=0.4626, Val Loss=0.4583, Val F1=0.6902, Test Loss=0.4693, Test F1=0.6904
Validation loss decreased (-0.688172 --> -0.690209).  Saving model ...
[Epoch 11/20], Time=11.69s, Train Loss=0.4507, Val Loss=0.4804, Val F1=0.6736, Test Loss=0.4866, Test F1=0.6832
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=11.48s, Train Loss=0.4416, Val Loss=0.4619, Val F1=0.6875, Test Loss=0.4706, Test F1=0.6968
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=11.61s, Train Loss=0.4431, Val Loss=0.4537, Val F1=0.6863, Test Loss=0.4685, Test F1=0.6792
EarlyStopping counter: 3 out of 5
[Epoch 14/20], Time=11.75s, Train Loss=0.4333, Val Loss=0.4832, Val F1=0.6567, Test Loss=0.4933, Test F1=0.6711
EarlyStopping counter: 4 out of 5
[Epoch 15/20], Time=11.79s, Train Loss=0.4316, Val Loss=0.4810, Val F1=0.6811, Test Loss=0.4879, Test F1=0.6889
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_18_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_18_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.795417348608838
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_18_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,18:56:16,4,18,0.6902,0.8303,0.6847,0.6958,256,0.00122,128,2,2,4,0.217718,8,5,0.27,0.22,0.7061,5,0.6829,0.8334,0.6794,0.6864,0.0073,False,OK

[I 2026-07-08 18:56:16,282] Trial 18 finished with value: 0.6902086677367576 and parameters: {'lr': 0.001219772741603871, 'd_model': 256, 'd_ff': 128, 'e_layers': 2, 'top_k': 2, 'dropout': 0.21771766613545987, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 5 with value: 0.7060755336617406.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_19     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0006185946884864982     --e_layers 2     --d_model 256     --d_ff 64     --top_k 2     --num_kernels 6     --dropout 0.04736331165800667     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.04736331165800667
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0006185946884864982
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_19
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_19_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=18.44s, Train Loss=0.5035, Val Loss=0.4876, Val F1=0.6787, Test Loss=0.4965, Test F1=0.6847
Validation loss decreased (inf --> -0.678748).  Saving model ...
[Epoch 02/20], Time=17.41s, Train Loss=0.4729, Val Loss=0.4560, Val F1=0.6791, Test Loss=0.4703, Test F1=0.6979
Validation loss decreased (-0.678748 --> -0.679128).  Saving model ...
[Epoch 03/20], Time=17.33s, Train Loss=0.4634, Val Loss=0.4749, Val F1=0.6793, Test Loss=0.4908, Test F1=0.6651
Validation loss decreased (-0.679128 --> -0.679310).  Saving model ...
[Epoch 04/20], Time=17.23s, Train Loss=0.4540, Val Loss=0.4477, Val F1=0.6997, Test Loss=0.4632, Test F1=0.6908
Validation loss decreased (-0.679310 --> -0.699690).  Saving model ...
[Epoch 05/20], Time=17.28s, Train Loss=0.4500, Val Loss=0.5579, Val F1=0.6160, Test Loss=0.5914, Test F1=0.6014
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=17.38s, Train Loss=0.4469, Val Loss=0.4502, Val F1=0.6923, Test Loss=0.4608, Test F1=0.7059
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=17.26s, Train Loss=0.4371, Val Loss=0.5068, Val F1=0.6895, Test Loss=0.5316, Test F1=0.6834
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=17.36s, Train Loss=0.4372, Val Loss=0.4735, Val F1=0.7023, Test Loss=0.4860, Test F1=0.7094
Validation loss decreased (-0.699690 --> -0.702265).  Saving model ...
[Epoch 09/20], Time=17.30s, Train Loss=0.4231, Val Loss=0.4748, Val F1=0.6922, Test Loss=0.4791, Test F1=0.6937
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=17.47s, Train Loss=0.4164, Val Loss=0.4852, Val F1=0.6831, Test Loss=0.4937, Test F1=0.6910
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=17.37s, Train Loss=0.4062, Val Loss=0.4926, Val F1=0.6843, Test Loss=0.5008, Test F1=0.6541
EarlyStopping counter: 3 out of 5
[Epoch 12/20], Time=17.47s, Train Loss=0.4017, Val Loss=0.4760, Val F1=0.7065, Test Loss=0.4933, Test F1=0.6773
Validation loss decreased (-0.702265 --> -0.706468).  Saving model ...
[Epoch 13/20], Time=17.47s, Train Loss=0.3981, Val Loss=0.4938, Val F1=0.6798, Test Loss=0.5144, Test F1=0.6876
EarlyStopping counter: 1 out of 5
[Epoch 14/20], Time=17.54s, Train Loss=0.3945, Val Loss=0.4876, Val F1=0.6875, Test Loss=0.5185, Test F1=0.6785
EarlyStopping counter: 2 out of 5
[Epoch 15/20], Time=17.55s, Train Loss=0.3823, Val Loss=0.4933, Val F1=0.6756, Test Loss=0.5030, Test F1=0.6735
EarlyStopping counter: 3 out of 5
[Epoch 16/20], Time=17.65s, Train Loss=0.3696, Val Loss=0.5343, Val F1=0.6809, Test Loss=0.5413, Test F1=0.6711
EarlyStopping counter: 4 out of 5
[Epoch 17/20], Time=17.41s, Train Loss=0.3642, Val Loss=0.5089, Val F1=0.6766, Test Loss=0.5210, Test F1=0.6588
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_19_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_19_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7995090016366612
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_19_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:02:12,4,19,0.7065,0.833,0.6783,0.737,256,0.000619,64,2,2,6,0.047363,8,5,0.54,0.51,0.7065,19,0.6711,0.8205,0.6361,0.7102,0.0353,False,OK

[I 2026-07-08 19:02:12,871] Trial 19 finished with value: 0.7064676616915423 and parameters: {'lr': 0.0006185946884864982, 'd_model': 256, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.04736331165800667, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_20     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0004102582021481928     --e_layers 2     --d_model 256     --d_ff 64     --top_k 2     --num_kernels 6     --dropout 0.059664904815310546     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.059664904815310546
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0004102582021481928
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_20
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_20_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=18.37s, Train Loss=0.5056, Val Loss=0.4801, Val F1=0.6800, Test Loss=0.4903, Test F1=0.6830
Validation loss decreased (inf --> -0.680000).  Saving model ...
[Epoch 02/20], Time=17.31s, Train Loss=0.4700, Val Loss=0.4564, Val F1=0.6839, Test Loss=0.4680, Test F1=0.6983
Validation loss decreased (-0.680000 --> -0.683871).  Saving model ...
[Epoch 03/20], Time=17.24s, Train Loss=0.4575, Val Loss=0.4666, Val F1=0.6839, Test Loss=0.4822, Test F1=0.6689
Validation loss decreased (-0.683871 --> -0.683938).  Saving model ...
[Epoch 04/20], Time=17.13s, Train Loss=0.4485, Val Loss=0.4507, Val F1=0.6946, Test Loss=0.4627, Test F1=0.6952
Validation loss decreased (-0.683938 --> -0.694574).  Saving model ...
[Epoch 05/20], Time=17.26s, Train Loss=0.4447, Val Loss=0.5054, Val F1=0.6425, Test Loss=0.5362, Test F1=0.6132
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=17.15s, Train Loss=0.4396, Val Loss=0.4510, Val F1=0.6948, Test Loss=0.4633, Test F1=0.7056
Validation loss decreased (-0.694574 --> -0.694805).  Saving model ...
[Epoch 07/20], Time=17.15s, Train Loss=0.4300, Val Loss=0.4962, Val F1=0.6897, Test Loss=0.5208, Test F1=0.6796
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=17.26s, Train Loss=0.4299, Val Loss=0.4682, Val F1=0.7018, Test Loss=0.4764, Test F1=0.7111
Validation loss decreased (-0.694805 --> -0.701812).  Saving model ...
[Epoch 09/20], Time=17.12s, Train Loss=0.4162, Val Loss=0.4900, Val F1=0.6889, Test Loss=0.4894, Test F1=0.6821
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=17.13s, Train Loss=0.4081, Val Loss=0.4965, Val F1=0.6777, Test Loss=0.4919, Test F1=0.6841
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=17.40s, Train Loss=0.4031, Val Loss=0.5009, Val F1=0.6807, Test Loss=0.5269, Test F1=0.6513
EarlyStopping counter: 3 out of 5
[Epoch 12/20], Time=17.58s, Train Loss=0.3952, Val Loss=0.4715, Val F1=0.6987, Test Loss=0.4903, Test F1=0.6783
EarlyStopping counter: 4 out of 5
[Epoch 13/20], Time=17.30s, Train Loss=0.3892, Val Loss=0.4851, Val F1=0.6839, Test Loss=0.5161, Test F1=0.6701
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_20_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_20_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.820785597381342
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_20_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:06:58,4,20,0.7018,0.8379,0.6783,0.727,256,0.00041,64,2,2,6,0.059665,8,5,0.49,0.49,0.7065,19,0.7111,0.8394,0.6794,0.7458,-0.0092,False,OK

[I 2026-07-08 19:06:58,390] Trial 20 finished with value: 0.7018121911037891 and parameters: {'lr': 0.0004102582021481928, 'd_model': 256, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.059664904815310546, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_21     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0014934165243026     --e_layers 2     --d_model 48     --d_ff 512     --top_k 2     --num_kernels 4     --dropout 0.10999936326185526     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.10999936326185526
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0014934165243026
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_21
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_21_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.85s, Train Loss=0.5055, Val Loss=0.4859, Val F1=0.6644, Test Loss=0.4928, Test F1=0.6707
Validation loss decreased (inf --> -0.664441).  Saving model ...
[Epoch 02/20], Time=6.62s, Train Loss=0.4721, Val Loss=0.4558, Val F1=0.6751, Test Loss=0.4738, Test F1=0.6715
Validation loss decreased (-0.664441 --> -0.675119).  Saving model ...
[Epoch 03/20], Time=6.61s, Train Loss=0.4642, Val Loss=0.4662, Val F1=0.6836, Test Loss=0.4851, Test F1=0.6827
Validation loss decreased (-0.675119 --> -0.683636).  Saving model ...
[Epoch 04/20], Time=6.61s, Train Loss=0.4600, Val Loss=0.4469, Val F1=0.6875, Test Loss=0.4604, Test F1=0.7018
Validation loss decreased (-0.683636 --> -0.687500).  Saving model ...
[Epoch 05/20], Time=6.71s, Train Loss=0.4557, Val Loss=0.4818, Val F1=0.6739, Test Loss=0.4952, Test F1=0.6770
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=6.72s, Train Loss=0.4497, Val Loss=0.4477, Val F1=0.6892, Test Loss=0.4712, Test F1=0.6793
Validation loss decreased (-0.687500 --> -0.689211).  Saving model ...
[Epoch 07/20], Time=6.73s, Train Loss=0.4510, Val Loss=0.4438, Val F1=0.6823, Test Loss=0.4600, Test F1=0.6904
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=6.70s, Train Loss=0.4485, Val Loss=0.4406, Val F1=0.6873, Test Loss=0.4638, Test F1=0.6863
EarlyStopping counter: 2 out of 5
[Epoch 09/20], Time=6.68s, Train Loss=0.4449, Val Loss=0.4490, Val F1=0.6867, Test Loss=0.4803, Test F1=0.6801
EarlyStopping counter: 3 out of 5
[Epoch 10/20], Time=6.74s, Train Loss=0.4440, Val Loss=0.4400, Val F1=0.6958, Test Loss=0.4504, Test F1=0.6906
Validation loss decreased (-0.689211 --> -0.695788).  Saving model ...
[Epoch 11/20], Time=6.86s, Train Loss=0.4382, Val Loss=0.4493, Val F1=0.6809, Test Loss=0.4586, Test F1=0.7004
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=6.79s, Train Loss=0.4400, Val Loss=0.4587, Val F1=0.6800, Test Loss=0.4711, Test F1=0.6788
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=6.85s, Train Loss=0.4372, Val Loss=0.4448, Val F1=0.6838, Test Loss=0.4559, Test F1=0.6926
EarlyStopping counter: 3 out of 5
[Epoch 14/20], Time=6.79s, Train Loss=0.4261, Val Loss=0.4521, Val F1=0.6913, Test Loss=0.4614, Test F1=0.6856
EarlyStopping counter: 4 out of 5
[Epoch 15/20], Time=6.89s, Train Loss=0.4243, Val Loss=0.4527, Val F1=0.6763, Test Loss=0.4698, Test F1=0.6763
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_21_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_21_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8036006546644845
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_21_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:09:32,4,21,0.6958,0.8377,0.7102,0.682,48,0.001493,512,2,2,4,0.109999,16,5,0.26,0.24,0.7065,19,0.6835,0.8343,0.6896,0.6775,0.0123,False,OK

[I 2026-07-08 19:09:32,547] Trial 21 finished with value: 0.6957878315132605 and parameters: {'lr': 0.0014934165243026, 'd_model': 48, 'd_ff': 512, 'e_layers': 2, 'top_k': 2, 'dropout': 0.10999936326185526, 'batch_size': 16, 'patience': 5, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_22     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0008341643031076046     --e_layers 2     --d_model 48     --d_ff 512     --top_k 2     --num_kernels 6     --dropout 0.25600415036565993     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.25600415036565993
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0008341643031076046
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_22
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_22_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=26.01s, Train Loss=0.5187, Val Loss=0.4647, Val F1=0.6712, Test Loss=0.4795, Test F1=0.6658
Validation loss decreased (inf --> -0.671186).  Saving model ...
[Epoch 02/20], Time=24.52s, Train Loss=0.4752, Val Loss=0.4817, Val F1=0.6709, Test Loss=0.4892, Test F1=0.6842
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=24.41s, Train Loss=0.4785, Val Loss=0.4593, Val F1=0.6767, Test Loss=0.4705, Test F1=0.6806
Validation loss decreased (-0.671186 --> -0.676667).  Saving model ...
[Epoch 04/20], Time=24.32s, Train Loss=0.4741, Val Loss=0.4584, Val F1=0.6852, Test Loss=0.4681, Test F1=0.6967
Validation loss decreased (-0.676667 --> -0.685185).  Saving model ...
[Epoch 05/20], Time=24.59s, Train Loss=0.4717, Val Loss=0.4509, Val F1=0.6815, Test Loss=0.4661, Test F1=0.6641
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=24.61s, Train Loss=0.4584, Val Loss=0.4500, Val F1=0.6837, Test Loss=0.4667, Test F1=0.6833
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=24.71s, Train Loss=0.4602, Val Loss=0.4717, Val F1=0.6799, Test Loss=0.4829, Test F1=0.6903
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=24.69s, Train Loss=0.4565, Val Loss=0.4526, Val F1=0.6909, Test Loss=0.4565, Test F1=0.6926
Validation loss decreased (-0.685185 --> -0.690852).  Saving model ...
[Epoch 09/20], Time=24.47s, Train Loss=0.4522, Val Loss=0.4705, Val F1=0.6797, Test Loss=0.4743, Test F1=0.6965
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=24.40s, Train Loss=0.4518, Val Loss=0.4370, Val F1=0.6983, Test Loss=0.4595, Test F1=0.6914
Validation loss decreased (-0.690852 --> -0.698305).  Saving model ...
[Epoch 11/20], Time=24.68s, Train Loss=0.4504, Val Loss=0.4431, Val F1=0.6898, Test Loss=0.4574, Test F1=0.6917
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=24.58s, Train Loss=0.4393, Val Loss=0.4500, Val F1=0.6734, Test Loss=0.4739, Test F1=0.6567
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=24.36s, Train Loss=0.4429, Val Loss=0.4479, Val F1=0.6945, Test Loss=0.4668, Test F1=0.6831
EarlyStopping counter: 3 out of 5
[Epoch 14/20], Time=24.51s, Train Loss=0.4349, Val Loss=0.4292, Val F1=0.6978, Test Loss=0.4477, Test F1=0.7036
EarlyStopping counter: 4 out of 5
[Epoch 15/20], Time=24.66s, Train Loss=0.4297, Val Loss=0.4437, Val F1=0.6837, Test Loss=0.4511, Test F1=0.7005
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_22_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_22_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.809328968903437
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_22_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:16:48,4,22,0.6983,0.8408,0.6561,0.7464,48,0.000834,512,2,2,6,0.256004,8,5,0.45,0.37,0.7065,19,0.6777,0.829,0.6234,0.7424,0.0206,False,OK

[I 2026-07-08 19:16:48,819] Trial 22 finished with value: 0.6983050847457627 and parameters: {'lr': 0.0008341643031076046, 'd_model': 48, 'd_ff': 512, 'e_layers': 2, 'top_k': 2, 'dropout': 0.25600415036565993, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_23     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00022846084515249876     --e_layers 4     --d_model 256     --d_ff 16     --top_k 2     --num_kernels 4     --dropout 0.2164954184984004     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2164954184984004
dtwwarp                  : False
e_layers                 : 4
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00022846084515249876
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_23
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_23_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el4_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=20.96s, Train Loss=0.5285, Val Loss=0.4965, Val F1=0.6755, Test Loss=0.5148, Test F1=0.6640
Validation loss decreased (inf --> -0.675497).  Saving model ...
[Epoch 02/20], Time=19.91s, Train Loss=0.4799, Val Loss=0.4769, Val F1=0.6838, Test Loss=0.4973, Test F1=0.6850
Validation loss decreased (-0.675497 --> -0.683761).  Saving model ...
[Epoch 03/20], Time=19.75s, Train Loss=0.4713, Val Loss=0.4896, Val F1=0.6636, Test Loss=0.4956, Test F1=0.6768
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=19.69s, Train Loss=0.4681, Val Loss=0.4543, Val F1=0.6830, Test Loss=0.4742, Test F1=0.6886
EarlyStopping counter: 2 out of 5
[Epoch 05/20], Time=19.71s, Train Loss=0.4583, Val Loss=0.4865, Val F1=0.6606, Test Loss=0.5019, Test F1=0.6781
EarlyStopping counter: 3 out of 5
[Epoch 06/20], Time=19.53s, Train Loss=0.4535, Val Loss=0.4605, Val F1=0.6912, Test Loss=0.4770, Test F1=0.6948
Validation loss decreased (-0.683761 --> -0.691152).  Saving model ...
[Epoch 07/20], Time=19.67s, Train Loss=0.4519, Val Loss=0.4599, Val F1=0.6970, Test Loss=0.4786, Test F1=0.6946
Validation loss decreased (-0.691152 --> -0.696970).  Saving model ...
[Epoch 08/20], Time=19.68s, Train Loss=0.4464, Val Loss=0.4599, Val F1=0.6997, Test Loss=0.4902, Test F1=0.6929
Validation loss decreased (-0.696970 --> -0.699690).  Saving model ...
[Epoch 09/20], Time=19.64s, Train Loss=0.4388, Val Loss=0.4380, Val F1=0.7006, Test Loss=0.4651, Test F1=0.6880
Validation loss decreased (-0.699690 --> -0.700599).  Saving model ...
[Epoch 10/20], Time=19.67s, Train Loss=0.4325, Val Loss=0.4577, Val F1=0.6931, Test Loss=0.4731, Test F1=0.6881
EarlyStopping counter: 1 out of 5
[Epoch 11/20], Time=19.84s, Train Loss=0.4341, Val Loss=0.4623, Val F1=0.6945, Test Loss=0.4860, Test F1=0.6814
EarlyStopping counter: 2 out of 5
[Epoch 12/20], Time=19.72s, Train Loss=0.4273, Val Loss=0.4647, Val F1=0.6957, Test Loss=0.4758, Test F1=0.7054
EarlyStopping counter: 3 out of 5
[Epoch 13/20], Time=19.95s, Train Loss=0.4266, Val Loss=0.4629, Val F1=0.6970, Test Loss=0.4780, Test F1=0.6943
EarlyStopping counter: 4 out of 5
[Epoch 14/20], Time=19.57s, Train Loss=0.4188, Val Loss=0.4567, Val F1=0.6895, Test Loss=0.4619, Test F1=0.6937
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_23_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el4_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_23_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el4_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8126022913256956
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_23_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el4_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:22:24,4,23,0.7006,0.8449,0.7452,0.661,256,0.000228,16,4,2,4,0.216495,8,5,0.31,0.37,0.7065,19,0.6839,0.8314,0.7074,0.6619,0.0167,False,OK

[I 2026-07-08 19:22:24,639] Trial 23 finished with value: 0.7005988023952096 and parameters: {'lr': 0.00022846084515249876, 'd_model': 256, 'd_ff': 16, 'e_layers': 4, 'top_k': 2, 'dropout': 0.2164954184984004, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_24     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 8     --train_epochs 20     --learning_rate 0.0003618415435601804     --e_layers 3     --d_model 64     --d_ff 128     --top_k 2     --num_kernels 4     --dropout 0.19653075643493065     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.19653075643493065
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0003618415435601804
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_24
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_24_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=16.66s, Train Loss=0.5032, Val Loss=0.4589, Val F1=0.6749, Test Loss=0.4685, Test F1=0.6773
Validation loss decreased (inf --> -0.674923).  Saving model ...
[Epoch 02/20], Time=15.99s, Train Loss=0.4722, Val Loss=0.4564, Val F1=0.6796, Test Loss=0.4718, Test F1=0.6866
Validation loss decreased (-0.674923 --> -0.679612).  Saving model ...
[Epoch 03/20], Time=16.06s, Train Loss=0.4606, Val Loss=0.4601, Val F1=0.6826, Test Loss=0.4725, Test F1=0.6800
Validation loss decreased (-0.679612 --> -0.682616).  Saving model ...
[Epoch 04/20], Time=14.68s, Train Loss=0.4568, Val Loss=0.4529, Val F1=0.6753, Test Loss=0.4652, Test F1=0.6876
EarlyStopping counter: 1 out of 4
[Epoch 05/20], Time=14.27s, Train Loss=0.4503, Val Loss=0.4490, Val F1=0.6812, Test Loss=0.4608, Test F1=0.6942
EarlyStopping counter: 2 out of 4
[Epoch 06/20], Time=14.14s, Train Loss=0.4436, Val Loss=0.4530, Val F1=0.6826, Test Loss=0.4739, Test F1=0.6608
Validation loss decreased (-0.682616 --> -0.682616).  Saving model ...
[Epoch 07/20], Time=14.22s, Train Loss=0.4400, Val Loss=0.4363, Val F1=0.7030, Test Loss=0.4602, Test F1=0.7017
Validation loss decreased (-0.682616 --> -0.703050).  Saving model ...
[Epoch 08/20], Time=14.18s, Train Loss=0.4404, Val Loss=0.4412, Val F1=0.6937, Test Loss=0.4576, Test F1=0.7035
EarlyStopping counter: 1 out of 4
[Epoch 09/20], Time=14.05s, Train Loss=0.4350, Val Loss=0.4481, Val F1=0.6924, Test Loss=0.4617, Test F1=0.6824
EarlyStopping counter: 2 out of 4
[Epoch 10/20], Time=14.10s, Train Loss=0.4327, Val Loss=0.4472, Val F1=0.6968, Test Loss=0.4649, Test F1=0.6895
EarlyStopping counter: 3 out of 4
[Epoch 11/20], Time=13.95s, Train Loss=0.4284, Val Loss=0.4666, Val F1=0.6754, Test Loss=0.4687, Test F1=0.7008
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_24_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_24_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8076923076923077
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_24_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:26:01,4,24,0.703,0.8432,0.6975,0.7087,64,0.000362,128,3,2,4,0.196531,8,4,0.33,0.34,0.7065,19,0.7016,0.8346,0.6819,0.7224,0.0015,False,OK

[I 2026-07-08 19:26:01,948] Trial 24 finished with value: 0.7030497592295345 and parameters: {'lr': 0.0003618415435601804, 'd_model': 64, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.19653075643493065, 'batch_size': 8, 'patience': 4, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_25     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0012879520922830594     --e_layers 2     --d_model 4     --d_ff 8     --top_k 2     --num_kernels 6     --dropout 0.1227754180371056     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 8
d_layers                 : 1
d_model                  : 4
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.1227754180371056
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0012879520922830594
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_25
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_25_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=12.86s, Train Loss=0.5793, Val Loss=0.4956, Val F1=0.6413, Test Loss=0.4971, Test F1=0.6522
Validation loss decreased (inf --> -0.641322).  Saving model ...
[Epoch 02/20], Time=11.86s, Train Loss=0.5025, Val Loss=0.4701, Val F1=0.6712, Test Loss=0.4780, Test F1=0.6667
Validation loss decreased (-0.641322 --> -0.671186).  Saving model ...
[Epoch 03/20], Time=12.00s, Train Loss=0.4877, Val Loss=0.4662, Val F1=0.6718, Test Loss=0.4775, Test F1=0.6675
Validation loss decreased (-0.671186 --> -0.671756).  Saving model ...
[Epoch 04/20], Time=12.06s, Train Loss=0.4868, Val Loss=0.4633, Val F1=0.6734, Test Loss=0.4731, Test F1=0.6751
Validation loss decreased (-0.671756 --> -0.673435).  Saving model ...
[Epoch 05/20], Time=12.24s, Train Loss=0.4782, Val Loss=0.4650, Val F1=0.6719, Test Loss=0.4750, Test F1=0.6732
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=12.24s, Train Loss=0.4829, Val Loss=0.4618, Val F1=0.6769, Test Loss=0.4736, Test F1=0.6752
Validation loss decreased (-0.673435 --> -0.676876).  Saving model ...
[Epoch 07/20], Time=12.03s, Train Loss=0.4742, Val Loss=0.4646, Val F1=0.6656, Test Loss=0.4767, Test F1=0.6650
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=12.20s, Train Loss=0.4737, Val Loss=0.4669, Val F1=0.6710, Test Loss=0.4796, Test F1=0.6658
EarlyStopping counter: 2 out of 5
[Epoch 09/20], Time=11.88s, Train Loss=0.4703, Val Loss=0.4608, Val F1=0.6687, Test Loss=0.4785, Test F1=0.6750
EarlyStopping counter: 3 out of 5
[Epoch 10/20], Time=12.05s, Train Loss=0.4689, Val Loss=0.4624, Val F1=0.6748, Test Loss=0.4757, Test F1=0.6667
EarlyStopping counter: 4 out of 5
[Epoch 11/20], Time=11.99s, Train Loss=0.4690, Val Loss=0.4570, Val F1=0.6799, Test Loss=0.4739, Test F1=0.6700
Validation loss decreased (-0.676876 --> -0.679878).  Saving model ...
[Epoch 12/20], Time=12.05s, Train Loss=0.4655, Val Loss=0.4618, Val F1=0.6737, Test Loss=0.4811, Test F1=0.6716
EarlyStopping counter: 1 out of 5
[Epoch 13/20], Time=12.15s, Train Loss=0.4627, Val Loss=0.4655, Val F1=0.6708, Test Loss=0.4828, Test F1=0.6759
EarlyStopping counter: 2 out of 5
[Epoch 14/20], Time=11.95s, Train Loss=0.4630, Val Loss=0.4627, Val F1=0.6667, Test Loss=0.4722, Test F1=0.6675
EarlyStopping counter: 3 out of 5
[Epoch 15/20], Time=12.04s, Train Loss=0.4623, Val Loss=0.4588, Val F1=0.6697, Test Loss=0.4739, Test F1=0.6716
EarlyStopping counter: 4 out of 5
[Epoch 16/20], Time=12.11s, Train Loss=0.4596, Val Loss=0.4572, Val F1=0.6751, Test Loss=0.4701, Test F1=0.6773
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_25_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_25_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7880523731587561
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_25_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:30:08,4,25,0.6799,0.8292,0.7102,0.652,4,0.001288,8,2,2,6,0.122775,8,5,0.3,0.29,0.7065,19,0.6692,0.8198,0.6819,0.6569,0.0107,False,OK

[I 2026-07-08 19:30:08,462] Trial 25 finished with value: 0.6798780487804879 and parameters: {'lr': 0.0012879520922830594, 'd_model': 4, 'd_ff': 8, 'e_layers': 2, 'top_k': 2, 'dropout': 0.1227754180371056, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_26     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0016466771159931268     --e_layers 3     --d_model 8     --d_ff 64     --top_k 2     --num_kernels 6     --dropout 0.08835293909769625     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 8
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.08835293909769625
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0016466771159931268
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_26
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_26_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=10.48s, Train Loss=0.5415, Val Loss=0.4681, Val F1=0.6465, Test Loss=0.4808, Test F1=0.6699
Validation loss decreased (inf --> -0.646526).  Saving model ...
[Epoch 02/20], Time=9.27s, Train Loss=0.4836, Val Loss=0.4513, Val F1=0.6750, Test Loss=0.4707, Test F1=0.6800
Validation loss decreased (-0.646526 --> -0.674961).  Saving model ...
[Epoch 03/20], Time=9.33s, Train Loss=0.4731, Val Loss=0.4447, Val F1=0.6779, Test Loss=0.4647, Test F1=0.6775
Validation loss decreased (-0.674961 --> -0.677863).  Saving model ...
[Epoch 04/20], Time=9.34s, Train Loss=0.4627, Val Loss=0.4452, Val F1=0.6831, Test Loss=0.4678, Test F1=0.6851
Validation loss decreased (-0.677863 --> -0.683077).  Saving model ...
[Epoch 05/20], Time=9.44s, Train Loss=0.4561, Val Loss=0.4587, Val F1=0.6763, Test Loss=0.4733, Test F1=0.6974
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=9.33s, Train Loss=0.4547, Val Loss=0.4395, Val F1=0.6883, Test Loss=0.4601, Test F1=0.6958
Validation loss decreased (-0.683077 --> -0.688272).  Saving model ...
[Epoch 07/20], Time=9.41s, Train Loss=0.4552, Val Loss=0.4555, Val F1=0.6708, Test Loss=0.4685, Test F1=0.6878
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=9.45s, Train Loss=0.4546, Val Loss=0.4292, Val F1=0.6988, Test Loss=0.4582, Test F1=0.6927
Validation loss decreased (-0.688272 --> -0.698758).  Saving model ...
[Epoch 09/20], Time=9.40s, Train Loss=0.4426, Val Loss=0.4421, Val F1=0.6911, Test Loss=0.4682, Test F1=0.6865
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=9.52s, Train Loss=0.4409, Val Loss=0.4394, Val F1=0.6930, Test Loss=0.4536, Test F1=0.6997
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=9.49s, Train Loss=0.4425, Val Loss=0.4463, Val F1=0.6806, Test Loss=0.4605, Test F1=0.6923
EarlyStopping counter: 3 out of 5
[Epoch 12/20], Time=9.49s, Train Loss=0.4435, Val Loss=0.4444, Val F1=0.6897, Test Loss=0.4552, Test F1=0.6994
EarlyStopping counter: 4 out of 5
[Epoch 13/20], Time=9.51s, Train Loss=0.4349, Val Loss=0.4332, Val F1=0.6970, Test Loss=0.4599, Test F1=0.6851
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_26_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_26_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7978723404255319
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_26_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:33:03,4,26,0.6988,0.8446,0.7166,0.6818,8,0.001647,64,3,2,6,0.088353,16,5,0.29,0.3,0.7065,19,0.6784,0.8291,0.7328,0.6316,0.0203,False,OK

[I 2026-07-08 19:33:03,968] Trial 26 finished with value: 0.6987577639751553 and parameters: {'lr': 0.0016466771159931268, 'd_model': 8, 'd_ff': 64, 'e_layers': 3, 'top_k': 2, 'dropout': 0.08835293909769625, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_27     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0005737083856223746     --e_layers 3     --d_model 256     --d_ff 512     --top_k 2     --num_kernels 6     --dropout 0.0054965520412460014     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.0054965520412460014
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0005737083856223746
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_27
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_27_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=16.86s, Train Loss=0.5016, Val Loss=0.5694, Val F1=0.6393, Test Loss=0.5760, Test F1=0.6434
Validation loss decreased (inf --> -0.639344).  Saving model ...
[Epoch 02/20], Time=15.71s, Train Loss=0.4765, Val Loss=0.4689, Val F1=0.6689, Test Loss=0.4784, Test F1=0.6701
Validation loss decreased (-0.639344 --> -0.668874).  Saving model ...
[Epoch 03/20], Time=15.78s, Train Loss=0.4732, Val Loss=0.5441, Val F1=0.6745, Test Loss=0.5425, Test F1=0.6815
Validation loss decreased (-0.668874 --> -0.674536).  Saving model ...
[Epoch 04/20], Time=15.76s, Train Loss=0.4662, Val Loss=0.4582, Val F1=0.6743, Test Loss=0.4714, Test F1=0.6649
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=15.73s, Train Loss=0.4598, Val Loss=0.4441, Val F1=0.6959, Test Loss=0.4607, Test F1=0.6789
Validation loss decreased (-0.674536 --> -0.695915).  Saving model ...
[Epoch 06/20], Time=15.76s, Train Loss=0.4494, Val Loss=0.4570, Val F1=0.6914, Test Loss=0.4638, Test F1=0.7029
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=15.66s, Train Loss=0.4559, Val Loss=0.4759, Val F1=0.6678, Test Loss=0.4885, Test F1=0.6834
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=15.71s, Train Loss=0.4348, Val Loss=0.4760, Val F1=0.6903, Test Loss=0.4775, Test F1=0.6967
EarlyStopping counter: 3 out of 5
[Epoch 09/20], Time=15.68s, Train Loss=0.4325, Val Loss=0.4578, Val F1=0.6892, Test Loss=0.4704, Test F1=0.6942
EarlyStopping counter: 4 out of 5
[Epoch 10/20], Time=15.69s, Train Loss=0.4241, Val Loss=0.4590, Val F1=0.6830, Test Loss=0.4838, Test F1=0.6754
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_27_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_27_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8003273322422259
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_27_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:36:45,4,27,0.6959,0.8344,0.7325,0.6628,256,0.000574,512,3,2,6,0.005497,16,5,0.32,0.38,0.7065,19,0.6691,0.8236,0.687,0.6522,0.0268,False,OK

[I 2026-07-08 19:36:45,226] Trial 27 finished with value: 0.6959152798789713 and parameters: {'lr': 0.0005737083856223746, 'd_model': 256, 'd_ff': 512, 'e_layers': 3, 'top_k': 2, 'dropout': 0.0054965520412460014, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_28     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 8     --train_epochs 20     --learning_rate 0.001061015329611695     --e_layers 3     --d_model 16     --d_ff 4     --top_k 2     --num_kernels 3     --dropout 0.09902165156449319     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 4
d_layers                 : 1
d_model                  : 16
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.09902165156449319
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.001061015329611695
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_28
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_28_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=12.95s, Train Loss=0.5292, Val Loss=0.4666, Val F1=0.6609, Test Loss=0.4788, Test F1=0.6620
Validation loss decreased (inf --> -0.660929).  Saving model ...
[Epoch 02/20], Time=11.79s, Train Loss=0.4803, Val Loss=0.4551, Val F1=0.6756, Test Loss=0.4708, Test F1=0.6724
Validation loss decreased (-0.660929 --> -0.675630).  Saving model ...
[Epoch 03/20], Time=11.77s, Train Loss=0.4643, Val Loss=0.4608, Val F1=0.6800, Test Loss=0.4760, Test F1=0.6796
Validation loss decreased (-0.675630 --> -0.680000).  Saving model ...
[Epoch 04/20], Time=11.83s, Train Loss=0.4612, Val Loss=0.4621, Val F1=0.6822, Test Loss=0.4784, Test F1=0.6814
Validation loss decreased (-0.680000 --> -0.682171).  Saving model ...
[Epoch 05/20], Time=11.67s, Train Loss=0.4575, Val Loss=0.4463, Val F1=0.6854, Test Loss=0.4633, Test F1=0.6903
Validation loss decreased (-0.682171 --> -0.685446).  Saving model ...
[Epoch 06/20], Time=11.72s, Train Loss=0.4514, Val Loss=0.4524, Val F1=0.6845, Test Loss=0.4619, Test F1=0.6922
EarlyStopping counter: 1 out of 4
[Epoch 07/20], Time=11.88s, Train Loss=0.4487, Val Loss=0.4435, Val F1=0.6912, Test Loss=0.4616, Test F1=0.6910
Validation loss decreased (-0.685446 --> -0.691244).  Saving model ...
[Epoch 08/20], Time=11.94s, Train Loss=0.4465, Val Loss=0.4530, Val F1=0.6828, Test Loss=0.4636, Test F1=0.6919
EarlyStopping counter: 1 out of 4
[Epoch 09/20], Time=11.72s, Train Loss=0.4472, Val Loss=0.4542, Val F1=0.6852, Test Loss=0.4634, Test F1=0.6888
EarlyStopping counter: 2 out of 4
[Epoch 10/20], Time=11.75s, Train Loss=0.4392, Val Loss=0.4516, Val F1=0.6856, Test Loss=0.4604, Test F1=0.6945
EarlyStopping counter: 3 out of 4
[Epoch 11/20], Time=11.80s, Train Loss=0.4412, Val Loss=0.4521, Val F1=0.6779, Test Loss=0.4694, Test F1=0.6675
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_28_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_28_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8011456628477905
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_28_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:39:48,4,28,0.6912,0.8356,0.7166,0.6677,16,0.001061,4,3,2,3,0.099022,8,4,0.27,0.29,0.7065,19,0.6904,0.829,0.715,0.6675,0.0008,False,OK

[I 2026-07-08 19:39:48,750] Trial 28 finished with value: 0.6912442396313364 and parameters: {'lr': 0.001061015329611695, 'd_model': 16, 'd_ff': 4, 'e_layers': 3, 'top_k': 2, 'dropout': 0.09902165156449319, 'batch_size': 8, 'patience': 4, 'num_kernels': 3}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_29     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00031420692153319316     --e_layers 2     --d_model 4     --d_ff 64     --top_k 2     --num_kernels 3     --dropout 0.003570512370208001     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 4
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.003570512370208001
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00031420692153319316
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_29
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_29_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=9.77s, Train Loss=0.6766, Val Loss=0.5953, Val F1=0.5718, Test Loss=0.5962, Test F1=0.5762
Validation loss decreased (inf --> -0.571762).  Saving model ...
[Epoch 02/20], Time=8.75s, Train Loss=0.5512, Val Loss=0.5057, Val F1=0.6442, Test Loss=0.5073, Test F1=0.6446
Validation loss decreased (-0.571762 --> -0.644231).  Saving model ...
[Epoch 03/20], Time=8.73s, Train Loss=0.4974, Val Loss=0.4723, Val F1=0.6781, Test Loss=0.4797, Test F1=0.6797
Validation loss decreased (-0.644231 --> -0.678072).  Saving model ...
[Epoch 04/20], Time=8.88s, Train Loss=0.4779, Val Loss=0.4662, Val F1=0.6724, Test Loss=0.4704, Test F1=0.6877
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=8.74s, Train Loss=0.4676, Val Loss=0.4633, Val F1=0.6737, Test Loss=0.4720, Test F1=0.6812
EarlyStopping counter: 2 out of 5
[Epoch 06/20], Time=8.70s, Train Loss=0.4612, Val Loss=0.4608, Val F1=0.6729, Test Loss=0.4643, Test F1=0.6885
EarlyStopping counter: 3 out of 5
[Epoch 07/20], Time=8.94s, Train Loss=0.4595, Val Loss=0.4552, Val F1=0.6739, Test Loss=0.4624, Test F1=0.6880
EarlyStopping counter: 4 out of 5
[Epoch 08/20], Time=8.88s, Train Loss=0.4551, Val Loss=0.4575, Val F1=0.6814, Test Loss=0.4686, Test F1=0.6762
Validation loss decreased (-0.678072 --> -0.681388).  Saving model ...
[Epoch 09/20], Time=8.69s, Train Loss=0.4532, Val Loss=0.4574, Val F1=0.6787, Test Loss=0.4626, Test F1=0.6864
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=8.82s, Train Loss=0.4492, Val Loss=0.4499, Val F1=0.6830, Test Loss=0.4582, Test F1=0.6885
Validation loss decreased (-0.681388 --> -0.683002).  Saving model ...
[Epoch 11/20], Time=8.81s, Train Loss=0.4495, Val Loss=0.4563, Val F1=0.6732, Test Loss=0.4679, Test F1=0.6886
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=8.86s, Train Loss=0.4467, Val Loss=0.4493, Val F1=0.6730, Test Loss=0.4584, Test F1=0.6914
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=8.89s, Train Loss=0.4429, Val Loss=0.4505, Val F1=0.6815, Test Loss=0.4563, Test F1=0.6913
EarlyStopping counter: 3 out of 5
[Epoch 14/20], Time=9.04s, Train Loss=0.4436, Val Loss=0.4530, Val F1=0.6794, Test Loss=0.4570, Test F1=0.7025
EarlyStopping counter: 4 out of 5
[Epoch 15/20], Time=8.69s, Train Loss=0.4402, Val Loss=0.4487, Val F1=0.6838, Test Loss=0.4553, Test F1=0.6915
Validation loss decreased (-0.683002 --> -0.683812).  Saving model ...
[Epoch 16/20], Time=8.80s, Train Loss=0.4402, Val Loss=0.4486, Val F1=0.6786, Test Loss=0.4557, Test F1=0.6937
EarlyStopping counter: 1 out of 5
[Epoch 17/20], Time=8.74s, Train Loss=0.4386, Val Loss=0.4476, Val F1=0.6818, Test Loss=0.4522, Test F1=0.6964
EarlyStopping counter: 2 out of 5
[Epoch 18/20], Time=8.86s, Train Loss=0.4371, Val Loss=0.4490, Val F1=0.6870, Test Loss=0.4586, Test F1=0.6915
Validation loss decreased (-0.683812 --> -0.686998).  Saving model ...
[Epoch 19/20], Time=8.81s, Train Loss=0.4324, Val Loss=0.4476, Val F1=0.6874, Test Loss=0.4640, Test F1=0.6875
Validation loss decreased (-0.686998 --> -0.687403).  Saving model ...
[Epoch 20/20], Time=8.97s, Train Loss=0.4322, Val Loss=0.4437, Val F1=0.6916, Test Loss=0.4549, Test F1=0.6977
Validation loss decreased (-0.687403 --> -0.691558).  Saving model ...
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_29_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_29_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8036006546644845
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_29_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:43:37,4,29,0.6916,0.8365,0.6783,0.7053,4,0.000314,64,2,2,3,0.003571,8,5,0.46,0.31,0.7065,19,0.6721,0.8338,0.6336,0.7155,0.0195,False,OK

[I 2026-07-08 19:43:37,454] Trial 29 finished with value: 0.6915584415584416 and parameters: {'lr': 0.00031420692153319316, 'd_model': 4, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.003570512370208001, 'batch_size': 8, 'patience': 5, 'num_kernels': 3}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_30     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0003471586815315168     --e_layers 3     --d_model 32     --d_ff 128     --top_k 2     --num_kernels 3     --dropout 0.2232746211441824     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2232746211441824
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0003471586815315168
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_30
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_30_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.55s, Train Loss=0.5506, Val Loss=0.4704, Val F1=0.6688, Test Loss=0.4773, Test F1=0.6822
Validation loss decreased (inf --> -0.668790).  Saving model ...
[Epoch 02/20], Time=12.78s, Train Loss=0.4764, Val Loss=0.4665, Val F1=0.6725, Test Loss=0.4758, Test F1=0.6901
Validation loss decreased (-0.668790 --> -0.672474).  Saving model ...
[Epoch 03/20], Time=12.73s, Train Loss=0.4676, Val Loss=0.4697, Val F1=0.6625, Test Loss=0.4760, Test F1=0.6864
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=12.77s, Train Loss=0.4658, Val Loss=0.4522, Val F1=0.6863, Test Loss=0.4698, Test F1=0.6872
Validation loss decreased (-0.672474 --> -0.686275).  Saving model ...
[Epoch 05/20], Time=13.07s, Train Loss=0.4605, Val Loss=0.4573, Val F1=0.6844, Test Loss=0.4722, Test F1=0.6847
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=12.77s, Train Loss=0.4532, Val Loss=0.4471, Val F1=0.6820, Test Loss=0.4649, Test F1=0.6813
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=12.74s, Train Loss=0.4510, Val Loss=0.4439, Val F1=0.6892, Test Loss=0.4648, Test F1=0.6935
Validation loss decreased (-0.686275 --> -0.689211).  Saving model ...
[Epoch 08/20], Time=12.74s, Train Loss=0.4519, Val Loss=0.4519, Val F1=0.6875, Test Loss=0.4624, Test F1=0.7032
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=12.83s, Train Loss=0.4491, Val Loss=0.4483, Val F1=0.6855, Test Loss=0.4678, Test F1=0.6968
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=12.84s, Train Loss=0.4481, Val Loss=0.4433, Val F1=0.6888, Test Loss=0.4585, Test F1=0.7044
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=13.03s, Train Loss=0.4430, Val Loss=0.4442, Val F1=0.6827, Test Loss=0.4591, Test F1=0.7044
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=13.07s, Train Loss=0.4415, Val Loss=0.4381, Val F1=0.6947, Test Loss=0.4574, Test F1=0.7020
Validation loss decreased (-0.689211 --> -0.694704).  Saving model ...
[Epoch 13/20], Time=12.85s, Train Loss=0.4412, Val Loss=0.4384, Val F1=0.7024, Test Loss=0.4599, Test F1=0.6980
Validation loss decreased (-0.694704 --> -0.702439).  Saving model ...
[Epoch 14/20], Time=12.92s, Train Loss=0.4375, Val Loss=0.4410, Val F1=0.6972, Test Loss=0.4586, Test F1=0.7083
EarlyStopping counter: 1 out of 5
[Epoch 15/20], Time=12.71s, Train Loss=0.4394, Val Loss=0.4445, Val F1=0.6944, Test Loss=0.4596, Test F1=0.7103
EarlyStopping counter: 2 out of 5
[Epoch 16/20], Time=12.89s, Train Loss=0.4294, Val Loss=0.4465, Val F1=0.6894, Test Loss=0.4565, Test F1=0.7012
EarlyStopping counter: 3 out of 5
[Epoch 17/20], Time=12.86s, Train Loss=0.4317, Val Loss=0.4495, Val F1=0.6933, Test Loss=0.4631, Test F1=0.7068
EarlyStopping counter: 4 out of 5
[Epoch 18/20], Time=12.93s, Train Loss=0.4238, Val Loss=0.4417, Val F1=0.6880, Test Loss=0.4602, Test F1=0.6987
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_30_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_30_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8076923076923077
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_30_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:48:22,4,30,0.7024,0.8388,0.6879,0.7176,32,0.000347,128,3,2,3,0.223275,8,5,0.33,0.26,0.7065,19,0.6957,0.8323,0.6718,0.7213,0.0068,False,OK

[I 2026-07-08 19:48:22,928] Trial 30 finished with value: 0.7024390243902439 and parameters: {'lr': 0.0003471586815315168, 'd_model': 32, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.2232746211441824, 'batch_size': 8, 'patience': 5, 'num_kernels': 3}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_31     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0006987752347171837     --e_layers 2     --d_model 16     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.16765032977704725     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 16
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.16765032977704725
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0006987752347171837
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_31
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_31_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=15.00s, Train Loss=0.5739, Val Loss=0.4790, Val F1=0.6646, Test Loss=0.4892, Test F1=0.6714
Validation loss decreased (inf --> -0.664577).  Saving model ...
[Epoch 02/20], Time=13.81s, Train Loss=0.4816, Val Loss=0.4617, Val F1=0.6725, Test Loss=0.4753, Test F1=0.6755
Validation loss decreased (-0.664577 --> -0.672535).  Saving model ...
[Epoch 03/20], Time=13.73s, Train Loss=0.4689, Val Loss=0.4730, Val F1=0.6730, Test Loss=0.4795, Test F1=0.6816
Validation loss decreased (-0.672535 --> -0.672986).  Saving model ...
[Epoch 04/20], Time=13.79s, Train Loss=0.4688, Val Loss=0.4514, Val F1=0.6806, Test Loss=0.4613, Test F1=0.6923
Validation loss decreased (-0.672986 --> -0.680556).  Saving model ...
[Epoch 05/20], Time=13.67s, Train Loss=0.4617, Val Loss=0.4555, Val F1=0.6738, Test Loss=0.4678, Test F1=0.6841
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=13.66s, Train Loss=0.4588, Val Loss=0.4546, Val F1=0.6770, Test Loss=0.4709, Test F1=0.6827
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=13.54s, Train Loss=0.4543, Val Loss=0.4473, Val F1=0.6764, Test Loss=0.4613, Test F1=0.6869
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=13.73s, Train Loss=0.4531, Val Loss=0.4691, Val F1=0.6844, Test Loss=0.4757, Test F1=0.6888
Validation loss decreased (-0.680556 --> -0.684375).  Saving model ...
[Epoch 09/20], Time=13.58s, Train Loss=0.4509, Val Loss=0.4455, Val F1=0.6888, Test Loss=0.4674, Test F1=0.6747
Validation loss decreased (-0.684375 --> -0.688784).  Saving model ...
[Epoch 10/20], Time=13.78s, Train Loss=0.4487, Val Loss=0.4423, Val F1=0.6917, Test Loss=0.4547, Test F1=0.7059
Validation loss decreased (-0.688784 --> -0.691706).  Saving model ...
[Epoch 11/20], Time=13.75s, Train Loss=0.4484, Val Loss=0.4459, Val F1=0.6851, Test Loss=0.4590, Test F1=0.6949
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=13.56s, Train Loss=0.4407, Val Loss=0.4541, Val F1=0.6785, Test Loss=0.4665, Test F1=0.6858
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=13.70s, Train Loss=0.4397, Val Loss=0.4420, Val F1=0.6997, Test Loss=0.4600, Test F1=0.7016
Validation loss decreased (-0.691706 --> -0.699700).  Saving model ...
[Epoch 14/20], Time=13.58s, Train Loss=0.4399, Val Loss=0.4488, Val F1=0.6806, Test Loss=0.4699, Test F1=0.6753
EarlyStopping counter: 1 out of 5
[Epoch 15/20], Time=13.70s, Train Loss=0.4360, Val Loss=0.4558, Val F1=0.6811, Test Loss=0.4582, Test F1=0.6954
EarlyStopping counter: 2 out of 5
[Epoch 16/20], Time=13.54s, Train Loss=0.4370, Val Loss=0.4453, Val F1=0.6817, Test Loss=0.4607, Test F1=0.6914
EarlyStopping counter: 3 out of 5
[Epoch 17/20], Time=13.85s, Train Loss=0.4301, Val Loss=0.4452, Val F1=0.6931, Test Loss=0.4575, Test F1=0.7047
EarlyStopping counter: 4 out of 5
[Epoch 18/20], Time=13.86s, Train Loss=0.4343, Val Loss=0.4399, Val F1=0.6890, Test Loss=0.4520, Test F1=0.7048
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_31_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_31_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8060556464811784
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_31_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:53:25,4,31,0.6997,0.8401,0.742,0.6619,16,0.000699,128,2,2,6,0.16765,8,5,0.2,0.23,0.7065,19,0.6764,0.8357,0.7684,0.604,0.0233,False,OK

[I 2026-07-08 19:53:25,940] Trial 31 finished with value: 0.6996996996996997 and parameters: {'lr': 0.0006987752347171837, 'd_model': 16, 'd_ff': 128, 'e_layers': 2, 'top_k': 2, 'dropout': 0.16765032977704725, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_32     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0015482784076836834     --e_layers 2     --d_model 256     --d_ff 256     --top_k 2     --num_kernels 6     --dropout 0.004139218206073873     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 256
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.004139218206073873
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0015482784076836834
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_32
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_32_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=15.92s, Train Loss=0.5072, Val Loss=0.4980, Val F1=0.6845, Test Loss=0.5130, Test F1=0.6697
Validation loss decreased (inf --> -0.684474).  Saving model ...
[Epoch 02/20], Time=14.80s, Train Loss=0.4936, Val Loss=0.4585, Val F1=0.6844, Test Loss=0.4727, Test F1=0.6891
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=14.86s, Train Loss=0.4903, Val Loss=0.4992, Val F1=0.6866, Test Loss=0.5153, Test F1=0.6897
Validation loss decreased (-0.684474 --> -0.686567).  Saving model ...
[Epoch 04/20], Time=14.93s, Train Loss=0.5062, Val Loss=0.4808, Val F1=0.6549, Test Loss=0.5026, Test F1=0.6555
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=14.99s, Train Loss=0.4742, Val Loss=0.4493, Val F1=0.6902, Test Loss=0.4639, Test F1=0.6849
Validation loss decreased (-0.686567 --> -0.690209).  Saving model ...
[Epoch 06/20], Time=14.87s, Train Loss=0.4683, Val Loss=0.4572, Val F1=0.6913, Test Loss=0.4729, Test F1=0.6895
Validation loss decreased (-0.690209 --> -0.691318).  Saving model ...
[Epoch 07/20], Time=14.91s, Train Loss=0.4590, Val Loss=0.4694, Val F1=0.6786, Test Loss=0.4810, Test F1=0.6996
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=14.81s, Train Loss=0.4514, Val Loss=0.4514, Val F1=0.6948, Test Loss=0.4712, Test F1=0.6982
Validation loss decreased (-0.691318 --> -0.694772).  Saving model ...
[Epoch 09/20], Time=15.00s, Train Loss=0.4548, Val Loss=0.4452, Val F1=0.6933, Test Loss=0.4560, Test F1=0.6971
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=15.00s, Train Loss=0.4490, Val Loss=0.4781, Val F1=0.6874, Test Loss=0.4895, Test F1=0.6763
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=14.91s, Train Loss=0.4483, Val Loss=0.4448, Val F1=0.6967, Test Loss=0.4708, Test F1=0.6859
Validation loss decreased (-0.694772 --> -0.696734).  Saving model ...
[Epoch 12/20], Time=14.89s, Train Loss=0.4423, Val Loss=0.4450, Val F1=0.6863, Test Loss=0.4635, Test F1=0.6833
EarlyStopping counter: 1 out of 5
[Epoch 13/20], Time=14.90s, Train Loss=0.4406, Val Loss=0.4403, Val F1=0.7018, Test Loss=0.4679, Test F1=0.6938
Validation loss decreased (-0.696734 --> -0.701812).  Saving model ...
[Epoch 14/20], Time=14.95s, Train Loss=0.4371, Val Loss=0.4384, Val F1=0.6973, Test Loss=0.4537, Test F1=0.6999
EarlyStopping counter: 1 out of 5
[Epoch 15/20], Time=14.91s, Train Loss=0.4378, Val Loss=0.4358, Val F1=0.6988, Test Loss=0.4473, Test F1=0.7023
EarlyStopping counter: 2 out of 5
[Epoch 16/20], Time=14.88s, Train Loss=0.4301, Val Loss=0.4521, Val F1=0.6918, Test Loss=0.4589, Test F1=0.7006
EarlyStopping counter: 3 out of 5
[Epoch 17/20], Time=14.96s, Train Loss=0.4239, Val Loss=0.4527, Val F1=0.6885, Test Loss=0.4726, Test F1=0.6749
EarlyStopping counter: 4 out of 5
[Epoch 18/20], Time=14.84s, Train Loss=0.4284, Val Loss=0.4653, Val F1=0.6728, Test Loss=0.4845, Test F1=0.6802
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_32_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_32_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7995090016366612
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_32_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,19:58:54,4,32,0.7018,0.8417,0.6783,0.727,256,0.001548,256,2,2,6,0.004139,8,5,0.3,0.24,0.7065,19,0.6792,0.8338,0.6438,0.7188,0.0226,False,OK

[I 2026-07-08 19:58:54,810] Trial 32 finished with value: 0.7018121911037891 and parameters: {'lr': 0.0015482784076836834, 'd_model': 256, 'd_ff': 256, 'e_layers': 2, 'top_k': 2, 'dropout': 0.004139218206073873, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_33     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 8     --train_epochs 20     --learning_rate 0.00029344913249921943     --e_layers 3     --d_model 48     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.22345864513246552     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.22345864513246552
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00029344913249921943
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_33
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_33_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=20.41s, Train Loss=0.5376, Val Loss=0.4622, Val F1=0.6740, Test Loss=0.4760, Test F1=0.6760
Validation loss decreased (inf --> -0.673981).  Saving model ...
[Epoch 02/20], Time=20.03s, Train Loss=0.4841, Val Loss=0.4669, Val F1=0.6815, Test Loss=0.4843, Test F1=0.6813
Validation loss decreased (-0.673981 --> -0.681458).  Saving model ...
[Epoch 03/20], Time=19.59s, Train Loss=0.4705, Val Loss=0.4590, Val F1=0.6759, Test Loss=0.4787, Test F1=0.6599
EarlyStopping counter: 1 out of 4
[Epoch 04/20], Time=19.60s, Train Loss=0.4618, Val Loss=0.4634, Val F1=0.6884, Test Loss=0.4853, Test F1=0.6760
Validation loss decreased (-0.681458 --> -0.688372).  Saving model ...
[Epoch 05/20], Time=19.25s, Train Loss=0.4602, Val Loss=0.4645, Val F1=0.6760, Test Loss=0.4780, Test F1=0.6834
EarlyStopping counter: 1 out of 4
[Epoch 06/20], Time=18.65s, Train Loss=0.4594, Val Loss=0.4548, Val F1=0.6851, Test Loss=0.4766, Test F1=0.6970
EarlyStopping counter: 2 out of 4
[Epoch 07/20], Time=18.77s, Train Loss=0.4520, Val Loss=0.4466, Val F1=0.6957, Test Loss=0.4611, Test F1=0.6960
Validation loss decreased (-0.688372 --> -0.695652).  Saving model ...
[Epoch 08/20], Time=18.74s, Train Loss=0.4457, Val Loss=0.4562, Val F1=0.6764, Test Loss=0.4680, Test F1=0.6790
EarlyStopping counter: 1 out of 4
[Epoch 09/20], Time=18.77s, Train Loss=0.4465, Val Loss=0.4502, Val F1=0.6881, Test Loss=0.4590, Test F1=0.7021
EarlyStopping counter: 2 out of 4
[Epoch 10/20], Time=18.69s, Train Loss=0.4436, Val Loss=0.4397, Val F1=0.6897, Test Loss=0.4518, Test F1=0.7041
EarlyStopping counter: 3 out of 4
[Epoch 11/20], Time=18.83s, Train Loss=0.4385, Val Loss=0.4483, Val F1=0.6855, Test Loss=0.4661, Test F1=0.6838
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_33_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_33_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8036006546644845
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_33_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:03:24,4,33,0.6957,0.8366,0.6879,0.7036,48,0.000293,128,3,2,6,0.223459,8,4,0.43,0.4,0.7065,19,0.6839,0.8313,0.6718,0.6966,0.0117,False,OK

[I 2026-07-08 20:03:24,281] Trial 33 finished with value: 0.6956521739130435 and parameters: {'lr': 0.00029344913249921943, 'd_model': 48, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.22345864513246552, 'batch_size': 8, 'patience': 4, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_34     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00046277398268096973     --e_layers 5     --d_model 32     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.08492411647632772     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.08492411647632772
dtwwarp                  : False
e_layers                 : 5
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00046277398268096973
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_34
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_34_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el5_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.0.kernels.4.weight
 - model.3.conv.0.kernels.4.bias
 - model.3.conv.0.kernels.5.weight
 - model.3.conv.0.kernels.5.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.3.conv.2.kernels.4.weight
 - model.3.conv.2.kernels.4.bias
 - model.3.conv.2.kernels.5.weight
 - model.3.conv.2.kernels.5.bias
 - model.4.conv.0.kernels.0.weight
 - model.4.conv.0.kernels.0.bias
 - model.4.conv.0.kernels.1.weight
 - model.4.conv.0.kernels.1.bias
 - model.4.conv.0.kernels.2.weight
 - model.4.conv.0.kernels.2.bias
 - model.4.conv.0.kernels.3.weight
 - model.4.conv.0.kernels.3.bias
 - model.4.conv.0.kernels.4.weight
 - model.4.conv.0.kernels.4.bias
 - model.4.conv.0.kernels.5.weight
 - model.4.conv.0.kernels.5.bias
 - model.4.conv.2.kernels.0.weight
 - model.4.conv.2.kernels.0.bias
 - model.4.conv.2.kernels.1.weight
 - model.4.conv.2.kernels.1.bias
 - model.4.conv.2.kernels.2.weight
 - model.4.conv.2.kernels.2.bias
 - model.4.conv.2.kernels.3.weight
 - model.4.conv.2.kernels.3.bias
 - model.4.conv.2.kernels.4.weight
 - model.4.conv.2.kernels.4.bias
 - model.4.conv.2.kernels.5.weight
 - model.4.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=29.90s, Train Loss=0.5153, Val Loss=0.4700, Val F1=0.6709, Test Loss=0.4729, Test F1=0.6824
Validation loss decreased (inf --> -0.670866).  Saving model ...
[Epoch 02/20], Time=28.74s, Train Loss=0.4700, Val Loss=0.4783, Val F1=0.6606, Test Loss=0.4809, Test F1=0.6874
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=28.72s, Train Loss=0.4608, Val Loss=0.4557, Val F1=0.6783, Test Loss=0.4598, Test F1=0.6977
Validation loss decreased (-0.670866 --> -0.678288).  Saving model ...
[Epoch 04/20], Time=28.79s, Train Loss=0.4513, Val Loss=0.4704, Val F1=0.6687, Test Loss=0.4798, Test F1=0.6725
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=28.94s, Train Loss=0.4503, Val Loss=0.4567, Val F1=0.6998, Test Loss=0.4806, Test F1=0.6815
Validation loss decreased (-0.678288 --> -0.699828).  Saving model ...
[Epoch 06/20], Time=28.88s, Train Loss=0.4484, Val Loss=0.4537, Val F1=0.6940, Test Loss=0.4645, Test F1=0.6979
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=28.72s, Train Loss=0.4486, Val Loss=0.4403, Val F1=0.6998, Test Loss=0.4519, Test F1=0.7047
Validation loss decreased (-0.699828 --> -0.699839).  Saving model ...
[Epoch 08/20], Time=28.87s, Train Loss=0.4423, Val Loss=0.4429, Val F1=0.6908, Test Loss=0.4645, Test F1=0.6755
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=28.70s, Train Loss=0.4358, Val Loss=0.4585, Val F1=0.6770, Test Loss=0.4621, Test F1=0.6989
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=28.63s, Train Loss=0.4340, Val Loss=0.4535, Val F1=0.6833, Test Loss=0.4663, Test F1=0.7004
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=28.75s, Train Loss=0.4356, Val Loss=0.4469, Val F1=0.6954, Test Loss=0.4685, Test F1=0.6957
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=28.76s, Train Loss=0.4268, Val Loss=0.4552, Val F1=0.6993, Test Loss=0.4725, Test F1=0.6959
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_34_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el5_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_34_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el5_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8142389525368249
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_34_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el5_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:10:14,4,34,0.6998,0.8391,0.6943,0.7055,32,0.000463,128,5,2,6,0.084924,8,5,0.43,0.35,0.7065,19,0.6911,0.8358,0.6718,0.7116,0.0087,False,OK

[I 2026-07-08 20:10:14,426] Trial 34 finished with value: 0.6998394863563403 and parameters: {'lr': 0.00046277398268096973, 'd_model': 32, 'd_ff': 128, 'e_layers': 5, 'top_k': 2, 'dropout': 0.08492411647632772, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_35     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0007511665710028448     --e_layers 2     --d_model 48     --d_ff 16     --top_k 2     --num_kernels 6     --dropout 0.10063806536870673     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.10063806536870673
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0007511665710028448
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_35
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_35_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.68s, Train Loss=0.5278, Val Loss=0.4548, Val F1=0.6770, Test Loss=0.4674, Test F1=0.6768
Validation loss decreased (inf --> -0.676971).  Saving model ...
[Epoch 02/20], Time=12.59s, Train Loss=0.4640, Val Loss=0.4605, Val F1=0.6848, Test Loss=0.4698, Test F1=0.6882
Validation loss decreased (-0.676971 --> -0.684838).  Saving model ...
[Epoch 03/20], Time=12.56s, Train Loss=0.4597, Val Loss=0.4522, Val F1=0.6852, Test Loss=0.4659, Test F1=0.6896
Validation loss decreased (-0.684838 --> -0.685246).  Saving model ...
[Epoch 04/20], Time=12.54s, Train Loss=0.4502, Val Loss=0.4557, Val F1=0.6985, Test Loss=0.4717, Test F1=0.6980
Validation loss decreased (-0.685246 --> -0.698462).  Saving model ...
[Epoch 05/20], Time=12.56s, Train Loss=0.4445, Val Loss=0.4432, Val F1=0.6974, Test Loss=0.4524, Test F1=0.6924
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=12.52s, Train Loss=0.4395, Val Loss=0.4477, Val F1=0.6924, Test Loss=0.4610, Test F1=0.6970
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=12.60s, Train Loss=0.4395, Val Loss=0.4406, Val F1=0.6881, Test Loss=0.4596, Test F1=0.6916
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=12.51s, Train Loss=0.4374, Val Loss=0.4467, Val F1=0.6997, Test Loss=0.4653, Test F1=0.7020
Validation loss decreased (-0.698462 --> -0.699670).  Saving model ...
[Epoch 09/20], Time=12.66s, Train Loss=0.4338, Val Loss=0.4405, Val F1=0.6975, Test Loss=0.4563, Test F1=0.7031
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=12.55s, Train Loss=0.4289, Val Loss=0.4452, Val F1=0.6987, Test Loss=0.4630, Test F1=0.6943
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=12.44s, Train Loss=0.4228, Val Loss=0.4401, Val F1=0.7010, Test Loss=0.4632, Test F1=0.7009
Validation loss decreased (-0.699670 --> -0.700997).  Saving model ...
[Epoch 12/20], Time=12.66s, Train Loss=0.4222, Val Loss=0.4508, Val F1=0.6928, Test Loss=0.4675, Test F1=0.7076
EarlyStopping counter: 1 out of 5
[Epoch 13/20], Time=12.57s, Train Loss=0.4204, Val Loss=0.4503, Val F1=0.6845, Test Loss=0.4661, Test F1=0.6811
EarlyStopping counter: 2 out of 5
[Epoch 14/20], Time=12.67s, Train Loss=0.4117, Val Loss=0.4419, Val F1=0.6910, Test Loss=0.4666, Test F1=0.6935
EarlyStopping counter: 3 out of 5
[Epoch 15/20], Time=12.73s, Train Loss=0.4108, Val Loss=0.4693, Val F1=0.6816, Test Loss=0.4856, Test F1=0.6789
EarlyStopping counter: 4 out of 5
[Epoch 16/20], Time=12.65s, Train Loss=0.4125, Val Loss=0.4502, Val F1=0.6893, Test Loss=0.4661, Test F1=0.6948
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_35_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_35_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8158756137479541
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_35_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:14:31,4,35,0.701,0.8434,0.672,0.7326,48,0.000751,16,2,2,6,0.100638,8,5,0.42,0.34,0.7065,19,0.6964,0.8353,0.6565,0.7414,0.0046,False,OK

[I 2026-07-08 20:14:31,196] Trial 35 finished with value: 0.7009966777408638 and parameters: {'lr': 0.0007511665710028448, 'd_model': 48, 'd_ff': 16, 'e_layers': 2, 'top_k': 2, 'dropout': 0.10063806536870673, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_36     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.002049183978546724     --e_layers 2     --d_model 128     --d_ff 64     --top_k 2     --num_kernels 4     --dropout 0.035718900132974046     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.035718900132974046
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.002049183978546724
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_36
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_36_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.84s, Train Loss=0.4997, Val Loss=0.4850, Val F1=0.6796, Test Loss=0.4961, Test F1=0.6767
Validation loss decreased (inf --> -0.679646).  Saving model ...
[Epoch 02/20], Time=10.93s, Train Loss=0.4805, Val Loss=0.4785, Val F1=0.6718, Test Loss=0.4771, Test F1=0.6707
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=10.96s, Train Loss=0.4653, Val Loss=0.4584, Val F1=0.6859, Test Loss=0.4658, Test F1=0.6821
Validation loss decreased (-0.679646 --> -0.685897).  Saving model ...
[Epoch 04/20], Time=10.47s, Train Loss=0.4596, Val Loss=0.4790, Val F1=0.6832, Test Loss=0.4906, Test F1=0.6920
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=10.55s, Train Loss=0.4558, Val Loss=0.4446, Val F1=0.6955, Test Loss=0.4688, Test F1=0.6873
Validation loss decreased (-0.685897 --> -0.695513).  Saving model ...
[Epoch 06/20], Time=10.59s, Train Loss=0.4493, Val Loss=0.4754, Val F1=0.6849, Test Loss=0.4873, Test F1=0.6992
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=10.65s, Train Loss=0.4428, Val Loss=0.4621, Val F1=0.6885, Test Loss=0.4718, Test F1=0.6914
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=10.56s, Train Loss=0.4436, Val Loss=0.4471, Val F1=0.6955, Test Loss=0.4588, Test F1=0.7009
EarlyStopping counter: 3 out of 5
[Epoch 09/20], Time=10.45s, Train Loss=0.4391, Val Loss=0.4499, Val F1=0.7049, Test Loss=0.4684, Test F1=0.7099
Validation loss decreased (-0.695513 --> -0.704918).  Saving model ...
[Epoch 10/20], Time=10.40s, Train Loss=0.4308, Val Loss=0.4519, Val F1=0.6877, Test Loss=0.4714, Test F1=0.6829
EarlyStopping counter: 1 out of 5
[Epoch 11/20], Time=10.47s, Train Loss=0.4285, Val Loss=0.4611, Val F1=0.6846, Test Loss=0.4913, Test F1=0.6811
EarlyStopping counter: 2 out of 5
[Epoch 12/20], Time=10.46s, Train Loss=0.4197, Val Loss=0.4433, Val F1=0.6998, Test Loss=0.4721, Test F1=0.6925
EarlyStopping counter: 3 out of 5
[Epoch 13/20], Time=10.42s, Train Loss=0.4174, Val Loss=0.4788, Val F1=0.6909, Test Loss=0.4870, Test F1=0.6889
EarlyStopping counter: 4 out of 5
[Epoch 14/20], Time=10.57s, Train Loss=0.4172, Val Loss=0.4611, Val F1=0.6821, Test Loss=0.4897, Test F1=0.6802
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_36_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_36_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8109656301145662
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_36_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:17:53,4,36,0.7049,0.8418,0.6847,0.7264,128,0.002049,64,2,2,4,0.035719,8,5,0.34,0.27,0.7065,19,0.6989,0.8368,0.6616,0.7407,0.006,False,OK

[I 2026-07-08 20:17:53,685] Trial 36 finished with value: 0.7049180327868853 and parameters: {'lr': 0.002049183978546724, 'd_model': 128, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.035718900132974046, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_37     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0025127946139836856     --e_layers 2     --d_model 64     --d_ff 64     --top_k 2     --num_kernels 3     --dropout 0.006159503138057593     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.006159503138057593
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0025127946139836856
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_37
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_37_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=10.48s, Train Loss=0.4940, Val Loss=0.5141, Val F1=0.6677, Test Loss=0.5220, Test F1=0.6853
Validation loss decreased (inf --> -0.667688).  Saving model ...
[Epoch 02/20], Time=9.43s, Train Loss=0.4698, Val Loss=0.4482, Val F1=0.6903, Test Loss=0.4613, Test F1=0.6941
Validation loss decreased (-0.667688 --> -0.690323).  Saving model ...
[Epoch 03/20], Time=9.55s, Train Loss=0.4598, Val Loss=0.4607, Val F1=0.6856, Test Loss=0.4674, Test F1=0.6885
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=9.70s, Train Loss=0.4497, Val Loss=0.4588, Val F1=0.6802, Test Loss=0.4747, Test F1=0.6895
EarlyStopping counter: 2 out of 5
[Epoch 05/20], Time=9.56s, Train Loss=0.4527, Val Loss=0.4578, Val F1=0.6806, Test Loss=0.4815, Test F1=0.6617
EarlyStopping counter: 3 out of 5
[Epoch 06/20], Time=9.51s, Train Loss=0.4435, Val Loss=0.4442, Val F1=0.6893, Test Loss=0.4706, Test F1=0.6849
EarlyStopping counter: 4 out of 5
[Epoch 07/20], Time=9.47s, Train Loss=0.4364, Val Loss=0.4481, Val F1=0.6854, Test Loss=0.4604, Test F1=0.6827
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_37_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_37_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8027823240589198
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_37_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:19:53,4,37,0.6903,0.8344,0.6815,0.6993,64,0.002513,64,2,2,3,0.00616,8,5,0.47,0.46,0.7065,19,0.689,0.8341,0.6794,0.699,0.0013,False,OK

[I 2026-07-08 20:19:53,693] Trial 37 finished with value: 0.6903225806451613 and parameters: {'lr': 0.0025127946139836856, 'd_model': 64, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.006159503138057593, 'batch_size': 8, 'patience': 5, 'num_kernels': 3}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_38     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0007033758678392671     --e_layers 2     --d_model 2     --d_ff 512     --top_k 2     --num_kernels 4     --dropout 0.01797619230703467     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 2
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.01797619230703467
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0007033758678392671
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_38
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_38_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=12.43s, Train Loss=0.6930, Val Loss=0.6261, Val F1=0.5239, Test Loss=0.6249, Test F1=0.5507
Validation loss decreased (inf --> -0.523929).  Saving model ...
[Epoch 02/20], Time=11.50s, Train Loss=0.6290, Val Loss=0.6450, Val F1=0.4871, Test Loss=0.6540, Test F1=0.4841
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=11.43s, Train Loss=0.6628, Val Loss=0.6326, Val F1=0.4868, Test Loss=0.6322, Test F1=0.4857
EarlyStopping counter: 2 out of 5
[Epoch 04/20], Time=11.35s, Train Loss=0.6212, Val Loss=0.6045, Val F1=0.4876, Test Loss=0.6121, Test F1=0.4848
EarlyStopping counter: 3 out of 5
[Epoch 05/20], Time=11.51s, Train Loss=0.6025, Val Loss=0.5864, Val F1=0.4864, Test Loss=0.5998, Test F1=0.4848
EarlyStopping counter: 4 out of 5
[Epoch 06/20], Time=11.29s, Train Loss=0.5878, Val Loss=0.5709, Val F1=0.4864, Test Loss=0.5899, Test F1=0.4848
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_38_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_38_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.6702127659574468
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_38_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:21:56,4,38,0.5239,0.6778,0.6624,0.4333,2,0.000703,512,2,2,4,0.017976,8,5,0.36,0.43,0.7065,19,0.5251,0.6724,0.6794,0.4279,-0.0011,False,OK

[I 2026-07-08 20:21:57,009] Trial 38 finished with value: 0.5239294710327456 and parameters: {'lr': 0.0007033758678392671, 'd_model': 2, 'd_ff': 512, 'e_layers': 2, 'top_k': 2, 'dropout': 0.01797619230703467, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_39     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.000736086925565968     --e_layers 2     --d_model 128     --d_ff 64     --top_k 2     --num_kernels 4     --dropout 0.07288965259153743     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.07288965259153743
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.000736086925565968
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_39
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_39_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.42s, Train Loss=0.5020, Val Loss=0.4678, Val F1=0.6838, Test Loss=0.4813, Test F1=0.6825
Validation loss decreased (inf --> -0.683849).  Saving model ...
[Epoch 02/20], Time=10.34s, Train Loss=0.4690, Val Loss=0.4741, Val F1=0.6775, Test Loss=0.4764, Test F1=0.6845
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=10.30s, Train Loss=0.4579, Val Loss=0.4596, Val F1=0.6851, Test Loss=0.4704, Test F1=0.6891
Validation loss decreased (-0.683849 --> -0.685065).  Saving model ...
[Epoch 04/20], Time=10.40s, Train Loss=0.4467, Val Loss=0.4943, Val F1=0.6844, Test Loss=0.5093, Test F1=0.6920
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=10.38s, Train Loss=0.4444, Val Loss=0.4501, Val F1=0.7021, Test Loss=0.4731, Test F1=0.6825
Validation loss decreased (-0.685065 --> -0.702128).  Saving model ...
[Epoch 06/20], Time=10.50s, Train Loss=0.4391, Val Loss=0.4595, Val F1=0.6953, Test Loss=0.4687, Test F1=0.7014
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=10.35s, Train Loss=0.4318, Val Loss=0.4487, Val F1=0.6921, Test Loss=0.4587, Test F1=0.6889
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=10.28s, Train Loss=0.4294, Val Loss=0.4447, Val F1=0.6952, Test Loss=0.4530, Test F1=0.6880
EarlyStopping counter: 3 out of 5
[Epoch 09/20], Time=10.49s, Train Loss=0.4202, Val Loss=0.4587, Val F1=0.6984, Test Loss=0.4767, Test F1=0.6859
EarlyStopping counter: 4 out of 5
[Epoch 10/20], Time=10.41s, Train Loss=0.4093, Val Loss=0.4569, Val F1=0.6818, Test Loss=0.4798, Test F1=0.6774
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_39_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_39_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8052373158756138
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_39_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:24:34,4,39,0.7021,0.842,0.7357,0.6715,128,0.000736,64,2,2,4,0.07289,8,5,0.4,0.48,0.7065,19,0.67,0.8249,0.6921,0.6492,0.0322,False,OK

[I 2026-07-08 20:24:34,165] Trial 39 finished with value: 0.7021276595744681 and parameters: {'lr': 0.000736086925565968, 'd_model': 128, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.07288965259153743, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_40     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 8     --train_epochs 20     --learning_rate 0.002127941679601184     --e_layers 3     --d_model 2     --d_ff 64     --top_k 2     --num_kernels 4     --dropout 0.0983037239821201     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 2
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.0983037239821201
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.002127941679601184
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_40
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_40_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=15.18s, Train Loss=0.5696, Val Loss=0.5150, Val F1=0.6430, Test Loss=0.5248, Test F1=0.6213
Validation loss decreased (inf --> -0.642968).  Saving model ...
[Epoch 02/20], Time=14.18s, Train Loss=0.5886, Val Loss=0.5958, Val F1=0.5440, Test Loss=0.6072, Test F1=0.5344
EarlyStopping counter: 1 out of 4
[Epoch 03/20], Time=13.99s, Train Loss=0.6325, Val Loss=0.6219, Val F1=0.4951, Test Loss=0.6257, Test F1=0.4909
EarlyStopping counter: 2 out of 4
[Epoch 04/20], Time=14.18s, Train Loss=0.6267, Val Loss=0.6225, Val F1=0.4903, Test Loss=0.6246, Test F1=0.4897
EarlyStopping counter: 3 out of 4
[Epoch 05/20], Time=13.99s, Train Loss=0.6242, Val Loss=0.6219, Val F1=0.4896, Test Loss=0.6241, Test F1=0.4910
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_40_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_40_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7610474631751227
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_40_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:26:40,4,40,0.643,0.7762,0.6624,0.6246,2,0.002128,64,3,2,4,0.098304,8,4,0.29,0.21,0.7065,19,0.6197,0.764,0.6489,0.593,0.0233,False,OK

[I 2026-07-08 20:26:40,199] Trial 40 finished with value: 0.642967542503864 and parameters: {'lr': 0.002127941679601184, 'd_model': 2, 'd_ff': 64, 'e_layers': 3, 'top_k': 2, 'dropout': 0.0983037239821201, 'batch_size': 8, 'patience': 4, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_41     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 16     --train_epochs 20     --learning_rate 0.002198675077910827     --e_layers 3     --d_model 128     --d_ff 32     --top_k 2     --num_kernels 4     --dropout 0.06465554964764698     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.06465554964764698
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.002198675077910827
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_41
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_41_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=8.77s, Train Loss=0.4920, Val Loss=0.5105, Val F1=0.6907, Test Loss=0.5232, Test F1=0.6764
Validation loss decreased (inf --> -0.690671).  Saving model ...
[Epoch 02/20], Time=7.67s, Train Loss=0.4705, Val Loss=0.4587, Val F1=0.6805, Test Loss=0.4732, Test F1=0.6809
EarlyStopping counter: 1 out of 4
[Epoch 03/20], Time=7.86s, Train Loss=0.4595, Val Loss=0.4642, Val F1=0.6779, Test Loss=0.4940, Test F1=0.6736
EarlyStopping counter: 2 out of 4
[Epoch 04/20], Time=7.74s, Train Loss=0.4493, Val Loss=0.4519, Val F1=0.6882, Test Loss=0.4638, Test F1=0.6830
EarlyStopping counter: 3 out of 4
[Epoch 05/20], Time=7.84s, Train Loss=0.4527, Val Loss=0.4660, Val F1=0.6845, Test Loss=0.4861, Test F1=0.6562
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_41_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_41_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7962356792144026
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_41_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:28:10,4,41,0.6907,0.8222,0.672,0.7104,128,0.002199,32,3,2,4,0.064656,16,4,0.21,0.2,0.7065,19,0.6738,0.8228,0.6412,0.7099,0.0169,False,OK

[I 2026-07-08 20:28:10,755] Trial 41 finished with value: 0.690671031096563 and parameters: {'lr': 0.002198675077910827, 'd_model': 128, 'd_ff': 32, 'e_layers': 3, 'top_k': 2, 'dropout': 0.06465554964764698, 'batch_size': 16, 'patience': 4, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_42     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 8     --train_epochs 20     --learning_rate 0.00018129865335403966     --e_layers 2     --d_model 8     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.06779925442059268     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 8
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.06779925442059268
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00018129865335403966
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_42
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_42_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=14.24s, Train Loss=0.5965, Val Loss=0.5049, Val F1=0.6269, Test Loss=0.5121, Test F1=0.6305
Validation loss decreased (inf --> -0.626866).  Saving model ...
[Epoch 02/20], Time=13.24s, Train Loss=0.5073, Val Loss=0.4753, Val F1=0.6561, Test Loss=0.4893, Test F1=0.6605
Validation loss decreased (-0.626866 --> -0.656085).  Saving model ...
[Epoch 03/20], Time=13.16s, Train Loss=0.4868, Val Loss=0.4614, Val F1=0.6667, Test Loss=0.4801, Test F1=0.6699
Validation loss decreased (-0.656085 --> -0.666667).  Saving model ...
[Epoch 04/20], Time=13.13s, Train Loss=0.4797, Val Loss=0.4588, Val F1=0.6698, Test Loss=0.4804, Test F1=0.6625
Validation loss decreased (-0.666667 --> -0.669782).  Saving model ...
[Epoch 05/20], Time=13.17s, Train Loss=0.4769, Val Loss=0.4605, Val F1=0.6721, Test Loss=0.4821, Test F1=0.6651
Validation loss decreased (-0.669782 --> -0.672052).  Saving model ...
[Epoch 06/20], Time=13.25s, Train Loss=0.4724, Val Loss=0.4544, Val F1=0.6738, Test Loss=0.4755, Test F1=0.6682
Validation loss decreased (-0.672052 --> -0.673813).  Saving model ...
[Epoch 07/20], Time=13.24s, Train Loss=0.4720, Val Loss=0.4568, Val F1=0.6633, Test Loss=0.4796, Test F1=0.6578
EarlyStopping counter: 1 out of 4
[Epoch 08/20], Time=13.23s, Train Loss=0.4689, Val Loss=0.4604, Val F1=0.6730, Test Loss=0.4838, Test F1=0.6618
EarlyStopping counter: 2 out of 4
[Epoch 09/20], Time=13.13s, Train Loss=0.4634, Val Loss=0.4556, Val F1=0.6688, Test Loss=0.4779, Test F1=0.6641
EarlyStopping counter: 3 out of 4
[Epoch 10/20], Time=13.16s, Train Loss=0.4661, Val Loss=0.4553, Val F1=0.6688, Test Loss=0.4778, Test F1=0.6613
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_42_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_42_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7888707037643208
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_42_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:31:17,4,42,0.6738,0.8325,0.7006,0.649,8,0.000181,128,2,2,6,0.067799,8,4,0.29,0.27,0.7065,19,0.6609,0.8187,0.6845,0.639,0.0129,False,OK

[I 2026-07-08 20:31:18,002] Trial 42 finished with value: 0.6738131699846861 and parameters: {'lr': 0.00018129865335403966, 'd_model': 8, 'd_ff': 128, 'e_layers': 2, 'top_k': 2, 'dropout': 0.06779925442059268, 'batch_size': 8, 'patience': 4, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_43     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0028612634465868523     --e_layers 2     --d_model 8     --d_ff 64     --top_k 2     --num_kernels 4     --dropout 0.08753690429196775     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 8
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.08753690429196775
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0028612634465868523
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_43
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_43_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.14s, Train Loss=0.5149, Val Loss=0.4649, Val F1=0.6688, Test Loss=0.4787, Test F1=0.6599
Validation loss decreased (inf --> -0.668790).  Saving model ...
[Epoch 02/20], Time=10.02s, Train Loss=0.4767, Val Loss=0.4633, Val F1=0.6841, Test Loss=0.4720, Test F1=0.6829
Validation loss decreased (-0.668790 --> -0.684129).  Saving model ...
[Epoch 03/20], Time=10.07s, Train Loss=0.4649, Val Loss=0.4857, Val F1=0.6718, Test Loss=0.4954, Test F1=0.6779
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=10.10s, Train Loss=0.4635, Val Loss=0.4562, Val F1=0.6815, Test Loss=0.4663, Test F1=0.6755
EarlyStopping counter: 2 out of 5
[Epoch 05/20], Time=10.12s, Train Loss=0.4644, Val Loss=0.4627, Val F1=0.6793, Test Loss=0.4809, Test F1=0.6675
EarlyStopping counter: 3 out of 5
[Epoch 06/20], Time=10.00s, Train Loss=0.4561, Val Loss=0.4577, Val F1=0.6738, Test Loss=0.4686, Test F1=0.6794
EarlyStopping counter: 4 out of 5
[Epoch 07/20], Time=10.10s, Train Loss=0.4512, Val Loss=0.4554, Val F1=0.6796, Test Loss=0.4641, Test F1=0.6886
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_43_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_43_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7978723404255319
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_43_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:33:21,4,43,0.6841,0.8268,0.707,0.6627,8,0.002861,64,2,2,4,0.087537,8,5,0.41,0.42,0.7065,19,0.6784,0.8282,0.6845,0.6725,0.0057,False,OK

[I 2026-07-08 20:33:21,940] Trial 43 finished with value: 0.6841294298921418 and parameters: {'lr': 0.0028612634465868523, 'd_model': 8, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.08753690429196775, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_44     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0009387263405256307     --e_layers 2     --d_model 32     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.2534148581564103     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2534148581564103
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0009387263405256307
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_44
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_44_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=8.50s, Train Loss=0.5369, Val Loss=0.4689, Val F1=0.6827, Test Loss=0.4906, Test F1=0.6718
Validation loss decreased (inf --> -0.682692).  Saving model ...
[Epoch 02/20], Time=7.46s, Train Loss=0.4792, Val Loss=0.4645, Val F1=0.6667, Test Loss=0.4789, Test F1=0.6684
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=7.35s, Train Loss=0.4676, Val Loss=0.4566, Val F1=0.6818, Test Loss=0.4725, Test F1=0.6812
EarlyStopping counter: 2 out of 5
[Epoch 04/20], Time=7.38s, Train Loss=0.4672, Val Loss=0.4434, Val F1=0.6861, Test Loss=0.4604, Test F1=0.6866
Validation loss decreased (-0.682692 --> -0.686084).  Saving model ...
[Epoch 05/20], Time=7.44s, Train Loss=0.4638, Val Loss=0.4587, Val F1=0.6710, Test Loss=0.4801, Test F1=0.6649
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=7.49s, Train Loss=0.4616, Val Loss=0.4572, Val F1=0.6805, Test Loss=0.4773, Test F1=0.6791
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=7.42s, Train Loss=0.4550, Val Loss=0.4465, Val F1=0.6877, Test Loss=0.4671, Test F1=0.6817
Validation loss decreased (-0.686084 --> -0.687708).  Saving model ...
[Epoch 08/20], Time=7.38s, Train Loss=0.4517, Val Loss=0.4417, Val F1=0.6959, Test Loss=0.4538, Test F1=0.7082
Validation loss decreased (-0.687708 --> -0.695935).  Saving model ...
[Epoch 09/20], Time=7.47s, Train Loss=0.4492, Val Loss=0.4368, Val F1=0.6991, Test Loss=0.4563, Test F1=0.7009
Validation loss decreased (-0.695935 --> -0.699060).  Saving model ...
[Epoch 10/20], Time=7.39s, Train Loss=0.4460, Val Loss=0.4461, Val F1=0.6927, Test Loss=0.4609, Test F1=0.7033
EarlyStopping counter: 1 out of 5
[Epoch 11/20], Time=7.36s, Train Loss=0.4392, Val Loss=0.4606, Val F1=0.6865, Test Loss=0.4682, Test F1=0.6933
EarlyStopping counter: 2 out of 5
[Epoch 12/20], Time=7.35s, Train Loss=0.4406, Val Loss=0.4353, Val F1=0.6955, Test Loss=0.4549, Test F1=0.6966
EarlyStopping counter: 3 out of 5
[Epoch 13/20], Time=7.36s, Train Loss=0.4371, Val Loss=0.4382, Val F1=0.6972, Test Loss=0.4573, Test F1=0.7006
EarlyStopping counter: 4 out of 5
[Epoch 14/20], Time=7.30s, Train Loss=0.4336, Val Loss=0.4447, Val F1=0.7002, Test Loss=0.4696, Test F1=0.6974
Validation loss decreased (-0.699060 --> -0.700157).  Saving model ...
[Epoch 15/20], Time=7.36s, Train Loss=0.4346, Val Loss=0.4363, Val F1=0.6945, Test Loss=0.4549, Test F1=0.7024
EarlyStopping counter: 1 out of 5
[Epoch 16/20], Time=7.47s, Train Loss=0.4312, Val Loss=0.4447, Val F1=0.6849, Test Loss=0.4528, Test F1=0.7003
EarlyStopping counter: 2 out of 5
[Epoch 17/20], Time=7.45s, Train Loss=0.4287, Val Loss=0.4390, Val F1=0.6948, Test Loss=0.4619, Test F1=0.6833
EarlyStopping counter: 3 out of 5
[Epoch 18/20], Time=7.56s, Train Loss=0.4281, Val Loss=0.4385, Val F1=0.7028, Test Loss=0.4616, Test F1=0.6950
Validation loss decreased (-0.700157 --> -0.702791).  Saving model ...
[Epoch 19/20], Time=7.54s, Train Loss=0.4211, Val Loss=0.4346, Val F1=0.7045, Test Loss=0.4581, Test F1=0.6934
Validation loss decreased (-0.702791 --> -0.704508).  Saving model ...
[Epoch 20/20], Time=7.62s, Train Loss=0.4216, Val Loss=0.4372, Val F1=0.6894, Test Loss=0.4662, Test F1=0.6867
EarlyStopping counter: 1 out of 5
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_44_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_44_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8101472995090017
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_44_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:36:43,4,44,0.7045,0.836,0.672,0.7404,32,0.000939,128,2,2,6,0.253415,16,5,0.4,0.28,0.7065,19,0.691,0.8273,0.6514,0.7356,0.0135,False,OK

[I 2026-07-08 20:36:43,540] Trial 44 finished with value: 0.7045075125208681 and parameters: {'lr': 0.0009387263405256307, 'd_model': 32, 'd_ff': 128, 'e_layers': 2, 'top_k': 2, 'dropout': 0.2534148581564103, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_45     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.00022378712885759956     --e_layers 4     --d_model 16     --d_ff 64     --top_k 2     --num_kernels 6     --dropout 0.14147780521857262     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 16
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.14147780521857262
dtwwarp                  : False
e_layers                 : 4
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00022378712885759956
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_45
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_45_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el4_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.0.kernels.4.weight
 - model.3.conv.0.kernels.4.bias
 - model.3.conv.0.kernels.5.weight
 - model.3.conv.0.kernels.5.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.3.conv.2.kernels.4.weight
 - model.3.conv.2.kernels.4.bias
 - model.3.conv.2.kernels.5.weight
 - model.3.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.07s, Train Loss=0.6047, Val Loss=0.4987, Val F1=0.6436, Test Loss=0.5025, Test F1=0.6399
Validation loss decreased (inf --> -0.643599).  Saving model ...
[Epoch 02/20], Time=12.16s, Train Loss=0.5133, Val Loss=0.4706, Val F1=0.6655, Test Loss=0.4792, Test F1=0.6552
Validation loss decreased (-0.643599 --> -0.665541).  Saving model ...
[Epoch 03/20], Time=12.31s, Train Loss=0.4888, Val Loss=0.4681, Val F1=0.6701, Test Loss=0.4805, Test F1=0.6588
Validation loss decreased (-0.665541 --> -0.670085).  Saving model ...
[Epoch 04/20], Time=12.30s, Train Loss=0.4813, Val Loss=0.4596, Val F1=0.6709, Test Loss=0.4724, Test F1=0.6675
Validation loss decreased (-0.670085 --> -0.670947).  Saving model ...
[Epoch 05/20], Time=11.88s, Train Loss=0.4760, Val Loss=0.4631, Val F1=0.6667, Test Loss=0.4756, Test F1=0.6707
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=11.85s, Train Loss=0.4756, Val Loss=0.4604, Val F1=0.6699, Test Loss=0.4747, Test F1=0.6667
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=11.75s, Train Loss=0.4669, Val Loss=0.4574, Val F1=0.6698, Test Loss=0.4721, Test F1=0.6717
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=11.86s, Train Loss=0.4643, Val Loss=0.4624, Val F1=0.6569, Test Loss=0.4774, Test F1=0.6543
EarlyStopping counter: 4 out of 5
[Epoch 09/20], Time=12.05s, Train Loss=0.4602, Val Loss=0.4568, Val F1=0.6708, Test Loss=0.4735, Test F1=0.6742
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_45_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el4_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_45_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el4_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.792962356792144
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_45_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el4_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:39:26,4,45,0.6709,0.8203,0.6656,0.6764,16,0.000224,64,4,2,6,0.141478,16,5,0.35,0.31,0.7065,19,0.6528,0.8166,0.6387,0.6676,0.0182,False,OK

[I 2026-07-08 20:39:26,251] Trial 45 finished with value: 0.6709470304975923 and parameters: {'lr': 0.00022378712885759956, 'd_model': 16, 'd_ff': 64, 'e_layers': 4, 'top_k': 2, 'dropout': 0.14147780521857262, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_46     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00038763514943211533     --e_layers 3     --d_model 48     --d_ff 128     --top_k 2     --num_kernels 4     --dropout 0.15977154163719426     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.15977154163719426
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00038763514943211533
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_46
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_46_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=15.53s, Train Loss=0.5296, Val Loss=0.4630, Val F1=0.6748, Test Loss=0.4731, Test F1=0.6822
Validation loss decreased (inf --> -0.674783).  Saving model ...
[Epoch 02/20], Time=14.29s, Train Loss=0.4679, Val Loss=0.4619, Val F1=0.6841, Test Loss=0.4732, Test F1=0.6864
Validation loss decreased (-0.674783 --> -0.684119).  Saving model ...
[Epoch 03/20], Time=14.41s, Train Loss=0.4654, Val Loss=0.4561, Val F1=0.6762, Test Loss=0.4686, Test F1=0.6769
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=14.38s, Train Loss=0.4590, Val Loss=0.4446, Val F1=0.6857, Test Loss=0.4634, Test F1=0.6961
Validation loss decreased (-0.684119 --> -0.685714).  Saving model ...
[Epoch 05/20], Time=14.06s, Train Loss=0.4501, Val Loss=0.4520, Val F1=0.6738, Test Loss=0.4661, Test F1=0.6880
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=14.15s, Train Loss=0.4489, Val Loss=0.4541, Val F1=0.6838, Test Loss=0.4655, Test F1=0.6870
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=14.33s, Train Loss=0.4447, Val Loss=0.4437, Val F1=0.6912, Test Loss=0.4537, Test F1=0.6949
Validation loss decreased (-0.685714 --> -0.691152).  Saving model ...
[Epoch 08/20], Time=14.30s, Train Loss=0.4364, Val Loss=0.4406, Val F1=0.6951, Test Loss=0.4609, Test F1=0.7022
Validation loss decreased (-0.691152 --> -0.695082).  Saving model ...
[Epoch 09/20], Time=14.11s, Train Loss=0.4341, Val Loss=0.4442, Val F1=0.6862, Test Loss=0.4630, Test F1=0.6958
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=14.46s, Train Loss=0.4315, Val Loss=0.4392, Val F1=0.7008, Test Loss=0.4592, Test F1=0.6995
Validation loss decreased (-0.695082 --> -0.700775).  Saving model ...
[Epoch 11/20], Time=14.18s, Train Loss=0.4292, Val Loss=0.4495, Val F1=0.6895, Test Loss=0.4600, Test F1=0.7114
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=14.16s, Train Loss=0.4260, Val Loss=0.4483, Val F1=0.6910, Test Loss=0.4637, Test F1=0.6929
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=14.26s, Train Loss=0.4260, Val Loss=0.4502, Val F1=0.6846, Test Loss=0.4544, Test F1=0.7018
EarlyStopping counter: 3 out of 5
[Epoch 14/20], Time=14.36s, Train Loss=0.4235, Val Loss=0.4482, Val F1=0.6847, Test Loss=0.4601, Test F1=0.6853
EarlyStopping counter: 4 out of 5
[Epoch 15/20], Time=14.62s, Train Loss=0.4236, Val Loss=0.4485, Val F1=0.6941, Test Loss=0.4593, Test F1=0.7021
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_46_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_46_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8109656301145662
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_46_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:43:56,4,46,0.7008,0.8413,0.7197,0.6828,48,0.000388,128,3,2,4,0.159772,8,5,0.33,0.32,0.7065,19,0.699,0.8357,0.6972,0.7008,0.0018,False,OK

[I 2026-07-08 20:43:56,518] Trial 46 finished with value: 0.7007751937984497 and parameters: {'lr': 0.00038763514943211533, 'd_model': 48, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.15977154163719426, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_47     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0001995340845256783     --e_layers 4     --d_model 48     --d_ff 4     --top_k 2     --num_kernels 6     --dropout 0.10701978436310691     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 4
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.10701978436310691
dtwwarp                  : False
e_layers                 : 4
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0001995340845256783
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_47
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_47_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el4_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.0.kernels.4.weight
 - model.3.conv.0.kernels.4.bias
 - model.3.conv.0.kernels.5.weight
 - model.3.conv.0.kernels.5.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.3.conv.2.kernels.4.weight
 - model.3.conv.2.kernels.4.bias
 - model.3.conv.2.kernels.5.weight
 - model.3.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=23.03s, Train Loss=0.5992, Val Loss=0.5052, Val F1=0.6110, Test Loss=0.5029, Test F1=0.6456
Validation loss decreased (inf --> -0.611012).  Saving model ...
[Epoch 02/20], Time=22.08s, Train Loss=0.4981, Val Loss=0.4700, Val F1=0.6720, Test Loss=0.4762, Test F1=0.6667
Validation loss decreased (-0.611012 --> -0.671975).  Saving model ...
[Epoch 03/20], Time=22.22s, Train Loss=0.4726, Val Loss=0.4618, Val F1=0.6739, Test Loss=0.4738, Test F1=0.6806
Validation loss decreased (-0.671975 --> -0.673879).  Saving model ...
[Epoch 04/20], Time=21.98s, Train Loss=0.4603, Val Loss=0.4559, Val F1=0.6786, Test Loss=0.4679, Test F1=0.6805
Validation loss decreased (-0.673879 --> -0.678571).  Saving model ...
[Epoch 05/20], Time=22.19s, Train Loss=0.4563, Val Loss=0.4566, Val F1=0.6813, Test Loss=0.4696, Test F1=0.6870
Validation loss decreased (-0.678571 --> -0.681319).  Saving model ...
[Epoch 06/20], Time=21.68s, Train Loss=0.4532, Val Loss=0.4548, Val F1=0.6865, Test Loss=0.4697, Test F1=0.6887
Validation loss decreased (-0.681319 --> -0.686469).  Saving model ...
[Epoch 07/20], Time=21.64s, Train Loss=0.4507, Val Loss=0.4554, Val F1=0.6799, Test Loss=0.4673, Test F1=0.6866
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=21.54s, Train Loss=0.4513, Val Loss=0.4562, Val F1=0.6805, Test Loss=0.4693, Test F1=0.6804
EarlyStopping counter: 2 out of 5
[Epoch 09/20], Time=21.52s, Train Loss=0.4461, Val Loss=0.4536, Val F1=0.6864, Test Loss=0.4669, Test F1=0.6804
EarlyStopping counter: 3 out of 5
[Epoch 10/20], Time=21.44s, Train Loss=0.4475, Val Loss=0.4516, Val F1=0.6839, Test Loss=0.4653, Test F1=0.6893
EarlyStopping counter: 4 out of 5
[Epoch 11/20], Time=21.50s, Train Loss=0.4437, Val Loss=0.4516, Val F1=0.6903, Test Loss=0.4684, Test F1=0.6915
Validation loss decreased (-0.686469 --> -0.690323).  Saving model ...
[Epoch 12/20], Time=21.38s, Train Loss=0.4438, Val Loss=0.4469, Val F1=0.6932, Test Loss=0.4635, Test F1=0.6877
Validation loss decreased (-0.690323 --> -0.693201).  Saving model ...
[Epoch 13/20], Time=21.71s, Train Loss=0.4388, Val Loss=0.4468, Val F1=0.6903, Test Loss=0.4663, Test F1=0.6930
EarlyStopping counter: 1 out of 5
[Epoch 14/20], Time=21.50s, Train Loss=0.4410, Val Loss=0.4509, Val F1=0.6889, Test Loss=0.4684, Test F1=0.6886
EarlyStopping counter: 2 out of 5
[Epoch 15/20], Time=21.54s, Train Loss=0.4370, Val Loss=0.4452, Val F1=0.6913, Test Loss=0.4623, Test F1=0.6957
EarlyStopping counter: 3 out of 5
[Epoch 16/20], Time=21.89s, Train Loss=0.4328, Val Loss=0.4485, Val F1=0.6942, Test Loss=0.4695, Test F1=0.6869
Validation loss decreased (-0.693201 --> -0.694215).  Saving model ...
[Epoch 17/20], Time=22.08s, Train Loss=0.4346, Val Loss=0.4417, Val F1=0.6958, Test Loss=0.4612, Test F1=0.6986
Validation loss decreased (-0.694215 --> -0.695793).  Saving model ...
[Epoch 18/20], Time=21.84s, Train Loss=0.4289, Val Loss=0.4422, Val F1=0.6982, Test Loss=0.4630, Test F1=0.6862
Validation loss decreased (-0.695793 --> -0.698206).  Saving model ...
[Epoch 19/20], Time=22.19s, Train Loss=0.4285, Val Loss=0.4397, Val F1=0.6980, Test Loss=0.4581, Test F1=0.7002
EarlyStopping counter: 1 out of 5
[Epoch 20/20], Time=21.71s, Train Loss=0.4246, Val Loss=0.4433, Val F1=0.6984, Test Loss=0.4613, Test F1=0.6935
Validation loss decreased (-0.698206 --> -0.698361).  Saving model ...
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_47_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el4_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_47_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el4_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8126022913256956
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_47_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el4_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:52:11,4,47,0.6984,0.8382,0.6783,0.7196,48,0.0002,4,4,2,6,0.10702,8,5,0.46,0.33,0.7065,19,0.6909,0.8335,0.6539,0.7322,0.0075,False,OK

[I 2026-07-08 20:52:11,572] Trial 47 finished with value: 0.6983606557377049 and parameters: {'lr': 0.0001995340845256783, 'd_model': 48, 'd_ff': 4, 'e_layers': 4, 'top_k': 2, 'dropout': 0.10701978436310691, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_48     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0004508037388315655     --e_layers 2     --d_model 2     --d_ff 128     --top_k 2     --num_kernels 4     --dropout 0.2159557954475141     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 2
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2159557954475141
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0004508037388315655
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_48
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_48_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.00s, Train Loss=0.6957, Val Loss=0.6448, Val F1=0.5156, Test Loss=0.6485, Test F1=0.5238
Validation loss decreased (inf --> -0.515625).  Saving model ...
[Epoch 02/20], Time=5.80s, Train Loss=0.6523, Val Loss=0.6040, Val F1=0.5142, Test Loss=0.6100, Test F1=0.5255
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=5.86s, Train Loss=0.6288, Val Loss=0.5910, Val F1=0.5099, Test Loss=0.5951, Test F1=0.5121
EarlyStopping counter: 2 out of 5
[Epoch 04/20], Time=5.83s, Train Loss=0.6142, Val Loss=0.5784, Val F1=0.5127, Test Loss=0.5875, Test F1=0.5205
EarlyStopping counter: 3 out of 5
[Epoch 05/20], Time=5.93s, Train Loss=0.6183, Val Loss=0.5823, Val F1=0.5128, Test Loss=0.5891, Test F1=0.5193
EarlyStopping counter: 4 out of 5
[Epoch 06/20], Time=5.77s, Train Loss=0.6097, Val Loss=0.5829, Val F1=0.5050, Test Loss=0.5878, Test F1=0.5208
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_48_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_48_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.6538461538461539
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_48_TimesNet_UEA_ftM_sl4_ll48_pl0_dm2_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:53:37,4,48,0.5156,0.6615,0.8408,0.3718,2,0.000451,128,2,2,4,0.215956,16,5,0.39,0.39,0.7065,19,0.5238,0.6608,0.8524,0.3781,-0.0082,False,OK

[I 2026-07-08 20:53:37,937] Trial 48 finished with value: 0.515625 and parameters: {'lr': 0.0004508037388315655, 'd_model': 2, 'd_ff': 128, 'e_layers': 2, 'top_k': 2, 'dropout': 0.2159557954475141, 'batch_size': 16, 'patience': 5, 'num_kernels': 4}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_49     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00039724998796660297     --e_layers 2     --d_model 48     --d_ff 256     --top_k 2     --num_kernels 3     --dropout 0.2069558856920532     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 256
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2069558856920532
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00039724998796660297
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_49
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_49_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=10.52s, Train Loss=0.5212, Val Loss=0.4659, Val F1=0.6667, Test Loss=0.4815, Test F1=0.6733
Validation loss decreased (inf --> -0.666667).  Saving model ...
[Epoch 02/20], Time=9.43s, Train Loss=0.4691, Val Loss=0.4777, Val F1=0.6806, Test Loss=0.4995, Test F1=0.6606
Validation loss decreased (-0.666667 --> -0.680645).  Saving model ...
[Epoch 03/20], Time=9.33s, Train Loss=0.4656, Val Loss=0.4590, Val F1=0.6743, Test Loss=0.4724, Test F1=0.6858
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=9.35s, Train Loss=0.4603, Val Loss=0.4569, Val F1=0.6810, Test Loss=0.4704, Test F1=0.6849
Validation loss decreased (-0.680645 --> -0.681004).  Saving model ...
[Epoch 05/20], Time=9.53s, Train Loss=0.4563, Val Loss=0.4616, Val F1=0.6872, Test Loss=0.4787, Test F1=0.6825
Validation loss decreased (-0.681004 --> -0.687211).  Saving model ...
[Epoch 06/20], Time=9.35s, Train Loss=0.4515, Val Loss=0.4507, Val F1=0.6884, Test Loss=0.4644, Test F1=0.6917
Validation loss decreased (-0.687211 --> -0.688372).  Saving model ...
[Epoch 07/20], Time=9.44s, Train Loss=0.4519, Val Loss=0.4432, Val F1=0.6816, Test Loss=0.4655, Test F1=0.6693
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=9.79s, Train Loss=0.4428, Val Loss=0.4486, Val F1=0.6922, Test Loss=0.4649, Test F1=0.7056
Validation loss decreased (-0.688372 --> -0.692185).  Saving model ...
[Epoch 09/20], Time=9.82s, Train Loss=0.4447, Val Loss=0.4406, Val F1=0.6924, Test Loss=0.4575, Test F1=0.6922
Validation loss decreased (-0.692185 --> -0.692437).  Saving model ...
[Epoch 10/20], Time=9.83s, Train Loss=0.4389, Val Loss=0.4393, Val F1=0.6929, Test Loss=0.4568, Test F1=0.6853
Validation loss decreased (-0.692437 --> -0.692913).  Saving model ...
[Epoch 11/20], Time=9.65s, Train Loss=0.4364, Val Loss=0.4385, Val F1=0.6997, Test Loss=0.4587, Test F1=0.7129
Validation loss decreased (-0.692913 --> -0.699690).  Saving model ...
[Epoch 12/20], Time=9.44s, Train Loss=0.4364, Val Loss=0.4409, Val F1=0.6815, Test Loss=0.4604, Test F1=0.6873
EarlyStopping counter: 1 out of 5
[Epoch 13/20], Time=9.55s, Train Loss=0.4314, Val Loss=0.4356, Val F1=0.6980, Test Loss=0.4604, Test F1=0.7001
EarlyStopping counter: 2 out of 5
[Epoch 14/20], Time=9.47s, Train Loss=0.4323, Val Loss=0.4454, Val F1=0.6921, Test Loss=0.4571, Test F1=0.6954
EarlyStopping counter: 3 out of 5
[Epoch 15/20], Time=9.70s, Train Loss=0.4266, Val Loss=0.4418, Val F1=0.7028, Test Loss=0.4562, Test F1=0.6964
Validation loss decreased (-0.699690 --> -0.702791).  Saving model ...
[Epoch 16/20], Time=9.63s, Train Loss=0.4263, Val Loss=0.4444, Val F1=0.6845, Test Loss=0.4568, Test F1=0.6894
EarlyStopping counter: 1 out of 5
[Epoch 17/20], Time=9.50s, Train Loss=0.4198, Val Loss=0.4427, Val F1=0.6893, Test Loss=0.4540, Test F1=0.7009
EarlyStopping counter: 2 out of 5
[Epoch 18/20], Time=9.55s, Train Loss=0.4157, Val Loss=0.4402, Val F1=0.6900, Test Loss=0.4521, Test F1=0.7005
EarlyStopping counter: 3 out of 5
[Epoch 19/20], Time=9.69s, Train Loss=0.4149, Val Loss=0.4587, Val F1=0.6862, Test Loss=0.4625, Test F1=0.6991
EarlyStopping counter: 4 out of 5
[Epoch 20/20], Time=9.52s, Train Loss=0.4137, Val Loss=0.4317, Val F1=0.7039, Test Loss=0.4567, Test F1=0.6930
Validation loss decreased (-0.702791 --> -0.703947).  Saving model ...
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_49_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_49_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8044189852700491
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_49_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,20:57:42,4,49,0.7039,0.8413,0.6815,0.7279,48,0.000397,256,2,2,3,0.206956,8,5,0.37,0.35,0.7065,19,0.6924,0.8334,0.6616,0.7263,0.0115,False,OK

[I 2026-07-08 20:57:42,483] Trial 49 finished with value: 0.7039473684210527 and parameters: {'lr': 0.00039724998796660297, 'd_model': 48, 'd_ff': 256, 'e_layers': 2, 'top_k': 2, 'dropout': 0.2069558856920532, 'batch_size': 8, 'patience': 5, 'num_kernels': 3}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_50     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00011565843763455988     --e_layers 2     --d_model 48     --d_ff 32     --top_k 2     --num_kernels 6     --dropout 0.2675050559673681     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2675050559673681
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00011565843763455988
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_50
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_50_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=14.41s, Train Loss=0.5763, Val Loss=0.5042, Val F1=0.6244, Test Loss=0.5010, Test F1=0.6411
Validation loss decreased (inf --> -0.624390).  Saving model ...
[Epoch 02/20], Time=13.01s, Train Loss=0.5210, Val Loss=0.4833, Val F1=0.6493, Test Loss=0.4876, Test F1=0.6594
Validation loss decreased (-0.624390 --> -0.649311).  Saving model ...
[Epoch 03/20], Time=13.57s, Train Loss=0.4943, Val Loss=0.4617, Val F1=0.6677, Test Loss=0.4733, Test F1=0.6692
Validation loss decreased (-0.649311 --> -0.667683).  Saving model ...
[Epoch 04/20], Time=13.24s, Train Loss=0.4844, Val Loss=0.4571, Val F1=0.6834, Test Loss=0.4734, Test F1=0.6797
Validation loss decreased (-0.667683 --> -0.683386).  Saving model ...
[Epoch 05/20], Time=13.54s, Train Loss=0.4680, Val Loss=0.4660, Val F1=0.6848, Test Loss=0.4845, Test F1=0.6725
Validation loss decreased (-0.683386 --> -0.684800).  Saving model ...
[Epoch 06/20], Time=13.30s, Train Loss=0.4699, Val Loss=0.4605, Val F1=0.6830, Test Loss=0.4768, Test F1=0.6787
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=13.17s, Train Loss=0.4615, Val Loss=0.4571, Val F1=0.6828, Test Loss=0.4708, Test F1=0.6810
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=13.59s, Train Loss=0.4566, Val Loss=0.4599, Val F1=0.6808, Test Loss=0.4745, Test F1=0.6823
EarlyStopping counter: 3 out of 5
[Epoch 09/20], Time=13.09s, Train Loss=0.4521, Val Loss=0.4593, Val F1=0.6811, Test Loss=0.4731, Test F1=0.6860
EarlyStopping counter: 4 out of 5
[Epoch 10/20], Time=13.14s, Train Loss=0.4569, Val Loss=0.4596, Val F1=0.6750, Test Loss=0.4719, Test F1=0.6831
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_50_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_50_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7806873977086743
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_50_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:00:50,4,50,0.6848,0.8311,0.6815,0.6881,48,0.000116,32,2,2,6,0.267505,8,5,0.24,0.21,0.7065,19,0.6675,0.8218,0.6514,0.6845,0.0173,False,OK

[I 2026-07-08 21:00:50,830] Trial 50 finished with value: 0.6848 and parameters: {'lr': 0.00011565843763455988, 'd_model': 48, 'd_ff': 32, 'e_layers': 2, 'top_k': 2, 'dropout': 0.2675050559673681, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 19 with value: 0.7064676616915423.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_51     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0007914395355568764     --e_layers 2     --d_model 32     --d_ff 512     --top_k 2     --num_kernels 6     --dropout 0.27772898040543464     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.27772898040543464
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0007914395355568764
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_51
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_51_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.74s, Train Loss=0.5228, Val Loss=0.4568, Val F1=0.6614, Test Loss=0.4731, Test F1=0.6707
Validation loss decreased (inf --> -0.661417).  Saving model ...
[Epoch 02/20], Time=12.37s, Train Loss=0.4794, Val Loss=0.4625, Val F1=0.6773, Test Loss=0.4810, Test F1=0.6777
Validation loss decreased (-0.661417 --> -0.677266).  Saving model ...
[Epoch 03/20], Time=12.30s, Train Loss=0.4750, Val Loss=0.4740, Val F1=0.6708, Test Loss=0.4879, Test F1=0.6901
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=12.38s, Train Loss=0.4732, Val Loss=0.4468, Val F1=0.6829, Test Loss=0.4629, Test F1=0.6904
Validation loss decreased (-0.677266 --> -0.682853).  Saving model ...
[Epoch 05/20], Time=12.35s, Train Loss=0.4669, Val Loss=0.4568, Val F1=0.6749, Test Loss=0.4721, Test F1=0.6882
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=12.32s, Train Loss=0.4616, Val Loss=0.4508, Val F1=0.6796, Test Loss=0.4703, Test F1=0.6951
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=12.29s, Train Loss=0.4646, Val Loss=0.4506, Val F1=0.6774, Test Loss=0.4678, Test F1=0.6958
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=12.26s, Train Loss=0.4517, Val Loss=0.4541, Val F1=0.6888, Test Loss=0.4631, Test F1=0.6836
Validation loss decreased (-0.682853 --> -0.688784).  Saving model ...
[Epoch 09/20], Time=12.27s, Train Loss=0.4518, Val Loss=0.4529, Val F1=0.6730, Test Loss=0.4704, Test F1=0.6781
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=12.58s, Train Loss=0.4559, Val Loss=0.4351, Val F1=0.6937, Test Loss=0.4673, Test F1=0.6667
Validation loss decreased (-0.688784 --> -0.693739).  Saving model ...
[Epoch 11/20], Time=12.27s, Train Loss=0.4506, Val Loss=0.4385, Val F1=0.6892, Test Loss=0.4590, Test F1=0.7026
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=12.37s, Train Loss=0.4510, Val Loss=0.4475, Val F1=0.6955, Test Loss=0.4685, Test F1=0.6903
Validation loss decreased (-0.693739 --> -0.695513).  Saving model ...
[Epoch 13/20], Time=12.35s, Train Loss=0.4402, Val Loss=0.4347, Val F1=0.6892, Test Loss=0.4635, Test F1=0.6806
EarlyStopping counter: 1 out of 5
[Epoch 14/20], Time=12.26s, Train Loss=0.4398, Val Loss=0.4496, Val F1=0.6872, Test Loss=0.4611, Test F1=0.6934
EarlyStopping counter: 2 out of 5
[Epoch 15/20], Time=12.41s, Train Loss=0.4401, Val Loss=0.4468, Val F1=0.6864, Test Loss=0.4696, Test F1=0.6739
EarlyStopping counter: 3 out of 5
[Epoch 16/20], Time=12.38s, Train Loss=0.4432, Val Loss=0.4436, Val F1=0.6793, Test Loss=0.4652, Test F1=0.6834
EarlyStopping counter: 4 out of 5
[Epoch 17/20], Time=12.60s, Train Loss=0.4364, Val Loss=0.4388, Val F1=0.6977, Test Loss=0.4657, Test F1=0.6821
Validation loss decreased (-0.695513 --> -0.697749).  Saving model ...
[Epoch 18/20], Time=12.39s, Train Loss=0.4348, Val Loss=0.4414, Val F1=0.6992, Test Loss=0.4593, Test F1=0.7057
Validation loss decreased (-0.697749 --> -0.699213).  Saving model ...
[Epoch 19/20], Time=12.37s, Train Loss=0.4315, Val Loss=0.4323, Val F1=0.7089, Test Loss=0.4560, Test F1=0.6944
Validation loss decreased (-0.699213 --> -0.708861).  Saving model ...
[Epoch 20/20], Time=12.33s, Train Loss=0.4321, Val Loss=0.4424, Val F1=0.6845, Test Loss=0.4612, Test F1=0.6912
EarlyStopping counter: 1 out of 5
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_51_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_51_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8126022913256956
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_51_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:05:57,4,51,0.7089,0.8412,0.7134,0.7044,32,0.000791,512,2,2,6,0.277729,16,5,0.34,0.34,0.7089,51,0.6944,0.8329,0.6997,0.6892,0.0144,False,OK

[I 2026-07-08 21:05:57,268] Trial 51 finished with value: 0.7088607594936709 and parameters: {'lr': 0.0007914395355568764, 'd_model': 32, 'd_ff': 512, 'e_layers': 2, 'top_k': 2, 'dropout': 0.27772898040543464, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_52     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 16     --train_epochs 20     --learning_rate 0.0018656152658575453     --e_layers 2     --d_model 32     --d_ff 512     --top_k 2     --num_kernels 3     --dropout 0.37617045877841226     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.37617045877841226
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0018656152658575453
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_52
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_52_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=6.42s, Train Loss=0.5339, Val Loss=0.4836, Val F1=0.6667, Test Loss=0.5018, Test F1=0.6658
Validation loss decreased (inf --> -0.666667).  Saving model ...
[Epoch 02/20], Time=5.44s, Train Loss=0.4880, Val Loss=0.4459, Val F1=0.6909, Test Loss=0.4698, Test F1=0.6783
Validation loss decreased (-0.666667 --> -0.690852).  Saving model ...
[Epoch 03/20], Time=5.56s, Train Loss=0.4785, Val Loss=0.4619, Val F1=0.6761, Test Loss=0.4796, Test F1=0.6744
EarlyStopping counter: 1 out of 4
[Epoch 04/20], Time=5.64s, Train Loss=0.4763, Val Loss=0.4523, Val F1=0.6866, Test Loss=0.4724, Test F1=0.6788
EarlyStopping counter: 2 out of 4
[Epoch 05/20], Time=5.52s, Train Loss=0.4726, Val Loss=0.4563, Val F1=0.6815, Test Loss=0.4836, Test F1=0.6747
EarlyStopping counter: 3 out of 4
[Epoch 06/20], Time=5.55s, Train Loss=0.4716, Val Loss=0.4560, Val F1=0.6775, Test Loss=0.4715, Test F1=0.6802
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_52_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_52_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7970540098199672
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_52_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:07:21,4,52,0.6909,0.8327,0.6975,0.6844,32,0.001866,512,2,2,3,0.37617,16,4,0.33,0.28,0.7089,51,0.6675,0.8209,0.6514,0.6845,0.0233,False,OK

[I 2026-07-08 21:07:21,441] Trial 52 finished with value: 0.6908517350157729 and parameters: {'lr': 0.0018656152658575453, 'd_model': 32, 'd_ff': 512, 'e_layers': 2, 'top_k': 2, 'dropout': 0.37617045877841226, 'batch_size': 16, 'patience': 4, 'num_kernels': 3}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_53     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.002201564695785877     --e_layers 2     --d_model 32     --d_ff 512     --top_k 2     --num_kernels 6     --dropout 0.2321994040663119     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2321994040663119
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.002201564695785877
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_53
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_53_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.28s, Train Loss=0.5061, Val Loss=0.4574, Val F1=0.6729, Test Loss=0.4749, Test F1=0.6764
Validation loss decreased (inf --> -0.672868).  Saving model ...
[Epoch 02/20], Time=12.25s, Train Loss=0.4810, Val Loss=0.4665, Val F1=0.6816, Test Loss=0.4723, Test F1=0.6848
Validation loss decreased (-0.672868 --> -0.681600).  Saving model ...
[Epoch 03/20], Time=12.26s, Train Loss=0.4771, Val Loss=0.4839, Val F1=0.6720, Test Loss=0.4948, Test F1=0.6845
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=12.24s, Train Loss=0.4718, Val Loss=0.4437, Val F1=0.6835, Test Loss=0.4616, Test F1=0.6894
Validation loss decreased (-0.681600 --> -0.683544).  Saving model ...
[Epoch 05/20], Time=12.36s, Train Loss=0.4708, Val Loss=0.4546, Val F1=0.6737, Test Loss=0.4789, Test F1=0.6776
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=12.27s, Train Loss=0.4673, Val Loss=0.4630, Val F1=0.6828, Test Loss=0.4854, Test F1=0.6840
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=12.29s, Train Loss=0.4697, Val Loss=0.4574, Val F1=0.6598, Test Loss=0.4808, Test F1=0.6711
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=12.20s, Train Loss=0.4554, Val Loss=0.4614, Val F1=0.6689, Test Loss=0.4692, Test F1=0.6824
EarlyStopping counter: 4 out of 5
[Epoch 09/20], Time=12.25s, Train Loss=0.4566, Val Loss=0.4695, Val F1=0.6656, Test Loss=0.4989, Test F1=0.6692
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_53_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_53_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8027823240589198
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_53_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:10:09,4,53,0.6835,0.8305,0.6019,0.7908,32,0.002202,512,2,2,6,0.232199,16,5,0.5,0.29,0.7089,51,0.6512,0.8246,0.5725,0.755,0.0323,False,OK

[I 2026-07-08 21:10:09,422] Trial 53 finished with value: 0.6835443037974683 and parameters: {'lr': 0.002201564695785877, 'd_model': 32, 'd_ff': 512, 'e_layers': 2, 'top_k': 2, 'dropout': 0.2321994040663119, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_54     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0014822298008496184     --e_layers 3     --d_model 48     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.11685458055216061     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.11685458055216061
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0014822298008496184
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_54
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_54_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=20.20s, Train Loss=0.5055, Val Loss=0.4539, Val F1=0.6875, Test Loss=0.4638, Test F1=0.6902
Validation loss decreased (inf --> -0.687500).  Saving model ...
[Epoch 02/20], Time=19.14s, Train Loss=0.4816, Val Loss=0.4741, Val F1=0.6646, Test Loss=0.4858, Test F1=0.6733
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=19.25s, Train Loss=0.4724, Val Loss=0.4865, Val F1=0.6758, Test Loss=0.4924, Test F1=0.6851
EarlyStopping counter: 2 out of 5
[Epoch 04/20], Time=19.07s, Train Loss=0.4692, Val Loss=0.4862, Val F1=0.6429, Test Loss=0.4910, Test F1=0.6667
EarlyStopping counter: 3 out of 5
[Epoch 05/20], Time=19.11s, Train Loss=0.4638, Val Loss=0.4728, Val F1=0.6762, Test Loss=0.4829, Test F1=0.6809
EarlyStopping counter: 4 out of 5
[Epoch 06/20], Time=19.08s, Train Loss=0.4643, Val Loss=0.4688, Val F1=0.6718, Test Loss=0.4706, Test F1=0.6929
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_54_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_54_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8003273322422259
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_54_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:13:03,4,54,0.6875,0.8289,0.7006,0.6748,48,0.001482,128,3,2,6,0.116855,8,5,0.39,0.36,0.7089,51,0.6855,0.8252,0.6794,0.6917,0.002,False,OK

[I 2026-07-08 21:13:03,085] Trial 54 finished with value: 0.6875 and parameters: {'lr': 0.0014822298008496184, 'd_model': 48, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.11685458055216061, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_55     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0002310175486021592     --e_layers 2     --d_model 32     --d_ff 512     --top_k 2     --num_kernels 6     --dropout 0.3825679721198923     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.3825679721198923
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0002310175486021592
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_55
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_55_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.46s, Train Loss=0.5748, Val Loss=0.4775, Val F1=0.6566, Test Loss=0.4864, Test F1=0.6692
Validation loss decreased (inf --> -0.656627).  Saving model ...
[Epoch 02/20], Time=12.26s, Train Loss=0.5018, Val Loss=0.4561, Val F1=0.6728, Test Loss=0.4729, Test F1=0.6766
Validation loss decreased (-0.656627 --> -0.672840).  Saving model ...
[Epoch 03/20], Time=12.25s, Train Loss=0.4932, Val Loss=0.4630, Val F1=0.6739, Test Loss=0.4797, Test F1=0.6772
Validation loss decreased (-0.672840 --> -0.673947).  Saving model ...
[Epoch 04/20], Time=12.26s, Train Loss=0.4840, Val Loss=0.4550, Val F1=0.6817, Test Loss=0.4726, Test F1=0.6852
Validation loss decreased (-0.673947 --> -0.681745).  Saving model ...
[Epoch 05/20], Time=12.28s, Train Loss=0.4793, Val Loss=0.4535, Val F1=0.6852, Test Loss=0.4736, Test F1=0.6892
Validation loss decreased (-0.681745 --> -0.685155).  Saving model ...
[Epoch 06/20], Time=12.23s, Train Loss=0.4673, Val Loss=0.4520, Val F1=0.6818, Test Loss=0.4697, Test F1=0.6869
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=12.15s, Train Loss=0.4691, Val Loss=0.4514, Val F1=0.6827, Test Loss=0.4673, Test F1=0.6913
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=12.15s, Train Loss=0.4655, Val Loss=0.4512, Val F1=0.6882, Test Loss=0.4672, Test F1=0.6884
Validation loss decreased (-0.685155 --> -0.688207).  Saving model ...
[Epoch 09/20], Time=12.18s, Train Loss=0.4624, Val Loss=0.4446, Val F1=0.6848, Test Loss=0.4643, Test F1=0.6875
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=12.13s, Train Loss=0.4654, Val Loss=0.4442, Val F1=0.6866, Test Loss=0.4642, Test F1=0.6873
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=12.22s, Train Loss=0.4646, Val Loss=0.4466, Val F1=0.6825, Test Loss=0.4657, Test F1=0.6894
EarlyStopping counter: 3 out of 5
[Epoch 12/20], Time=12.24s, Train Loss=0.4625, Val Loss=0.4517, Val F1=0.6891, Test Loss=0.4662, Test F1=0.6889
Validation loss decreased (-0.688207 --> -0.689103).  Saving model ...
[Epoch 13/20], Time=12.25s, Train Loss=0.4524, Val Loss=0.4511, Val F1=0.6794, Test Loss=0.4719, Test F1=0.6641
EarlyStopping counter: 1 out of 5
[Epoch 14/20], Time=12.26s, Train Loss=0.4525, Val Loss=0.4475, Val F1=0.6815, Test Loss=0.4663, Test F1=0.6913
EarlyStopping counter: 2 out of 5
[Epoch 15/20], Time=12.25s, Train Loss=0.4581, Val Loss=0.4419, Val F1=0.6846, Test Loss=0.4617, Test F1=0.6856
EarlyStopping counter: 3 out of 5
[Epoch 16/20], Time=12.23s, Train Loss=0.4561, Val Loss=0.4486, Val F1=0.6834, Test Loss=0.4632, Test F1=0.6885
EarlyStopping counter: 4 out of 5
[Epoch 17/20], Time=12.24s, Train Loss=0.4535, Val Loss=0.4515, Val F1=0.6776, Test Loss=0.4693, Test F1=0.6824
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_55_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_55_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7986906710310966
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_55_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:17:29,4,55,0.6891,0.8306,0.6847,0.6935,32,0.000231,512,2,2,6,0.382568,16,5,0.43,0.4,0.7089,51,0.6832,0.8271,0.6667,0.7005,0.0059,False,OK

[I 2026-07-08 21:17:29,322] Trial 55 finished with value: 0.6891025641025641 and parameters: {'lr': 0.0002310175486021592, 'd_model': 32, 'd_ff': 512, 'e_layers': 2, 'top_k': 2, 'dropout': 0.3825679721198923, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_56     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0017898065289489828     --e_layers 2     --d_model 128     --d_ff 8     --top_k 2     --num_kernels 6     --dropout 0.31932938207084616     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 8
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.31932938207084616
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0017898065289489828
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_56
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_56_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=8.35s, Train Loss=0.5366, Val Loss=0.4720, Val F1=0.6697, Test Loss=0.4840, Test F1=0.6699
Validation loss decreased (inf --> -0.669670).  Saving model ...
[Epoch 02/20], Time=7.34s, Train Loss=0.4813, Val Loss=0.4595, Val F1=0.6786, Test Loss=0.4709, Test F1=0.6789
Validation loss decreased (-0.669670 --> -0.678571).  Saving model ...
[Epoch 03/20], Time=7.16s, Train Loss=0.4764, Val Loss=0.4695, Val F1=0.6838, Test Loss=0.4785, Test F1=0.6769
Validation loss decreased (-0.678571 --> -0.683849).  Saving model ...
[Epoch 04/20], Time=7.29s, Train Loss=0.4807, Val Loss=0.4489, Val F1=0.6900, Test Loss=0.4687, Test F1=0.6749
Validation loss decreased (-0.683849 --> -0.689984).  Saving model ...
[Epoch 05/20], Time=7.23s, Train Loss=0.4648, Val Loss=0.4556, Val F1=0.6782, Test Loss=0.4748, Test F1=0.6885
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=7.29s, Train Loss=0.4646, Val Loss=0.4660, Val F1=0.6639, Test Loss=0.4826, Test F1=0.6520
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=7.37s, Train Loss=0.4656, Val Loss=0.4466, Val F1=0.6995, Test Loss=0.4593, Test F1=0.6938
Validation loss decreased (-0.689984 --> -0.699523).  Saving model ...
[Epoch 08/20], Time=7.16s, Train Loss=0.4622, Val Loss=0.4351, Val F1=0.6944, Test Loss=0.4572, Test F1=0.6991
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=7.39s, Train Loss=0.4507, Val Loss=0.4432, Val F1=0.6902, Test Loss=0.4542, Test F1=0.7062
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=7.26s, Train Loss=0.4530, Val Loss=0.4370, Val F1=0.6868, Test Loss=0.4492, Test F1=0.7019
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=7.31s, Train Loss=0.4454, Val Loss=0.4302, Val F1=0.7045, Test Loss=0.4534, Test F1=0.6919
Validation loss decreased (-0.699523 --> -0.704508).  Saving model ...
[Epoch 12/20], Time=7.17s, Train Loss=0.4449, Val Loss=0.4481, Val F1=0.6888, Test Loss=0.4718, Test F1=0.6854
EarlyStopping counter: 1 out of 5
[Epoch 13/20], Time=7.25s, Train Loss=0.4407, Val Loss=0.4544, Val F1=0.6902, Test Loss=0.4688, Test F1=0.7059
EarlyStopping counter: 2 out of 5
[Epoch 14/20], Time=7.24s, Train Loss=0.4315, Val Loss=0.4603, Val F1=0.6780, Test Loss=0.4678, Test F1=0.7001
EarlyStopping counter: 3 out of 5
[Epoch 15/20], Time=7.19s, Train Loss=0.4306, Val Loss=0.4670, Val F1=0.6978, Test Loss=0.4839, Test F1=0.6842
EarlyStopping counter: 4 out of 5
[Epoch 16/20], Time=7.29s, Train Loss=0.4318, Val Loss=0.4449, Val F1=0.6908, Test Loss=0.4607, Test F1=0.6884
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_56_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_56_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7986906710310966
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_56_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:20:18,4,56,0.7045,0.846,0.672,0.7404,128,0.00179,8,2,2,6,0.319329,16,5,0.39,0.31,0.7089,51,0.6667,0.8329,0.6209,0.7198,0.0378,False,OK

[I 2026-07-08 21:20:18,464] Trial 56 finished with value: 0.7045075125208681 and parameters: {'lr': 0.0017898065289489828, 'd_model': 128, 'd_ff': 8, 'e_layers': 2, 'top_k': 2, 'dropout': 0.31932938207084616, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_57     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0005985401380270111     --e_layers 2     --d_model 64     --d_ff 32     --top_k 2     --num_kernels 4     --dropout 0.3438966303636909     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.3438966303636909
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0005985401380270111
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_57
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_57_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.60s, Train Loss=0.5442, Val Loss=0.4727, Val F1=0.6708, Test Loss=0.4783, Test F1=0.6768
Validation loss decreased (inf --> -0.670846).  Saving model ...
[Epoch 02/20], Time=10.43s, Train Loss=0.4814, Val Loss=0.4732, Val F1=0.6752, Test Loss=0.4856, Test F1=0.6805
Validation loss decreased (-0.670846 --> -0.675200).  Saving model ...
[Epoch 03/20], Time=10.58s, Train Loss=0.4722, Val Loss=0.4585, Val F1=0.6870, Test Loss=0.4785, Test F1=0.6803
Validation loss decreased (-0.675200 --> -0.686998).  Saving model ...
[Epoch 04/20], Time=10.63s, Train Loss=0.4656, Val Loss=0.4858, Val F1=0.6826, Test Loss=0.5019, Test F1=0.6922
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=10.45s, Train Loss=0.4644, Val Loss=0.4638, Val F1=0.6839, Test Loss=0.4836, Test F1=0.6835
EarlyStopping counter: 2 out of 5
[Epoch 06/20], Time=10.52s, Train Loss=0.4574, Val Loss=0.4535, Val F1=0.6893, Test Loss=0.4713, Test F1=0.6857
Validation loss decreased (-0.686998 --> -0.689335).  Saving model ...
[Epoch 07/20], Time=10.34s, Train Loss=0.4600, Val Loss=0.4504, Val F1=0.6812, Test Loss=0.4673, Test F1=0.6834
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=10.35s, Train Loss=0.4515, Val Loss=0.4602, Val F1=0.6780, Test Loss=0.4671, Test F1=0.6849
EarlyStopping counter: 2 out of 5
[Epoch 09/20], Time=10.37s, Train Loss=0.4488, Val Loss=0.4539, Val F1=0.6961, Test Loss=0.4657, Test F1=0.6955
Validation loss decreased (-0.689335 --> -0.696063).  Saving model ...
[Epoch 10/20], Time=10.21s, Train Loss=0.4419, Val Loss=0.4441, Val F1=0.7035, Test Loss=0.4530, Test F1=0.7063
Validation loss decreased (-0.696063 --> -0.703470).  Saving model ...
[Epoch 11/20], Time=10.41s, Train Loss=0.4428, Val Loss=0.4356, Val F1=0.6985, Test Loss=0.4486, Test F1=0.7018
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=10.43s, Train Loss=0.4389, Val Loss=0.4609, Val F1=0.6887, Test Loss=0.4635, Test F1=0.7084
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=10.43s, Train Loss=0.4331, Val Loss=0.4500, Val F1=0.6947, Test Loss=0.4702, Test F1=0.6908
EarlyStopping counter: 3 out of 5
[Epoch 14/20], Time=10.63s, Train Loss=0.4358, Val Loss=0.4351, Val F1=0.6966, Test Loss=0.4496, Test F1=0.7037
EarlyStopping counter: 4 out of 5
[Epoch 15/20], Time=10.42s, Train Loss=0.4334, Val Loss=0.4393, Val F1=0.6971, Test Loss=0.4572, Test F1=0.7068
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_57_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_57_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8036006546644845
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_57_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:23:49,4,57,0.7035,0.8382,0.7102,0.6969,64,0.000599,32,2,2,4,0.343897,8,5,0.27,0.24,0.7089,51,0.7033,0.8406,0.6997,0.7069,0.0001,False,OK

[I 2026-07-08 21:23:49,131] Trial 57 finished with value: 0.7034700315457413 and parameters: {'lr': 0.0005985401380270111, 'd_model': 64, 'd_ff': 32, 'e_layers': 2, 'top_k': 2, 'dropout': 0.3438966303636909, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_58     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0008704471398408262     --e_layers 3     --d_model 128     --d_ff 128     --top_k 2     --num_kernels 3     --dropout 0.0035854769447998397     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.0035854769447998397
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0008704471398408262
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_58
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_58_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.75s, Train Loss=0.4983, Val Loss=0.4508, Val F1=0.6912, Test Loss=0.4655, Test F1=0.6819
Validation loss decreased (inf --> -0.691244).  Saving model ...
[Epoch 02/20], Time=12.72s, Train Loss=0.4715, Val Loss=0.4587, Val F1=0.6857, Test Loss=0.4748, Test F1=0.6698
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=12.77s, Train Loss=0.4562, Val Loss=0.4559, Val F1=0.6808, Test Loss=0.4759, Test F1=0.6876
EarlyStopping counter: 2 out of 5
[Epoch 04/20], Time=12.98s, Train Loss=0.4512, Val Loss=0.4613, Val F1=0.6771, Test Loss=0.4741, Test F1=0.6764
EarlyStopping counter: 3 out of 5
[Epoch 05/20], Time=12.85s, Train Loss=0.4521, Val Loss=0.4741, Val F1=0.7011, Test Loss=0.4934, Test F1=0.7011
Validation loss decreased (-0.691244 --> -0.701131).  Saving model ...
[Epoch 06/20], Time=12.70s, Train Loss=0.4386, Val Loss=0.4472, Val F1=0.6868, Test Loss=0.4648, Test F1=0.6898
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=12.76s, Train Loss=0.4301, Val Loss=0.4599, Val F1=0.6904, Test Loss=0.4671, Test F1=0.7012
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=12.76s, Train Loss=0.4200, Val Loss=0.4600, Val F1=0.6966, Test Loss=0.4598, Test F1=0.7024
EarlyStopping counter: 3 out of 5
[Epoch 09/20], Time=12.80s, Train Loss=0.4133, Val Loss=0.4810, Val F1=0.6678, Test Loss=0.4861, Test F1=0.6715
EarlyStopping counter: 4 out of 5
[Epoch 10/20], Time=12.68s, Train Loss=0.4051, Val Loss=0.4549, Val F1=0.6944, Test Loss=0.4834, Test F1=0.6774
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_58_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_58_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7774140752864157
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_58_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:26:51,4,58,0.7011,0.8357,0.6911,0.7115,128,0.00087,128,3,2,3,0.003585,8,5,0.21,0.22,0.7089,51,0.6997,0.8363,0.6819,0.7185,0.0014,False,OK

[I 2026-07-08 21:26:51,774] Trial 58 finished with value: 0.7011308562197092 and parameters: {'lr': 0.0008704471398408262, 'd_model': 128, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.0035854769447998397, 'batch_size': 8, 'patience': 5, 'num_kernels': 3}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_59     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0018589010703293344     --e_layers 3     --d_model 4     --d_ff 4     --top_k 2     --num_kernels 4     --dropout 0.025051036800327095     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 4
d_layers                 : 1
d_model                  : 4
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.025051036800327095
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0018589010703293344
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_59
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_59_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.90s, Train Loss=0.6143, Val Loss=0.4956, Val F1=0.6461, Test Loss=0.5029, Test F1=0.6413
Validation loss decreased (inf --> -0.646098).  Saving model ...
[Epoch 02/20], Time=13.01s, Train Loss=0.4949, Val Loss=0.4608, Val F1=0.6713, Test Loss=0.4782, Test F1=0.6635
Validation loss decreased (-0.646098 --> -0.671280).  Saving model ...
[Epoch 03/20], Time=13.09s, Train Loss=0.4750, Val Loss=0.4619, Val F1=0.6803, Test Loss=0.4833, Test F1=0.6643
Validation loss decreased (-0.671280 --> -0.680342).  Saving model ...
[Epoch 04/20], Time=12.93s, Train Loss=0.4716, Val Loss=0.4505, Val F1=0.6815, Test Loss=0.4731, Test F1=0.6613
Validation loss decreased (-0.680342 --> -0.681548).  Saving model ...
[Epoch 05/20], Time=12.93s, Train Loss=0.4673, Val Loss=0.4535, Val F1=0.6839, Test Loss=0.4813, Test F1=0.6667
Validation loss decreased (-0.681548 --> -0.683871).  Saving model ...
[Epoch 06/20], Time=12.92s, Train Loss=0.4590, Val Loss=0.4544, Val F1=0.6768, Test Loss=0.4819, Test F1=0.6675
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=12.90s, Train Loss=0.4565, Val Loss=0.4444, Val F1=0.6878, Test Loss=0.4643, Test F1=0.6853
Validation loss decreased (-0.683871 --> -0.687797).  Saving model ...
[Epoch 08/20], Time=12.76s, Train Loss=0.4545, Val Loss=0.4450, Val F1=0.6902, Test Loss=0.4677, Test F1=0.6889
Validation loss decreased (-0.687797 --> -0.690209).  Saving model ...
[Epoch 09/20], Time=12.81s, Train Loss=0.4521, Val Loss=0.4456, Val F1=0.6903, Test Loss=0.4690, Test F1=0.6822
Validation loss decreased (-0.690209 --> -0.690323).  Saving model ...
[Epoch 10/20], Time=12.82s, Train Loss=0.4484, Val Loss=0.4481, Val F1=0.6962, Test Loss=0.4680, Test F1=0.6941
Validation loss decreased (-0.690323 --> -0.696203).  Saving model ...
[Epoch 11/20], Time=12.97s, Train Loss=0.4478, Val Loss=0.4497, Val F1=0.6939, Test Loss=0.4779, Test F1=0.6855
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=12.90s, Train Loss=0.4420, Val Loss=0.4500, Val F1=0.6877, Test Loss=0.4704, Test F1=0.6874
EarlyStopping counter: 2 out of 5
[Epoch 13/20], Time=13.05s, Train Loss=0.4450, Val Loss=0.4375, Val F1=0.6939, Test Loss=0.4626, Test F1=0.6886
EarlyStopping counter: 3 out of 5
[Epoch 14/20], Time=12.95s, Train Loss=0.4406, Val Loss=0.4436, Val F1=0.6856, Test Loss=0.4651, Test F1=0.6806
EarlyStopping counter: 4 out of 5
[Epoch 15/20], Time=12.84s, Train Loss=0.4420, Val Loss=0.4350, Val F1=0.6903, Test Loss=0.4580, Test F1=0.6905
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_59_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_59_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.806873977086743
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_59_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:31:00,4,59,0.6962,0.835,0.7006,0.6918,4,0.001859,4,3,2,4,0.025051,8,5,0.43,0.41,0.7089,51,0.69,0.8291,0.6768,0.7037,0.0062,False,OK

[I 2026-07-08 21:31:00,450] Trial 59 finished with value: 0.6962025316455697 and parameters: {'lr': 0.0018589010703293344, 'd_model': 4, 'd_ff': 4, 'e_layers': 3, 'top_k': 2, 'dropout': 0.025051036800327095, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_60     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00023636959748055836     --e_layers 2     --d_model 64     --d_ff 2     --top_k 2     --num_kernels 6     --dropout 0.04582346030868675     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 2
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.04582346030868675
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00023636959748055836
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_60
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_60_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.42s, Train Loss=0.5682, Val Loss=0.4944, Val F1=0.6419, Test Loss=0.4963, Test F1=0.6451
Validation loss decreased (inf --> -0.641935).  Saving model ...
[Epoch 02/20], Time=12.44s, Train Loss=0.4928, Val Loss=0.4655, Val F1=0.6734, Test Loss=0.4769, Test F1=0.6667
Validation loss decreased (-0.641935 --> -0.673401).  Saving model ...
[Epoch 03/20], Time=12.54s, Train Loss=0.4735, Val Loss=0.4570, Val F1=0.6816, Test Loss=0.4717, Test F1=0.6748
Validation loss decreased (-0.673401 --> -0.681600).  Saving model ...
[Epoch 04/20], Time=12.40s, Train Loss=0.4639, Val Loss=0.4540, Val F1=0.6854, Test Loss=0.4711, Test F1=0.6760
Validation loss decreased (-0.681600 --> -0.685358).  Saving model ...
[Epoch 05/20], Time=12.48s, Train Loss=0.4583, Val Loss=0.4547, Val F1=0.6824, Test Loss=0.4697, Test F1=0.6816
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=12.46s, Train Loss=0.4552, Val Loss=0.4619, Val F1=0.6814, Test Loss=0.4725, Test F1=0.6843
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=12.46s, Train Loss=0.4519, Val Loss=0.4650, Val F1=0.6835, Test Loss=0.4799, Test F1=0.6891
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=12.54s, Train Loss=0.4517, Val Loss=0.4535, Val F1=0.6827, Test Loss=0.4672, Test F1=0.6914
EarlyStopping counter: 4 out of 5
[Epoch 09/20], Time=12.37s, Train Loss=0.4463, Val Loss=0.4578, Val F1=0.6827, Test Loss=0.4703, Test F1=0.6744
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_60_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_60_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7913256955810147
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_60_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:33:46,4,60,0.6854,0.829,0.7006,0.6707,64,0.000236,2,2,2,6,0.045823,8,5,0.32,0.23,0.7089,51,0.6709,0.8221,0.6667,0.6753,0.0144,False,OK

[I 2026-07-08 21:33:46,968] Trial 60 finished with value: 0.6853582554517134 and parameters: {'lr': 0.00023636959748055836, 'd_model': 64, 'd_ff': 2, 'e_layers': 2, 'top_k': 2, 'dropout': 0.04582346030868675, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_61     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0009266422447015222     --e_layers 3     --d_model 48     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.33546272549320005     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.33546272549320005
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0009266422447015222
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_61
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_61_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.62s, Train Loss=0.5497, Val Loss=0.4688, Val F1=0.6709, Test Loss=0.4831, Test F1=0.6764
Validation loss decreased (inf --> -0.670866).  Saving model ...
[Epoch 02/20], Time=10.36s, Train Loss=0.4908, Val Loss=0.4705, Val F1=0.6763, Test Loss=0.4874, Test F1=0.6793
Validation loss decreased (-0.670866 --> -0.676282).  Saving model ...
[Epoch 03/20], Time=10.37s, Train Loss=0.4799, Val Loss=0.4509, Val F1=0.6791, Test Loss=0.4769, Test F1=0.6659
Validation loss decreased (-0.676282 --> -0.679070).  Saving model ...
[Epoch 04/20], Time=10.44s, Train Loss=0.4657, Val Loss=0.4557, Val F1=0.6918, Test Loss=0.4780, Test F1=0.6742
Validation loss decreased (-0.679070 --> -0.691824).  Saving model ...
[Epoch 05/20], Time=10.41s, Train Loss=0.4652, Val Loss=0.4598, Val F1=0.6886, Test Loss=0.4799, Test F1=0.6872
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=10.39s, Train Loss=0.4687, Val Loss=0.4515, Val F1=0.6897, Test Loss=0.4745, Test F1=0.6850
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=10.25s, Train Loss=0.4572, Val Loss=0.4436, Val F1=0.6948, Test Loss=0.4577, Test F1=0.6987
Validation loss decreased (-0.691824 --> -0.694836).  Saving model ...
[Epoch 08/20], Time=10.40s, Train Loss=0.4543, Val Loss=0.4438, Val F1=0.6884, Test Loss=0.4565, Test F1=0.6830
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=10.32s, Train Loss=0.4510, Val Loss=0.4440, Val F1=0.6886, Test Loss=0.4551, Test F1=0.6968
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=10.42s, Train Loss=0.4472, Val Loss=0.4281, Val F1=0.6991, Test Loss=0.4422, Test F1=0.7087
Validation loss decreased (-0.694836 --> -0.699099).  Saving model ...
[Epoch 11/20], Time=10.43s, Train Loss=0.4470, Val Loss=0.4455, Val F1=0.6862, Test Loss=0.4729, Test F1=0.6915
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=10.35s, Train Loss=0.4427, Val Loss=0.4406, Val F1=0.7000, Test Loss=0.4598, Test F1=0.6969
Validation loss decreased (-0.699099 --> -0.700000).  Saving model ...
[Epoch 13/20], Time=10.28s, Train Loss=0.4396, Val Loss=0.4559, Val F1=0.7040, Test Loss=0.4875, Test F1=0.7000
Validation loss decreased (-0.700000 --> -0.704000).  Saving model ...
[Epoch 14/20], Time=10.45s, Train Loss=0.4409, Val Loss=0.4540, Val F1=0.6997, Test Loss=0.4704, Test F1=0.6960
EarlyStopping counter: 1 out of 5
[Epoch 15/20], Time=10.41s, Train Loss=0.4331, Val Loss=0.4477, Val F1=0.6865, Test Loss=0.4592, Test F1=0.6948
EarlyStopping counter: 2 out of 5
[Epoch 16/20], Time=10.31s, Train Loss=0.4357, Val Loss=0.4433, Val F1=0.6955, Test Loss=0.4684, Test F1=0.6832
EarlyStopping counter: 3 out of 5
[Epoch 17/20], Time=10.39s, Train Loss=0.4369, Val Loss=0.4490, Val F1=0.6851, Test Loss=0.4660, Test F1=0.7037
EarlyStopping counter: 4 out of 5
[Epoch 18/20], Time=10.37s, Train Loss=0.4294, Val Loss=0.4426, Val F1=0.6903, Test Loss=0.4568, Test F1=0.7026
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_61_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_61_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8085106382978723
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_61_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:37:48,4,61,0.704,0.8426,0.7006,0.7074,48,0.000927,128,3,2,6,0.335463,16,5,0.29,0.37,0.7089,51,0.6923,0.8296,0.687,0.6977,0.0117,False,OK

[I 2026-07-08 21:37:48,442] Trial 61 finished with value: 0.704 and parameters: {'lr': 0.0009266422447015222, 'd_model': 48, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.33546272549320005, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_62     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 3     --batch_size 8     --train_epochs 20     --learning_rate 0.0024199133397444484     --e_layers 2     --d_model 128     --d_ff 128     --top_k 2     --num_kernels 4     --dropout 0.014431850186613679     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.014431850186613679
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0024199133397444484
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_62
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 3
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_62_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.69s, Train Loss=0.5031, Val Loss=0.4865, Val F1=0.6667, Test Loss=0.4964, Test F1=0.6715
Validation loss decreased (inf --> -0.666667).  Saving model ...
[Epoch 02/20], Time=10.70s, Train Loss=0.4835, Val Loss=0.4640, Val F1=0.6775, Test Loss=0.4745, Test F1=0.6902
Validation loss decreased (-0.666667 --> -0.677536).  Saving model ...
[Epoch 03/20], Time=10.91s, Train Loss=0.4779, Val Loss=0.4595, Val F1=0.6724, Test Loss=0.4829, Test F1=0.6634
EarlyStopping counter: 1 out of 3
[Epoch 04/20], Time=11.01s, Train Loss=0.4744, Val Loss=0.4707, Val F1=0.6656, Test Loss=0.4773, Test F1=0.6710
EarlyStopping counter: 2 out of 3
[Epoch 05/20], Time=10.92s, Train Loss=0.4620, Val Loss=0.5158, Val F1=0.6732, Test Loss=0.5444, Test F1=0.6824
EarlyStopping counter: 3 out of 3
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_62_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_62_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.792962356792144
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_62_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:39:37,4,62,0.6775,0.8123,0.5955,0.7857,128,0.00242,128,2,2,4,0.014432,8,3,0.43,0.3,0.7089,51,0.6437,0.8108,0.57,0.7393,0.0339,False,OK

[I 2026-07-08 21:39:37,286] Trial 62 finished with value: 0.677536231884058 and parameters: {'lr': 0.0024199133397444484, 'd_model': 128, 'd_ff': 128, 'e_layers': 2, 'top_k': 2, 'dropout': 0.014431850186613679, 'batch_size': 8, 'patience': 3, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_63     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 16     --train_epochs 20     --learning_rate 0.0007354389084760041     --e_layers 2     --d_model 32     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.1373295454577035     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.1373295454577035
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0007354389084760041
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_63
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_63_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=8.76s, Train Loss=0.5230, Val Loss=0.4597, Val F1=0.6774, Test Loss=0.4770, Test F1=0.6798
Validation loss decreased (inf --> -0.677368).  Saving model ...
[Epoch 02/20], Time=7.55s, Train Loss=0.4713, Val Loss=0.4608, Val F1=0.6761, Test Loss=0.4706, Test F1=0.6793
EarlyStopping counter: 1 out of 4
[Epoch 03/20], Time=7.63s, Train Loss=0.4582, Val Loss=0.4496, Val F1=0.6871, Test Loss=0.4669, Test F1=0.6803
Validation loss decreased (-0.677368 --> -0.687097).  Saving model ...
[Epoch 04/20], Time=7.55s, Train Loss=0.4621, Val Loss=0.4438, Val F1=0.6823, Test Loss=0.4598, Test F1=0.6888
EarlyStopping counter: 1 out of 4
[Epoch 05/20], Time=7.55s, Train Loss=0.4566, Val Loss=0.4532, Val F1=0.6785, Test Loss=0.4741, Test F1=0.6711
EarlyStopping counter: 2 out of 4
[Epoch 06/20], Time=7.66s, Train Loss=0.4512, Val Loss=0.4571, Val F1=0.6791, Test Loss=0.4765, Test F1=0.6837
EarlyStopping counter: 3 out of 4
[Epoch 07/20], Time=7.55s, Train Loss=0.4469, Val Loss=0.4419, Val F1=0.6980, Test Loss=0.4608, Test F1=0.6980
Validation loss decreased (-0.687097 --> -0.697966).  Saving model ...
[Epoch 08/20], Time=7.70s, Train Loss=0.4434, Val Loss=0.4391, Val F1=0.6942, Test Loss=0.4530, Test F1=0.7098
EarlyStopping counter: 1 out of 4
[Epoch 09/20], Time=7.57s, Train Loss=0.4407, Val Loss=0.4416, Val F1=0.6912, Test Loss=0.4546, Test F1=0.7044
EarlyStopping counter: 2 out of 4
[Epoch 10/20], Time=7.70s, Train Loss=0.4388, Val Loss=0.4401, Val F1=0.6944, Test Loss=0.4557, Test F1=0.7099
EarlyStopping counter: 3 out of 4
[Epoch 11/20], Time=7.67s, Train Loss=0.4324, Val Loss=0.4557, Val F1=0.6883, Test Loss=0.4614, Test F1=0.6967
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_63_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_63_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8011456628477905
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_63_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:41:53,4,63,0.698,0.8372,0.7102,0.6862,32,0.000735,128,2,2,6,0.13733,16,4,0.32,0.32,0.7089,51,0.698,0.833,0.6997,0.6962,-0.0,False,OK

[I 2026-07-08 21:41:53,439] Trial 63 finished with value: 0.6979655712050078 and parameters: {'lr': 0.0007354389084760041, 'd_model': 32, 'd_ff': 128, 'e_layers': 2, 'top_k': 2, 'dropout': 0.1373295454577035, 'batch_size': 16, 'patience': 4, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_64     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.00032078019496735785     --e_layers 3     --d_model 32     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.28765860925800085     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.28765860925800085
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00032078019496735785
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_64
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_64_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.51s, Train Loss=0.6268, Val Loss=0.4892, Val F1=0.6424, Test Loss=0.4953, Test F1=0.6527
Validation loss decreased (inf --> -0.642361).  Saving model ...
[Epoch 02/20], Time=10.31s, Train Loss=0.4944, Val Loss=0.4724, Val F1=0.6698, Test Loss=0.4883, Test F1=0.6675
Validation loss decreased (-0.642361 --> -0.669826).  Saving model ...
[Epoch 03/20], Time=10.44s, Train Loss=0.4865, Val Loss=0.4609, Val F1=0.6699, Test Loss=0.4755, Test F1=0.6715
Validation loss decreased (-0.669826 --> -0.669903).  Saving model ...
[Epoch 04/20], Time=10.40s, Train Loss=0.4738, Val Loss=0.4536, Val F1=0.6822, Test Loss=0.4682, Test F1=0.6767
Validation loss decreased (-0.669903 --> -0.682196).  Saving model ...
[Epoch 05/20], Time=10.38s, Train Loss=0.4651, Val Loss=0.4547, Val F1=0.6795, Test Loss=0.4638, Test F1=0.6913
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=10.37s, Train Loss=0.4618, Val Loss=0.4529, Val F1=0.6795, Test Loss=0.4651, Test F1=0.6756
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=10.46s, Train Loss=0.4606, Val Loss=0.4526, Val F1=0.6806, Test Loss=0.4687, Test F1=0.6753
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=10.37s, Train Loss=0.4559, Val Loss=0.4524, Val F1=0.6813, Test Loss=0.4694, Test F1=0.6770
EarlyStopping counter: 4 out of 5
[Epoch 09/20], Time=10.48s, Train Loss=0.4590, Val Loss=0.4500, Val F1=0.6824, Test Loss=0.4634, Test F1=0.6869
Validation loss decreased (-0.682196 --> -0.682390).  Saving model ...
[Epoch 10/20], Time=10.44s, Train Loss=0.4570, Val Loss=0.4560, Val F1=0.6797, Test Loss=0.4674, Test F1=0.6893
EarlyStopping counter: 1 out of 5
[Epoch 11/20], Time=10.49s, Train Loss=0.4538, Val Loss=0.4484, Val F1=0.6819, Test Loss=0.4646, Test F1=0.6912
EarlyStopping counter: 2 out of 5
[Epoch 12/20], Time=10.36s, Train Loss=0.4526, Val Loss=0.4567, Val F1=0.6773, Test Loss=0.4661, Test F1=0.6866
EarlyStopping counter: 3 out of 5
[Epoch 13/20], Time=10.45s, Train Loss=0.4480, Val Loss=0.4468, Val F1=0.6840, Test Loss=0.4618, Test F1=0.6914
Validation loss decreased (-0.682390 --> -0.684039).  Saving model ...
[Epoch 14/20], Time=10.43s, Train Loss=0.4539, Val Loss=0.4520, Val F1=0.6774, Test Loss=0.4604, Test F1=0.6878
EarlyStopping counter: 1 out of 5
[Epoch 15/20], Time=10.48s, Train Loss=0.4470, Val Loss=0.4485, Val F1=0.6809, Test Loss=0.4623, Test F1=0.7024
EarlyStopping counter: 2 out of 5
[Epoch 16/20], Time=10.36s, Train Loss=0.4479, Val Loss=0.4447, Val F1=0.6873, Test Loss=0.4599, Test F1=0.6972
Validation loss decreased (-0.684039 --> -0.687296).  Saving model ...
[Epoch 17/20], Time=10.26s, Train Loss=0.4429, Val Loss=0.4451, Val F1=0.6921, Test Loss=0.4581, Test F1=0.6987
Validation loss decreased (-0.687296 --> -0.692063).  Saving model ...
[Epoch 18/20], Time=10.29s, Train Loss=0.4401, Val Loss=0.4361, Val F1=0.6921, Test Loss=0.4509, Test F1=0.7003
Validation loss decreased (-0.692063 --> -0.692063).  Saving model ...
[Epoch 19/20], Time=10.42s, Train Loss=0.4379, Val Loss=0.4345, Val F1=0.6947, Test Loss=0.4525, Test F1=0.7051
Validation loss decreased (-0.692063 --> -0.694669).  Saving model ...
[Epoch 20/20], Time=10.43s, Train Loss=0.4399, Val Loss=0.4370, Val F1=0.6945, Test Loss=0.4545, Test F1=0.7009
EarlyStopping counter: 1 out of 5
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_64_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_64_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8052373158756138
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_64_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:46:16,4,64,0.6947,0.8397,0.6847,0.7049,32,0.000321,128,3,2,6,0.287659,16,5,0.32,0.25,0.7089,51,0.6975,0.8405,0.6718,0.7253,-0.0028,False,OK

[I 2026-07-08 21:46:16,837] Trial 64 finished with value: 0.6946688206785138 and parameters: {'lr': 0.00032078019496735785, 'd_model': 32, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.28765860925800085, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_65     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 16     --train_epochs 20     --learning_rate 0.0011599794978058853     --e_layers 2     --d_model 32     --d_ff 4     --top_k 2     --num_kernels 4     --dropout 0.2569105461807418     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 4
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2569105461807418
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0011599794978058853
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_65
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_65_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.07s, Train Loss=0.5854, Val Loss=0.4847, Val F1=0.6465, Test Loss=0.4863, Test F1=0.6545
Validation loss decreased (inf --> -0.646465).  Saving model ...
[Epoch 02/20], Time=5.89s, Train Loss=0.5024, Val Loss=0.4679, Val F1=0.6727, Test Loss=0.4761, Test F1=0.6730
Validation loss decreased (-0.646465 --> -0.672700).  Saving model ...
[Epoch 03/20], Time=5.87s, Train Loss=0.4838, Val Loss=0.4562, Val F1=0.6789, Test Loss=0.4673, Test F1=0.6804
Validation loss decreased (-0.672700 --> -0.678899).  Saving model ...
[Epoch 04/20], Time=5.82s, Train Loss=0.4767, Val Loss=0.4547, Val F1=0.6780, Test Loss=0.4651, Test F1=0.6820
EarlyStopping counter: 1 out of 4
[Epoch 05/20], Time=5.75s, Train Loss=0.4663, Val Loss=0.4561, Val F1=0.6835, Test Loss=0.4682, Test F1=0.6893
Validation loss decreased (-0.678899 --> -0.683544).  Saving model ...
[Epoch 06/20], Time=5.85s, Train Loss=0.4613, Val Loss=0.4522, Val F1=0.6859, Test Loss=0.4675, Test F1=0.6888
Validation loss decreased (-0.683544 --> -0.685921).  Saving model ...
[Epoch 07/20], Time=5.70s, Train Loss=0.4657, Val Loss=0.4474, Val F1=0.6863, Test Loss=0.4623, Test F1=0.6879
Validation loss decreased (-0.685921 --> -0.686335).  Saving model ...
[Epoch 08/20], Time=5.79s, Train Loss=0.4611, Val Loss=0.4467, Val F1=0.6838, Test Loss=0.4609, Test F1=0.6894
EarlyStopping counter: 1 out of 4
[Epoch 09/20], Time=5.71s, Train Loss=0.4522, Val Loss=0.4469, Val F1=0.6823, Test Loss=0.4596, Test F1=0.6815
EarlyStopping counter: 2 out of 4
[Epoch 10/20], Time=5.94s, Train Loss=0.4507, Val Loss=0.4564, Val F1=0.6923, Test Loss=0.4691, Test F1=0.6909
Validation loss decreased (-0.686335 --> -0.692308).  Saving model ...
[Epoch 11/20], Time=5.65s, Train Loss=0.4515, Val Loss=0.4422, Val F1=0.6885, Test Loss=0.4588, Test F1=0.6942
EarlyStopping counter: 1 out of 4
[Epoch 12/20], Time=5.84s, Train Loss=0.4474, Val Loss=0.4391, Val F1=0.6906, Test Loss=0.4570, Test F1=0.6896
EarlyStopping counter: 2 out of 4
[Epoch 13/20], Time=5.78s, Train Loss=0.4537, Val Loss=0.4387, Val F1=0.6927, Test Loss=0.4559, Test F1=0.6850
Validation loss decreased (-0.692308 --> -0.692668).  Saving model ...
[Epoch 14/20], Time=5.74s, Train Loss=0.4443, Val Loss=0.4425, Val F1=0.6883, Test Loss=0.4557, Test F1=0.6867
EarlyStopping counter: 1 out of 4
[Epoch 15/20], Time=5.85s, Train Loss=0.4460, Val Loss=0.4477, Val F1=0.6836, Test Loss=0.4641, Test F1=0.6805
EarlyStopping counter: 2 out of 4
[Epoch 16/20], Time=5.88s, Train Loss=0.4439, Val Loss=0.4456, Val F1=0.6867, Test Loss=0.4567, Test F1=0.6958
EarlyStopping counter: 3 out of 4
[Epoch 17/20], Time=5.93s, Train Loss=0.4424, Val Loss=0.4558, Val F1=0.6931, Test Loss=0.4771, Test F1=0.6896
Validation loss decreased (-0.692668 --> -0.693069).  Saving model ...
[Epoch 18/20], Time=5.87s, Train Loss=0.4465, Val Loss=0.4537, Val F1=0.6949, Test Loss=0.4737, Test F1=0.6825
Validation loss decreased (-0.693069 --> -0.694915).  Saving model ...
[Epoch 19/20], Time=5.89s, Train Loss=0.4446, Val Loss=0.4357, Val F1=0.6963, Test Loss=0.4553, Test F1=0.6996
Validation loss decreased (-0.694915 --> -0.696319).  Saving model ...
[Epoch 20/20], Time=5.81s, Train Loss=0.4468, Val Loss=0.4452, Val F1=0.6784, Test Loss=0.4570, Test F1=0.6807
EarlyStopping counter: 1 out of 4
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_65_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_65_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8036006546644845
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_65_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:49:04,4,65,0.6963,0.8398,0.7229,0.6716,32,0.00116,4,2,2,4,0.256911,16,4,0.26,0.29,0.7089,51,0.6922,0.8337,0.7125,0.6731,0.0041,False,OK

[I 2026-07-08 21:49:04,968] Trial 65 finished with value: 0.696319018404908 and parameters: {'lr': 0.0011599794978058853, 'd_model': 32, 'd_ff': 4, 'e_layers': 2, 'top_k': 2, 'dropout': 0.2569105461807418, 'batch_size': 16, 'patience': 4, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_66     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0002496194227138508     --e_layers 3     --d_model 4     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.07432217856037268     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 4
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.07432217856037268
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0002496194227138508
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_66
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_66_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=19.49s, Train Loss=0.6393, Val Loss=0.5709, Val F1=0.5798, Test Loss=0.5686, Test F1=0.5864
Validation loss decreased (inf --> -0.579760).  Saving model ...
[Epoch 02/20], Time=18.26s, Train Loss=0.5456, Val Loss=0.5049, Val F1=0.6309, Test Loss=0.5084, Test F1=0.6385
Validation loss decreased (-0.579760 --> -0.630934).  Saving model ...
[Epoch 03/20], Time=18.39s, Train Loss=0.5062, Val Loss=0.4821, Val F1=0.6515, Test Loss=0.4919, Test F1=0.6490
Validation loss decreased (-0.630934 --> -0.651540).  Saving model ...
[Epoch 04/20], Time=18.48s, Train Loss=0.4921, Val Loss=0.4764, Val F1=0.6656, Test Loss=0.4881, Test F1=0.6594
Validation loss decreased (-0.651540 --> -0.665605).  Saving model ...
[Epoch 05/20], Time=18.54s, Train Loss=0.4864, Val Loss=0.4707, Val F1=0.6677, Test Loss=0.4817, Test F1=0.6692
Validation loss decreased (-0.665605 --> -0.667747).  Saving model ...
[Epoch 06/20], Time=18.50s, Train Loss=0.4836, Val Loss=0.4674, Val F1=0.6624, Test Loss=0.4808, Test F1=0.6650
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=18.41s, Train Loss=0.4811, Val Loss=0.4655, Val F1=0.6667, Test Loss=0.4770, Test F1=0.6726
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=18.43s, Train Loss=0.4726, Val Loss=0.4642, Val F1=0.6687, Test Loss=0.4776, Test F1=0.6717
Validation loss decreased (-0.667747 --> -0.668740).  Saving model ...
[Epoch 09/20], Time=18.25s, Train Loss=0.4786, Val Loss=0.4616, Val F1=0.6634, Test Loss=0.4779, Test F1=0.6701
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=18.39s, Train Loss=0.4669, Val Loss=0.4592, Val F1=0.6667, Test Loss=0.4758, Test F1=0.6773
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=18.35s, Train Loss=0.4679, Val Loss=0.4567, Val F1=0.6696, Test Loss=0.4778, Test F1=0.6752
Validation loss decreased (-0.668740 --> -0.669565).  Saving model ...
[Epoch 12/20], Time=18.46s, Train Loss=0.4632, Val Loss=0.4588, Val F1=0.6698, Test Loss=0.4723, Test F1=0.6780
Validation loss decreased (-0.669565 --> -0.669782).  Saving model ...
[Epoch 13/20], Time=18.46s, Train Loss=0.4636, Val Loss=0.4539, Val F1=0.6749, Test Loss=0.4729, Test F1=0.6768
Validation loss decreased (-0.669782 --> -0.674923).  Saving model ...
[Epoch 14/20], Time=18.41s, Train Loss=0.4614, Val Loss=0.4575, Val F1=0.6726, Test Loss=0.4728, Test F1=0.6775
EarlyStopping counter: 1 out of 5
[Epoch 15/20], Time=18.48s, Train Loss=0.4666, Val Loss=0.4675, Val F1=0.6698, Test Loss=0.4855, Test F1=0.6830
EarlyStopping counter: 2 out of 5
[Epoch 16/20], Time=18.35s, Train Loss=0.4637, Val Loss=0.4547, Val F1=0.6677, Test Loss=0.4755, Test F1=0.6785
EarlyStopping counter: 3 out of 5
[Epoch 17/20], Time=18.19s, Train Loss=0.4611, Val Loss=0.4563, Val F1=0.6771, Test Loss=0.4735, Test F1=0.6809
Validation loss decreased (-0.674923 --> -0.677067).  Saving model ...
[Epoch 18/20], Time=18.38s, Train Loss=0.4564, Val Loss=0.4530, Val F1=0.6667, Test Loss=0.4758, Test F1=0.6684
EarlyStopping counter: 1 out of 5
[Epoch 19/20], Time=18.52s, Train Loss=0.4562, Val Loss=0.4564, Val F1=0.6657, Test Loss=0.4819, Test F1=0.6719
EarlyStopping counter: 2 out of 5
[Epoch 20/20], Time=18.55s, Train Loss=0.4617, Val Loss=0.4523, Val F1=0.6801, Test Loss=0.4758, Test F1=0.6708
Validation loss decreased (-0.677067 --> -0.680057).  Saving model ...
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_66_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_66_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7978723404255319
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_66_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:56:12,4,66,0.6801,0.834,0.7548,0.6188,4,0.00025,128,3,2,6,0.074322,8,5,0.27,0.33,0.7089,51,0.6461,0.8146,0.7201,0.5859,0.0339,False,OK

[I 2026-07-08 21:56:12,275] Trial 66 finished with value: 0.6800573888091822 and parameters: {'lr': 0.0002496194227138508, 'd_model': 4, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.07432217856037268, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_67     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0014249589646837036     --e_layers 2     --d_model 64     --d_ff 2     --top_k 2     --num_kernels 6     --dropout 0.2666058123961904     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 2
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2666058123961904
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0014249589646837036
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_67
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_67_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.43s, Train Loss=0.5439, Val Loss=0.4665, Val F1=0.6747, Test Loss=0.4795, Test F1=0.6743
Validation loss decreased (inf --> -0.674658).  Saving model ...
[Epoch 02/20], Time=12.45s, Train Loss=0.4907, Val Loss=0.4635, Val F1=0.6805, Test Loss=0.4789, Test F1=0.6756
Validation loss decreased (-0.674658 --> -0.680511).  Saving model ...
[Epoch 03/20], Time=12.35s, Train Loss=0.4751, Val Loss=0.4623, Val F1=0.6733, Test Loss=0.4678, Test F1=0.6827
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=12.60s, Train Loss=0.4721, Val Loss=0.4549, Val F1=0.6875, Test Loss=0.4653, Test F1=0.6897
Validation loss decreased (-0.680511 --> -0.687500).  Saving model ...
[Epoch 05/20], Time=12.63s, Train Loss=0.4672, Val Loss=0.4577, Val F1=0.6894, Test Loss=0.4721, Test F1=0.6885
Validation loss decreased (-0.687500 --> -0.689431).  Saving model ...
[Epoch 06/20], Time=12.71s, Train Loss=0.4649, Val Loss=0.4791, Val F1=0.6854, Test Loss=0.4912, Test F1=0.6865
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=12.51s, Train Loss=0.4630, Val Loss=0.4716, Val F1=0.6871, Test Loss=0.4848, Test F1=0.6935
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=12.48s, Train Loss=0.4609, Val Loss=0.4550, Val F1=0.6924, Test Loss=0.4692, Test F1=0.6947
Validation loss decreased (-0.689431 --> -0.692432).  Saving model ...
[Epoch 09/20], Time=12.40s, Train Loss=0.4535, Val Loss=0.4688, Val F1=0.6731, Test Loss=0.4792, Test F1=0.6557
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=12.40s, Train Loss=0.4569, Val Loss=0.4547, Val F1=0.6913, Test Loss=0.4698, Test F1=0.6789
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=12.41s, Train Loss=0.4543, Val Loss=0.4537, Val F1=0.6831, Test Loss=0.4683, Test F1=0.6799
EarlyStopping counter: 3 out of 5
[Epoch 12/20], Time=12.60s, Train Loss=0.4509, Val Loss=0.4565, Val F1=0.6807, Test Loss=0.4702, Test F1=0.6872
EarlyStopping counter: 4 out of 5
[Epoch 13/20], Time=12.43s, Train Loss=0.4476, Val Loss=0.4468, Val F1=0.6823, Test Loss=0.4601, Test F1=0.6928
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_67_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_67_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8052373158756138
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_67_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,21:59:49,4,67,0.6924,0.835,0.6847,0.7003,64,0.001425,2,2,2,6,0.266606,8,5,0.29,0.23,0.7089,51,0.6896,0.829,0.6641,0.717,0.0029,False,OK

[I 2026-07-08 21:59:49,510] Trial 67 finished with value: 0.6924315619967794 and parameters: {'lr': 0.0014249589646837036, 'd_model': 64, 'd_ff': 2, 'e_layers': 2, 'top_k': 2, 'dropout': 0.2666058123961904, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_68     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 8     --train_epochs 20     --learning_rate 0.00045061468400676486     --e_layers 3     --d_model 32     --d_ff 64     --top_k 2     --num_kernels 6     --dropout 0.08298516201363292     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.08298516201363292
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00045061468400676486
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_68
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_68_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=18.74s, Train Loss=0.5187, Val Loss=0.4592, Val F1=0.6773, Test Loss=0.4710, Test F1=0.6737
Validation loss decreased (inf --> -0.677266).  Saving model ...
[Epoch 02/20], Time=17.60s, Train Loss=0.4649, Val Loss=0.4634, Val F1=0.6688, Test Loss=0.4722, Test F1=0.6806
EarlyStopping counter: 1 out of 4
[Epoch 03/20], Time=17.80s, Train Loss=0.4581, Val Loss=0.4503, Val F1=0.6882, Test Loss=0.4685, Test F1=0.6870
Validation loss decreased (-0.677266 --> -0.688172).  Saving model ...
[Epoch 04/20], Time=17.50s, Train Loss=0.4531, Val Loss=0.4479, Val F1=0.6831, Test Loss=0.4628, Test F1=0.6914
EarlyStopping counter: 1 out of 4
[Epoch 05/20], Time=17.46s, Train Loss=0.4474, Val Loss=0.4485, Val F1=0.6900, Test Loss=0.4625, Test F1=0.6896
Validation loss decreased (-0.688172 --> -0.689984).  Saving model ...
[Epoch 06/20], Time=17.50s, Train Loss=0.4441, Val Loss=0.4502, Val F1=0.6832, Test Loss=0.4609, Test F1=0.6962
EarlyStopping counter: 1 out of 4
[Epoch 07/20], Time=17.68s, Train Loss=0.4391, Val Loss=0.4481, Val F1=0.6929, Test Loss=0.4630, Test F1=0.6943
Validation loss decreased (-0.689984 --> -0.692913).  Saving model ...
[Epoch 08/20], Time=17.74s, Train Loss=0.4391, Val Loss=0.4395, Val F1=0.6948, Test Loss=0.4612, Test F1=0.6935
Validation loss decreased (-0.692913 --> -0.694805).  Saving model ...
[Epoch 09/20], Time=17.75s, Train Loss=0.4320, Val Loss=0.4361, Val F1=0.6977, Test Loss=0.4601, Test F1=0.7054
Validation loss decreased (-0.694805 --> -0.697674).  Saving model ...
[Epoch 10/20], Time=17.63s, Train Loss=0.4269, Val Loss=0.4300, Val F1=0.6991, Test Loss=0.4524, Test F1=0.7022
Validation loss decreased (-0.697674 --> -0.699060).  Saving model ...
[Epoch 11/20], Time=17.79s, Train Loss=0.4218, Val Loss=0.4397, Val F1=0.6973, Test Loss=0.4560, Test F1=0.6912
EarlyStopping counter: 1 out of 4
[Epoch 12/20], Time=17.75s, Train Loss=0.4226, Val Loss=0.4414, Val F1=0.6958, Test Loss=0.4635, Test F1=0.6854
EarlyStopping counter: 2 out of 4
[Epoch 13/20], Time=17.53s, Train Loss=0.4155, Val Loss=0.4530, Val F1=0.6922, Test Loss=0.4633, Test F1=0.7038
EarlyStopping counter: 3 out of 4
[Epoch 14/20], Time=17.83s, Train Loss=0.4161, Val Loss=0.4417, Val F1=0.7041, Test Loss=0.4563, Test F1=0.7006
Validation loss decreased (-0.699060 --> -0.704132).  Saving model ...
[Epoch 15/20], Time=17.82s, Train Loss=0.4070, Val Loss=0.4414, Val F1=0.6954, Test Loss=0.4684, Test F1=0.6836
EarlyStopping counter: 1 out of 4
[Epoch 16/20], Time=17.65s, Train Loss=0.4104, Val Loss=0.4504, Val F1=0.6916, Test Loss=0.4673, Test F1=0.6952
EarlyStopping counter: 2 out of 4
[Epoch 17/20], Time=17.74s, Train Loss=0.4017, Val Loss=0.4553, Val F1=0.6957, Test Loss=0.4704, Test F1=0.6852
EarlyStopping counter: 3 out of 4
[Epoch 18/20], Time=17.79s, Train Loss=0.4009, Val Loss=0.4500, Val F1=0.6971, Test Loss=0.4680, Test F1=0.6852
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_68_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_68_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8060556464811784
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_68_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:06:05,4,68,0.7041,0.8331,0.6783,0.732,32,0.000451,64,3,2,6,0.082985,8,4,0.45,0.37,0.7089,51,0.6925,0.8325,0.659,0.7296,0.0116,False,OK

[I 2026-07-08 22:06:05,646] Trial 68 finished with value: 0.7041322314049587 and parameters: {'lr': 0.00045061468400676486, 'd_model': 32, 'd_ff': 64, 'e_layers': 3, 'top_k': 2, 'dropout': 0.08298516201363292, 'batch_size': 8, 'patience': 4, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_69     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 16     --train_epochs 20     --learning_rate 0.0006034023249002023     --e_layers 2     --d_model 4     --d_ff 512     --top_k 2     --num_kernels 6     --dropout 0.30252032967929987     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 4
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.30252032967929987
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0006034023249002023
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_69
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_69_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.11s, Train Loss=0.6261, Val Loss=0.5313, Val F1=0.6047, Test Loss=0.5285, Test F1=0.6257
Validation loss decreased (inf --> -0.604720).  Saving model ...
[Epoch 02/20], Time=12.05s, Train Loss=0.5507, Val Loss=0.5079, Val F1=0.6341, Test Loss=0.5123, Test F1=0.6480
Validation loss decreased (-0.604720 --> -0.634146).  Saving model ...
[Epoch 03/20], Time=12.02s, Train Loss=0.5233, Val Loss=0.4866, Val F1=0.6486, Test Loss=0.4906, Test F1=0.6643
Validation loss decreased (-0.634146 --> -0.648649).  Saving model ...
[Epoch 04/20], Time=11.99s, Train Loss=0.5104, Val Loss=0.4795, Val F1=0.6561, Test Loss=0.4868, Test F1=0.6731
Validation loss decreased (-0.648649 --> -0.656051).  Saving model ...
[Epoch 05/20], Time=12.03s, Train Loss=0.4972, Val Loss=0.4797, Val F1=0.6527, Test Loss=0.4809, Test F1=0.6691
EarlyStopping counter: 1 out of 4
[Epoch 06/20], Time=12.03s, Train Loss=0.5032, Val Loss=0.4801, Val F1=0.6572, Test Loss=0.4791, Test F1=0.6762
Validation loss decreased (-0.656051 --> -0.657233).  Saving model ...
[Epoch 07/20], Time=12.07s, Train Loss=0.4930, Val Loss=0.4732, Val F1=0.6606, Test Loss=0.4789, Test F1=0.6691
Validation loss decreased (-0.657233 --> -0.660633).  Saving model ...
[Epoch 08/20], Time=12.21s, Train Loss=0.4884, Val Loss=0.4721, Val F1=0.6710, Test Loss=0.4812, Test F1=0.6782
Validation loss decreased (-0.660633 --> -0.671010).  Saving model ...
[Epoch 09/20], Time=12.16s, Train Loss=0.4890, Val Loss=0.4757, Val F1=0.6525, Test Loss=0.4783, Test F1=0.6723
EarlyStopping counter: 1 out of 4
[Epoch 10/20], Time=12.08s, Train Loss=0.4927, Val Loss=0.4848, Val F1=0.6456, Test Loss=0.4867, Test F1=0.6706
EarlyStopping counter: 2 out of 4
[Epoch 11/20], Time=12.05s, Train Loss=0.4850, Val Loss=0.4659, Val F1=0.6637, Test Loss=0.4757, Test F1=0.6742
EarlyStopping counter: 3 out of 4
[Epoch 12/20], Time=12.07s, Train Loss=0.4829, Val Loss=0.4642, Val F1=0.6698, Test Loss=0.4791, Test F1=0.6774
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_69_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_69_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7896890343698855
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_69_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:09:28,4,69,0.671,0.8091,0.6561,0.6867,4,0.000603,512,2,2,6,0.30252,16,4,0.29,0.24,0.7089,51,0.6632,0.8113,0.6412,0.6866,0.0079,False,OK

[I 2026-07-08 22:09:28,023] Trial 69 finished with value: 0.6710097719869706 and parameters: {'lr': 0.0006034023249002023, 'd_model': 4, 'd_ff': 512, 'e_layers': 2, 'top_k': 2, 'dropout': 0.30252032967929987, 'batch_size': 16, 'patience': 4, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_70     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00219546970438341     --e_layers 2     --d_model 128     --d_ff 32     --top_k 2     --num_kernels 4     --dropout 0.037565811319816456     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.037565811319816456
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00219546970438341
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_70
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_70_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.83s, Train Loss=0.4930, Val Loss=0.4738, Val F1=0.6701, Test Loss=0.4939, Test F1=0.6593
Validation loss decreased (inf --> -0.670085).  Saving model ...
[Epoch 02/20], Time=10.85s, Train Loss=0.4727, Val Loss=0.4450, Val F1=0.6975, Test Loss=0.4595, Test F1=0.6955
Validation loss decreased (-0.670085 --> -0.697509).  Saving model ...
[Epoch 03/20], Time=10.81s, Train Loss=0.4644, Val Loss=0.4639, Val F1=0.7057, Test Loss=0.4839, Test F1=0.6882
Validation loss decreased (-0.697509 --> -0.705696).  Saving model ...
[Epoch 04/20], Time=10.74s, Train Loss=0.4582, Val Loss=0.4645, Val F1=0.6918, Test Loss=0.4812, Test F1=0.6928
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=10.73s, Train Loss=0.4549, Val Loss=0.4619, Val F1=0.7010, Test Loss=0.4811, Test F1=0.7032
EarlyStopping counter: 2 out of 5
[Epoch 06/20], Time=10.64s, Train Loss=0.4497, Val Loss=0.4709, Val F1=0.6918, Test Loss=0.4863, Test F1=0.6979
EarlyStopping counter: 3 out of 5
[Epoch 07/20], Time=10.73s, Train Loss=0.4430, Val Loss=0.4376, Val F1=0.6985, Test Loss=0.4538, Test F1=0.6991
EarlyStopping counter: 4 out of 5
[Epoch 08/20], Time=10.74s, Train Loss=0.4348, Val Loss=0.4590, Val F1=0.6903, Test Loss=0.4835, Test F1=0.6910
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_70_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_70_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8019639934533551
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_70_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:11:48,4,70,0.7057,0.8292,0.7102,0.7013,128,0.002195,32,2,2,4,0.037566,8,5,0.36,0.38,0.7089,51,0.6879,0.8245,0.687,0.6888,0.0178,False,OK

[I 2026-07-08 22:11:48,830] Trial 70 finished with value: 0.7056962025316456 and parameters: {'lr': 0.00219546970438341, 'd_model': 128, 'd_ff': 32, 'e_layers': 2, 'top_k': 2, 'dropout': 0.037565811319816456, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_71     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.002562979139413566     --e_layers 2     --d_model 128     --d_ff 512     --top_k 2     --num_kernels 4     --dropout 0.03855981058944924     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.03855981058944924
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.002562979139413566
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_71
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_71_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.99s, Train Loss=0.5176, Val Loss=0.5670, Val F1=0.6202, Test Loss=0.5890, Test F1=0.6099
Validation loss decreased (inf --> -0.620155).  Saving model ...
[Epoch 02/20], Time=10.87s, Train Loss=0.5072, Val Loss=0.5457, Val F1=0.6576, Test Loss=0.5783, Test F1=0.6606
Validation loss decreased (-0.620155 --> -0.657627).  Saving model ...
[Epoch 03/20], Time=10.99s, Train Loss=0.4921, Val Loss=0.4732, Val F1=0.6700, Test Loss=0.4894, Test F1=0.6702
Validation loss decreased (-0.657627 --> -0.669983).  Saving model ...
[Epoch 04/20], Time=10.84s, Train Loss=0.4746, Val Loss=0.4630, Val F1=0.6687, Test Loss=0.4720, Test F1=0.6761
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=10.59s, Train Loss=0.4673, Val Loss=0.4598, Val F1=0.6703, Test Loss=0.4769, Test F1=0.6649
Validation loss decreased (-0.669983 --> -0.670270).  Saving model ...
[Epoch 06/20], Time=10.62s, Train Loss=0.4597, Val Loss=0.4482, Val F1=0.6724, Test Loss=0.4636, Test F1=0.6783
Validation loss decreased (-0.670270 --> -0.672355).  Saving model ...
[Epoch 07/20], Time=10.78s, Train Loss=0.4562, Val Loss=0.4573, Val F1=0.6656, Test Loss=0.4609, Test F1=0.6814
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=10.79s, Train Loss=0.4539, Val Loss=0.4503, Val F1=0.6759, Test Loss=0.4654, Test F1=0.6852
Validation loss decreased (-0.672355 --> -0.675926).  Saving model ...
[Epoch 09/20], Time=10.96s, Train Loss=0.4489, Val Loss=0.4746, Val F1=0.6720, Test Loss=0.4814, Test F1=0.6796
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=10.90s, Train Loss=0.4445, Val Loss=0.4597, Val F1=0.6862, Test Loss=0.4868, Test F1=0.6822
Validation loss decreased (-0.675926 --> -0.686179).  Saving model ...
[Epoch 11/20], Time=10.92s, Train Loss=0.4488, Val Loss=0.4601, Val F1=0.6792, Test Loss=0.4744, Test F1=0.6826
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=10.89s, Train Loss=0.4441, Val Loss=0.4593, Val F1=0.6899, Test Loss=0.4860, Test F1=0.6875
Validation loss decreased (-0.686179 --> -0.689884).  Saving model ...
[Epoch 13/20], Time=10.96s, Train Loss=0.4386, Val Loss=0.4518, Val F1=0.6667, Test Loss=0.4585, Test F1=0.6828
EarlyStopping counter: 1 out of 5
[Epoch 14/20], Time=10.85s, Train Loss=0.4350, Val Loss=0.4567, Val F1=0.6753, Test Loss=0.4818, Test F1=0.6755
EarlyStopping counter: 2 out of 5
[Epoch 15/20], Time=10.86s, Train Loss=0.4310, Val Loss=0.4755, Val F1=0.6624, Test Loss=0.4904, Test F1=0.6675
EarlyStopping counter: 3 out of 5
[Epoch 16/20], Time=10.84s, Train Loss=0.4304, Val Loss=0.4536, Val F1=0.6752, Test Loss=0.4759, Test F1=0.6667
EarlyStopping counter: 4 out of 5
[Epoch 17/20], Time=10.71s, Train Loss=0.4300, Val Loss=0.4900, Val F1=0.6783, Test Loss=0.5186, Test F1=0.6796
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_71_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_71_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8085106382978723
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_71_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:15:49,4,71,0.6899,0.8412,0.6624,0.7197,128,0.002563,512,2,2,4,0.03856,8,5,0.42,0.31,0.7089,51,0.6821,0.8304,0.6361,0.7353,0.0078,False,OK

[I 2026-07-08 22:15:49,079] Trial 71 finished with value: 0.6898839137645107 and parameters: {'lr': 0.002562979139413566, 'd_model': 128, 'd_ff': 512, 'e_layers': 2, 'top_k': 2, 'dropout': 0.03855981058944924, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_72     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.002212790491667799     --e_layers 2     --d_model 128     --d_ff 64     --top_k 2     --num_kernels 6     --dropout 0.031420555250276025     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.031420555250276025
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.002212790491667799
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_72
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_72_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=14.49s, Train Loss=0.5009, Val Loss=0.4556, Val F1=0.6901, Test Loss=0.4700, Test F1=0.6851
Validation loss decreased (inf --> -0.690096).  Saving model ...
[Epoch 02/20], Time=13.40s, Train Loss=0.4763, Val Loss=0.4685, Val F1=0.6846, Test Loss=0.4716, Test F1=0.7023
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=13.37s, Train Loss=0.4705, Val Loss=0.4619, Val F1=0.6932, Test Loss=0.4713, Test F1=0.6960
Validation loss decreased (-0.690096 --> -0.693201).  Saving model ...
[Epoch 04/20], Time=13.42s, Train Loss=0.4654, Val Loss=0.4443, Val F1=0.6892, Test Loss=0.4602, Test F1=0.6983
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=13.34s, Train Loss=0.4581, Val Loss=0.4594, Val F1=0.6750, Test Loss=0.4699, Test F1=0.6694
EarlyStopping counter: 2 out of 5
[Epoch 06/20], Time=13.31s, Train Loss=0.4569, Val Loss=0.4448, Val F1=0.6987, Test Loss=0.4577, Test F1=0.6904
Validation loss decreased (-0.693201 --> -0.698675).  Saving model ...
[Epoch 07/20], Time=13.24s, Train Loss=0.4452, Val Loss=0.4576, Val F1=0.6758, Test Loss=0.4718, Test F1=0.6781
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=13.44s, Train Loss=0.4429, Val Loss=0.4491, Val F1=0.6991, Test Loss=0.4736, Test F1=0.6996
Validation loss decreased (-0.698675 --> -0.699060).  Saving model ...
[Epoch 09/20], Time=13.22s, Train Loss=0.4414, Val Loss=0.4611, Val F1=0.6804, Test Loss=0.4546, Test F1=0.6961
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=13.38s, Train Loss=0.4405, Val Loss=0.4481, Val F1=0.6919, Test Loss=0.4606, Test F1=0.7003
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=13.29s, Train Loss=0.4310, Val Loss=0.4546, Val F1=0.6760, Test Loss=0.4752, Test F1=0.6791
EarlyStopping counter: 3 out of 5
[Epoch 12/20], Time=13.53s, Train Loss=0.4318, Val Loss=0.4584, Val F1=0.6872, Test Loss=0.4706, Test F1=0.6997
EarlyStopping counter: 4 out of 5
[Epoch 13/20], Time=13.36s, Train Loss=0.4366, Val Loss=0.4523, Val F1=0.6867, Test Loss=0.4659, Test F1=0.7028
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_72_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_72_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8036006546644845
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_72_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:19:38,4,72,0.6991,0.8383,0.7102,0.6883,128,0.002213,64,2,2,6,0.031421,8,5,0.29,0.27,0.7089,51,0.6954,0.8302,0.6768,0.7151,0.0036,False,OK

[I 2026-07-08 22:19:38,490] Trial 72 finished with value: 0.6990595611285266 and parameters: {'lr': 0.002212790491667799, 'd_model': 128, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.031420555250276025, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_73     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 3     --batch_size 8     --train_epochs 20     --learning_rate 0.0006895001585637043     --e_layers 2     --d_model 256     --d_ff 64     --top_k 2     --num_kernels 4     --dropout 0.03060837476734916     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.03060837476734916
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0006895001585637043
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_73
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 3
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_73_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.81s, Train Loss=0.4995, Val Loss=0.4611, Val F1=0.6844, Test Loss=0.4779, Test F1=0.6819
Validation loss decreased (inf --> -0.684397).  Saving model ...
[Epoch 02/20], Time=10.70s, Train Loss=0.4672, Val Loss=0.5114, Val F1=0.6981, Test Loss=0.5162, Test F1=0.6968
Validation loss decreased (-0.684397 --> -0.698113).  Saving model ...
[Epoch 03/20], Time=10.66s, Train Loss=0.4673, Val Loss=0.4765, Val F1=0.6804, Test Loss=0.4873, Test F1=0.6762
EarlyStopping counter: 1 out of 3
[Epoch 04/20], Time=10.71s, Train Loss=0.4529, Val Loss=0.4584, Val F1=0.6779, Test Loss=0.4588, Test F1=0.6992
EarlyStopping counter: 2 out of 3
[Epoch 05/20], Time=10.79s, Train Loss=0.4439, Val Loss=0.4815, Val F1=0.6738, Test Loss=0.4701, Test F1=0.6919
EarlyStopping counter: 3 out of 3
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_73_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_73_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7986906710310966
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_73_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:21:26,4,73,0.6981,0.8332,0.707,0.6894,256,0.00069,64,2,2,4,0.030608,8,3,0.58,0.47,0.7089,51,0.6934,0.8344,0.6819,0.7053,0.0047,False,OK

[I 2026-07-08 22:21:26,654] Trial 73 finished with value: 0.6981132075471698 and parameters: {'lr': 0.0006895001585637043, 'd_model': 256, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.03060837476734916, 'batch_size': 8, 'patience': 3, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_74     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0009104842938821864     --e_layers 2     --d_model 8     --d_ff 2     --top_k 2     --num_kernels 6     --dropout 0.24972607273406305     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 2
d_layers                 : 1
d_model                  : 8
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.24972607273406305
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0009104842938821864
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_74
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_74_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.76s, Train Loss=0.6345, Val Loss=0.5519, Val F1=0.5572, Test Loss=0.5491, Test F1=0.5911
Validation loss decreased (inf --> -0.557196).  Saving model ...
[Epoch 02/20], Time=6.66s, Train Loss=0.5523, Val Loss=0.5062, Val F1=0.6081, Test Loss=0.5061, Test F1=0.6363
Validation loss decreased (-0.557196 --> -0.608130).  Saving model ...
[Epoch 03/20], Time=6.78s, Train Loss=0.5243, Val Loss=0.4831, Val F1=0.6412, Test Loss=0.4892, Test F1=0.6553
Validation loss decreased (-0.608130 --> -0.641221).  Saving model ...
[Epoch 04/20], Time=6.63s, Train Loss=0.5019, Val Loss=0.4706, Val F1=0.6698, Test Loss=0.4800, Test F1=0.6708
Validation loss decreased (-0.641221 --> -0.669767).  Saving model ...
[Epoch 05/20], Time=6.67s, Train Loss=0.4901, Val Loss=0.4672, Val F1=0.6688, Test Loss=0.4784, Test F1=0.6740
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=6.70s, Train Loss=0.4867, Val Loss=0.4645, Val F1=0.6769, Test Loss=0.4761, Test F1=0.6724
Validation loss decreased (-0.669767 --> -0.676923).  Saving model ...
[Epoch 07/20], Time=6.63s, Train Loss=0.4802, Val Loss=0.4612, Val F1=0.6799, Test Loss=0.4732, Test F1=0.6775
Validation loss decreased (-0.676923 --> -0.679939).  Saving model ...
[Epoch 08/20], Time=6.71s, Train Loss=0.4745, Val Loss=0.4617, Val F1=0.6760, Test Loss=0.4738, Test F1=0.6787
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=6.69s, Train Loss=0.4695, Val Loss=0.4555, Val F1=0.6827, Test Loss=0.4680, Test F1=0.6844
Validation loss decreased (-0.679939 --> -0.682692).  Saving model ...
[Epoch 10/20], Time=6.69s, Train Loss=0.4719, Val Loss=0.4561, Val F1=0.6830, Test Loss=0.4669, Test F1=0.6818
Validation loss decreased (-0.682692 --> -0.683007).  Saving model ...
[Epoch 11/20], Time=6.85s, Train Loss=0.4742, Val Loss=0.4544, Val F1=0.6851, Test Loss=0.4666, Test F1=0.6887
Validation loss decreased (-0.683007 --> -0.685065).  Saving model ...
[Epoch 12/20], Time=6.80s, Train Loss=0.4716, Val Loss=0.4526, Val F1=0.6875, Test Loss=0.4659, Test F1=0.6915
Validation loss decreased (-0.685065 --> -0.687500).  Saving model ...
[Epoch 13/20], Time=6.68s, Train Loss=0.4693, Val Loss=0.4501, Val F1=0.6870, Test Loss=0.4651, Test F1=0.6832
EarlyStopping counter: 1 out of 5
[Epoch 14/20], Time=6.85s, Train Loss=0.4618, Val Loss=0.4463, Val F1=0.6867, Test Loss=0.4626, Test F1=0.6934
EarlyStopping counter: 2 out of 5
[Epoch 15/20], Time=6.71s, Train Loss=0.4634, Val Loss=0.4474, Val F1=0.6847, Test Loss=0.4625, Test F1=0.6939
EarlyStopping counter: 3 out of 5
[Epoch 16/20], Time=6.74s, Train Loss=0.4623, Val Loss=0.4455, Val F1=0.6875, Test Loss=0.4607, Test F1=0.6924
Validation loss decreased (-0.687500 --> -0.687500).  Saving model ...
[Epoch 17/20], Time=6.73s, Train Loss=0.4615, Val Loss=0.4473, Val F1=0.6802, Test Loss=0.4636, Test F1=0.6897
EarlyStopping counter: 1 out of 5
[Epoch 18/20], Time=6.80s, Train Loss=0.4642, Val Loss=0.4451, Val F1=0.6869, Test Loss=0.4620, Test F1=0.6937
EarlyStopping counter: 2 out of 5
[Epoch 19/20], Time=6.74s, Train Loss=0.4559, Val Loss=0.4439, Val F1=0.6839, Test Loss=0.4598, Test F1=0.6953
EarlyStopping counter: 3 out of 5
[Epoch 20/20], Time=6.78s, Train Loss=0.4609, Val Loss=0.4480, Val F1=0.6828, Test Loss=0.4651, Test F1=0.6906
EarlyStopping counter: 4 out of 5
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_74_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_74_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8003273322422259
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_74_TimesNet_UEA_ftM_sl4_ll48_pl0_dm8_nh8_el2_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:24:33,4,74,0.6875,0.8315,0.7006,0.6748,8,0.00091,2,2,2,6,0.249726,16,5,0.31,0.31,0.7089,51,0.6924,0.8282,0.6845,0.7005,-0.0049,False,OK

[I 2026-07-08 22:24:33,490] Trial 74 finished with value: 0.6875 and parameters: {'lr': 0.0009104842938821864, 'd_model': 8, 'd_ff': 2, 'e_layers': 2, 'top_k': 2, 'dropout': 0.24972607273406305, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_75     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0017280774383331252     --e_layers 3     --d_model 48     --d_ff 32     --top_k 2     --num_kernels 4     --dropout 0.07393257856578189     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.07393257856578189
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0017280774383331252
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_75
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_75_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=15.38s, Train Loss=0.5067, Val Loss=0.4600, Val F1=0.6719, Test Loss=0.4696, Test F1=0.6795
Validation loss decreased (inf --> -0.671875).  Saving model ...
[Epoch 02/20], Time=14.22s, Train Loss=0.4679, Val Loss=0.4506, Val F1=0.6930, Test Loss=0.4620, Test F1=0.6884
Validation loss decreased (-0.671875 --> -0.693038).  Saving model ...
[Epoch 03/20], Time=14.39s, Train Loss=0.4610, Val Loss=0.4584, Val F1=0.6834, Test Loss=0.4739, Test F1=0.6938
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=14.28s, Train Loss=0.4520, Val Loss=0.4695, Val F1=0.6775, Test Loss=0.4946, Test F1=0.6587
EarlyStopping counter: 2 out of 5
[Epoch 05/20], Time=14.36s, Train Loss=0.4539, Val Loss=0.4492, Val F1=0.6949, Test Loss=0.4724, Test F1=0.6939
Validation loss decreased (-0.693038 --> -0.694943).  Saving model ...
[Epoch 06/20], Time=14.29s, Train Loss=0.4396, Val Loss=0.4445, Val F1=0.6917, Test Loss=0.4636, Test F1=0.6834
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=14.13s, Train Loss=0.4434, Val Loss=0.4467, Val F1=0.6801, Test Loss=0.4633, Test F1=0.6896
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=14.14s, Train Loss=0.4341, Val Loss=0.4437, Val F1=0.6938, Test Loss=0.4679, Test F1=0.6955
EarlyStopping counter: 3 out of 5
[Epoch 09/20], Time=14.12s, Train Loss=0.4293, Val Loss=0.4544, Val F1=0.6845, Test Loss=0.4754, Test F1=0.6855
EarlyStopping counter: 4 out of 5
[Epoch 10/20], Time=14.05s, Train Loss=0.4262, Val Loss=0.4524, Val F1=0.6900, Test Loss=0.4695, Test F1=0.6991
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_75_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_75_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8044189852700491
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_75_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:27:51,4,75,0.6949,0.8385,0.6783,0.7124,48,0.001728,32,3,2,4,0.073933,8,5,0.47,0.34,0.7089,51,0.6844,0.8287,0.6565,0.7147,0.0106,False,OK

[I 2026-07-08 22:27:51,591] Trial 75 finished with value: 0.6949429037520392 and parameters: {'lr': 0.0017280774383331252, 'd_model': 48, 'd_ff': 32, 'e_layers': 3, 'top_k': 2, 'dropout': 0.07393257856578189, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_76     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0026400082331030036     --e_layers 2     --d_model 256     --d_ff 32     --top_k 2     --num_kernels 4     --dropout 0.019549579430246364     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.019549579430246364
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0026400082331030036
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_76
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_76_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=12.00s, Train Loss=0.5114, Val Loss=0.4999, Val F1=0.6863, Test Loss=0.5161, Test F1=0.6598
Validation loss decreased (inf --> -0.686308).  Saving model ...
[Epoch 02/20], Time=10.83s, Train Loss=0.5130, Val Loss=0.4745, Val F1=0.6733, Test Loss=0.4975, Test F1=0.6643
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=10.96s, Train Loss=0.4916, Val Loss=0.4781, Val F1=0.6710, Test Loss=0.4855, Test F1=0.6676
EarlyStopping counter: 2 out of 5
[Epoch 04/20], Time=10.77s, Train Loss=0.4806, Val Loss=0.4575, Val F1=0.6829, Test Loss=0.4790, Test F1=0.6870
EarlyStopping counter: 3 out of 5
[Epoch 05/20], Time=10.69s, Train Loss=0.4609, Val Loss=0.4592, Val F1=0.6767, Test Loss=0.4773, Test F1=0.6631
EarlyStopping counter: 4 out of 5
[Epoch 06/20], Time=10.62s, Train Loss=0.4525, Val Loss=0.4477, Val F1=0.6844, Test Loss=0.4697, Test F1=0.6943
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_76_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_76_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7855973813420621
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_76_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:29:50,4,76,0.6863,0.8115,0.6306,0.7529,256,0.00264,32,2,2,4,0.01955,8,5,0.39,0.3,0.7089,51,0.6496,0.8015,0.6132,0.6905,0.0367,False,OK

[I 2026-07-08 22:29:50,520] Trial 76 finished with value: 0.6863084922010398 and parameters: {'lr': 0.0026400082331030036, 'd_model': 256, 'd_ff': 32, 'e_layers': 2, 'top_k': 2, 'dropout': 0.019549579430246364, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_77     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.00039350267941288804     --e_layers 4     --d_model 64     --d_ff 128     --top_k 2     --num_kernels 4     --dropout 0.25939183627897083     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.25939183627897083
dtwwarp                  : False
e_layers                 : 4
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00039350267941288804
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_77
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_77_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.30s, Train Loss=0.5412, Val Loss=0.4716, Val F1=0.6646, Test Loss=0.4850, Test F1=0.6667
Validation loss decreased (inf --> -0.664596).  Saving model ...
[Epoch 02/20], Time=10.34s, Train Loss=0.4730, Val Loss=0.4586, Val F1=0.6760, Test Loss=0.4706, Test F1=0.6806
Validation loss decreased (-0.664596 --> -0.676012).  Saving model ...
[Epoch 03/20], Time=10.23s, Train Loss=0.4665, Val Loss=0.4539, Val F1=0.6801, Test Loss=0.4715, Test F1=0.6873
Validation loss decreased (-0.676012 --> -0.680124).  Saving model ...
[Epoch 04/20], Time=10.25s, Train Loss=0.4617, Val Loss=0.4570, Val F1=0.6775, Test Loss=0.4689, Test F1=0.6684
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=10.23s, Train Loss=0.4539, Val Loss=0.4524, Val F1=0.6887, Test Loss=0.4661, Test F1=0.6798
Validation loss decreased (-0.680124 --> -0.688679).  Saving model ...
[Epoch 06/20], Time=10.18s, Train Loss=0.4554, Val Loss=0.4710, Val F1=0.6537, Test Loss=0.4833, Test F1=0.6621
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=10.17s, Train Loss=0.4561, Val Loss=0.4392, Val F1=0.6937, Test Loss=0.4586, Test F1=0.7033
Validation loss decreased (-0.688679 --> -0.693750).  Saving model ...
[Epoch 08/20], Time=10.13s, Train Loss=0.4500, Val Loss=0.4588, Val F1=0.6877, Test Loss=0.4733, Test F1=0.6957
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=10.11s, Train Loss=0.4457, Val Loss=0.4364, Val F1=0.6935, Test Loss=0.4562, Test F1=0.6879
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=10.05s, Train Loss=0.4413, Val Loss=0.4501, Val F1=0.6925, Test Loss=0.4682, Test F1=0.7048
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=9.96s, Train Loss=0.4403, Val Loss=0.4651, Val F1=0.6836, Test Loss=0.4700, Test F1=0.6920
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=10.02s, Train Loss=0.4394, Val Loss=0.4371, Val F1=0.6889, Test Loss=0.4589, Test F1=0.6997
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_77_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_77_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7995090016366612
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_77_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:32:46,4,77,0.6937,0.8362,0.707,0.681,64,0.000394,128,4,2,4,0.259392,16,5,0.35,0.38,0.7089,51,0.6944,0.8291,0.6997,0.6892,-0.0007,False,OK

[I 2026-07-08 22:32:46,666] Trial 77 finished with value: 0.69375 and parameters: {'lr': 0.00039350267941288804, 'd_model': 64, 'd_ff': 128, 'e_layers': 4, 'top_k': 2, 'dropout': 0.25939183627897083, 'batch_size': 16, 'patience': 5, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_78     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 8     --train_epochs 20     --learning_rate 0.0009676098516280165     --e_layers 2     --d_model 128     --d_ff 32     --top_k 2     --num_kernels 4     --dropout 0.0380774101465272     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.0380774101465272
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0009676098516280165
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_78
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_78_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.59s, Train Loss=0.4952, Val Loss=0.4616, Val F1=0.6787, Test Loss=0.4810, Test F1=0.6714
Validation loss decreased (inf --> -0.678689).  Saving model ...
[Epoch 02/20], Time=10.60s, Train Loss=0.4645, Val Loss=0.4440, Val F1=0.6895, Test Loss=0.4603, Test F1=0.6812
Validation loss decreased (-0.678689 --> -0.689531).  Saving model ...
[Epoch 03/20], Time=10.59s, Train Loss=0.4536, Val Loss=0.4620, Val F1=0.6947, Test Loss=0.4779, Test F1=0.6902
Validation loss decreased (-0.689531 --> -0.694669).  Saving model ...
[Epoch 04/20], Time=10.45s, Train Loss=0.4504, Val Loss=0.4555, Val F1=0.6959, Test Loss=0.4729, Test F1=0.6945
Validation loss decreased (-0.694669 --> -0.695925).  Saving model ...
[Epoch 05/20], Time=10.53s, Train Loss=0.4416, Val Loss=0.4733, Val F1=0.6947, Test Loss=0.4938, Test F1=0.6964
EarlyStopping counter: 1 out of 4
[Epoch 06/20], Time=10.24s, Train Loss=0.4418, Val Loss=0.4701, Val F1=0.6943, Test Loss=0.4765, Test F1=0.7047
EarlyStopping counter: 2 out of 4
[Epoch 07/20], Time=10.57s, Train Loss=0.4346, Val Loss=0.4460, Val F1=0.6973, Test Loss=0.4582, Test F1=0.7000
Validation loss decreased (-0.695925 --> -0.697306).  Saving model ...
[Epoch 08/20], Time=10.46s, Train Loss=0.4274, Val Loss=0.4688, Val F1=0.6844, Test Loss=0.4826, Test F1=0.6938
EarlyStopping counter: 1 out of 4
[Epoch 09/20], Time=10.68s, Train Loss=0.4202, Val Loss=0.4552, Val F1=0.6811, Test Loss=0.4742, Test F1=0.6798
EarlyStopping counter: 2 out of 4
[Epoch 10/20], Time=10.48s, Train Loss=0.4121, Val Loss=0.4643, Val F1=0.6752, Test Loss=0.4886, Test F1=0.6746
EarlyStopping counter: 3 out of 4
[Epoch 11/20], Time=10.49s, Train Loss=0.4044, Val Loss=0.4655, Val F1=0.6909, Test Loss=0.4824, Test F1=0.6897
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_78_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_78_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8011456628477905
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_78_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:35:36,4,78,0.6973,0.839,0.7006,0.694,128,0.000968,32,2,2,4,0.038077,8,4,0.29,0.26,0.7089,51,0.694,0.8358,0.6896,0.6985,0.0033,False,OK

[I 2026-07-08 22:35:36,947] Trial 78 finished with value: 0.6973058637083994 and parameters: {'lr': 0.0009676098516280165, 'd_model': 128, 'd_ff': 32, 'e_layers': 2, 'top_k': 2, 'dropout': 0.0380774101465272, 'batch_size': 8, 'patience': 4, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_79     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0009088670449148217     --e_layers 2     --d_model 32     --d_ff 256     --top_k 2     --num_kernels 6     --dropout 0.2804593618402217     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 256
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2804593618402217
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0009088670449148217
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_79
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_79_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=10.12s, Train Loss=0.5695, Val Loss=0.4590, Val F1=0.6712, Test Loss=0.4781, Test F1=0.6683
Validation loss decreased (inf --> -0.671164).  Saving model ...
[Epoch 02/20], Time=9.05s, Train Loss=0.4867, Val Loss=0.4533, Val F1=0.6750, Test Loss=0.4716, Test F1=0.6708
Validation loss decreased (-0.671164 --> -0.675039).  Saving model ...
[Epoch 03/20], Time=9.04s, Train Loss=0.4757, Val Loss=0.4548, Val F1=0.6837, Test Loss=0.4795, Test F1=0.6813
Validation loss decreased (-0.675039 --> -0.683706).  Saving model ...
[Epoch 04/20], Time=9.06s, Train Loss=0.4698, Val Loss=0.4539, Val F1=0.6794, Test Loss=0.4716, Test F1=0.6814
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=9.05s, Train Loss=0.4647, Val Loss=0.4600, Val F1=0.6837, Test Loss=0.4782, Test F1=0.6889
Validation loss decreased (-0.683706 --> -0.683706).  Saving model ...
[Epoch 06/20], Time=9.01s, Train Loss=0.4674, Val Loss=0.4588, Val F1=0.6880, Test Loss=0.4815, Test F1=0.6835
Validation loss decreased (-0.683706 --> -0.687976).  Saving model ...
[Epoch 07/20], Time=9.18s, Train Loss=0.4639, Val Loss=0.4429, Val F1=0.6881, Test Loss=0.4679, Test F1=0.6823
Validation loss decreased (-0.687976 --> -0.688103).  Saving model ...
[Epoch 08/20], Time=9.01s, Train Loss=0.4572, Val Loss=0.4386, Val F1=0.6962, Test Loss=0.4594, Test F1=0.6980
Validation loss decreased (-0.688103 --> -0.696223).  Saving model ...
[Epoch 09/20], Time=9.19s, Train Loss=0.4540, Val Loss=0.4417, Val F1=0.6909, Test Loss=0.4609, Test F1=0.6845
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=9.13s, Train Loss=0.4542, Val Loss=0.4439, Val F1=0.6840, Test Loss=0.4634, Test F1=0.6825
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=9.13s, Train Loss=0.4495, Val Loss=0.4471, Val F1=0.6865, Test Loss=0.4653, Test F1=0.6980
EarlyStopping counter: 3 out of 5
[Epoch 12/20], Time=9.14s, Train Loss=0.4473, Val Loss=0.4474, Val F1=0.6895, Test Loss=0.4633, Test F1=0.6987
EarlyStopping counter: 4 out of 5
[Epoch 13/20], Time=9.07s, Train Loss=0.4445, Val Loss=0.4466, Val F1=0.6882, Test Loss=0.4668, Test F1=0.6930
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_79_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_79_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8044189852700491
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_79_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:38:29,4,79,0.6962,0.8329,0.6752,0.7186,32,0.000909,256,2,2,6,0.280459,16,5,0.39,0.32,0.7089,51,0.6897,0.8279,0.659,0.7235,0.0065,False,OK

[I 2026-07-08 22:38:29,301] Trial 79 finished with value: 0.6962233169129721 and parameters: {'lr': 0.0009088670449148217, 'd_model': 32, 'd_ff': 256, 'e_layers': 2, 'top_k': 2, 'dropout': 0.2804593618402217, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_80     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 8     --train_epochs 20     --learning_rate 0.0012807930021863274     --e_layers 2     --d_model 32     --d_ff 16     --top_k 2     --num_kernels 4     --dropout 0.05810423292505544     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.05810423292505544
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0012807930021863274
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_80
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_80_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.43s, Train Loss=0.5270, Val Loss=0.4567, Val F1=0.6832, Test Loss=0.4717, Test F1=0.6751
Validation loss decreased (inf --> -0.683230).  Saving model ...
[Epoch 02/20], Time=10.32s, Train Loss=0.4636, Val Loss=0.4611, Val F1=0.6821, Test Loss=0.4767, Test F1=0.6777
EarlyStopping counter: 1 out of 4
[Epoch 03/20], Time=10.42s, Train Loss=0.4580, Val Loss=0.4633, Val F1=0.6781, Test Loss=0.4808, Test F1=0.6918
EarlyStopping counter: 2 out of 4
[Epoch 04/20], Time=10.48s, Train Loss=0.4525, Val Loss=0.4481, Val F1=0.6879, Test Loss=0.4673, Test F1=0.6774
Validation loss decreased (-0.683230 --> -0.687898).  Saving model ...
[Epoch 05/20], Time=10.49s, Train Loss=0.4467, Val Loss=0.4539, Val F1=0.6774, Test Loss=0.4648, Test F1=0.6945
EarlyStopping counter: 1 out of 4
[Epoch 06/20], Time=10.51s, Train Loss=0.4422, Val Loss=0.4437, Val F1=0.6822, Test Loss=0.4589, Test F1=0.7060
EarlyStopping counter: 2 out of 4
[Epoch 07/20], Time=10.43s, Train Loss=0.4372, Val Loss=0.4450, Val F1=0.7016, Test Loss=0.4602, Test F1=0.7049
Validation loss decreased (-0.687898 --> -0.701627).  Saving model ...
[Epoch 08/20], Time=10.35s, Train Loss=0.4367, Val Loss=0.4388, Val F1=0.6980, Test Loss=0.4546, Test F1=0.7029
EarlyStopping counter: 1 out of 4
[Epoch 09/20], Time=10.41s, Train Loss=0.4235, Val Loss=0.4441, Val F1=0.6943, Test Loss=0.4615, Test F1=0.7047
EarlyStopping counter: 2 out of 4
[Epoch 10/20], Time=10.46s, Train Loss=0.4235, Val Loss=0.4440, Val F1=0.6987, Test Loss=0.4649, Test F1=0.7011
EarlyStopping counter: 3 out of 4
[Epoch 11/20], Time=10.38s, Train Loss=0.4192, Val Loss=0.4628, Val F1=0.6938, Test Loss=0.4777, Test F1=0.6960
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_80_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_80_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.809328968903437
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_80_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el2_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:41:17,4,80,0.7016,0.8352,0.6178,0.8117,32,0.001281,16,2,2,4,0.058104,8,4,0.6,0.31,0.7089,51,0.6647,0.8354,0.5827,0.7736,0.0369,False,OK

[I 2026-07-08 22:41:17,278] Trial 80 finished with value: 0.701627486437613 and parameters: {'lr': 0.0012807930021863274, 'd_model': 32, 'd_ff': 16, 'e_layers': 2, 'top_k': 2, 'dropout': 0.05810423292505544, 'batch_size': 8, 'patience': 4, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_81     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0014306999266381942     --e_layers 3     --d_model 128     --d_ff 8     --top_k 2     --num_kernels 6     --dropout 0.2504040842748183     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 8
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2504040842748183
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0014306999266381942
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_81
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_81_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=10.99s, Train Loss=0.5341, Val Loss=0.4649, Val F1=0.6812, Test Loss=0.4820, Test F1=0.6700
Validation loss decreased (inf --> -0.681182).  Saving model ...
[Epoch 02/20], Time=10.04s, Train Loss=0.4791, Val Loss=0.4567, Val F1=0.6921, Test Loss=0.4788, Test F1=0.6854
Validation loss decreased (-0.681182 --> -0.692063).  Saving model ...
[Epoch 03/20], Time=9.88s, Train Loss=0.4690, Val Loss=0.4484, Val F1=0.6899, Test Loss=0.4696, Test F1=0.6825
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=9.88s, Train Loss=0.4620, Val Loss=0.4431, Val F1=0.7048, Test Loss=0.4636, Test F1=0.6890
Validation loss decreased (-0.692063 --> -0.704762).  Saving model ...
[Epoch 05/20], Time=10.13s, Train Loss=0.4501, Val Loss=0.4424, Val F1=0.6914, Test Loss=0.4579, Test F1=0.6995
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=9.90s, Train Loss=0.4516, Val Loss=0.4862, Val F1=0.6859, Test Loss=0.4932, Test F1=0.6962
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=9.88s, Train Loss=0.4547, Val Loss=0.4433, Val F1=0.6952, Test Loss=0.4544, Test F1=0.6943
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=9.88s, Train Loss=0.4452, Val Loss=0.4536, Val F1=0.7018, Test Loss=0.4792, Test F1=0.6775
EarlyStopping counter: 4 out of 5
[Epoch 09/20], Time=9.92s, Train Loss=0.4403, Val Loss=0.4482, Val F1=0.6930, Test Loss=0.4757, Test F1=0.6983
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_81_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_81_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8060556464811784
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_81_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:43:40,4,81,0.7048,0.8363,0.707,0.7025,128,0.001431,8,3,2,6,0.250404,16,5,0.37,0.36,0.7089,51,0.6874,0.8307,0.6743,0.7011,0.0173,False,OK

[I 2026-07-08 22:43:40,808] Trial 81 finished with value: 0.7047619047619048 and parameters: {'lr': 0.0014306999266381942, 'd_model': 128, 'd_ff': 8, 'e_layers': 3, 'top_k': 2, 'dropout': 0.2504040842748183, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_82     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0001513878703899425     --e_layers 3     --d_model 64     --d_ff 512     --top_k 2     --num_kernels 4     --dropout 0.2684697937012287     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2684697937012287
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0001513878703899425
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_82
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_82_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=16.58s, Train Loss=0.5401, Val Loss=0.4768, Val F1=0.6718, Test Loss=0.4893, Test F1=0.6723
Validation loss decreased (inf --> -0.671803).  Saving model ...
[Epoch 02/20], Time=15.57s, Train Loss=0.4773, Val Loss=0.4586, Val F1=0.6845, Test Loss=0.4648, Test F1=0.6964
Validation loss decreased (-0.671803 --> -0.684458).  Saving model ...
[Epoch 03/20], Time=15.67s, Train Loss=0.4696, Val Loss=0.4574, Val F1=0.6850, Test Loss=0.4650, Test F1=0.6931
Validation loss decreased (-0.684458 --> -0.684976).  Saving model ...
[Epoch 04/20], Time=15.68s, Train Loss=0.4668, Val Loss=0.4517, Val F1=0.6853, Test Loss=0.4644, Test F1=0.6917
Validation loss decreased (-0.684976 --> -0.685338).  Saving model ...
[Epoch 05/20], Time=15.60s, Train Loss=0.4580, Val Loss=0.4531, Val F1=0.6817, Test Loss=0.4686, Test F1=0.6684
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=15.75s, Train Loss=0.4587, Val Loss=0.4566, Val F1=0.6784, Test Loss=0.4691, Test F1=0.6702
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=15.62s, Train Loss=0.4533, Val Loss=0.4534, Val F1=0.6809, Test Loss=0.4655, Test F1=0.6872
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=15.57s, Train Loss=0.4544, Val Loss=0.4583, Val F1=0.6776, Test Loss=0.4695, Test F1=0.6919
EarlyStopping counter: 4 out of 5
[Epoch 09/20], Time=15.74s, Train Loss=0.4485, Val Loss=0.4500, Val F1=0.6868, Test Loss=0.4629, Test F1=0.6837
Validation loss decreased (-0.685338 --> -0.686804).  Saving model ...
[Epoch 10/20], Time=15.64s, Train Loss=0.4460, Val Loss=0.4497, Val F1=0.6890, Test Loss=0.4600, Test F1=0.6957
Validation loss decreased (-0.686804 --> -0.689024).  Saving model ...
[Epoch 11/20], Time=15.57s, Train Loss=0.4398, Val Loss=0.4392, Val F1=0.6989, Test Loss=0.4573, Test F1=0.7038
Validation loss decreased (-0.689024 --> -0.698908).  Saving model ...
[Epoch 12/20], Time=15.66s, Train Loss=0.4401, Val Loss=0.4455, Val F1=0.6817, Test Loss=0.4514, Test F1=0.7000
EarlyStopping counter: 1 out of 5
[Epoch 13/20], Time=15.72s, Train Loss=0.4361, Val Loss=0.4433, Val F1=0.6935, Test Loss=0.4595, Test F1=0.6992
EarlyStopping counter: 2 out of 5
[Epoch 14/20], Time=15.56s, Train Loss=0.4380, Val Loss=0.4395, Val F1=0.6975, Test Loss=0.4564, Test F1=0.7063
EarlyStopping counter: 3 out of 5
[Epoch 15/20], Time=15.65s, Train Loss=0.4305, Val Loss=0.4408, Val F1=0.6893, Test Loss=0.4508, Test F1=0.7033
EarlyStopping counter: 4 out of 5
[Epoch 16/20], Time=15.49s, Train Loss=0.4321, Val Loss=0.4393, Val F1=0.6935, Test Loss=0.4521, Test F1=0.7026
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_82_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_82_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8052373158756138
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_82_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:48:49,4,82,0.6989,0.8357,0.7134,0.685,64,0.000151,512,3,2,4,0.26847,8,5,0.29,0.29,0.7089,51,0.7038,0.8341,0.7074,0.7003,-0.0049,False,OK

[I 2026-07-08 22:48:49,367] Trial 82 finished with value: 0.6989079563182528 and parameters: {'lr': 0.0001513878703899425, 'd_model': 64, 'd_ff': 512, 'e_layers': 3, 'top_k': 2, 'dropout': 0.2684697937012287, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 51 with value: 0.7088607594936709.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_83     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.001260166653050406     --e_layers 3     --d_model 128     --d_ff 4     --top_k 2     --num_kernels 3     --dropout 0.2274204614967979     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 4
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2274204614967979
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.001260166653050406
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_83
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_83_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.87s, Train Loss=0.5235, Val Loss=0.4501, Val F1=0.6769, Test Loss=0.4638, Test F1=0.6873
Validation loss decreased (inf --> -0.676923).  Saving model ...
[Epoch 02/20], Time=6.91s, Train Loss=0.4723, Val Loss=0.4619, Val F1=0.6800, Test Loss=0.4707, Test F1=0.6843
Validation loss decreased (-0.676923 --> -0.680000).  Saving model ...
[Epoch 03/20], Time=6.85s, Train Loss=0.4710, Val Loss=0.4477, Val F1=0.6892, Test Loss=0.4618, Test F1=0.6948
Validation loss decreased (-0.680000 --> -0.689249).  Saving model ...
[Epoch 04/20], Time=6.99s, Train Loss=0.4631, Val Loss=0.4556, Val F1=0.6794, Test Loss=0.4634, Test F1=0.6974
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=6.83s, Train Loss=0.4633, Val Loss=0.4475, Val F1=0.6893, Test Loss=0.4560, Test F1=0.7047
Validation loss decreased (-0.689249 --> -0.689320).  Saving model ...
[Epoch 06/20], Time=6.96s, Train Loss=0.4573, Val Loss=0.4450, Val F1=0.6881, Test Loss=0.4563, Test F1=0.6982
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=6.85s, Train Loss=0.4527, Val Loss=0.4517, Val F1=0.6879, Test Loss=0.4687, Test F1=0.6898
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=6.81s, Train Loss=0.4539, Val Loss=0.4590, Val F1=0.7042, Test Loss=0.4777, Test F1=0.6975
Validation loss decreased (-0.689320 --> -0.704180).  Saving model ...
[Epoch 09/20], Time=6.88s, Train Loss=0.4523, Val Loss=0.4472, Val F1=0.7094, Test Loss=0.4635, Test F1=0.7026
Validation loss decreased (-0.704180 --> -0.709360).  Saving model ...
[Epoch 10/20], Time=6.85s, Train Loss=0.4437, Val Loss=0.4477, Val F1=0.6995, Test Loss=0.4692, Test F1=0.7078
EarlyStopping counter: 1 out of 5
[Epoch 11/20], Time=6.89s, Train Loss=0.4521, Val Loss=0.4428, Val F1=0.6949, Test Loss=0.4651, Test F1=0.7062
EarlyStopping counter: 2 out of 5
[Epoch 12/20], Time=6.89s, Train Loss=0.4477, Val Loss=0.4379, Val F1=0.7015, Test Loss=0.4585, Test F1=0.7088
EarlyStopping counter: 3 out of 5
[Epoch 13/20], Time=6.81s, Train Loss=0.4426, Val Loss=0.4480, Val F1=0.6986, Test Loss=0.4605, Test F1=0.6931
EarlyStopping counter: 4 out of 5
[Epoch 14/20], Time=6.95s, Train Loss=0.4318, Val Loss=0.4495, Val F1=0.6866, Test Loss=0.4697, Test F1=0.7003
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_83_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_83_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8076923076923077
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_83_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:51:18,4,83,0.7094,0.8389,0.6879,0.7322,128,0.00126,4,3,2,3,0.22742,16,5,0.54,0.37,0.7094,83,0.6821,0.8381,0.6361,0.7353,0.0272,False,OK

[I 2026-07-08 22:51:18,090] Trial 83 finished with value: 0.7093596059113301 and parameters: {'lr': 0.001260166653050406, 'd_model': 128, 'd_ff': 4, 'e_layers': 3, 'top_k': 2, 'dropout': 0.2274204614967979, 'batch_size': 16, 'patience': 5, 'num_kernels': 3}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_84     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.000923154259942812     --e_layers 4     --d_model 64     --d_ff 8     --top_k 2     --num_kernels 6     --dropout 0.13813191625213156     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 8
d_layers                 : 1
d_model                  : 64
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.13813191625213156
dtwwarp                  : False
e_layers                 : 4
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.000923154259942812
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_84
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_84_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.0.kernels.4.weight
 - model.3.conv.0.kernels.4.bias
 - model.3.conv.0.kernels.5.weight
 - model.3.conv.0.kernels.5.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.3.conv.2.kernels.4.weight
 - model.3.conv.2.kernels.4.bias
 - model.3.conv.2.kernels.5.weight
 - model.3.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.07s, Train Loss=0.5427, Val Loss=0.4555, Val F1=0.6794, Test Loss=0.4705, Test F1=0.6792
Validation loss decreased (inf --> -0.679426).  Saving model ...
[Epoch 02/20], Time=12.13s, Train Loss=0.4732, Val Loss=0.4561, Val F1=0.6888, Test Loss=0.4769, Test F1=0.6874
Validation loss decreased (-0.679426 --> -0.688811).  Saving model ...
[Epoch 03/20], Time=12.14s, Train Loss=0.4655, Val Loss=0.4475, Val F1=0.6934, Test Loss=0.4628, Test F1=0.6908
Validation loss decreased (-0.688811 --> -0.693419).  Saving model ...
[Epoch 04/20], Time=11.83s, Train Loss=0.4528, Val Loss=0.4457, Val F1=0.6939, Test Loss=0.4568, Test F1=0.7001
Validation loss decreased (-0.693419 --> -0.693878).  Saving model ...
[Epoch 05/20], Time=11.80s, Train Loss=0.4508, Val Loss=0.4440, Val F1=0.6929, Test Loss=0.4562, Test F1=0.7007
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=11.83s, Train Loss=0.4425, Val Loss=0.4434, Val F1=0.6856, Test Loss=0.4573, Test F1=0.6930
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=11.80s, Train Loss=0.4430, Val Loss=0.4361, Val F1=0.7002, Test Loss=0.4524, Test F1=0.7038
Validation loss decreased (-0.693878 --> -0.700162).  Saving model ...
[Epoch 08/20], Time=12.12s, Train Loss=0.4377, Val Loss=0.4441, Val F1=0.6836, Test Loss=0.4608, Test F1=0.6923
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=11.95s, Train Loss=0.4358, Val Loss=0.4396, Val F1=0.6936, Test Loss=0.4519, Test F1=0.7089
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=12.01s, Train Loss=0.4307, Val Loss=0.4393, Val F1=0.6855, Test Loss=0.4518, Test F1=0.7031
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=12.06s, Train Loss=0.4253, Val Loss=0.4409, Val F1=0.6865, Test Loss=0.4619, Test F1=0.7034
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=12.00s, Train Loss=0.4262, Val Loss=0.4383, Val F1=0.7012, Test Loss=0.4539, Test F1=0.6955
Validation loss decreased (-0.700162 --> -0.701169).  Saving model ...
[Epoch 13/20], Time=12.04s, Train Loss=0.4238, Val Loss=0.4413, Val F1=0.6998, Test Loss=0.4543, Test F1=0.7066
EarlyStopping counter: 1 out of 5
[Epoch 14/20], Time=11.90s, Train Loss=0.4205, Val Loss=0.4434, Val F1=0.6985, Test Loss=0.4582, Test F1=0.6941
EarlyStopping counter: 2 out of 5
[Epoch 15/20], Time=12.08s, Train Loss=0.4165, Val Loss=0.4582, Val F1=0.6907, Test Loss=0.4661, Test F1=0.7022
EarlyStopping counter: 3 out of 5
[Epoch 16/20], Time=11.87s, Train Loss=0.4143, Val Loss=0.4511, Val F1=0.6843, Test Loss=0.4665, Test F1=0.6970
EarlyStopping counter: 4 out of 5
[Epoch 17/20], Time=11.82s, Train Loss=0.4131, Val Loss=0.4544, Val F1=0.6832, Test Loss=0.4838, Test F1=0.6782
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_84_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_84_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8036006546644845
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_84_TimesNet_UEA_ftM_sl4_ll48_pl0_dm64_nh8_el4_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:55:35,4,84,0.7012,0.8346,0.6688,0.7368,64,0.000923,8,4,2,6,0.138132,16,5,0.44,0.36,0.7094,83,0.6796,0.8308,0.626,0.7432,0.0216,False,OK

[I 2026-07-08 22:55:35,990] Trial 84 finished with value: 0.7011686143572621 and parameters: {'lr': 0.000923154259942812, 'd_model': 64, 'd_ff': 8, 'e_layers': 4, 'top_k': 2, 'dropout': 0.13813191625213156, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_85     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0015081985822696141     --e_layers 3     --d_model 16     --d_ff 4     --top_k 2     --num_kernels 3     --dropout 0.20739660917078273     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 4
d_layers                 : 1
d_model                  : 16
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.20739660917078273
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0015081985822696141
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_85
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_85_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.75s, Train Loss=0.5552, Val Loss=0.4789, Val F1=0.6438, Test Loss=0.4868, Test F1=0.6548
Validation loss decreased (inf --> -0.643791).  Saving model ...
[Epoch 02/20], Time=6.58s, Train Loss=0.4956, Val Loss=0.4561, Val F1=0.6763, Test Loss=0.4717, Test F1=0.6684
Validation loss decreased (-0.643791 --> -0.676282).  Saving model ...
[Epoch 03/20], Time=6.63s, Train Loss=0.4856, Val Loss=0.4589, Val F1=0.6750, Test Loss=0.4747, Test F1=0.6683
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=6.55s, Train Loss=0.4753, Val Loss=0.4571, Val F1=0.6792, Test Loss=0.4763, Test F1=0.6724
Validation loss decreased (-0.676282 --> -0.679245).  Saving model ...
[Epoch 05/20], Time=6.58s, Train Loss=0.4645, Val Loss=0.4517, Val F1=0.6846, Test Loss=0.4734, Test F1=0.6864
Validation loss decreased (-0.679245 --> -0.684628).  Saving model ...
[Epoch 06/20], Time=6.54s, Train Loss=0.4604, Val Loss=0.4516, Val F1=0.6792, Test Loss=0.4643, Test F1=0.6796
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=6.58s, Train Loss=0.4567, Val Loss=0.4441, Val F1=0.6867, Test Loss=0.4638, Test F1=0.6875
Validation loss decreased (-0.684628 --> -0.686667).  Saving model ...
[Epoch 08/20], Time=6.61s, Train Loss=0.4572, Val Loss=0.4482, Val F1=0.6870, Test Loss=0.4627, Test F1=0.6878
Validation loss decreased (-0.686667 --> -0.686971).  Saving model ...
[Epoch 09/20], Time=6.60s, Train Loss=0.4550, Val Loss=0.4577, Val F1=0.6774, Test Loss=0.4711, Test F1=0.6848
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=6.65s, Train Loss=0.4518, Val Loss=0.4391, Val F1=0.6879, Test Loss=0.4593, Test F1=0.6914
Validation loss decreased (-0.686971 --> -0.687919).  Saving model ...
[Epoch 11/20], Time=6.62s, Train Loss=0.4527, Val Loss=0.4428, Val F1=0.6865, Test Loss=0.4623, Test F1=0.6839
EarlyStopping counter: 1 out of 5
[Epoch 12/20], Time=6.50s, Train Loss=0.4516, Val Loss=0.4402, Val F1=0.6879, Test Loss=0.4634, Test F1=0.6896
Validation loss decreased (-0.687919 --> -0.687919).  Saving model ...
[Epoch 13/20], Time=6.56s, Train Loss=0.4528, Val Loss=0.4408, Val F1=0.6892, Test Loss=0.4556, Test F1=0.6968
Validation loss decreased (-0.687919 --> -0.689211).  Saving model ...
[Epoch 14/20], Time=6.46s, Train Loss=0.4476, Val Loss=0.4455, Val F1=0.6901, Test Loss=0.4682, Test F1=0.6908
Validation loss decreased (-0.689211 --> -0.690117).  Saving model ...
[Epoch 15/20], Time=6.51s, Train Loss=0.4511, Val Loss=0.4463, Val F1=0.6914, Test Loss=0.4623, Test F1=0.6955
Validation loss decreased (-0.690117 --> -0.691438).  Saving model ...
[Epoch 16/20], Time=6.58s, Train Loss=0.4525, Val Loss=0.4500, Val F1=0.6756, Test Loss=0.4631, Test F1=0.6804
EarlyStopping counter: 1 out of 5
[Epoch 17/20], Time=6.63s, Train Loss=0.4387, Val Loss=0.4415, Val F1=0.6901, Test Loss=0.4616, Test F1=0.6828
EarlyStopping counter: 2 out of 5
[Epoch 18/20], Time=6.61s, Train Loss=0.4387, Val Loss=0.4362, Val F1=0.6924, Test Loss=0.4566, Test F1=0.6889
Validation loss decreased (-0.691438 --> -0.692432).  Saving model ...
[Epoch 19/20], Time=6.65s, Train Loss=0.4412, Val Loss=0.4442, Val F1=0.6855, Test Loss=0.4650, Test F1=0.6896
EarlyStopping counter: 1 out of 5
[Epoch 20/20], Time=6.53s, Train Loss=0.4393, Val Loss=0.4358, Val F1=0.6932, Test Loss=0.4535, Test F1=0.6929
Validation loss decreased (-0.692432 --> -0.693164).  Saving model ...
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_85_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_85_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8101472995090017
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_85_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:58:39,4,85,0.6932,0.8387,0.6943,0.6921,16,0.001508,4,3,2,3,0.207397,16,5,0.34,0.31,0.7094,83,0.6832,0.8326,0.6667,0.7005,0.01,False,OK

[I 2026-07-08 22:58:39,234] Trial 85 finished with value: 0.6931637519872814 and parameters: {'lr': 0.0015081985822696141, 'd_model': 16, 'd_ff': 4, 'e_layers': 3, 'top_k': 2, 'dropout': 0.20739660917078273, 'batch_size': 16, 'patience': 5, 'num_kernels': 3}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_86     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0019192939140734767     --e_layers 5     --d_model 128     --d_ff 8     --top_k 2     --num_kernels 6     --dropout 0.2297667531816865     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 8
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2297667531816865
dtwwarp                  : False
e_layers                 : 5
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0019192939140734767
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_86
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_86_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el5_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.0.kernels.4.weight
 - model.3.conv.0.kernels.4.bias
 - model.3.conv.0.kernels.5.weight
 - model.3.conv.0.kernels.5.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.3.conv.2.kernels.4.weight
 - model.3.conv.2.kernels.4.bias
 - model.3.conv.2.kernels.5.weight
 - model.3.conv.2.kernels.5.bias
 - model.4.conv.0.kernels.0.weight
 - model.4.conv.0.kernels.0.bias
 - model.4.conv.0.kernels.1.weight
 - model.4.conv.0.kernels.1.bias
 - model.4.conv.0.kernels.2.weight
 - model.4.conv.0.kernels.2.bias
 - model.4.conv.0.kernels.3.weight
 - model.4.conv.0.kernels.3.bias
 - model.4.conv.0.kernels.4.weight
 - model.4.conv.0.kernels.4.bias
 - model.4.conv.0.kernels.5.weight
 - model.4.conv.0.kernels.5.bias
 - model.4.conv.2.kernels.0.weight
 - model.4.conv.2.kernels.0.bias
 - model.4.conv.2.kernels.1.weight
 - model.4.conv.2.kernels.1.bias
 - model.4.conv.2.kernels.2.weight
 - model.4.conv.2.kernels.2.bias
 - model.4.conv.2.kernels.3.weight
 - model.4.conv.2.kernels.3.bias
 - model.4.conv.2.kernels.4.weight
 - model.4.conv.2.kernels.4.bias
 - model.4.conv.2.kernels.5.weight
 - model.4.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=16.13s, Train Loss=0.5261, Val Loss=0.4734, Val F1=0.6772, Test Loss=0.4854, Test F1=0.6743
Validation loss decreased (inf --> -0.677215).  Saving model ...
[Epoch 02/20], Time=15.09s, Train Loss=0.4789, Val Loss=0.4488, Val F1=0.6955, Test Loss=0.4658, Test F1=0.6975
Validation loss decreased (-0.677215 --> -0.695518).  Saving model ...
[Epoch 03/20], Time=15.11s, Train Loss=0.4665, Val Loss=0.4634, Val F1=0.6725, Test Loss=0.4700, Test F1=0.6729
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=15.09s, Train Loss=0.4629, Val Loss=0.4422, Val F1=0.6832, Test Loss=0.4576, Test F1=0.6979
EarlyStopping counter: 2 out of 5
[Epoch 05/20], Time=15.19s, Train Loss=0.4704, Val Loss=0.4589, Val F1=0.6845, Test Loss=0.4780, Test F1=0.6792
EarlyStopping counter: 3 out of 5
[Epoch 06/20], Time=15.16s, Train Loss=0.4610, Val Loss=0.4602, Val F1=0.6813, Test Loss=0.4825, Test F1=0.6658
EarlyStopping counter: 4 out of 5
[Epoch 07/20], Time=15.26s, Train Loss=0.4539, Val Loss=0.4599, Val F1=0.6926, Test Loss=0.4781, Test F1=0.7079
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_86_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el5_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_86_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el5_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7986906710310966
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_86_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el5_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:01:21,4,86,0.6955,0.8334,0.7166,0.6757,128,0.001919,8,5,2,6,0.229767,16,5,0.31,0.3,0.7094,83,0.6935,0.8274,0.7023,0.6849,0.0021,False,OK

[I 2026-07-08 23:01:21,501] Trial 86 finished with value: 0.6955177743431221 and parameters: {'lr': 0.0019192939140734767, 'd_model': 128, 'd_ff': 8, 'e_layers': 5, 'top_k': 2, 'dropout': 0.2297667531816865, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_87     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 16     --train_epochs 20     --learning_rate 0.0021988164216446876     --e_layers 3     --d_model 128     --d_ff 4     --top_k 2     --num_kernels 3     --dropout 0.21488776227462175     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 4
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.21488776227462175
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0021988164216446876
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_87
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_87_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.99s, Train Loss=0.5113, Val Loss=0.4533, Val F1=0.6813, Test Loss=0.4675, Test F1=0.6861
Validation loss decreased (inf --> -0.681282).  Saving model ...
[Epoch 02/20], Time=6.89s, Train Loss=0.4714, Val Loss=0.4638, Val F1=0.6814, Test Loss=0.4714, Test F1=0.6901
Validation loss decreased (-0.681282 --> -0.681388).  Saving model ...
[Epoch 03/20], Time=6.92s, Train Loss=0.4735, Val Loss=0.4468, Val F1=0.6902, Test Loss=0.4617, Test F1=0.6912
Validation loss decreased (-0.681388 --> -0.690209).  Saving model ...
[Epoch 04/20], Time=6.86s, Train Loss=0.4663, Val Loss=0.4591, Val F1=0.6717, Test Loss=0.4653, Test F1=0.6888
EarlyStopping counter: 1 out of 4
[Epoch 05/20], Time=6.96s, Train Loss=0.4708, Val Loss=0.4511, Val F1=0.6974, Test Loss=0.4655, Test F1=0.7006
Validation loss decreased (-0.690209 --> -0.697368).  Saving model ...
[Epoch 06/20], Time=7.04s, Train Loss=0.4596, Val Loss=0.4441, Val F1=0.6984, Test Loss=0.4588, Test F1=0.6991
Validation loss decreased (-0.697368 --> -0.698413).  Saving model ...
[Epoch 07/20], Time=7.01s, Train Loss=0.4561, Val Loss=0.4649, Val F1=0.6886, Test Loss=0.4707, Test F1=0.6927
EarlyStopping counter: 1 out of 4
[Epoch 08/20], Time=6.96s, Train Loss=0.4544, Val Loss=0.4662, Val F1=0.6984, Test Loss=0.4874, Test F1=0.6965
Validation loss decreased (-0.698413 --> -0.698413).  Saving model ...
[Epoch 09/20], Time=7.01s, Train Loss=0.4550, Val Loss=0.4411, Val F1=0.7026, Test Loss=0.4612, Test F1=0.7015
Validation loss decreased (-0.698413 --> -0.702619).  Saving model ...
[Epoch 10/20], Time=7.01s, Train Loss=0.4423, Val Loss=0.4650, Val F1=0.6933, Test Loss=0.4702, Test F1=0.7070
EarlyStopping counter: 1 out of 4
[Epoch 11/20], Time=6.97s, Train Loss=0.4502, Val Loss=0.4436, Val F1=0.6942, Test Loss=0.4590, Test F1=0.7068
EarlyStopping counter: 2 out of 4
[Epoch 12/20], Time=6.95s, Train Loss=0.4425, Val Loss=0.4394, Val F1=0.6961, Test Loss=0.4477, Test F1=0.7104
EarlyStopping counter: 3 out of 4
[Epoch 13/20], Time=6.96s, Train Loss=0.4364, Val Loss=0.4573, Val F1=0.6975, Test Loss=0.4552, Test F1=0.7040
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_87_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_87_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8126022913256956
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_87_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df4_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:03:44,4,87,0.7026,0.8432,0.7261,0.6806,128,0.002199,4,3,2,3,0.214888,16,4,0.33,0.34,0.7094,83,0.6995,0.8384,0.7226,0.6778,0.0031,False,OK

[I 2026-07-08 23:03:44,450] Trial 87 finished with value: 0.7026194144838213 and parameters: {'lr': 0.0021988164216446876, 'd_model': 128, 'd_ff': 4, 'e_layers': 3, 'top_k': 2, 'dropout': 0.21488776227462175, 'batch_size': 16, 'patience': 4, 'num_kernels': 3}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_88     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0011258304219050879     --e_layers 4     --d_model 128     --d_ff 2     --top_k 2     --num_kernels 3     --dropout 0.19161518901785468     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 2
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.19161518901785468
dtwwarp                  : False
e_layers                 : 4
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0011258304219050879
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_88
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_88_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el4_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=9.62s, Train Loss=0.5293, Val Loss=0.4616, Val F1=0.6632, Test Loss=0.4721, Test F1=0.6683
Validation loss decreased (inf --> -0.663176).  Saving model ...
[Epoch 02/20], Time=8.54s, Train Loss=0.4811, Val Loss=0.4499, Val F1=0.6794, Test Loss=0.4691, Test F1=0.6800
Validation loss decreased (-0.663176 --> -0.679365).  Saving model ...
[Epoch 03/20], Time=8.59s, Train Loss=0.4704, Val Loss=0.4570, Val F1=0.6817, Test Loss=0.4754, Test F1=0.6833
Validation loss decreased (-0.679365 --> -0.681672).  Saving model ...
[Epoch 04/20], Time=8.52s, Train Loss=0.4646, Val Loss=0.4432, Val F1=0.6893, Test Loss=0.4600, Test F1=0.6787
Validation loss decreased (-0.681672 --> -0.689320).  Saving model ...
[Epoch 05/20], Time=8.65s, Train Loss=0.4600, Val Loss=0.4581, Val F1=0.6804, Test Loss=0.4756, Test F1=0.6843
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=8.73s, Train Loss=0.4540, Val Loss=0.4494, Val F1=0.7000, Test Loss=0.4669, Test F1=0.6996
Validation loss decreased (-0.689320 --> -0.700000).  Saving model ...
[Epoch 07/20], Time=8.67s, Train Loss=0.4590, Val Loss=0.4454, Val F1=0.6962, Test Loss=0.4654, Test F1=0.6855
EarlyStopping counter: 1 out of 5
[Epoch 08/20], Time=8.59s, Train Loss=0.4534, Val Loss=0.4444, Val F1=0.6922, Test Loss=0.4662, Test F1=0.6702
EarlyStopping counter: 2 out of 5
[Epoch 09/20], Time=8.51s, Train Loss=0.4503, Val Loss=0.4579, Val F1=0.6787, Test Loss=0.4749, Test F1=0.6676
EarlyStopping counter: 3 out of 5
[Epoch 10/20], Time=8.66s, Train Loss=0.4501, Val Loss=0.4380, Val F1=0.7022, Test Loss=0.4644, Test F1=0.6872
Validation loss decreased (-0.700000 --> -0.702163).  Saving model ...
[Epoch 11/20], Time=8.74s, Train Loss=0.4484, Val Loss=0.4470, Val F1=0.7026, Test Loss=0.4706, Test F1=0.6775
Validation loss decreased (-0.702163 --> -0.702609).  Saving model ...
[Epoch 12/20], Time=8.66s, Train Loss=0.4453, Val Loss=0.4446, Val F1=0.6859, Test Loss=0.4596, Test F1=0.6927
EarlyStopping counter: 1 out of 5
[Epoch 13/20], Time=8.67s, Train Loss=0.4432, Val Loss=0.4470, Val F1=0.6941, Test Loss=0.4634, Test F1=0.6852
EarlyStopping counter: 2 out of 5
[Epoch 14/20], Time=8.52s, Train Loss=0.4384, Val Loss=0.4416, Val F1=0.6977, Test Loss=0.4588, Test F1=0.6908
EarlyStopping counter: 3 out of 5
[Epoch 15/20], Time=8.57s, Train Loss=0.4398, Val Loss=0.4416, Val F1=0.6927, Test Loss=0.4712, Test F1=0.6746
EarlyStopping counter: 4 out of 5
[Epoch 16/20], Time=8.56s, Train Loss=0.4362, Val Loss=0.4549, Val F1=0.6887, Test Loss=0.4687, Test F1=0.6914
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_88_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el4_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_88_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el4_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8060556464811784
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_88_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el4_dl1_df2_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:06:55,4,88,0.7026,0.8379,0.6433,0.7739,128,0.001126,2,4,2,3,0.191615,16,5,0.41,0.3,0.7094,83,0.6629,0.8241,0.5929,0.7516,0.0397,False,OK

[I 2026-07-08 23:06:55,430] Trial 88 finished with value: 0.7026086956521739 and parameters: {'lr': 0.0011258304219050879, 'd_model': 128, 'd_ff': 2, 'e_layers': 4, 'top_k': 2, 'dropout': 0.19161518901785468, 'batch_size': 16, 'patience': 5, 'num_kernels': 3}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_89     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0011808842845465381     --e_layers 4     --d_model 32     --d_ff 8     --top_k 2     --num_kernels 6     --dropout 0.31302397145527483     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 8
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.31302397145527483
dtwwarp                  : False
e_layers                 : 4
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0011808842845465381
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_89
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_89_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el4_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.0.kernels.4.weight
 - model.3.conv.0.kernels.4.bias
 - model.3.conv.0.kernels.5.weight
 - model.3.conv.0.kernels.5.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.3.conv.2.kernels.4.weight
 - model.3.conv.2.kernels.4.bias
 - model.3.conv.2.kernels.5.weight
 - model.3.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=23.10s, Train Loss=0.5531, Val Loss=0.4647, Val F1=0.6823, Test Loss=0.4807, Test F1=0.6783
Validation loss decreased (inf --> -0.682316).  Saving model ...
[Epoch 02/20], Time=21.94s, Train Loss=0.4768, Val Loss=0.4522, Val F1=0.6876, Test Loss=0.4736, Test F1=0.6773
Validation loss decreased (-0.682316 --> -0.687603).  Saving model ...
[Epoch 03/20], Time=22.03s, Train Loss=0.4699, Val Loss=0.4666, Val F1=0.6796, Test Loss=0.4838, Test F1=0.6851
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=21.99s, Train Loss=0.4592, Val Loss=0.4953, Val F1=0.6599, Test Loss=0.5209, Test F1=0.6585
EarlyStopping counter: 2 out of 5
[Epoch 05/20], Time=21.79s, Train Loss=0.4632, Val Loss=0.4498, Val F1=0.6794, Test Loss=0.4683, Test F1=0.6804
EarlyStopping counter: 3 out of 5
[Epoch 06/20], Time=21.89s, Train Loss=0.4607, Val Loss=0.4464, Val F1=0.6845, Test Loss=0.4675, Test F1=0.6828
EarlyStopping counter: 4 out of 5
[Epoch 07/20], Time=21.78s, Train Loss=0.4571, Val Loss=0.4454, Val F1=0.6927, Test Loss=0.4632, Test F1=0.6996
Validation loss decreased (-0.687603 --> -0.692668).  Saving model ...
[Epoch 08/20], Time=22.10s, Train Loss=0.4516, Val Loss=0.4469, Val F1=0.6881, Test Loss=0.4660, Test F1=0.6887
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=22.10s, Train Loss=0.4548, Val Loss=0.4555, Val F1=0.6901, Test Loss=0.4816, Test F1=0.6999
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=22.00s, Train Loss=0.4541, Val Loss=0.4410, Val F1=0.6841, Test Loss=0.4633, Test F1=0.6964
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=21.82s, Train Loss=0.4535, Val Loss=0.4484, Val F1=0.6837, Test Loss=0.4722, Test F1=0.6880
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=22.07s, Train Loss=0.4470, Val Loss=0.4414, Val F1=0.6899, Test Loss=0.4668, Test F1=0.6769
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_89_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el4_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_89_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el4_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8044189852700491
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_89_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el4_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:12:18,4,89,0.6927,0.8322,0.707,0.6789,32,0.001181,8,4,2,6,0.313024,8,5,0.35,0.33,0.7094,83,0.6933,0.8248,0.6845,0.7023,-0.0006,False,OK

[I 2026-07-08 23:12:18,596] Trial 89 finished with value: 0.6926677067082684 and parameters: {'lr': 0.0011808842845465381, 'd_model': 32, 'd_ff': 8, 'e_layers': 4, 'top_k': 2, 'dropout': 0.31302397145527483, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_90     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0007213081113954443     --e_layers 3     --d_model 256     --d_ff 16     --top_k 2     --num_kernels 3     --dropout 0.1780265701510702     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.1780265701510702
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0007213081113954443
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_90
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_90_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=8.07s, Train Loss=0.5087, Val Loss=0.4697, Val F1=0.6738, Test Loss=0.4787, Test F1=0.6811
Validation loss decreased (inf --> -0.673780).  Saving model ...
[Epoch 02/20], Time=7.01s, Train Loss=0.4750, Val Loss=0.4991, Val F1=0.6800, Test Loss=0.5100, Test F1=0.6763
Validation loss decreased (-0.673780 --> -0.680000).  Saving model ...
[Epoch 03/20], Time=7.12s, Train Loss=0.4688, Val Loss=0.4595, Val F1=0.6891, Test Loss=0.4759, Test F1=0.7014
Validation loss decreased (-0.680000 --> -0.689103).  Saving model ...
[Epoch 04/20], Time=7.05s, Train Loss=0.4609, Val Loss=0.4788, Val F1=0.6871, Test Loss=0.4905, Test F1=0.6933
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=6.98s, Train Loss=0.4511, Val Loss=0.4739, Val F1=0.6923, Test Loss=0.4855, Test F1=0.6833
Validation loss decreased (-0.689103 --> -0.692308).  Saving model ...
[Epoch 06/20], Time=7.01s, Train Loss=0.4522, Val Loss=0.4615, Val F1=0.6937, Test Loss=0.4813, Test F1=0.6990
Validation loss decreased (-0.692308 --> -0.693750).  Saving model ...
[Epoch 07/20], Time=7.08s, Train Loss=0.4480, Val Loss=0.4464, Val F1=0.6954, Test Loss=0.4606, Test F1=0.6783
Validation loss decreased (-0.693750 --> -0.695375).  Saving model ...
[Epoch 08/20], Time=7.00s, Train Loss=0.4455, Val Loss=0.4614, Val F1=0.6906, Test Loss=0.4733, Test F1=0.6915
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=7.01s, Train Loss=0.4421, Val Loss=0.4707, Val F1=0.6476, Test Loss=0.4682, Test F1=0.6649
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=6.93s, Train Loss=0.4384, Val Loss=0.4766, Val F1=0.6824, Test Loss=0.4755, Test F1=0.6859
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=6.86s, Train Loss=0.4335, Val Loss=0.4636, Val F1=0.6859, Test Loss=0.4863, Test F1=0.6786
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=7.06s, Train Loss=0.4291, Val Loss=0.4625, Val F1=0.6759, Test Loss=0.4656, Test F1=0.6875
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_90_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_90_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.806873977086743
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_90_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:14:34,4,90,0.6954,0.8341,0.6943,0.6965,256,0.000721,16,3,2,3,0.178027,16,5,0.39,0.44,0.7094,83,0.671,0.8291,0.6616,0.6806,0.0244,False,OK

[I 2026-07-08 23:14:34,814] Trial 90 finished with value: 0.6953748006379585 and parameters: {'lr': 0.0007213081113954443, 'd_model': 256, 'd_ff': 16, 'e_layers': 3, 'top_k': 2, 'dropout': 0.1780265701510702, 'batch_size': 16, 'patience': 5, 'num_kernels': 3}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_91     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0014561367781658779     --e_layers 3     --d_model 128     --d_ff 16     --top_k 2     --num_kernels 6     --dropout 0.10911208539375908     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.10911208539375908
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0014561367781658779
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_91
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_91_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=11.11s, Train Loss=0.5128, Val Loss=0.4602, Val F1=0.6828, Test Loss=0.4720, Test F1=0.6852
Validation loss decreased (inf --> -0.682842).  Saving model ...
[Epoch 02/20], Time=9.90s, Train Loss=0.4682, Val Loss=0.4582, Val F1=0.6742, Test Loss=0.4695, Test F1=0.6876
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=9.95s, Train Loss=0.4615, Val Loss=0.4501, Val F1=0.6761, Test Loss=0.4622, Test F1=0.6649
EarlyStopping counter: 2 out of 5
[Epoch 04/20], Time=9.98s, Train Loss=0.4611, Val Loss=0.4429, Val F1=0.6875, Test Loss=0.4551, Test F1=0.7074
Validation loss decreased (-0.682842 --> -0.687500).  Saving model ...
[Epoch 05/20], Time=9.96s, Train Loss=0.4520, Val Loss=0.4397, Val F1=0.7049, Test Loss=0.4605, Test F1=0.7035
Validation loss decreased (-0.687500 --> -0.704944).  Saving model ...
[Epoch 06/20], Time=9.87s, Train Loss=0.4441, Val Loss=0.4825, Val F1=0.6937, Test Loss=0.4915, Test F1=0.7051
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=9.92s, Train Loss=0.4385, Val Loss=0.4465, Val F1=0.6931, Test Loss=0.4677, Test F1=0.6887
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=9.99s, Train Loss=0.4426, Val Loss=0.4556, Val F1=0.7024, Test Loss=0.4647, Test F1=0.7050
EarlyStopping counter: 3 out of 5
[Epoch 09/20], Time=10.06s, Train Loss=0.4317, Val Loss=0.4475, Val F1=0.6975, Test Loss=0.4658, Test F1=0.6958
EarlyStopping counter: 4 out of 5
[Epoch 10/20], Time=10.06s, Train Loss=0.4285, Val Loss=0.4432, Val F1=0.6908, Test Loss=0.4639, Test F1=0.6844
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_91_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_91_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8052373158756138
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_91_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:17:08,4,91,0.7049,0.839,0.7038,0.7061,128,0.001456,16,3,2,6,0.109112,16,5,0.31,0.28,0.7094,83,0.6934,0.8351,0.6819,0.7053,0.0115,False,OK

[I 2026-07-08 23:17:08,032] Trial 91 finished with value: 0.7049441786283892 and parameters: {'lr': 0.0014561367781658779, 'd_model': 128, 'd_ff': 16, 'e_layers': 3, 'top_k': 2, 'dropout': 0.10911208539375908, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_92     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0009225288517190945     --e_layers 3     --d_model 32     --d_ff 16     --top_k 2     --num_kernels 6     --dropout 0.005714141222569136     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 32
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.005714141222569136
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0009225288517190945
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_92
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_92_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=10.60s, Train Loss=0.5564, Val Loss=0.4708, Val F1=0.6621, Test Loss=0.4766, Test F1=0.6692
Validation loss decreased (inf --> -0.662069).  Saving model ...
[Epoch 02/20], Time=9.42s, Train Loss=0.4658, Val Loss=0.4576, Val F1=0.6785, Test Loss=0.4675, Test F1=0.6820
Validation loss decreased (-0.662069 --> -0.678514).  Saving model ...
[Epoch 03/20], Time=9.28s, Train Loss=0.4552, Val Loss=0.4691, Val F1=0.6763, Test Loss=0.4729, Test F1=0.6845
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=9.27s, Train Loss=0.4520, Val Loss=0.4461, Val F1=0.6876, Test Loss=0.4578, Test F1=0.6932
Validation loss decreased (-0.678514 --> -0.687598).  Saving model ...
[Epoch 05/20], Time=9.34s, Train Loss=0.4471, Val Loss=0.4393, Val F1=0.6995, Test Loss=0.4559, Test F1=0.6985
Validation loss decreased (-0.687598 --> -0.699507).  Saving model ...
[Epoch 06/20], Time=9.26s, Train Loss=0.4378, Val Loss=0.4382, Val F1=0.6949, Test Loss=0.4531, Test F1=0.7022
EarlyStopping counter: 1 out of 5
[Epoch 07/20], Time=9.40s, Train Loss=0.4328, Val Loss=0.4428, Val F1=0.6943, Test Loss=0.4558, Test F1=0.6943
EarlyStopping counter: 2 out of 5
[Epoch 08/20], Time=9.56s, Train Loss=0.4326, Val Loss=0.4366, Val F1=0.6887, Test Loss=0.4577, Test F1=0.6916
EarlyStopping counter: 3 out of 5
[Epoch 09/20], Time=9.65s, Train Loss=0.4285, Val Loss=0.4316, Val F1=0.6968, Test Loss=0.4527, Test F1=0.6987
EarlyStopping counter: 4 out of 5
[Epoch 10/20], Time=9.49s, Train Loss=0.4207, Val Loss=0.4374, Val F1=0.6975, Test Loss=0.4570, Test F1=0.6960
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_92_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_92_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8076923076923077
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_92_TimesNet_UEA_ftM_sl4_ll48_pl0_dm32_nh8_el3_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:19:35,4,92,0.6995,0.834,0.6783,0.722,32,0.000923,16,3,2,6,0.005714,16,5,0.4,0.32,0.7094,83,0.6881,0.8274,0.6539,0.726,0.0114,False,OK

[I 2026-07-08 23:19:35,563] Trial 92 finished with value: 0.6995073891625616 and parameters: {'lr': 0.0009225288517190945, 'd_model': 32, 'd_ff': 16, 'e_layers': 3, 'top_k': 2, 'dropout': 0.005714141222569136, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_93     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0011242327629540053     --e_layers 4     --d_model 128     --d_ff 16     --top_k 2     --num_kernels 6     --dropout 0.15823049090060382     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 16
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.15823049090060382
dtwwarp                  : False
e_layers                 : 4
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0011242327629540053
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_93
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_93_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el4_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - model.3.conv.0.kernels.0.weight
 - model.3.conv.0.kernels.0.bias
 - model.3.conv.0.kernels.1.weight
 - model.3.conv.0.kernels.1.bias
 - model.3.conv.0.kernels.2.weight
 - model.3.conv.0.kernels.2.bias
 - model.3.conv.0.kernels.3.weight
 - model.3.conv.0.kernels.3.bias
 - model.3.conv.0.kernels.4.weight
 - model.3.conv.0.kernels.4.bias
 - model.3.conv.0.kernels.5.weight
 - model.3.conv.0.kernels.5.bias
 - model.3.conv.2.kernels.0.weight
 - model.3.conv.2.kernels.0.bias
 - model.3.conv.2.kernels.1.weight
 - model.3.conv.2.kernels.1.bias
 - model.3.conv.2.kernels.2.weight
 - model.3.conv.2.kernels.2.bias
 - model.3.conv.2.kernels.3.weight
 - model.3.conv.2.kernels.3.bias
 - model.3.conv.2.kernels.4.weight
 - model.3.conv.2.kernels.4.bias
 - model.3.conv.2.kernels.5.weight
 - model.3.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=13.79s, Train Loss=0.5181, Val Loss=0.4612, Val F1=0.6792, Test Loss=0.4832, Test F1=0.6568
Validation loss decreased (inf --> -0.679245).  Saving model ...
[Epoch 02/20], Time=12.65s, Train Loss=0.4664, Val Loss=0.4490, Val F1=0.6872, Test Loss=0.4656, Test F1=0.6938
Validation loss decreased (-0.679245 --> -0.687196).  Saving model ...
[Epoch 03/20], Time=12.70s, Train Loss=0.4604, Val Loss=0.4541, Val F1=0.6913, Test Loss=0.4734, Test F1=0.6697
Validation loss decreased (-0.687196 --> -0.691318).  Saving model ...
[Epoch 04/20], Time=12.57s, Train Loss=0.4620, Val Loss=0.4791, Val F1=0.6913, Test Loss=0.4945, Test F1=0.6798
Validation loss decreased (-0.691318 --> -0.691318).  Saving model ...
[Epoch 05/20], Time=12.45s, Train Loss=0.4433, Val Loss=0.4548, Val F1=0.6780, Test Loss=0.4823, Test F1=0.6770
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=12.63s, Train Loss=0.4435, Val Loss=0.4542, Val F1=0.6839, Test Loss=0.4731, Test F1=0.6773
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=12.62s, Train Loss=0.4396, Val Loss=0.4478, Val F1=0.6975, Test Loss=0.4659, Test F1=0.6940
Validation loss decreased (-0.691318 --> -0.697531).  Saving model ...
[Epoch 08/20], Time=12.65s, Train Loss=0.4353, Val Loss=0.4667, Val F1=0.6801, Test Loss=0.4734, Test F1=0.6928
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=12.64s, Train Loss=0.4302, Val Loss=0.4604, Val F1=0.6827, Test Loss=0.4842, Test F1=0.6630
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=12.63s, Train Loss=0.4287, Val Loss=0.4455, Val F1=0.6868, Test Loss=0.4704, Test F1=0.6904
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=12.60s, Train Loss=0.4242, Val Loss=0.4601, Val F1=0.6821, Test Loss=0.4678, Test F1=0.6979
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=12.68s, Train Loss=0.4167, Val Loss=0.4550, Val F1=0.6800, Test Loss=0.4717, Test F1=0.6772
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_93_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el4_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_93_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el4_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.809328968903437
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_93_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el4_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:23:02,4,93,0.6975,0.8366,0.7197,0.6766,128,0.001124,16,4,2,6,0.15823,16,5,0.38,0.4,0.7094,83,0.6936,0.831,0.6997,0.6875,0.004,False,OK

[I 2026-07-08 23:23:02,067] Trial 93 finished with value: 0.6975308641975309 and parameters: {'lr': 0.0011242327629540053, 'd_model': 128, 'd_ff': 16, 'e_layers': 4, 'top_k': 2, 'dropout': 0.15823049090060382, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_94     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0010640463933962276     --e_layers 2     --d_model 256     --d_ff 64     --top_k 2     --num_kernels 4     --dropout 0.06913350250519144     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 256
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.06913350250519144
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0010640463933962276
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_94
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_94_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=7.31s, Train Loss=0.4980, Val Loss=0.4592, Val F1=0.6901, Test Loss=0.4784, Test F1=0.6873
Validation loss decreased (inf --> -0.690117).  Saving model ...
[Epoch 02/20], Time=6.18s, Train Loss=0.4666, Val Loss=0.4541, Val F1=0.6972, Test Loss=0.4631, Test F1=0.6902
Validation loss decreased (-0.690117 --> -0.697161).  Saving model ...
[Epoch 03/20], Time=6.25s, Train Loss=0.4618, Val Loss=0.4807, Val F1=0.6699, Test Loss=0.4886, Test F1=0.6649
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=6.29s, Train Loss=0.4531, Val Loss=0.4543, Val F1=0.6790, Test Loss=0.4658, Test F1=0.6802
EarlyStopping counter: 2 out of 5
[Epoch 05/20], Time=6.25s, Train Loss=0.4457, Val Loss=0.4670, Val F1=0.6623, Test Loss=0.4629, Test F1=0.6825
EarlyStopping counter: 3 out of 5
[Epoch 06/20], Time=6.09s, Train Loss=0.4457, Val Loss=0.4837, Val F1=0.6922, Test Loss=0.5192, Test F1=0.6801
EarlyStopping counter: 4 out of 5
[Epoch 07/20], Time=6.13s, Train Loss=0.4423, Val Loss=0.4792, Val F1=0.6752, Test Loss=0.4823, Test F1=0.6891
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_94_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_94_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8036006546644845
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_94_TimesNet_UEA_ftM_sl4_ll48_pl0_dm256_nh8_el2_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:24:37,4,94,0.6972,0.8323,0.7038,0.6906,256,0.001064,64,2,2,4,0.069134,16,5,0.37,0.35,0.7094,83,0.6769,0.834,0.6718,0.6822,0.0202,False,OK

[I 2026-07-08 23:24:37,489] Trial 94 finished with value: 0.6971608832807571 and parameters: {'lr': 0.0010640463933962276, 'd_model': 256, 'd_ff': 64, 'e_layers': 2, 'top_k': 2, 'dropout': 0.06913350250519144, 'batch_size': 16, 'patience': 5, 'num_kernels': 4}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_95     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.0020371640489758257     --e_layers 3     --d_model 128     --d_ff 32     --top_k 2     --num_kernels 4     --dropout 0.20101864035461353     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 32
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.20101864035461353
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0020371640489758257
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_95
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 4
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_95_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=14.99s, Train Loss=0.4989, Val Loss=0.5082, Val F1=0.6754, Test Loss=0.5227, Test F1=0.6762
Validation loss decreased (inf --> -0.675367).  Saving model ...
[Epoch 02/20], Time=14.15s, Train Loss=0.4836, Val Loss=0.4671, Val F1=0.6561, Test Loss=0.4857, Test F1=0.6452
EarlyStopping counter: 1 out of 5
[Epoch 03/20], Time=14.22s, Train Loss=0.4795, Val Loss=0.4559, Val F1=0.6889, Test Loss=0.4808, Test F1=0.6827
Validation loss decreased (-0.675367 --> -0.688889).  Saving model ...
[Epoch 04/20], Time=14.23s, Train Loss=0.4677, Val Loss=0.4489, Val F1=0.6923, Test Loss=0.4653, Test F1=0.6970
Validation loss decreased (-0.688889 --> -0.692308).  Saving model ...
[Epoch 05/20], Time=14.28s, Train Loss=0.4634, Val Loss=0.4709, Val F1=0.6895, Test Loss=0.4894, Test F1=0.6727
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=14.26s, Train Loss=0.4618, Val Loss=0.4342, Val F1=0.6984, Test Loss=0.4561, Test F1=0.6850
Validation loss decreased (-0.692308 --> -0.698361).  Saving model ...
[Epoch 07/20], Time=14.36s, Train Loss=0.4506, Val Loss=0.4347, Val F1=0.7000, Test Loss=0.4646, Test F1=0.6965
Validation loss decreased (-0.698361 --> -0.700000).  Saving model ...
[Epoch 08/20], Time=14.22s, Train Loss=0.4446, Val Loss=0.4531, Val F1=0.6925, Test Loss=0.4743, Test F1=0.6984
EarlyStopping counter: 1 out of 5
[Epoch 09/20], Time=14.20s, Train Loss=0.4468, Val Loss=0.4395, Val F1=0.6966, Test Loss=0.4649, Test F1=0.6982
EarlyStopping counter: 2 out of 5
[Epoch 10/20], Time=14.17s, Train Loss=0.4374, Val Loss=0.4708, Val F1=0.6790, Test Loss=0.4731, Test F1=0.6899
EarlyStopping counter: 3 out of 5
[Epoch 11/20], Time=14.03s, Train Loss=0.4376, Val Loss=0.4538, Val F1=0.6998, Test Loss=0.4702, Test F1=0.6912
EarlyStopping counter: 4 out of 5
[Epoch 12/20], Time=14.12s, Train Loss=0.4367, Val Loss=0.4414, Val F1=0.6939, Test Loss=0.4580, Test F1=0.6985
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_95_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_95_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8076923076923077
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_95_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df32_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:28:24,4,95,0.7,0.8426,0.7134,0.6871,128,0.002037,32,3,2,4,0.201019,8,5,0.28,0.3,0.7094,83,0.6903,0.8297,0.6947,0.6859,0.0097,False,OK

[I 2026-07-08 23:28:24,206] Trial 95 finished with value: 0.7 and parameters: {'lr': 0.0020371640489758257, 'd_model': 128, 'd_ff': 32, 'e_layers': 3, 'top_k': 2, 'dropout': 0.20101864035461353, 'batch_size': 8, 'patience': 5, 'num_kernels': 4}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_96     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.000743924693200876     --e_layers 3     --d_model 128     --d_ff 64     --top_k 2     --num_kernels 3     --dropout 0.2847910361707597     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 64
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.2847910361707597
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.000743924693200876
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_96
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 3
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_96_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=8.16s, Train Loss=0.5209, Val Loss=0.4523, Val F1=0.6835, Test Loss=0.4758, Test F1=0.6751
Validation loss decreased (inf --> -0.683465).  Saving model ...
[Epoch 02/20], Time=7.29s, Train Loss=0.4788, Val Loss=0.4499, Val F1=0.6849, Test Loss=0.4731, Test F1=0.6775
Validation loss decreased (-0.683465 --> -0.684887).  Saving model ...
[Epoch 03/20], Time=7.01s, Train Loss=0.4618, Val Loss=0.4612, Val F1=0.6722, Test Loss=0.4741, Test F1=0.6957
EarlyStopping counter: 1 out of 5
[Epoch 04/20], Time=7.22s, Train Loss=0.4604, Val Loss=0.4561, Val F1=0.6966, Test Loss=0.4721, Test F1=0.6929
Validation loss decreased (-0.684887 --> -0.696629).  Saving model ...
[Epoch 05/20], Time=7.12s, Train Loss=0.4535, Val Loss=0.4604, Val F1=0.6882, Test Loss=0.4830, Test F1=0.6870
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=7.18s, Train Loss=0.4569, Val Loss=0.4490, Val F1=0.6965, Test Loss=0.4712, Test F1=0.6977
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=7.01s, Train Loss=0.4505, Val Loss=0.4498, Val F1=0.6895, Test Loss=0.4701, Test F1=0.6962
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=7.11s, Train Loss=0.4469, Val Loss=0.4443, Val F1=0.6879, Test Loss=0.4589, Test F1=0.6967
EarlyStopping counter: 4 out of 5
[Epoch 09/20], Time=7.13s, Train Loss=0.4441, Val Loss=0.4796, Val F1=0.6712, Test Loss=0.4949, Test F1=0.6685
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_96_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_96_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8036006546644845
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_96_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el3_dl1_df64_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:30:20,4,96,0.6966,0.8337,0.6911,0.7023,128,0.000744,64,3,2,3,0.284791,16,5,0.5,0.39,0.7094,83,0.6825,0.8295,0.6565,0.7107,0.0141,False,OK

[I 2026-07-08 23:30:20,599] Trial 96 finished with value: 0.6966292134831461 and parameters: {'lr': 0.000743924693200876, 'd_model': 128, 'd_ff': 64, 'e_layers': 3, 'top_k': 2, 'dropout': 0.2847910361707597, 'batch_size': 16, 'patience': 5, 'num_kernels': 3}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_97     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0011140237727184164     --e_layers 3     --d_model 4     --d_ff 8     --top_k 2     --num_kernels 6     --dropout 0.22502742694112446     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 8
d_layers                 : 1
d_model                  : 4
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.22502742694112446
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0011140237727184164
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_97
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_97_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=10.31s, Train Loss=0.6917, Val Loss=0.6386, Val F1=0.4866, Test Loss=0.6435, Test F1=0.4867
Validation loss decreased (inf --> -0.486631).  Saving model ...
[Epoch 02/20], Time=9.24s, Train Loss=0.6256, Val Loss=0.5805, Val F1=0.5705, Test Loss=0.5857, Test F1=0.5634
Validation loss decreased (-0.486631 --> -0.570492).  Saving model ...
[Epoch 03/20], Time=9.23s, Train Loss=0.5804, Val Loss=0.5211, Val F1=0.6238, Test Loss=0.5272, Test F1=0.6150
Validation loss decreased (-0.570492 --> -0.623824).  Saving model ...
[Epoch 04/20], Time=9.10s, Train Loss=0.5324, Val Loss=0.4800, Val F1=0.6645, Test Loss=0.4882, Test F1=0.6748
Validation loss decreased (-0.623824 --> -0.664484).  Saving model ...
[Epoch 05/20], Time=9.17s, Train Loss=0.5059, Val Loss=0.4675, Val F1=0.6748, Test Loss=0.4770, Test F1=0.6755
Validation loss decreased (-0.664484 --> -0.674772).  Saving model ...
[Epoch 06/20], Time=9.17s, Train Loss=0.4932, Val Loss=0.4642, Val F1=0.6790, Test Loss=0.4751, Test F1=0.6788
Validation loss decreased (-0.674772 --> -0.678955).  Saving model ...
[Epoch 07/20], Time=9.15s, Train Loss=0.4910, Val Loss=0.4640, Val F1=0.6818, Test Loss=0.4759, Test F1=0.6758
Validation loss decreased (-0.678955 --> -0.681818).  Saving model ...
[Epoch 08/20], Time=9.00s, Train Loss=0.4864, Val Loss=0.4601, Val F1=0.6843, Test Loss=0.4754, Test F1=0.6773
Validation loss decreased (-0.681818 --> -0.684292).  Saving model ...
[Epoch 09/20], Time=9.29s, Train Loss=0.4799, Val Loss=0.4692, Val F1=0.6804, Test Loss=0.4876, Test F1=0.6796
EarlyStopping counter: 1 out of 5
[Epoch 10/20], Time=9.14s, Train Loss=0.4783, Val Loss=0.4566, Val F1=0.6825, Test Loss=0.4747, Test F1=0.6779
EarlyStopping counter: 2 out of 5
[Epoch 11/20], Time=9.01s, Train Loss=0.4740, Val Loss=0.4561, Val F1=0.6836, Test Loss=0.4746, Test F1=0.6802
EarlyStopping counter: 3 out of 5
[Epoch 12/20], Time=9.14s, Train Loss=0.4752, Val Loss=0.4573, Val F1=0.6833, Test Loss=0.4758, Test F1=0.6782
EarlyStopping counter: 4 out of 5
[Epoch 13/20], Time=9.23s, Train Loss=0.4713, Val Loss=0.4567, Val F1=0.6845, Test Loss=0.4750, Test F1=0.6773
Validation loss decreased (-0.684292 --> -0.684543).  Saving model ...
[Epoch 14/20], Time=9.31s, Train Loss=0.4715, Val Loss=0.4511, Val F1=0.6854, Test Loss=0.4670, Test F1=0.6806
Validation loss decreased (-0.684543 --> -0.685377).  Saving model ...
[Epoch 15/20], Time=9.22s, Train Loss=0.4746, Val Loss=0.4545, Val F1=0.6855, Test Loss=0.4691, Test F1=0.6827
Validation loss decreased (-0.685377 --> -0.685535).  Saving model ...
[Epoch 16/20], Time=9.26s, Train Loss=0.4729, Val Loss=0.4548, Val F1=0.6876, Test Loss=0.4694, Test F1=0.6863
Validation loss decreased (-0.685535 --> -0.687598).  Saving model ...
[Epoch 17/20], Time=9.27s, Train Loss=0.4667, Val Loss=0.4470, Val F1=0.6892, Test Loss=0.4628, Test F1=0.6852
Validation loss decreased (-0.687598 --> -0.689231).  Saving model ...
[Epoch 18/20], Time=9.11s, Train Loss=0.4626, Val Loss=0.4527, Val F1=0.6912, Test Loss=0.4697, Test F1=0.6897
Validation loss decreased (-0.689231 --> -0.691244).  Saving model ...
[Epoch 19/20], Time=9.20s, Train Loss=0.4637, Val Loss=0.4505, Val F1=0.6910, Test Loss=0.4635, Test F1=0.6875
EarlyStopping counter: 1 out of 5
[Epoch 20/20], Time=9.25s, Train Loss=0.4698, Val Loss=0.4502, Val F1=0.6871, Test Loss=0.4662, Test F1=0.6866
EarlyStopping counter: 2 out of 5
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_97_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_97_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.795417348608838
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_97_TimesNet_UEA_ftM_sl4_ll48_pl0_dm4_nh8_el3_dl1_df8_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:34:17,4,97,0.6912,0.8323,0.7166,0.6677,4,0.001114,8,3,2,6,0.225027,16,5,0.31,0.33,0.7094,83,0.6659,0.8247,0.7328,0.6102,0.0253,False,OK

[I 2026-07-08 23:34:17,422] Trial 97 finished with value: 0.6912442396313364 and parameters: {'lr': 0.0011140237727184164, 'd_model': 4, 'd_ff': 8, 'e_layers': 3, 'top_k': 2, 'dropout': 0.22502742694112446, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_98     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 4     --batch_size 16     --train_epochs 20     --learning_rate 0.0004415989037582618     --e_layers 2     --d_model 128     --d_ff 256     --top_k 2     --num_kernels 6     --dropout 0.11264539160574959     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 256
d_layers                 : 1
d_model                  : 128
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.11264539160574959
dtwwarp                  : False
e_layers                 : 2
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0004415989037582618
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_98
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 4
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_98_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=8.67s, Train Loss=0.5190, Val Loss=0.4518, Val F1=0.6817, Test Loss=0.4672, Test F1=0.6855
Validation loss decreased (inf --> -0.681682).  Saving model ...
[Epoch 02/20], Time=7.42s, Train Loss=0.4671, Val Loss=0.4580, Val F1=0.6848, Test Loss=0.4720, Test F1=0.6762
Validation loss decreased (-0.681682 --> -0.684800).  Saving model ...
[Epoch 03/20], Time=7.58s, Train Loss=0.4634, Val Loss=0.4437, Val F1=0.6907, Test Loss=0.4661, Test F1=0.6849
Validation loss decreased (-0.684800 --> -0.690691).  Saving model ...
[Epoch 04/20], Time=7.62s, Train Loss=0.4531, Val Loss=0.4497, Val F1=0.6995, Test Loss=0.4658, Test F1=0.6968
Validation loss decreased (-0.690691 --> -0.699523).  Saving model ...
[Epoch 05/20], Time=7.59s, Train Loss=0.4474, Val Loss=0.4386, Val F1=0.6966, Test Loss=0.4614, Test F1=0.6939
EarlyStopping counter: 1 out of 4
[Epoch 06/20], Time=7.73s, Train Loss=0.4393, Val Loss=0.4501, Val F1=0.6782, Test Loss=0.4574, Test F1=0.6891
EarlyStopping counter: 2 out of 4
[Epoch 07/20], Time=7.56s, Train Loss=0.4360, Val Loss=0.4565, Val F1=0.6946, Test Loss=0.4686, Test F1=0.7029
EarlyStopping counter: 3 out of 4
[Epoch 08/20], Time=7.63s, Train Loss=0.4377, Val Loss=0.4449, Val F1=0.6850, Test Loss=0.4676, Test F1=0.6915
EarlyStopping counter: 4 out of 4
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_98_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_98_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.8044189852700491
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_98_TimesNet_UEA_ftM_sl4_ll48_pl0_dm128_nh8_el2_dl1_df256_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:36:11,4,98,0.6995,0.8365,0.7006,0.6984,128,0.000442,256,2,2,6,0.112645,16,4,0.3,0.28,0.7094,83,0.6937,0.8339,0.6743,0.7143,0.0058,False,OK

[I 2026-07-08 23:36:11,521] Trial 98 finished with value: 0.699523052464229 and parameters: {'lr': 0.0004415989037582618, 'd_model': 128, 'd_ff': 256, 'e_layers': 2, 'top_k': 2, 'dropout': 0.11264539160574959, 'batch_size': 16, 'patience': 4, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_99     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 16     --train_epochs 20     --learning_rate 0.0011184498673760782     --e_layers 3     --d_model 16     --d_ff 512     --top_k 2     --num_kernels 6     --dropout 0.33742624737652077     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 16
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 512
d_layers                 : 1
d_model                  : 16
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.33742624737652077
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.0011184498673760782
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_99
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_99_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=18.49s, Train Loss=0.5409, Val Loss=0.4587, Val F1=0.6609, Test Loss=0.4665, Test F1=0.6734
Validation loss decreased (inf --> -0.660870).  Saving model ...
[Epoch 02/20], Time=17.42s, Train Loss=0.4920, Val Loss=0.4609, Val F1=0.6667, Test Loss=0.4695, Test F1=0.6793
Validation loss decreased (-0.660870 --> -0.666667).  Saving model ...
[Epoch 03/20], Time=17.51s, Train Loss=0.4924, Val Loss=0.4576, Val F1=0.6844, Test Loss=0.4773, Test F1=0.6650
Validation loss decreased (-0.666667 --> -0.684375).  Saving model ...
[Epoch 04/20], Time=17.56s, Train Loss=0.4855, Val Loss=0.4505, Val F1=0.6910, Test Loss=0.4703, Test F1=0.6895
Validation loss decreased (-0.684375 --> -0.690967).  Saving model ...
[Epoch 05/20], Time=17.52s, Train Loss=0.4824, Val Loss=0.4667, Val F1=0.6708, Test Loss=0.4783, Test F1=0.6817
EarlyStopping counter: 1 out of 5
[Epoch 06/20], Time=17.41s, Train Loss=0.4786, Val Loss=0.4673, Val F1=0.6688, Test Loss=0.4739, Test F1=0.6802
EarlyStopping counter: 2 out of 5
[Epoch 07/20], Time=17.47s, Train Loss=0.4748, Val Loss=0.4559, Val F1=0.6815, Test Loss=0.4659, Test F1=0.6876
EarlyStopping counter: 3 out of 5
[Epoch 08/20], Time=17.46s, Train Loss=0.4707, Val Loss=0.4596, Val F1=0.6720, Test Loss=0.4762, Test F1=0.6710
EarlyStopping counter: 4 out of 5
[Epoch 09/20], Time=17.41s, Train Loss=0.4687, Val Loss=0.4527, Val F1=0.6888, Test Loss=0.4690, Test F1=0.6795
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_99_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_99_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7962356792144026
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_99_TimesNet_UEA_ftM_sl4_ll48_pl0_dm16_nh8_el3_dl1_df512_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:39:49,4,99,0.691,0.831,0.6943,0.6877,16,0.001118,512,3,2,6,0.337426,16,5,0.31,0.25,0.7094,83,0.6805,0.8226,0.6692,0.6921,0.0105,False,OK

[I 2026-07-08 23:39:49,963] Trial 99 finished with value: 0.6909667194928685 and parameters: {'lr': 0.0011184498673760782, 'd_model': 16, 'd_ff': 512, 'e_layers': 3, 'top_k': 2, 'dropout': 0.33742624737652077, 'batch_size': 16, 'patience': 5, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

CUDA_VISIBLE_DEVICES=0 python -u /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/Time-Series-Library/run.py     --task_name classification     --is_training 1     --mode UnfrozenOptWL     --root_path /content/FraudDataset_NAS_4/     --model_id NAS_TimesNet_100     --model TimesNet     --data UEA     --data_path FraudDataset     --features M     --seq_len 4     --target OT     --gpu 0     --use_gpu 1     --patience 5     --batch_size 8     --train_epochs 20     --learning_rate 0.00013987202686605512     --e_layers 3     --d_model 48     --d_ff 128     --top_k 2     --num_kernels 6     --dropout 0.12896496722222972     --des NAS_UnfrozenOptWL_Search     --itr 1

Using GPU
Use UnfrozenOptWL
Use GPU: cuda:0
🔧 Building model and loading metadata...

========== Experiment Arguments ==========
activation               : gelu
alpha                    : 0.1
anomaly_ratio            : 0.25
augmentation_ratio       : 0
batch_size               : 8
c_out                    : 7
channel_independence     : 1
checkpoints              : ./checkpoints/
conv_channel             : 32
d_conv                   : 4
d_ff                     : 128
d_layers                 : 1
d_model                  : 48
data                     : UEA
data_path                : FraudDataset
dec_in                   : 7
decomp_method            : moving_avg
des                      : NAS_UnfrozenOptWL_Search
device                   : cuda:0
devices                  : 0,1,2,3
discdtw                  : False
discsdtw                 : False
distil                   : True
down_sampling_layers     : 0
down_sampling_method     : None
down_sampling_window     : 1
dropout                  : 0.12896496722222972
dtwwarp                  : False
e_layers                 : 3
embed                    : timeF
enc_in                   : 13
expand                   : 2
extra_tag                :
factor                   : 1
features                 : M
freq                     : h
gcn_depth                : 2
gcn_dropout              : 0.3
gpu                      : 0
gpu_type                 : cuda
individual               : False
inverse                  : False
is_training              : 1
itr                      : 1
jitter                   : False
label_len                : 48
learning_rate            : 0.00013987202686605512
loss                     : MSE
lradj                    : type1
magwarp                  : False
mask_rate                : 0.25
mode                     : UnfrozenOptWL
model                    : TimesNet
model_id                 : NAS_TimesNet_100
moving_avg               : 25
n_heads                  : 8
node_dim                 : 10
num_class                : 2
num_kernels              : 6
num_workers              : 10
p_hidden_dims            : [128, 128]
p_hidden_layers          : 2
patch_len                : 16
patience                 : 5
permutation              : False
pos                      : 1
pred_len                 : 0
propalpha                : 0.3
randompermutation        : False
root_path                : /content/FraudDataset_NAS_4/
rotation                 : False
scaling                  : False
seasonal_patterns        : Monthly
seed                     : 2
seg_len                  : 96
seq_len                  : 4
shapedtwwarp             : False
skip_channel             : 32
spawner                  : False
target                   : OT
task_name                : classification
timewarp                 : False
top_k                    : 2
top_p                    : 0.5
train_epochs             : 20
use_amp                  : False
use_dtw                  : False
use_gpu                  : True
use_multi_gpu            : False
use_norm                 : 1
wdba                     : False
windowslice              : False
windowwarp               : False
==========================================

>>>>>>>start training : classification_NAS_TimesNet_100_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0>>>>>>>>>>>>>>>>>>>>>>>>>>

✅ Trainable parameters:
 - model.0.conv.0.kernels.0.weight
 - model.0.conv.0.kernels.0.bias
 - model.0.conv.0.kernels.1.weight
 - model.0.conv.0.kernels.1.bias
 - model.0.conv.0.kernels.2.weight
 - model.0.conv.0.kernels.2.bias
 - model.0.conv.0.kernels.3.weight
 - model.0.conv.0.kernels.3.bias
 - model.0.conv.0.kernels.4.weight
 - model.0.conv.0.kernels.4.bias
 - model.0.conv.0.kernels.5.weight
 - model.0.conv.0.kernels.5.bias
 - model.0.conv.2.kernels.0.weight
 - model.0.conv.2.kernels.0.bias
 - model.0.conv.2.kernels.1.weight
 - model.0.conv.2.kernels.1.bias
 - model.0.conv.2.kernels.2.weight
 - model.0.conv.2.kernels.2.bias
 - model.0.conv.2.kernels.3.weight
 - model.0.conv.2.kernels.3.bias
 - model.0.conv.2.kernels.4.weight
 - model.0.conv.2.kernels.4.bias
 - model.0.conv.2.kernels.5.weight
 - model.0.conv.2.kernels.5.bias
 - model.1.conv.0.kernels.0.weight
 - model.1.conv.0.kernels.0.bias
 - model.1.conv.0.kernels.1.weight
 - model.1.conv.0.kernels.1.bias
 - model.1.conv.0.kernels.2.weight
 - model.1.conv.0.kernels.2.bias
 - model.1.conv.0.kernels.3.weight
 - model.1.conv.0.kernels.3.bias
 - model.1.conv.0.kernels.4.weight
 - model.1.conv.0.kernels.4.bias
 - model.1.conv.0.kernels.5.weight
 - model.1.conv.0.kernels.5.bias
 - model.1.conv.2.kernels.0.weight
 - model.1.conv.2.kernels.0.bias
 - model.1.conv.2.kernels.1.weight
 - model.1.conv.2.kernels.1.bias
 - model.1.conv.2.kernels.2.weight
 - model.1.conv.2.kernels.2.bias
 - model.1.conv.2.kernels.3.weight
 - model.1.conv.2.kernels.3.bias
 - model.1.conv.2.kernels.4.weight
 - model.1.conv.2.kernels.4.bias
 - model.1.conv.2.kernels.5.weight
 - model.1.conv.2.kernels.5.bias
 - model.2.conv.0.kernels.0.weight
 - model.2.conv.0.kernels.0.bias
 - model.2.conv.0.kernels.1.weight
 - model.2.conv.0.kernels.1.bias
 - model.2.conv.0.kernels.2.weight
 - model.2.conv.0.kernels.2.bias
 - model.2.conv.0.kernels.3.weight
 - model.2.conv.0.kernels.3.bias
 - model.2.conv.0.kernels.4.weight
 - model.2.conv.0.kernels.4.bias
 - model.2.conv.0.kernels.5.weight
 - model.2.conv.0.kernels.5.bias
 - model.2.conv.2.kernels.0.weight
 - model.2.conv.2.kernels.0.bias
 - model.2.conv.2.kernels.1.weight
 - model.2.conv.2.kernels.1.bias
 - model.2.conv.2.kernels.2.weight
 - model.2.conv.2.kernels.2.bias
 - model.2.conv.2.kernels.3.weight
 - model.2.conv.2.kernels.3.bias
 - model.2.conv.2.kernels.4.weight
 - model.2.conv.2.kernels.4.bias
 - model.2.conv.2.kernels.5.weight
 - model.2.conv.2.kernels.5.bias
 - enc_embedding.value_embedding.tokenConv.weight
 - enc_embedding.temporal_embedding.embed.weight
 - layer_norm.weight
 - layer_norm.bias
 - projection.weight
 - projection.bias
[Epoch 01/20], Time=20.39s, Train Loss=0.5417, Val Loss=0.4662, Val F1=0.6644, Test Loss=0.4755, Test F1=0.6708
Validation loss decreased (inf --> -0.664407).  Saving model ...
[Epoch 02/20], Time=19.47s, Train Loss=0.4836, Val Loss=0.4570, Val F1=0.6784, Test Loss=0.4729, Test F1=0.6816
Validation loss decreased (-0.664407 --> -0.678400).  Saving model ...
[Epoch 03/20], Time=19.38s, Train Loss=0.4681, Val Loss=0.4526, Val F1=0.6901, Test Loss=0.4699, Test F1=0.6781
Validation loss decreased (-0.678400 --> -0.690076).  Saving model ...
[Epoch 04/20], Time=19.28s, Train Loss=0.4588, Val Loss=0.4602, Val F1=0.6893, Test Loss=0.4775, Test F1=0.6850
EarlyStopping counter: 1 out of 5
[Epoch 05/20], Time=19.38s, Train Loss=0.4531, Val Loss=0.4596, Val F1=0.6878, Test Loss=0.4709, Test F1=0.6860
EarlyStopping counter: 2 out of 5
[Epoch 06/20], Time=19.33s, Train Loss=0.4533, Val Loss=0.4604, Val F1=0.6861, Test Loss=0.4797, Test F1=0.6921
EarlyStopping counter: 3 out of 5
[Epoch 07/20], Time=19.53s, Train Loss=0.4477, Val Loss=0.4462, Val F1=0.6854, Test Loss=0.4600, Test F1=0.6878
EarlyStopping counter: 4 out of 5
[Epoch 08/20], Time=19.58s, Train Loss=0.4442, Val Loss=0.4539, Val F1=0.6774, Test Loss=0.4664, Test F1=0.6746
EarlyStopping counter: 5 out of 5
Early stopping
✅ Saved loss history to ./test_results/classification_NAS_TimesNet_100_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0/loss_history.csv
✅ Saved TRAIN and VAL probabilities for gap analysis
>>>>>>>testing : classification_NAS_TimesNet_100_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test shape: torch.Size([1222, 2]) torch.Size([1222, 1])
accuracy:0.7962356792144026
✅ Saved predictions and true labels to ./test_results/classification_NAS_TimesNet_100_TimesNet_UEA_ftM_sl4_ll48_pl0_dm48_nh8_el3_dl1_df128_expand2_dc4_fc1_ebtimeF_dtTrue_NAS_UnfrozenOptWL_Search_0
==========================xxxxxxxxxxxxxxxxxx===============

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,23:43:24,4,100,0.6901,0.8322,0.7197,0.6628,48,0.00014,128,3,2,6,0.128965,8,5,0.27,0.33,0.7094,83,0.6765,0.8251,0.7023,0.6525,0.0136,False,OK

[I 2026-07-08 23:43:24,112] Trial 100 finished with value: 0.6900763358778625 and parameters: {'lr': 0.00013987202686605512, 'd_model': 48, 'd_ff': 128, 'e_layers': 3, 'top_k': 2, 'dropout': 0.12896496722222972, 'batch_size': 8, 'patience': 5, 'num_kernels': 6}. Best is trial 83 with value: 0.7093596059113301.

============================================================
🎉 BEST NAS MODEL FOUND
============================================================
Model ID: NAS_TimesNet_83
Best F1: 0.7093596059113301
Best Params: {'lr': 0.001260166653050406, 'd_model': 128, 'd_ff': 4, 'e_layers': 3, 'top_k': 2, 'dropout': 0.2274204614967979, 'batch_size': 16, 'patience': 5, 'num_kernels': 3}

============================================================
📊 ALL TRIALS RANKED BY F1
============================================================

,date,time,seq_length,trial_id,val_f1,val_auc,val_recall,val_precision,d_model,lr,d_ff,e_layers,top_k,num_kernels,dropout,batch_size,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-08,22:51:18,4,83,0.7094,0.8389,0.6879,0.7322,128,0.001260,4,3,2,3,0.227420,16,5,0.54,0.37,0.7094,83,0.6821,0.8381,0.6361,0.7353,0.0272,False,OK
1,2026-07-08,21:05:57,4,51,0.7089,0.8412,0.7134,0.7044,32,0.000791,512,2,2,6,0.277729,16,5,0.34,0.34,0.7089,51,0.6944,0.8329,0.6997,0.6892,0.0144,False,OK
2,2026-07-08,19:02:12,4,19,0.7065,0.8330,0.6783,0.7370,256,0.000619,64,2,2,6,0.047363,8,5,0.54,0.51,0.7065,19,0.6711,0.8205,0.6361,0.7102,0.0353,False,OK
3,2026-07-08,18:05:35,4,5,0.7061,0.8427,0.6847,0.7288,64,0.000411,128,3,2,4,0.208027,8,5,0.36,0.33,0.7061,5,0.6961,0.8342,0.6616,0.7345,0.0100,False,OK
4,2026-07-08,18:41:26,4,15,0.7057,0.8396,0.6911,0.7209,48,0.000837,128,2,2,6,0.174002,8,5,0.49,0.39,0.7061,5,0.6736,0.8241,0.6590,0.6888,0.0321,False,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026-07-08,20:26:40,4,40,0.6430,0.7762,0.6624,0.6246,2,0.002128,64,3,2,4,0.098304,8,4,0.29,0.21,0.7065,19,0.6197,0.7640,0.6489,0.5930,0.0233,False,OK
96,2026-07-08,18:00:11,4,3,0.5705,0.7322,0.5860,0.5559,2,0.001000,2,2,2,6,0.000000,16,3,0.42,0.34,0.6834,2,0.5592,0.7283,0.6005,0.5233,0.0113,True,OK
97,2026-07-08,20:21:56,4,38,0.5239,0.6778,0.6624,0.4333,2,0.000703,512,2,2,4,0.017976,8,5,0.36,0.43,0.7065,19,0.5251,0.6724,0.6794,0.4279,-0.0011,False,OK
98,2026-07-08,20:53:37,4,48,0.5156,0.6615,0.8408,0.3718,2,0.000451,128,2,2,4,0.215956,16,5,0.39,0.39,0.7065,19,0.5238,0.6608,0.8524,0.3781,-0.0082,False,OK
99,2026-07-08,18:01:52,4,4,0.5133,0.4349,0.9522,0.3514,2,0.000232,4,3,2,4,0.244741,16,3,0.43,0.43,0.6834,2,0.5184,0.4352,0.9669,0.3541,-0.0051,False,OK

============================================================
📈 MODEL SIZE vs PERFORMANCE ANALYSIS
============================================================

Performance by d_model:
                  Avg_F1    Max_F1  Trials
params_d_model
2               0.553274  0.642968       5
4               0.681756  0.696203       9
8               0.686050  0.698758       4
16              0.688084  0.699700       8
32              0.696097  0.708861      17
48              0.696852  0.705691      15
64              0.696596  0.706076      12
128             0.699317  0.709360      20
256             0.697377  0.706468      10

💾 Results saved to: /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/results/NAS_v2/nas_timesnet_results_WL4.csv

#freeze

In [27]:
%pip freeze > "{project_path}requirement/freez/NASEnhancedPretraindMLModleAdvance-lock.txt"

In [28]:
end = time.time()
elapsed = end - start_time

hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)

print(f"Total Time = {hours}h {minutes}m {seconds}s")

Total Time = 5h 57m 12s