This notebook for finding best parmter on LSTM

This is to find best parm based on LSTM

#**Pre-request**

##Mount google drive

In [1]:
### **Mount** Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##Install pakages

In [2]:
#Install pakages
project_path = "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/"
!cat "{project_path}requirement/Install/NASEnhancedPretraindMLModleAdvance.txt"
!pip install  -r "{project_path}requirement/Install/NASEnhancedPretraindMLModleAdvance.txt" --no-cache-dir
%cd $project_path

torch
transformers
huggingface_hub
datasets
timm
patool
sktime
reformer_pytorch
optuna
ptflopsRequirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2.11.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (5.12.1)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.20.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (4.0.0)
Requirement already satisfied: timm in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 5)) (1.0.27)
Collecting patool (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 6))
  Downloading patool-4.0.5-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting sktime (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7))
  Downloading sktime-1.0.1-py3-none-any.whl.metadata (28 kB)
Collecting reformer_pytorch (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading reformer_pytorch-1.4.4-py3-none-any.whl.metadata (764 bytes)
Collecting optuna (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting ptflops (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 10))
  Downloading ptflops-0.7.5-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.29.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (0.28.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (0.70.16)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from timm->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 5)) (0.26.0+cu128)
Requirement already satisfied: joblib<1.6,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.5.3)
Collecting scikit-base<1.1.0,>=1.0.0 (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7))
  Downloading scikit_base-1.0.2-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: scikit-learn<1.8.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.6.1)
Requirement already satisfied: scipy<2.0.0,>=1.2 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.16.3)
Collecting axial-positional-embedding>=0.1.0 (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading axial_positional_embedding-0.3.12-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8)) (0.8.2)
Collecting local-attention (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading local_attention-1.11.2-py3-none-any.whl.metadata (929 bytes)
Collecting product-key-memory (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading product_key_memory-0.3.0-py3-none-any.whl.metadata (4.9 kB)
Collecting alembic>=1.5.0 (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9)) (2.0.51)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9)) (1.1.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.5.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.9.0.post0)

##Import  libs

In [3]:
# =====================================================
# 📦 Standard Library
# =====================================================
import os
import sys
import time
import logging
import hashlib
import shutil
import subprocess
import warnings
from datetime import datetime

# Start timer
start_time = time.time()

# =====================================================
# 🧮 Data & Visualization
# =====================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yaml

# Pandas display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# =====================================================
# ⚙️ Machine Learning - Scikit-learn
# =====================================================
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler
from sklearn.utils import class_weight
from sklearn.covariance import EmpiricalCovariance
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)

# =====================================================
# 🌲 XGBoost
# =====================================================
from xgboost import XGBClassifier
import joblib

# =====================================================
# 🔥 Deep Learning - PyTorch
# =====================================================
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from torch.cuda.amp import autocast

# =====================================================
# 🤖 Deep Learning - TensorFlow / Keras
# =====================================================
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Dense, Masking, Dropout, Layer
from tensorflow.keras.optimizers import Adam

# =====================================================
# 🤗 Transformers & Time Series
# =====================================================
from transformers import AutoModel
from sktime.datasets import load_from_tsfile_to_dataframe
# from mamba_ssm import Mamba  # Uncomment if needed

# =====================================================
# 🧠 Explainability
# =====================================================
import shap

# =====================================================
# 📊 Google Colab Specific
# =====================================================
from google.colab import data_table
data_table.enable_dataframe_formatter()
try:
    from google.colab import data_table
    data_table.enable_dataframe_formatter()
    data_table.DataTable.max_columns = 50
    data_table.DataTable.max_rows = 150
except ImportError:
    pass
from tqdm import tqdm

print("✅ All imports loaded successfully!")

✅ All imports loaded successfully!

##Confirmation setup

In [4]:
# =====================================================
# 🎲 Random Seeds (Reproducibility)
# =====================================================
!nvidia-smi                # confirm GPU
!pip show torch  # confirm versions
torch.manual_seed(42)
np.random.seed(42)

Thu Jul  9 11:31:05 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   27C    P0             44W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Name: torch
Version: 2.11.0+cu128
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org
Author:
Author-email: PyTorch Team <packages@pytorch.org>
License: BSD-3-Clause
Location: /usr/local/lib/python3.12/dist-packages
Requires: cuda-bindings, cuda-toolkit, filelock, fsspec, jinja2, networkx, nvidia-cudnn-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvshmem-cu12, setuptools, sympy, triton, typing-extensions
Required-by: accelerate, axial_positional_embedding, CoLT5-attention, fastai, hyper-connections, local-attention, peft, product_key_memory, ptflops, reformer-pytorch, sentence-transformers, timm, torch-einops-utils, torchdata, torchvision

## Enable Config

In [5]:

logger = logging.getLogger(__name__)

def load_config(config_path="configs/baseline.yaml"):
    """Load YAML config file and expand ${root_path} placeholders."""
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    logger.info(f"✅ Loaded config from {config_path}")

    # --- Expand ${root_path} placeholders ---
    root = config.get("root_path", "")

    def expand_paths(obj):
        if isinstance(obj, dict):
            return {k: expand_paths(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [expand_paths(i) for i in obj]
        elif isinstance(obj, str) and "${root_path}" in obj:
            return obj.replace("${root_path}", root)
        else:
            return obj

    config = expand_paths(config)
    return config
config = load_config(os.path.join(project_path, "configs", "baseline.yaml"))

## Set Variables

In [6]:


#limit = config['ML']['limit']

# ==========================================================
# UNIFIED HYPERPARAMETERS (Match TimesNet NAS Best)
# ==========================================================
# ==========================================================
# 🔧 UNIFIED HYPERPARAMETERS (Match TimesNet NAS Best)
# ==========================================================

# ----------------------------------------------------------
# 📏 Sequence Settings
# ----------------------------------------------------------
max_seq_len = 6                  # Maximum sequence length
recent_mode = False               # False → oldest mode, True → recent-window mode
nas_epochs = 20
n_trials_rf_xgb = 100




# ----------------------------------------------------------
# 📊 Evaluation Settings
# ----------------------------------------------------------
threshold = 0.5                   # Default classification threshold
opt_metric = "f1"                 # Optimization metric for model selection
early_stop_metric = 'val_accuracy'# Metric for early stopping
correlation_threshold = 0.85      # Feature correlation threshold


# ----------------------------------------------------------
# 💾 Paths
# ----------------------------------------------------------
model_path = config['ML']['models']

# ----------------------------------------------------------
# 🔄 Training State (Reset before each model)
# ----------------------------------------------------------
best_threshold = 0.5              # Best threshold (general)

# ==========================================================
# ✅ Configuration Summary
# ==========================================================
print("="*60)
print("📋 CONFIGURATION SUMMARY")
print("="*60)
print(f"  Sequence length:  {max_seq_len}")
print(f"  Mode:             {'Recent' if recent_mode else 'Oldest'}")
print(f"  Threshold:        {threshold}")
print(f"  Model path:       {model_path}")
print("="*60)

# Global unified results table for all models
results_table = pd.DataFrame(columns=["Round", "AUC", "Recall", "F1", "Model"])
summary = pd.DataFrame(
    columns=[
        "Model",
        "AUC",
        "Recall",
        "Precision",
        "F1",
        "threshold"
    ]
)

============================================================
📋 CONFIGURATION SUMMARY
============================================================
  Sequence length:  6
  Mode:             Oldest
  Threshold:        0.5
  Model path:       /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/models/
============================================================

##Split users level

In [7]:

# user_path = config['ML']['Events']['base_path'] + config['ML']['Events']['files']['user']
# df_user = pd.read_csv(user_path)
# print(f"✅ Loaded transactional user dataset: {df_user.shape}")



# # Aggregate to one row per user (max label = 1 if any fraud)
# user_labels = df_user.groupby("phone_no_m")["label"].max()
# print(f"👥 Unique users for splitting: {len(user_labels)}")

# # ==============================================================
# # 2️⃣ Create user-level split (stratified, no leakage)
# # ==============================================================

# fraud_users = user_labels[user_labels == 1].index
# normal_users = user_labels[user_labels == 0].index

# fraud_train, fraud_test = train_test_split(fraud_users, test_size=0.2, random_state=42)
# normal_train, normal_test = train_test_split(normal_users, test_size=0.2, random_state=42)

# train_users = set(fraud_train) | set(normal_train)
# test_users  = set(fraud_test)  | set(normal_test)

# # ==============================================================
# # 3️⃣ Save unified split (shared across LSTM / RF / XGB)
# # ==============================================================

# split_dir = "splits/shared_user_split_v1"
# os.makedirs(split_dir, exist_ok=True)

# pd.DataFrame({"phone_no_m": sorted(train_users)}).to_csv(f"{split_dir}/train_users.csv", index=False)
# pd.DataFrame({"phone_no_m": sorted(test_users)}).to_csv(f"{split_dir}/test_users.csv", index=False)

# # ==============================================================
# # 4️⃣ Summary
# # ==============================================================

# print("\n👥 Users Summary:")
# print(f"   Total : {len(user_labels):,}")
# print(f"   Fraud : {len(fraud_users):,} ({len(fraud_users)/len(user_labels)*100:.2f}%)")
# print(f"   Normal: {len(normal_users):,} ({len(normal_users)/len(user_labels)*100:.2f}%)")

# print("\n📂 Split saved to /splits/:")
# print(f"   Train users: {len(train_users)}")
# print(f"   Test  users: {len(test_users)}")
# print(f"   Fraud ratio train: {len(fraud_train)/len(train_users)*100:.2f}%")
# print(f"   Fraud ratio test : {len(fraud_test)/len(test_users)*100:.2f}%")

## Helpers

### evaluate_global

In [8]:
def evaluate_global(model, X_test, y_test, model_name="Model", threshold=0.5):
    """
    Generic evaluator for both classic ML models and neural networks.
    """
    print(f"\n📊 Evaluation threshold is: {threshold}")

    # ---- Predict probabilities ----
    if hasattr(model, "predict_proba"):
        # For sklearn-style models
        y_pred_prob = model.predict_proba(X_test)[:, 1]
    else:
        # For neural nets (e.g., Keras)
        preds = model.predict(X_test)
        if preds.shape[-1] == 2:
            # 2-class softmax output
            y_pred_prob = preds[:, 1]
        else:
            # Single sigmoid output
            y_pred_prob = preds.ravel()

    # ... rest of function unchanged
    # ---- Predict classes ----
    y_pred = (y_pred_prob > threshold).astype(int)

    # ---- Metrics ----
    auc = roc_auc_score(y_test, y_pred_prob)
    #recall = recall_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred, zero_division=0)

    precision = precision_score(y_test, y_pred, zero_division=0)
    #f1 = f1_score(y_test, y_pred)
    f1     = f1_score(y_test, y_pred, zero_division=0)

    report = classification_report(y_test, y_pred, digits=4)
    cm = confusion_matrix(y_test, y_pred)

    # ---- Display ----
    print(f"\n📊 Classification Report — {model_name}")
    print(report)
    print(f"AUC: {auc:.4f} | Recall: {recall:.4f} | Precision: {precision:.4f} | F1: {f1:.4f}")

    # ---- Confusion Matrix ----
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Normal (0)", "Fraud (1)"])
    disp.plot(cmap="Blues")
    plt.title(f"Confusion Matrix — {model_name}")
    plt.grid(False)
    plt.show()

    # ---- Summary Dictionary ----
    return {
        "Model": model_name,
        "AUC": auc,
        "Recall": recall,
        "Precision": precision,
        "F1": f1,
        "threshold": threshold
    }

### append_to_summary

In [9]:

def append_to_summary(summary, model_name, results):
    """
    Appends or updates the summary table with model results.
    Works with both capitalized and lowercase keys automatically.
    """
    # ✅ Create summary DataFrame if missing
    if summary is None or not isinstance(summary, pd.DataFrame):
          summary = pd.DataFrame(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])
    # Ensure "Model" column exists (prevents KeyError)
    if "Model" not in summary.columns:
        summary = pd.DataFrame(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])

    # ✅ Normalize key names to lowercase
    results = {k.lower(): v for k, v in results.items()}

    # ✅ Remove any existing row for the same model
    summary = summary[summary["Model"] != model_name]

    # ✅ Add new row (robust to missing values)
    row = {
        "Model": model_name,
        "AUC": round(results.get("auc", np.nan), 4) if not pd.isna(results.get("auc", np.nan)) else np.nan,
        "Recall": round(results.get("recall", np.nan), 4) if not pd.isna(results.get("recall", np.nan)) else np.nan,
        "Precision": round(results.get("precision", np.nan), 4) if not pd.isna(results.get("precision", np.nan)) else np.nan,
        "F1": round(results.get("f1", np.nan), 4) if not pd.isna(results.get("f1", np.nan)) else np.nan,
        "Threshold": round(results.get("threshold", np.nan), 4) if not pd.isna(results.get("threshold", np.nan)) else np.nan
    }


    # ✅ Append and reindex
    summary = pd.concat([summary, pd.DataFrame([row])], ignore_index=True)
    summary = summary.reindex(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])
    return summary

### find_best_threshold

In [10]:
def find_best_threshold(y_true, probs, low=0.2, high=0.8, n=61):
    best_f1 = -1.0
    best_thr = 0.5
    for thr in np.linspace(low, high, n):
        preds = (probs >= thr).astype(int)
        f1 = f1_score(y_true, preds, zero_division=0)
        if f1 > best_f1:
            best_f1 = f1
            best_thr = thr
    return best_thr, best_f1


def get_timesnet_val_threshold(results_dir):
    val_prob_path = os.path.join(results_dir, "val_prob.npy")
    val_true_path = os.path.join(results_dir, "val_true.npy")

    if not os.path.exists(val_prob_path) or not os.path.exists(val_true_path):
        raise FileNotFoundError(
            f"Missing validation probability files in {results_dir}. "
            f"Expected val_prob.npy and val_true.npy"
        )

    val_probs = np.load(val_prob_path)
    val_true = np.load(val_true_path)

    best_thr, best_f1 = find_best_threshold(val_true, val_probs)
    return best_thr, best_f1

###Drop and select features

In [11]:
def prepare_features(df):
    """
    Selects only the explicitly defined features for model training.
    You control which features are used by editing 'selected_features' below.
    """

    # --- Define selected features manually ---
    selected_features = [
        "window_size", "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
       "voc_avg_duration", "voc_max_duration", "voc_std_duration", "voc_active_days",
       "voc_active_hours", "sms_total_msgs", "sms_unique_contacts", "sms_active_hours",
       "sms_calltype_ratio", "app_months_active", "app_total_flow", "app_avg_flow",
       "app_std_flow", "app_unique_apps_mean", "app_unique_apps_max", "user_months_active",
        "arpu_mean", "arpu_std", "arpu_max", "idcard_cnt", "snapshot_round"
   ]
  #  selected_features = [
   #     "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
    #   "voc_avg_duration", "voc_max_duration", "voc_std_duration", "voc_active_days",
     # "voc_active_hours", "sms_total_msgs", "sms_unique_contacts", "sms_active_hours",
     #"sms_calltype_ratio", "idcard_cnt"
    #]
   # selected_features = [
    #    "voc_active_days",
    #"voc_active_hours",
    #"voc_unique_contacts",
    #"sms_calltype_ratio",
    #"sms_active_hours" ]


    # ✅ You can manually remove or comment out features here
    # For example:
    # selected_features = [f for f in selected_features if not (f.startswith("app_") or f.startswith("arpu_"))]

    # --- Keep only existing columns ---
    available = [f for f in selected_features if f in df.columns]
    missing = [f for f in selected_features if f not in df.columns]

    X = df[available].copy()

    #print(f"\n📊 Final features used ({len(available)}): {available}")
    if missing:
        print(f"⚠️ Missing columns not found in data: {missing}")

    return X

### Compare

In [12]:

def plot_progressive_results(
    results_table,
    metrics=("AUC", "Recall", "F1"),
    round_col=None,
    figsize=(14, 6)
):
    """
    Plot progressive evaluation metrics per round for multiple models.

    Parameters
    ----------
    results_table : pd.DataFrame
        Must contain columns: Model, metrics, and either Round or input_size
    metrics : tuple
        Metrics to plot (default: AUC, Recall, F1)
    round_col : str or None
        Column name for x-axis. If None, auto-detects.
    figsize : tuple
        Figure size for plots
    """

    # --------------------------------------------------
    # Auto-detect round column
    # --------------------------------------------------
    if round_col is None:
        if "Round" in results_table.columns:
            round_col = "Round"
        elif "input_size" in results_table.columns:
            round_col = "input_size"
        else:
            raise ValueError("No Round or input_size column found.")

    # --------------------------------------------------
    # Sort results (important for correct curves)
    # --------------------------------------------------
    results_table = results_table.sort_values(
        by=[round_col, "Model"],
        ascending=True
    ).reset_index(drop=True)


    # --------------------------------------------------
    # Plot each metric
    # --------------------------------------------------
    for metric in metrics:

        plt.figure(figsize=figsize)

        for model in results_table["Model"].unique():
            subset = (
                results_table[results_table["Model"] == model]
                .sort_values(by=round_col)
            )

            plt.plot(
                subset[round_col],
                subset[metric],
                marker="o",
                markersize=6,
                linewidth=2,
                label=model,
                alpha=0.85
            )

        plt.title(f"{metric} per {round_col}", fontsize=18)
        plt.xlabel(round_col, fontsize=14)
        plt.ylabel(metric, fontsize=14)
        plt.grid(True, linestyle="--", alpha=0.4)

        # Legend outside
        plt.legend(
            loc="upper center",
            bbox_to_anchor=(0.5, -0.12),
            ncol=4,
            fontsize=10
        )

        plt.tight_layout(rect=[0, 0.1, 1, 1])
        plt.show()
    display(results_table)

    return results_table

###get_key_rounds

In [13]:
# ============================================================
# 🔬 SCIENTIFIC KEY ROUNDS SELECTION
# ============================================================

def get_key_rounds(max_seq_len, method="linear", n_points=5):
    """
    Generate scientifically meaningful evaluation checkpoints.

    Args:
        max_seq_len: Maximum sequence length (16, 100, 300, etc.)
        method: Selection strategy
            - "linear": Equal spacing (1, 25%, 50%, 75%, 100%)
            - "logarithmic": More points early (where changes happen fast)
            - "sqrt": Square root spacing (balanced)
            - "percentile": Fixed percentages
        n_points: Number of evaluation points (default 5)

    Returns:
        List of round numbers to evaluate
    """

    if max_seq_len <= n_points:
        # If sequence is short, evaluate all rounds
        return list(range(1, max_seq_len + 1))

    if method == "linear":
        # Equal spacing: 1, 25%, 50%, 75%, 100%
        rounds = np.linspace(1, max_seq_len, n_points)

    elif method == "logarithmic":
        # More points early (fraud detection often shows early signal)
        # Log scale: 1, 2, 4, 8, 16 style
        rounds = np.logspace(0, np.log10(max_seq_len), n_points)

    elif method == "sqrt":
        # Square root spacing (balanced between linear and log)
        rounds = np.square(np.linspace(1, np.sqrt(max_seq_len), n_points))

    elif method == "percentile":
        # Fixed percentages: 1st event, 10%, 25%, 50%, 75%, 100%
        percentages = [0, 0.1, 0.25, 0.5, 0.75, 1.0]
        rounds = [max(1, int(p * max_seq_len)) for p in percentages]
        return sorted(set(rounds))  # Remove duplicates

    elif method == "early_focus":
        # Focus on early detection (more points in first half)
        # Useful for fraud detection where early signal matters
        early = np.linspace(1, max_seq_len * 0.5, n_points - 2)
        late = [max_seq_len * 0.75, max_seq_len]
        rounds = np.concatenate([early, late])

    else:
        raise ValueError(f"Unknown method: {method}")

    # Convert to integers, ensure valid range, remove duplicates
    rounds = [int(round(r)) for r in rounds]
    rounds = [max(1, min(r, max_seq_len)) for r in rounds]
    rounds = sorted(set(rounds))

    # Always include 1 and max_seq_len
    if 1 not in rounds:
        rounds = [1] + rounds
    if max_seq_len not in rounds:
        rounds = rounds + [max_seq_len]

    return rounds

##key_rounds = get_key_rounds(max_seq_len, method=method, n_points=n_points)
##print(f"📊 Evaluating rounds: {key_rounds}")
#print(f"   Total: {len(key_rounds)} rounds instead of {max_seq_len}")

#ML Modules

### Feature Importance

In [14]:
# def plot_feature_importance(model, X_train, model_name="Model", top_n=20):
#     """
#     Plot feature importance for tree-based models (XGBoost, RandomForest).
#     """


#     # Handle model type
#     if hasattr(model, "get_booster"):  # XGBoost
#         importance = model.get_booster().get_score(importance_type='gain')
#         fi = pd.DataFrame({
#             'Feature': list(importance.keys()),
#             'Importance': list(importance.values())
#         })
#     elif hasattr(model, "feature_importances_"):  # RandomForest
#         fi = pd.DataFrame({
#             'Feature': X_train.columns,
#             'Importance': model.feature_importances_
#         })
#     else:
#         raise ValueError(f"{model_name} does not support feature importance extraction.")

#     # Sort and plot
#     fi = fi.sort_values(by='Importance', ascending=False)
#     display(fi.head(10))

#     plt.figure(figsize=(10,6))
#     plt.barh(fi['Feature'][:top_n][::-1], fi['Importance'][:top_n][::-1])
#     plt.title(f'📊 {model_name} Feature Importance (Top {top_n})')
#     plt.xlabel('Importance')
#     plt.ylabel('Feature')
#     plt.grid(alpha=0.4)
#     plt.tight_layout()
#     plt.show()

#     return fi

# fi_xgb = plot_feature_importance(xgb_model, snap_X_train, "XGBoost")
# fi_rf = plot_feature_importance(rf_model, snap_X_train, "Random Forest")

### Load

In [15]:
def load_raw_datasets(config):


    if "ML" in config and "Events" in config["ML"]:
        events_cfg = config["ML"]["Events"]
    else:
        events_cfg = config["Events"]

    base = events_cfg["base_path"]
    files = events_cfg["files"]

    # --- Load all datasets ---
    df_voc = pd.read_csv(os.path.join(base, files["voc"]))
    df_sms = pd.read_csv(os.path.join(base, files["sms"]))
    df_app = pd.read_csv(os.path.join(base, files["app"]))
    df_user = pd.read_csv(os.path.join(base, files["user"]))

    # --- Normalize timestamps and add source column ---
    for df, src in [(df_voc, "VOC"), (df_sms, "SMS"), (df_app, "APP"), (df_user, "USER")]:
        df["source"] = src
        ts_col = [c for c in df.columns if "time" in c.lower()][0]
        df.rename(columns={ts_col: "event_time"}, inplace=True)
        df["event_time"] = pd.to_datetime(df["event_time"], errors="coerce")

    print("✅ Raw datasets loaded and timestamp-normalized.")
    return df_voc, df_sms, df_app, df_user

df_voc, df_sms, df_app, df_user = load_raw_datasets(config)

✅ Raw datasets loaded and timestamp-normalized.

### Build timeline (events)

In [16]:
def merge_and_prepare_events(df_voc, df_sms, df_app, df_user):

    # --- 1️⃣ Normalize USER dataset ---
    if 'label' not in df_user.columns:
        raise KeyError("❌ 'label' column not found in user dataset")

    # Ensure numeric consistency
    df_user['label'] = df_user['label'].fillna(0).astype(int)
    df_user['idcard_cnt'] = df_user['idcard_cnt'].fillna(0).astype(float)
    df_user['arpu_value'] = df_user['arpu_value'].fillna(0).astype(float)

    # --- 2️⃣ Extract static info for merging (label + sim count only) ---
    #static_user_info = df_user.groupby("phone_no_m", as_index=False)[["label", "idcard_cnt"]].max()
    # --- 2️⃣ Extract static info from the RAW user table (covers all 6,106 users) ---
    lbl_cfg = config["ML"]["labels"]
    raw_user = pd.read_csv(os.path.join(lbl_cfg["base_path"], lbl_cfg["file"]))
    static_user_info = raw_user[["phone_no_m", "label", "idcard_cnt"]].drop_duplicates("phone_no_m")
    static_user_info["label"] = static_user_info["label"].astype(int)
    static_user_info["idcard_cnt"] = static_user_info["idcard_cnt"].fillna(0).astype(float)

    # --- 3️⃣ Merge static info into other event tables ---
    df_voc = df_voc.merge(static_user_info, on="phone_no_m", how="left")
    df_sms = df_sms.merge(static_user_info, on="phone_no_m", how="left")
    df_app = df_app.merge(static_user_info, on="phone_no_m", how="left")


    # --- 4️⃣ Combine all transactional event sources ---
    # include df_user itself since arpu_value is event-like
    events = pd.concat([df_voc, df_sms, df_app, df_user], ignore_index=True)

    # --- 5️⃣ Fill and order ---
    #events["label"] = events["label"].fillna(0).astype(int)
    missing = int(events["label"].isna().sum())
    assert missing == 0, f"{missing} events have no label — label merge is broken"
    events["label"] = events["label"].astype(int)

    events["event_time"] = pd.to_datetime(events["event_time"], errors="coerce")
    events = events.sort_values(["phone_no_m", "event_time"]).reset_index(drop=True)

    # --- 6️⃣ Summary ---
    print("\n🔎 Feature Summary per Source:")
    for src, df in [("VOC", df_voc), ("SMS", df_sms), ("APP", df_app), ("USER", df_user)]:
        print(f"\n📂 Source: {src}")
        print(f"   Events: {len(df):,}")
        print(f"   Users : {df['phone_no_m'].nunique():,}")
        print(f"   Columns ({len(df.columns)}): {', '.join(df.columns)}")

    print("\n📊 Combined Dataset Summary:")
    print(f"   Total events: {len(events):,}")
    print(f"   Unique users: {events['phone_no_m'].nunique():,}")
    print(f"   Fraud ratio: {events['label'].mean()*100:.2f}%")
    user_labels = events.groupby("phone_no_m")["label"].max()
    print(f"   Fraud users: {int(user_labels.sum()):,} / {user_labels.size:,} ({user_labels.mean()*100:.2f}%)")

    return events

events = merge_and_prepare_events(df_voc, df_sms, df_app, df_user)

display(events.head())

🔎 Feature Summary per Source:

📂 Source: VOC
   Events: 5,015,430
   Users : 6,025
   Columns (11): phone_no_m, opposite_no_m, calltype_id, event_time, call_dur, city_name, county_name, imei_m, source, label, idcard_cnt

📂 Source: SMS
   Events: 6,848,509
   Users : 6,103
   Columns (7): phone_no_m, opposite_no_m, calltype_id, event_time, source, label, idcard_cnt

📂 Source: APP
   Events: 3,283,602
   Users : 6,106
   Columns (10): phone_no_m, event_time, source, busi_name, flow, month_id, flow_norm, month_str, label, idcard_cnt

📂 Source: USER
   Events: 39,454
   Users : 5,929
   Columns (10): phone_no_m, event_time, source, month_id, arpu_value, city_name, county_name, idcard_cnt, label, month_col

📊 Combined Dataset Summary:
   Total events: 15,186,995
   Unique users: 6,106
   Fraud ratio: 24.63%
   Fraud users: 1,962 / 6,106 (32.13%)

,phone_no_m,opposite_no_m,calltype_id,event_time,call_dur,city_name,county_name,imei_m,source,label,idcard_cnt,busi_name,flow,month_id,flow_norm,month_str,arpu_value,month_col
0,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-13 16:21:53,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-13 16:21:53,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Split data based on users (fraud, not fraud)

In [17]:


# ======================================
# Clean Numeric Columns
# ======================================
events = events.copy()
numeric_cols = events.select_dtypes(include=["number"]).columns.difference(["label"])

# Replace NaN with 0 for numeric fields (avoids scaling issues)
events[numeric_cols] = events[numeric_cols].fillna(0)

print(f"\n📊 Numeric columns to scale ({len(numeric_cols)}): {numeric_cols.tolist()}")


# ======================================
# 2 Create / Load Shared Train-Val-Test User Split
# ======================================
split_dir = os.path.join(config["root_path"], "splits", "shared_user_split_v1")
train_split_file = f"{split_dir}/train_users.csv"
test_split_file  = f"{split_dir}/test_users.csv"
val_split_file   = f"{split_dir}/val_users.csv"

os.makedirs(split_dir, exist_ok=True)

all_split_files_exist = (
    os.path.exists(train_split_file)
    and os.path.exists(test_split_file)
    and os.path.exists(val_split_file)
)

if all_split_files_exist:
    print("📂 Using shared user split files...")
    train_users = set(pd.read_csv(train_split_file)["phone_no_m"])
    test_users  = set(pd.read_csv(test_split_file)["phone_no_m"])
    val_users   = set(pd.read_csv(val_split_file)["phone_no_m"])
else:
    print("🆕 Creating shared train/test/val user split...")

    # One label per user
    user_labels = events.groupby("phone_no_m")["label"].max()
    fraud_users = user_labels[user_labels == 1].index
    normal_users = user_labels[user_labels == 0].index

    # 1) Train/Test split (split fraud user %)
    fraud_train, fraud_test = train_test_split(
        fraud_users, test_size=0.2, random_state=42
    )
    normal_train, normal_test = train_test_split(
        normal_users, test_size=0.2, random_state=42
    )

    train_users_full = set(fraud_train) | set(normal_train)
    test_users = set(fraud_test) | set(normal_test)

    # 2) Validation split from training users only
    train_user_labels = user_labels.loc[list(train_users_full)]

    fraud_train_users = train_user_labels[train_user_labels == 1].index
    normal_train_users = train_user_labels[train_user_labels == 0].index

    fraud_tr, fraud_val = train_test_split(
        fraud_train_users, test_size=0.2, random_state=42
    )
    normal_tr, normal_val = train_test_split(
        normal_train_users, test_size=0.2, random_state=42
    )

    train_users = set(fraud_tr) | set(normal_tr)
    val_users   = set(fraud_val) | set(normal_val)

    pd.DataFrame({"phone_no_m": sorted(train_users)}).to_csv(train_split_file, index=False)
    pd.DataFrame({"phone_no_m": sorted(test_users)}).to_csv(test_split_file, index=False)
    pd.DataFrame({"phone_no_m": sorted(val_users)}).to_csv(val_split_file, index=False)

    print(f"✅ Saved shared split files to '{split_dir}/'")
# ======================================
# Split overlap checks
# ======================================
assert len(train_users & test_users) == 0, "❌ User leakage: train and test overlap"
assert len(train_users & val_users) == 0, "❌ User leakage: train and val overlap"
assert len(test_users & val_users) == 0, "❌ User leakage: test and val overlap"

print("🔒 Split overlap checks passed:")
print(f"   train ∩ test = {len(train_users & test_users)}")
print(f"   train ∩ val  = {len(train_users & val_users)}")
print(f"   test  ∩ val  = {len(test_users & val_users)}")
user_labels = events.groupby("phone_no_m")["label"].max()
print(f"   sizes  train/val/test = {len(train_users)} / {len(val_users)} / {len(test_users)}")
print(f"   fraud  train/val/test = {int(user_labels.loc[list(train_users)].sum())} / "
      f"{int(user_labels.loc[list(val_users)].sum())} / {int(user_labels.loc[list(test_users)].sum())}")
# ======================================
# Apply Split to Events
# ======================================
train_events = events[events["phone_no_m"].isin(train_users)]
test_events  = events[events["phone_no_m"].isin(test_users)]
val_events = events[events["phone_no_m"].isin(val_users)]

# Sanity checks
assert len(set(train_events["phone_no_m"]) & set(test_events["phone_no_m"])) == 0, "❌ User leakage detected!"
assert train_events["label"].nunique() == 2, "❌ Training set must contain both classes"
assert test_events["label"].nunique() == 2, "❌ Test set must contain both classes"

# --- add time gap, scaled featur ---
# for name, df in [('train_events', train_events), ('test_events', test_events)]:
#     df = df.copy()  # avoid SettingWithCopyWarning
#     df['event_time'] = pd.to_datetime(df['event_time'])
#     #df.sort_values(['phone_no_m', 'event_time'], inplace=True)
#     df = df.sort_values(['phone_no_m', 'event_time'], kind='mergesort').reset_index(drop=True)
#     df['dt_hours'] = df.groupby('phone_no_m')['event_time'].diff().dt.total_seconds() / 3600
#     df['dt_hours'] = df['dt_hours'].fillna(0)
#     df['dt_hours'] = np.log1p(df['dt_hours'])  # normalize gaps
#     if name == 'train_events':
#         train_events = df
#     else:
#         test_events = df
for name, df in [
    ('train_events', train_events),
    ('val_events', val_events),
    ('test_events', test_events)
]:
    df = df.copy()
    df['event_time'] = pd.to_datetime(df['event_time'])
    df = df.sort_values(['phone_no_m', 'event_time'], kind='mergesort').reset_index(drop=True)
    df['dt_hours'] = df.groupby('phone_no_m')['event_time'].diff().dt.total_seconds() / 3600
    df['dt_hours'] = df['dt_hours'].fillna(0)
    df['dt_hours'] = np.log1p(df['dt_hours'])

    if name == 'train_events':
        train_events = df
    elif name == 'val_events':
        val_events = df
    else:
        test_events = df


# Store unscaled events BEFORE line 895
train_events_unscaled = train_events.copy()
test_events_unscaled = test_events.copy()
val_events_unscaled = val_events.copy()


# Sanity checks
assert len(set(train_events["phone_no_m"]) & set(test_events["phone_no_m"])) == 0, "❌ User leakage detected!"
assert train_events["label"].nunique() == 2, "❌ Training set must contain both classes"
assert test_events["label"].nunique() == 2, "❌ Test set must contain both classes"
scale_cols_seq = sorted(set(train_events.select_dtypes(include=["number"]).columns) - {"label"})
scaler_seq = StandardScaler().fit(train_events[scale_cols_seq])
train_events[scale_cols_seq] = scaler_seq.transform(train_events[scale_cols_seq])
test_events[scale_cols_seq]  = scaler_seq.transform(test_events[scale_cols_seq])
val_events[scale_cols_seq]   = scaler_seq.transform(val_events[scale_cols_seq])

# ======================================
# 4️⃣ snapshot
# ======================================

# ======================================
# 4️⃣ Create Sequences (using multiple features)
# ======================================
numeric_features = [c for c in numeric_cols if c not in ["label"]]  # exclude label
if 'dt_hours' in train_events.columns:
    numeric_features.append('dt_hours')
print(f"\n📦 Features used for sequences: {numeric_features}")
feature_cols_tf = numeric_features.copy()
# 👉 Transformer feature columns: same numeric features as LSTM + source_id

if "source_id" not in feature_cols_tf:
    feature_cols_tf.append("source_id")

print("[Transformer] feature_cols_tf:", feature_cols_tf)

📊 Numeric columns to scale (6): ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt']
📂 Using shared user split files...
🔒 Split overlap checks passed:
   train ∩ test = 0
   train ∩ val  = 0
   test  ∩ val  = 0
   sizes  train/val/test = 3907 / 977 / 1222
   fraud  train/val/test = 1255 / 314 / 393

📦 Features used for sequences: ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt', 'dt_hours']
[Transformer] feature_cols_tf: ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt', 'dt_hours', 'source_id']

### Generate_snapshots_from_events

In [18]:
# ============================================================
# 🔧 OPTIMIZED SNAPSHOT GENERATION FROM EVENTS (FIXED)
# ============================================================

def generate_snapshots_from_events(
    events_df,
    users,
    r,
    max_seq_len,
    recent_mode=True
):
    """
    Generate snapshot features from events DataFrame.
    OPTIMIZED: Uses groupby instead of per-user filtering.
    """

    # 1️⃣ Filter to relevant users FIRST (huge speedup)
    events_filtered = events_df[events_df["phone_no_m"].isin(users)].copy()

    if events_filtered.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    # 2️⃣ Sort once
    events_filtered = events_filtered.sort_values(["phone_no_m", "event_time"])

    # 3️⃣ Apply selection logic per user using groupby
    def select_events(df_u):
        if recent_mode:
            df_u = df_u.tail(max_seq_len).head(r)
        else:
            df_u = df_u.head(r)
        return df_u

    selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)

    if selected.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    # 4️⃣ Aggregate features using groupby
    snapshot_rows = []

    for user, df_u in tqdm(selected.groupby("phone_no_m"), desc="Generating snapshots"):
    #for user, df_u in selected.groupby("phone_no_m"):
        row = {"phone_no_m": user}

        # Get label
        label = int(df_u["label"].max()) if "label" in df_u.columns else 0

        # --- Voice Features ---
        voc = df_u[df_u["source"] == "VOC"]
        if len(voc) > 0:
            if "call_dur" in voc.columns:
                call_dur = pd.to_numeric(voc["call_dur"], errors="coerce").fillna(0)
            else:
                call_dur = pd.Series([0])

            row["voc_total_calls"] = len(voc)
            row["voc_unique_contacts"] = voc["opposite_no_m"].nunique() if "opposite_no_m" in voc.columns else 0
            row["voc_total_duration"] = call_dur.sum()
            row["voc_avg_duration"] = call_dur.mean()
            row["voc_max_duration"] = call_dur.max()
            row["voc_std_duration"] = call_dur.std() if len(call_dur) > 1 else 0
            row["voc_active_days"] = voc["event_time"].dt.weekday.nunique()
            row["voc_active_hours"] = voc["event_time"].dt.hour.nunique()
        else:
            row.update({
                "voc_total_calls": 0, "voc_unique_contacts": 0, "voc_total_duration": 0,
                "voc_avg_duration": 0, "voc_max_duration": 0, "voc_std_duration": 0,
                "voc_active_days": 0, "voc_active_hours": 0
            })

        # --- SMS Features ---
        sms = df_u[df_u["source"] == "SMS"]
        if len(sms) > 0:
            row["sms_total_msgs"] = len(sms)
            row["sms_unique_contacts"] = sms["opposite_no_m"].nunique() if "opposite_no_m" in sms.columns else 0
            row["sms_active_hours"] = sms["event_time"].dt.hour.nunique()
            if "calltype_id" in sms.columns:
                calltype = pd.to_numeric(sms["calltype_id"], errors="coerce")
                row["sms_calltype_ratio"] = (calltype == 1).mean()
            else:
                row["sms_calltype_ratio"] = 0
        else:
            row.update({
                "sms_total_msgs": 0, "sms_unique_contacts": 0,
                "sms_active_hours": 0, "sms_calltype_ratio": 0
            })

        # --- App Features ---
        app = df_u[df_u["source"] == "APP"]
        if len(app) > 0:
            if "flow" in app.columns:
                flow = pd.to_numeric(app["flow"], errors="coerce").fillna(0)
            else:
                flow = pd.Series([0])

            row["app_months_active"] = app["month_id"].nunique() if "month_id" in app.columns else 0
            row["app_total_flow"] = flow.sum()
            row["app_avg_flow"] = flow.mean()
            row["app_std_flow"] = flow.std() if len(flow) > 1 else 0
            row["app_unique_apps_mean"] = app["busi_name"].nunique() if "busi_name" in app.columns else 0
            row["app_unique_apps_max"] = app["busi_name"].nunique() if "busi_name" in app.columns else 0
        else:
            row.update({
                "app_months_active": 0, "app_total_flow": 0, "app_avg_flow": 0,
                "app_std_flow": 0, "app_unique_apps_mean": 0, "app_unique_apps_max": 0
            })

        # --- User/ARPU Features ---
        arpu = df_u[df_u["source"] == "USER"]
        if len(arpu) > 0:
            if "arpu_value" in arpu.columns:
                arpu_val = pd.to_numeric(arpu["arpu_value"], errors="coerce")
            else:
                arpu_val = pd.Series([0])

            row["user_months_active"] = arpu["month_id"].nunique() if "month_id" in arpu.columns else 0
            row["arpu_mean"] = arpu_val.mean()
            row["arpu_std"] = arpu_val.std() if len(arpu_val) > 1 else 0
            row["arpu_max"] = arpu_val.max()
            row["idcard_cnt"] = arpu["idcard_cnt"].max() if "idcard_cnt" in arpu.columns else 0
        else:
            row.update({
                "user_months_active": 0, "arpu_mean": 0, "arpu_std": 0,
                "arpu_max": 0, "idcard_cnt": 0
            })

        # Meta features
        row["window_size"] = r
        row["snapshot_round"] = r
        row["label"] = label

        snapshot_rows.append(row)

    # Build DataFrame
    df_snapshot = pd.DataFrame(snapshot_rows).fillna(0)

    if df_snapshot.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    y = df_snapshot["label"].values
    user_ids = df_snapshot["phone_no_m"].values
    X = df_snapshot.drop(columns=["phone_no_m", "label"])

    return X, y, user_ids

#  ▶ Classic Ml Snapshot based

###### Genrate input data

In [19]:

# ============================================================
# 📋 Define snapshot feature columns (same as sequencestreaming.py)
# ============================================================

SNAPSHOT_FEATURE_COLS = [
    # Voice
    "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
    "voc_avg_duration", "voc_max_duration", "voc_std_duration",
    "voc_active_days", "voc_active_hours",
    # SMS
    "sms_total_msgs", "sms_unique_contacts", "sms_active_hours", "sms_calltype_ratio",
    # App
    "app_months_active", "app_total_flow", "app_avg_flow",
    "app_std_flow", "app_unique_apps_mean", "app_unique_apps_max",
    # User / ARPU
    "user_months_active", "arpu_mean", "arpu_std", "arpu_max", "idcard_cnt",
    # Meta
    "window_size", "snapshot_round"
]

print(f"📊 Snapshot features: {len(SNAPSHOT_FEATURE_COLS)} columns")

# ============================================================
# 🚀 RF/XGBoost - UNIFIED PIPELINE (Uses same events as LSTM)
# ============================================================


print("\n" + "="*60)
print(f"[{datetime.now()}] 🌲 RF/XGBoost Training (from events, same as LSTM)")
print("="*60)

# ============================================================
# 1️⃣ Generate training snapshots (r = max_seq_len)
# ============================================================
print(f"\n[{datetime.now()}] 📊 Generating training snapshots (r={max_seq_len})...")

X_train_snap, y_train_snap, users_train_snap = generate_snapshots_from_events(
    events_df=train_events_unscaled,
    users=train_users,
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)
neg = (y_train_snap == 0).sum()
pos = (y_train_snap == 1).sum()
XGB_scale_pos_weight = neg / pos

print(f"[{datetime.now()}] ✅ Training snapshots: {len(X_train_snap)} users, {X_train_snap.shape[1]} features")

# ============================================================
# 2️⃣ Align columns and scale
# ============================================================
print(f"[{datetime.now()}] 🔄 Scaling...")
X_train_snap = X_train_snap.reindex(columns=SNAPSHOT_FEATURE_COLS, fill_value=0)
scaler_snap = StandardScaler().fit(X_train_snap)
X_train_scaled = scaler_snap.transform(X_train_snap)
print(f"[{datetime.now()}] ✅ Scaling done")

📊 Snapshot features: 25 columns

============================================================
[2026-07-09 11:34:07.823903] 🌲 RF/XGBoost Training (from events, same as LSTM)
============================================================

[2026-07-09 11:34:07.824026] 📊 Generating training snapshots (r=6)...

/tmp/ipykernel_993/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 3907/3907 [00:11<00:00, 328.91it/s]

[2026-07-09 11:34:35.208025] ✅ Training snapshots: 3907 users, 25 features
[2026-07-09 11:34:35.208201] 🔄 Scaling...
[2026-07-09 11:34:35.214147] ✅ Scaling done

#### Show sample

In [20]:
# ============================================================
# 🔍 DEBUG: Print Sample Snapshots
# ============================================================

print("="*60)
print("🔍 SAMPLE SNAPSHOTS DEBUG")
print("="*60)

# Generate a small sample
X_sample, y_sample, users_sample = generate_snapshots_from_events(
    events_df=train_events_unscaled,
    users=list(train_users)[:10],  # Only 10 users for sample
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)

print(f"\n📊 Sample shape: {X_sample.shape}")
print(f"📊 Labels: {y_sample}")
print(f"📊 Users: {users_sample}")

# Show features
print(f"\n📋 Feature columns ({len(X_sample.columns)}):")
print(X_sample.columns.tolist())

# Show sample data
print(f"\n📊 Sample snapshots (first 5 users):")
sample_df = X_sample.copy()
sample_df['label'] = y_sample
sample_df['user'] = users_sample
sample_df = sample_df[['user', 'label'] + [c for c in sample_df.columns if c not in ['user', 'label']]]
display(sample_df.head())

# Show statistics
print(f"\n📈 Feature statistics:")
display(X_sample.describe().T)

# Show class distribution
print(f"\n📊 Class distribution:")
print(f"   Fraud (1): {sum(y_sample == 1)} ({sum(y_sample == 1)/len(y_sample)*100:.1f}%)")
print(f"   Normal (0): {sum(y_sample == 0)} ({sum(y_sample == 0)/len(y_sample)*100:.1f}%)")

============================================================
🔍 SAMPLE SNAPSHOTS DEBUG
============================================================

/tmp/ipykernel_993/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 10/10 [00:00<00:00, 315.38it/s]

📊 Sample shape: (10, 25)
📊 Labels: [0 0 1 0 0 0 1 0 0 0]
📊 Users: ['03ca40c4aa148f63dbb3beedf20c6424547d294741deb06d0a949c55c851b86e40b0e329da3cc98a3bf14100256eb283b94c0685155a3fa34b21022823536fab'
 '0a5344aa38fa437528731f1bfb3a847010984b29b7c82736b3f15d678ae57ba90fb8ca373c9243221256c43433373af9b1c6a2be4ff170f700b583e798feb420'
 '0c126c04959b5b79e8901ab6346508de8f7e1dd5f833b2967b4b97dd31a3aea4da6a6e3d38aed7f7b1fdafa718398d9f951bb8902ed68e79f48daf2f574a11fb'
 '207a8f04c4054de9db37e25a740ff6e7a8e912527ee22b39296420bf5bd9a1ccd5aa7423eb4c5790db88b2acba0bbb808fb1a85c2fdbe35dbc2a0a0096d95538'
 '4f73cf2699fe7d61103bd7a0977d91a64374a46ba17851b577e31dd8eff668fcf1f09dba497cbbbac730e36c20d1c47397c7ee0a3752d5768e4cfbaa061e5ed8'
 '4fd19a6cf38863dd07d6c42eeb6925739ede8c3ed726e3a9cdc4ae336bad220dadf1ea45f9940c812c2224b9d3b0da31fc982c5c6c5d7547891ee20975575362'
 '53d193a2d20f44e5c7467c66f7ba8dc97c570ebc3d0a91f88e593ba58810b3f38c41dc4735942a5d58c75e01cd9a5e3d3f90707ba89f7899955bc1b3407bcafc'
 'a561824a8ac38dc5ecb4419d23a8ea82152ce23fe544a6afc09db3be1f3e55606b0d7c78801c517a281edd2f459485478354aa7068bb7f6f621100a304c248d5'
 'b0bf047483c2811be37bb77c8c755cf184df45e87954287bc4b98cfaae1af75dbaba41b0d1f9eb44986b591cb97f9619e47e56663dded7ae53aa53b5d666853a'
 'dfaeefa854cc440c5d9aa4760b9f22e28ec2c49b1cb90e0c7bb2aff95272c06926bb7fc2bdb0a7bb53d4498f37726f67907b431fd6241c5c15ab39c471b18f7f']

📋 Feature columns (25):
['voc_total_calls', 'voc_unique_contacts', 'voc_total_duration', 'voc_avg_duration', 'voc_max_duration', 'voc_std_duration', 'voc_active_days', 'voc_active_hours', 'sms_total_msgs', 'sms_unique_contacts', 'sms_active_hours', 'sms_calltype_ratio', 'app_months_active', 'app_total_flow', 'app_avg_flow', 'app_std_flow', 'app_unique_apps_mean', 'app_unique_apps_max', 'user_months_active', 'arpu_mean', 'arpu_std', 'arpu_max', 'idcard_cnt', 'window_size', 'snapshot_round']

📊 Sample snapshots (first 5 users):

,user,label,voc_total_calls,voc_unique_contacts,voc_total_duration,voc_avg_duration,voc_max_duration,voc_std_duration,voc_active_days,voc_active_hours,sms_total_msgs,sms_unique_contacts,sms_active_hours,sms_calltype_ratio,app_months_active,app_total_flow,app_avg_flow,app_std_flow,app_unique_apps_mean,app_unique_apps_max,user_months_active,arpu_mean,arpu_std,arpu_max,idcard_cnt,window_size,snapshot_round
0,03ca40c4aa148f63dbb3beedf20c6424547d294741deb0...,0,5,5,152.0,30.4,68.0,21.524405,4,3,1,1,1,0.0,0,0.000000,0.000000,0.000000,0,0,0,0.0,0.0,0.0,0.0,6,6
1,0a5344aa38fa437528731f1bfb3a847010984b29b7c827...,0,2,2,146.0,73.0,114.0,57.982756,1,1,4,3,3,0.0,0,0.000000,0.000000,0.000000,0,0,0,0.0,0.0,0.0,0.0,6,6
2,0c126c04959b5b79e8901ab6346508de8f7e1dd5f833b2...,1,6,2,192.0,32.0,65.0,20.039960,1,1,0,0,0,0.0,0,0.000000,0.000000,0.000000,0,0,0,0.0,0.0,0.0,0.0,6,6
3,207a8f04c4054de9db37e25a740ff6e7a8e912527ee22b...,0,1,1,79.0,79.0,79.0,0.000000,1,1,0,0,0,0.0,1,0.004471,0.002235,0.001084,2,2,3,1.0,0.0,1.0,2.0,6,6
4,4f73cf2699fe7d61103bd7a0977d91a64374a46ba17851...,0,0,0,0.0,0.0,0.0,0.000000,0,0,6,2,2,0.0,0,0.000000,0.000000,0.000000,0,0,0,0.0,0.0,0.0,0.0,6,6

📈 Feature statistics:

,count,mean,std,min,25%,50%,75%,max
voc_total_calls,10.0,1.700000,2.162817,0.0,0.00,1.0,2.00000,6.000000
voc_unique_contacts,10.0,1.300000,1.567021,0.0,0.00,1.0,2.00000,5.000000
voc_total_duration,10.0,60.300000,75.836154,0.0,0.00,17.0,129.25000,192.000000
voc_avg_duration,10.0,24.140000,30.073547,0.0,0.00,13.5,31.60000,79.000000
voc_max_duration,10.0,35.300000,42.261225,0.0,0.00,13.5,67.25000,114.000000
voc_std_duration,10.0,9.954712,18.961766,0.0,0.00,0.0,15.02997,57.982756
voc_active_days,10.0,0.900000,1.197219,0.0,0.00,1.0,1.00000,4.000000
voc_active_hours,10.0,0.900000,0.994429,0.0,0.00,1.0,1.00000,3.000000
sms_total_msgs,10.0,3.800000,2.529822,0.0,1.75,4.5,6.00000,6.000000
sms_unique_contacts,10.0,1.400000,1.074968,0.0,1.00,1.0,2.00000,3.000000
sms_active_hours,10.0,1.400000,1.074968,0.0,1.00,1.0,2.00000,3.000000
sms_calltype_ratio,10.0,0.000000,0.000000,0.0,0.00,0.0,0.00000,0.000000
app_months_active,10.0,0.100000,0.316228,0.0,0.00,0.0,0.00000,1.000000
app_total_flow,10.0,0.000447,0.001414,0.0,0.00,0.0,0.00000,0.004471
app_avg_flow,10.0,0.000224,0.000707,0.0,0.00,0.0,0.00000,0.002235
app_std_flow,10.0,0.000108,0.000343,0.0,0.00,0.0,0.00000,0.001084
app_unique_apps_mean,10.0,0.200000,0.632456,0.0,0.00,0.0,0.00000,2.000000
app_unique_apps_max,10.0,0.200000,0.632456,0.0,0.00,0.0,0.00000,2.000000
user_months_active,10.0,0.300000,0.948683,0.0,0.00,0.0,0.00000,3.000000
arpu_mean,10.0,0.100000,0.316228,0.0,0.00,0.0,0.00000,1.000000
arpu_std,10.0,0.000000,0.000000,0.0,0.00,0.0,0.00000,0.000000
arpu_max,10.0,0.100000,0.316228,0.0,0.00,0.0,0.00000,1.000000
idcard_cnt,10.0,0.200000,0.632456,0.0,0.00,0.0,0.00000,2.000000
window_size,10.0,6.000000,0.000000,6.0,6.00,6.0,6.00000,6.000000
snapshot_round,10.0,6.000000,0.000000,6.0,6.00,6.0,6.00000,6.000000

📊 Class distribution:
   Fraud (1): 2 (20.0%)
   Normal (0): 8 (80.0%)

### RF and XGB NAS

In [21]:
# ============================================================
# 🔧 PREPARE DATA FOR RF/XGB NAS
# ============================================================
import optuna
from optuna.samplers import TPESampler
# Number of trials (same as TimesNet/LSTM NAS)
# ============================================================
# 📊 Trial Logging (matches NAS TimesNet structure)
# ============================================================
rf_trial_log = []
best_rf_f1_so_far = -1.0
best_rf_trial_so_far = -1
ENQUEUED_RF_IDS = {0, 1, 2, 3}

xgb_trial_log = []
best_xgb_f1_so_far = -1.0
best_xgb_trial_so_far = -1
ENQUEUED_XGB_IDS = {0, 1, 2, 3}
print(f"\\n[{datetime.now()}] 📊 Generating test snapshots...")

X_test_snap, y_test_snap, users_test_snap = generate_snapshots_from_events(
    events_df=test_events_unscaled,
    users=test_users,
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)

X_test_snap = X_test_snap.reindex(columns=SNAPSHOT_FEATURE_COLS, fill_value=0)
X_test_scaled = scaler_snap.transform(X_test_snap)

print(f"[{datetime.now()}] ✅ Test snapshots: {len(X_test_snap)} users")

# Generate validation snapshots
print(f"\\n[{datetime.now()}] 📊 Generating validation snapshots...")

X_val_snap, y_val_snap, users_val_snap = generate_snapshots_from_events(
    events_df=val_events_unscaled,
    users=val_users,
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)

X_val_snap = X_val_snap.reindex(columns=SNAPSHOT_FEATURE_COLS, fill_value=0)
X_val_scaled = scaler_snap.transform(X_val_snap)

print(f"[{datetime.now()}] ✅ Validation snapshots: {len(X_val_snap)} users")

neg = (y_train_snap == 0).sum()
pos = (y_train_snap == 1).sum()
XGB_scale_pos_weight = neg / pos
print(f"   Class ratio → Normal: {neg}, Fraud: {pos}, scale_pos_weight: {XGB_scale_pos_weight:.2f}")

# Already computed above for XGB, reuse the same neg/pos
RF_class_weight = {
    0: 1.0,           # normal users — keep as 1
    1: neg / pos      # fraud users — same ratio as XGB
}
print(f"   RF class_weight: {RF_class_weight}")


# ============================================================
# 🌲 RANDOM FOREST NAS
# ============================================================

def rf_objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 500),
        "max_depth": trial.suggest_int("max_depth", 2, 20),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
    }

    model = RandomForestClassifier(**params, random_state=42, n_jobs=-1)
    model.fit(X_train_scaled, y_train_snap)

    val_probs  = model.predict_proba(X_val_scaled)[:, 1]
    test_probs = model.predict_proba(X_test_scaled)[:, 1]

    # --- Validation threshold + metrics ---
    best_val_thr, best_val_f1 = find_best_threshold(y_val_snap, val_probs)
    val_preds = (val_probs >= best_val_thr).astype(int)
    val_auc = roc_auc_score(y_val_snap, val_probs)
    val_recall = recall_score(y_val_snap, val_preds, zero_division=0)
    val_precision = precision_score(y_val_snap, val_preds, zero_division=0)

    # --- Test metrics using VALIDATION threshold ---
    test_preds = (test_probs >= best_val_thr).astype(int)
    test_f1 = f1_score(y_test_snap, test_preds, zero_division=0)
    test_auc = roc_auc_score(y_test_snap, test_probs)
    test_recall = recall_score(y_test_snap, test_preds, zero_division=0)
    test_precision = precision_score(y_test_snap, test_preds, zero_division=0)

    # --- Oracle test threshold (monitoring only) ---
    best_test_thr, best_test_f1_oracle = find_best_threshold(y_test_snap, test_probs)

    # --- Log trial ---
    global best_rf_f1_so_far, best_rf_trial_so_far
    if best_val_f1 > best_rf_f1_so_far:
        best_rf_f1_so_far = best_val_f1
        best_rf_trial_so_far = trial.number

    trial_row = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "time": datetime.now().strftime("%H:%M:%S"),
        "seq_length": max_seq_len,
        "trial_id": trial.number,
        "model": "RandomForest",

        # Validation
        "val_f1": round(best_val_f1, 4),
        "val_auc": round(val_auc, 4),
        "val_recall": round(val_recall, 4),
        "val_precision": round(val_precision, 4),

        # Parameters
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "min_samples_split": params["min_samples_split"],
        "min_samples_leaf": params["min_samples_leaf"],

        # Thresholds
        "val_threshold": round(best_val_thr, 3),
        "best_test_threshold": round(best_test_thr, 3),

        # Best tracking
        "best_val_so_far": round(best_rf_f1_so_far, 4),
        "best_trial_id": best_rf_trial_so_far,

        # Test (monitoring only)
        "test_f1": round(test_f1, 4),
        "test_auc": round(test_auc, 4),
        "test_recall": round(test_recall, 4),
        "test_precision": round(test_precision, 4),

        # Diagnostics
        "gap_val_test": round(best_val_f1 - test_f1, 4),
        "is_enqueued": trial.number in ENQUEUED_RF_IDS,
        "status": "OK",
    }
    rf_trial_log.append(trial_row)

    display(pd.DataFrame([trial_row]))

    return best_val_f1

    # Evaluate on TEST set (same as TimesNet NAS)
    #probs = model.predict_proba(X_test_scaled)[:, 1]

    # # Same threshold search as TimesNet/LSTM NAS
    # best_f1 = -1.0
    # for thr in np.linspace(0.2, 0.8, 61):
    #     pred = (probs >= thr).astype(int)
    #     f1 = f1_score(y_test_snap, pred, zero_division=0)
    #     if f1 > best_f1:
    #         best_f1 = f1

    # return best_f1


# ============================================================
# 🚀 XGBOOST NAS
# ============================================================

def xgb_objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 500),
        "max_depth": trial.suggest_int("max_depth", 2, 20),
        "learning_rate": trial.suggest_float("learning_rate", 0.001, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "gamma": trial.suggest_float("gamma", 0.0, 1.0),
        "patience": trial.suggest_int("patience", 2, 5),
    }

    patience = params.pop("patience")
    model = XGBClassifier(**params,early_stopping_rounds=patience, random_state=42, n_jobs=-1, eval_metric='logloss')

    model.fit(X_train_scaled, y_train_snap,eval_set=[(X_val_scaled, y_val_snap)], verbose=False)
    actual_trees = model.best_iteration if hasattr(model, "best_iteration") else params["n_estimators"]

    val_probs  = model.predict_proba(X_val_scaled)[:, 1]
    test_probs = model.predict_proba(X_test_scaled)[:, 1]

    # --- Validation threshold + metrics ---
    best_val_thr, best_val_f1 = find_best_threshold(y_val_snap, val_probs)
    val_preds = (val_probs >= best_val_thr).astype(int)
    val_auc = roc_auc_score(y_val_snap, val_probs)
    val_recall = recall_score(y_val_snap, val_preds, zero_division=0)
    val_precision = precision_score(y_val_snap, val_preds, zero_division=0)

    # --- Test metrics using VALIDATION threshold ---
    test_preds = (test_probs >= best_val_thr).astype(int)
    test_f1 = f1_score(y_test_snap, test_preds, zero_division=0)
    test_auc = roc_auc_score(y_test_snap, test_probs)
    test_recall = recall_score(y_test_snap, test_preds, zero_division=0)
    test_precision = precision_score(y_test_snap, test_preds, zero_division=0)

    # --- Oracle test threshold (monitoring only) ---
    best_test_thr, best_test_f1_oracle = find_best_threshold(y_test_snap, test_probs)

    # --- Log trial ---
    global best_xgb_f1_so_far, best_xgb_trial_so_far
    if best_val_f1 > best_xgb_f1_so_far:
        best_xgb_f1_so_far = best_val_f1
        best_xgb_trial_so_far = trial.number

    trial_row = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "time": datetime.now().strftime("%H:%M:%S"),
        "seq_length": max_seq_len,
        "trial_id": trial.number,
        "model": "XGBoost",

        # Validation
        "val_f1": round(best_val_f1, 4),
        "val_auc": round(val_auc, 4),
        "val_recall": round(val_recall, 4),
        "val_precision": round(val_precision, 4),

        # Parameters
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "learning_rate": params["learning_rate"],
        "subsample": params["subsample"],
        "colsample_bytree": params["colsample_bytree"],
        "min_child_weight": params["min_child_weight"],
        "gamma": params["gamma"],

        "actual_trees": actual_trees,
        "patience": patience,

        # Thresholds
        "val_threshold": round(best_val_thr, 3),
        "best_test_threshold": round(best_test_thr, 3),

        # Best tracking
        "best_val_so_far": round(best_xgb_f1_so_far, 4),
        "best_trial_id": best_xgb_trial_so_far,

        # Test (monitoring only)
        "test_f1": round(test_f1, 4),
        "test_auc": round(test_auc, 4),
        "test_recall": round(test_recall, 4),
        "test_precision": round(test_precision, 4),

        # Diagnostics
        "gap_val_test": round(best_val_f1 - test_f1, 4),
        "is_enqueued": trial.number in ENQUEUED_XGB_IDS,
        "status": "OK",
    }
    xgb_trial_log.append(trial_row)

    display(pd.DataFrame([trial_row]))

    return best_val_f1


# ============================================================
# 🔬 RUN NAS - RANDOM FOREST
# ============================================================

print("\\n" + "="*60)
print("🌲 RANDOM FOREST NAS")
print("="*60)

sampler_rf = TPESampler(
    n_startup_trials=10,
    n_ei_candidates=24,
    multivariate=True,
    seed=42
)

study_rf = optuna.create_study(
    direction="maximize",
    sampler=sampler_rf
    #pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=3)
)

study_rf.enqueue_trial({"n_estimators": 100, "max_depth": 10, "min_samples_split": 2, "min_samples_leaf": 1})
study_rf.enqueue_trial({"n_estimators": 500, "max_depth": 20, "min_samples_split": 2, "min_samples_leaf": 1})
study_rf.enqueue_trial({"n_estimators": 200, "max_depth":  5, "min_samples_split":10, "min_samples_leaf": 5})
study_rf.enqueue_trial({"n_estimators": 300, "max_depth": 12, "min_samples_split": 5, "min_samples_leaf": 2})


print(f"[{datetime.now()}] 🚀 Starting RF NAS ({n_trials_rf_xgb} trials)...")
study_rf.optimize(rf_objective, n_trials=n_trials_rf_xgb)

print("\\n" + "="*60)
print("🎉 RF NAS COMPLETE")
print("="*60)
print(f"Best Trial: {study_rf.best_trial.number}")
print(f"Best F1: {study_rf.best_value:.4f}")
print(f"Best Params: {study_rf.best_params}")


# ============================================================
# 🔬 RUN NAS - XGBOOST
# ============================================================

print("\\n" + "="*60)
print("🚀 XGBOOST NAS")
print("="*60)

sampler_xgb = TPESampler(
    n_startup_trials=10,
    n_ei_candidates=24,
    multivariate=True,
    seed=42
)

study_xgb = optuna.create_study(
    direction="maximize",
    sampler=sampler_xgb
    #pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=3)
)

study_xgb.enqueue_trial({"n_estimators": 100, "max_depth": 6, "learning_rate": 0.1,  "subsample": 1.0, "colsample_bytree": 1.0, "min_child_weight": 1, "gamma": 0.0, "patience": 3 })
study_xgb.enqueue_trial({"n_estimators": 500, "max_depth": 4, "learning_rate": 0.01, "subsample": 0.8, "colsample_bytree": 0.8, "min_child_weight": 3, "gamma": 0.1, "patience": 3 })
study_xgb.enqueue_trial({"n_estimators":  50, "max_depth": 8, "learning_rate": 0.3,  "subsample": 0.7, "colsample_bytree": 0.7, "min_child_weight": 1, "gamma": 0.0, "patience": 3 })
study_xgb.enqueue_trial({"n_estimators": 300, "max_depth": 3, "learning_rate": 0.05, "subsample": 0.6, "colsample_bytree": 0.6, "min_child_weight": 5, "gamma": 0.5, "patience": 3 })



print(f"[{datetime.now()}] 🚀 Starting XGB NAS ({n_trials_rf_xgb} trials)...")
study_xgb.optimize(xgb_objective, n_trials=n_trials_rf_xgb)

print("\\n" + "="*60)
print("🎉 XGB NAS COMPLETE")
print("="*60)
print(f"Best Trial: {study_xgb.best_trial.number}")
print(f"Best F1: {study_xgb.best_value:.4f}")
print(f"Best Params: {study_xgb.best_params}")


# ============================================================
# 📊 SAVE RESULTS
# ============================================================

# Save Optuna study results
OUT_DIR = os.path.join(config["output"]["results_dir"], "NAS_v2/")
os.makedirs(OUT_DIR, exist_ok=True)
study_rf.trials_dataframe().to_csv(f"{OUT_DIR}nas_rf_results_WL{max_seq_len}.csv", index=False)
study_xgb.trials_dataframe().to_csv(f"{OUT_DIR}nas_xgb_results_WL{max_seq_len}.csv", index=False)
pd.DataFrame(rf_trial_log).to_csv(f"{OUT_DIR}nas_rf_trial_log_WL{max_seq_len}.csv", index=False)
pd.DataFrame(xgb_trial_log).to_csv(f"{OUT_DIR}nas_xgb_trial_log_WL{max_seq_len}.csv", index=False)

print("💾 Saved: nas_rf_results.csv, nas_xgb_results.csv")
print("💾 Saved: nas_rf_trial_log.csv, nas_xgb_trial_log.csv")

# ============================================================
# 📋 COMPARISON SUMMARY
# ============================================================

print("\n" + "="*60)
print("📋 NAS RESULTS COMPARISON")
print("="*60)

print(f"\n{'Model':<15} {'Best Val F1':<12} {'Best Trial':<12}")
print("-" * 40)
print(f"{'RandomForest':<15} {study_rf.best_value:<12.4f} {study_rf.best_trial.number:<12}")
print(f"{'XGBoost':<15} {study_xgb.best_value:<12.4f} {study_xgb.best_trial.number:<12}")

print("\n📊 Best RF Params:")
for k, v in study_rf.best_params.items():
    print(f"   {k}: {v}")

print("\n📊 Best XGB Params:")
for k, v in study_xgb.best_params.items():
    print(f"   {k}: {v}")

# Display full trial logs
print("\n📊 RF Trial Log (sorted by val_f1):")
display(
    pd.DataFrame(rf_trial_log)
    .sort_values("val_f1", ascending=False)
    .reset_index(drop=True)
)

print("\n📊 XGB Trial Log (sorted by val_f1):")
display(
    pd.DataFrame(xgb_trial_log)
    .sort_values("val_f1", ascending=False)
    .reset_index(drop=True)
)

\n[2026-07-09 11:34:36.366601] 📊 Generating test snapshots...

/tmp/ipykernel_993/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 1222/1222 [00:03<00:00, 345.48it/s]

[2026-07-09 11:34:44.551165] ✅ Test snapshots: 1222 users
\n[2026-07-09 11:34:44.551291] 📊 Generating validation snapshots...

/tmp/ipykernel_993/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 977/977 [00:02<00:00, 342.19it/s]
/tmp/ipykernel_993/3487339742.py:269: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  sampler_rf = TPESampler(
[I 2026-07-09 11:34:51,002] A new study created in memory with name: no-name-0b22a1d1-82ed-46ab-b7ea-50ef8d1da630

[2026-07-09 11:34:50.999054] ✅ Validation snapshots: 977 users
   Class ratio → Normal: 2652, Fraud: 1255, scale_pos_weight: 2.11
   RF class_weight: {0: 1.0, 1: np.float64(2.113147410358566)}
\n============================================================
🌲 RANDOM FOREST NAS
============================================================
[2026-07-09 11:34:51.003646] 🚀 Starting RF NAS (100 trials)...

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:34:51,6,0,RandomForest,0.6537,0.7957,0.7516,0.5784,100,10,2,1,0.27,0.3,0.6537,0,0.6254,0.7782,0.6947,0.5687,0.0283,True,OK

[I 2026-07-09 11:34:51,536] Trial 0 finished with value: 0.6537396121883656 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.6537396121883656.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:34:53,6,1,RandomForest,0.6386,0.7781,0.7006,0.5867,500,20,2,1,0.32,0.32,0.6537,0,0.6043,0.7558,0.6412,0.5714,0.0343,True,OK

[I 2026-07-09 11:34:53,118] Trial 1 finished with value: 0.6386066763425254 and parameters: {'n_estimators': 500, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.6537396121883656.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:34:53,6,2,RandomForest,0.6598,0.7948,0.7102,0.616,200,5,10,5,0.31,0.3,0.6598,2,0.598,0.7751,0.6132,0.5835,0.0617,True,OK

[I 2026-07-09 11:34:53,872] Trial 2 finished with value: 0.6597633136094675 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 2 with value: 0.6597633136094675.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:34:54,6,3,RandomForest,0.6528,0.7963,0.6975,0.6134,300,12,5,2,0.32,0.31,0.6598,2,0.6299,0.7763,0.6539,0.6076,0.0229,True,OK

[I 2026-07-09 11:34:54,895] Trial 3 finished with value: 0.6527570789865872 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.6597633136094675.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:34:55,6,4,RandomForest,0.6537,0.7931,0.7516,0.5784,218,20,15,6,0.29,0.31,0.6598,2,0.621,0.7708,0.6921,0.5631,0.0327,False,OK

[I 2026-07-09 11:34:55,694] Trial 4 finished with value: 0.6537396121883656 and parameters: {'n_estimators': 218, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 6}. Best is trial 2 with value: 0.6597633136094675.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:34:56,6,5,RandomForest,0.6598,0.793,0.7102,0.616,120,4,3,9,0.35,0.22,0.6598,2,0.598,0.7719,0.6132,0.5835,0.0617,False,OK

[I 2026-07-09 11:34:56,244] Trial 5 finished with value: 0.6597633136094675 and parameters: {'n_estimators': 120, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 2 with value: 0.6597633136094675.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:34:57,6,6,RandomForest,0.6611,0.7953,0.7516,0.59,321,15,2,10,0.3,0.28,0.6611,6,0.6209,0.7716,0.6794,0.5717,0.0401,False,OK

[I 2026-07-09 11:34:57,313] Trial 6 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 321, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:34:58,6,7,RandomForest,0.6583,0.7998,0.7484,0.5875,425,6,5,2,0.28,0.28,0.6611,6,0.6256,0.7822,0.6845,0.576,0.0327,False,OK

[I 2026-07-09 11:34:58,660] Trial 7 finished with value: 0.6582633053221288 and parameters: {'n_estimators': 425, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:34:59,6,8,RandomForest,0.6538,0.7984,0.7548,0.5766,187,11,10,3,0.27,0.27,0.6611,6,0.6316,0.7764,0.7023,0.5738,0.0222,False,OK

[I 2026-07-09 11:34:59,410] Trial 8 finished with value: 0.6537931034482759 and parameters: {'n_estimators': 187, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:00,6,9,RandomForest,0.6498,0.793,0.6529,0.6467,325,4,7,4,0.35,0.33,0.6611,6,0.5942,0.7735,0.57,0.6205,0.0556,False,OK

[I 2026-07-09 11:35:00,502] Trial 9 finished with value: 0.6497622820919176 and parameters: {'n_estimators': 325, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:01,6,10,RandomForest,0.6601,0.7965,0.7516,0.5885,313,13,2,8,0.3,0.29,0.6611,6,0.6225,0.7739,0.6819,0.5726,0.0376,False,OK

[I 2026-07-09 11:35:01,560] Trial 10 finished with value: 0.6601398601398601 and parameters: {'n_estimators': 313, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:02,6,11,RandomForest,0.6611,0.796,0.7516,0.59,354,15,4,9,0.3,0.3,0.6611,6,0.6209,0.772,0.6794,0.5717,0.0401,False,OK

[I 2026-07-09 11:35:02,709] Trial 11 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 354, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:04,6,12,RandomForest,0.6611,0.7958,0.7516,0.59,439,17,7,9,0.3,0.3,0.6611,6,0.6209,0.7724,0.6794,0.5717,0.0401,False,OK

[I 2026-07-09 11:35:04,084] Trial 12 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 439, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:04,6,13,RandomForest,0.6601,0.7955,0.7516,0.5885,233,18,8,10,0.3,0.28,0.6611,6,0.6193,0.7725,0.6768,0.5708,0.0408,False,OK

[I 2026-07-09 11:35:04,935] Trial 13 finished with value: 0.6601398601398601 and parameters: {'n_estimators': 233, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:06,6,14,RandomForest,0.6601,0.7953,0.7516,0.5885,330,20,3,10,0.3,0.28,0.6611,6,0.6193,0.7712,0.6768,0.5708,0.0408,False,OK

[I 2026-07-09 11:35:06,029] Trial 14 finished with value: 0.6601398601398601 and parameters: {'n_estimators': 330, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:07,6,15,RandomForest,0.6582,0.7991,0.742,0.5914,323,6,2,9,0.3,0.29,0.6611,6,0.6165,0.7775,0.6667,0.5733,0.0417,False,OK

[I 2026-07-09 11:35:07,106] Trial 15 finished with value: 0.6581920903954802 and parameters: {'n_estimators': 323, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:08,6,16,RandomForest,0.6611,0.7959,0.7516,0.59,340,11,15,9,0.3,0.27,0.6611,6,0.62,0.7751,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:35:08,216] Trial 16 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 340, 'max_depth': 11, 'min_samples_split': 15, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:08,6,17,RandomForest,0.6611,0.7948,0.7516,0.59,104,13,6,10,0.3,0.28,0.6611,6,0.6192,0.7739,0.6743,0.5724,0.0419,False,OK

[I 2026-07-09 11:35:08,742] Trial 17 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 104, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:10,6,18,RandomForest,0.6611,0.7958,0.7516,0.59,427,11,4,10,0.3,0.28,0.6611,6,0.6184,0.7745,0.6743,0.5711,0.0426,False,OK

[I 2026-07-09 11:35:10,073] Trial 18 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 427, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:11,6,19,RandomForest,0.6583,0.7961,0.7516,0.5856,454,11,2,6,0.29,0.26,0.6611,6,0.625,0.7777,0.687,0.5732,0.0333,False,OK

[I 2026-07-09 11:35:11,529] Trial 19 finished with value: 0.6582984658298466 and parameters: {'n_estimators': 454, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:12,6,20,RandomForest,0.6547,0.7934,0.7548,0.578,145,20,4,6,0.29,0.29,0.6611,6,0.6201,0.7696,0.6896,0.5634,0.0346,False,OK

[I 2026-07-09 11:35:12,184] Trial 20 finished with value: 0.6546961325966851 and parameters: {'n_estimators': 145, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:13,6,21,RandomForest,0.6611,0.7958,0.7516,0.59,491,19,10,9,0.3,0.3,0.6611,6,0.6209,0.7724,0.6794,0.5717,0.0401,False,OK

[I 2026-07-09 11:35:13,751] Trial 21 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 491, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:15,6,22,RandomForest,0.6546,0.7959,0.7516,0.5799,482,18,3,7,0.29,0.3,0.6611,6,0.6208,0.771,0.6896,0.5646,0.0338,False,OK

[I 2026-07-09 11:35:15,234] Trial 22 finished with value: 0.6546463245492372 and parameters: {'n_estimators': 482, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:16,6,23,RandomForest,0.6611,0.796,0.7516,0.59,372,15,6,9,0.3,0.3,0.6611,6,0.6209,0.7718,0.6794,0.5717,0.0401,False,OK

[I 2026-07-09 11:35:16,433] Trial 23 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 372, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:17,6,24,RandomForest,0.6556,0.7957,0.7548,0.5795,453,14,11,5,0.28,0.31,0.6611,6,0.6249,0.773,0.6972,0.5661,0.0307,False,OK

[I 2026-07-09 11:35:17,848] Trial 24 finished with value: 0.6556016597510373 and parameters: {'n_estimators': 453, 'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 5}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:18,6,25,RandomForest,0.6611,0.7963,0.7516,0.59,342,16,11,9,0.3,0.3,0.6611,6,0.6202,0.7715,0.6794,0.5705,0.0409,False,OK

[I 2026-07-09 11:35:18,968] Trial 25 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 342, 'max_depth': 16, 'min_samples_split': 11, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:20,6,26,RandomForest,0.6602,0.7995,0.7548,0.5866,483,8,20,3,0.26,0.26,0.6611,6,0.6305,0.7824,0.6947,0.5772,0.0297,False,OK

[I 2026-07-09 11:35:20,444] Trial 26 finished with value: 0.6601671309192201 and parameters: {'n_estimators': 483, 'max_depth': 8, 'min_samples_split': 20, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:21,6,27,RandomForest,0.6592,0.7962,0.7516,0.5871,223,15,5,8,0.29,0.29,0.6611,6,0.6243,0.7723,0.687,0.572,0.0349,False,OK

[I 2026-07-09 11:35:21,256] Trial 27 finished with value: 0.659217877094972 and parameters: {'n_estimators': 223, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:22,6,28,RandomForest,0.6493,0.7916,0.6752,0.6254,345,20,6,4,0.34,0.32,0.6611,6,0.6208,0.7678,0.631,0.6108,0.0285,False,OK

[I 2026-07-09 11:35:22,407] Trial 28 finished with value: 0.6493108728943339 and parameters: {'n_estimators': 345, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:23,6,29,RandomForest,0.6611,0.7949,0.7516,0.59,422,16,5,10,0.3,0.28,0.6611,6,0.6193,0.7704,0.6768,0.5708,0.0417,False,OK

[I 2026-07-09 11:35:23,749] Trial 29 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 422, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:24,6,30,RandomForest,0.6611,0.7953,0.7516,0.59,305,14,2,9,0.3,0.29,0.6611,6,0.6217,0.7735,0.6794,0.573,0.0394,False,OK

[I 2026-07-09 11:35:24,831] Trial 30 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 305, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:26,6,31,RandomForest,0.6592,0.798,0.7484,0.589,391,9,17,9,0.3,0.28,0.6611,6,0.62,0.7774,0.6768,0.572,0.0391,False,OK

[I 2026-07-09 11:35:26,118] Trial 31 finished with value: 0.6591865357643759 and parameters: {'n_estimators': 391, 'max_depth': 9, 'min_samples_split': 17, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:26,6,32,RandomForest,0.6592,0.7958,0.7484,0.589,223,10,17,9,0.3,0.27,0.6611,6,0.62,0.7753,0.6768,0.572,0.0391,False,OK

[I 2026-07-09 11:35:26,940] Trial 32 finished with value: 0.6591865357643759 and parameters: {'n_estimators': 223, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:27,6,33,RandomForest,0.648,0.7877,0.7006,0.6027,145,20,19,1,0.32,0.35,0.6611,6,0.6217,0.7654,0.6565,0.5904,0.0263,False,OK

[I 2026-07-09 11:35:27,576] Trial 33 finished with value: 0.6480117820324006 and parameters: {'n_estimators': 145, 'max_depth': 20, 'min_samples_split': 19, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:28,6,34,RandomForest,0.6611,0.7955,0.7516,0.59,301,15,17,10,0.3,0.28,0.6611,6,0.6193,0.7724,0.6768,0.5708,0.0417,False,OK

[I 2026-07-09 11:35:28,603] Trial 34 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 301, 'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:29,6,35,RandomForest,0.6611,0.7958,0.7516,0.59,287,10,12,9,0.3,0.27,0.6611,6,0.62,0.7756,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:35:29,579] Trial 35 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 287, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:30,6,36,RandomForest,0.6611,0.7967,0.7516,0.59,448,10,11,9,0.3,0.27,0.6611,6,0.62,0.776,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:35:30,972] Trial 36 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 448, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:31,6,37,RandomForest,0.6611,0.7958,0.7516,0.59,267,15,5,10,0.3,0.28,0.6611,6,0.6193,0.7722,0.6768,0.5708,0.0417,False,OK

[I 2026-07-09 11:35:31,906] Trial 37 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 267, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:32,6,38,RandomForest,0.6432,0.7881,0.7261,0.5772,177,2,6,1,0.43,0.43,0.6611,6,0.6019,0.7685,0.6539,0.5575,0.0413,False,OK

[I 2026-07-09 11:35:32,591] Trial 38 finished with value: 0.6431593794076164 and parameters: {'n_estimators': 177, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:33,6,39,RandomForest,0.6498,0.7933,0.6529,0.6467,298,4,20,6,0.35,0.33,0.6611,6,0.5942,0.772,0.57,0.6205,0.0556,False,OK

[I 2026-07-09 11:35:33,581] Trial 39 finished with value: 0.6497622820919176 and parameters: {'n_estimators': 298, 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:34,6,40,RandomForest,0.6556,0.7961,0.7516,0.5813,308,13,17,6,0.29,0.29,0.6611,6,0.6259,0.7752,0.6896,0.5729,0.0297,False,OK

[I 2026-07-09 11:35:34,616] Trial 40 finished with value: 0.6555555555555556 and parameters: {'n_estimators': 308, 'max_depth': 13, 'min_samples_split': 17, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.6610644257703081.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:35,6,41,RandomForest,0.662,0.7951,0.7516,0.5915,70,11,7,10,0.31,0.28,0.662,41,0.6184,0.7743,0.6743,0.5711,0.0436,False,OK

[I 2026-07-09 11:35:35,062] Trial 41 finished with value: 0.6619915848527349 and parameters: {'n_estimators': 70, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:35,6,42,RandomForest,0.6565,0.7988,0.7516,0.5827,61,8,12,8,0.29,0.28,0.662,41,0.6282,0.7809,0.6921,0.5751,0.0283,False,OK

[I 2026-07-09 11:35:35,485] Trial 42 finished with value: 0.6564673157162726 and parameters: {'n_estimators': 61, 'max_depth': 8, 'min_samples_split': 12, 'min_samples_leaf': 8}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:35,6,43,RandomForest,0.6592,0.7966,0.7516,0.5871,81,9,8,9,0.3,0.3,0.662,41,0.6241,0.7781,0.6845,0.5736,0.0351,False,OK

[I 2026-07-09 11:35:35,943] Trial 43 finished with value: 0.659217877094972 and parameters: {'n_estimators': 81, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 9}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:37,6,44,RandomForest,0.6611,0.7955,0.7516,0.59,365,15,2,10,0.3,0.28,0.662,41,0.6209,0.7713,0.6794,0.5717,0.0401,False,OK

[I 2026-07-09 11:35:37,160] Trial 44 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 365, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:38,6,45,RandomForest,0.6513,0.7925,0.6752,0.6291,316,14,12,1,0.33,0.31,0.662,41,0.6241,0.7704,0.6336,0.6148,0.0272,False,OK

[I 2026-07-09 11:35:38,259] Trial 45 finished with value: 0.6513056835637481 and parameters: {'n_estimators': 316, 'max_depth': 14, 'min_samples_split': 12, 'min_samples_leaf': 1}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:38,6,46,RandomForest,0.6517,0.7943,0.6911,0.6165,61,14,6,7,0.32,0.31,0.662,41,0.623,0.772,0.6412,0.6058,0.0287,False,OK

[I 2026-07-09 11:35:38,685] Trial 46 finished with value: 0.6516516516516516 and parameters: {'n_estimators': 61, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:40,6,47,RandomForest,0.6313,0.7874,0.6815,0.5879,468,2,12,2,0.43,0.35,0.662,41,0.5771,0.7686,0.5954,0.5598,0.0542,False,OK

[I 2026-07-09 11:35:40,105] Trial 47 finished with value: 0.6312684365781711 and parameters: {'n_estimators': 468, 'max_depth': 2, 'min_samples_split': 12, 'min_samples_leaf': 2}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:41,6,48,RandomForest,0.6592,0.7961,0.7516,0.5871,361,20,8,8,0.3,0.28,0.662,41,0.6195,0.7723,0.6794,0.5693,0.0397,False,OK

[I 2026-07-09 11:35:41,279] Trial 48 finished with value: 0.659217877094972 and parameters: {'n_estimators': 361, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 8}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:41,6,49,RandomForest,0.6611,0.792,0.7516,0.59,57,14,2,10,0.31,0.29,0.662,41,0.6192,0.7753,0.6743,0.5724,0.0419,False,OK

[I 2026-07-09 11:35:41,690] Trial 49 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 57, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:42,6,50,RandomForest,0.6611,0.7943,0.7516,0.59,72,16,9,10,0.3,0.29,0.662,41,0.62,0.773,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:35:42,136] Trial 50 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 72, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:42,6,51,RandomForest,0.6611,0.7955,0.7516,0.59,68,9,4,10,0.31,0.28,0.662,41,0.6184,0.7775,0.6743,0.5711,0.0426,False,OK

[I 2026-07-09 11:35:42,576] Trial 51 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 68, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:43,6,52,RandomForest,0.6611,0.7971,0.7516,0.59,120,13,8,9,0.3,0.28,0.662,41,0.6193,0.7745,0.6768,0.5708,0.0417,False,OK

[I 2026-07-09 11:35:43,136] Trial 52 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 120, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 9}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:44,6,53,RandomForest,0.6601,0.7962,0.7516,0.5885,387,14,7,8,0.3,0.29,0.662,41,0.6202,0.7736,0.6794,0.5705,0.0399,False,OK

[I 2026-07-09 11:35:44,375] Trial 53 finished with value: 0.6601398601398601 and parameters: {'n_estimators': 387, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:44,6,54,RandomForest,0.6592,0.7971,0.7484,0.589,137,11,4,9,0.3,0.27,0.662,41,0.6184,0.7762,0.6743,0.5711,0.0408,False,OK

[I 2026-07-09 11:35:44,982] Trial 54 finished with value: 0.6591865357643759 and parameters: {'n_estimators': 137, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:45,6,55,RandomForest,0.6472,0.7867,0.672,0.6243,74,15,15,5,0.34,0.31,0.662,41,0.6187,0.7698,0.6234,0.614,0.0286,False,OK

[I 2026-07-09 11:35:45,441] Trial 55 finished with value: 0.647239263803681 and parameters: {'n_estimators': 74, 'max_depth': 15, 'min_samples_split': 15, 'min_samples_leaf': 5}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:46,6,56,RandomForest,0.6467,0.7858,0.6879,0.6102,138,20,10,1,0.33,0.39,0.662,41,0.6165,0.7625,0.6361,0.5981,0.0302,False,OK

[I 2026-07-09 11:35:46,066] Trial 56 finished with value: 0.6467065868263473 and parameters: {'n_estimators': 138, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:47,6,57,RandomForest,0.6601,0.7958,0.7516,0.5885,457,19,17,9,0.3,0.3,0.662,41,0.6209,0.7726,0.6794,0.5717,0.0392,False,OK

[I 2026-07-09 11:35:47,480] Trial 57 finished with value: 0.6601398601398601 and parameters: {'n_estimators': 457, 'max_depth': 19, 'min_samples_split': 17, 'min_samples_leaf': 9}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:47,6,58,RandomForest,0.6611,0.8008,0.7611,0.5844,59,7,16,2,0.26,0.28,0.662,41,0.6287,0.7841,0.7023,0.5691,0.0324,False,OK

[I 2026-07-09 11:35:47,894] Trial 58 finished with value: 0.661134163208852 and parameters: {'n_estimators': 59, 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 2}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:48,6,59,RandomForest,0.6592,0.7995,0.7516,0.5871,110,7,15,1,0.27,0.26,0.662,41,0.6289,0.7836,0.6921,0.5763,0.0303,False,OK

[I 2026-07-09 11:35:48,440] Trial 59 finished with value: 0.659217877094972 and parameters: {'n_estimators': 110, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 1}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:48,6,60,RandomForest,0.6598,0.7938,0.7102,0.616,58,5,14,4,0.32,0.31,0.662,41,0.598,0.7751,0.6132,0.5835,0.0617,False,OK

[I 2026-07-09 11:35:48,855] Trial 60 finished with value: 0.6597633136094675 and parameters: {'n_estimators': 58, 'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 4}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:49,6,61,RandomForest,0.6432,0.7876,0.7261,0.5772,230,2,17,2,0.43,0.43,0.662,41,0.6019,0.7686,0.6539,0.5575,0.0413,False,OK

[I 2026-07-09 11:35:49,713] Trial 61 finished with value: 0.6431593794076164 and parameters: {'n_estimators': 230, 'max_depth': 2, 'min_samples_split': 17, 'min_samples_leaf': 2}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:50,6,62,RandomForest,0.6593,0.7983,0.7611,0.5815,96,8,16,4,0.25,0.25,0.662,41,0.6292,0.7828,0.6972,0.5732,0.0301,False,OK

[I 2026-07-09 11:35:50,238] Trial 62 finished with value: 0.6593103448275862 and parameters: {'n_estimators': 96, 'max_depth': 8, 'min_samples_split': 16, 'min_samples_leaf': 4}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:51,6,63,RandomForest,0.6592,0.7969,0.7516,0.5871,386,18,4,8,0.3,0.29,0.662,41,0.6195,0.7725,0.6794,0.5693,0.0397,False,OK

[I 2026-07-09 11:35:51,509] Trial 63 finished with value: 0.659217877094972 and parameters: {'n_estimators': 386, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 8}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:52,6,64,RandomForest,0.6611,0.7941,0.7516,0.59,95,13,6,10,0.3,0.28,0.662,41,0.6184,0.7744,0.6743,0.5711,0.0426,False,OK

[I 2026-07-09 11:35:52,051] Trial 64 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 95, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:52,6,65,RandomForest,0.6584,0.8025,0.758,0.5819,184,8,19,1,0.25,0.25,0.662,41,0.6276,0.7828,0.6947,0.5723,0.0308,False,OK

[I 2026-07-09 11:35:52,780] Trial 65 finished with value: 0.6583679114799447 and parameters: {'n_estimators': 184, 'max_depth': 8, 'min_samples_split': 19, 'min_samples_leaf': 1}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:53,6,66,RandomForest,0.6432,0.7874,0.7261,0.5772,279,2,13,10,0.43,0.43,0.662,41,0.6019,0.7684,0.6539,0.5575,0.0413,False,OK

[I 2026-07-09 11:35:53,730] Trial 66 finished with value: 0.6431593794076164 and parameters: {'n_estimators': 279, 'max_depth': 2, 'min_samples_split': 13, 'min_samples_leaf': 10}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:54,6,67,RandomForest,0.6598,0.7912,0.7102,0.616,51,5,11,1,0.31,0.3,0.662,41,0.5998,0.7766,0.6158,0.5845,0.06,False,OK

[I 2026-07-09 11:35:54,136] Trial 67 finished with value: 0.6597633136094675 and parameters: {'n_estimators': 51, 'max_depth': 5, 'min_samples_split': 11, 'min_samples_leaf': 1}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:55,6,68,RandomForest,0.6592,0.7982,0.7516,0.5871,357,7,14,7,0.29,0.27,0.662,41,0.6225,0.7812,0.6819,0.5726,0.0367,False,OK

[I 2026-07-09 11:35:55,298] Trial 68 finished with value: 0.659217877094972 and parameters: {'n_estimators': 357, 'max_depth': 7, 'min_samples_split': 14, 'min_samples_leaf': 7}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:56,6,69,RandomForest,0.6508,0.7915,0.6529,0.6487,468,3,3,8,0.39,0.2,0.662,41,0.5957,0.7713,0.57,0.624,0.055,False,OK

[I 2026-07-09 11:35:56,750] Trial 69 finished with value: 0.6507936507936508 and parameters: {'n_estimators': 468, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 41 with value: 0.6619915848527349.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:57,6,70,RandomForest,0.662,0.8002,0.7611,0.5858,69,7,4,5,0.26,0.26,0.662,70,0.6286,0.7803,0.6997,0.5705,0.0335,False,OK

[I 2026-07-09 11:35:57,191] Trial 70 finished with value: 0.6620498614958449 and parameters: {'n_estimators': 69, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:57,6,71,RandomForest,0.6602,0.7985,0.7548,0.5866,83,9,4,3,0.27,0.27,0.662,70,0.6321,0.7809,0.6972,0.5781,0.0281,False,OK

[I 2026-07-09 11:35:57,675] Trial 71 finished with value: 0.6601671309192201 and parameters: {'n_estimators': 83, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:58,6,72,RandomForest,0.6611,0.7959,0.7516,0.59,340,12,15,10,0.3,0.28,0.662,70,0.62,0.7736,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:35:58,833] Trial 72 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 340, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 10}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:59,6,73,RandomForest,0.6574,0.7973,0.7548,0.5823,109,11,13,2,0.27,0.27,0.662,70,0.6301,0.7726,0.7023,0.5714,0.0273,False,OK

[I 2026-07-09 11:35:59,375] Trial 73 finished with value: 0.6574202496532594 and parameters: {'n_estimators': 109, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 2}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:59,6,74,RandomForest,0.6592,0.7983,0.7516,0.5871,103,7,2,4,0.28,0.26,0.662,70,0.6241,0.7828,0.6845,0.5736,0.0351,False,OK

[I 2026-07-09 11:35:59,907] Trial 74 finished with value: 0.659217877094972 and parameters: {'n_estimators': 103, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:00,6,75,RandomForest,0.6397,0.7857,0.6306,0.6492,51,3,5,3,0.39,0.2,0.662,70,0.5792,0.768,0.5445,0.6185,0.0606,False,OK

[I 2026-07-09 11:36:00,308] Trial 75 finished with value: 0.6397415185783522 and parameters: {'n_estimators': 51, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 3}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:00,6,76,RandomForest,0.659,0.7997,0.7325,0.599,72,7,19,3,0.29,0.26,0.662,70,0.619,0.784,0.6616,0.5817,0.04,False,OK

[I 2026-07-09 11:36:00,755] Trial 76 finished with value: 0.6590257879656161 and parameters: {'n_estimators': 72, 'max_depth': 7, 'min_samples_split': 19, 'min_samples_leaf': 3}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:01,6,77,RandomForest,0.6592,0.7962,0.7516,0.5871,74,8,6,6,0.29,0.27,0.662,70,0.6241,0.7801,0.6845,0.5736,0.0351,False,OK

[I 2026-07-09 11:36:01,211] Trial 77 finished with value: 0.659217877094972 and parameters: {'n_estimators': 74, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:01,6,78,RandomForest,0.6578,0.7963,0.7102,0.6126,89,6,4,6,0.3,0.27,0.662,70,0.6025,0.779,0.6209,0.5851,0.0553,False,OK

[I 2026-07-09 11:36:01,714] Trial 78 finished with value: 0.6578171091445427 and parameters: {'n_estimators': 89, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:02,6,79,RandomForest,0.6611,0.7979,0.7516,0.59,276,9,6,10,0.3,0.28,0.662,70,0.62,0.7768,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:36:02,703] Trial 79 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 276, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:03,6,80,RandomForest,0.6592,0.7951,0.7516,0.5871,291,16,2,8,0.3,0.29,0.662,70,0.6202,0.7715,0.6794,0.5705,0.039,False,OK

[I 2026-07-09 11:36:03,756] Trial 80 finished with value: 0.659217877094972 and parameters: {'n_estimators': 291, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:05,6,81,RandomForest,0.6611,0.7964,0.7516,0.59,499,10,5,9,0.3,0.27,0.662,70,0.62,0.7759,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:36:05,362] Trial 81 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 499, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:06,6,82,RandomForest,0.6611,0.7951,0.7516,0.59,334,13,6,10,0.3,0.28,0.662,70,0.62,0.7715,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:36:06,472] Trial 82 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 334, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:07,6,83,RandomForest,0.6611,0.7966,0.7516,0.59,372,10,2,9,0.3,0.27,0.662,70,0.62,0.7753,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:36:07,677] Trial 83 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 372, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:08,6,84,RandomForest,0.6611,0.7948,0.7516,0.59,284,16,2,10,0.3,0.28,0.662,70,0.6193,0.772,0.6768,0.5708,0.0417,False,OK

[I 2026-07-09 11:36:08,674] Trial 84 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 284, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:10,6,85,RandomForest,0.6611,0.7948,0.7516,0.59,489,18,6,10,0.3,0.28,0.662,70,0.6193,0.7712,0.6768,0.5708,0.0417,False,OK

[I 2026-07-09 11:36:10,188] Trial 85 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 489, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:10,6,86,RandomForest,0.6592,0.7952,0.7484,0.589,160,10,10,9,0.3,0.27,0.662,70,0.6184,0.7746,0.6743,0.5711,0.0408,False,OK

[I 2026-07-09 11:36:10,856] Trial 86 finished with value: 0.6591865357643759 and parameters: {'n_estimators': 160, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:12,6,87,RandomForest,0.6611,0.7961,0.7516,0.59,406,11,7,9,0.3,0.28,0.662,70,0.62,0.7761,0.6768,0.572,0.041,False,OK

[I 2026-07-09 11:36:12,144] Trial 87 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 406, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:13,6,88,RandomForest,0.6611,0.7958,0.7516,0.59,490,13,2,9,0.3,0.29,0.662,70,0.6209,0.7735,0.6794,0.5717,0.0401,False,OK

[I 2026-07-09 11:36:13,651] Trial 88 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 490, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:14,6,89,RandomForest,0.6517,0.7944,0.6943,0.6141,71,12,10,9,0.31,0.28,0.662,70,0.6179,0.7751,0.6336,0.6029,0.0339,False,OK

[I 2026-07-09 11:36:14,102] Trial 89 finished with value: 0.6517189835575485 and parameters: {'n_estimators': 71, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:15,6,90,RandomForest,0.6611,0.795,0.7516,0.59,416,14,10,10,0.3,0.28,0.662,70,0.6209,0.7719,0.6794,0.5717,0.0401,False,OK

[I 2026-07-09 11:36:15,439] Trial 90 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 416, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:16,6,91,RandomForest,0.6611,0.7949,0.7516,0.59,491,18,11,10,0.3,0.28,0.662,70,0.6193,0.7713,0.6768,0.5708,0.0417,False,OK

[I 2026-07-09 11:36:16,986] Trial 91 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 491, 'max_depth': 18, 'min_samples_split': 11, 'min_samples_leaf': 10}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:18,6,92,RandomForest,0.6583,0.7967,0.7516,0.5856,444,17,6,8,0.3,0.29,0.662,70,0.6195,0.7718,0.6794,0.5693,0.0388,False,OK

[I 2026-07-09 11:36:18,415] Trial 92 finished with value: 0.6582984658298466 and parameters: {'n_estimators': 444, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:19,6,93,RandomForest,0.6611,0.7959,0.7516,0.59,444,20,9,9,0.3,0.3,0.662,70,0.6209,0.7723,0.6794,0.5717,0.0401,False,OK

[I 2026-07-09 11:36:19,779] Trial 93 finished with value: 0.6610644257703081 and parameters: {'n_estimators': 444, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:21,6,94,RandomForest,0.6583,0.7959,0.7516,0.5856,478,20,8,8,0.3,0.28,0.662,70,0.6202,0.7721,0.6794,0.5705,0.0381,False,OK

[I 2026-07-09 11:36:21,250] Trial 94 finished with value: 0.6582984658298466 and parameters: {'n_estimators': 478, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 8}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:22,6,95,RandomForest,0.6601,0.7967,0.7516,0.5885,407,13,15,8,0.3,0.29,0.662,70,0.6209,0.7746,0.6794,0.5717,0.0392,False,OK

[I 2026-07-09 11:36:22,534] Trial 95 finished with value: 0.6601398601398601 and parameters: {'n_estimators': 407, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 8}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:23,6,96,RandomForest,0.6583,0.7966,0.7516,0.5856,240,11,3,4,0.28,0.28,0.662,70,0.6298,0.7783,0.6947,0.5759,0.0285,False,OK

[I 2026-07-09 11:36:23,402] Trial 96 finished with value: 0.6582984658298466 and parameters: {'n_estimators': 240, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:23,6,97,RandomForest,0.6582,0.7993,0.7452,0.5894,58,6,15,2,0.29,0.27,0.662,70,0.619,0.7822,0.6718,0.5739,0.0392,False,OK

[I 2026-07-09 11:36:23,818] Trial 97 finished with value: 0.6582278481012658 and parameters: {'n_estimators': 58, 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 2}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:24,6,98,RandomForest,0.6598,0.7923,0.7102,0.616,145,5,20,10,0.32,0.3,0.662,70,0.598,0.7725,0.6132,0.5835,0.0617,False,OK

[I 2026-07-09 11:36:24,446] Trial 98 finished with value: 0.6597633136094675 and parameters: {'n_estimators': 145, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 10}. Best is trial 70 with value: 0.6620498614958449.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:25,6,99,RandomForest,0.6601,0.7967,0.7516,0.5885,400,14,3,8,0.3,0.28,0.662,70,0.6209,0.7735,0.6794,0.5717,0.0392,False,OK

[I 2026-07-09 11:36:25,722] Trial 99 finished with value: 0.6601398601398601 and parameters: {'n_estimators': 400, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 70 with value: 0.6620498614958449.
/tmp/ipykernel_993/3487339742.py:307: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  sampler_xgb = TPESampler(
[I 2026-07-09 11:36:25,724] A new study created in memory with name: no-name-dce383df-8533-4598-aa79-17a47bb6b0e5

\n============================================================
🎉 RF NAS COMPLETE
============================================================
Best Trial: 70
Best F1: 0.6620
Best Params: {'n_estimators': 69, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 5}
\n============================================================
🚀 XGBOOST NAS
============================================================
[2026-07-09 11:36:25.725559] 🚀 Starting XGB NAS (100 trials)...

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:26,6,0,XGBoost,0.6577,0.7989,0.7803,0.5684,100,6,0.1,1.0,1.0,1,0.0,29,3,0.24,0.23,0.6577,0,0.6218,0.7783,0.7176,0.5486,0.0359,True,OK

[I 2026-07-09 11:36:26,539] Trial 0 finished with value: 0.6577181208053692 and parameters: {'n_estimators': 100, 'max_depth': 6, 'learning_rate': 0.1, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 0.0, 'patience': 3}. Best is trial 0 with value: 0.6577181208053692.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:26,6,1,XGBoost,0.6657,0.8044,0.7707,0.586,500,4,0.01,0.8,0.8,3,0.1,258,3,0.26,0.27,0.6657,1,0.6271,0.7813,0.6997,0.5682,0.0386,True,OK

[I 2026-07-09 11:36:26,997] Trial 1 finished with value: 0.6657496561210454 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.01, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1, 'patience': 3}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:27,6,2,XGBoost,0.6439,0.7923,0.7803,0.5481,50,8,0.3,0.7,0.7,1,0.0,8,3,0.26,0.31,0.6657,1,0.6177,0.7753,0.7277,0.5366,0.0262,True,OK

[I 2026-07-09 11:36:27,268] Trial 2 finished with value: 0.6438896189224704 and parameters: {'n_estimators': 50, 'max_depth': 8, 'learning_rate': 0.3, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1, 'gamma': 0.0, 'patience': 3}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:27,6,3,XGBoost,0.6639,0.7965,0.7611,0.5887,300,3,0.05,0.6,0.6,5,0.5,51,3,0.3,0.29,0.6657,1,0.6267,0.7795,0.6921,0.5726,0.0372,True,OK

[I 2026-07-09 11:36:27,618] Trial 3 finished with value: 0.6638888888888889 and parameters: {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.05, 'subsample': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5, 'gamma': 0.5, 'patience': 3}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:27,6,4,XGBoost,0.6548,0.7898,0.7643,0.5728,218,20,0.065049,0.799329,0.578009,2,0.058084,46,5,0.31,0.31,0.6657,1,0.6051,0.7634,0.6921,0.5375,0.0497,False,OK

[I 2026-07-09 11:36:28,004] Trial 4 finished with value: 0.654843110504775 and parameters: {'n_estimators': 218, 'max_depth': 20, 'learning_rate': 0.06504856968981275, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'min_child_weight': 2, 'gamma': 0.05808361216819946, 'patience': 5}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:31,6,5,XGBoost,0.6487,0.7879,0.7675,0.5618,321,15,0.001125,0.984955,0.916221,3,0.181825,320,2,0.31,0.32,0.6657,1,0.5989,0.7645,0.6819,0.5339,0.0498,False,OK

[I 2026-07-09 11:36:31,931] Trial 5 finished with value: 0.648721399730821 and parameters: {'n_estimators': 321, 'max_depth': 15, 'learning_rate': 0.001124579825911934, 'subsample': 0.9849549260809971, 'colsample_bytree': 0.9162213204002109, 'min_child_weight': 3, 'gamma': 0.18182496720710062, 'patience': 2}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:32,6,6,XGBoost,0.6531,0.7908,0.7675,0.5684,187,11,0.011748,0.645615,0.805926,2,0.292145,185,3,0.28,0.31,0.6657,1,0.6127,0.7668,0.7023,0.5433,0.0405,False,OK

[I 2026-07-09 11:36:32,463] Trial 6 finished with value: 0.6531165311653117 and parameters: {'n_estimators': 187, 'max_depth': 11, 'learning_rate': 0.01174843954800703, 'subsample': 0.645614570099021, 'colsample_bytree': 0.8059264473611898, 'min_child_weight': 2, 'gamma': 0.29214464853521815, 'patience': 3}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:33,6,7,XGBoost,0.6549,0.7914,0.7675,0.5711,255,16,0.003123,0.757117,0.796207,1,0.607545,254,2,0.3,0.31,0.6657,1,0.6173,0.7707,0.6997,0.5522,0.0376,False,OK

[I 2026-07-09 11:36:33,227] Trial 7 finished with value: 0.654891304347826 and parameters: {'n_estimators': 255, 'max_depth': 16, 'learning_rate': 0.003123317753376431, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'min_child_weight': 1, 'gamma': 0.6075448519014384, 'patience': 2}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:33,6,8,XGBoost,0.6429,0.7933,0.7739,0.5498,79,20,0.246597,0.904199,0.652307,1,0.684233,8,3,0.29,0.42,0.6657,1,0.6022,0.7673,0.7048,0.5256,0.0407,False,OK

[I 2026-07-09 11:36:33,547] Trial 8 finished with value: 0.6428571428571429 and parameters: {'n_estimators': 79, 'max_depth': 20, 'learning_rate': 0.24659691172104828, 'subsample': 0.9041986740582306, 'colsample_bytree': 0.6523068845866853, 'min_child_weight': 1, 'gamma': 0.6842330265121569, 'patience': 3}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:33,6,9,XGBoost,0.6497,0.7921,0.7325,0.5838,105,11,0.001217,0.95466,0.62939,7,0.311711,104,4,0.32,0.32,0.6657,1,0.6199,0.7728,0.6743,0.5736,0.0298,False,OK

[I 2026-07-09 11:36:33,976] Trial 9 finished with value: 0.6497175141242938 and parameters: {'n_estimators': 105, 'max_depth': 11, 'learning_rate': 0.0012167028814593455, 'subsample': 0.954660201039391, 'colsample_bytree': 0.6293899908000085, 'min_child_weight': 7, 'gamma': 0.31171107608941095, 'patience': 4}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:34,6,10,XGBoost,0.6657,0.8061,0.7707,0.586,448,3,0.021349,0.841898,0.761913,3,0.185566,176,4,0.27,0.28,0.6657,1,0.6288,0.7812,0.7048,0.5676,0.0369,False,OK

[I 2026-07-09 11:36:34,348] Trial 10 finished with value: 0.6657496561210454 and parameters: {'n_estimators': 448, 'max_depth': 3, 'learning_rate': 0.02134897198365317, 'subsample': 0.841898172650503, 'colsample_bytree': 0.7619128128093872, 'min_child_weight': 3, 'gamma': 0.18556568622710587, 'patience': 4}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:34,6,11,XGBoost,0.6612,0.8056,0.7643,0.5825,474,5,0.011441,0.775375,0.813293,1,0.157326,204,3,0.26,0.25,0.6657,1,0.6301,0.7858,0.7023,0.5714,0.031,False,OK

[I 2026-07-09 11:36:34,791] Trial 11 finished with value: 0.6611570247933884 and parameters: {'n_estimators': 474, 'max_depth': 5, 'learning_rate': 0.01144141475946822, 'subsample': 0.7753747596070704, 'colsample_bytree': 0.8132934323300276, 'min_child_weight': 1, 'gamma': 0.15732603553275873, 'patience': 3}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:35,6,12,XGBoost,0.6603,0.8007,0.7675,0.5793,353,6,0.008133,0.820265,0.972687,6,0.129774,314,3,0.26,0.24,0.6657,1,0.6168,0.776,0.6921,0.5562,0.0435,False,OK

[I 2026-07-09 11:36:35,352] Trial 12 finished with value: 0.6602739726027397 and parameters: {'n_estimators': 353, 'max_depth': 6, 'learning_rate': 0.008133405573570231, 'subsample': 0.8202653893527182, 'colsample_bytree': 0.9726872768199497, 'min_child_weight': 6, 'gamma': 0.12977386689343998, 'patience': 3}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:35,6,13,XGBoost,0.6602,0.7957,0.7643,0.5811,423,8,0.067931,0.898104,0.811985,4,0.44786,36,4,0.29,0.25,0.6657,1,0.615,0.7705,0.687,0.5567,0.0452,False,OK

[I 2026-07-09 11:36:35,674] Trial 13 finished with value: 0.6602475928473177 and parameters: {'n_estimators': 423, 'max_depth': 8, 'learning_rate': 0.0679306891540692, 'subsample': 0.8981039795803184, 'colsample_bytree': 0.8119853975542913, 'min_child_weight': 4, 'gamma': 0.44785986825007595, 'patience': 4}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:36,6,14,XGBoost,0.6592,0.7994,0.7516,0.5871,490,2,0.015266,0.729302,0.684721,7,0.112935,263,2,0.32,0.31,0.6657,1,0.624,0.7816,0.6819,0.5751,0.0352,False,OK

[I 2026-07-09 11:36:36,079] Trial 14 finished with value: 0.659217877094972 and parameters: {'n_estimators': 490, 'max_depth': 2, 'learning_rate': 0.015265615120011228, 'subsample': 0.7293023240258234, 'colsample_bytree': 0.6847206772510797, 'min_child_weight': 7, 'gamma': 0.11293526642960407, 'patience': 2}. Best is trial 1 with value: 0.6657496561210454.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:36,6,15,XGBoost,0.6676,0.8066,0.7739,0.587,382,4,0.096318,0.992013,0.640055,5,0.121329,27,3,0.26,0.26,0.6676,15,0.6301,0.7851,0.7023,0.5714,0.0374,False,OK

[I 2026-07-09 11:36:36,475] Trial 15 finished with value: 0.6675824175824175 and parameters: {'n_estimators': 382, 'max_depth': 4, 'learning_rate': 0.09631789525384356, 'subsample': 0.9920129988123861, 'colsample_bytree': 0.6400551889834704, 'min_child_weight': 5, 'gamma': 0.12132877818462398, 'patience': 3}. Best is trial 15 with value: 0.6675824175824175.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:36,6,16,XGBoost,0.6667,0.802,0.7707,0.5874,281,3,0.142931,0.928212,0.532076,3,0.283025,25,3,0.27,0.27,0.6676,15,0.6324,0.7849,0.7048,0.5735,0.0342,False,OK

[I 2026-07-09 11:36:36,763] Trial 16 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 281, 'max_depth': 3, 'learning_rate': 0.14293077490705453, 'subsample': 0.9282119110753435, 'colsample_bytree': 0.5320763806704023, 'min_child_weight': 3, 'gamma': 0.28302529015720124, 'patience': 3}. Best is trial 15 with value: 0.6675824175824175.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:37,6,17,XGBoost,0.6602,0.7974,0.758,0.5848,308,6,0.06745,0.910745,0.648898,3,0.535535,41,2,0.27,0.24,0.6676,15,0.6142,0.7781,0.6845,0.5569,0.046,False,OK

[I 2026-07-09 11:36:37,072] Trial 17 finished with value: 0.6601941747572816 and parameters: {'n_estimators': 308, 'max_depth': 6, 'learning_rate': 0.06745039400228034, 'subsample': 0.9107451517739795, 'colsample_bytree': 0.6488984182470833, 'min_child_weight': 3, 'gamma': 0.5355346505090712, 'patience': 2}. Best is trial 15 with value: 0.6675824175824175.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:37,6,18,XGBoost,0.6694,0.8021,0.7771,0.588,295,2,0.111008,0.948012,0.673945,6,0.064221,43,3,0.29,0.29,0.6694,18,0.6279,0.7819,0.6997,0.5694,0.0416,False,OK

[I 2026-07-09 11:36:37,370] Trial 18 finished with value: 0.6694101508916324 and parameters: {'n_estimators': 295, 'max_depth': 2, 'learning_rate': 0.11100783274318998, 'subsample': 0.9480123693393426, 'colsample_bytree': 0.6739452080830536, 'min_child_weight': 6, 'gamma': 0.06422100470509792, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:37,6,19,XGBoost,0.6592,0.8013,0.7548,0.5852,305,2,0.238441,0.951598,0.6052,7,0.026932,14,2,0.3,0.3,0.6694,18,0.6289,0.784,0.6921,0.5763,0.0303,False,OK

[I 2026-07-09 11:36:37,662] Trial 19 finished with value: 0.6592489568845619 and parameters: {'n_estimators': 305, 'max_depth': 2, 'learning_rate': 0.23844082757719579, 'subsample': 0.9515977684925708, 'colsample_bytree': 0.6051996096921004, 'min_child_weight': 7, 'gamma': 0.026932226434274745, 'patience': 2}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:38,6,20,XGBoost,0.6694,0.8054,0.7834,0.5843,149,4,0.113332,0.94136,0.819457,6,0.325454,25,2,0.26,0.26,0.6694,18,0.629,0.7801,0.7074,0.5662,0.0404,False,OK

[I 2026-07-09 11:36:38,017] Trial 20 finished with value: 0.6693877551020408 and parameters: {'n_estimators': 149, 'max_depth': 4, 'learning_rate': 0.11333186647600386, 'subsample': 0.941360471958717, 'colsample_bytree': 0.8194570485830894, 'min_child_weight': 6, 'gamma': 0.32545376047867824, 'patience': 2}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:38,6,21,XGBoost,0.6658,0.8067,0.8025,0.5688,124,5,0.294006,0.806452,0.811606,8,0.283653,11,2,0.24,0.25,0.6694,18,0.6205,0.7748,0.7176,0.5465,0.0453,False,OK

[I 2026-07-09 11:36:38,296] Trial 21 finished with value: 0.665785997357992 and parameters: {'n_estimators': 124, 'max_depth': 5, 'learning_rate': 0.2940057393970998, 'subsample': 0.8064516041897251, 'colsample_bytree': 0.8116056576164153, 'min_child_weight': 8, 'gamma': 0.2836534494609039, 'patience': 2}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:38,6,22,XGBoost,0.6667,0.8057,0.7803,0.5819,227,4,0.052377,0.998965,0.799747,10,0.114597,73,4,0.25,0.3,0.6694,18,0.6249,0.7844,0.7099,0.558,0.0418,False,OK

[I 2026-07-09 11:36:38,629] Trial 22 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 227, 'max_depth': 4, 'learning_rate': 0.052376679924630444, 'subsample': 0.9989645635839076, 'colsample_bytree': 0.7997468553319516, 'min_child_weight': 10, 'gamma': 0.11459691969740052, 'patience': 4}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:38,6,23,XGBoost,0.6685,0.8052,0.7834,0.5829,120,3,0.086706,0.98083,0.882,7,0.659724,43,3,0.25,0.28,0.6694,18,0.6263,0.7817,0.7099,0.5602,0.0422,False,OK

[I 2026-07-09 11:36:38,929] Trial 23 finished with value: 0.6684782608695652 and parameters: {'n_estimators': 120, 'max_depth': 3, 'learning_rate': 0.08670622441560731, 'subsample': 0.9808299638340698, 'colsample_bytree': 0.8820003746855838, 'min_child_weight': 7, 'gamma': 0.6597236662182191, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:39,6,24,XGBoost,0.6694,0.8075,0.7803,0.5861,102,4,0.060039,0.961119,0.86324,8,0.848727,52,3,0.26,0.31,0.6694,18,0.6258,0.7837,0.715,0.5564,0.0436,False,OK

[I 2026-07-09 11:36:39,245] Trial 24 finished with value: 0.6693989071038251 and parameters: {'n_estimators': 102, 'max_depth': 4, 'learning_rate': 0.06003854004795514, 'subsample': 0.9611192014760638, 'colsample_bytree': 0.863239594725774, 'min_child_weight': 8, 'gamma': 0.8487272573049465, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:39,6,25,XGBoost,0.6549,0.7949,0.7675,0.5711,57,9,0.051384,0.857074,0.882052,10,0.744942,54,2,0.26,0.26,0.6694,18,0.6178,0.7725,0.6972,0.5547,0.0371,False,OK

[I 2026-07-09 11:36:39,574] Trial 25 finished with value: 0.654891304347826 and parameters: {'n_estimators': 57, 'max_depth': 9, 'learning_rate': 0.051383720107017784, 'subsample': 0.8570744638630036, 'colsample_bytree': 0.8820522181971124, 'min_child_weight': 10, 'gamma': 0.7449421284614484, 'patience': 2}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:39,6,26,XGBoost,0.6685,0.8019,0.7739,0.5884,75,5,0.00997,0.984664,0.877041,9,0.969595,74,3,0.29,0.28,0.6694,18,0.625,0.783,0.6997,0.5647,0.0435,False,OK

[I 2026-07-09 11:36:39,913] Trial 26 finished with value: 0.6685006877579092 and parameters: {'n_estimators': 75, 'max_depth': 5, 'learning_rate': 0.009970470950028638, 'subsample': 0.984663979900695, 'colsample_bytree': 0.8770407693600549, 'min_child_weight': 9, 'gamma': 0.9695948496083986, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:40,6,27,XGBoost,0.6496,0.79,0.7675,0.5631,160,10,0.068681,0.938202,0.754066,7,0.176281,37,2,0.26,0.33,0.6694,18,0.6111,0.7642,0.6997,0.5424,0.0385,False,OK

[I 2026-07-09 11:36:40,246] Trial 27 finished with value: 0.6495956873315364 and parameters: {'n_estimators': 160, 'max_depth': 10, 'learning_rate': 0.06868059628275772, 'subsample': 0.9382020442217296, 'colsample_bytree': 0.7540659524953307, 'min_child_weight': 7, 'gamma': 0.17628147268060318, 'patience': 2}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:40,6,28,XGBoost,0.6549,0.7948,0.7675,0.5711,64,8,0.06515,0.948787,0.611859,9,0.757113,44,4,0.26,0.27,0.6694,18,0.6183,0.7719,0.6947,0.5571,0.0365,False,OK

[I 2026-07-09 11:36:40,618] Trial 28 finished with value: 0.654891304347826 and parameters: {'n_estimators': 64, 'max_depth': 8, 'learning_rate': 0.065149712443338, 'subsample': 0.9487866522061413, 'colsample_bytree': 0.6118586639492374, 'min_child_weight': 9, 'gamma': 0.7571126399022485, 'patience': 4}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:41,6,29,XGBoost,0.6584,0.8005,0.758,0.5819,257,6,0.029035,0.767201,0.919459,10,0.80443,110,4,0.28,0.25,0.6694,18,0.6196,0.7811,0.6921,0.5608,0.0388,False,OK

[I 2026-07-09 11:36:41,021] Trial 29 finished with value: 0.6583679114799447 and parameters: {'n_estimators': 257, 'max_depth': 6, 'learning_rate': 0.0290353420373122, 'subsample': 0.7672008746306255, 'colsample_bytree': 0.9194587061057105, 'min_child_weight': 10, 'gamma': 0.8044300697227731, 'patience': 4}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:41,6,30,XGBoost,0.6648,0.8068,0.7739,0.5827,200,3,0.042948,0.977832,0.825031,6,0.149564,76,2,0.27,0.27,0.6694,18,0.6297,0.7839,0.7074,0.5673,0.0352,False,OK

[I 2026-07-09 11:36:41,341] Trial 30 finished with value: 0.66484268125855 and parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.042947770705748685, 'subsample': 0.9778322662681109, 'colsample_bytree': 0.8250305547059915, 'min_child_weight': 6, 'gamma': 0.1495639218850845, 'patience': 2}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:41,6,31,XGBoost,0.662,0.797,0.758,0.5877,81,9,0.007386,0.868102,0.820593,9,0.991193,80,3,0.3,0.29,0.6694,18,0.6173,0.7769,0.6794,0.5657,0.0447,False,OK

[I 2026-07-09 11:36:41,807] Trial 31 finished with value: 0.6620305980528511 and parameters: {'n_estimators': 81, 'max_depth': 9, 'learning_rate': 0.007385724249216141, 'subsample': 0.8681021411438805, 'colsample_bytree': 0.8205931088566604, 'min_child_weight': 9, 'gamma': 0.9911928116419313, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:44,6,32,XGBoost,0.6676,0.8023,0.7707,0.5888,112,5,0.010202,0.980256,0.792546,9,0.880847,111,3,0.28,0.29,0.6694,18,0.6256,0.7811,0.6972,0.5673,0.042,False,OK

[I 2026-07-09 11:36:44,768] Trial 32 finished with value: 0.6675862068965517 and parameters: {'n_estimators': 112, 'max_depth': 5, 'learning_rate': 0.01020210927008105, 'subsample': 0.980255506643274, 'colsample_bytree': 0.7925464998490407, 'min_child_weight': 9, 'gamma': 0.8808466626675656, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:45,6,33,XGBoost,0.6667,0.7963,0.7643,0.5911,52,6,0.042509,0.978288,0.895508,10,0.992261,50,4,0.28,0.24,0.6694,18,0.6204,0.7773,0.6819,0.569,0.0463,False,OK

[I 2026-07-09 11:36:45,112] Trial 33 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 52, 'max_depth': 6, 'learning_rate': 0.042509170005591825, 'subsample': 0.9782879570942463, 'colsample_bytree': 0.8955082314043431, 'min_child_weight': 10, 'gamma': 0.992260930074723, 'patience': 4}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:45,6,34,XGBoost,0.63,0.779,0.6752,0.5905,82,2,0.004809,0.913266,0.95534,10,0.991465,81,3,0.33,0.28,0.6694,18,0.5862,0.7633,0.6056,0.568,0.0438,False,OK

[I 2026-07-09 11:36:45,448] Trial 34 finished with value: 0.6300148588410104 and parameters: {'n_estimators': 82, 'max_depth': 2, 'learning_rate': 0.004808609727143809, 'subsample': 0.9132661123404078, 'colsample_bytree': 0.9553397805794733, 'min_child_weight': 10, 'gamma': 0.9914654369437755, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:45,6,35,XGBoost,0.6549,0.7924,0.7707,0.5694,186,9,0.128883,0.978957,0.903003,4,0.251974,20,3,0.28,0.29,0.6694,18,0.6075,0.765,0.6972,0.5383,0.0474,False,OK

[I 2026-07-09 11:36:45,782] Trial 35 finished with value: 0.6549391069012178 and parameters: {'n_estimators': 186, 'max_depth': 9, 'learning_rate': 0.12888305426752147, 'subsample': 0.9789568593617172, 'colsample_bytree': 0.9030030017699173, 'min_child_weight': 4, 'gamma': 0.2519737422252555, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:46,6,36,XGBoost,0.663,0.8015,0.7707,0.5817,237,3,0.027794,0.80226,0.705339,5,0.061951,138,4,0.27,0.29,0.6694,18,0.6288,0.7827,0.7048,0.5676,0.0342,False,OK

[I 2026-07-09 11:36:46,154] Trial 36 finished with value: 0.663013698630137 and parameters: {'n_estimators': 237, 'max_depth': 3, 'learning_rate': 0.02779407055011885, 'subsample': 0.802260187045819, 'colsample_bytree': 0.7053386502080325, 'min_child_weight': 5, 'gamma': 0.06195053611280988, 'patience': 4}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:46,6,37,XGBoost,0.6685,0.8041,0.7739,0.5884,141,4,0.113265,0.839554,0.874439,8,0.997775,28,3,0.28,0.25,0.6694,18,0.6241,0.7821,0.6972,0.5649,0.0444,False,OK

[I 2026-07-09 11:36:46,450] Trial 37 finished with value: 0.6685006877579092 and parameters: {'n_estimators': 141, 'max_depth': 4, 'learning_rate': 0.11326474673296517, 'subsample': 0.8395541532575634, 'colsample_bytree': 0.8744387947650892, 'min_child_weight': 8, 'gamma': 0.9977749160588147, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:46,6,38,XGBoost,0.6621,0.8052,0.7739,0.5786,142,3,0.074752,0.932741,0.864695,2,0.582979,43,2,0.26,0.28,0.6694,18,0.6292,0.7838,0.7125,0.5634,0.0329,False,OK

[I 2026-07-09 11:36:46,760] Trial 38 finished with value: 0.662125340599455 and parameters: {'n_estimators': 142, 'max_depth': 3, 'learning_rate': 0.07475197786263194, 'subsample': 0.9327412712095438, 'colsample_bytree': 0.8646954735349888, 'min_child_weight': 2, 'gamma': 0.582978808496077, 'patience': 2}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:47,6,39,XGBoost,0.6685,0.8049,0.7803,0.5847,264,4,0.054034,0.887959,0.652507,7,0.370791,67,3,0.26,0.29,0.6694,18,0.624,0.7821,0.7074,0.5582,0.0445,False,OK

[I 2026-07-09 11:36:47,092] Trial 39 finished with value: 0.6684856753069577 and parameters: {'n_estimators': 264, 'max_depth': 4, 'learning_rate': 0.05403429248388556, 'subsample': 0.8879585124195674, 'colsample_bytree': 0.6525070874685834, 'min_child_weight': 7, 'gamma': 0.3707911931879172, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:47,6,40,XGBoost,0.6667,0.8028,0.7675,0.5892,90,2,0.260589,0.917158,0.884161,6,0.21934,18,2,0.3,0.3,0.6694,18,0.6315,0.7813,0.6997,0.5753,0.0352,False,OK

[I 2026-07-09 11:36:47,383] Trial 40 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 90, 'max_depth': 2, 'learning_rate': 0.2605894866544237, 'subsample': 0.9171579230323592, 'colsample_bytree': 0.8841614124941237, 'min_child_weight': 6, 'gamma': 0.21934008737433036, 'patience': 2}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:47,6,41,XGBoost,0.6602,0.7972,0.7611,0.5829,71,2,0.083263,0.604428,0.932406,9,0.698766,45,3,0.3,0.3,0.6694,18,0.6306,0.7804,0.6972,0.5756,0.0296,False,OK

[I 2026-07-09 11:36:47,688] Trial 41 finished with value: 0.6602209944751382 and parameters: {'n_estimators': 71, 'max_depth': 2, 'learning_rate': 0.08326322268819275, 'subsample': 0.6044275281721007, 'colsample_bytree': 0.9324062366830876, 'min_child_weight': 9, 'gamma': 0.6987664209902718, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:47,6,42,XGBoost,0.6531,0.7989,0.7675,0.5684,224,10,0.160641,0.978578,0.646019,6,0.011576,14,4,0.28,0.29,0.6694,18,0.6133,0.7679,0.6921,0.5506,0.0398,False,OK

[I 2026-07-09 11:36:47,983] Trial 42 finished with value: 0.6531165311653117 and parameters: {'n_estimators': 224, 'max_depth': 10, 'learning_rate': 0.16064139299419644, 'subsample': 0.9785775147500271, 'colsample_bytree': 0.6460194638706336, 'min_child_weight': 6, 'gamma': 0.011575675344289167, 'patience': 4}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:48,6,43,XGBoost,0.6639,0.803,0.7675,0.585,196,2,0.247637,0.869151,0.862685,6,0.958199,26,2,0.27,0.31,0.6694,18,0.6286,0.7823,0.6997,0.5705,0.0353,False,OK

[I 2026-07-09 11:36:48,345] Trial 43 finished with value: 0.6639118457300276 and parameters: {'n_estimators': 196, 'max_depth': 2, 'learning_rate': 0.2476368822656518, 'subsample': 0.8691506815678146, 'colsample_bytree': 0.8626848142450052, 'min_child_weight': 6, 'gamma': 0.9581989835783982, 'patience': 2}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:48,6,44,XGBoost,0.6676,0.8019,0.7771,0.5851,185,5,0.059383,0.778971,0.753016,8,0.853255,44,3,0.25,0.25,0.6694,18,0.6319,0.7839,0.7099,0.5694,0.0356,False,OK

[I 2026-07-09 11:36:48,658] Trial 44 finished with value: 0.667578659370725 and parameters: {'n_estimators': 185, 'max_depth': 5, 'learning_rate': 0.059382697466826964, 'subsample': 0.7789706741941969, 'colsample_bytree': 0.7530163129191739, 'min_child_weight': 8, 'gamma': 0.8532549261049794, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:49,6,45,XGBoost,0.6639,0.7992,0.7675,0.585,62,6,0.048451,0.905665,0.756281,5,0.985709,57,3,0.25,0.3,0.6694,18,0.6109,0.7771,0.687,0.5499,0.0531,False,OK

[I 2026-07-09 11:36:49,031] Trial 45 finished with value: 0.6639118457300276 and parameters: {'n_estimators': 62, 'max_depth': 6, 'learning_rate': 0.04845122791971091, 'subsample': 0.9056648505788281, 'colsample_bytree': 0.7562808962506619, 'min_child_weight': 5, 'gamma': 0.9857094581941516, 'patience': 3}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:49,6,46,XGBoost,0.654,0.791,0.7675,0.5697,134,12,0.00586,0.99061,0.992604,3,0.940065,133,4,0.3,0.28,0.6694,18,0.6104,0.7663,0.6896,0.5475,0.0436,False,OK

[I 2026-07-09 11:36:49,537] Trial 46 finished with value: 0.6540027137042063 and parameters: {'n_estimators': 134, 'max_depth': 12, 'learning_rate': 0.0058595625837310475, 'subsample': 0.9906095936174711, 'colsample_bytree': 0.9926038737851366, 'min_child_weight': 3, 'gamma': 0.9400649357575187, 'patience': 4}. Best is trial 18 with value: 0.6694101508916324.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:49,6,47,XGBoost,0.6712,0.8054,0.793,0.5818,136,5,0.257024,0.73804,0.833615,9,0.988626,8,2,0.25,0.28,0.6712,47,0.6256,0.7812,0.7226,0.5515,0.0456,False,OK

[I 2026-07-09 11:36:49,820] Trial 47 finished with value: 0.6711590296495957 and parameters: {'n_estimators': 136, 'max_depth': 5, 'learning_rate': 0.25702417209507145, 'subsample': 0.7380397704122255, 'colsample_bytree': 0.8336145544002741, 'min_child_weight': 9, 'gamma': 0.9886264497813226, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:50,6,48,XGBoost,0.6676,0.8082,0.7803,0.5833,118,4,0.105085,0.746634,0.840727,9,0.952125,29,2,0.25,0.25,0.6712,47,0.6317,0.7833,0.7201,0.5626,0.0359,False,OK

[I 2026-07-09 11:36:50,128] Trial 48 finished with value: 0.667574931880109 and parameters: {'n_estimators': 118, 'max_depth': 4, 'learning_rate': 0.10508532249970266, 'subsample': 0.7466340432319577, 'colsample_bytree': 0.8407268330147646, 'min_child_weight': 9, 'gamma': 0.952125383012925, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:50,6,49,XGBoost,0.6604,0.7976,0.7834,0.5708,181,7,0.269205,0.728851,0.643603,9,0.98583,8,2,0.27,0.3,0.6712,47,0.62,0.7756,0.7099,0.5503,0.0404,False,OK

[I 2026-07-09 11:36:50,423] Trial 49 finished with value: 0.6604026845637584 and parameters: {'n_estimators': 181, 'max_depth': 7, 'learning_rate': 0.26920525426236896, 'subsample': 0.7288513856411514, 'colsample_bytree': 0.6436029589733164, 'min_child_weight': 9, 'gamma': 0.9858300701885587, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:50,6,50,XGBoost,0.6648,0.8047,0.7707,0.5845,201,5,0.157653,0.97251,0.748969,4,0.370815,15,2,0.26,0.29,0.6712,47,0.6171,0.7784,0.6972,0.5535,0.0477,False,OK

[I 2026-07-09 11:36:50,720] Trial 50 finished with value: 0.6648351648351648 and parameters: {'n_estimators': 201, 'max_depth': 5, 'learning_rate': 0.15765307186032856, 'subsample': 0.9725097778339757, 'colsample_bytree': 0.7489686848474382, 'min_child_weight': 4, 'gamma': 0.3708149540945489, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:51,6,51,XGBoost,0.6621,0.799,0.7739,0.5786,166,8,0.125043,0.961095,0.907056,8,0.95077,16,3,0.28,0.28,0.6712,47,0.6161,0.771,0.6921,0.5551,0.046,False,OK

[I 2026-07-09 11:36:51,059] Trial 51 finished with value: 0.662125340599455 and parameters: {'n_estimators': 166, 'max_depth': 8, 'learning_rate': 0.12504264311268873, 'subsample': 0.9610946420507029, 'colsample_bytree': 0.9070558229589881, 'min_child_weight': 8, 'gamma': 0.9507704733855111, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:51,6,52,XGBoost,0.6648,0.8016,0.7707,0.5845,123,2,0.082325,0.776397,0.969028,8,0.905486,64,4,0.28,0.3,0.6712,47,0.6295,0.782,0.7048,0.5688,0.0353,False,OK

[I 2026-07-09 11:36:51,459] Trial 52 finished with value: 0.6648351648351648 and parameters: {'n_estimators': 123, 'max_depth': 2, 'learning_rate': 0.08232539621999524, 'subsample': 0.7763967080768815, 'colsample_bytree': 0.9690280641096843, 'min_child_weight': 8, 'gamma': 0.9054856754940188, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:51,6,53,XGBoost,0.6575,0.8006,0.758,0.5805,77,7,0.165483,0.708249,0.927076,8,0.99964,17,3,0.28,0.28,0.6712,47,0.6217,0.7716,0.6921,0.5643,0.0357,False,OK

[I 2026-07-09 11:36:51,768] Trial 53 finished with value: 0.6574585635359116 and parameters: {'n_estimators': 77, 'max_depth': 7, 'learning_rate': 0.1654831214821415, 'subsample': 0.7082490294445597, 'colsample_bytree': 0.927076394598435, 'min_child_weight': 8, 'gamma': 0.9996404496638162, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:52,6,54,XGBoost,0.663,0.7969,0.758,0.5891,75,8,0.019054,0.968219,0.976655,8,0.909413,74,2,0.29,0.29,0.6712,47,0.6161,0.7732,0.6819,0.5618,0.0469,False,OK

[I 2026-07-09 11:36:52,169] Trial 54 finished with value: 0.6629526462395543 and parameters: {'n_estimators': 75, 'max_depth': 8, 'learning_rate': 0.01905377641130429, 'subsample': 0.9682186555751876, 'colsample_bytree': 0.9766548022523097, 'min_child_weight': 8, 'gamma': 0.9094133100969423, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:52,6,55,XGBoost,0.6576,0.8006,0.7739,0.5718,238,7,0.282554,0.694142,0.859282,10,0.797085,11,2,0.27,0.26,0.6712,47,0.6278,0.7746,0.7125,0.5611,0.0298,False,OK

[I 2026-07-09 11:36:52,516] Trial 55 finished with value: 0.6576454668470907 and parameters: {'n_estimators': 238, 'max_depth': 7, 'learning_rate': 0.2825539152142696, 'subsample': 0.694142311576224, 'colsample_bytree': 0.8592816919368488, 'min_child_weight': 10, 'gamma': 0.7970846195810831, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:52,6,56,XGBoost,0.6667,0.8041,0.7771,0.5837,109,3,0.04983,0.938796,0.723863,7,0.485802,68,2,0.27,0.28,0.6712,47,0.6274,0.7814,0.7048,0.5653,0.0393,False,OK

[I 2026-07-09 11:36:52,844] Trial 56 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 109, 'max_depth': 3, 'learning_rate': 0.049830181889130035, 'subsample': 0.9387959217048827, 'colsample_bytree': 0.7238632353107621, 'min_child_weight': 7, 'gamma': 0.48580200637316395, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:53,6,57,XGBoost,0.6685,0.8008,0.7771,0.5865,267,2,0.100727,0.906748,0.660908,4,0.049396,58,3,0.28,0.29,0.6712,47,0.6282,0.7843,0.7074,0.565,0.0402,False,OK

[I 2026-07-09 11:36:53,159] Trial 57 finished with value: 0.6684931506849315 and parameters: {'n_estimators': 267, 'max_depth': 2, 'learning_rate': 0.10072653840483922, 'subsample': 0.90674791023372, 'colsample_bytree': 0.6609076829354502, 'min_child_weight': 4, 'gamma': 0.04939616034149417, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:53,6,58,XGBoost,0.663,0.8042,0.7707,0.5817,140,3,0.114865,0.948399,0.820921,9,0.960566,26,3,0.27,0.28,0.6712,47,0.6288,0.7813,0.7048,0.5676,0.0342,False,OK

[I 2026-07-09 11:36:53,526] Trial 58 finished with value: 0.663013698630137 and parameters: {'n_estimators': 140, 'max_depth': 3, 'learning_rate': 0.11486519923471669, 'subsample': 0.9483992755957968, 'colsample_bytree': 0.8209212257346795, 'min_child_weight': 9, 'gamma': 0.9605663938971709, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:53,6,59,XGBoost,0.6355,0.7863,0.672,0.6029,154,15,0.001021,0.613957,0.570838,10,0.476191,153,4,0.33,0.32,0.6712,47,0.586,0.7716,0.598,0.5746,0.0495,False,OK

[I 2026-07-09 11:36:53,950] Trial 59 finished with value: 0.6355421686746988 and parameters: {'n_estimators': 154, 'max_depth': 15, 'learning_rate': 0.001021220035378734, 'subsample': 0.613956579860588, 'colsample_bytree': 0.5708383644203106, 'min_child_weight': 10, 'gamma': 0.47619127099878844, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:54,6,60,XGBoost,0.6271,0.7581,0.6051,0.6507,93,2,0.00284,0.959622,0.824055,5,0.939009,92,2,0.33,0.29,0.6712,47,0.5734,0.7338,0.5267,0.6292,0.0537,False,OK

[I 2026-07-09 11:36:54,304] Trial 60 finished with value: 0.6270627062706271 and parameters: {'n_estimators': 93, 'max_depth': 2, 'learning_rate': 0.002840272628020466, 'subsample': 0.9596219165209624, 'colsample_bytree': 0.8240548945803302, 'min_child_weight': 5, 'gamma': 0.9390094481323003, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:54,6,61,XGBoost,0.6648,0.8047,0.7675,0.5864,283,2,0.041788,0.912409,0.73827,5,0.15347,116,3,0.29,0.3,0.6712,47,0.6261,0.7827,0.6947,0.5699,0.0387,False,OK

[I 2026-07-09 11:36:54,652] Trial 61 finished with value: 0.6648275862068965 and parameters: {'n_estimators': 283, 'max_depth': 2, 'learning_rate': 0.04178792378164806, 'subsample': 0.9124085224346098, 'colsample_bytree': 0.738269608489179, 'min_child_weight': 5, 'gamma': 0.15347014509185952, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:54,6,62,XGBoost,0.6639,0.802,0.7643,0.5868,264,2,0.251859,0.88544,0.768894,4,0.205125,18,3,0.3,0.31,0.6712,47,0.6276,0.7804,0.6947,0.5723,0.0363,False,OK

[I 2026-07-09 11:36:54,945] Trial 62 finished with value: 0.6639004149377593 and parameters: {'n_estimators': 264, 'max_depth': 2, 'learning_rate': 0.25185857512059373, 'subsample': 0.8854397639517084, 'colsample_bytree': 0.7688936909925485, 'min_child_weight': 4, 'gamma': 0.205124811555227, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:56,6,63,XGBoost,0.6639,0.8039,0.7739,0.5813,273,3,0.093333,0.999766,0.672466,7,0.107212,44,4,0.27,0.29,0.6712,47,0.6275,0.7824,0.7074,0.5639,0.0364,False,OK

[I 2026-07-09 11:36:56,275] Trial 63 finished with value: 0.6639344262295082 and parameters: {'n_estimators': 273, 'max_depth': 3, 'learning_rate': 0.09333312092860366, 'subsample': 0.9997658930948822, 'colsample_bytree': 0.6724661934169086, 'min_child_weight': 7, 'gamma': 0.10721152032737462, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:58,6,64,XGBoost,0.6224,0.7835,0.6561,0.592,153,2,0.002673,0.56862,0.961121,2,0.857489,152,4,0.33,0.28,0.6712,47,0.5903,0.7672,0.6031,0.578,0.0321,False,OK

[I 2026-07-09 11:36:58,262] Trial 64 finished with value: 0.622356495468278 and parameters: {'n_estimators': 153, 'max_depth': 2, 'learning_rate': 0.002672577557110557, 'subsample': 0.5686202072656128, 'colsample_bytree': 0.9611211174493228, 'min_child_weight': 2, 'gamma': 0.8574888470389677, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:58,6,65,XGBoost,0.6694,0.8026,0.7771,0.588,202,4,0.270475,0.853198,0.799465,8,0.954799,11,4,0.26,0.3,0.6712,47,0.628,0.777,0.7023,0.5679,0.0414,False,OK

[I 2026-07-09 11:36:58,538] Trial 65 finished with value: 0.6694101508916324 and parameters: {'n_estimators': 202, 'max_depth': 4, 'learning_rate': 0.2704754238122186, 'subsample': 0.8531982111114785, 'colsample_bytree': 0.799464669706508, 'min_child_weight': 8, 'gamma': 0.9547988083542104, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:58,6,66,XGBoost,0.6566,0.7952,0.7611,0.5773,347,7,0.175826,0.869049,0.79079,8,0.914906,18,4,0.28,0.23,0.6712,47,0.6128,0.7712,0.6845,0.5546,0.0438,False,OK

[I 2026-07-09 11:36:58,844] Trial 66 finished with value: 0.6565934065934066 and parameters: {'n_estimators': 347, 'max_depth': 7, 'learning_rate': 0.1758257235329535, 'subsample': 0.8690485602792078, 'colsample_bytree': 0.7907903436696939, 'min_child_weight': 8, 'gamma': 0.9149060834294418, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:59,6,67,XGBoost,0.6514,0.7934,0.7707,0.5641,163,12,0.138321,0.757842,0.902065,7,0.83327,18,5,0.28,0.29,0.6712,47,0.6138,0.7674,0.6997,0.5467,0.0376,False,OK

[I 2026-07-09 11:36:59,191] Trial 67 finished with value: 0.6514131897711979 and parameters: {'n_estimators': 163, 'max_depth': 12, 'learning_rate': 0.13832074401307243, 'subsample': 0.7578422126541681, 'colsample_bytree': 0.9020646725787721, 'min_child_weight': 7, 'gamma': 0.8332703348687553, 'patience': 5}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:59,6,68,XGBoost,0.6639,0.8051,0.7643,0.5868,272,4,0.249222,0.865642,0.699904,6,0.848084,14,4,0.29,0.3,0.6712,47,0.6126,0.7742,0.6819,0.556,0.0513,False,OK

[I 2026-07-09 11:36:59,493] Trial 68 finished with value: 0.6639004149377593 and parameters: {'n_estimators': 272, 'max_depth': 4, 'learning_rate': 0.24922194600624517, 'subsample': 0.8656422982072682, 'colsample_bytree': 0.6999037786997928, 'min_child_weight': 6, 'gamma': 0.848083584171151, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:59,6,69,XGBoost,0.6639,0.8032,0.7739,0.5813,208,3,0.152853,0.801934,0.822281,6,0.987405,27,4,0.26,0.26,0.6712,47,0.6254,0.7807,0.7074,0.5605,0.0385,False,OK

[I 2026-07-09 11:36:59,820] Trial 69 finished with value: 0.6639344262295082 and parameters: {'n_estimators': 208, 'max_depth': 3, 'learning_rate': 0.15285319778309397, 'subsample': 0.8019336560758088, 'colsample_bytree': 0.8222812355930965, 'min_child_weight': 6, 'gamma': 0.9874054202776723, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:00,6,70,XGBoost,0.6585,0.7926,0.7739,0.5731,285,12,0.115063,0.552564,0.967993,4,0.975333,21,2,0.28,0.27,0.6712,47,0.6109,0.7608,0.6972,0.5437,0.0476,False,OK

[I 2026-07-09 11:37:00,160] Trial 70 finished with value: 0.6585365853658537 and parameters: {'n_estimators': 285, 'max_depth': 12, 'learning_rate': 0.11506258700884622, 'subsample': 0.5525640522825467, 'colsample_bytree': 0.9679931209964303, 'min_child_weight': 4, 'gamma': 0.9753331353997321, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:00,6,71,XGBoost,0.655,0.7957,0.7771,0.5661,435,20,0.006632,0.584179,0.960767,6,0.686944,407,5,0.26,0.25,0.6712,47,0.6162,0.7721,0.7048,0.5474,0.0388,False,OK

[I 2026-07-09 11:37:00,966] Trial 71 finished with value: 0.6550335570469799 and parameters: {'n_estimators': 435, 'max_depth': 20, 'learning_rate': 0.006631685076863805, 'subsample': 0.5841786569807509, 'colsample_bytree': 0.9607674261367027, 'min_child_weight': 6, 'gamma': 0.6869436850290915, 'patience': 5}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:01,6,72,XGBoost,0.663,0.8026,0.7675,0.5835,211,2,0.251382,0.961568,0.921775,7,0.956762,26,4,0.27,0.29,0.6712,47,0.6279,0.7805,0.6997,0.5694,0.0351,False,OK

[I 2026-07-09 11:37:01,262] Trial 72 finished with value: 0.6629986244841816 and parameters: {'n_estimators': 211, 'max_depth': 2, 'learning_rate': 0.2513819567158875, 'subsample': 0.961568485212173, 'colsample_bytree': 0.9217746030544706, 'min_child_weight': 7, 'gamma': 0.9567624157059221, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:01,6,73,XGBoost,0.6676,0.7979,0.7675,0.5907,392,19,0.215602,0.591663,0.500771,8,0.378049,15,5,0.3,0.29,0.6712,47,0.6231,0.7699,0.6921,0.5667,0.0445,False,OK

[I 2026-07-09 11:37:01,580] Trial 73 finished with value: 0.667590027700831 and parameters: {'n_estimators': 392, 'max_depth': 19, 'learning_rate': 0.2156022710264404, 'subsample': 0.5916626817329522, 'colsample_bytree': 0.5007709687521267, 'min_child_weight': 8, 'gamma': 0.3780486114155994, 'patience': 5}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:01,6,74,XGBoost,0.6602,0.7974,0.7611,0.5829,104,3,0.126625,0.534437,0.658147,1,0.261151,24,5,0.29,0.29,0.6712,47,0.6323,0.7826,0.7023,0.575,0.0279,False,OK

[I 2026-07-09 11:37:01,878] Trial 74 finished with value: 0.6602209944751382 and parameters: {'n_estimators': 104, 'max_depth': 3, 'learning_rate': 0.12662523584923827, 'subsample': 0.5344368730696502, 'colsample_bytree': 0.6581468648802479, 'min_child_weight': 1, 'gamma': 0.26115110298680566, 'patience': 5}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:02,6,75,XGBoost,0.6658,0.8033,0.7866,0.5771,198,3,0.20729,0.630075,0.733914,10,0.940499,24,4,0.25,0.29,0.6712,47,0.627,0.7788,0.7099,0.5614,0.0388,False,OK

[I 2026-07-09 11:37:02,195] Trial 75 finished with value: 0.6657681940700808 and parameters: {'n_estimators': 198, 'max_depth': 3, 'learning_rate': 0.20728977619768305, 'subsample': 0.6300752375427767, 'colsample_bytree': 0.7339141621047567, 'min_child_weight': 10, 'gamma': 0.94049941458753, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:02,6,76,XGBoost,0.6667,0.7966,0.7675,0.5892,245,8,0.00249,0.97661,0.81572,7,0.647937,244,5,0.3,0.31,0.6712,47,0.6093,0.7746,0.6845,0.549,0.0574,False,OK

[I 2026-07-09 11:37:02,846] Trial 76 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 245, 'max_depth': 8, 'learning_rate': 0.0024896594775279837, 'subsample': 0.9766095489066682, 'colsample_bytree': 0.815719888200489, 'min_child_weight': 7, 'gamma': 0.6479374258442646, 'patience': 5}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:03,6,77,XGBoost,0.6667,0.7995,0.7707,0.5874,199,2,0.177212,0.796786,0.588074,6,0.085859,35,4,0.29,0.29,0.6712,47,0.627,0.7805,0.6972,0.5696,0.0397,False,OK

[I 2026-07-09 11:37:03,165] Trial 77 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 199, 'max_depth': 2, 'learning_rate': 0.1772117960447786, 'subsample': 0.7967864684159638, 'colsample_bytree': 0.5880742954948708, 'min_child_weight': 6, 'gamma': 0.08585946308719511, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:03,6,78,XGBoost,0.6611,0.8068,0.7611,0.5844,102,4,0.257831,0.823685,0.825226,8,0.783333,18,3,0.29,0.26,0.6712,47,0.6135,0.7767,0.6845,0.5558,0.0477,False,OK

[I 2026-07-09 11:37:03,472] Trial 78 finished with value: 0.661134163208852 and parameters: {'n_estimators': 102, 'max_depth': 4, 'learning_rate': 0.25783114371771004, 'subsample': 0.8236854197633119, 'colsample_bytree': 0.825225888157221, 'min_child_weight': 8, 'gamma': 0.7833328749165273, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:03,6,79,XGBoost,0.662,0.8032,0.7548,0.5896,171,4,0.046033,0.972406,0.577821,4,0.108632,84,3,0.29,0.27,0.6712,47,0.6216,0.7838,0.6896,0.5658,0.0405,False,OK

[I 2026-07-09 11:37:03,826] Trial 79 finished with value: 0.6620111731843575 and parameters: {'n_estimators': 171, 'max_depth': 4, 'learning_rate': 0.04603339429461716, 'subsample': 0.9724059941365889, 'colsample_bytree': 0.5778212396938862, 'min_child_weight': 4, 'gamma': 0.10863201057928237, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:04,6,80,XGBoost,0.6667,0.8022,0.7707,0.5874,428,5,0.160258,0.850624,0.640702,8,0.145063,15,3,0.28,0.29,0.6712,47,0.6316,0.7829,0.7023,0.5738,0.0351,False,OK

[I 2026-07-09 11:37:04,126] Trial 80 finished with value: 0.6666666666666666 and parameters: {'n_estimators': 428, 'max_depth': 5, 'learning_rate': 0.16025831601903925, 'subsample': 0.8506236787875271, 'colsample_bytree': 0.6407019463428429, 'min_child_weight': 8, 'gamma': 0.14506270561317886, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:04,6,81,XGBoost,0.6557,0.7962,0.7611,0.5759,357,11,0.005306,0.900398,0.664248,6,0.258252,356,2,0.28,0.31,0.6712,47,0.6107,0.7688,0.6845,0.5512,0.045,False,OK

[I 2026-07-09 11:37:04,932] Trial 81 finished with value: 0.6556927297668038 and parameters: {'n_estimators': 357, 'max_depth': 11, 'learning_rate': 0.005305994361868116, 'subsample': 0.9003978017670282, 'colsample_bytree': 0.6642476160347118, 'min_child_weight': 6, 'gamma': 0.2582515204038961, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:05,6,82,XGBoost,0.6621,0.8016,0.7675,0.5821,312,6,0.116791,0.900708,0.590513,7,0.475129,27,3,0.27,0.25,0.6712,47,0.6175,0.7745,0.6921,0.5574,0.0446,False,OK

[I 2026-07-09 11:37:05,265] Trial 82 finished with value: 0.6620879120879121 and parameters: {'n_estimators': 312, 'max_depth': 6, 'learning_rate': 0.116790529161701, 'subsample': 0.9007083171623528, 'colsample_bytree': 0.5905125383984268, 'min_child_weight': 7, 'gamma': 0.47512904652359683, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:05,6,83,XGBoost,0.6676,0.7987,0.7675,0.5907,185,7,0.002816,0.95852,0.890835,7,0.976317,184,3,0.31,0.32,0.6712,47,0.6087,0.775,0.6768,0.553,0.0589,False,OK

[I 2026-07-09 11:37:05,750] Trial 83 finished with value: 0.667590027700831 and parameters: {'n_estimators': 185, 'max_depth': 7, 'learning_rate': 0.0028163532152995284, 'subsample': 0.9585202548736408, 'colsample_bytree': 0.8908352886538666, 'min_child_weight': 7, 'gamma': 0.9763166714531862, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:06,6,84,XGBoost,0.6611,0.8003,0.7548,0.5881,255,6,0.015086,0.911465,0.653893,9,0.314752,180,3,0.29,0.25,0.6712,47,0.6186,0.7789,0.6768,0.5696,0.0425,False,OK

[I 2026-07-09 11:37:06,232] Trial 84 finished with value: 0.6610878661087866 and parameters: {'n_estimators': 255, 'max_depth': 6, 'learning_rate': 0.015085754546504052, 'subsample': 0.9114649785958603, 'colsample_bytree': 0.6538928001230033, 'min_child_weight': 9, 'gamma': 0.3147519831452862, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:06,6,85,XGBoost,0.6508,0.7951,0.6975,0.61,57,14,0.002782,0.741589,0.94851,8,0.415206,56,4,0.32,0.31,0.6712,47,0.6131,0.7764,0.631,0.5962,0.0377,False,OK

[I 2026-07-09 11:37:06,599] Trial 85 finished with value: 0.6508172362555721 and parameters: {'n_estimators': 57, 'max_depth': 14, 'learning_rate': 0.0027824176853996495, 'subsample': 0.7415891271695293, 'colsample_bytree': 0.9485101260192187, 'min_child_weight': 8, 'gamma': 0.41520566138076553, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:06,6,86,XGBoost,0.6521,0.7971,0.758,0.5721,50,13,0.276623,0.604566,0.699452,7,0.232382,11,3,0.3,0.25,0.6712,47,0.6109,0.7625,0.687,0.5499,0.0412,False,OK

[I 2026-07-09 11:37:06,980] Trial 86 finished with value: 0.6520547945205479 and parameters: {'n_estimators': 50, 'max_depth': 13, 'learning_rate': 0.27662320163438636, 'subsample': 0.6045657683199609, 'colsample_bytree': 0.699451653265898, 'min_child_weight': 7, 'gamma': 0.2323820783894402, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:07,6,87,XGBoost,0.6685,0.806,0.7803,0.5847,293,3,0.062629,0.982219,0.998208,7,0.408606,64,2,0.26,0.29,0.6712,47,0.6233,0.7809,0.7074,0.5571,0.0452,False,OK

[I 2026-07-09 11:37:07,334] Trial 87 finished with value: 0.6684856753069577 and parameters: {'n_estimators': 293, 'max_depth': 3, 'learning_rate': 0.06262856492197981, 'subsample': 0.9822194001111958, 'colsample_bytree': 0.9982082143491382, 'min_child_weight': 7, 'gamma': 0.4086060253630605, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:07,6,88,XGBoost,0.6566,0.7933,0.7611,0.5773,307,8,0.037029,0.905868,0.604191,2,0.118222,84,3,0.28,0.29,0.6712,47,0.6208,0.7725,0.6997,0.5578,0.0358,False,OK

[I 2026-07-09 11:37:07,725] Trial 88 finished with value: 0.6565934065934066 and parameters: {'n_estimators': 307, 'max_depth': 8, 'learning_rate': 0.03702931255508747, 'subsample': 0.9058675646116523, 'colsample_bytree': 0.6041908231623883, 'min_child_weight': 2, 'gamma': 0.11822190926669554, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:08,6,89,XGBoost,0.6601,0.7984,0.7516,0.5885,374,2,0.087775,0.89158,0.69131,2,0.038644,36,2,0.31,0.31,0.6712,47,0.6233,0.7813,0.6819,0.5739,0.0369,False,OK

[I 2026-07-09 11:37:08,092] Trial 89 finished with value: 0.6601398601398601 and parameters: {'n_estimators': 374, 'max_depth': 2, 'learning_rate': 0.08777532772009813, 'subsample': 0.8915798901892135, 'colsample_bytree': 0.6913098608615239, 'min_child_weight': 2, 'gamma': 0.0386444109910484, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:09,6,90,XGBoost,0.6594,0.8061,0.7707,0.5762,286,3,0.099446,0.909564,0.726075,2,0.001963,42,4,0.26,0.29,0.6712,47,0.6337,0.7851,0.7176,0.5674,0.0257,False,OK

[I 2026-07-09 11:37:09,653] Trial 90 finished with value: 0.659400544959128 and parameters: {'n_estimators': 286, 'max_depth': 3, 'learning_rate': 0.09944565770710251, 'subsample': 0.9095641566242171, 'colsample_bytree': 0.7260751263491245, 'min_child_weight': 2, 'gamma': 0.0019629819788029162, 'patience': 4}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:11,6,91,XGBoost,0.6639,0.8041,0.7707,0.5831,365,4,0.043701,0.857645,0.990122,9,0.244147,64,2,0.27,0.28,0.6712,47,0.628,0.7826,0.7023,0.5679,0.0359,False,OK

[I 2026-07-09 11:37:11,229] Trial 91 finished with value: 0.663923182441701 and parameters: {'n_estimators': 365, 'max_depth': 4, 'learning_rate': 0.043700848706153976, 'subsample': 0.8576454644773522, 'colsample_bytree': 0.9901222894134207, 'min_child_weight': 9, 'gamma': 0.24414671362252985, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:11,6,92,XGBoost,0.6648,0.8057,0.7643,0.5882,254,3,0.009705,0.886651,0.906831,6,0.565953,253,2,0.29,0.27,0.6712,47,0.6276,0.7842,0.6947,0.5723,0.0372,False,OK

[I 2026-07-09 11:37:11,891] Trial 92 finished with value: 0.6648199445983379 and parameters: {'n_estimators': 254, 'max_depth': 3, 'learning_rate': 0.00970510269471514, 'subsample': 0.8866514078076132, 'colsample_bytree': 0.9068305002960836, 'min_child_weight': 6, 'gamma': 0.565953171470958, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:12,6,93,XGBoost,0.6604,0.7939,0.7803,0.5724,393,9,0.277659,0.927272,0.923466,7,0.581323,9,2,0.27,0.28,0.6712,47,0.6144,0.765,0.7074,0.543,0.046,False,OK

[I 2026-07-09 11:37:12,233] Trial 93 finished with value: 0.660377358490566 and parameters: {'n_estimators': 393, 'max_depth': 9, 'learning_rate': 0.27765946419417104, 'subsample': 0.9272722591584013, 'colsample_bytree': 0.9234658258850731, 'min_child_weight': 7, 'gamma': 0.5813233771033673, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:12,6,94,XGBoost,0.6595,0.8035,0.7866,0.5678,323,5,0.143955,0.971694,0.991075,7,0.388997,21,2,0.24,0.24,0.6712,47,0.6295,0.78,0.7328,0.5517,0.03,False,OK

[I 2026-07-09 11:37:12,559] Trial 94 finished with value: 0.6595460614152203 and parameters: {'n_estimators': 323, 'max_depth': 5, 'learning_rate': 0.14395482337943963, 'subsample': 0.971693667424116, 'colsample_bytree': 0.9910747829189906, 'min_child_weight': 7, 'gamma': 0.3889965402767866, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:12,6,95,XGBoost,0.6676,0.8057,0.7834,0.5816,184,4,0.026736,0.957384,0.978551,10,0.284163,125,2,0.25,0.32,0.6712,47,0.6264,0.7845,0.7125,0.5589,0.0412,False,OK

[I 2026-07-09 11:37:12,933] Trial 95 finished with value: 0.6675712347354138 and parameters: {'n_estimators': 184, 'max_depth': 4, 'learning_rate': 0.026736090771891246, 'subsample': 0.9573844100804132, 'colsample_bytree': 0.978551398441508, 'min_child_weight': 10, 'gamma': 0.28416271122996356, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:13,6,96,XGBoost,0.6639,0.8047,0.7707,0.5831,374,4,0.034001,0.929821,0.629356,6,0.373004,92,2,0.27,0.28,0.6712,47,0.625,0.782,0.6997,0.5647,0.0389,False,OK

[I 2026-07-09 11:37:13,335] Trial 96 finished with value: 0.663923182441701 and parameters: {'n_estimators': 374, 'max_depth': 4, 'learning_rate': 0.03400076247693121, 'subsample': 0.9298214483777998, 'colsample_bytree': 0.6293557371043417, 'min_child_weight': 6, 'gamma': 0.37300391995052895, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:13,6,97,XGBoost,0.6703,0.8061,0.7803,0.5875,450,5,0.017285,0.940933,0.9583,5,0.489365,151,2,0.26,0.27,0.6712,47,0.6247,0.7814,0.7074,0.5594,0.0456,False,OK

[I 2026-07-09 11:37:13,750] Trial 97 finished with value: 0.6703146374829001 and parameters: {'n_estimators': 450, 'max_depth': 5, 'learning_rate': 0.017285269067138176, 'subsample': 0.9409328175242632, 'colsample_bytree': 0.9582999888323226, 'min_child_weight': 5, 'gamma': 0.4893649032793501, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:14,6,98,XGBoost,0.6639,0.8051,0.7643,0.5868,467,3,0.008436,0.868579,0.850119,6,0.294915,328,2,0.29,0.27,0.6712,47,0.63,0.7837,0.6997,0.5729,0.0339,False,OK

[I 2026-07-09 11:37:14,259] Trial 98 finished with value: 0.6639004149377593 and parameters: {'n_estimators': 467, 'max_depth': 3, 'learning_rate': 0.00843604506983936, 'subsample': 0.8685793078710318, 'colsample_bytree': 0.8501187924982146, 'min_child_weight': 6, 'gamma': 0.294915131086036, 'patience': 2}. Best is trial 47 with value: 0.6711590296495957.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:37:14,6,99,XGBoost,0.6583,0.7986,0.7516,0.5856,155,2,0.018129,0.93736,0.946264,6,0.852294,154,3,0.32,0.32,0.6712,47,0.6257,0.7809,0.687,0.5745,0.0326,False,OK

[I 2026-07-09 11:37:14,642] Trial 99 finished with value: 0.6582984658298466 and parameters: {'n_estimators': 155, 'max_depth': 2, 'learning_rate': 0.018128948915756803, 'subsample': 0.9373595181841669, 'colsample_bytree': 0.9462636041256121, 'min_child_weight': 6, 'gamma': 0.8522937840444114, 'patience': 3}. Best is trial 47 with value: 0.6711590296495957.

\n============================================================
🎉 XGB NAS COMPLETE
============================================================
Best Trial: 47
Best F1: 0.6712
Best Params: {'n_estimators': 136, 'max_depth': 5, 'learning_rate': 0.25702417209507145, 'subsample': 0.7380397704122255, 'colsample_bytree': 0.8336145544002741, 'min_child_weight': 9, 'gamma': 0.9886264497813226, 'patience': 2}
💾 Saved: nas_rf_results.csv, nas_xgb_results.csv
💾 Saved: nas_rf_trial_log.csv, nas_xgb_trial_log.csv

============================================================
📋 NAS RESULTS COMPARISON
============================================================

Model           Best Val F1  Best Trial
----------------------------------------
RandomForest    0.6620       70
XGBoost         0.6712       47

📊 Best RF Params:
   n_estimators: 69
   max_depth: 7
   min_samples_split: 4
   min_samples_leaf: 5

📊 Best XGB Params:
   n_estimators: 136
   max_depth: 5
   learning_rate: 0.25702417209507145
   subsample: 0.7380397704122255
   colsample_bytree: 0.8336145544002741
   min_child_weight: 9
   gamma: 0.9886264497813226
   patience: 2

📊 RF Trial Log (sorted by val_f1):

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:35:57,6,70,RandomForest,0.6620,0.8002,0.7611,0.5858,69,7,4,5,0.26,0.26,0.6620,70,0.6286,0.7803,0.6997,0.5705,0.0335,False,OK
1,2026-07-09,11:35:35,6,41,RandomForest,0.6620,0.7951,0.7516,0.5915,70,11,7,10,0.31,0.28,0.6620,41,0.6184,0.7743,0.6743,0.5711,0.0436,False,OK
2,2026-07-09,11:35:04,6,12,RandomForest,0.6611,0.7958,0.7516,0.5900,439,17,7,9,0.30,0.30,0.6611,6,0.6209,0.7724,0.6794,0.5717,0.0401,False,OK
3,2026-07-09,11:35:10,6,18,RandomForest,0.6611,0.7958,0.7516,0.5900,427,11,4,10,0.30,0.28,0.6611,6,0.6184,0.7745,0.6743,0.5711,0.0426,False,OK
4,2026-07-09,11:35:23,6,29,RandomForest,0.6611,0.7949,0.7516,0.5900,422,16,5,10,0.30,0.28,0.6611,6,0.6193,0.7704,0.6768,0.5708,0.0417,False,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026-07-09,11:35:49,6,61,RandomForest,0.6432,0.7876,0.7261,0.5772,230,2,17,2,0.43,0.43,0.6620,41,0.6019,0.7686,0.6539,0.5575,0.0413,False,OK
96,2026-07-09,11:35:53,6,66,RandomForest,0.6432,0.7874,0.7261,0.5772,279,2,13,10,0.43,0.43,0.6620,41,0.6019,0.7684,0.6539,0.5575,0.0413,False,OK
97,2026-07-09,11:36:00,6,75,RandomForest,0.6397,0.7857,0.6306,0.6492,51,3,5,3,0.39,0.20,0.6620,70,0.5792,0.7680,0.5445,0.6185,0.0606,False,OK
98,2026-07-09,11:34:53,6,1,RandomForest,0.6386,0.7781,0.7006,0.5867,500,20,2,1,0.32,0.32,0.6537,0,0.6043,0.7558,0.6412,0.5714,0.0343,True,OK
99,2026-07-09,11:35:40,6,47,RandomForest,0.6313,0.7874,0.6815,0.5879,468,2,12,2,0.43,0.35,0.6620,41,0.5771,0.7686,0.5954,0.5598,0.0542,False,OK

📊 XGB Trial Log (sorted by val_f1):

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,11:36:49,6,47,XGBoost,0.6712,0.8054,0.7930,0.5818,136,5,0.257024,0.738040,0.833615,9,0.988626,8,2,0.25,0.28,0.6712,47,0.6256,0.7812,0.7226,0.5515,0.0456,False,OK
1,2026-07-09,11:37:13,6,97,XGBoost,0.6703,0.8061,0.7803,0.5875,450,5,0.017285,0.940933,0.958300,5,0.489365,151,2,0.26,0.27,0.6712,47,0.6247,0.7814,0.7074,0.5594,0.0456,False,OK
2,2026-07-09,11:36:38,6,20,XGBoost,0.6694,0.8054,0.7834,0.5843,149,4,0.113332,0.941360,0.819457,6,0.325454,25,2,0.26,0.26,0.6694,18,0.6290,0.7801,0.7074,0.5662,0.0404,False,OK
3,2026-07-09,11:36:39,6,24,XGBoost,0.6694,0.8075,0.7803,0.5861,102,4,0.060039,0.961119,0.863240,8,0.848727,52,3,0.26,0.31,0.6694,18,0.6258,0.7837,0.7150,0.5564,0.0436,False,OK
4,2026-07-09,11:36:37,6,18,XGBoost,0.6694,0.8021,0.7771,0.5880,295,2,0.111008,0.948012,0.673945,6,0.064221,43,3,0.29,0.29,0.6694,18,0.6279,0.7819,0.6997,0.5694,0.0416,False,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026-07-09,11:36:33,6,8,XGBoost,0.6429,0.7933,0.7739,0.5498,79,20,0.246597,0.904199,0.652307,1,0.684233,8,3,0.29,0.42,0.6657,1,0.6022,0.7673,0.7048,0.5256,0.0407,False,OK
96,2026-07-09,11:36:53,6,59,XGBoost,0.6355,0.7863,0.6720,0.6029,154,15,0.001021,0.613957,0.570838,10,0.476191,153,4,0.33,0.32,0.6712,47,0.5860,0.7716,0.5980,0.5746,0.0495,False,OK
97,2026-07-09,11:36:45,6,34,XGBoost,0.6300,0.7790,0.6752,0.5905,82,2,0.004809,0.913266,0.955340,10,0.991465,81,3,0.33,0.28,0.6694,18,0.5862,0.7633,0.6056,0.5680,0.0438,False,OK
98,2026-07-09,11:36:54,6,60,XGBoost,0.6271,0.7581,0.6051,0.6507,93,2,0.002840,0.959622,0.824055,5,0.939009,92,2,0.33,0.29,0.6712,47,0.5734,0.7338,0.5267,0.6292,0.0537,False,OK
99,2026-07-09,11:36:58,6,64,XGBoost,0.6224,0.7835,0.6561,0.5920,153,2,0.002673,0.568620,0.961121,2,0.857489,152,4,0.33,0.28,0.6712,47,0.5903,0.7672,0.6031,0.5780,0.0321,False,OK

#freeze

In [22]:
%pip freeze > "{project_path}requirement/freez/NASEnhancedPretraindMLModleAdvance-lock.txt"

In [23]:
end = time.time()
elapsed = end - start_time

hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)

print(f"Total Time = {hours}h {minutes}m {seconds}s")

Total Time = 0h 6m 36s