This notebook for finding best parmter on LSTM

This is to find best parm based on LSTM

#**Pre-request**

##Mount google drive

In [1]:
### **Mount** Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##Install pakages

In [2]:
#Install pakages
project_path = "/content/drive/MyDrive/Sem-6/coding/github/fraud_detection/"
!cat "{project_path}requirement/Install/NASEnhancedPretraindMLModleAdvance.txt"
!pip install  -r "{project_path}requirement/Install/NASEnhancedPretraindMLModleAdvance.txt" --no-cache-dir
%cd $project_path

torch
transformers
huggingface_hub
datasets
timm
patool
sktime
reformer_pytorch
optuna
ptflopsRequirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2.11.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (5.12.1)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.20.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (4.0.0)
Requirement already satisfied: timm in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 5)) (1.0.27)
Collecting patool (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 6))
  Downloading patool-4.0.5-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting sktime (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7))
  Downloading sktime-1.0.1-py3-none-any.whl.metadata (28 kB)
Collecting reformer_pytorch (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading reformer_pytorch-1.4.4-py3-none-any.whl.metadata (764 bytes)
Collecting optuna (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting ptflops (from -r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 10))
  Downloading ptflops-0.7.5-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.29.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (12.8.90)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 2)) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (0.28.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (0.70.16)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from timm->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 5)) (0.26.0+cu128)
Requirement already satisfied: joblib<1.6,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.5.3)
Collecting scikit-base<1.1.0,>=1.0.0 (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7))
  Downloading scikit_base-1.0.2-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: scikit-learn<1.8.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.6.1)
Requirement already satisfied: scipy<2.0.0,>=1.2 in /usr/local/lib/python3.12/dist-packages (from sktime->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 7)) (1.16.3)
Collecting axial-positional-embedding>=0.1.0 (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading axial_positional_embedding-0.3.12-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8)) (0.8.2)
Collecting local-attention (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading local_attention-1.11.2-py3-none-any.whl.metadata (929 bytes)
Collecting product-key-memory (from reformer_pytorch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 8))
  Downloading product_key_memory-0.3.0-py3-none-any.whl.metadata (4.9 kB)
Collecting alembic>=1.5.0 (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading alembic-1.18.5-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9))
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9)) (2.0.51)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 9)) (1.1.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 1)) (1.5.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 3)) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->-r /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/requirement/Install/NASEnhancedPretraindMLModleAdvance.txt (line 4)) (2.9.0.post0)

##Import  libs

In [3]:
# =====================================================
# 📦 Standard Library
# =====================================================
import os
import sys
import time
import logging
import hashlib
import shutil
import subprocess
import warnings
from datetime import datetime

# Start timer
start_time = time.time()

# =====================================================
# 🧮 Data & Visualization
# =====================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yaml

# Pandas display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# =====================================================
# ⚙️ Machine Learning - Scikit-learn
# =====================================================
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler
from sklearn.utils import class_weight
from sklearn.covariance import EmpiricalCovariance
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)

# =====================================================
# 🌲 XGBoost
# =====================================================
from xgboost import XGBClassifier
import joblib

# =====================================================
# 🔥 Deep Learning - PyTorch
# =====================================================
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
from torch.cuda.amp import autocast

# =====================================================
# 🤖 Deep Learning - TensorFlow / Keras
# =====================================================
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Dense, Masking, Dropout, Layer
from tensorflow.keras.optimizers import Adam

# =====================================================
# 🤗 Transformers & Time Series
# =====================================================
from transformers import AutoModel
from sktime.datasets import load_from_tsfile_to_dataframe
# from mamba_ssm import Mamba  # Uncomment if needed

# =====================================================
# 🧠 Explainability
# =====================================================
import shap

# =====================================================
# 📊 Google Colab Specific
# =====================================================
from google.colab import data_table
data_table.enable_dataframe_formatter()
try:
    from google.colab import data_table
    data_table.enable_dataframe_formatter()
    data_table.DataTable.max_columns = 50
    data_table.DataTable.max_rows = 150
except ImportError:
    pass
from tqdm import tqdm

print("✅ All imports loaded successfully!")

✅ All imports loaded successfully!

##Confirmation setup

In [4]:
# =====================================================
# 🎲 Random Seeds (Reproducibility)
# =====================================================
!nvidia-smi                # confirm GPU
!pip show torch  # confirm versions
torch.manual_seed(42)
np.random.seed(42)

Thu Jul  9 14:05:37 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:00:05.0 Off |                    0 |
| N/A   36C    P0             53W /  400W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Name: torch
Version: 2.11.0+cu128
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org
Author:
Author-email: PyTorch Team <packages@pytorch.org>
License: BSD-3-Clause
Location: /usr/local/lib/python3.12/dist-packages
Requires: cuda-bindings, cuda-toolkit, filelock, fsspec, jinja2, networkx, nvidia-cudnn-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvshmem-cu12, setuptools, sympy, triton, typing-extensions
Required-by: accelerate, axial_positional_embedding, CoLT5-attention, fastai, hyper-connections, local-attention, peft, product_key_memory, ptflops, reformer-pytorch, sentence-transformers, timm, torch-einops-utils, torchdata, torchvision

## Enable Config

In [5]:

logger = logging.getLogger(__name__)

def load_config(config_path="configs/baseline.yaml"):
    """Load YAML config file and expand ${root_path} placeholders."""
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    logger.info(f"✅ Loaded config from {config_path}")

    # --- Expand ${root_path} placeholders ---
    root = config.get("root_path", "")

    def expand_paths(obj):
        if isinstance(obj, dict):
            return {k: expand_paths(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [expand_paths(i) for i in obj]
        elif isinstance(obj, str) and "${root_path}" in obj:
            return obj.replace("${root_path}", root)
        else:
            return obj

    config = expand_paths(config)
    return config
config = load_config(os.path.join(project_path, "configs", "baseline.yaml"))

## Set Variables

In [6]:


#limit = config['ML']['limit']

# ==========================================================
# UNIFIED HYPERPARAMETERS (Match TimesNet NAS Best)
# ==========================================================
# ==========================================================
# 🔧 UNIFIED HYPERPARAMETERS (Match TimesNet NAS Best)
# ==========================================================

# ----------------------------------------------------------
# 📏 Sequence Settings
# ----------------------------------------------------------
max_seq_len = 16                  # Maximum sequence length
recent_mode = False               # False → oldest mode, True → recent-window mode
nas_epochs = 20
n_trials_rf_xgb = 100




# ----------------------------------------------------------
# 📊 Evaluation Settings
# ----------------------------------------------------------
threshold = 0.5                   # Default classification threshold
opt_metric = "f1"                 # Optimization metric for model selection
early_stop_metric = 'val_accuracy'# Metric for early stopping
correlation_threshold = 0.85      # Feature correlation threshold


# ----------------------------------------------------------
# 💾 Paths
# ----------------------------------------------------------
model_path = config['ML']['models']

# ----------------------------------------------------------
# 🔄 Training State (Reset before each model)
# ----------------------------------------------------------
best_threshold = 0.5              # Best threshold (general)

# ==========================================================
# ✅ Configuration Summary
# ==========================================================
print("="*60)
print("📋 CONFIGURATION SUMMARY")
print("="*60)
print(f"  Sequence length:  {max_seq_len}")
print(f"  Mode:             {'Recent' if recent_mode else 'Oldest'}")
print(f"  Threshold:        {threshold}")
print(f"  Model path:       {model_path}")
print("="*60)

# Global unified results table for all models
results_table = pd.DataFrame(columns=["Round", "AUC", "Recall", "F1", "Model"])
summary = pd.DataFrame(
    columns=[
        "Model",
        "AUC",
        "Recall",
        "Precision",
        "F1",
        "threshold"
    ]
)

============================================================
📋 CONFIGURATION SUMMARY
============================================================
  Sequence length:  16
  Mode:             Oldest
  Threshold:        0.5
  Model path:       /content/drive/MyDrive/Sem-6/coding/github/fraud_detection/models/
============================================================

##Split users level

In [7]:

# user_path = config['ML']['Events']['base_path'] + config['ML']['Events']['files']['user']
# df_user = pd.read_csv(user_path)
# print(f"✅ Loaded transactional user dataset: {df_user.shape}")



# # Aggregate to one row per user (max label = 1 if any fraud)
# user_labels = df_user.groupby("phone_no_m")["label"].max()
# print(f"👥 Unique users for splitting: {len(user_labels)}")

# # ==============================================================
# # 2️⃣ Create user-level split (stratified, no leakage)
# # ==============================================================

# fraud_users = user_labels[user_labels == 1].index
# normal_users = user_labels[user_labels == 0].index

# fraud_train, fraud_test = train_test_split(fraud_users, test_size=0.2, random_state=42)
# normal_train, normal_test = train_test_split(normal_users, test_size=0.2, random_state=42)

# train_users = set(fraud_train) | set(normal_train)
# test_users  = set(fraud_test)  | set(normal_test)

# # ==============================================================
# # 3️⃣ Save unified split (shared across LSTM / RF / XGB)
# # ==============================================================

# split_dir = "splits/shared_user_split_v1"
# os.makedirs(split_dir, exist_ok=True)

# pd.DataFrame({"phone_no_m": sorted(train_users)}).to_csv(f"{split_dir}/train_users.csv", index=False)
# pd.DataFrame({"phone_no_m": sorted(test_users)}).to_csv(f"{split_dir}/test_users.csv", index=False)

# # ==============================================================
# # 4️⃣ Summary
# # ==============================================================

# print("\n👥 Users Summary:")
# print(f"   Total : {len(user_labels):,}")
# print(f"   Fraud : {len(fraud_users):,} ({len(fraud_users)/len(user_labels)*100:.2f}%)")
# print(f"   Normal: {len(normal_users):,} ({len(normal_users)/len(user_labels)*100:.2f}%)")

# print("\n📂 Split saved to /splits/:")
# print(f"   Train users: {len(train_users)}")
# print(f"   Test  users: {len(test_users)}")
# print(f"   Fraud ratio train: {len(fraud_train)/len(train_users)*100:.2f}%")
# print(f"   Fraud ratio test : {len(fraud_test)/len(test_users)*100:.2f}%")

## Helpers

### evaluate_global

In [8]:
def evaluate_global(model, X_test, y_test, model_name="Model", threshold=0.5):
    """
    Generic evaluator for both classic ML models and neural networks.
    """
    print(f"\n📊 Evaluation threshold is: {threshold}")

    # ---- Predict probabilities ----
    if hasattr(model, "predict_proba"):
        # For sklearn-style models
        y_pred_prob = model.predict_proba(X_test)[:, 1]
    else:
        # For neural nets (e.g., Keras)
        preds = model.predict(X_test)
        if preds.shape[-1] == 2:
            # 2-class softmax output
            y_pred_prob = preds[:, 1]
        else:
            # Single sigmoid output
            y_pred_prob = preds.ravel()

    # ... rest of function unchanged
    # ---- Predict classes ----
    y_pred = (y_pred_prob > threshold).astype(int)

    # ---- Metrics ----
    auc = roc_auc_score(y_test, y_pred_prob)
    #recall = recall_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred, zero_division=0)

    precision = precision_score(y_test, y_pred, zero_division=0)
    #f1 = f1_score(y_test, y_pred)
    f1     = f1_score(y_test, y_pred, zero_division=0)

    report = classification_report(y_test, y_pred, digits=4)
    cm = confusion_matrix(y_test, y_pred)

    # ---- Display ----
    print(f"\n📊 Classification Report — {model_name}")
    print(report)
    print(f"AUC: {auc:.4f} | Recall: {recall:.4f} | Precision: {precision:.4f} | F1: {f1:.4f}")

    # ---- Confusion Matrix ----
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Normal (0)", "Fraud (1)"])
    disp.plot(cmap="Blues")
    plt.title(f"Confusion Matrix — {model_name}")
    plt.grid(False)
    plt.show()

    # ---- Summary Dictionary ----
    return {
        "Model": model_name,
        "AUC": auc,
        "Recall": recall,
        "Precision": precision,
        "F1": f1,
        "threshold": threshold
    }

### append_to_summary

In [9]:

def append_to_summary(summary, model_name, results):
    """
    Appends or updates the summary table with model results.
    Works with both capitalized and lowercase keys automatically.
    """
    # ✅ Create summary DataFrame if missing
    if summary is None or not isinstance(summary, pd.DataFrame):
          summary = pd.DataFrame(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])
    # Ensure "Model" column exists (prevents KeyError)
    if "Model" not in summary.columns:
        summary = pd.DataFrame(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])

    # ✅ Normalize key names to lowercase
    results = {k.lower(): v for k, v in results.items()}

    # ✅ Remove any existing row for the same model
    summary = summary[summary["Model"] != model_name]

    # ✅ Add new row (robust to missing values)
    row = {
        "Model": model_name,
        "AUC": round(results.get("auc", np.nan), 4) if not pd.isna(results.get("auc", np.nan)) else np.nan,
        "Recall": round(results.get("recall", np.nan), 4) if not pd.isna(results.get("recall", np.nan)) else np.nan,
        "Precision": round(results.get("precision", np.nan), 4) if not pd.isna(results.get("precision", np.nan)) else np.nan,
        "F1": round(results.get("f1", np.nan), 4) if not pd.isna(results.get("f1", np.nan)) else np.nan,
        "Threshold": round(results.get("threshold", np.nan), 4) if not pd.isna(results.get("threshold", np.nan)) else np.nan
    }


    # ✅ Append and reindex
    summary = pd.concat([summary, pd.DataFrame([row])], ignore_index=True)
    summary = summary.reindex(columns=["Model", "AUC", "Recall", "Precision", "F1", "Threshold"])
    return summary

### find_best_threshold

In [10]:
def find_best_threshold(y_true, probs, low=0.2, high=0.8, n=61):
    best_f1 = -1.0
    best_thr = 0.5
    for thr in np.linspace(low, high, n):
        preds = (probs >= thr).astype(int)
        f1 = f1_score(y_true, preds, zero_division=0)
        if f1 > best_f1:
            best_f1 = f1
            best_thr = thr
    return best_thr, best_f1


def get_timesnet_val_threshold(results_dir):
    val_prob_path = os.path.join(results_dir, "val_prob.npy")
    val_true_path = os.path.join(results_dir, "val_true.npy")

    if not os.path.exists(val_prob_path) or not os.path.exists(val_true_path):
        raise FileNotFoundError(
            f"Missing validation probability files in {results_dir}. "
            f"Expected val_prob.npy and val_true.npy"
        )

    val_probs = np.load(val_prob_path)
    val_true = np.load(val_true_path)

    best_thr, best_f1 = find_best_threshold(val_true, val_probs)
    return best_thr, best_f1

###Drop and select features

In [11]:
def prepare_features(df):
    """
    Selects only the explicitly defined features for model training.
    You control which features are used by editing 'selected_features' below.
    """

    # --- Define selected features manually ---
    selected_features = [
        "window_size", "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
       "voc_avg_duration", "voc_max_duration", "voc_std_duration", "voc_active_days",
       "voc_active_hours", "sms_total_msgs", "sms_unique_contacts", "sms_active_hours",
       "sms_calltype_ratio", "app_months_active", "app_total_flow", "app_avg_flow",
       "app_std_flow", "app_unique_apps_mean", "app_unique_apps_max", "user_months_active",
        "arpu_mean", "arpu_std", "arpu_max", "idcard_cnt", "snapshot_round"
   ]
  #  selected_features = [
   #     "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
    #   "voc_avg_duration", "voc_max_duration", "voc_std_duration", "voc_active_days",
     # "voc_active_hours", "sms_total_msgs", "sms_unique_contacts", "sms_active_hours",
     #"sms_calltype_ratio", "idcard_cnt"
    #]
   # selected_features = [
    #    "voc_active_days",
    #"voc_active_hours",
    #"voc_unique_contacts",
    #"sms_calltype_ratio",
    #"sms_active_hours" ]


    # ✅ You can manually remove or comment out features here
    # For example:
    # selected_features = [f for f in selected_features if not (f.startswith("app_") or f.startswith("arpu_"))]

    # --- Keep only existing columns ---
    available = [f for f in selected_features if f in df.columns]
    missing = [f for f in selected_features if f not in df.columns]

    X = df[available].copy()

    #print(f"\n📊 Final features used ({len(available)}): {available}")
    if missing:
        print(f"⚠️ Missing columns not found in data: {missing}")

    return X

### Compare

In [12]:

def plot_progressive_results(
    results_table,
    metrics=("AUC", "Recall", "F1"),
    round_col=None,
    figsize=(14, 6)
):
    """
    Plot progressive evaluation metrics per round for multiple models.

    Parameters
    ----------
    results_table : pd.DataFrame
        Must contain columns: Model, metrics, and either Round or input_size
    metrics : tuple
        Metrics to plot (default: AUC, Recall, F1)
    round_col : str or None
        Column name for x-axis. If None, auto-detects.
    figsize : tuple
        Figure size for plots
    """

    # --------------------------------------------------
    # Auto-detect round column
    # --------------------------------------------------
    if round_col is None:
        if "Round" in results_table.columns:
            round_col = "Round"
        elif "input_size" in results_table.columns:
            round_col = "input_size"
        else:
            raise ValueError("No Round or input_size column found.")

    # --------------------------------------------------
    # Sort results (important for correct curves)
    # --------------------------------------------------
    results_table = results_table.sort_values(
        by=[round_col, "Model"],
        ascending=True
    ).reset_index(drop=True)


    # --------------------------------------------------
    # Plot each metric
    # --------------------------------------------------
    for metric in metrics:

        plt.figure(figsize=figsize)

        for model in results_table["Model"].unique():
            subset = (
                results_table[results_table["Model"] == model]
                .sort_values(by=round_col)
            )

            plt.plot(
                subset[round_col],
                subset[metric],
                marker="o",
                markersize=6,
                linewidth=2,
                label=model,
                alpha=0.85
            )

        plt.title(f"{metric} per {round_col}", fontsize=18)
        plt.xlabel(round_col, fontsize=14)
        plt.ylabel(metric, fontsize=14)
        plt.grid(True, linestyle="--", alpha=0.4)

        # Legend outside
        plt.legend(
            loc="upper center",
            bbox_to_anchor=(0.5, -0.12),
            ncol=4,
            fontsize=10
        )

        plt.tight_layout(rect=[0, 0.1, 1, 1])
        plt.show()
    display(results_table)

    return results_table

###get_key_rounds

In [13]:
# ============================================================
# 🔬 SCIENTIFIC KEY ROUNDS SELECTION
# ============================================================

def get_key_rounds(max_seq_len, method="linear", n_points=5):
    """
    Generate scientifically meaningful evaluation checkpoints.

    Args:
        max_seq_len: Maximum sequence length (16, 100, 300, etc.)
        method: Selection strategy
            - "linear": Equal spacing (1, 25%, 50%, 75%, 100%)
            - "logarithmic": More points early (where changes happen fast)
            - "sqrt": Square root spacing (balanced)
            - "percentile": Fixed percentages
        n_points: Number of evaluation points (default 5)

    Returns:
        List of round numbers to evaluate
    """

    if max_seq_len <= n_points:
        # If sequence is short, evaluate all rounds
        return list(range(1, max_seq_len + 1))

    if method == "linear":
        # Equal spacing: 1, 25%, 50%, 75%, 100%
        rounds = np.linspace(1, max_seq_len, n_points)

    elif method == "logarithmic":
        # More points early (fraud detection often shows early signal)
        # Log scale: 1, 2, 4, 8, 16 style
        rounds = np.logspace(0, np.log10(max_seq_len), n_points)

    elif method == "sqrt":
        # Square root spacing (balanced between linear and log)
        rounds = np.square(np.linspace(1, np.sqrt(max_seq_len), n_points))

    elif method == "percentile":
        # Fixed percentages: 1st event, 10%, 25%, 50%, 75%, 100%
        percentages = [0, 0.1, 0.25, 0.5, 0.75, 1.0]
        rounds = [max(1, int(p * max_seq_len)) for p in percentages]
        return sorted(set(rounds))  # Remove duplicates

    elif method == "early_focus":
        # Focus on early detection (more points in first half)
        # Useful for fraud detection where early signal matters
        early = np.linspace(1, max_seq_len * 0.5, n_points - 2)
        late = [max_seq_len * 0.75, max_seq_len]
        rounds = np.concatenate([early, late])

    else:
        raise ValueError(f"Unknown method: {method}")

    # Convert to integers, ensure valid range, remove duplicates
    rounds = [int(round(r)) for r in rounds]
    rounds = [max(1, min(r, max_seq_len)) for r in rounds]
    rounds = sorted(set(rounds))

    # Always include 1 and max_seq_len
    if 1 not in rounds:
        rounds = [1] + rounds
    if max_seq_len not in rounds:
        rounds = rounds + [max_seq_len]

    return rounds

##key_rounds = get_key_rounds(max_seq_len, method=method, n_points=n_points)
##print(f"📊 Evaluating rounds: {key_rounds}")
#print(f"   Total: {len(key_rounds)} rounds instead of {max_seq_len}")

#ML Modules

### Feature Importance

In [14]:
# def plot_feature_importance(model, X_train, model_name="Model", top_n=20):
#     """
#     Plot feature importance for tree-based models (XGBoost, RandomForest).
#     """


#     # Handle model type
#     if hasattr(model, "get_booster"):  # XGBoost
#         importance = model.get_booster().get_score(importance_type='gain')
#         fi = pd.DataFrame({
#             'Feature': list(importance.keys()),
#             'Importance': list(importance.values())
#         })
#     elif hasattr(model, "feature_importances_"):  # RandomForest
#         fi = pd.DataFrame({
#             'Feature': X_train.columns,
#             'Importance': model.feature_importances_
#         })
#     else:
#         raise ValueError(f"{model_name} does not support feature importance extraction.")

#     # Sort and plot
#     fi = fi.sort_values(by='Importance', ascending=False)
#     display(fi.head(10))

#     plt.figure(figsize=(10,6))
#     plt.barh(fi['Feature'][:top_n][::-1], fi['Importance'][:top_n][::-1])
#     plt.title(f'📊 {model_name} Feature Importance (Top {top_n})')
#     plt.xlabel('Importance')
#     plt.ylabel('Feature')
#     plt.grid(alpha=0.4)
#     plt.tight_layout()
#     plt.show()

#     return fi

# fi_xgb = plot_feature_importance(xgb_model, snap_X_train, "XGBoost")
# fi_rf = plot_feature_importance(rf_model, snap_X_train, "Random Forest")

### Load

In [15]:
def load_raw_datasets(config):


    if "ML" in config and "Events" in config["ML"]:
        events_cfg = config["ML"]["Events"]
    else:
        events_cfg = config["Events"]

    base = events_cfg["base_path"]
    files = events_cfg["files"]

    # --- Load all datasets ---
    df_voc = pd.read_csv(os.path.join(base, files["voc"]))
    df_sms = pd.read_csv(os.path.join(base, files["sms"]))
    df_app = pd.read_csv(os.path.join(base, files["app"]))
    df_user = pd.read_csv(os.path.join(base, files["user"]))

    # --- Normalize timestamps and add source column ---
    for df, src in [(df_voc, "VOC"), (df_sms, "SMS"), (df_app, "APP"), (df_user, "USER")]:
        df["source"] = src
        ts_col = [c for c in df.columns if "time" in c.lower()][0]
        df.rename(columns={ts_col: "event_time"}, inplace=True)
        df["event_time"] = pd.to_datetime(df["event_time"], errors="coerce")

    print("✅ Raw datasets loaded and timestamp-normalized.")
    return df_voc, df_sms, df_app, df_user

df_voc, df_sms, df_app, df_user = load_raw_datasets(config)

✅ Raw datasets loaded and timestamp-normalized.

### Build timeline (events)

In [16]:
def merge_and_prepare_events(df_voc, df_sms, df_app, df_user):

    # --- 1️⃣ Normalize USER dataset ---
    if 'label' not in df_user.columns:
        raise KeyError("❌ 'label' column not found in user dataset")

    # Ensure numeric consistency
    df_user['label'] = df_user['label'].fillna(0).astype(int)
    df_user['idcard_cnt'] = df_user['idcard_cnt'].fillna(0).astype(float)
    df_user['arpu_value'] = df_user['arpu_value'].fillna(0).astype(float)

    # --- 2️⃣ Extract static info for merging (label + sim count only) ---
    #static_user_info = df_user.groupby("phone_no_m", as_index=False)[["label", "idcard_cnt"]].max()
    # --- 2️⃣ Extract static info from the RAW user table (covers all 6,106 users) ---
    lbl_cfg = config["ML"]["labels"]
    raw_user = pd.read_csv(os.path.join(lbl_cfg["base_path"], lbl_cfg["file"]))
    static_user_info = raw_user[["phone_no_m", "label", "idcard_cnt"]].drop_duplicates("phone_no_m")
    static_user_info["label"] = static_user_info["label"].astype(int)
    static_user_info["idcard_cnt"] = static_user_info["idcard_cnt"].fillna(0).astype(float)

    # --- 3️⃣ Merge static info into other event tables ---
    df_voc = df_voc.merge(static_user_info, on="phone_no_m", how="left")
    df_sms = df_sms.merge(static_user_info, on="phone_no_m", how="left")
    df_app = df_app.merge(static_user_info, on="phone_no_m", how="left")


    # --- 4️⃣ Combine all transactional event sources ---
    # include df_user itself since arpu_value is event-like
    events = pd.concat([df_voc, df_sms, df_app, df_user], ignore_index=True)

    # --- 5️⃣ Fill and order ---
    #events["label"] = events["label"].fillna(0).astype(int)
    missing = int(events["label"].isna().sum())
    assert missing == 0, f"{missing} events have no label — label merge is broken"
    events["label"] = events["label"].astype(int)

    events["event_time"] = pd.to_datetime(events["event_time"], errors="coerce")
    events = events.sort_values(["phone_no_m", "event_time"]).reset_index(drop=True)

    # --- 6️⃣ Summary ---
    print("\n🔎 Feature Summary per Source:")
    for src, df in [("VOC", df_voc), ("SMS", df_sms), ("APP", df_app), ("USER", df_user)]:
        print(f"\n📂 Source: {src}")
        print(f"   Events: {len(df):,}")
        print(f"   Users : {df['phone_no_m'].nunique():,}")
        print(f"   Columns ({len(df.columns)}): {', '.join(df.columns)}")

    print("\n📊 Combined Dataset Summary:")
    print(f"   Total events: {len(events):,}")
    print(f"   Unique users: {events['phone_no_m'].nunique():,}")
    print(f"   Fraud ratio: {events['label'].mean()*100:.2f}%")
    user_labels = events.groupby("phone_no_m")["label"].max()
    print(f"   Fraud users: {int(user_labels.sum()):,} / {user_labels.size:,} ({user_labels.mean()*100:.2f}%)")

    return events

events = merge_and_prepare_events(df_voc, df_sms, df_app, df_user)

display(events.head())

🔎 Feature Summary per Source:

📂 Source: VOC
   Events: 5,015,430
   Users : 6,025
   Columns (11): phone_no_m, opposite_no_m, calltype_id, event_time, call_dur, city_name, county_name, imei_m, source, label, idcard_cnt

📂 Source: SMS
   Events: 6,848,509
   Users : 6,103
   Columns (7): phone_no_m, opposite_no_m, calltype_id, event_time, source, label, idcard_cnt

📂 Source: APP
   Events: 3,283,602
   Users : 6,106
   Columns (10): phone_no_m, event_time, source, busi_name, flow, month_id, flow_norm, month_str, label, idcard_cnt

📂 Source: USER
   Events: 39,454
   Users : 5,929
   Columns (10): phone_no_m, event_time, source, month_id, arpu_value, city_name, county_name, idcard_cnt, label, month_col

📊 Combined Dataset Summary:
   Total events: 15,186,995
   Unique users: 6,106
   Fraud ratio: 24.63%
   Fraud users: 1,962 / 6,106 (32.13%)

,phone_no_m,opposite_no_m,calltype_id,event_time,call_dur,city_name,county_name,imei_m,source,label,idcard_cnt,busi_name,flow,month_id,flow_norm,month_str,arpu_value,month_col
0,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-12 08:09:11,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-13 16:21:53,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,df22edbc0e3dd6bc4f2f453e687b743e8442a54834b64f...,2.0,2019-08-13 16:21:53,NaN,NaN,NaN,NaN,SMS,0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Split data based on users (fraud, not fraud)

In [17]:


# ======================================
# Clean Numeric Columns
# ======================================
events = events.copy()
numeric_cols = events.select_dtypes(include=["number"]).columns.difference(["label"])

# Replace NaN with 0 for numeric fields (avoids scaling issues)
events[numeric_cols] = events[numeric_cols].fillna(0)

print(f"\n📊 Numeric columns to scale ({len(numeric_cols)}): {numeric_cols.tolist()}")


# ======================================
# 2 Create / Load Shared Train-Val-Test User Split
# ======================================
split_dir = os.path.join(config["root_path"], "splits", "shared_user_split_v1")
train_split_file = f"{split_dir}/train_users.csv"
test_split_file  = f"{split_dir}/test_users.csv"
val_split_file   = f"{split_dir}/val_users.csv"

os.makedirs(split_dir, exist_ok=True)

all_split_files_exist = (
    os.path.exists(train_split_file)
    and os.path.exists(test_split_file)
    and os.path.exists(val_split_file)
)

if all_split_files_exist:
    print("📂 Using shared user split files...")
    train_users = set(pd.read_csv(train_split_file)["phone_no_m"])
    test_users  = set(pd.read_csv(test_split_file)["phone_no_m"])
    val_users   = set(pd.read_csv(val_split_file)["phone_no_m"])
else:
    print("🆕 Creating shared train/test/val user split...")

    # One label per user
    user_labels = events.groupby("phone_no_m")["label"].max()
    fraud_users = user_labels[user_labels == 1].index
    normal_users = user_labels[user_labels == 0].index

    # 1) Train/Test split (split fraud user %)
    fraud_train, fraud_test = train_test_split(
        fraud_users, test_size=0.2, random_state=42
    )
    normal_train, normal_test = train_test_split(
        normal_users, test_size=0.2, random_state=42
    )

    train_users_full = set(fraud_train) | set(normal_train)
    test_users = set(fraud_test) | set(normal_test)

    # 2) Validation split from training users only
    train_user_labels = user_labels.loc[list(train_users_full)]

    fraud_train_users = train_user_labels[train_user_labels == 1].index
    normal_train_users = train_user_labels[train_user_labels == 0].index

    fraud_tr, fraud_val = train_test_split(
        fraud_train_users, test_size=0.2, random_state=42
    )
    normal_tr, normal_val = train_test_split(
        normal_train_users, test_size=0.2, random_state=42
    )

    train_users = set(fraud_tr) | set(normal_tr)
    val_users   = set(fraud_val) | set(normal_val)

    pd.DataFrame({"phone_no_m": sorted(train_users)}).to_csv(train_split_file, index=False)
    pd.DataFrame({"phone_no_m": sorted(test_users)}).to_csv(test_split_file, index=False)
    pd.DataFrame({"phone_no_m": sorted(val_users)}).to_csv(val_split_file, index=False)

    print(f"✅ Saved shared split files to '{split_dir}/'")
# ======================================
# Split overlap checks
# ======================================
assert len(train_users & test_users) == 0, "❌ User leakage: train and test overlap"
assert len(train_users & val_users) == 0, "❌ User leakage: train and val overlap"
assert len(test_users & val_users) == 0, "❌ User leakage: test and val overlap"

print("🔒 Split overlap checks passed:")
print(f"   train ∩ test = {len(train_users & test_users)}")
print(f"   train ∩ val  = {len(train_users & val_users)}")
print(f"   test  ∩ val  = {len(test_users & val_users)}")
user_labels = events.groupby("phone_no_m")["label"].max()
print(f"   sizes  train/val/test = {len(train_users)} / {len(val_users)} / {len(test_users)}")
print(f"   fraud  train/val/test = {int(user_labels.loc[list(train_users)].sum())} / "
      f"{int(user_labels.loc[list(val_users)].sum())} / {int(user_labels.loc[list(test_users)].sum())}")
# ======================================
# Apply Split to Events
# ======================================
train_events = events[events["phone_no_m"].isin(train_users)]
test_events  = events[events["phone_no_m"].isin(test_users)]
val_events = events[events["phone_no_m"].isin(val_users)]

# Sanity checks
assert len(set(train_events["phone_no_m"]) & set(test_events["phone_no_m"])) == 0, "❌ User leakage detected!"
assert train_events["label"].nunique() == 2, "❌ Training set must contain both classes"
assert test_events["label"].nunique() == 2, "❌ Test set must contain both classes"

# --- add time gap, scaled featur ---
# for name, df in [('train_events', train_events), ('test_events', test_events)]:
#     df = df.copy()  # avoid SettingWithCopyWarning
#     df['event_time'] = pd.to_datetime(df['event_time'])
#     #df.sort_values(['phone_no_m', 'event_time'], inplace=True)
#     df = df.sort_values(['phone_no_m', 'event_time'], kind='mergesort').reset_index(drop=True)
#     df['dt_hours'] = df.groupby('phone_no_m')['event_time'].diff().dt.total_seconds() / 3600
#     df['dt_hours'] = df['dt_hours'].fillna(0)
#     df['dt_hours'] = np.log1p(df['dt_hours'])  # normalize gaps
#     if name == 'train_events':
#         train_events = df
#     else:
#         test_events = df
for name, df in [
    ('train_events', train_events),
    ('val_events', val_events),
    ('test_events', test_events)
]:
    df = df.copy()
    df['event_time'] = pd.to_datetime(df['event_time'])
    df = df.sort_values(['phone_no_m', 'event_time'], kind='mergesort').reset_index(drop=True)
    df['dt_hours'] = df.groupby('phone_no_m')['event_time'].diff().dt.total_seconds() / 3600
    df['dt_hours'] = df['dt_hours'].fillna(0)
    df['dt_hours'] = np.log1p(df['dt_hours'])

    if name == 'train_events':
        train_events = df
    elif name == 'val_events':
        val_events = df
    else:
        test_events = df


# Store unscaled events BEFORE line 895
train_events_unscaled = train_events.copy()
test_events_unscaled = test_events.copy()
val_events_unscaled = val_events.copy()


# Sanity checks
assert len(set(train_events["phone_no_m"]) & set(test_events["phone_no_m"])) == 0, "❌ User leakage detected!"
assert train_events["label"].nunique() == 2, "❌ Training set must contain both classes"
assert test_events["label"].nunique() == 2, "❌ Test set must contain both classes"
scale_cols_seq = sorted(set(train_events.select_dtypes(include=["number"]).columns) - {"label"})
scaler_seq = StandardScaler().fit(train_events[scale_cols_seq])
train_events[scale_cols_seq] = scaler_seq.transform(train_events[scale_cols_seq])
test_events[scale_cols_seq]  = scaler_seq.transform(test_events[scale_cols_seq])
val_events[scale_cols_seq]   = scaler_seq.transform(val_events[scale_cols_seq])

# ======================================
# 4️⃣ snapshot
# ======================================

# ======================================
# 4️⃣ Create Sequences (using multiple features)
# ======================================
numeric_features = [c for c in numeric_cols if c not in ["label"]]  # exclude label
if 'dt_hours' in train_events.columns:
    numeric_features.append('dt_hours')
print(f"\n📦 Features used for sequences: {numeric_features}")
feature_cols_tf = numeric_features.copy()
# 👉 Transformer feature columns: same numeric features as LSTM + source_id

if "source_id" not in feature_cols_tf:
    feature_cols_tf.append("source_id")

print("[Transformer] feature_cols_tf:", feature_cols_tf)

📊 Numeric columns to scale (6): ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt']
📂 Using shared user split files...
🔒 Split overlap checks passed:
   train ∩ test = 0
   train ∩ val  = 0
   test  ∩ val  = 0
   sizes  train/val/test = 3907 / 977 / 1222
   fraud  train/val/test = 1255 / 314 / 393

📦 Features used for sequences: ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt', 'dt_hours']
[Transformer] feature_cols_tf: ['arpu_value', 'call_dur', 'calltype_id', 'flow', 'flow_norm', 'idcard_cnt', 'dt_hours', 'source_id']

### Generate_snapshots_from_events

In [18]:
# ============================================================
# 🔧 OPTIMIZED SNAPSHOT GENERATION FROM EVENTS (FIXED)
# ============================================================

def generate_snapshots_from_events(
    events_df,
    users,
    r,
    max_seq_len,
    recent_mode=True
):
    """
    Generate snapshot features from events DataFrame.
    OPTIMIZED: Uses groupby instead of per-user filtering.
    """

    # 1️⃣ Filter to relevant users FIRST (huge speedup)
    events_filtered = events_df[events_df["phone_no_m"].isin(users)].copy()

    if events_filtered.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    # 2️⃣ Sort once
    events_filtered = events_filtered.sort_values(["phone_no_m", "event_time"])

    # 3️⃣ Apply selection logic per user using groupby
    def select_events(df_u):
        if recent_mode:
            df_u = df_u.tail(max_seq_len).head(r)
        else:
            df_u = df_u.head(r)
        return df_u

    selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)

    if selected.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    # 4️⃣ Aggregate features using groupby
    snapshot_rows = []

    for user, df_u in tqdm(selected.groupby("phone_no_m"), desc="Generating snapshots"):
    #for user, df_u in selected.groupby("phone_no_m"):
        row = {"phone_no_m": user}

        # Get label
        label = int(df_u["label"].max()) if "label" in df_u.columns else 0

        # --- Voice Features ---
        voc = df_u[df_u["source"] == "VOC"]
        if len(voc) > 0:
            if "call_dur" in voc.columns:
                call_dur = pd.to_numeric(voc["call_dur"], errors="coerce").fillna(0)
            else:
                call_dur = pd.Series([0])

            row["voc_total_calls"] = len(voc)
            row["voc_unique_contacts"] = voc["opposite_no_m"].nunique() if "opposite_no_m" in voc.columns else 0
            row["voc_total_duration"] = call_dur.sum()
            row["voc_avg_duration"] = call_dur.mean()
            row["voc_max_duration"] = call_dur.max()
            row["voc_std_duration"] = call_dur.std() if len(call_dur) > 1 else 0
            row["voc_active_days"] = voc["event_time"].dt.weekday.nunique()
            row["voc_active_hours"] = voc["event_time"].dt.hour.nunique()
        else:
            row.update({
                "voc_total_calls": 0, "voc_unique_contacts": 0, "voc_total_duration": 0,
                "voc_avg_duration": 0, "voc_max_duration": 0, "voc_std_duration": 0,
                "voc_active_days": 0, "voc_active_hours": 0
            })

        # --- SMS Features ---
        sms = df_u[df_u["source"] == "SMS"]
        if len(sms) > 0:
            row["sms_total_msgs"] = len(sms)
            row["sms_unique_contacts"] = sms["opposite_no_m"].nunique() if "opposite_no_m" in sms.columns else 0
            row["sms_active_hours"] = sms["event_time"].dt.hour.nunique()
            if "calltype_id" in sms.columns:
                calltype = pd.to_numeric(sms["calltype_id"], errors="coerce")
                row["sms_calltype_ratio"] = (calltype == 1).mean()
            else:
                row["sms_calltype_ratio"] = 0
        else:
            row.update({
                "sms_total_msgs": 0, "sms_unique_contacts": 0,
                "sms_active_hours": 0, "sms_calltype_ratio": 0
            })

        # --- App Features ---
        app = df_u[df_u["source"] == "APP"]
        if len(app) > 0:
            if "flow" in app.columns:
                flow = pd.to_numeric(app["flow"], errors="coerce").fillna(0)
            else:
                flow = pd.Series([0])

            row["app_months_active"] = app["month_id"].nunique() if "month_id" in app.columns else 0
            row["app_total_flow"] = flow.sum()
            row["app_avg_flow"] = flow.mean()
            row["app_std_flow"] = flow.std() if len(flow) > 1 else 0
            row["app_unique_apps_mean"] = app["busi_name"].nunique() if "busi_name" in app.columns else 0
            row["app_unique_apps_max"] = app["busi_name"].nunique() if "busi_name" in app.columns else 0
        else:
            row.update({
                "app_months_active": 0, "app_total_flow": 0, "app_avg_flow": 0,
                "app_std_flow": 0, "app_unique_apps_mean": 0, "app_unique_apps_max": 0
            })

        # --- User/ARPU Features ---
        arpu = df_u[df_u["source"] == "USER"]
        if len(arpu) > 0:
            if "arpu_value" in arpu.columns:
                arpu_val = pd.to_numeric(arpu["arpu_value"], errors="coerce")
            else:
                arpu_val = pd.Series([0])

            row["user_months_active"] = arpu["month_id"].nunique() if "month_id" in arpu.columns else 0
            row["arpu_mean"] = arpu_val.mean()
            row["arpu_std"] = arpu_val.std() if len(arpu_val) > 1 else 0
            row["arpu_max"] = arpu_val.max()
            row["idcard_cnt"] = arpu["idcard_cnt"].max() if "idcard_cnt" in arpu.columns else 0
        else:
            row.update({
                "user_months_active": 0, "arpu_mean": 0, "arpu_std": 0,
                "arpu_max": 0, "idcard_cnt": 0
            })

        # Meta features
        row["window_size"] = r
        row["snapshot_round"] = r
        row["label"] = label

        snapshot_rows.append(row)

    # Build DataFrame
    df_snapshot = pd.DataFrame(snapshot_rows).fillna(0)

    if df_snapshot.empty:
        return pd.DataFrame(), np.array([]), np.array([])

    y = df_snapshot["label"].values
    user_ids = df_snapshot["phone_no_m"].values
    X = df_snapshot.drop(columns=["phone_no_m", "label"])

    return X, y, user_ids

#  ▶ Classic Ml Snapshot based

###### Genrate input data

In [19]:

# ============================================================
# 📋 Define snapshot feature columns (same as sequencestreaming.py)
# ============================================================

SNAPSHOT_FEATURE_COLS = [
    # Voice
    "voc_total_calls", "voc_unique_contacts", "voc_total_duration",
    "voc_avg_duration", "voc_max_duration", "voc_std_duration",
    "voc_active_days", "voc_active_hours",
    # SMS
    "sms_total_msgs", "sms_unique_contacts", "sms_active_hours", "sms_calltype_ratio",
    # App
    "app_months_active", "app_total_flow", "app_avg_flow",
    "app_std_flow", "app_unique_apps_mean", "app_unique_apps_max",
    # User / ARPU
    "user_months_active", "arpu_mean", "arpu_std", "arpu_max", "idcard_cnt",
    # Meta
    "window_size", "snapshot_round"
]

print(f"📊 Snapshot features: {len(SNAPSHOT_FEATURE_COLS)} columns")

# ============================================================
# 🚀 RF/XGBoost - UNIFIED PIPELINE (Uses same events as LSTM)
# ============================================================


print("\n" + "="*60)
print(f"[{datetime.now()}] 🌲 RF/XGBoost Training (from events, same as LSTM)")
print("="*60)

# ============================================================
# 1️⃣ Generate training snapshots (r = max_seq_len)
# ============================================================
print(f"\n[{datetime.now()}] 📊 Generating training snapshots (r={max_seq_len})...")

X_train_snap, y_train_snap, users_train_snap = generate_snapshots_from_events(
    events_df=train_events_unscaled,
    users=train_users,
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)
neg = (y_train_snap == 0).sum()
pos = (y_train_snap == 1).sum()
XGB_scale_pos_weight = neg / pos

print(f"[{datetime.now()}] ✅ Training snapshots: {len(X_train_snap)} users, {X_train_snap.shape[1]} features")

# ============================================================
# 2️⃣ Align columns and scale
# ============================================================
print(f"[{datetime.now()}] 🔄 Scaling...")
X_train_snap = X_train_snap.reindex(columns=SNAPSHOT_FEATURE_COLS, fill_value=0)
scaler_snap = StandardScaler().fit(X_train_snap)
X_train_scaled = scaler_snap.transform(X_train_snap)
print(f"[{datetime.now()}] ✅ Scaling done")

📊 Snapshot features: 25 columns

============================================================
[2026-07-09 14:08:44.897214] 🌲 RF/XGBoost Training (from events, same as LSTM)
============================================================

[2026-07-09 14:08:44.897299] 📊 Generating training snapshots (r=16)...

/tmp/ipykernel_925/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 3907/3907 [00:12<00:00, 314.99it/s]

[2026-07-09 14:09:13.158864] ✅ Training snapshots: 3907 users, 25 features
[2026-07-09 14:09:13.159026] 🔄 Scaling...
[2026-07-09 14:09:13.164096] ✅ Scaling done

#### Show sample

In [20]:
# ============================================================
# 🔍 DEBUG: Print Sample Snapshots
# ============================================================

print("="*60)
print("🔍 SAMPLE SNAPSHOTS DEBUG")
print("="*60)

# Generate a small sample
X_sample, y_sample, users_sample = generate_snapshots_from_events(
    events_df=train_events_unscaled,
    users=list(train_users)[:10],  # Only 10 users for sample
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)

print(f"\n📊 Sample shape: {X_sample.shape}")
print(f"📊 Labels: {y_sample}")
print(f"📊 Users: {users_sample}")

# Show features
print(f"\n📋 Feature columns ({len(X_sample.columns)}):")
print(X_sample.columns.tolist())

# Show sample data
print(f"\n📊 Sample snapshots (first 5 users):")
sample_df = X_sample.copy()
sample_df['label'] = y_sample
sample_df['user'] = users_sample
sample_df = sample_df[['user', 'label'] + [c for c in sample_df.columns if c not in ['user', 'label']]]
display(sample_df.head())

# Show statistics
print(f"\n📈 Feature statistics:")
display(X_sample.describe().T)

# Show class distribution
print(f"\n📊 Class distribution:")
print(f"   Fraud (1): {sum(y_sample == 1)} ({sum(y_sample == 1)/len(y_sample)*100:.1f}%)")
print(f"   Normal (0): {sum(y_sample == 0)} ({sum(y_sample == 0)/len(y_sample)*100:.1f}%)")

============================================================
🔍 SAMPLE SNAPSHOTS DEBUG
============================================================

/tmp/ipykernel_925/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 10/10 [00:00<00:00, 314.47it/s]

📊 Sample shape: (10, 25)
📊 Labels: [0 0 1 1 0 0 0 0 0 1]
📊 Users: ['0dea8b38517e1debb9b04c863e311a82a143b86f5e19b433afd6e02112d3c0305f0ffa3917e77354f54ae64023bfb06ed9aaba0e458a8be142f93f13362b9088'
 '340d09a17101f7c6482861a04680204a6ff69c3edb7c7a51a3014425efea209aca32cc6416a4d9e3e2ece83475954ec68811b535d6d392e380670e237fb16ccb'
 '39ec2007423378cdd9ca31d0568daa13d6bb85a1f43c59508b91fae0599473e124de960f528d130a76d836975bea6d852c9afab519617eb336619ee8c0ab349b'
 '3f42b3a532b2ce7fa4ff8802adab7b37e08f414720329934446314a979373ae8762663a921df46285acd3bc44fe245a7d9ac289aeb6b6ed40f579d7876ff70ee'
 '42f4d0e01820190cd757c13aa6bcc67144f0bfdeecd61adeb7de2c07144f24bed259ecd045dedacdfea4fddfa0434acf8b7bda0a22f975e8216025a1395c89f4'
 '66d544958955ae884e82523646702cd6fa5cf66a94d2cd08f3154ec19fa41f1a88ccdc0000306e8dd97f2c20889f37ff2f12b9664dba472730fab0b4dd2f966e'
 '9e1b59525baeb052df87d34c5ee0cc7e6be7c717f072a71b74c71e6f1a2960a88a46f73fa0ce81447c9bfd6d58665cd4c929562b2c5ec7e80c51e3e75c129509'
 'ae066e8be0418a3a942e8c3251a67b4dc03f75145c211a18afe658510f8ef9911b6377f9f5ffc4fdf1e1ccf841b86a2280504c577f976e10173882c3c74864d1'
 'ed714134650a9eddbcd2a9c6701c8ceaa73ca13847f25e628c9784ac27ea4b5a8cbbd4271099e790e99503c00d080411689780bdb09b26b8ff0ea0845ce51ed8'
 'f637bbf262785e1bd3f009e33446a52cc7d155434caeae91220cd586a4982296f0852d879a46547829386c53c826f6be1c6f74bf3fe1b2e28e5408de61d1e211']

📋 Feature columns (25):
['voc_total_calls', 'voc_unique_contacts', 'voc_total_duration', 'voc_avg_duration', 'voc_max_duration', 'voc_std_duration', 'voc_active_days', 'voc_active_hours', 'sms_total_msgs', 'sms_unique_contacts', 'sms_active_hours', 'sms_calltype_ratio', 'app_months_active', 'app_total_flow', 'app_avg_flow', 'app_std_flow', 'app_unique_apps_mean', 'app_unique_apps_max', 'user_months_active', 'arpu_mean', 'arpu_std', 'arpu_max', 'idcard_cnt', 'window_size', 'snapshot_round']

📊 Sample snapshots (first 5 users):

,user,label,voc_total_calls,voc_unique_contacts,voc_total_duration,voc_avg_duration,voc_max_duration,voc_std_duration,voc_active_days,voc_active_hours,sms_total_msgs,sms_unique_contacts,sms_active_hours,sms_calltype_ratio,app_months_active,app_total_flow,app_avg_flow,app_std_flow,app_unique_apps_mean,app_unique_apps_max,user_months_active,arpu_mean,arpu_std,arpu_max,idcard_cnt,window_size,snapshot_round
0,0dea8b38517e1debb9b04c863e311a82a143b86f5e19b4...,0,5,3,421.0,84.200000,191.0,65.350593,1,3,11,3,4,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,16,16
1,340d09a17101f7c6482861a04680204a6ff69c3edb7c7a...,0,0,0,0.0,0.000000,0.0,0.000000,0,0,16,1,1,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,16,16
2,39ec2007423378cdd9ca31d0568daa13d6bb85a1f43c59...,1,0,0,0.0,0.000000,0.0,0.000000,0,0,16,1,2,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,16,16
3,3f42b3a532b2ce7fa4ff8802adab7b37e08f4147203299...,1,0,0,0.0,0.000000,0.0,0.000000,0,0,16,1,1,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,16,16
4,42f4d0e01820190cd757c13aa6bcc67144f0bfdeecd61a...,0,13,11,1670.0,128.461538,480.0,128.218313,2,6,3,2,2,0.0,0,0.0,0.0,0.0,0,0,0,0,0,0,0,16,16

📈 Feature statistics:

,count,mean,std,min,25%,50%,75%,max
voc_total_calls,10.0,2.100000,4.121758,0.0,0.00,0.5,1.000000,13.000000
voc_unique_contacts,10.0,1.700000,3.400980,0.0,0.00,0.5,1.000000,11.000000
voc_total_duration,10.0,269.400000,514.059703,0.0,0.00,48.5,261.000000,1670.000000
voc_avg_duration,10.0,81.566154,102.740575,0.0,0.00,42.1,120.596154,269.000000
voc_max_duration,10.0,127.400000,164.151827,0.0,0.00,48.5,225.500000,480.000000
voc_std_duration,10.0,19.356891,43.414979,0.0,0.00,0.0,0.000000,128.218313
voc_active_days,10.0,0.600000,0.699206,0.0,0.00,0.5,1.000000,2.000000
voc_active_hours,10.0,1.200000,1.932184,0.0,0.00,0.5,1.000000,6.000000
sms_total_msgs,10.0,13.500000,4.089281,3.0,12.75,15.0,16.000000,16.000000
sms_unique_contacts,10.0,3.100000,2.282786,1.0,1.25,2.5,3.750000,7.000000
sms_active_hours,10.0,3.600000,2.366432,1.0,2.00,3.0,5.000000,8.000000
sms_calltype_ratio,10.0,0.020000,0.063246,0.0,0.00,0.0,0.000000,0.200000
app_months_active,10.0,0.100000,0.316228,0.0,0.00,0.0,0.000000,1.000000
app_total_flow,10.0,0.003160,0.009991,0.0,0.00,0.0,0.000000,0.031595
app_avg_flow,10.0,0.000790,0.002498,0.0,0.00,0.0,0.000000,0.007899
app_std_flow,10.0,0.000292,0.000925,0.0,0.00,0.0,0.000000,0.002924
app_unique_apps_mean,10.0,0.400000,1.264911,0.0,0.00,0.0,0.000000,4.000000
app_unique_apps_max,10.0,0.400000,1.264911,0.0,0.00,0.0,0.000000,4.000000
user_months_active,10.0,0.000000,0.000000,0.0,0.00,0.0,0.000000,0.000000
arpu_mean,10.0,0.000000,0.000000,0.0,0.00,0.0,0.000000,0.000000
arpu_std,10.0,0.000000,0.000000,0.0,0.00,0.0,0.000000,0.000000
arpu_max,10.0,0.000000,0.000000,0.0,0.00,0.0,0.000000,0.000000
idcard_cnt,10.0,0.000000,0.000000,0.0,0.00,0.0,0.000000,0.000000
window_size,10.0,16.000000,0.000000,16.0,16.00,16.0,16.000000,16.000000
snapshot_round,10.0,16.000000,0.000000,16.0,16.00,16.0,16.000000,16.000000

📊 Class distribution:
   Fraud (1): 3 (30.0%)
   Normal (0): 7 (70.0%)

### RF and XGB NAS

In [21]:
# ============================================================
# 🔧 PREPARE DATA FOR RF/XGB NAS
# ============================================================
import optuna
from optuna.samplers import TPESampler
# Number of trials (same as TimesNet/LSTM NAS)
# ============================================================
# 📊 Trial Logging (matches NAS TimesNet structure)
# ============================================================
rf_trial_log = []
best_rf_f1_so_far = -1.0
best_rf_trial_so_far = -1
ENQUEUED_RF_IDS = {0, 1, 2, 3}

xgb_trial_log = []
best_xgb_f1_so_far = -1.0
best_xgb_trial_so_far = -1
ENQUEUED_XGB_IDS = {0, 1, 2, 3}
print(f"\\n[{datetime.now()}] 📊 Generating test snapshots...")

X_test_snap, y_test_snap, users_test_snap = generate_snapshots_from_events(
    events_df=test_events_unscaled,
    users=test_users,
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)

X_test_snap = X_test_snap.reindex(columns=SNAPSHOT_FEATURE_COLS, fill_value=0)
X_test_scaled = scaler_snap.transform(X_test_snap)

print(f"[{datetime.now()}] ✅ Test snapshots: {len(X_test_snap)} users")

# Generate validation snapshots
print(f"\\n[{datetime.now()}] 📊 Generating validation snapshots...")

X_val_snap, y_val_snap, users_val_snap = generate_snapshots_from_events(
    events_df=val_events_unscaled,
    users=val_users,
    r=max_seq_len,
    max_seq_len=max_seq_len,
    recent_mode=recent_mode
)

X_val_snap = X_val_snap.reindex(columns=SNAPSHOT_FEATURE_COLS, fill_value=0)
X_val_scaled = scaler_snap.transform(X_val_snap)

print(f"[{datetime.now()}] ✅ Validation snapshots: {len(X_val_snap)} users")

neg = (y_train_snap == 0).sum()
pos = (y_train_snap == 1).sum()
XGB_scale_pos_weight = neg / pos
print(f"   Class ratio → Normal: {neg}, Fraud: {pos}, scale_pos_weight: {XGB_scale_pos_weight:.2f}")

# Already computed above for XGB, reuse the same neg/pos
RF_class_weight = {
    0: 1.0,           # normal users — keep as 1
    1: neg / pos      # fraud users — same ratio as XGB
}
print(f"   RF class_weight: {RF_class_weight}")


# ============================================================
# 🌲 RANDOM FOREST NAS
# ============================================================

def rf_objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 500),
        "max_depth": trial.suggest_int("max_depth", 2, 20),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
    }

    model = RandomForestClassifier(**params, random_state=42, n_jobs=-1)
    model.fit(X_train_scaled, y_train_snap)

    val_probs  = model.predict_proba(X_val_scaled)[:, 1]
    test_probs = model.predict_proba(X_test_scaled)[:, 1]

    # --- Validation threshold + metrics ---
    best_val_thr, best_val_f1 = find_best_threshold(y_val_snap, val_probs)
    val_preds = (val_probs >= best_val_thr).astype(int)
    val_auc = roc_auc_score(y_val_snap, val_probs)
    val_recall = recall_score(y_val_snap, val_preds, zero_division=0)
    val_precision = precision_score(y_val_snap, val_preds, zero_division=0)

    # --- Test metrics using VALIDATION threshold ---
    test_preds = (test_probs >= best_val_thr).astype(int)
    test_f1 = f1_score(y_test_snap, test_preds, zero_division=0)
    test_auc = roc_auc_score(y_test_snap, test_probs)
    test_recall = recall_score(y_test_snap, test_preds, zero_division=0)
    test_precision = precision_score(y_test_snap, test_preds, zero_division=0)

    # --- Oracle test threshold (monitoring only) ---
    best_test_thr, best_test_f1_oracle = find_best_threshold(y_test_snap, test_probs)

    # --- Log trial ---
    global best_rf_f1_so_far, best_rf_trial_so_far
    if best_val_f1 > best_rf_f1_so_far:
        best_rf_f1_so_far = best_val_f1
        best_rf_trial_so_far = trial.number

    trial_row = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "time": datetime.now().strftime("%H:%M:%S"),
        "seq_length": max_seq_len,
        "trial_id": trial.number,
        "model": "RandomForest",

        # Validation
        "val_f1": round(best_val_f1, 4),
        "val_auc": round(val_auc, 4),
        "val_recall": round(val_recall, 4),
        "val_precision": round(val_precision, 4),

        # Parameters
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "min_samples_split": params["min_samples_split"],
        "min_samples_leaf": params["min_samples_leaf"],

        # Thresholds
        "val_threshold": round(best_val_thr, 3),
        "best_test_threshold": round(best_test_thr, 3),

        # Best tracking
        "best_val_so_far": round(best_rf_f1_so_far, 4),
        "best_trial_id": best_rf_trial_so_far,

        # Test (monitoring only)
        "test_f1": round(test_f1, 4),
        "test_auc": round(test_auc, 4),
        "test_recall": round(test_recall, 4),
        "test_precision": round(test_precision, 4),

        # Diagnostics
        "gap_val_test": round(best_val_f1 - test_f1, 4),
        "is_enqueued": trial.number in ENQUEUED_RF_IDS,
        "status": "OK",
    }
    rf_trial_log.append(trial_row)

    display(pd.DataFrame([trial_row]))

    return best_val_f1

    # Evaluate on TEST set (same as TimesNet NAS)
    #probs = model.predict_proba(X_test_scaled)[:, 1]

    # # Same threshold search as TimesNet/LSTM NAS
    # best_f1 = -1.0
    # for thr in np.linspace(0.2, 0.8, 61):
    #     pred = (probs >= thr).astype(int)
    #     f1 = f1_score(y_test_snap, pred, zero_division=0)
    #     if f1 > best_f1:
    #         best_f1 = f1

    # return best_f1


# ============================================================
# 🚀 XGBOOST NAS
# ============================================================

def xgb_objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 500),
        "max_depth": trial.suggest_int("max_depth", 2, 20),
        "learning_rate": trial.suggest_float("learning_rate", 0.001, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "gamma": trial.suggest_float("gamma", 0.0, 1.0),
        "patience": trial.suggest_int("patience", 2, 5),
    }

    patience = params.pop("patience")
    model = XGBClassifier(**params,early_stopping_rounds=patience, random_state=42, n_jobs=-1, eval_metric='logloss')

    model.fit(X_train_scaled, y_train_snap,eval_set=[(X_val_scaled, y_val_snap)], verbose=False)
    actual_trees = model.best_iteration if hasattr(model, "best_iteration") else params["n_estimators"]

    val_probs  = model.predict_proba(X_val_scaled)[:, 1]
    test_probs = model.predict_proba(X_test_scaled)[:, 1]

    # --- Validation threshold + metrics ---
    best_val_thr, best_val_f1 = find_best_threshold(y_val_snap, val_probs)
    val_preds = (val_probs >= best_val_thr).astype(int)
    val_auc = roc_auc_score(y_val_snap, val_probs)
    val_recall = recall_score(y_val_snap, val_preds, zero_division=0)
    val_precision = precision_score(y_val_snap, val_preds, zero_division=0)

    # --- Test metrics using VALIDATION threshold ---
    test_preds = (test_probs >= best_val_thr).astype(int)
    test_f1 = f1_score(y_test_snap, test_preds, zero_division=0)
    test_auc = roc_auc_score(y_test_snap, test_probs)
    test_recall = recall_score(y_test_snap, test_preds, zero_division=0)
    test_precision = precision_score(y_test_snap, test_preds, zero_division=0)

    # --- Oracle test threshold (monitoring only) ---
    best_test_thr, best_test_f1_oracle = find_best_threshold(y_test_snap, test_probs)

    # --- Log trial ---
    global best_xgb_f1_so_far, best_xgb_trial_so_far
    if best_val_f1 > best_xgb_f1_so_far:
        best_xgb_f1_so_far = best_val_f1
        best_xgb_trial_so_far = trial.number

    trial_row = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "time": datetime.now().strftime("%H:%M:%S"),
        "seq_length": max_seq_len,
        "trial_id": trial.number,
        "model": "XGBoost",

        # Validation
        "val_f1": round(best_val_f1, 4),
        "val_auc": round(val_auc, 4),
        "val_recall": round(val_recall, 4),
        "val_precision": round(val_precision, 4),

        # Parameters
        "n_estimators": params["n_estimators"],
        "max_depth": params["max_depth"],
        "learning_rate": params["learning_rate"],
        "subsample": params["subsample"],
        "colsample_bytree": params["colsample_bytree"],
        "min_child_weight": params["min_child_weight"],
        "gamma": params["gamma"],

        "actual_trees": actual_trees,
        "patience": patience,

        # Thresholds
        "val_threshold": round(best_val_thr, 3),
        "best_test_threshold": round(best_test_thr, 3),

        # Best tracking
        "best_val_so_far": round(best_xgb_f1_so_far, 4),
        "best_trial_id": best_xgb_trial_so_far,

        # Test (monitoring only)
        "test_f1": round(test_f1, 4),
        "test_auc": round(test_auc, 4),
        "test_recall": round(test_recall, 4),
        "test_precision": round(test_precision, 4),

        # Diagnostics
        "gap_val_test": round(best_val_f1 - test_f1, 4),
        "is_enqueued": trial.number in ENQUEUED_XGB_IDS,
        "status": "OK",
    }
    xgb_trial_log.append(trial_row)

    display(pd.DataFrame([trial_row]))

    return best_val_f1


# ============================================================
# 🔬 RUN NAS - RANDOM FOREST
# ============================================================

print("\\n" + "="*60)
print("🌲 RANDOM FOREST NAS")
print("="*60)

sampler_rf = TPESampler(
    n_startup_trials=10,
    n_ei_candidates=24,
    multivariate=True,
    seed=42
)

study_rf = optuna.create_study(
    direction="maximize",
    sampler=sampler_rf
    #pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=3)
)

study_rf.enqueue_trial({"n_estimators": 100, "max_depth": 10, "min_samples_split": 2, "min_samples_leaf": 1})
study_rf.enqueue_trial({"n_estimators": 500, "max_depth": 20, "min_samples_split": 2, "min_samples_leaf": 1})
study_rf.enqueue_trial({"n_estimators": 200, "max_depth":  5, "min_samples_split":10, "min_samples_leaf": 5})
study_rf.enqueue_trial({"n_estimators": 300, "max_depth": 12, "min_samples_split": 5, "min_samples_leaf": 2})


print(f"[{datetime.now()}] 🚀 Starting RF NAS ({n_trials_rf_xgb} trials)...")
study_rf.optimize(rf_objective, n_trials=n_trials_rf_xgb)

print("\\n" + "="*60)
print("🎉 RF NAS COMPLETE")
print("="*60)
print(f"Best Trial: {study_rf.best_trial.number}")
print(f"Best F1: {study_rf.best_value:.4f}")
print(f"Best Params: {study_rf.best_params}")


# ============================================================
# 🔬 RUN NAS - XGBOOST
# ============================================================

print("\\n" + "="*60)
print("🚀 XGBOOST NAS")
print("="*60)

sampler_xgb = TPESampler(
    n_startup_trials=10,
    n_ei_candidates=24,
    multivariate=True,
    seed=42
)

study_xgb = optuna.create_study(
    direction="maximize",
    sampler=sampler_xgb
   # pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=3)
)

study_xgb.enqueue_trial({"n_estimators": 100, "max_depth": 6, "learning_rate": 0.1,  "subsample": 1.0, "colsample_bytree": 1.0, "min_child_weight": 1, "gamma": 0.0, "patience": 3 })
study_xgb.enqueue_trial({"n_estimators": 500, "max_depth": 4, "learning_rate": 0.01, "subsample": 0.8, "colsample_bytree": 0.8, "min_child_weight": 3, "gamma": 0.1, "patience": 3 })
study_xgb.enqueue_trial({"n_estimators":  50, "max_depth": 8, "learning_rate": 0.3,  "subsample": 0.7, "colsample_bytree": 0.7, "min_child_weight": 1, "gamma": 0.0, "patience": 3 })
study_xgb.enqueue_trial({"n_estimators": 300, "max_depth": 3, "learning_rate": 0.05, "subsample": 0.6, "colsample_bytree": 0.6, "min_child_weight": 5, "gamma": 0.5, "patience": 3 })



print(f"[{datetime.now()}] 🚀 Starting XGB NAS ({n_trials_rf_xgb} trials)...")
study_xgb.optimize(xgb_objective, n_trials=n_trials_rf_xgb)

print("\\n" + "="*60)
print("🎉 XGB NAS COMPLETE")
print("="*60)
print(f"Best Trial: {study_xgb.best_trial.number}")
print(f"Best F1: {study_xgb.best_value:.4f}")
print(f"Best Params: {study_xgb.best_params}")


# ============================================================
# 📊 SAVE RESULTS
# ============================================================

# Save Optuna study results
OUT_DIR = os.path.join(config["output"]["results_dir"], "NAS_v2/")
os.makedirs(OUT_DIR, exist_ok=True)
study_rf.trials_dataframe().to_csv(f"{OUT_DIR}nas_rf_results_WL{max_seq_len}.csv", index=False)
study_xgb.trials_dataframe().to_csv(f"{OUT_DIR}nas_xgb_results_WL{max_seq_len}.csv", index=False)
pd.DataFrame(rf_trial_log).to_csv(f"{OUT_DIR}nas_rf_trial_log_WL{max_seq_len}.csv", index=False)
pd.DataFrame(xgb_trial_log).to_csv(f"{OUT_DIR}nas_xgb_trial_log_WL{max_seq_len}.csv", index=False)

print("💾 Saved: nas_rf_results.csv, nas_xgb_results.csv")
print("💾 Saved: nas_rf_trial_log.csv, nas_xgb_trial_log.csv")

# ============================================================
# 📋 COMPARISON SUMMARY
# ============================================================

print("\n" + "="*60)
print("📋 NAS RESULTS COMPARISON")
print("="*60)

print(f"\n{'Model':<15} {'Best Val F1':<12} {'Best Trial':<12}")
print("-" * 40)
print(f"{'RandomForest':<15} {study_rf.best_value:<12.4f} {study_rf.best_trial.number:<12}")
print(f"{'XGBoost':<15} {study_xgb.best_value:<12.4f} {study_xgb.best_trial.number:<12}")

print("\n📊 Best RF Params:")
for k, v in study_rf.best_params.items():
    print(f"   {k}: {v}")

print("\n📊 Best XGB Params:")
for k, v in study_xgb.best_params.items():
    print(f"   {k}: {v}")

# Display full trial logs
print("\n📊 RF Trial Log (sorted by val_f1):")
display(
    pd.DataFrame(rf_trial_log)
    .sort_values("val_f1", ascending=False)
    .reset_index(drop=True)
)

print("\n📊 XGB Trial Log (sorted by val_f1):")
display(
    pd.DataFrame(xgb_trial_log)
    .sort_values("val_f1", ascending=False)
    .reset_index(drop=True)
)

\n[2026-07-09 14:09:14.312699] 📊 Generating test snapshots...

/tmp/ipykernel_925/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 1222/1222 [00:03<00:00, 316.58it/s]

[2026-07-09 14:09:23.359601] ✅ Test snapshots: 1222 users
\n[2026-07-09 14:09:23.359733] 📊 Generating validation snapshots...

/tmp/ipykernel_925/10258993.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  selected = events_filtered.groupby("phone_no_m", group_keys=False).apply(select_events)
Generating snapshots: 100%|██████████| 977/977 [00:03<00:00, 286.50it/s]
/tmp/ipykernel_925/2777212690.py:269: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  sampler_rf = TPESampler(
[I 2026-07-09 14:09:30,063] A new study created in memory with name: no-name-8e3c31b3-b42a-4f6e-a98e-8449cd131624

[2026-07-09 14:09:30.060896] ✅ Validation snapshots: 977 users
   Class ratio → Normal: 2652, Fraud: 1255, scale_pos_weight: 2.11
   RF class_weight: {0: 1.0, 1: np.float64(2.113147410358566)}
\n============================================================
🌲 RANDOM FOREST NAS
============================================================
[2026-07-09 14:09:30.064943] 🚀 Starting RF NAS (100 trials)...

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:30,16,0,RandomForest,0.7034,0.8488,0.7325,0.6765,100,10,2,1,0.39,0.26,0.7034,0,0.6623,0.822,0.6438,0.6819,0.0411,True,OK

[I 2026-07-09 14:09:30,600] Trial 0 finished with value: 0.7033639143730887 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.7033639143730887.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:32,16,1,RandomForest,0.6861,0.8334,0.8248,0.5873,500,20,2,1,0.26,0.29,0.7034,0,0.6571,0.7975,0.7583,0.5798,0.029,True,OK

[I 2026-07-09 14:09:32,187] Trial 1 finished with value: 0.686092715231788 and parameters: {'n_estimators': 500, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.7033639143730887.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:32,16,2,RandomForest,0.6887,0.8383,0.7293,0.6524,200,5,10,5,0.37,0.33,0.7034,0,0.6624,0.8163,0.659,0.6658,0.0263,True,OK

[I 2026-07-09 14:09:32,948] Trial 2 finished with value: 0.6887218045112782 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.7033639143730887.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:33,16,3,RandomForest,0.7019,0.8466,0.7197,0.6848,300,12,5,2,0.44,0.34,0.7034,0,0.6533,0.8196,0.6209,0.6893,0.0486,True,OK

[I 2026-07-09 14:09:33,990] Trial 3 finished with value: 0.7018633540372671 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.7033639143730887.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:34,16,4,RandomForest,0.7024,0.8466,0.6879,0.7176,218,20,15,6,0.53,0.26,0.7034,0,0.6378,0.821,0.5802,0.7081,0.0647,False,OK

[I 2026-07-09 14:09:34,836] Trial 4 finished with value: 0.7024390243902439 and parameters: {'n_estimators': 218, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.7033639143730887.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:35,16,5,RandomForest,0.6829,0.8331,0.7166,0.6522,120,4,3,9,0.38,0.37,0.7034,0,0.6521,0.8101,0.6438,0.6606,0.0308,False,OK

[I 2026-07-09 14:09:35,390] Trial 5 finished with value: 0.6828528072837633 and parameters: {'n_estimators': 120, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 0 with value: 0.7033639143730887.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:36,16,6,RandomForest,0.7093,0.8453,0.742,0.6793,321,15,2,10,0.4,0.3,0.7093,6,0.6727,0.8209,0.6641,0.6815,0.0366,False,OK

[I 2026-07-09 14:09:36,486] Trial 6 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 321, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:37,16,7,RandomForest,0.7021,0.842,0.7357,0.6715,425,6,5,2,0.38,0.29,0.7093,6,0.6554,0.8206,0.6387,0.6729,0.0468,False,OK

[I 2026-07-09 14:09:37,831] Trial 7 finished with value: 0.7021276595744681 and parameters: {'n_estimators': 425, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:38,16,8,RandomForest,0.7005,0.8462,0.7261,0.6766,187,11,10,3,0.41,0.23,0.7093,6,0.6623,0.8219,0.6438,0.6819,0.0382,False,OK

[I 2026-07-09 14:09:38,571] Trial 8 finished with value: 0.7004608294930875 and parameters: {'n_estimators': 187, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:39,16,9,RandomForest,0.6819,0.8356,0.7134,0.6531,325,4,7,4,0.38,0.36,0.7093,6,0.6485,0.8116,0.6361,0.6614,0.0334,False,OK

[I 2026-07-09 14:09:39,633] Trial 9 finished with value: 0.6818873668188736 and parameters: {'n_estimators': 325, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:40,16,10,RandomForest,0.7038,0.8463,0.7452,0.6667,313,13,2,8,0.38,0.28,0.7093,6,0.6675,0.8216,0.6641,0.671,0.0362,False,OK

[I 2026-07-09 14:09:40,707] Trial 10 finished with value: 0.7037593984962406 and parameters: {'n_estimators': 313, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:41,16,11,RandomForest,0.7039,0.8475,0.742,0.6695,354,15,4,9,0.38,0.27,0.7093,6,0.6701,0.8213,0.6667,0.6735,0.0339,False,OK

[I 2026-07-09 14:09:41,878] Trial 11 finished with value: 0.7039274924471299 and parameters: {'n_estimators': 354, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:43,16,12,RandomForest,0.7059,0.8471,0.7452,0.6705,439,17,7,9,0.38,0.31,0.7093,6,0.6718,0.8214,0.6692,0.6744,0.0341,False,OK

[I 2026-07-09 14:09:43,263] Trial 12 finished with value: 0.7058823529411765 and parameters: {'n_estimators': 439, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:44,16,13,RandomForest,0.7025,0.8455,0.7484,0.662,427,18,12,8,0.37,0.28,0.7093,6,0.6751,0.8208,0.6794,0.6709,0.0274,False,OK

[I 2026-07-09 14:09:44,619] Trial 13 finished with value: 0.70254110612855 and parameters: {'n_estimators': 427, 'max_depth': 18, 'min_samples_split': 12, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:46,16,14,RandomForest,0.7059,0.8459,0.7452,0.6705,491,15,2,6,0.39,0.26,0.7093,6,0.6735,0.8211,0.6718,0.6752,0.0324,False,OK

[I 2026-07-09 14:09:46,137] Trial 14 finished with value: 0.7058823529411765 and parameters: {'n_estimators': 491, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:47,16,15,RandomForest,0.7052,0.8469,0.7389,0.6744,411,10,14,6,0.38,0.27,0.7093,6,0.6675,0.8232,0.659,0.6762,0.0376,False,OK

[I 2026-07-09 14:09:47,452] Trial 15 finished with value: 0.7051671732522796 and parameters: {'n_estimators': 411, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:48,16,16,RandomForest,0.7093,0.8456,0.742,0.6793,277,15,10,10,0.4,0.32,0.7093,6,0.6727,0.8209,0.6641,0.6815,0.0366,False,OK

[I 2026-07-09 14:09:48,435] Trial 16 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 277, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:48,16,17,RandomForest,0.7073,0.8462,0.7389,0.6784,69,13,10,10,0.4,0.29,0.7093,6,0.6735,0.8196,0.6667,0.6805,0.0338,False,OK

[I 2026-07-09 14:09:48,884] Trial 17 finished with value: 0.7073170731707317 and parameters: {'n_estimators': 69, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:49,16,18,RandomForest,0.7084,0.8443,0.7389,0.6804,257,17,10,10,0.4,0.34,0.7093,6,0.6701,0.8211,0.6616,0.6789,0.0383,False,OK

[I 2026-07-09 14:09:49,838] Trial 18 finished with value: 0.7083969465648855 and parameters: {'n_estimators': 257, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:50,16,19,RandomForest,0.6934,0.8404,0.7166,0.6716,99,6,17,9,0.41,0.28,0.7093,6,0.6543,0.819,0.6285,0.6823,0.0391,False,OK

[I 2026-07-09 14:09:50,369] Trial 19 finished with value: 0.6933744221879815 and parameters: {'n_estimators': 99, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:50,16,20,RandomForest,0.7038,0.846,0.7452,0.6667,75,18,4,7,0.38,0.38,0.7093,6,0.6786,0.8184,0.6768,0.6803,0.0252,False,OK

[I 2026-07-09 14:09:50,828] Trial 20 finished with value: 0.7037593984962406 and parameters: {'n_estimators': 75, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:51,16,21,RandomForest,0.7093,0.8443,0.742,0.6793,232,17,8,10,0.39,0.34,0.7093,6,0.6709,0.8211,0.6667,0.6753,0.0383,False,OK

[I 2026-07-09 14:09:51,688] Trial 21 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 232, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:52,16,22,RandomForest,0.7084,0.8449,0.7389,0.6804,245,17,4,10,0.41,0.34,0.7093,6,0.6719,0.8211,0.659,0.6852,0.0365,False,OK

[I 2026-07-09 14:09:52,583] Trial 22 finished with value: 0.7083969465648855 and parameters: {'n_estimators': 245, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:53,16,23,RandomForest,0.7071,0.8442,0.742,0.6754,230,15,19,9,0.39,0.32,0.7093,6,0.6735,0.8213,0.6692,0.6778,0.0336,False,OK

[I 2026-07-09 14:09:53,440] Trial 23 finished with value: 0.7071320182094082 and parameters: {'n_estimators': 230, 'max_depth': 15, 'min_samples_split': 19, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:54,16,24,RandomForest,0.7059,0.8452,0.7452,0.6705,308,9,10,10,0.37,0.31,0.7093,6,0.6684,0.8229,0.6641,0.6727,0.0375,False,OK

[I 2026-07-09 14:09:54,484] Trial 24 finished with value: 0.7058823529411765 and parameters: {'n_estimators': 308, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:55,16,25,RandomForest,0.708,0.8454,0.7452,0.6744,237,11,6,10,0.38,0.33,0.7093,6,0.6675,0.8224,0.6641,0.671,0.0405,False,OK

[I 2026-07-09 14:09:55,347] Trial 25 finished with value: 0.708018154311649 and parameters: {'n_estimators': 237, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:56,16,26,RandomForest,0.7059,0.8445,0.7452,0.6705,483,8,20,3,0.36,0.29,0.7093,6,0.6684,0.8228,0.6667,0.6701,0.0375,False,OK

[I 2026-07-09 14:09:56,804] Trial 26 finished with value: 0.7058823529411765 and parameters: {'n_estimators': 483, 'max_depth': 8, 'min_samples_split': 20, 'min_samples_leaf': 3}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:58,16,27,RandomForest,0.7073,0.8453,0.7389,0.6784,410,12,2,10,0.39,0.32,0.7093,6,0.671,0.8215,0.6641,0.6779,0.0364,False,OK

[I 2026-07-09 14:09:58,105] Trial 27 finished with value: 0.7073170731707317 and parameters: {'n_estimators': 410, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:09:59,16,28,RandomForest,0.701,0.8451,0.6943,0.7078,320,19,7,8,0.5,0.28,0.7093,6,0.6427,0.8206,0.5903,0.7052,0.0583,False,OK

[I 2026-07-09 14:09:59,181] Trial 28 finished with value: 0.7009646302250804 and parameters: {'n_estimators': 320, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:00,16,29,RandomForest,0.7038,0.8458,0.7452,0.6667,242,13,14,8,0.38,0.28,0.7093,6,0.6675,0.822,0.6641,0.671,0.0362,False,OK

[I 2026-07-09 14:10:00,064] Trial 29 finished with value: 0.7037593984962406 and parameters: {'n_estimators': 242, 'max_depth': 13, 'min_samples_split': 14, 'min_samples_leaf': 8}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:01,16,30,RandomForest,0.7084,0.8449,0.7389,0.6804,256,20,14,10,0.4,0.3,0.7093,6,0.6718,0.8211,0.6641,0.6797,0.0366,False,OK

[I 2026-07-09 14:10:01,016] Trial 30 finished with value: 0.7083969465648855 and parameters: {'n_estimators': 256, 'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:02,16,31,RandomForest,0.7093,0.8455,0.742,0.6793,286,15,10,10,0.4,0.3,0.7093,6,0.6727,0.8212,0.6641,0.6815,0.0366,False,OK

[I 2026-07-09 14:10:02,025] Trial 31 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 286, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:03,16,32,RandomForest,0.7052,0.8469,0.7389,0.6744,291,14,11,9,0.39,0.31,0.7093,6,0.6675,0.8214,0.659,0.6762,0.0376,False,OK

[I 2026-07-09 14:10:03,063] Trial 32 finished with value: 0.7051671732522796 and parameters: {'n_estimators': 291, 'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:03,16,33,RandomForest,0.7011,0.8419,0.6911,0.7115,145,20,19,1,0.52,0.33,0.7093,6,0.6408,0.814,0.5878,0.7043,0.0604,False,OK

[I 2026-07-09 14:10:03,715] Trial 33 finished with value: 0.7011308562197092 and parameters: {'n_estimators': 145, 'max_depth': 20, 'min_samples_split': 19, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:04,16,34,RandomForest,0.7048,0.8483,0.7452,0.6686,150,19,7,9,0.37,0.32,0.7093,6,0.6718,0.821,0.6718,0.6718,0.0331,False,OK

[I 2026-07-09 14:10:04,367] Trial 34 finished with value: 0.7048192771084337 and parameters: {'n_estimators': 150, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:05,16,35,RandomForest,0.7093,0.8454,0.742,0.6793,373,14,15,10,0.4,0.31,0.7093,6,0.6753,0.8212,0.6667,0.6841,0.034,False,OK

[I 2026-07-09 14:10:05,598] Trial 35 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 373, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:06,16,36,RandomForest,0.7093,0.8447,0.742,0.6793,363,18,3,10,0.39,0.31,0.7093,6,0.6718,0.8214,0.6667,0.677,0.0375,False,OK

[I 2026-07-09 14:10:06,808] Trial 36 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 363, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:07,16,37,RandomForest,0.7093,0.8453,0.742,0.6793,258,15,11,10,0.4,0.32,0.7093,6,0.6735,0.8207,0.6641,0.6832,0.0357,False,OK

[I 2026-07-09 14:10:07,751] Trial 37 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 258, 'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 10}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:08,16,38,RandomForest,0.6487,0.8129,0.7293,0.5842,177,2,6,1,0.38,0.37,0.7093,6,0.6244,0.793,0.6641,0.5892,0.0243,False,OK

[I 2026-07-09 14:10:08,461] Trial 38 finished with value: 0.6487252124645893 and parameters: {'n_estimators': 177, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 1}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:09,16,39,RandomForest,0.6789,0.8352,0.707,0.6529,298,4,20,6,0.39,0.32,0.7093,6,0.645,0.8113,0.631,0.6596,0.0339,False,OK

[I 2026-07-09 14:10:09,473] Trial 39 finished with value: 0.6788990825688074 and parameters: {'n_estimators': 298, 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 6}. Best is trial 6 with value: 0.7092846270928462.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:10,16,40,RandomForest,0.7104,0.8444,0.742,0.6813,298,17,7,10,0.4,0.33,0.7104,40,0.6727,0.8215,0.6616,0.6842,0.0377,False,OK

[I 2026-07-09 14:10:10,513] Trial 40 finished with value: 0.7103658536585366 and parameters: {'n_estimators': 298, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:11,16,41,RandomForest,0.7104,0.8446,0.742,0.6813,297,19,7,10,0.4,0.33,0.7104,40,0.6727,0.8218,0.6616,0.6842,0.0377,False,OK

[I 2026-07-09 14:10:11,552] Trial 41 finished with value: 0.7103658536585366 and parameters: {'n_estimators': 297, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:12,16,42,RandomForest,0.7034,0.8469,0.7325,0.6765,283,20,5,9,0.4,0.28,0.7104,40,0.6727,0.8212,0.6616,0.6842,0.0307,False,OK

[I 2026-07-09 14:10:12,550] Trial 42 finished with value: 0.7033639143730887 and parameters: {'n_estimators': 283, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 9}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:13,16,43,RandomForest,0.7064,0.8471,0.7357,0.6794,253,16,8,9,0.4,0.31,0.7104,40,0.6736,0.82,0.6616,0.686,0.0328,False,OK

[I 2026-07-09 14:10:13,501] Trial 43 finished with value: 0.7064220183486238 and parameters: {'n_estimators': 253, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 9}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:14,16,44,RandomForest,0.7082,0.8452,0.742,0.6773,353,15,6,10,0.39,0.31,0.7104,40,0.6709,0.8212,0.6667,0.6753,0.0373,False,OK

[I 2026-07-09 14:10:14,708] Trial 44 finished with value: 0.7082066869300911 and parameters: {'n_estimators': 353, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:15,16,45,RandomForest,0.7026,0.8454,0.6847,0.7215,316,14,12,1,0.54,0.28,0.7104,40,0.6407,0.8165,0.5852,0.7077,0.0619,False,OK

[I 2026-07-09 14:10:15,839] Trial 45 finished with value: 0.7026143790849673 and parameters: {'n_estimators': 316, 'max_depth': 14, 'min_samples_split': 12, 'min_samples_leaf': 1}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:16,16,46,RandomForest,0.7104,0.8445,0.742,0.6813,277,20,7,10,0.4,0.31,0.7104,40,0.6718,0.8212,0.6616,0.6824,0.0385,False,OK

[I 2026-07-09 14:10:16,818] Trial 46 finished with value: 0.7103658536585366 and parameters: {'n_estimators': 277, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:18,16,47,RandomForest,0.6496,0.8151,0.7293,0.5857,468,2,12,2,0.39,0.22,0.7104,40,0.6268,0.7935,0.6667,0.5914,0.0229,False,OK

[I 2026-07-09 14:10:18,225] Trial 47 finished with value: 0.649645390070922 and parameters: {'n_estimators': 468, 'max_depth': 2, 'min_samples_split': 12, 'min_samples_leaf': 2}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:19,16,48,RandomForest,0.7104,0.8445,0.742,0.6813,349,19,10,10,0.4,0.27,0.7104,40,0.671,0.8211,0.6616,0.6806,0.0394,False,OK

[I 2026-07-09 14:10:19,386] Trial 48 finished with value: 0.7103658536585366 and parameters: {'n_estimators': 349, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:20,16,49,RandomForest,0.7034,0.8465,0.7325,0.6765,302,20,10,9,0.4,0.31,0.7104,40,0.6753,0.8212,0.6641,0.6868,0.0281,False,OK

[I 2026-07-09 14:10:20,409] Trial 49 finished with value: 0.7033639143730887 and parameters: {'n_estimators': 302, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 9}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:21,16,50,RandomForest,0.7028,0.8456,0.6815,0.7254,290,20,2,4,0.55,0.28,0.7104,40,0.6365,0.8162,0.5725,0.7166,0.0663,False,OK

[I 2026-07-09 14:10:21,423] Trial 50 finished with value: 0.7027914614121511 and parameters: {'n_estimators': 290, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:22,16,51,RandomForest,0.7093,0.845,0.742,0.6793,390,20,7,10,0.39,0.31,0.7104,40,0.6718,0.8214,0.6667,0.677,0.0375,False,OK

[I 2026-07-09 14:10:22,674] Trial 51 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 390, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:23,16,52,RandomForest,0.7093,0.8445,0.742,0.6793,291,20,7,10,0.39,0.27,0.7104,40,0.6709,0.8215,0.6667,0.6753,0.0383,False,OK

[I 2026-07-09 14:10:23,673] Trial 52 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 291, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:24,16,53,RandomForest,0.7093,0.8445,0.742,0.6793,350,20,9,10,0.39,0.27,0.7104,40,0.6727,0.8211,0.6667,0.6788,0.0366,False,OK

[I 2026-07-09 14:10:24,813] Trial 53 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 350, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:26,16,54,RandomForest,0.6906,0.8378,0.6752,0.7067,437,5,16,10,0.46,0.34,0.7104,40,0.6257,0.8151,0.57,0.6935,0.0649,False,OK

[I 2026-07-09 14:10:26,152] Trial 54 finished with value: 0.6905537459283387 and parameters: {'n_estimators': 437, 'max_depth': 5, 'min_samples_split': 16, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:26,16,55,RandomForest,0.7016,0.8464,0.7038,0.6994,74,15,15,5,0.49,0.39,0.7104,40,0.6484,0.8185,0.6031,0.7012,0.0532,False,OK

[I 2026-07-09 14:10:26,613] Trial 55 finished with value: 0.7015873015873015 and parameters: {'n_estimators': 74, 'max_depth': 15, 'min_samples_split': 15, 'min_samples_leaf': 5}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:27,16,56,RandomForest,0.698,0.8397,0.7325,0.6667,138,20,10,1,0.42,0.34,0.7104,40,0.6573,0.8125,0.6565,0.6582,0.0407,False,OK

[I 2026-07-09 14:10:27,260] Trial 56 finished with value: 0.6980273141122914 and parameters: {'n_estimators': 138, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:28,16,57,RandomForest,0.7041,0.8472,0.7389,0.6725,271,16,2,9,0.39,0.27,0.7104,40,0.6701,0.82,0.6641,0.6762,0.034,False,OK

[I 2026-07-09 14:10:28,241] Trial 57 finished with value: 0.7040971168437026 and parameters: {'n_estimators': 271, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:28,16,58,RandomForest,0.7002,0.8431,0.7325,0.6706,59,7,16,2,0.39,0.29,0.7104,40,0.65,0.8196,0.6285,0.673,0.0502,False,OK

[I 2026-07-09 14:10:28,674] Trial 58 finished with value: 0.700152207001522 and parameters: {'n_estimators': 59, 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 2}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:29,16,59,RandomForest,0.7038,0.8481,0.7452,0.6667,384,15,9,9,0.38,0.29,0.7104,40,0.6701,0.8215,0.6667,0.6735,0.0337,False,OK

[I 2026-07-09 14:10:29,909] Trial 59 finished with value: 0.7037593984962406 and parameters: {'n_estimators': 384, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:30,16,60,RandomForest,0.7093,0.8453,0.742,0.6793,305,15,2,10,0.39,0.3,0.7104,40,0.6718,0.8209,0.6667,0.677,0.0375,False,OK

[I 2026-07-09 14:10:30,948] Trial 60 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 305, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:31,16,61,RandomForest,0.7084,0.8446,0.7389,0.6804,255,17,7,10,0.4,0.34,0.7104,40,0.6701,0.8212,0.6616,0.6789,0.0383,False,OK

[I 2026-07-09 14:10:31,856] Trial 61 finished with value: 0.7083969465648855 and parameters: {'n_estimators': 255, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:32,16,62,RandomForest,0.7084,0.8446,0.7389,0.6804,255,17,7,10,0.4,0.34,0.7104,40,0.6701,0.8212,0.6616,0.6789,0.0383,False,OK

[I 2026-07-09 14:10:32,772] Trial 62 finished with value: 0.7083969465648855 and parameters: {'n_estimators': 255, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:34,16,63,RandomForest,0.7059,0.8463,0.7452,0.6705,464,18,20,8,0.39,0.28,0.7104,40,0.6684,0.8208,0.6641,0.6727,0.0375,False,OK

[I 2026-07-09 14:10:34,229] Trial 63 finished with value: 0.7058823529411765 and parameters: {'n_estimators': 464, 'max_depth': 18, 'min_samples_split': 20, 'min_samples_leaf': 8}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:35,16,64,RandomForest,0.7093,0.8445,0.742,0.6793,334,17,9,10,0.39,0.31,0.7104,40,0.6718,0.8216,0.6667,0.677,0.0375,False,OK

[I 2026-07-09 14:10:35,337] Trial 64 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 334, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:36,16,65,RandomForest,0.7104,0.8449,0.742,0.6813,258,20,9,10,0.4,0.33,0.7104,40,0.6718,0.8208,0.6641,0.6797,0.0386,False,OK

[I 2026-07-09 14:10:36,255] Trial 65 finished with value: 0.7103658536585366 and parameters: {'n_estimators': 258, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:37,16,66,RandomForest,0.7093,0.8447,0.742,0.6793,207,20,7,10,0.39,0.34,0.7104,40,0.6701,0.8207,0.6641,0.6762,0.0392,False,OK

[I 2026-07-09 14:10:37,044] Trial 66 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 207, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:38,16,67,RandomForest,0.7039,0.8473,0.742,0.6695,356,19,14,9,0.38,0.27,0.7104,40,0.6692,0.8219,0.6667,0.6718,0.0347,False,OK

[I 2026-07-09 14:10:38,238] Trial 67 finished with value: 0.7039274924471299 and parameters: {'n_estimators': 356, 'max_depth': 19, 'min_samples_split': 14, 'min_samples_leaf': 9}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:39,16,68,RandomForest,0.7041,0.847,0.7389,0.6725,259,20,12,7,0.39,0.27,0.7104,40,0.6684,0.8196,0.659,0.678,0.0357,False,OK

[I 2026-07-09 14:10:39,190] Trial 68 finished with value: 0.7040971168437026 and parameters: {'n_estimators': 259, 'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 7}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:40,16,69,RandomForest,0.6595,0.8265,0.6815,0.6388,468,3,3,8,0.42,0.23,0.7104,40,0.6302,0.8033,0.6158,0.6453,0.0293,False,OK

[I 2026-07-09 14:10:40,618] Trial 69 finished with value: 0.6594761171032357 and parameters: {'n_estimators': 468, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:41,16,70,RandomForest,0.7104,0.8429,0.742,0.6813,69,7,4,5,0.39,0.31,0.7104,40,0.6614,0.8205,0.6438,0.6801,0.0489,False,OK

[I 2026-07-09 14:10:41,060] Trial 70 finished with value: 0.7103658536585366 and parameters: {'n_estimators': 69, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:41,16,71,RandomForest,0.7054,0.8447,0.7548,0.662,83,9,4,3,0.35,0.34,0.7104,40,0.6793,0.8247,0.6845,0.6742,0.0261,False,OK

[I 2026-07-09 14:10:41,561] Trial 71 finished with value: 0.7053571428571429 and parameters: {'n_estimators': 83, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 3}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:42,16,72,RandomForest,0.7093,0.8446,0.742,0.6793,363,20,12,10,0.39,0.32,0.7104,40,0.6727,0.8213,0.6667,0.6788,0.0366,False,OK

[I 2026-07-09 14:10:42,753] Trial 72 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 363, 'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:43,16,73,RandomForest,0.7069,0.8465,0.7452,0.6724,88,9,4,4,0.38,0.26,0.7104,40,0.6675,0.8225,0.659,0.6762,0.0394,False,OK

[I 2026-07-09 14:10:43,232] Trial 73 finished with value: 0.7069486404833837 and parameters: {'n_estimators': 88, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:43,16,74,RandomForest,0.7061,0.8435,0.742,0.6734,129,20,12,10,0.39,0.31,0.7104,40,0.6667,0.8202,0.6616,0.6718,0.0394,False,OK

[I 2026-07-09 14:10:43,831] Trial 74 finished with value: 0.706060606060606 and parameters: {'n_estimators': 129, 'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:44,16,75,RandomForest,0.6962,0.8397,0.7261,0.6686,151,6,2,5,0.39,0.28,0.7104,40,0.671,0.8195,0.6539,0.689,0.0252,False,OK

[I 2026-07-09 14:10:44,477] Trial 75 finished with value: 0.6961832061068702 and parameters: {'n_estimators': 151, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:44,16,76,RandomForest,0.6512,0.8202,0.758,0.5707,94,3,2,3,0.33,0.21,0.7104,40,0.6266,0.8001,0.6896,0.5742,0.0246,False,OK

[I 2026-07-09 14:10:44,986] Trial 76 finished with value: 0.6511627906976745 and parameters: {'n_estimators': 94, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:45,16,77,RandomForest,0.7084,0.8448,0.7389,0.6804,278,18,6,10,0.4,0.33,0.7104,40,0.6727,0.8213,0.6616,0.6842,0.0357,False,OK

[I 2026-07-09 14:10:45,964] Trial 77 finished with value: 0.7083969465648855 and parameters: {'n_estimators': 278, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:46,16,78,RandomForest,0.6953,0.839,0.7484,0.6492,89,6,4,6,0.36,0.3,0.7104,40,0.6616,0.8184,0.6692,0.6542,0.0336,False,OK

[I 2026-07-09 14:10:46,437] Trial 78 finished with value: 0.6952662721893491 and parameters: {'n_estimators': 89, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 6}. Best is trial 40 with value: 0.7103658536585366.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:46,16,79,RandomForest,0.711,0.8426,0.7484,0.6772,59,7,7,5,0.38,0.3,0.711,79,0.6649,0.8196,0.6539,0.6763,0.0461,False,OK

[I 2026-07-09 14:10:46,859] Trial 79 finished with value: 0.7110438729198184 and parameters: {'n_estimators': 59, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:47,16,80,RandomForest,0.7026,0.847,0.7261,0.6806,84,8,7,5,0.4,0.3,0.711,79,0.6658,0.8221,0.6438,0.6894,0.0368,False,OK

[I 2026-07-09 14:10:47,334] Trial 80 finished with value: 0.7026194144838213 and parameters: {'n_estimators': 84, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:47,16,81,RandomForest,0.7048,0.8477,0.7452,0.6686,145,10,11,6,0.38,0.26,0.711,79,0.6658,0.8232,0.6565,0.6754,0.039,False,OK

[I 2026-07-09 14:10:47,972] Trial 81 finished with value: 0.7048192771084337 and parameters: {'n_estimators': 145, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 6}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:48,16,82,RandomForest,0.7075,0.8448,0.7548,0.6657,88,7,8,4,0.36,0.32,0.711,79,0.6718,0.8213,0.6692,0.6744,0.0357,False,OK

[I 2026-07-09 14:10:48,447] Trial 82 finished with value: 0.7074626865671642 and parameters: {'n_estimators': 88, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 4}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:49,16,83,RandomForest,0.7078,0.8469,0.7484,0.6714,267,15,5,7,0.38,0.26,0.711,79,0.6709,0.8203,0.6692,0.6726,0.0369,False,OK

[I 2026-07-09 14:10:49,398] Trial 83 finished with value: 0.7078313253012049 and parameters: {'n_estimators': 267, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 7}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:50,16,84,RandomForest,0.7093,0.8448,0.742,0.6793,267,20,12,10,0.4,0.31,0.711,79,0.6727,0.8209,0.6641,0.6815,0.0366,False,OK

[I 2026-07-09 14:10:50,335] Trial 84 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 267, 'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 10}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:51,16,85,RandomForest,0.7069,0.8456,0.7452,0.6724,268,11,3,10,0.38,0.29,0.711,79,0.6675,0.8218,0.6641,0.671,0.0394,False,OK

[I 2026-07-09 14:10:51,272] Trial 85 finished with value: 0.7069486404833837 and parameters: {'n_estimators': 268, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:52,16,86,RandomForest,0.7038,0.8471,0.7452,0.6667,314,12,20,1,0.39,0.24,0.711,79,0.6692,0.821,0.6641,0.6744,0.0345,False,OK

[I 2026-07-09 14:10:52,359] Trial 86 finished with value: 0.7037593984962406 and parameters: {'n_estimators': 314, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 1}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:52,16,87,RandomForest,0.6485,0.807,0.7197,0.5901,62,2,6,7,0.38,0.21,0.711,79,0.6233,0.7879,0.659,0.5913,0.0251,False,OK

[I 2026-07-09 14:10:52,790] Trial 87 finished with value: 0.648493543758967 and parameters: {'n_estimators': 62, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:53,16,88,RandomForest,0.701,0.845,0.6943,0.7078,306,20,6,8,0.5,0.28,0.711,79,0.6427,0.8205,0.5903,0.7052,0.0583,False,OK

[I 2026-07-09 14:10:53,871] Trial 88 finished with value: 0.7009646302250804 and parameters: {'n_estimators': 306, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:54,16,89,RandomForest,0.6548,0.8241,0.6433,0.6667,231,3,8,10,0.44,0.23,0.711,79,0.6104,0.8017,0.57,0.6569,0.0444,False,OK

[I 2026-07-09 14:10:54,738] Trial 89 finished with value: 0.6547811993517018 and parameters: {'n_estimators': 231, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:55,16,90,RandomForest,0.6819,0.8338,0.7134,0.6531,128,4,7,5,0.38,0.36,0.711,79,0.6477,0.8109,0.6361,0.6596,0.0342,False,OK

[I 2026-07-09 14:10:55,315] Trial 90 finished with value: 0.6818873668188736 and parameters: {'n_estimators': 128, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:56,16,91,RandomForest,0.7093,0.8448,0.742,0.6793,235,20,9,10,0.39,0.34,0.711,79,0.6709,0.8207,0.6667,0.6753,0.0383,False,OK

[I 2026-07-09 14:10:56,178] Trial 91 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 235, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:56,16,92,RandomForest,0.7059,0.8465,0.7452,0.6705,74,9,2,7,0.38,0.26,0.711,79,0.665,0.822,0.6616,0.6684,0.0409,False,OK

[I 2026-07-09 14:10:56,633] Trial 92 finished with value: 0.7058823529411765 and parameters: {'n_estimators': 74, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:57,16,93,RandomForest,0.7073,0.8455,0.7389,0.6784,233,14,11,10,0.4,0.33,0.711,79,0.6701,0.8205,0.659,0.6816,0.0372,False,OK

[I 2026-07-09 14:10:57,505] Trial 93 finished with value: 0.7073170731707317 and parameters: {'n_estimators': 233, 'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 10}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:58,16,94,RandomForest,0.7093,0.8444,0.742,0.6793,340,17,9,10,0.39,0.31,0.711,79,0.6718,0.8216,0.6667,0.677,0.0375,False,OK

[I 2026-07-09 14:10:58,628] Trial 94 finished with value: 0.7092846270928462 and parameters: {'n_estimators': 340, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:59,16,95,RandomForest,0.7005,0.8449,0.7038,0.6972,249,17,10,8,0.48,0.27,0.711,79,0.6493,0.8211,0.6031,0.7033,0.0512,False,OK

[I 2026-07-09 14:10:59,528] Trial 95 finished with value: 0.7004754358161648 and parameters: {'n_estimators': 249, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:00,16,96,RandomForest,0.7084,0.8438,0.7389,0.6804,139,16,8,10,0.4,0.31,0.711,79,0.6692,0.8207,0.6616,0.6771,0.0392,False,OK

[I 2026-07-09 14:11:00,149] Trial 96 finished with value: 0.7083969465648855 and parameters: {'n_estimators': 139, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:00,16,97,RandomForest,0.6501,0.8129,0.7484,0.5746,192,2,13,2,0.37,0.22,0.711,79,0.6233,0.7927,0.6819,0.5739,0.0268,False,OK

[I 2026-07-09 14:11:00,884] Trial 97 finished with value: 0.6500691562932227 and parameters: {'n_estimators': 192, 'max_depth': 2, 'min_samples_split': 13, 'min_samples_leaf': 2}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:01,16,98,RandomForest,0.71,0.8443,0.7484,0.6753,70,7,10,7,0.38,0.29,0.711,79,0.6589,0.8207,0.6463,0.672,0.0511,False,OK

[I 2026-07-09 14:11:01,324] Trial 98 finished with value: 0.7099697885196374 and parameters: {'n_estimators': 70, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 7}. Best is trial 79 with value: 0.7110438729198184.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:01,16,99,RandomForest,0.7091,0.8442,0.7452,0.6763,69,7,8,7,0.38,0.29,0.711,79,0.6606,0.8207,0.6463,0.6755,0.0485,False,OK

[I 2026-07-09 14:11:01,763] Trial 99 finished with value: 0.7090909090909091 and parameters: {'n_estimators': 69, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 79 with value: 0.7110438729198184.
/tmp/ipykernel_925/2777212690.py:307: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  sampler_xgb = TPESampler(
[I 2026-07-09 14:11:01,765] A new study created in memory with name: no-name-06bfac8c-d631-484e-b46b-4b4b62a76b8c

\n============================================================
🎉 RF NAS COMPLETE
============================================================
Best Trial: 79
Best F1: 0.7110
Best Params: {'n_estimators': 59, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 5}
\n============================================================
🚀 XGBOOST NAS
============================================================
[2026-07-09 14:11:01.766975] 🚀 Starting XGB NAS (100 trials)...

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:02,16,0,XGBoost,0.7064,0.8442,0.7357,0.6794,100,6,0.1,1.0,1.0,1,0.0,34,3,0.39,0.31,0.7064,0,0.6598,0.8199,0.6514,0.6684,0.0466,True,OK

[I 2026-07-09 14:11:02,498] Trial 0 finished with value: 0.7064220183486238 and parameters: {'n_estimators': 100, 'max_depth': 6, 'learning_rate': 0.1, 'subsample': 1.0, 'colsample_bytree': 1.0, 'min_child_weight': 1, 'gamma': 0.0, 'patience': 3}. Best is trial 0 with value: 0.7064220183486238.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:03,16,1,XGBoost,0.7048,0.8449,0.7261,0.6847,500,4,0.01,0.8,0.8,3,0.1,345,3,0.42,0.28,0.7064,0,0.6622,0.8259,0.6336,0.6936,0.0426,True,OK

[I 2026-07-09 14:11:03,043] Trial 1 finished with value: 0.7047913446676971 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.01, 'subsample': 0.8, 'colsample_bytree': 0.8, 'min_child_weight': 3, 'gamma': 0.1, 'patience': 3}. Best is trial 0 with value: 0.7064220183486238.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:03,16,2,XGBoost,0.7068,0.842,0.7293,0.6856,50,8,0.3,0.7,0.7,1,0.0,7,3,0.41,0.28,0.7068,2,0.6457,0.8134,0.626,0.6667,0.0611,True,OK

[I 2026-07-09 14:11:03,312] Trial 2 finished with value: 0.7067901234567902 and parameters: {'n_estimators': 50, 'max_depth': 8, 'learning_rate': 0.3, 'subsample': 0.7, 'colsample_bytree': 0.7, 'min_child_weight': 1, 'gamma': 0.0, 'patience': 3}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:03,16,3,XGBoost,0.6991,0.8445,0.7325,0.6686,300,3,0.05,0.6,0.6,5,0.5,107,3,0.39,0.28,0.7068,2,0.6727,0.8283,0.6616,0.6842,0.0264,True,OK

[I 2026-07-09 14:11:03,753] Trial 3 finished with value: 0.6990881458966566 and parameters: {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.05, 'subsample': 0.6, 'colsample_bytree': 0.6, 'min_child_weight': 5, 'gamma': 0.5, 'patience': 3}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:04,16,4,XGBoost,0.6909,0.8452,0.6656,0.7182,218,20,0.065049,0.799329,0.578009,2,0.058084,54,5,0.54,0.41,0.7068,2,0.6387,0.8127,0.5802,0.7103,0.0523,False,OK

[I 2026-07-09 14:11:04,136] Trial 4 finished with value: 0.6909090909090909 and parameters: {'n_estimators': 218, 'max_depth': 20, 'learning_rate': 0.06504856968981275, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'min_child_weight': 2, 'gamma': 0.05808361216819946, 'patience': 5}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:08,16,5,XGBoost,0.7038,0.8456,0.7452,0.6667,321,15,0.001125,0.984955,0.916221,3,0.181825,320,2,0.34,0.33,0.7068,2,0.6658,0.8124,0.6692,0.6625,0.0379,False,OK

[I 2026-07-09 14:11:08,476] Trial 5 finished with value: 0.7037593984962406 and parameters: {'n_estimators': 321, 'max_depth': 15, 'learning_rate': 0.001124579825911934, 'subsample': 0.9849549260809971, 'colsample_bytree': 0.9162213204002109, 'min_child_weight': 3, 'gamma': 0.18182496720710062, 'patience': 2}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:09,16,6,XGBoost,0.7007,0.8476,0.6783,0.7245,187,11,0.011748,0.645615,0.805926,2,0.292145,186,3,0.53,0.29,0.7068,2,0.6423,0.8193,0.5802,0.7192,0.0584,False,OK

[I 2026-07-09 14:11:09,044] Trial 6 finished with value: 0.7006578947368421 and parameters: {'n_estimators': 187, 'max_depth': 11, 'learning_rate': 0.01174843954800703, 'subsample': 0.645614570099021, 'colsample_bytree': 0.8059264473611898, 'min_child_weight': 2, 'gamma': 0.29214464853521815, 'patience': 3}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:09,16,7,XGBoost,0.6989,0.8489,0.7134,0.685,255,16,0.003123,0.757117,0.796207,1,0.607545,254,2,0.39,0.3,0.7068,2,0.6514,0.8184,0.6158,0.6914,0.0475,False,OK

[I 2026-07-09 14:11:09,869] Trial 7 finished with value: 0.6989079563182528 and parameters: {'n_estimators': 255, 'max_depth': 16, 'learning_rate': 0.003123317753376431, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'min_child_weight': 1, 'gamma': 0.6075448519014384, 'patience': 2}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:10,16,8,XGBoost,0.6971,0.8394,0.7293,0.6676,79,20,0.246597,0.904199,0.652307,1,0.684233,9,3,0.43,0.36,0.7068,2,0.658,0.8115,0.6438,0.6729,0.0391,False,OK

[I 2026-07-09 14:11:10,165] Trial 8 finished with value: 0.6971080669710806 and parameters: {'n_estimators': 79, 'max_depth': 20, 'learning_rate': 0.24659691172104828, 'subsample': 0.9041986740582306, 'colsample_bytree': 0.6523068845866853, 'min_child_weight': 1, 'gamma': 0.6842330265121569, 'patience': 3}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:10,16,9,XGBoost,0.6904,0.8407,0.742,0.6454,105,11,0.001217,0.95466,0.62939,7,0.311711,104,4,0.33,0.32,0.7068,2,0.6608,0.8207,0.6718,0.6502,0.0295,False,OK

[I 2026-07-09 14:11:10,624] Trial 9 finished with value: 0.6903703703703704 and parameters: {'n_estimators': 105, 'max_depth': 11, 'learning_rate': 0.0012167028814593455, 'subsample': 0.954660201039391, 'colsample_bytree': 0.6293899908000085, 'min_child_weight': 7, 'gamma': 0.31171107608941095, 'patience': 4}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:10,16,10,XGBoost,0.7042,0.8505,0.6975,0.711,214,4,0.122814,0.777197,0.695303,2,0.15394,57,4,0.52,0.3,0.7068,2,0.6557,0.8277,0.6081,0.7113,0.0485,False,OK

[I 2026-07-09 14:11:10,942] Trial 10 finished with value: 0.7041800643086816 and parameters: {'n_estimators': 214, 'max_depth': 4, 'learning_rate': 0.12281405447035115, 'subsample': 0.7771968315996324, 'colsample_bytree': 0.6953032697284646, 'min_child_weight': 2, 'gamma': 0.1539402661906502, 'patience': 4}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:11,16,11,XGBoost,0.6967,0.8376,0.7134,0.6809,73,2,0.154566,0.883408,0.937137,1,0.200844,35,3,0.43,0.35,0.7068,2,0.6552,0.8252,0.631,0.6813,0.0415,False,OK

[I 2026-07-09 14:11:11,234] Trial 11 finished with value: 0.6967340590979783 and parameters: {'n_estimators': 73, 'max_depth': 2, 'learning_rate': 0.15456585985729884, 'subsample': 0.8834079599627223, 'colsample_bytree': 0.9371369723351402, 'min_child_weight': 1, 'gamma': 0.20084441267792222, 'patience': 3}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:11,16,12,XGBoost,0.6941,0.8403,0.7261,0.6647,114,14,0.052645,0.983536,0.931446,3,0.089931,44,3,0.41,0.37,0.7068,2,0.6649,0.8068,0.6489,0.6818,0.0291,False,OK

[I 2026-07-09 14:11:11,643] Trial 12 finished with value: 0.6940639269406392 and parameters: {'n_estimators': 114, 'max_depth': 14, 'learning_rate': 0.05264477954650517, 'subsample': 0.9835362183897025, 'colsample_bytree': 0.9314459720698616, 'min_child_weight': 3, 'gamma': 0.08993064405322271, 'patience': 3}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:11,16,13,XGBoost,0.698,0.8413,0.7102,0.6862,113,10,0.161863,0.616271,0.880497,3,0.081186,15,4,0.46,0.23,0.7068,2,0.647,0.8176,0.6132,0.6847,0.051,False,OK

[I 2026-07-09 14:11:11,936] Trial 13 finished with value: 0.6979655712050078 and parameters: {'n_estimators': 113, 'max_depth': 10, 'learning_rate': 0.16186258544241466, 'subsample': 0.6162706284113394, 'colsample_bytree': 0.8804973600079926, 'min_child_weight': 3, 'gamma': 0.0811857872572626, 'patience': 4}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:12,16,14,XGBoost,0.703,0.8404,0.7197,0.6869,124,10,0.257324,0.678402,0.628127,2,0.134487,8,2,0.43,0.36,0.7068,2,0.6507,0.8127,0.6234,0.6806,0.0522,False,OK

[I 2026-07-09 14:11:12,217] Trial 14 finished with value: 0.702954898911353 and parameters: {'n_estimators': 124, 'max_depth': 10, 'learning_rate': 0.2573237388142572, 'subsample': 0.6784017537764548, 'colsample_bytree': 0.6281274979537668, 'min_child_weight': 2, 'gamma': 0.13448651762918384, 'patience': 2}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:12,16,15,XGBoost,0.6961,0.8458,0.6783,0.7148,104,3,0.188148,0.5097,0.731132,2,0.207018,32,3,0.52,0.34,0.7068,2,0.6456,0.826,0.598,0.7015,0.0505,False,OK

[I 2026-07-09 14:11:12,547] Trial 15 finished with value: 0.696078431372549 and parameters: {'n_estimators': 104, 'max_depth': 3, 'learning_rate': 0.18814781983606393, 'subsample': 0.5097001640361639, 'colsample_bytree': 0.7311322070847369, 'min_child_weight': 2, 'gamma': 0.20701799365790766, 'patience': 3}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:12,16,16,XGBoost,0.7036,0.8454,0.707,0.7003,252,6,0.184383,0.849088,0.996219,2,0.625045,25,4,0.49,0.29,0.7068,2,0.6523,0.8185,0.6158,0.6934,0.0514,False,OK

[I 2026-07-09 14:11:12,866] Trial 16 finished with value: 0.7036450079239303 and parameters: {'n_estimators': 252, 'max_depth': 6, 'learning_rate': 0.1843833408943317, 'subsample': 0.8490881309614714, 'colsample_bytree': 0.9962186108263973, 'min_child_weight': 2, 'gamma': 0.6250451815218928, 'patience': 4}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:13,16,17,XGBoost,0.6945,0.833,0.7675,0.6342,231,2,0.011216,0.950999,0.940342,4,0.37152,230,2,0.33,0.33,0.7068,2,0.6917,0.8233,0.7277,0.659,0.0029,False,OK

[I 2026-07-09 14:11:13,266] Trial 17 finished with value: 0.6945244956772334 and parameters: {'n_estimators': 231, 'max_depth': 2, 'learning_rate': 0.011215837981231644, 'subsample': 0.9509993795111534, 'colsample_bytree': 0.9403420825254118, 'min_child_weight': 4, 'gamma': 0.37152036635584856, 'patience': 2}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:13,16,18,XGBoost,0.7009,0.8414,0.7166,0.686,90,4,0.015452,0.879309,0.992999,3,0.022615,89,3,0.4,0.33,0.7068,2,0.6515,0.8239,0.6183,0.6884,0.0495,False,OK

[I 2026-07-09 14:11:13,640] Trial 18 finished with value: 0.7009345794392523 and parameters: {'n_estimators': 90, 'max_depth': 4, 'learning_rate': 0.01545189282644664, 'subsample': 0.8793090177722691, 'colsample_bytree': 0.9929993266284828, 'min_child_weight': 3, 'gamma': 0.022615455862511163, 'patience': 3}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:13,16,19,XGBoost,0.694,0.8454,0.7006,0.6875,106,9,0.250713,0.780501,0.523814,4,0.042613,15,4,0.48,0.35,0.7068,2,0.6559,0.8177,0.6209,0.6952,0.0381,False,OK

[I 2026-07-09 14:11:13,937] Trial 19 finished with value: 0.694006309148265 and parameters: {'n_estimators': 106, 'max_depth': 9, 'learning_rate': 0.2507126480024375, 'subsample': 0.7805005939981196, 'colsample_bytree': 0.5238141954748516, 'min_child_weight': 4, 'gamma': 0.04261306006769842, 'patience': 4}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:14,16,20,XGBoost,0.7041,0.846,0.7389,0.6725,273,7,0.088907,0.88152,0.996365,1,0.003886,43,5,0.38,0.27,0.7068,2,0.6607,0.818,0.6616,0.6599,0.0434,False,OK

[I 2026-07-09 14:11:14,271] Trial 20 finished with value: 0.7040971168437026 and parameters: {'n_estimators': 273, 'max_depth': 7, 'learning_rate': 0.08890696844820603, 'subsample': 0.8815195200072169, 'colsample_bytree': 0.9963651585008978, 'min_child_weight': 1, 'gamma': 0.003886448858676665, 'patience': 5}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:14,16,21,XGBoost,0.702,0.8485,0.7166,0.6881,471,6,0.014515,0.818426,0.768478,3,0.199968,244,4,0.42,0.27,0.7068,2,0.6587,0.8266,0.631,0.6889,0.0433,False,OK

[I 2026-07-09 14:11:14,832] Trial 21 finished with value: 0.7020280811232449 and parameters: {'n_estimators': 471, 'max_depth': 6, 'learning_rate': 0.014515240412838245, 'subsample': 0.8184260187408372, 'colsample_bytree': 0.7684779755236538, 'min_child_weight': 3, 'gamma': 0.19996813367361124, 'patience': 4}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:15,16,22,XGBoost,0.7062,0.8466,0.758,0.6611,74,7,0.060325,0.997636,0.988689,1,0.135024,48,2,0.34,0.29,0.7068,2,0.6716,0.8183,0.687,0.6569,0.0346,False,OK

[I 2026-07-09 14:11:15,181] Trial 22 finished with value: 0.7062314540059347 and parameters: {'n_estimators': 74, 'max_depth': 7, 'learning_rate': 0.06032482152861806, 'subsample': 0.9976364985736242, 'colsample_bytree': 0.9886889808858932, 'min_child_weight': 1, 'gamma': 0.13502412175230116, 'patience': 2}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:15,16,23,XGBoost,0.6969,0.8458,0.7102,0.684,216,5,0.244082,0.978893,0.799452,2,0.072355,11,2,0.43,0.27,0.7068,2,0.6578,0.8273,0.631,0.687,0.0391,False,OK

[I 2026-07-09 14:11:15,485] Trial 23 finished with value: 0.696875 and parameters: {'n_estimators': 216, 'max_depth': 5, 'learning_rate': 0.24408204592204727, 'subsample': 0.9788927210372688, 'colsample_bytree': 0.7994520840646722, 'min_child_weight': 2, 'gamma': 0.07235466752893711, 'patience': 2}. Best is trial 2 with value: 0.7067901234567902.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:15,16,24,XGBoost,0.7073,0.8484,0.758,0.663,86,7,0.045058,0.965273,0.92536,3,0.390809,72,2,0.34,0.28,0.7073,24,0.6717,0.8209,0.6819,0.6617,0.0356,False,OK

[I 2026-07-09 14:11:15,877] Trial 24 finished with value: 0.7072808320950966 and parameters: {'n_estimators': 86, 'max_depth': 7, 'learning_rate': 0.0450578714894124, 'subsample': 0.9652726259295449, 'colsample_bytree': 0.9253595147240299, 'min_child_weight': 3, 'gamma': 0.3908091352490363, 'patience': 2}. Best is trial 24 with value: 0.7072808320950966.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:16,16,25,XGBoost,0.7035,0.8474,0.7707,0.6471,99,9,0.103018,0.988064,0.839618,2,0.760558,28,3,0.33,0.3,0.7073,24,0.6691,0.8142,0.6947,0.6454,0.0344,False,OK

[I 2026-07-09 14:11:16,253] Trial 25 finished with value: 0.7034883720930233 and parameters: {'n_estimators': 99, 'max_depth': 9, 'learning_rate': 0.10301750885891672, 'subsample': 0.9880644098512781, 'colsample_bytree': 0.8396178088746824, 'min_child_weight': 2, 'gamma': 0.7605579065268916, 'patience': 3}. Best is trial 24 with value: 0.7072808320950966.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:16,16,26,XGBoost,0.7132,0.8438,0.7643,0.6685,72,7,0.007643,0.985198,0.917497,5,0.699187,71,2,0.32,0.3,0.7132,26,0.6708,0.8204,0.6896,0.653,0.0424,False,OK

[I 2026-07-09 14:11:16,606] Trial 26 finished with value: 0.7132243684992571 and parameters: {'n_estimators': 72, 'max_depth': 7, 'learning_rate': 0.007642767607771812, 'subsample': 0.985198489514726, 'colsample_bytree': 0.9174969249868766, 'min_child_weight': 5, 'gamma': 0.6991872563266783, 'patience': 2}. Best is trial 26 with value: 0.7132243684992571.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:16,16,27,XGBoost,0.7108,0.8483,0.7357,0.6875,91,7,0.004402,0.869281,0.849435,5,0.719116,90,3,0.35,0.31,0.7132,26,0.6579,0.8224,0.6387,0.6784,0.0528,False,OK

[I 2026-07-09 14:11:17,002] Trial 27 finished with value: 0.7107692307692308 and parameters: {'n_estimators': 91, 'max_depth': 7, 'learning_rate': 0.004401987160626409, 'subsample': 0.8692814292203717, 'colsample_bytree': 0.849434652411039, 'min_child_weight': 5, 'gamma': 0.7191161767578225, 'patience': 3}. Best is trial 26 with value: 0.7132243684992571.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:17,16,28,XGBoost,0.7077,0.8441,0.7325,0.6845,77,10,0.009246,0.816289,0.786887,7,0.470747,76,2,0.37,0.31,0.7132,26,0.657,0.8233,0.6361,0.6793,0.0507,False,OK

[I 2026-07-09 14:11:17,386] Trial 28 finished with value: 0.7076923076923077 and parameters: {'n_estimators': 77, 'max_depth': 10, 'learning_rate': 0.009246458539779, 'subsample': 0.8162891298610867, 'colsample_bytree': 0.7868874150735493, 'min_child_weight': 7, 'gamma': 0.47074696736631116, 'patience': 2}. Best is trial 26 with value: 0.7132243684992571.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:17,16,29,XGBoost,0.7076,0.845,0.7516,0.6686,73,11,0.016255,0.877671,0.808225,8,0.808002,72,2,0.34,0.3,0.7132,26,0.6675,0.8222,0.6718,0.6633,0.0401,False,OK

[I 2026-07-09 14:11:17,750] Trial 29 finished with value: 0.7076461769115442 and parameters: {'n_estimators': 73, 'max_depth': 11, 'learning_rate': 0.01625536336689684, 'subsample': 0.8776709513825864, 'colsample_bytree': 0.808225036319128, 'min_child_weight': 8, 'gamma': 0.8080017687151735, 'patience': 2}. Best is trial 26 with value: 0.7132243684992571.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:18,16,30,XGBoost,0.7086,0.8461,0.7357,0.6834,100,13,0.016364,0.795049,0.816406,8,0.189055,99,2,0.38,0.28,0.7132,26,0.6667,0.8228,0.6565,0.6772,0.0419,False,OK

[I 2026-07-09 14:11:18,205] Trial 30 finished with value: 0.7085889570552147 and parameters: {'n_estimators': 100, 'max_depth': 13, 'learning_rate': 0.016364398047743565, 'subsample': 0.7950492475082921, 'colsample_bytree': 0.8164059745941264, 'min_child_weight': 8, 'gamma': 0.18905545462291712, 'patience': 2}. Best is trial 26 with value: 0.7132243684992571.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:18,16,31,XGBoost,0.7128,0.8458,0.7707,0.663,106,9,0.048465,0.821062,0.853562,9,0.280666,53,2,0.32,0.32,0.7132,26,0.684,0.8239,0.7048,0.6643,0.0289,False,OK

[I 2026-07-09 14:11:18,679] Trial 31 finished with value: 0.7128129602356407 and parameters: {'n_estimators': 106, 'max_depth': 9, 'learning_rate': 0.04846482692740486, 'subsample': 0.8210623048980965, 'colsample_bytree': 0.8535624643471298, 'min_child_weight': 9, 'gamma': 0.2806656886724161, 'patience': 2}. Best is trial 26 with value: 0.7132243684992571.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:21,16,32,XGBoost,0.7177,0.8452,0.7611,0.679,121,6,0.004361,0.968151,0.98764,6,0.919729,120,2,0.33,0.31,0.7177,32,0.6718,0.8209,0.6692,0.6744,0.0459,False,OK

[I 2026-07-09 14:11:21,523] Trial 32 finished with value: 0.7177177177177178 and parameters: {'n_estimators': 121, 'max_depth': 6, 'learning_rate': 0.004360547256544793, 'subsample': 0.9681512063522199, 'colsample_bytree': 0.9876396483580693, 'min_child_weight': 6, 'gamma': 0.9197293910467357, 'patience': 2}. Best is trial 32 with value: 0.7177177177177178.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:21,16,33,XGBoost,0.7199,0.8465,0.7611,0.6829,148,6,0.00412,0.917587,0.972212,6,0.772311,147,2,0.33,0.29,0.7199,33,0.6641,0.8219,0.659,0.6693,0.0558,False,OK

[I 2026-07-09 14:11:21,966] Trial 33 finished with value: 0.7198795180722891 and parameters: {'n_estimators': 148, 'max_depth': 6, 'learning_rate': 0.004120366431974378, 'subsample': 0.917587357439022, 'colsample_bytree': 0.9722115190446639, 'min_child_weight': 6, 'gamma': 0.7723114844653445, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:22,16,34,XGBoost,0.6627,0.8181,0.7038,0.6261,115,2,0.002352,0.872404,0.98351,10,0.972514,114,2,0.32,0.32,0.7199,33,0.6725,0.8114,0.6819,0.6634,-0.0099,False,OK

[I 2026-07-09 14:11:22,322] Trial 34 finished with value: 0.6626686656671664 and parameters: {'n_estimators': 115, 'max_depth': 2, 'learning_rate': 0.002352479968363008, 'subsample': 0.8724036913550696, 'colsample_bytree': 0.9835096247767222, 'min_child_weight': 10, 'gamma': 0.9725135143197184, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:22,16,35,XGBoost,0.7064,0.8457,0.7548,0.6639,244,7,0.106991,0.764372,0.886203,8,0.236977,27,2,0.32,0.29,0.7199,33,0.6838,0.825,0.7099,0.6596,0.0226,False,OK

[I 2026-07-09 14:11:22,646] Trial 35 finished with value: 0.706408345752608 and parameters: {'n_estimators': 244, 'max_depth': 7, 'learning_rate': 0.10699147943696391, 'subsample': 0.7643715107963895, 'colsample_bytree': 0.8862034277794367, 'min_child_weight': 8, 'gamma': 0.2369769237516218, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:23,16,36,XGBoost,0.7143,0.8413,0.7643,0.6704,127,9,0.003103,0.999516,0.956396,5,0.689255,126,2,0.33,0.32,0.7199,33,0.6667,0.8182,0.6794,0.6544,0.0476,False,OK

[I 2026-07-09 14:11:23,152] Trial 36 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 127, 'max_depth': 9, 'learning_rate': 0.0031033099524564824, 'subsample': 0.9995163929802363, 'colsample_bytree': 0.9563960099414758, 'min_child_weight': 5, 'gamma': 0.6892545807576836, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:23,16,37,XGBoost,0.7149,0.8471,0.7707,0.6667,91,8,0.007779,0.951652,0.960332,6,0.876277,90,2,0.32,0.29,0.7199,33,0.6683,0.8176,0.6921,0.6461,0.0466,False,OK

[I 2026-07-09 14:11:23,537] Trial 37 finished with value: 0.7149187592319055 and parameters: {'n_estimators': 91, 'max_depth': 8, 'learning_rate': 0.00777856982378281, 'subsample': 0.9516524916929465, 'colsample_bytree': 0.960331711904131, 'min_child_weight': 6, 'gamma': 0.8762771807855663, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:23,16,38,XGBoost,0.7104,0.8414,0.758,0.6685,103,5,0.001074,0.924864,0.961389,3,0.961688,102,2,0.32,0.31,0.7199,33,0.665,0.8195,0.6768,0.6536,0.0454,False,OK

[I 2026-07-09 14:11:23,932] Trial 38 finished with value: 0.7104477611940299 and parameters: {'n_estimators': 103, 'max_depth': 5, 'learning_rate': 0.0010739252746236056, 'subsample': 0.9248643247905062, 'colsample_bytree': 0.9613892860268958, 'min_child_weight': 3, 'gamma': 0.9616880158858294, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:24,16,39,XGBoost,0.7132,0.8473,0.7325,0.6949,260,9,0.001807,0.925719,0.912474,6,0.573823,259,2,0.37,0.3,0.7199,33,0.6587,0.8195,0.6336,0.686,0.0544,False,OK

[I 2026-07-09 14:11:24,542] Trial 39 finished with value: 0.7131782945736435 and parameters: {'n_estimators': 260, 'max_depth': 9, 'learning_rate': 0.0018070467233746617, 'subsample': 0.9257186919433766, 'colsample_bytree': 0.9124741000689595, 'min_child_weight': 6, 'gamma': 0.5738234532595308, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:25,16,40,XGBoost,0.7126,0.8445,0.7739,0.6603,232,7,0.008089,0.962318,0.979523,6,0.851853,231,3,0.31,0.3,0.7199,33,0.6748,0.8195,0.7048,0.6472,0.0378,False,OK

[I 2026-07-09 14:11:25,082] Trial 40 finished with value: 0.7126099706744868 and parameters: {'n_estimators': 232, 'max_depth': 7, 'learning_rate': 0.008088679489134299, 'subsample': 0.9623178151863054, 'colsample_bytree': 0.9795230678806951, 'min_child_weight': 6, 'gamma': 0.8518533807299458, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:25,16,41,XGBoost,0.7115,0.8424,0.742,0.6833,68,5,0.014017,0.985453,0.925274,7,0.632285,67,2,0.35,0.31,0.7199,33,0.6641,0.8216,0.6489,0.68,0.0474,False,OK

[I 2026-07-09 14:11:25,419] Trial 41 finished with value: 0.7114503816793893 and parameters: {'n_estimators': 68, 'max_depth': 5, 'learning_rate': 0.014017295604258979, 'subsample': 0.9854530328358895, 'colsample_bytree': 0.9252738995329406, 'min_child_weight': 7, 'gamma': 0.6322848267487958, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:25,16,42,XGBoost,0.7025,0.8483,0.7484,0.662,132,12,0.004813,0.950409,0.917289,2,0.653758,131,2,0.34,0.34,0.7199,33,0.6733,0.8152,0.6845,0.6626,0.0292,False,OK

[I 2026-07-09 14:11:25,928] Trial 42 finished with value: 0.70254110612855 and parameters: {'n_estimators': 132, 'max_depth': 12, 'learning_rate': 0.00481305969577395, 'subsample': 0.9504094583310502, 'colsample_bytree': 0.9172894343872803, 'min_child_weight': 2, 'gamma': 0.6537581428955397, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:26,16,43,XGBoost,0.7044,0.8447,0.7134,0.6957,159,4,0.036329,0.943837,0.920896,4,0.928766,98,2,0.46,0.33,0.7199,33,0.6569,0.8273,0.626,0.691,0.0475,False,OK

[I 2026-07-09 14:11:26,303] Trial 43 finished with value: 0.7044025157232704 and parameters: {'n_estimators': 159, 'max_depth': 4, 'learning_rate': 0.03632877668163798, 'subsample': 0.9438367368997617, 'colsample_bytree': 0.9208960282707552, 'min_child_weight': 4, 'gamma': 0.928766351904348, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:26,16,44,XGBoost,0.7132,0.8407,0.7484,0.6812,76,10,0.002859,0.991953,0.998413,8,0.899182,75,2,0.33,0.31,0.7199,33,0.6581,0.8137,0.6514,0.6649,0.0551,False,OK

[I 2026-07-09 14:11:26,705] Trial 44 finished with value: 0.7132018209408194 and parameters: {'n_estimators': 76, 'max_depth': 10, 'learning_rate': 0.002859439161080143, 'subsample': 0.9919534326748068, 'colsample_bytree': 0.9984134049187763, 'min_child_weight': 8, 'gamma': 0.8991819485468266, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:27,16,45,XGBoost,0.713,0.8466,0.7675,0.6657,84,7,0.007053,0.937501,0.957981,5,0.75483,83,3,0.32,0.29,0.7199,33,0.6741,0.8209,0.6921,0.657,0.0389,False,OK

[I 2026-07-09 14:11:27,087] Trial 45 finished with value: 0.7130177514792899 and parameters: {'n_estimators': 84, 'max_depth': 7, 'learning_rate': 0.007052899605604158, 'subsample': 0.9375011967287495, 'colsample_bytree': 0.9579813069756701, 'min_child_weight': 5, 'gamma': 0.7548295887315865, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:27,16,46,XGBoost,0.716,0.8454,0.7548,0.681,75,6,0.006462,0.874108,0.938471,6,0.958746,74,2,0.33,0.31,0.7199,33,0.6589,0.8243,0.6489,0.6693,0.0571,False,OK

[I 2026-07-09 14:11:27,437] Trial 46 finished with value: 0.716012084592145 and parameters: {'n_estimators': 75, 'max_depth': 6, 'learning_rate': 0.006462081783547266, 'subsample': 0.8741075915374821, 'colsample_bytree': 0.9384708880959614, 'min_child_weight': 6, 'gamma': 0.9587464176417841, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:27,16,47,XGBoost,0.7092,0.8453,0.7261,0.693,100,6,0.034027,0.770263,0.883025,7,0.986381,91,2,0.45,0.3,0.7199,33,0.6631,0.8263,0.6361,0.6925,0.046,False,OK

[I 2026-07-09 14:11:27,808] Trial 47 finished with value: 0.7091757387247278 and parameters: {'n_estimators': 100, 'max_depth': 6, 'learning_rate': 0.03402654290216228, 'subsample': 0.770262732524274, 'colsample_bytree': 0.883024625384194, 'min_child_weight': 7, 'gamma': 0.9863814012437391, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:28,16,48,XGBoost,0.7059,0.8426,0.7452,0.6705,62,9,0.003205,0.745948,0.942019,6,0.796297,61,2,0.33,0.32,0.7199,33,0.6667,0.8224,0.6641,0.6692,0.0392,False,OK

[I 2026-07-09 14:11:28,164] Trial 48 finished with value: 0.7058823529411765 and parameters: {'n_estimators': 62, 'max_depth': 9, 'learning_rate': 0.0032048153361602825, 'subsample': 0.7459483930550584, 'colsample_bytree': 0.9420191068451259, 'min_child_weight': 6, 'gamma': 0.7962969167648782, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:28,16,49,XGBoost,0.71,0.8463,0.7484,0.6753,197,8,0.005054,0.879689,0.913161,7,0.92792,196,2,0.34,0.29,0.7199,33,0.6675,0.8208,0.6692,0.6658,0.0425,False,OK

[I 2026-07-09 14:11:28,707] Trial 49 finished with value: 0.7099697885196374 and parameters: {'n_estimators': 197, 'max_depth': 8, 'learning_rate': 0.005054297620327306, 'subsample': 0.8796891463501642, 'colsample_bytree': 0.9131611225100457, 'min_child_weight': 7, 'gamma': 0.9279197846436835, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:29,16,50,XGBoost,0.7134,0.8472,0.7611,0.6713,67,6,0.004216,0.880799,0.91125,6,0.990132,66,2,0.32,0.32,0.7199,33,0.6717,0.8229,0.6845,0.6593,0.0418,False,OK

[I 2026-07-09 14:11:29,052] Trial 50 finished with value: 0.7134328358208956 and parameters: {'n_estimators': 67, 'max_depth': 6, 'learning_rate': 0.004216377533333947, 'subsample': 0.8807993291287519, 'colsample_bytree': 0.9112503685412912, 'min_child_weight': 6, 'gamma': 0.9901318139278176, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:29,16,51,XGBoost,0.6765,0.8168,0.7325,0.6284,258,2,0.001733,0.987565,0.942849,5,0.794055,257,2,0.31,0.31,0.7199,33,0.6782,0.8114,0.6972,0.6602,-0.0017,False,OK

[I 2026-07-09 14:11:29,466] Trial 51 finished with value: 0.6764705882352942 and parameters: {'n_estimators': 258, 'max_depth': 2, 'learning_rate': 0.001732869130230182, 'subsample': 0.9875650358828778, 'colsample_bytree': 0.9428492469148838, 'min_child_weight': 5, 'gamma': 0.7940546045926051, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:29,16,52,XGBoost,0.7045,0.8439,0.7707,0.6488,120,12,0.022147,0.937651,0.990122,3,0.984141,115,2,0.34,0.31,0.7199,33,0.6716,0.8143,0.6921,0.6523,0.0329,False,OK

[I 2026-07-09 14:11:29,928] Trial 52 finished with value: 0.7045123726346434 and parameters: {'n_estimators': 120, 'max_depth': 12, 'learning_rate': 0.022147414216496072, 'subsample': 0.9376507800668407, 'colsample_bytree': 0.9901222097805589, 'min_child_weight': 3, 'gamma': 0.9841412396851821, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:30,16,53,XGBoost,0.6627,0.8194,0.7038,0.6261,119,2,0.002219,0.803497,0.92648,6,0.957565,118,3,0.33,0.33,0.7199,33,0.6758,0.8141,0.687,0.665,-0.0132,False,OK

[I 2026-07-09 14:11:30,288] Trial 53 finished with value: 0.6626686656671664 and parameters: {'n_estimators': 119, 'max_depth': 2, 'learning_rate': 0.002219189836482901, 'subsample': 0.8034969630272736, 'colsample_bytree': 0.9264795332665601, 'min_child_weight': 6, 'gamma': 0.957564783231523, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:30,16,54,XGBoost,0.6938,0.8333,0.7866,0.6206,158,3,0.006078,0.896567,0.998117,5,0.783198,157,2,0.27,0.3,0.7199,33,0.6887,0.8205,0.743,0.6418,0.0051,False,OK

[I 2026-07-09 14:11:30,665] Trial 54 finished with value: 0.6938202247191011 and parameters: {'n_estimators': 158, 'max_depth': 3, 'learning_rate': 0.006078022049061542, 'subsample': 0.896566716364172, 'colsample_bytree': 0.998116580092427, 'min_child_weight': 5, 'gamma': 0.7831981870723347, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:31,16,55,XGBoost,0.7103,0.8395,0.7611,0.6657,120,5,0.00147,0.980683,0.995107,4,0.454044,119,3,0.32,0.31,0.7199,33,0.66,0.8184,0.6743,0.6463,0.0502,False,OK

[I 2026-07-09 14:11:31,048] Trial 55 finished with value: 0.7102526002971769 and parameters: {'n_estimators': 120, 'max_depth': 5, 'learning_rate': 0.0014703669605708272, 'subsample': 0.980683167453093, 'colsample_bytree': 0.9951067530689763, 'min_child_weight': 4, 'gamma': 0.45404436116020475, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:31,16,56,XGBoost,0.6878,0.8278,0.7611,0.6273,109,3,0.00244,0.926061,0.854098,7,0.884463,108,2,0.32,0.32,0.7199,33,0.6906,0.818,0.7328,0.6531,-0.0029,False,OK

[I 2026-07-09 14:11:31,429] Trial 56 finished with value: 0.6877697841726619 and parameters: {'n_estimators': 109, 'max_depth': 3, 'learning_rate': 0.0024401263323810727, 'subsample': 0.9260609462009557, 'colsample_bytree': 0.8540981598106189, 'min_child_weight': 7, 'gamma': 0.8844630854125932, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:31,16,57,XGBoost,0.6997,0.8456,0.6975,0.7019,457,14,0.078614,0.889121,0.589162,2,0.125386,37,2,0.46,0.34,0.7199,33,0.6531,0.811,0.6107,0.7018,0.0466,False,OK

[I 2026-07-09 14:11:31,798] Trial 57 finished with value: 0.6996805111821086 and parameters: {'n_estimators': 457, 'max_depth': 14, 'learning_rate': 0.07861362213169187, 'subsample': 0.8891207060943994, 'colsample_bytree': 0.5891623663048405, 'min_child_weight': 2, 'gamma': 0.12538595940786523, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:34,16,58,XGBoost,0.6997,0.8456,0.6975,0.7019,76,17,0.019889,0.99501,0.64787,3,0.500705,75,5,0.45,0.3,0.7199,33,0.6503,0.8181,0.6056,0.7021,0.0494,False,OK

[I 2026-07-09 14:11:34,734] Trial 58 finished with value: 0.6996805111821086 and parameters: {'n_estimators': 76, 'max_depth': 17, 'learning_rate': 0.019888575398031808, 'subsample': 0.9950099214501411, 'colsample_bytree': 0.6478698683834716, 'min_child_weight': 3, 'gamma': 0.5007054000428385, 'patience': 5}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:35,16,59,XGBoost,0.7132,0.8431,0.7643,0.6685,166,15,0.003943,0.97233,0.978802,5,0.625296,165,2,0.34,0.31,0.7199,33,0.6616,0.8173,0.6641,0.6591,0.0516,False,OK

[I 2026-07-09 14:11:35,463] Trial 59 finished with value: 0.7132243684992571 and parameters: {'n_estimators': 166, 'max_depth': 15, 'learning_rate': 0.003942724773556051, 'subsample': 0.9723300042787992, 'colsample_bytree': 0.9788023110946492, 'min_child_weight': 5, 'gamma': 0.6252962192460763, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:35,16,60,XGBoost,0.7093,0.8467,0.7771,0.6524,123,9,0.004887,0.810648,0.947424,5,0.983833,122,2,0.32,0.3,0.7199,33,0.665,0.8196,0.6921,0.64,0.0443,False,OK

[I 2026-07-09 14:11:35,895] Trial 60 finished with value: 0.7093023255813954 and parameters: {'n_estimators': 123, 'max_depth': 9, 'learning_rate': 0.004887489026157461, 'subsample': 0.8106478835199792, 'colsample_bytree': 0.9474244667180053, 'min_child_weight': 5, 'gamma': 0.9838331495887017, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:36,16,61,XGBoost,0.7108,0.8455,0.7357,0.6875,94,9,0.002414,0.901675,0.904012,6,0.889721,93,2,0.34,0.31,0.7199,33,0.6562,0.8217,0.6361,0.6775,0.0546,False,OK

[I 2026-07-09 14:11:36,330] Trial 61 finished with value: 0.7107692307692308 and parameters: {'n_estimators': 94, 'max_depth': 9, 'learning_rate': 0.002413821957551575, 'subsample': 0.9016750809474214, 'colsample_bytree': 0.904012237224665, 'min_child_weight': 6, 'gamma': 0.8897211288816813, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:36,16,62,XGBoost,0.7105,0.8409,0.7739,0.6568,52,8,0.002644,0.988187,0.849486,5,0.393343,51,2,0.32,0.31,0.7199,33,0.6675,0.8196,0.6997,0.6381,0.0431,False,OK

[I 2026-07-09 14:11:36,682] Trial 62 finished with value: 0.7105263157894737 and parameters: {'n_estimators': 52, 'max_depth': 8, 'learning_rate': 0.0026438987331127844, 'subsample': 0.9881870114791981, 'colsample_bytree': 0.8494857892188983, 'min_child_weight': 5, 'gamma': 0.39334317901257637, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:37,16,63,XGBoost,0.7149,0.8451,0.7548,0.6791,54,6,0.023551,0.975899,0.956185,7,0.962725,53,3,0.34,0.29,0.7199,33,0.6734,0.8204,0.6768,0.67,0.0415,False,OK

[I 2026-07-09 14:11:37,028] Trial 63 finished with value: 0.7149321266968326 and parameters: {'n_estimators': 54, 'max_depth': 6, 'learning_rate': 0.023550797085814628, 'subsample': 0.9758993918540779, 'colsample_bytree': 0.9561853214508047, 'min_child_weight': 7, 'gamma': 0.9627246801626459, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:37,16,64,XGBoost,0.7118,0.8444,0.7707,0.6612,53,8,0.031748,0.937397,0.893122,8,0.921662,52,4,0.32,0.29,0.7199,33,0.6675,0.8182,0.687,0.649,0.0443,False,OK

[I 2026-07-09 14:11:37,379] Trial 64 finished with value: 0.711764705882353 and parameters: {'n_estimators': 53, 'max_depth': 8, 'learning_rate': 0.031748420201959816, 'subsample': 0.9373965766602718, 'colsample_bytree': 0.8931215140043145, 'min_child_weight': 8, 'gamma': 0.9216622791155598, 'patience': 4}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:37,16,65,XGBoost,0.7125,0.8415,0.742,0.6853,149,5,0.012235,0.982168,0.934643,7,0.87021,148,2,0.36,0.3,0.7199,33,0.6641,0.8241,0.6489,0.68,0.0485,False,OK

[I 2026-07-09 14:11:37,810] Trial 65 finished with value: 0.7125382262996942 and parameters: {'n_estimators': 149, 'max_depth': 5, 'learning_rate': 0.012235120896847673, 'subsample': 0.9821680622660284, 'colsample_bytree': 0.9346428228691879, 'min_child_weight': 7, 'gamma': 0.8702101072815057, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:38,16,66,XGBoost,0.7134,0.8423,0.7452,0.6842,60,8,0.036905,0.985523,0.998157,7,0.866624,59,2,0.39,0.32,0.7199,33,0.6632,0.8195,0.6514,0.6755,0.0502,False,OK

[I 2026-07-09 14:11:38,165] Trial 66 finished with value: 0.7134146341463414 and parameters: {'n_estimators': 60, 'max_depth': 8, 'learning_rate': 0.036905411298846356, 'subsample': 0.9855232327386734, 'colsample_bytree': 0.9981571408499091, 'min_child_weight': 7, 'gamma': 0.8666240621415037, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:38,16,67,XGBoost,0.7046,0.8444,0.7293,0.6815,210,13,0.004833,0.703871,0.609759,8,0.894793,209,5,0.38,0.35,0.7199,33,0.664,0.8247,0.6438,0.6856,0.0406,False,OK

[I 2026-07-09 14:11:38,729] Trial 67 finished with value: 0.7046153846153846 and parameters: {'n_estimators': 210, 'max_depth': 13, 'learning_rate': 0.004833321780078906, 'subsample': 0.7038714741996794, 'colsample_bytree': 0.6097592249605399, 'min_child_weight': 8, 'gamma': 0.8947933742347303, 'patience': 5}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:39,16,68,XGBoost,0.6936,0.8309,0.7643,0.6349,80,2,0.022195,0.937232,0.927465,5,0.954495,79,3,0.32,0.31,0.7199,33,0.6909,0.8206,0.7252,0.6597,0.0027,False,OK

[I 2026-07-09 14:11:39,054] Trial 68 finished with value: 0.6936416184971098 and parameters: {'n_estimators': 80, 'max_depth': 2, 'learning_rate': 0.022194819833777937, 'subsample': 0.9372321536557612, 'colsample_bytree': 0.9274648925827975, 'min_child_weight': 5, 'gamma': 0.9544950878017232, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:39,16,69,XGBoost,0.7136,0.8419,0.758,0.6742,77,7,0.007195,0.837827,0.983335,8,0.955918,76,3,0.33,0.31,0.7199,33,0.6641,0.8208,0.6667,0.6616,0.0495,False,OK

[I 2026-07-09 14:11:39,428] Trial 69 finished with value: 0.7136431784107946 and parameters: {'n_estimators': 77, 'max_depth': 7, 'learning_rate': 0.007194990267818137, 'subsample': 0.8378270788961917, 'colsample_bytree': 0.9833346113214224, 'min_child_weight': 8, 'gamma': 0.9559177424043049, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:39,16,70,XGBoost,0.7091,0.8451,0.7452,0.6763,91,12,0.006184,0.795621,0.961856,6,0.890661,90,4,0.34,0.3,0.7199,33,0.6675,0.8196,0.6565,0.6789,0.0416,False,OK

[I 2026-07-09 14:11:39,831] Trial 70 finished with value: 0.7090909090909091 and parameters: {'n_estimators': 91, 'max_depth': 12, 'learning_rate': 0.006184414639989298, 'subsample': 0.7956207519723247, 'colsample_bytree': 0.9618557756438607, 'min_child_weight': 6, 'gamma': 0.8906611039308072, 'patience': 4}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:40,16,71,XGBoost,0.6775,0.8214,0.7325,0.6301,55,2,0.018684,0.791216,0.996236,6,0.917201,54,2,0.32,0.32,0.7199,33,0.6791,0.813,0.6972,0.6618,-0.0016,False,OK

[I 2026-07-09 14:11:40,172] Trial 71 finished with value: 0.6774668630338734 and parameters: {'n_estimators': 55, 'max_depth': 2, 'learning_rate': 0.018683701722784465, 'subsample': 0.7912157367926317, 'colsample_bytree': 0.99623623555236, 'min_child_weight': 6, 'gamma': 0.9172010568302501, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:40,16,72,XGBoost,0.7091,0.8441,0.7452,0.6763,140,9,0.001569,0.898717,0.994442,6,0.661902,139,2,0.33,0.31,0.7199,33,0.6641,0.8186,0.6539,0.6745,0.045,False,OK

[I 2026-07-09 14:11:40,643] Trial 72 finished with value: 0.7090909090909091 and parameters: {'n_estimators': 140, 'max_depth': 9, 'learning_rate': 0.0015692729268608143, 'subsample': 0.8987170906427587, 'colsample_bytree': 0.9944418500109538, 'min_child_weight': 6, 'gamma': 0.6619016892441186, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:40,16,73,XGBoost,0.7141,0.8423,0.7516,0.6801,61,6,0.010115,0.853346,0.965516,8,0.739405,60,3,0.34,0.3,0.7199,33,0.6606,0.8225,0.6489,0.6728,0.0534,False,OK

[I 2026-07-09 14:11:40,994] Trial 73 finished with value: 0.7140695915279879 and parameters: {'n_estimators': 61, 'max_depth': 6, 'learning_rate': 0.010115194823082981, 'subsample': 0.8533461627674506, 'colsample_bytree': 0.9655157592929346, 'min_child_weight': 8, 'gamma': 0.7394052278497967, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:41,16,74,XGBoost,0.6974,0.8368,0.7962,0.6203,59,3,0.028972,0.839913,0.973337,10,0.88362,58,3,0.26,0.28,0.7199,33,0.6892,0.8251,0.7532,0.6352,0.0082,False,OK

[I 2026-07-09 14:11:41,323] Trial 74 finished with value: 0.697350069735007 and parameters: {'n_estimators': 59, 'max_depth': 3, 'learning_rate': 0.028972020967827423, 'subsample': 0.8399134989622297, 'colsample_bytree': 0.9733373069497882, 'min_child_weight': 10, 'gamma': 0.8836197029603591, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:41,16,75,XGBoost,0.7117,0.8432,0.7548,0.6733,114,10,0.003292,0.903027,0.93785,10,0.643912,113,3,0.33,0.31,0.7199,33,0.6717,0.8204,0.6794,0.6642,0.04,False,OK

[I 2026-07-09 14:11:41,794] Trial 75 finished with value: 0.7117117117117117 and parameters: {'n_estimators': 114, 'max_depth': 10, 'learning_rate': 0.003292077566022885, 'subsample': 0.9030268445660589, 'colsample_bytree': 0.9378502638219324, 'min_child_weight': 10, 'gamma': 0.6439116429769866, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:42,16,76,XGBoost,0.7083,0.8445,0.758,0.6648,120,9,0.055285,0.822416,0.979652,6,0.684126,64,4,0.34,0.35,0.7199,33,0.6823,0.8209,0.7023,0.6635,0.026,False,OK

[I 2026-07-09 14:11:42,169] Trial 76 finished with value: 0.7083333333333334 and parameters: {'n_estimators': 120, 'max_depth': 9, 'learning_rate': 0.05528502671119891, 'subsample': 0.8224163118493252, 'colsample_bytree': 0.9796524972465293, 'min_child_weight': 6, 'gamma': 0.6841261576615694, 'patience': 4}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:42,16,77,XGBoost,0.7104,0.8433,0.742,0.6813,91,6,0.007148,0.856853,0.919841,8,0.94111,90,3,0.35,0.31,0.7199,33,0.6597,0.8235,0.6412,0.6792,0.0507,False,OK

[I 2026-07-09 14:11:42,543] Trial 77 finished with value: 0.7103658536585366 and parameters: {'n_estimators': 91, 'max_depth': 6, 'learning_rate': 0.007147900856643382, 'subsample': 0.8568528563173535, 'colsample_bytree': 0.9198409430412868, 'min_child_weight': 8, 'gamma': 0.9411099110749699, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:43,16,78,XGBoost,0.7092,0.8449,0.7611,0.6639,406,7,0.014865,0.549345,0.95502,4,0.111891,171,2,0.33,0.31,0.7199,33,0.6832,0.8246,0.7023,0.6651,0.026,False,OK

[I 2026-07-09 14:11:43,017] Trial 78 finished with value: 0.7091988130563798 and parameters: {'n_estimators': 406, 'max_depth': 7, 'learning_rate': 0.014864937806802684, 'subsample': 0.549344720427038, 'colsample_bytree': 0.9550200187953907, 'min_child_weight': 4, 'gamma': 0.11189128355756855, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:43,16,79,XGBoost,0.7145,0.8507,0.7293,0.7003,64,5,0.072303,0.612309,0.526411,2,0.999788,61,2,0.43,0.33,0.7199,33,0.664,0.8298,0.6387,0.6915,0.0505,False,OK

[I 2026-07-09 14:11:43,385] Trial 79 finished with value: 0.7145085803432137 and parameters: {'n_estimators': 64, 'max_depth': 5, 'learning_rate': 0.07230306253074964, 'subsample': 0.6123089352692415, 'colsample_bytree': 0.5264109400254153, 'min_child_weight': 2, 'gamma': 0.999788075651773, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:43,16,80,XGBoost,0.7032,0.8487,0.7357,0.6735,100,5,0.072054,0.74518,0.566712,3,0.889343,69,3,0.39,0.33,0.7199,33,0.6667,0.8271,0.6565,0.6772,0.0365,False,OK

[I 2026-07-09 14:11:43,732] Trial 80 finished with value: 0.7031963470319634 and parameters: {'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.07205404756747776, 'subsample': 0.7451800120795037, 'colsample_bytree': 0.5667119131674114, 'min_child_weight': 3, 'gamma': 0.88934268869969, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:44,16,81,XGBoost,0.7061,0.8442,0.742,0.6734,357,11,0.005306,0.900398,0.664248,6,0.258252,356,2,0.36,0.28,0.7199,33,0.6667,0.8213,0.6616,0.6718,0.0394,False,OK

[I 2026-07-09 14:11:44,498] Trial 81 finished with value: 0.706060606060606 and parameters: {'n_estimators': 357, 'max_depth': 11, 'learning_rate': 0.005305994361868116, 'subsample': 0.9003978017670281, 'colsample_bytree': 0.6642476160347118, 'min_child_weight': 6, 'gamma': 0.258251520403896, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:44,16,82,XGBoost,0.7002,0.8459,0.7325,0.6706,52,6,0.0361,0.54598,0.5173,2,0.867939,51,2,0.37,0.35,0.7199,33,0.6667,0.824,0.6565,0.6772,0.0335,False,OK

[I 2026-07-09 14:11:44,879] Trial 82 finished with value: 0.700152207001522 and parameters: {'n_estimators': 52, 'max_depth': 6, 'learning_rate': 0.036099688732943155, 'subsample': 0.5459798612819136, 'colsample_bytree': 0.5173000732289619, 'min_child_weight': 2, 'gamma': 0.8679387125798017, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:45,16,83,XGBoost,0.7068,0.8453,0.7293,0.6856,116,4,0.081408,0.595099,0.646446,3,0.972295,44,2,0.43,0.31,0.7199,33,0.6569,0.8269,0.6285,0.688,0.0499,False,OK

[I 2026-07-09 14:11:45,208] Trial 83 finished with value: 0.7067901234567902 and parameters: {'n_estimators': 116, 'max_depth': 4, 'learning_rate': 0.08140813487128089, 'subsample': 0.5950987143249779, 'colsample_bytree': 0.6464455480872227, 'min_child_weight': 3, 'gamma': 0.9722949863403783, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:46,16,84,XGBoost,0.7154,0.8423,0.7643,0.6723,55,9,0.007995,0.988125,0.998316,5,0.952974,54,2,0.33,0.31,0.7199,33,0.6675,0.8185,0.6743,0.6608,0.0478,False,OK

[I 2026-07-09 14:11:46,629] Trial 84 finished with value: 0.7153502235469449 and parameters: {'n_estimators': 55, 'max_depth': 9, 'learning_rate': 0.007994878575529685, 'subsample': 0.9881245724962981, 'colsample_bytree': 0.9983162089292438, 'min_child_weight': 5, 'gamma': 0.9529742216002096, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:47,16,85,XGBoost,0.7012,0.8412,0.7325,0.6725,87,4,0.206654,0.64458,0.506199,4,0.933637,15,2,0.41,0.33,0.7199,33,0.6684,0.8234,0.6565,0.6807,0.0328,False,OK

[I 2026-07-09 14:11:47,755] Trial 85 finished with value: 0.7012195121951219 and parameters: {'n_estimators': 87, 'max_depth': 4, 'learning_rate': 0.2066544635052424, 'subsample': 0.644579815155847, 'colsample_bytree': 0.506199330825439, 'min_child_weight': 4, 'gamma': 0.9336369569860672, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:48,16,86,XGBoost,0.7084,0.8458,0.7389,0.6804,145,6,0.006271,0.853923,0.885515,7,0.486502,144,4,0.35,0.31,0.7199,33,0.6615,0.8225,0.6463,0.6773,0.0469,False,OK

[I 2026-07-09 14:11:48,482] Trial 86 finished with value: 0.7083969465648855 and parameters: {'n_estimators': 145, 'max_depth': 6, 'learning_rate': 0.006271113410174632, 'subsample': 0.8539233150780997, 'colsample_bytree': 0.8855146132558037, 'min_child_weight': 7, 'gamma': 0.48650217025694814, 'patience': 4}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:48,16,87,XGBoost,0.7143,0.843,0.7643,0.6704,56,12,0.006902,0.976044,0.89384,5,0.881268,55,2,0.33,0.32,0.7199,33,0.6709,0.8206,0.6794,0.6625,0.0434,False,OK

[I 2026-07-09 14:11:48,858] Trial 87 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 56, 'max_depth': 12, 'learning_rate': 0.006901529391167884, 'subsample': 0.9760440608649334, 'colsample_bytree': 0.8938396027488197, 'min_child_weight': 5, 'gamma': 0.8812676004431418, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:49,16,88,XGBoost,0.7113,0.8472,0.7611,0.6676,88,16,0.012711,0.883036,0.887215,4,0.974801,87,3,0.34,0.28,0.7199,33,0.6708,0.8192,0.6819,0.6601,0.0405,False,OK

[I 2026-07-09 14:11:49,284] Trial 88 finished with value: 0.7113095238095238 and parameters: {'n_estimators': 88, 'max_depth': 16, 'learning_rate': 0.01271118536975847, 'subsample': 0.8830364046583971, 'colsample_bytree': 0.8872147546548977, 'min_child_weight': 4, 'gamma': 0.9748011375527597, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:49,16,89,XGBoost,0.7147,0.8426,0.758,0.6761,59,10,0.010701,0.970325,0.981725,5,0.779506,58,2,0.34,0.32,0.7199,33,0.665,0.8172,0.6641,0.6658,0.0497,False,OK

[I 2026-07-09 14:11:49,663] Trial 89 finished with value: 0.7147147147147147 and parameters: {'n_estimators': 59, 'max_depth': 10, 'learning_rate': 0.01070121566011614, 'subsample': 0.9703246219579709, 'colsample_bytree': 0.9817246989942271, 'min_child_weight': 5, 'gamma': 0.7795061637949134, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:50,16,90,XGBoost,0.7094,0.8477,0.758,0.6667,95,8,0.041497,0.927057,0.983598,5,0.948657,93,3,0.34,0.32,0.7199,33,0.6625,0.8214,0.6718,0.6535,0.0469,False,OK

[I 2026-07-09 14:11:50,099] Trial 90 finished with value: 0.7093889716840537 and parameters: {'n_estimators': 95, 'max_depth': 8, 'learning_rate': 0.04149697466585654, 'subsample': 0.9270566295044016, 'colsample_bytree': 0.9835975594724838, 'min_child_weight': 5, 'gamma': 0.948657265542722, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:50,16,91,XGBoost,0.7143,0.8437,0.7643,0.6704,73,9,0.014428,0.985517,0.928945,5,0.784728,72,2,0.34,0.3,0.7199,33,0.6641,0.8188,0.6667,0.6616,0.0502,False,OK

[I 2026-07-09 14:11:50,486] Trial 91 finished with value: 0.7142857142857143 and parameters: {'n_estimators': 73, 'max_depth': 9, 'learning_rate': 0.014427574155563458, 'subsample': 0.9855167366601012, 'colsample_bytree': 0.9289448176192877, 'min_child_weight': 5, 'gamma': 0.7847277036030716, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:50,16,92,XGBoost,0.7064,0.8477,0.7548,0.6639,59,9,0.013768,0.986573,0.80689,2,0.931514,58,3,0.33,0.29,0.7199,33,0.6733,0.8189,0.6896,0.6578,0.0331,False,OK

[I 2026-07-09 14:11:50,870] Trial 92 finished with value: 0.706408345752608 and parameters: {'n_estimators': 59, 'max_depth': 9, 'learning_rate': 0.01376846841405391, 'subsample': 0.9865732226719796, 'colsample_bytree': 0.806889752180741, 'min_child_weight': 2, 'gamma': 0.9315140499475356, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:51,16,93,XGBoost,0.7122,0.8443,0.7643,0.6667,56,12,0.006622,0.969576,0.962467,3,0.811008,55,2,0.34,0.31,0.7199,33,0.6582,0.8112,0.6616,0.6549,0.0539,False,OK

[I 2026-07-09 14:11:51,277] Trial 93 finished with value: 0.712166172106825 and parameters: {'n_estimators': 56, 'max_depth': 12, 'learning_rate': 0.006622374908493852, 'subsample': 0.969576329034649, 'colsample_bytree': 0.9624666433057667, 'min_child_weight': 3, 'gamma': 0.8110077582828759, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:51,16,94,XGBoost,0.7052,0.8473,0.758,0.6593,123,10,0.004594,0.990406,0.788866,4,0.923349,122,2,0.33,0.31,0.7199,33,0.6667,0.819,0.687,0.6475,0.0385,False,OK

[I 2026-07-09 14:11:51,762] Trial 94 finished with value: 0.7051851851851851 and parameters: {'n_estimators': 123, 'max_depth': 10, 'learning_rate': 0.0045944200266467145, 'subsample': 0.990405955389297, 'colsample_bytree': 0.7888664458904304, 'min_child_weight': 4, 'gamma': 0.9233492913455822, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:52,16,95,XGBoost,0.7106,0.8422,0.7548,0.6714,98,9,0.00248,0.973556,0.97306,5,0.722392,97,2,0.33,0.31,0.7199,33,0.6581,0.8174,0.6539,0.6624,0.0525,False,OK

[I 2026-07-09 14:11:52,209] Trial 95 finished with value: 0.7106446776611695 and parameters: {'n_estimators': 98, 'max_depth': 9, 'learning_rate': 0.0024798448727557246, 'subsample': 0.9735557109686503, 'colsample_bytree': 0.9730596551315897, 'min_child_weight': 5, 'gamma': 0.7223922240988069, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:52,16,96,XGBoost,0.7101,0.8449,0.7293,0.6918,77,11,0.007756,0.955076,0.97016,6,0.929023,76,2,0.38,0.3,0.7199,33,0.6588,0.8176,0.6361,0.6831,0.0513,False,OK

[I 2026-07-09 14:11:52,604] Trial 96 finished with value: 0.710077519379845 and parameters: {'n_estimators': 77, 'max_depth': 11, 'learning_rate': 0.007756153832131997, 'subsample': 0.9550755329979939, 'colsample_bytree': 0.9701598304784653, 'min_child_weight': 6, 'gamma': 0.9290228109335755, 'patience': 2}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:53,16,97,XGBoost,0.7099,0.8461,0.7675,0.6603,486,19,0.005677,0.695513,0.941774,8,0.389276,485,3,0.32,0.35,0.7199,33,0.6756,0.8236,0.7048,0.6487,0.0343,False,OK

[I 2026-07-09 14:11:53,558] Trial 97 finished with value: 0.7098674521354934 and parameters: {'n_estimators': 486, 'max_depth': 19, 'learning_rate': 0.005676524032106958, 'subsample': 0.6955127391625251, 'colsample_bytree': 0.941774336092138, 'min_child_weight': 8, 'gamma': 0.3892756711268557, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:53,16,98,XGBoost,0.7051,0.8446,0.7006,0.7097,182,12,0.094781,0.551814,0.500595,4,0.923764,35,3,0.48,0.34,0.7199,33,0.6475,0.8257,0.6005,0.7024,0.0577,False,OK

[I 2026-07-09 14:11:53,900] Trial 98 finished with value: 0.7051282051282052 and parameters: {'n_estimators': 182, 'max_depth': 12, 'learning_rate': 0.09478055032117362, 'subsample': 0.5518135216569898, 'colsample_bytree': 0.5005950736557381, 'min_child_weight': 4, 'gamma': 0.9237639308949139, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:54,16,99,XGBoost,0.6994,0.84,0.7707,0.6402,253,14,0.274568,0.514665,0.879944,4,0.821384,9,3,0.33,0.28,0.7199,33,0.6778,0.8214,0.7226,0.6382,0.0216,False,OK

[I 2026-07-09 14:11:54,236] Trial 99 finished with value: 0.6994219653179191 and parameters: {'n_estimators': 253, 'max_depth': 14, 'learning_rate': 0.2745681519901021, 'subsample': 0.5146651014645731, 'colsample_bytree': 0.8799436277369026, 'min_child_weight': 4, 'gamma': 0.8213839443098998, 'patience': 3}. Best is trial 33 with value: 0.7198795180722891.

\n============================================================
🎉 XGB NAS COMPLETE
============================================================
Best Trial: 33
Best F1: 0.7199
Best Params: {'n_estimators': 148, 'max_depth': 6, 'learning_rate': 0.004120366431974378, 'subsample': 0.917587357439022, 'colsample_bytree': 0.9722115190446639, 'min_child_weight': 6, 'gamma': 0.7723114844653445, 'patience': 2}
💾 Saved: nas_rf_results.csv, nas_xgb_results.csv
💾 Saved: nas_rf_trial_log.csv, nas_xgb_trial_log.csv

============================================================
📋 NAS RESULTS COMPARISON
============================================================

Model           Best Val F1  Best Trial
----------------------------------------
RandomForest    0.7110       79
XGBoost         0.7199       33

📊 Best RF Params:
   n_estimators: 59
   max_depth: 7
   min_samples_split: 7
   min_samples_leaf: 5

📊 Best XGB Params:
   n_estimators: 148
   max_depth: 6
   learning_rate: 0.004120366431974378
   subsample: 0.917587357439022
   colsample_bytree: 0.9722115190446639
   min_child_weight: 6
   gamma: 0.7723114844653445
   patience: 2

📊 RF Trial Log (sorted by val_f1):

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,min_samples_split,min_samples_leaf,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:10:46,16,79,RandomForest,0.7110,0.8426,0.7484,0.6772,59,7,7,5,0.38,0.30,0.7110,79,0.6649,0.8196,0.6539,0.6763,0.0461,False,OK
1,2026-07-09,14:10:10,16,40,RandomForest,0.7104,0.8444,0.7420,0.6813,298,17,7,10,0.40,0.33,0.7104,40,0.6727,0.8215,0.6616,0.6842,0.0377,False,OK
2,2026-07-09,14:10:11,16,41,RandomForest,0.7104,0.8446,0.7420,0.6813,297,19,7,10,0.40,0.33,0.7104,40,0.6727,0.8218,0.6616,0.6842,0.0377,False,OK
3,2026-07-09,14:10:19,16,48,RandomForest,0.7104,0.8445,0.7420,0.6813,349,19,10,10,0.40,0.27,0.7104,40,0.6710,0.8211,0.6616,0.6806,0.0394,False,OK
4,2026-07-09,14:10:16,16,46,RandomForest,0.7104,0.8445,0.7420,0.6813,277,20,7,10,0.40,0.31,0.7104,40,0.6718,0.8212,0.6616,0.6824,0.0385,False,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026-07-09,14:10:44,16,76,RandomForest,0.6512,0.8202,0.7580,0.5707,94,3,2,3,0.33,0.21,0.7104,40,0.6266,0.8001,0.6896,0.5742,0.0246,False,OK
96,2026-07-09,14:11:00,16,97,RandomForest,0.6501,0.8129,0.7484,0.5746,192,2,13,2,0.37,0.22,0.7110,79,0.6233,0.7927,0.6819,0.5739,0.0268,False,OK
97,2026-07-09,14:10:18,16,47,RandomForest,0.6496,0.8151,0.7293,0.5857,468,2,12,2,0.39,0.22,0.7104,40,0.6268,0.7935,0.6667,0.5914,0.0229,False,OK
98,2026-07-09,14:10:08,16,38,RandomForest,0.6487,0.8129,0.7293,0.5842,177,2,6,1,0.38,0.37,0.7093,6,0.6244,0.7930,0.6641,0.5892,0.0243,False,OK
99,2026-07-09,14:10:52,16,87,RandomForest,0.6485,0.8070,0.7197,0.5901,62,2,6,7,0.38,0.21,0.7110,79,0.6233,0.7879,0.6590,0.5913,0.0251,False,OK

📊 XGB Trial Log (sorted by val_f1):

,date,time,seq_length,trial_id,model,val_f1,val_auc,val_recall,val_precision,n_estimators,max_depth,learning_rate,subsample,colsample_bytree,min_child_weight,gamma,actual_trees,patience,val_threshold,best_test_threshold,best_val_so_far,best_trial_id,test_f1,test_auc,test_recall,test_precision,gap_val_test,is_enqueued,status
0,2026-07-09,14:11:21,16,33,XGBoost,0.7199,0.8465,0.7611,0.6829,148,6,0.004120,0.917587,0.972212,6,0.772311,147,2,0.33,0.29,0.7199,33,0.6641,0.8219,0.6590,0.6693,0.0558,False,OK
1,2026-07-09,14:11:21,16,32,XGBoost,0.7177,0.8452,0.7611,0.6790,121,6,0.004361,0.968151,0.987640,6,0.919729,120,2,0.33,0.31,0.7177,32,0.6718,0.8209,0.6692,0.6744,0.0459,False,OK
2,2026-07-09,14:11:27,16,46,XGBoost,0.7160,0.8454,0.7548,0.6810,75,6,0.006462,0.874108,0.938471,6,0.958746,74,2,0.33,0.31,0.7199,33,0.6589,0.8243,0.6489,0.6693,0.0571,False,OK
3,2026-07-09,14:11:46,16,84,XGBoost,0.7154,0.8423,0.7643,0.6723,55,9,0.007995,0.988125,0.998316,5,0.952974,54,2,0.33,0.31,0.7199,33,0.6675,0.8185,0.6743,0.6608,0.0478,False,OK
4,2026-07-09,14:11:23,16,37,XGBoost,0.7149,0.8471,0.7707,0.6667,91,8,0.007779,0.951652,0.960332,6,0.876277,90,2,0.32,0.29,0.7199,33,0.6683,0.8176,0.6921,0.6461,0.0466,False,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026-07-09,14:11:31,16,56,XGBoost,0.6878,0.8278,0.7611,0.6273,109,3,0.002440,0.926061,0.854098,7,0.884463,108,2,0.32,0.32,0.7199,33,0.6906,0.8180,0.7328,0.6531,-0.0029,False,OK
96,2026-07-09,14:11:40,16,71,XGBoost,0.6775,0.8214,0.7325,0.6301,55,2,0.018684,0.791216,0.996236,6,0.917201,54,2,0.32,0.32,0.7199,33,0.6791,0.8130,0.6972,0.6618,-0.0016,False,OK
97,2026-07-09,14:11:29,16,51,XGBoost,0.6765,0.8168,0.7325,0.6284,258,2,0.001733,0.987565,0.942849,5,0.794055,257,2,0.31,0.31,0.7199,33,0.6782,0.8114,0.6972,0.6602,-0.0017,False,OK
98,2026-07-09,14:11:22,16,34,XGBoost,0.6627,0.8181,0.7038,0.6261,115,2,0.002352,0.872404,0.983510,10,0.972514,114,2,0.32,0.32,0.7199,33,0.6725,0.8114,0.6819,0.6634,-0.0099,False,OK
99,2026-07-09,14:11:30,16,53,XGBoost,0.6627,0.8194,0.7038,0.6261,119,2,0.002219,0.803497,0.926480,6,0.957565,118,3,0.33,0.33,0.7199,33,0.6758,0.8141,0.6870,0.6650,-0.0132,False,OK

#freeze

In [22]:
%pip freeze > "{project_path}requirement/freez/NASEnhancedPretraindMLModleAdvance-lock.txt"

In [23]:
end = time.time()
elapsed = end - start_time

hours = int(elapsed // 3600)
minutes = int((elapsed % 3600) // 60)
seconds = int(elapsed % 60)

print(f"Total Time = {hours}h {minutes}m {seconds}s")

Total Time = 0h 6m 42s